### ISSUE TITLE
/etc/rc.d/rc.sysinit, in testing branch, missing messages on the console?

### ISSUE THREAD

**Issue by gyrog** [puppylinux-woof-CE/woof-CE#1004]
Has anyone else seen this issue?
The green "done" message for the "Performing a 'switch_root' to the layered filesystem..." message,
and the "Making the filesystem usable...", are both missing from the console display.
The result looks Ok, but the status on the end of the "Performing a 'switch_root' to the layered filesystem..." line actually belongs to the missing "Making the filesystem usable..." line.

On my system, moving the mount of devtmpfs up to the beginning of "MAIN", fixes the problem.

**Comment by wdlkmpx** [comment]
Hmm i haven't paid much attention to it, but there's something odd
indeed (as far as i remember) .. you might want to test that change in
a full install and commit it...<div
id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br /> <table
style="border-top: 1px solid #D3D4DE;">
	<tr>
      <td style="width: 55px; padding-top: 18px;"><a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank"><img
src="https://ipmcdn.avast.com/images/icons/icon-envelope-tick-round-orange-animated-no-repeat-v1.gif"
width="46" height="29" style="width: 46px; height: 29px;" /></a></td>
		<td style="width: 470px; padding-top: 17px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Libre de virus. <a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avast.com</a> 		</td>
	</tr>
</table>
<a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>

**Comment by gyrog** [comment]
You can see it clearly if you temporarily add a "sleep" just before the "##LOAD SWAP##" line.
I've never done a full install of any Puppy.

**Comment by gyrog** [comment]
I've created a new fork and updated rc.sysinit there. Here is the URL:
[https://github.com/gyrog/woof-CE/raw/39d00824c72001721f39662e3aabfff085f1f2c7/woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit](url)
I could do a pull request.

**Comment by gyrog** [comment]
I've tested this change in a full-install of tahr_6.0.6 on an ext3 partition on a usb hd, and it did not seem to create any issues. Although it doesn't seem to be necessary on the full-install.
Since it seems to be sfe, I will push the fix to woof-ce/testing soon.

**Comment by peabee** [comment]
Tested as a ydrv patch ona frugal install....saw message:
> Making the filesystem usable...

**Comment by gyrog** [comment]
Thanks peabee.
I've pushed the patch to testing, so I'm closing this issue.
