### ISSUE TITLE
full-install fails with read-only filesystem??

### ISSUE THREAD

**Issue by gyrog** [puppylinux-woof-CE/woof-CE#1006]
Has anyone else seen this problem?
I have been testing the latest tahrpup, xenialpup and lxpupsc as a full-install, using an ext3 partition on a usb hd.
All of them failed to boot properly, with lots of error mesages complaining about the filesystem being read-only, and ending with a console prompt. (Entering "reboot", got me out of there.)
The problem is that the "mount -o remount ,rw" of "/", early in rc.sysinit, fails.
I have found 2 workarounds:
1) Include "rw" as a boot parameter.
2) Patch rc.sysinit to include the device name of the partition in the "mount -o remount,rw" command.
I have a patch for 2) but I haven't pushed it to "testing".

**Comment by wdlkmpx** [comment]
Last time a i tested a full install was.. months ago. It was broken, but I guess it got broken again. I had a precise install and a slacko 700 install. It was a bit tricky as one of those was not booting to desktop and showing a read-only fs error. 

A full install is only useful when the ram is too low and the cpu is too slow... and for arm builds. It should be disabled in the puppyinstaller or maybe we should put a giant warning. Many people think a full install is better than a frugal install, and that's wrong.

But besides that it's good to test a full install and fix stuff.

**Comment by gyrog** [comment]
Since it's not just me, I will push a patch of rc.sysiniit to "testing" that overcomes the read-only fs error.
However I have an idea that would make it conditional, but I will test this before pushing.

I agree with your asesment of full-install, but it's still there, and some folk use it.

Perhaps a better solution for low ram is to use a normal frugal install with "pfix=nocopy".

**Comment by gyrog** [comment]
Since I'm not sure if the old remount commands still work sometimes, I going to push a patch that leaves the old remount commands in place, but if they fail, executes a different variatiation of the remount command, one that works in the cases I have tested.

**Comment by gyrog** [comment]
patch pushed to "testing"
