### ISSUE TITLE
Critical bug in /usr/local/pup_event/frontend_funcs

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1013]
This bug affects `pupmode 13` (and probably 7) .

I noticed this in `/tmp/xerrs.log` on a FAT32 usb install of the latest slacko beta:

```
/usr/local/pup_event/frontend_funcs: line 451: [: too many arguments
/usr/local/pup_event/frontend_funcs: line 459: [: -lt: unary operator expected
```

Looking at that output it is reasonable to assume that there are/is (an) empty variable(s) causing the error. I tracked it down to `SIZETMPM`, (`df -m | grep ' /initrd/pup_rw$' | tr -s ' ' | cut -f 4 -d ' '`).  This doesn't work with the new init because `/initrd/pup_rw` is an absolute link to `/initrd/mnt/tmpfs/pup_rw`, which in turn is not a mount point so doesn't show up when `df` is called.

From the `README.init` document...

>   * If all files are present we end up with a stack that looks like this:
tmpfs        read-write
adrv...sfs   read-only
ydrv...sfs   read-only
puppy...sfs  read-only
fdrv...sfs   read-only
zdrv...sfs   read-only
(snip)
> * If the boot is considered to be from a "flash" device, the directory containing the save layer
is inserted as a read-only layer immediately below the read-write layer.
> * Otherwise the tmpfs read-write layer is replaced with the directory
containing the save layer as the read-write layer.

By that rationale, if `/initrd/pup_rw` is a symlink then we should be grepping for `/initrd/mnt/tmpfs$` to obtain the `SIZETMPM` variable.

I propose this diff:

```patch
--- frontend_funcs.orig	2017-04-29 16:50:19.623266816 +1000
+++ frontend_funcs	2017-05-20 08:07:35.177360705 +1000
@@ -445,9 +445,14 @@ free_flash_func() { #PUPMODE 3,7,13. cal
  else
   SIZEFREEM=`df -m | grep ' /initrd/pup_ro1$' | tr -s ' ' | cut -f 4 -d ' '`
  fi
- SIZETMPM=`df -m | grep ' /initrd/pup_rw$' | tr -s ' ' | cut -f 4 -d ' '`
+ if [ -L /initrd/pup_rw ];then
+  SIZETMPM=`df -m | grep ' /initrd/mnt/tmpfs$' | tr -s ' ' | cut -f 4 -d ' '`
+ else
+  SIZETMPM=`df -m | grep ' /initrd/pup_rw$' | tr -s ' ' | cut -f 4 -d ' '`
+ fi
  [ -s /tmp/pup_event_sizefreem ] && PREVSIZEFREEM=`cat /tmp/pup_event_sizefreem`
  [ -s /tmp/pup_event_sizetmpm ] && PREVSIZETMPM=`cat /tmp/pup_event_sizetmpm`
+ [ -z "$PREVSIZETMPM" -o -z  "$SIZETMPM" ] && return #failsafe
  [ $PREVSIZEFREEM -eq $SIZEFREEM -a $PREVSIZETMPM -eq $SIZETMPM ] && return
  if [ $SIZEFREEM -lt 10 ];then
   if [ -d /initrd/pup_ro1/lib/modules/all-firmware -a "$ZDRVINIT" = "yes" ];then

```

Any comments?

**Comment by wdlkmpx** [comment]
I agree with the proposed solution.. There is also a bug in free_func. Both free_flash_func() and free_func() are called by frontend_timeout

**Comment by 01micko** [comment]
I think free_func() is ok. Well `SIZEFREEM` gets a value for me in pupmodes 12 and 13.

**Comment by wdlkmpx** [comment]
You're right .. i saw the same there's already an if statemente there.. i misread.

however the same bug appears to be in remasterpup2:

SIZETMPFSM="`df -m | grep '^tmpfs' | grep '/initrd/pup_rw' | tr -s " " | cut -f 4 -d " "`"

and shutdownconfig

[ "`mount | grep ' /initrd/pup_rw '`" != "" ] && DU_INITRD_PUP_RW=`du -B 1M -c /initrd/pup_rw |tail -n1 |awk '{print $1}'` #M=1024,MB=1000

**Comment by wdlkmpx** [comment]
Hmm i see i already addressed this issue in functions4puppy. I'll push a fix for the 3 affected files..

**Comment by 01micko** [comment]
Ok, was just going to look... :+1:

**Comment by gyrog** [comment]
Sorry I seem to be too late for this issue.
Wouldn't it be better to use a command that always gets the mount point no matter what "/initrd/pup_rw" is.
e.g. "stat -c %m $(readlink -f /initrd/pup_rw)"
While the current patch works now, future changes could easily break it.

**Comment by wdlkmpx** [comment]
Yes that is a better solution

**Comment by wdlkmpx** [comment]
Some scripts require the mountpoint to get some generic info. pup_rw and pup_ro1 can be a symlink (savefolder) or a mountpoint (savefile); the code suggested by gyro is the best option for this:

pup_rw=$(stat -c %m $(readlink -f /initrd/pup_rw))
pup_ro1=$(stat -c %m $(readlink -f /initrd/pup_ro1))

There are some rare cases where some apps refuse to operate with symlinks and require an actual directory. and here the symlink does not point to the actual mounpoint (it's a subdir) the example in functions4puppy solves this issue:

 pup_rw="/initrd/pup_rw"
 [ -L /initrd/pup_rw ] && pup_rw="$(readlink /initrd/pup_rw)"
 pup_ro1='/initrd/pup_ro1'
 [ -L /initrd/pup_ro1 ] && pup_ro1="$(readlink /initrd/pup_ro1)"
