### ISSUE TITLE
Won't work in live cd mode.

### ISSUE THREAD

**Issue by Randall-Glass** [puppylinux-woof-CE/woof-CE#1015]
I have tried woof-ce in tahr64-6.0.5 live cd, tahr-6.0.5_PAE 32 bit live cd, slacko64-6.3.2-uefi live cd, slacko-6.3.2-uefi 32 bit live cd, precise live cd. And it does not create a iso. Nor burn a cd.

Woof-ce will not work on a live cd.

Here are the errors , and warnings, I get in tahr64-6.0.5 live cd:
https://paste.ee/p/LyQFx

**Comment by wdlkmpx** [comment]
I can't access that url. Even the web proxies i'm trying give this error: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

But it's a possibility, i guess all of us don't use a cd to run puppy, so that is mostly untested. I'm building a pup and i'll burn the iso and test it one of these days..

**Comment by Randall-Glass** [comment]
Do you want to create a live-CD .iso file, which is the normal choice for a
PC-compatible target, or is your target an SD-card for an ARM-based board?
In the latter case, you would already have downloaded an SD-card skeleton image
file into folder 'sd-skeleton-images' (done by script '1download') -- if there
is no image file in that folder, you cannot choose the SD-card option.
WARNING: for the SD-card option, you must have enough free space in the
current directory /mnt/sda11/woof-out_x86_x86_64_ubuntu_xenial64/sandbox3
to expand the SD image file, typically 4GB.
Press ENTER only for normal .iso creation, or 
any other printable character for SD-card: 


Now building sandbox3/rootfs-complete, with the complete filesystem...

If you know what packages you want included from rootfs-packages
you can bypass the checkbox GUI by renaming 

'support/rootfs-packages.conf-backup'

to

'support/rootfs-packages.conf'

and edit it to include your customised package list.

You can CTRL-C out of this script and try it right now if you wish
or hit Enter/Return to continue.

copying firewall_ng
copying pfilesearch
copying pfind
copying pgprs
copying pmirror
copying pmusic
copying sfs_load
copying wallpaper
cat: /tmp/rootfs_pkgs_pinstall_ptheme.sh: No such file or directory
Creating file woof-installed-packages...

Exiting from support/findpkgs, already created up-to-date pkg list:
 /mnt/sda11/woof-out_x86_x86_64_ubuntu_xenial64/status/findpkgs_FINAL_PKGS-ubuntu-xenial

Copying to sandbox3/rootfs-complete...
 915resolution a52dec acpi acpid-busibox advancecomp align alsa-lib alsa-base alsa-driver alsa-utils alsaequal apparmor apulse asunder atk atkmm at-spi2-atk attr audiofile audit autoconf avahi avfs axel babeltrace bacon bacon_runtime bash bbc_provided bbe bc bcrypt bdb bin86 binutils boehm-gc bones bzip2 ca-certificates caps ccache cddetect cdparanoia cdrkit cdrtools cgtkcalc chntpw cifs-utils clipit close copy-fast coreutils colord cpio cryptsetup curl cvs cyrus-sasl2 dash dbus dbus-glib d-conf ddcprobe debianutils desk_icon_theme_blue_moon desk_icon_theme_ardis desk_icon_theme_flattr desk_icon_theme_irokami desk_icon_theme_moblin_stark desk_icon_theme_Moka desk_icon_theme_oranchelo desk_icon_theme_Sarai desk_icon_theme_neon desk_icon_theme_jq8raised desktop-file-utils devmapper dhcpcd dialog dictd_client dietlibc diffstat diffutils directfb disktype dmidecode dosfstools dpkg dunst dvdauthor dvd+rwtools e2fsprogs ed edid efibootmgr efivar eject elfutils elspci embutils_cut enchant esound ethtool exiv2 exfat expat f2fs-tools faac faad ffconvert ffmpeg ffmpegdev file file_sharing-curlftpfs-mpscan findutils firewallstatus flac flex florence flsynclient fontconfig foomatic-db-engine foomatic-filters fpm2 freeglut freememapplet freetype fribidi frisbee fuse gadmin-rsync gail gamin gawk gcc_dev gcc_lib gconf gdb gdbm gdk-pixbuf gdmap getcurpos gettext_devxonly gettext gexec gfontsel gftp giflib gifsicle glade2 glib glibc glibc32 glibc_locales glibmm glib-networking gmeasures gmp gnet gnome-doc-utils gnome-keyring gnome-menus gnome-vfs gnutls gobject-introspection gpart gparted gperf gpptp graphite2 grep groff grub grub4dos gsettings-desktop-schemas gsm gstreamer1 gstreamer1-dev gtk+ gtk2-engines-pixbuf gtk+3 gtk-chtheme gtkdialog gtkhash gtklp gtkmm gtk_theme_stark gtk_theme_flatbluecontrast gtk_theme_flat_grey_rounded gtk_theme_stardust_zigbert gtk_theme_stark-blueish gtksourceview guess_fstype gview gwhere gxmessage gzip hal_flash hardinfo harfbuzz harfbuzz-dev hdparm heimdal helpsurfer hexchat hiawatha hicolor-icon-theme hotplug2stdout htop iconfinder icu id3lib ifplugd ifplugd_old ijs initscripts init-system-helpers inotail inotify-tools installwatch intltool iptables iso-codes isomaster jasper jbigkit jimtcl json-c jwm jwmconfig3 JWMDesk jwm_theme_stark-blueish keyutils kmod krb5 lame lcms lcms2 leafpad legacy_grub_2013 less libaacs libao libappindicator libarchive libart libbluray libbonobo libboost-filesystem libboost-system libbsd libc6-i386 libcanberra libcaca libcap libcap-ng libcddb libcdio libcdk5 libcgi-pm-perl libcroco libcurl3-gnutls libdaemon libdatrie libdb libdbusmenu libdc1394 libdca libde265 libdjvulibre libdmx libdrm libdv libdvbpsi libdvdcss libdvdread libedit libebml libenca libepoxy liberror-perl libevdev libevent libexif libexif-gtk libffi libfftw3 libfs libgc libgcrypt libgd2 libgee libgeoip libgif libglade2 libgles libgnome libgnomecanvas libgnome-keyring libgnomeui libgpg-error libgphoto2 libgringotts libgsf libgudev libhogweed libical libid3tag libidl libidn libieee1284 libimlib libindicator libinput libjack libjansson4 libjpeg62 libjpeg8 libjpeg libjsoncpp1 libjson-glib libloudmouth libltdl libmad libmcrypt libmirclient libmng libmnl libmpcdec libmpfr libmtp libnatpmp libnfnetlink libnetfilter-conntrack libnl libnl3 libnotify libopencore libogg libpaper libpcap libpciaccess libpcsclite libperl libpipeline libpng libpng14 libproxy libpthread-stubs libraw1394 librest librevenge librsvg libsamplerate libselinux libsepol libsigc++ libsigsegv libslang libsmartcols libsndfile libsoup2.4 libspectre libstdc++5 libstdc++6 libsystem libsystemd libtasn1 libthai libtheora libtiff libtool libunistring libusb libusb1 libv4l libva libvdpau libvorbis libvpx libvte libwbclient libwmf libwpd libwpg libx86 libxatracker2 libxcb libzip xcb-util libxdg-basedir libxkbcommon libxml2 libxml2-utils libxshmfence libxslt libxvmc linux_firmware_dvb linux-header lirc ListDD llvm lsb-base lvm2 lxrandr lxtask lzma lzo2 m4 madplay makebootfat man man_cut mesa metamail mhash mingetty minidlna miniupnpc minixcal mirdir mktemp modem-stats momanager mp mpfr ms-sys mtdev mtp_phone_connect mtr multirename nas nbtscan ncurses ndiswrapper nenscript netpbm net_setup net-tools nettle netmon_wce network_roxapp normalize notecase nrg2iso nspr nss ntfs-3g ntpdate numactl numlockx opencv openldap openslp opensp-runtime opensp openssh_client openssl optipng opus orbit2 orc ots p7zip-full p11-kit PackIt pam pango pangomm parted patch patchutils pbackup pburn pcd pciutils pcmciautils pcre pdiag pdvdrsab pequalizer perl perl_tiny perl-compress-zlib perl-digest-sha1_devxonly perl-digest-sha1 perl-extutils-depends perl-extutils-pkgconfig perl-html-parser_devxonly perl-html-parser perl-intl-perl perl-text-unidecode perl-uri perl-xml-parser perl-xml-simple picocom picscale pixman pkgconfig pmcputemp pmirror pmirrorget pnethood pnscan poppler popt powerapplet_tray ppp pptp procps programchooser pschedule psmisc psync pulseaudio PupClockset Pup-SysInfo puppyinputdetect puppyphone puppy_standard_icons puppyserialdetect pure-ftpd python python-libxml2 python_support pythondev qbat radeon_firmware raptor2 readline redland retrovol rman rox_filer rp-pppoe rpl rsync_devxonly rsync rtmpdump rxvt-unicode samba sane-backends scale2x schroedinger sdl sed serf setserial setvol sgml-base sgml-data shared-mime-info speex sqlite squashfs-tools4 ssh-gui ssl-certificate-fix startup-notification strace streamripper subversion sudo sylpheed sys-freedos sysfsutils syslinux sysprof sysvinit taglib tar tbb tcp-wrappers tdb tevent texinfo time transmission tree ucf udev eudev uget unclutter unrar unzip UrxvtControl usb-modeswitch usb-modeswitch-data usbutils util-linux uextract vala vamps vcdimager viewnior vo-aacenc vo-amrwbenc vobcopy vorbis-tools wag_profiles waitmax wavplay wayland wcpufreq wget wireless-tools wmctrl wpa_supplicant wv wvdial wvstreams x11proto x264 x265 xarchive xauth xaw3d xclip xcur2png xdelta xdg_puppy Xdialog xf86-input-keyboard xf86-input-mouse xfdiff-cut xfonts-encodings xkbconfigmanager xml-core xorg_base_new xorg_dri xsane xserver_xorg xtrans xvidcore xz yad yaf-splash yajl z_geany_bacon_hack zip zlib z_xenialfix64
Removing extra documentation
Removing extra locales


Executing sandbox3/pinstall.sh post-install script...
Configuring Puppy skeleton...
Configuring Puppy Help page...
Writing version number and distro name and date to Help page...
Writing distro name to jumping-off page...
Creating base release notes...
Setting mtpaint -s as defaultscreenshot app
Updating certificates in /mnt/sda11/woof-out_x86_x86_64_ubuntu_xenial64/sandbox3/rootfs-complete/etc/ssl/certs... Post-install script for glib...
Symlinking gtkdialog
post-install for gxmessage, creating symlink to replace xmessage
/mnt/sda11/woof-out_x86_x86_64_ubuntu_xenial64/sandbox3/pinstall.sh: line 422: /usr/local/jwmdesk/treeicons: No such file or directory
/mnt/sda11/woof-out_x86_x86_64_ubuntu_xenial64/sandbox3/pinstall.sh: line 737: [: /mnt/sda11/woof-out_x86_x86_64_ubuntu_xenial64/sandbox3/rootfs-complete: integer expression expected
cat: ./root/.icewm/preferences: No such file or directory
cat: ./root/.icewm/preferences: No such file or directory
mv: cannot move 'tmpfile' to './root/.icewm/preferences': No such file or directory
cat: ./root/.config/fbpanel/default: No such file or directory
mv: cannot stat '/tmp/tmpfile': No such file or directory
cat: ./usr/sbin/pfbpanel: No such file or directory
chmod: cannot access '/tmp/tmpfile': No such file or directory
mv: cannot stat '/tmp/tmpfile': No such file or directory
cat: ./usr/sbin/pfbpanel: No such file or directory
sed: can't read ./usr/sbin/pfbpanel: No such file or directory
Xarchive post-install script
xorg_base post-install script...
Removing legacy X11R7 directory and links
Now setting /etc/os-release file
pinstall.sh finished OK

...done.
building /etc/profile
setup for kernel-skeleton...

Installing HUGE kernel
Kernel is 3.14.54-tahr_64 version
kernel-modules.sfs-3.14.54-tahr_64
vmlinuz-3.14.54-tahr_64

Now building initial ramdisk in initrd-tree/...
LANG: en_US.UTF-8

* Extracting initrd_progs-20170322-static.tar.xz...
Arch: x86_64

* Using default locale
* Using default keymap


***        INITRD: initrd.gz [x86_64]
*** /DISTRO_SPECS: xenialpup64 7.0.8.4 x86_64

*** Doing a cross-build. Not chrooting to do a sanity-test ***
Updating pkg data in rootfs-complete/root/.packages ...
Rationalizing categories in Packages-puppy-xenial64-official, please wait...
Fixing: rootfs-complete/usr/share/themes/Flat-grey-rounded/gtk-2.0/gtkrc
Fixing: rootfs-complete/usr/share/themes/FlatBlueContrast/gtk-2.0/gtkrc
Fixing: rootfs-complete/usr/share/themes/MurrinaSpring/gtk-2.0/gtkrc
Fixing: rootfs-complete/usr/share/themes/Stardust/gtk-2.0/gtkrc
Fixing: rootfs-complete/usr/share/themes/stark-blueish/gtk-2.0/gtkrc
Fixing: rootfs-complete/usr/share/themes/stark/gtk-2.0/gtkrc

Continuing to setup /mnt/sda11/woof-out_x86_x86_64_ubuntu_xenial64/sandbox3/rootfs-complete...

File card_mntd48.png created.
File card_mntd_boot48.png created.
File drive_mntd48.png created.
File drive_mntd_boot48.png created.
File floppy_mntd48.png created.
File floppy_mntd_boot48.png created.
File optical_mntd48.png created.
File optical_mntd_boot48.png created.
File usbdrv_mntd48.png created.
File usbdrv_mntd_boot48.png created.
'rootfs-complete/usr/local/bin/rox' -> 'defaultfilemanager'
ln: failed to create symbolic link 'rootfs-complete/usr/lib/cups/backend/smb': No such file or directory

Now building sandbox3/0builtin_files_xenialpup64-7.0.8.4.pet,
which is a PET package with lists of all packages and files builtin to the SFS...
915resolution JWMDesk ListDD PackIt Pup-SysInfo PupClockset UrxvtControl Xdialog a52dec acpi acpid-busibox align alsa-base alsa-driver alsa-lib alsa-utils alsaequal apparmor apulse asunder at-spi2-atk atk atkmm attr audiofile audit avahi avfs axel babeltrace bacon_runtime bash bbc_provided bbe bc bcrypt bdb binutils boehm-gc bones busybox bzip2 ca-certificates caps cddetect cdparanoia cdrkit cdrtools cgtkcalc chntpw cifs-utils clipit close colord copy-fast coreutils cpio cryptsetup curl cyrus-sasl2 d-conf dash dbus dbus-glib ddcprobe debianutils desk_icon_theme_Moka desk_icon_theme_Sarai desk_icon_theme_ardis desk_icon_theme_blue_moon desk_icon_theme_flattr desk_icon_theme_irokami desk_icon_theme_jq8raised desk_icon_theme_moblin_stark desk_icon_theme_neon desk_icon_theme_oranchelo desktop-file-utils devmapper dhcpcd dialog dictd_client diffstat diffutils directfb disktype dmidecode dosfstools dpkg dunst dvd+rwtools dvdauthor e2fsprogs ed edid efibootmgr efivar eject elfutils elspci embutils_cut enchant esound ethtool eudev exfat exiv2 expat f2fs-tools faac faad ffconvert ffmpeg file file_sharing-curlftpfs-mpscan findutils firewallstatus flac florence flsynclient fontconfig foomatic-db-engine foomatic-filters fpm2 freeglut freememapplet freetype fribidi frisbee fuse gadmin-rsync gail gamin gawk gcc_dev gcc_lib gconf gdbm gdk-pixbuf gdmap getcurpos gettext gexec gfontsel gftp giflib gifsicle glib glib-networking glibc glibc32 glibc_locales glibmm gmeasures gmp gnet gnome-keyring gnome-menus gnome-vfs gnutls gobject-introspection gpart gparted gperf gpptp graphite2 grep grub grub4dos gsettings-desktop-schemas gsm gstreamer1 gtk+ gtk+3 gtk-chtheme gtk2-engines-pixbuf gtk_theme_flat_grey_rounded gtk_theme_flatbluecontrast gtk_theme_stardust_zigbert gtk_theme_stark gtk_theme_stark-blueish gtkdialog gtkhash gtklp gtkmm gtksourceview guess_fstype gview gwhere gxmessage gzip hal_flash hardinfo harfbuzz hdparm heimdal helpsurfer hexchat hiawatha hicolor-icon-theme hotplug2stdout htop iconfinder icu id3lib ifplugd ifplugd_old ijs init-system-helpers initscripts inotail inotify-tools installwatch intltool iptables iso-codes isomaster jasper jbigkit jimtcl json-c jwm jwm_theme_stark-blueish jwmconfig3 keyutils kmod krb5 lame lcms lcms2 leafpad legacy_grub_2013 less libaacs libao libappindicator libarchive libart libbluray libbonobo libboost-filesystem libboost-system libbsd libc6-i386 libcaca libcanberra libcap libcap-ng libcddb libcdio libcdk5 libcgi-pm-perl libcroco libcurl3-gnutls libdaemon libdatrie libdbusmenu libdc1394 libdca libde265 libdjvulibre libdmx libdrm libdv libdvbpsi libdvdcss libdvdread libebml libedit libenca libepoxy libevdev libevent libexif libexif-gtk libffi libfftw3 libfs libgc libgcrypt libgd2 libgee libgeoip libgif libglade2 libgles libgnome libgnome-keyring libgnomecanvas libgnomeui libgpg-error libgphoto2 libgringotts libgsf libgudev libhogweed libical libid3tag libidl libidn libieee1284 libimlib libindicator libinput libjack libjansson4 libjpeg libjpeg62 libjpeg8 libjson-glib libjsoncpp1 libloudmouth libltdl libmad libmcrypt libmirclient libmng libmnl libmpcdec libmpfr libmtp libnatpmp libnetfilter-conntrack libnfnetlink libnl libnl3 libnotify libogg libopencore libpaper libpcap libpciaccess libpcsclite libperl libpng libpng14 libproxy libraw1394 librest librevenge librsvg libsamplerate libselinux libsepol libsigc++ libsigsegv libslang libsmartcols libsndfile libsoup2.4 libspectre libstdc++5 libstdc++6 libsystem libsystemd libtasn1 libthai libtheora libtiff libunistring libusb libusb1 libv4l libva libvdpau libvorbis libvpx libvte libwbclient libwmf libwpd libwpg libx86 libxatracker2 libxcb libxdg-basedir libxkbcommon libxml2 libxshmfence libxslt libxvmc libzip linux_firmware_dvb lirc llvm lsb-base lvm2 lxrandr lxtask lzma lzo2 madplay makebootfat man_cut mesa metamail mhash mingetty minidlna miniupnpc minixcal mirdir mktemp modem-stats momanager mp ms-sys mtdev mtp_phone_connect mtr multirename nas nbtscan ncurses ndiswrapper nenscript net-tools net_setup netmon_wce netpbm nettle network_roxapp normalize notecase nrg2iso nspr nss ntfs-3g ntpdate numactl numlockx opencv openldap openslp opensp-runtime openssh_client openssl opus orbit2 orc ots p11-kit p7zip-full pam pango pangomm parted pbackup pburn pcd pciutils pcmciautils pcre pdiag pdvdrsab pequalizer perl-digest-sha1 perl-html-parser perl_tiny picocom picscale pixman pmcputemp pmirror pmirrorget pnethood pnscan poppler popt powerapplet_tray ppp pptp procps programchooser pschedule psmisc psync pulseaudio puppy_standard_icons puppyinputdetect puppyphone puppyserialdetect pupx pure-ftpd python python-libxml2 python_support qbat radeon_firmware raptor2 readline redland retrovol rox_filer rp-pppoe rpl rsync rtmpdump rxvt-unicode samba sane-backends scale2x schroedinger sdl sed setserial setvol sfs_load shared-mime-info speex sqlite squashfs-tools4 ssh-gui ssl-certificate-fix startup-notification streamripper sudo sylpheed sys-freedos sysfsutils syslinux sysvinit taglib tar tbb tcp-wrappers tdb tevent time transmission tree ucf udev uextract uget unclutter unrar unzip usb-modeswitch usb-modeswitch-data usbutils util-linux vamps vcdimager viewnior vo-aacenc vo-amrwbenc vobcopy vorbis-tools wag_profiles waitmax wavplay wayland wcpufreq wget wireless-tools wmctrl wpa_supplicant wv wvdial wvstreams x264 x265 xarchive xauth xaw3d xcb-util xclip xcur2png xdelta xdg_puppy xf86-input-keyboard xf86-input-mouse xfdiff-cut xfonts-encodings xkbconfigmanager xorg_base_new xorg_dri xsane xserver_xorg xvidcore xz yad yaf-splash yajl z_geany_bacon_hack z_xenialfix64 zip zlib firewall_ng pfilesearch pfind pgprs pmirror pmusic sfs_load wallpaper 
Converting directory 0builtin_files_xenialpup64-7.0.8.4 to 0builtin_files_xenialpup64-7.0.8.4.tar.gz...
Done

installing pkg lists into rootfs-complete/root/.packages/builtin_files...
...done
Removing redundant aufs-utils...
deleting auibusy
deleting auplink
deleting mount.aufs
deleting umount.aufs
deleting aufs
deleting libau.so*
deleting aufs
deleting aufs.5
deleting aubrsync
deleting aubusy
deleting auchk
Removing redundant firmware as it is in the z drive

Creating Fontconfig cache files...
Leaving PPM2 gui

Fixing permissions on CUPS libraries..
chmod: cannot access 'rootfs-complete/usr/lib/cups/backend': No such file or directory
chmod: cannot access 'rootfs-complete/usr/lib/cups/backend/*': No such file or directory

'rootfs-complete/usr/sbin/gtkdialog3' -> 'gtkdialog'
'rootfs-complete/usr/sbin/gtkdialog4' -> 'gtkdialog'
rm: cannot remove 'lib64': No such file or directory
Setting default apps specified in build.conf ...
defaultcdplayer -> deadbeef (main sfs)
defaultterminal -> urxvt (main sfs)



Finding invalid symlinks...

Now building the main f.s., puppy_xenialpup64_7.0.8.4.sfs...
Parallel mksquashfs: Using 4 processors
Creating 4.0 filesystem on build/puppy_xenialpup64_7.0.8.4.sfs, block size 524288.
[=========================================================================================================================================================================\] 15343/15343 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 524288
	compressed data, compressed metadata, compressed fragments, no xattrs
	duplicates are removed
Filesystem size 167963.49 Kbytes (164.03 Mbytes)
	23.22% of uncompressed filesystem size (723285.63 Kbytes)
Inode table size 205912 bytes (201.09 Kbytes)
	23.34% of uncompressed inode table size (882165 bytes)
Directory table size 230682 bytes (225.28 Kbytes)
	41.26% of uncompressed directory table size (559101 bytes)
Number of duplicate files found 706
Number of inodes 24758
Number of files 14507
Number of fragments 532
Number of symbolic links  7797
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 2454
Number of ids (unique uids + gids) 17
Number of uids 9
	root (0)
	webuser (1002)
	spot (502)
	ftp (1000)
	unknown (506)
	unknown (500)
	unknown (1883)
	unknown (999)
	unknown (501)
Number of gids 15
	root (0)
	daemon (1)
	tty (2)
	webgroup (504)
	spot (502)
	ftp (1000)
	unknown (43)
	unknown (506)
	uucp (10)
	users (500)
	unknown (8000)
	disk (100)
	dip (30)
	unknown (999)
	guest (501)
find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

Can't find Grub2

Would you like to burn it to a CD? 
ENTER only for yes, or any printable char then ENTER not to: 
Type "y" for multisession, else just ENTER: 
Please insert blank CD into /dev/sr0
(which is described as: PLDS DVD-RW DU8A6SH )
-- also be sure that it is unmounted.
Then hit ENTER key: 
Cdrecord-ProDVD-ProBD-Clone 3.01a25 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2014 Joerg Schilling
TOC Type: 1 = CD-ROM
scsidev: '/dev/sr0'
devname: '/dev/sr0'
scsibus: -2 target: -2 lun: -2
Warning: Open by 'devname' is unintentional and not supported.
Linux sg driver version: 3.5.27
Using libscg version 'schily-0.9'.
SCSI buffer size: 64512
atapi: 1
Device type    : Removable CD-ROM
Version        : 5
Response Format: 2
Capabilities   : 
Vendor_info    : 'PLDS    '
Identifikation : 'DVD-RW DU8A6SH  '
Revision       : 'DL62'
Device seems to be: Generic mmc2 DVD-R/DVD-RW/DVD-RAM.
Current: CD-RW
Profile: DVD+R/DL 
Profile: DVD+R 
Profile: DVD+RW 
Profile: DVD-R/DL layer jump recording 
Profile: DVD-R/DL sequential recording 
Profile: DVD-RW sequential recording 
Profile: DVD-RW restricted overwrite 
Profile: DVD-RAM 
Profile: DVD-R sequential recording 
Profile: DVD-ROM 
Profile: CD-RW (current)
Profile: CD-R 
Profile: CD-ROM 
Profile: Removable Disk 
Using generic SCSI-3/mmc   CD-R/CD-RW driver (mmc_cdr).
Driver flags   : MMC-3 SWABAUDIO BURNFREE FORCESPEED 
Supported modes: TAO PACKET SAO SAO/R96P SAO/R96R RAW/R16 RAW/R96P RAW/R96R
Drive buf size : 335104 = 327 KB
cdrecord: Warning: Cannot read drive buffer.
cdrecord: Warning: The DMA speed test has been skipped.
FIFO size      : 4194304 = 4096 KB
cdrecord: No such file or directory. Cannot open '../woof-output-xenialpup64-7.0.8.4-uefi/xenialpup64-7.0.8.4-uefi.iso'.
...done

Hit ENTER to build the 'devx' SFS file, any other key to exit: m

**Comment by 01micko** [comment]
Looks like you have tried to make a UEFI iso but didn't choose the grub2-uefi package at the start of 3builddistro-Z. (checkbox field). You can configure this. Read the instructions  about 'support/rootfs-packages.conf'
