### ISSUE TITLE
OverlayFS support

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1029]
Here we can discuss this new feature that is being written by gyro and it will be pushed to rationalise in the future once he gets something working. 1st is the initrd and then hopefully the rest of the system.

woodenshoe-wee will attempt to fix stuff and make it work in the raspberry pi.

This will take some time and important commits may reference this issue.

**Comment by gyrog** [comment]
I've created a different issue, beacuse my init re-write is about more than just OverlayFS.
