### ISSUE TITLE
Saving to folder fails in pupmode 13

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1033]
This was introduced around the last week or so.

\<ot\>I honestly feel like going into full Linus rant mode about these basic breakages (that's what branches are for - testing is not; we try as much as possible to keep it stable)\</ot\>

Back on topic.. see http://www.murga-linux.com/puppy/viewtopic.php?p=956635#956635

I just haven't the time to hunt it and fix it; especially since as far as I know I didn't break it. If I did, full apologies will be pending.

**Comment by peabee** [comment]
Hear hear - I have also been worried that a degree of inappropriate instability has been apparent recently in testing.....

**Comment by ninaholic** [comment]
I found when rationalise is behind testing, rationalise is the stable version and testing is for testing, and when rationalise is ahead of testing, testing is the more stable bugfixes version and rationalise is for testing new things. The first scenario (when rationalise is behind testing) is more often the case and seems to be a secret undocumented one I notice over time. Sorry if I spoiled the secret  :laughing:

(my firefox tells me "rationalise" is a spelling mistake: "did you mean rationalize?", maybe Firefox is American or needs to update dictionary, it also seems to be against the word "colour") https://ibb.co/chbSxa

**Comment by gyrog** [comment]
Problem is "snapmergepuppy" is exiting with an error message.
The line `BASEMTP="$(df-FULL | awk '{print $6}' | grep "$BASE" | tail -1)"` doesn't work if BASE is not a mountpoint.
So replace it with `BASEMTP="$(stat -c %m "$BASE")"`
or `BASEMTP="`df --output=target "$BASE" | tail -1`"`
or even `BASEMTP="`df-FULL --output=target "$BASE" | tail -1`"` which is what it used to be.

**Comment by gyrog** [comment]
What's the name of the branch?

**Comment by wdlkmpx** [comment]
It's testing. I'll push it myself... this is the correct solution:

BASEMTP="$(stat -c %m "$BASE")"

by the way, the aufs specific stuff will not work with overlay. in this case it does need to follow symlinks to get the real $SNAP and $BASE

**Comment by wdlkmpx** [comment]
Checking the log... that seems the only bad bug introduced recently which i didn't test in my current install with a savefolder, i thought i had copied that file from my other build (slacko 5.3-ce) and actually performed some tests in my main build but the change that introduced the bug was missing...

**Comment by ninaholic** [comment]
Thank you @wdlkmpx and @gyrog ! This ataflash saving problem has been in Slacko 14.0 woof-ce since the new init was rolled out last year (I try even when 14.0 option was removed :laughing: ), and now it **finally works** right too! Yesss :D
