### ISSUE TITLE
debdb2pupdb fails in woof-out_x86_64_arm_raspbian_jessie

### ISSUE THREAD

**Issue by pjz** [puppylinux-woof-CE/woof-CE#1066]
`debdb2pupdb` fails in woof-out_x86_64_arm_raspbian_jessie so when I run `./0setup` I end up with zero-length `Packages-raspbian-jessie-*` files.  And I can't find the source to `debdb2pupdb`... anyone got a pointer for me?

**Comment by woodenshoe-wi** [comment]
What version of Puppy are you running woof-CE in?  The debdb2pupdb in older Puppies may segfaut with the newer Packages.xz files.

You could try copying the debdb2pupdb from woof-CE/woof-arch/x86_64/build/support over the one in Puppy, /usr/local/petget/debdb2pupdb

The source code for debdb2pupdb is at woof-CE/initrd-progs/pkg/w_apps_static/w_apps

Glad to see that someone else is interested in building Puppy for Raspberry Pi too.

**Comment by woodenshoe-wi** [comment]
Raspbian stretch is now the stable version so I updated it a little and deleted the raspbian/jessie build.

This should allow you to use rpi-update without any keyboard problems.

**Comment by pjz** [comment]
...maybe I'm doing it wrong?  Is it only runnable on a Puppy install?  I've been trying to do it on Ubuntu (16.04 if it matters) to build a puppy distro for a raspi... if I can download such an image I'd be happy to, but I couldn't find a valid link.

**Comment by woodenshoe-wi** [comment]
You should be able to do the building using run-woof  
https://github.com/puppylinux-woof-CE/run_woof  
So you wouldn't need to install Puppy if you don't want to but you will still need to download a Puppy ISO and devx sfs.

I used the tahr64-6.0.6-ufi.iso and devx_tahr64_6.0.6.sfs from  
http://distro.ibiblio.org/puppylinux/puppy-tahr/iso/tahrpup%20-6.0-CE/  
for my builds using run-woof so I know that should work.

I suppose I could upload the image file I built to Dropbox if you wanted to play with it but I don't have enough time to maintain a release properly so if you would be willing to learn to use woof-CE you would be able to build a new image whenever you wanted to.

Let me know if you have any other questions or want me to upload my image file.

**Comment by woodenshoe-wi** [comment]
I wrote a more detailed description of using run_woof here  
http://www.murga-linux.com/puppy/viewtopic.php?t=111268

If you run into any problems that are related to run_woof either post them there or open an issue at  
https://github.com/woodenshoe-wi/run_woof

Currently there is no Issues tab at puppylinux-woof-CE/run_woof
