### ISSUE TITLE
/status/2createpackages_history_builds-*** cannot be read

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1069]
/status/2createpackages_history_builds-*** will no longer open with texteditor - has strange type - application/octet-stream - was text/plain type previously......

**Comment by ninaholic** [comment]
slacko 6.9.9.9 built with latest woof-ce: 2createpackages_history_builds-slackware-14.2 and all files in /status show up as ASCII text and open correctly in Geany for me

**Comment by peabee** [comment]
Mystery!
