### ISSUE TITLE
Multiple-Sound-Card-Wizard doesn't "see" usb mic

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1073]
or retrovol....

http://murga-linux.com/puppy/viewtopic.php?p=963246#963246

**Comment by wdlkmpx** [comment]
I see ```aplay -l``` is ignoring the usb mic. I guess it's because the webcam doesn't have a pcm output device.

In other words, this requires some changes in the MSCW design. The alsa's pcm file contains all needed info.
