### ISSUE TITLE
Block exit command when initrd is dropping out the console

### ISSUE THREAD

**Issue by rizalmartin** [puppylinux-woof-CE/woof-CE#1074]
When init script in puppy triggers a fatal error. It will drop the console. However if you type "exit" on the console. Kernel panic was triggered. Please block this command when dropping out the console. Instead reboot the computer if "exit" was typed on the console.

**Comment by rizalmartin** [comment]
I figured out to solve this. Just type reboot under the /bin/sh command

**Comment by mavrothal** [comment]
does this still needs to be open?
