### ISSUE TITLE
rc.sysinit waits for external pcmcia modules to load even when built in to newer kernels. 

### ISSUE THREAD

**Issue by Marv1943** [puppylinux-woof-CE/woof-CE#1075]
A change such as in the diff below, pretty similar to what was done for USB would save 10 secs on boot with newer kernels.  The diff is on the most recent rc.sysinit from LxPupSc 17.08.24T.  Modification tested on LxPupSc with built-in pcmcia and X-slacko 4.3 without.

# diff  /root/Desktop/sysinitwork/rc.sysinit_stock /root/Desktop/sysinitwork/rc.sysinit_mod
563,572c563,578
< WAITCNT=0
< PCIPCMCIA="`elspci -l | grep -o '060700'`"
< if [ "$PCIPCMCIA" != "" ];then #this may be slow to respond.
<  echo -n " pcmcia"  >/dev/console
<  while [ $WAITCNT -lt 10 ];do
<   [ "`lsmod | grep -E '^yenta_socket |^tcic |^i82092 |^i82365 |^pd6729 '`" != "" ] && break
<   WAITCNT=`expr $WAITCNT + 1`
<   sleep 1
<   echo -n " $WAITCNT" >/dev/console
<  done
---
> PCMCIABUILTIN='no'
> if [ "`modinfo yenta_socket 2>/dev/null`" = "" ];then   #Marvmod shut this up.
>  #kernel has PCMCIA core drivers builtin.
>  PCMCIABUILTIN='yes'
> else
>   WAITCNT=0
>   PCIPCMCIA="`elspci -l | grep -o '060700'`"
>   if [ "$PCIPCMCIA" != "" ];then   #this may be slow to respond. 
>    echo -n " pcmcia"  >/dev/console
>    while [ $WAITCNT -lt 10 ];do
>     [ "`lsmod | grep -E '^yenta_socket |^tcic |^i82092 |^i82365 |^pd6729 '`" != "" ] && break
>     WAITCNT=`expr $WAITCNT + 1`
>     sleep 1
>     echo -n " $WAITCNT" >/dev/console
>    done
>   fi

**Comment by wdlkmpx** [comment]
I'll apply the patch but you have to provide a proper patch first..
upload your patch to https://pastebin.com/

diff -u /root/Desktop/sysinitwork/rc.sysinit_stock
/root/Desktop/sysinitwork/rc.sysinit_mod > yourpatch.diff

**Comment by Marv1943** [comment]
OK I think I have it up in pastebin and public.  The title is rc.sysinit diff.  I've never done GitHub or pastebin before so bear with me.

**Comment by wdlkmpx** [comment]
Don't worry, learning git takes time. In the past i offered my help
several times to include patches and code people want to merge, for me
it's easy to perform even somewhat complex operations in git. So just
to avoid the pain of comitting and possibly encountering issues, i'm
still here listening.

When you paste something in pastebin.com.. remember to share the link,
this is your patch..
http://pastebin.com/raw/BGapgSt5
