### ISSUE TITLE
Configuration files need to be added to woof-distro?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1082]
_00build.conf and /support/rootfs-packages.conf are configuration files that define how a build is made but are not currently recorded in woof-distro. They should be? and should be installed into woof-out by merge2out?

**Comment by wdlkmpx** [comment]
_00build.conf is already in woof-distro, in fact i'm editing the custom _00build.conf for dpup stretch/puduan. It's up to 01micko and mrfricks to add their own. Let me see....  upups already have _00build.conf... 

It's easy to add the other file, but what's preventing me from adding it to the dpup dir is the thought that rootfs-packages should not exist... everything that is really important should go to rootfs-skeleton. Everything else should go to the repos.. and that requires a person to check threads and most importantly, advertise himself as the one people can rely on to keep the repos up-to-date.

merge2out already does what you suggest. but to make it work with -/support/rootfs-packages.conf... the build scripts must change that path to -/rootfs-packages.conf

**Comment by wdlkmpx** [comment]
I was thinking about a way to include the rootfs-packages in _00build.conf, but as a doocracy, the one who does it first is the winner and i accept my defeat. But it certainly needs adjusting so it can be stored in woof-distro and made available by merge2out.

hmmm some things i see scottman talk about in the puppy forum... guess what.. i already done that. but i don't have time to expand/make them more generic and port the gui's from yad to gtkdialog.. which is a regression anyway as gtkdialog doesnt support gtk3.. yad does.
