### ISSUE TITLE
bring newest peasyapps to ibiblio / woof-ce?

### ISSUE THREAD

**Issue by ninaholic** [puppylinux-woof-CE/woof-CE#1094]
I find a thread with links to most:
http://www.murga-linux.com/puppy/viewtopic.php?t=84490

Based on what's here:
http://distro.ibiblio.org/puppylinux/pet_packages-noarch/
http://distro.ibiblio.org/puppylinux/pet_packages-common/

The ones with updates I found:
- peasydiff-1.4 (latest was 1.0)
- peasydisc-4.1 (latest was 3.9)
- peasyglue-2.0 (latest was 1.9)
- peasypdf-4.2 (latest was 3.9)
- peasyscale-2.0 (latest was 1.51)
- peasyscan-2.12 (latest was 2.5)
- peasywifi-4.5 (latest was 4.3)

Would it be a good idea to add these to the repository and noarch list?
I can try the latter if someone does the former. :)

**Comment by peabee** [comment]
Hi
If you can provide a list in a file with the direct download link for each .pet + the petspec line extracted from each .pet that would be a great help and I could update ibiblio accordingly - thanks. Perhaps you could take on the role as monitor for these apps?

**Comment by ninaholic** [comment]
Hi peabee! Thanks for the link. I'll write more in your thread once I get them all set up then. :)

**Comment by peabee** [comment]
Done.
