### ISSUE TITLE
Update wizardwizard

### ISSUE THREAD

**Issue by zigbert** [puppylinux-woof-CE/woof-CE#1097]
I am looking at simplifying setup GUIs. Things I have been thinking about:

- Why do 'accelerated graphics' has its own button in wizardwizard. I would put it into the xserverwizard. It is already there, but the code is deactivated (line 572). What is the problem?

- Instead I would offer a button in wizardwizard for time and date with a new wizard-like GUI. Including the options provided by the clock-menu in 'jwm_config'.

- The 'Mouse / Keyboard' setup lacks the settings for double-click behavior (speed and area definition). I have been wondering about of how to set this up - as it is controlled by JWM (not always included). For now, I think the best solution is to make a mouse-script in the 'jwm_config' package. This to collect JWM code in one place rather having it 'all over'. JWM tends to upgrade rapidly and has often missed backward compatibility. There are of course other solutions for this. What do you think?

- Can we change the name of the menu-items from 'wizard' to 'setup'?
ALSA sound wizard  -->  Sound setup
CUPS printer wizard  -->  Printer setup
Internet connection wizard  --> Internet connection setup
Mouse/keyboard wizard  -->  Mouse/Keyboard setup
Xorg video wizard  -->  Screen/Graphics setup

**Comment by ninaholic** [comment]
I think wizard sounds more fun and less scary or boring than setup and liked when it was it was called "wizard wizard" because I felt like the master control panel for puppy as new user :laughing: "Xorg video wizard" was nice because it taught me what Xorg means and I feel like a smarter and true Linux user when I see XORG. Think this question depends what audience you're going for (playful and unique or boring/serious/business/generic)

**Comment by wdlkmpx** [comment]
There is a problem with the 'accelerated graphics' wizard.. or 'video
upgrade' wizard. It doesn't work, i saw only code that deals with
wary. Just remove that button from the main wizard dlg.

I would think the mouse is controlled by xorg, not by jwm. If you need
to adjust jwm stuff, it should onLy happen inside jwm config, jwm
wizard, etc. Some people don't like jwm, so it shouldn't be hardcoded
or its stuff placed where it doesn't belong... you have think outside
the box..

However inside the box there are plenty of things to improve, such as
xrandrshell, it can be as good as the C-compiled apps.
A builtin replacement for flSynclient.. i once looked at the code and
thought... a shell script can replace this ugly FLTK app.

**Comment by zigbert** [comment]
Yes, mouse is controlled by X, but there are 2 settings in JWM to define mouse doubleclick.
see in /root/.jwm/jwmrc-personal
```
<!-- Double click speed (in milliseconds) -->
<DoubleClickSpeed>400</DoubleClickSpeed>

<!-- Double click delta (in pixels) -->
<DoubleClickDelta>3</DoubleClickDelta>
```
I have done some tests, but can't see these values actually do anything. Do anyone know what they do, and/or how to control doubleclick?
