### ISSUE TITLE
Mount drives without partition table

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1099]
mkdosfs and windows utilities can make an entire drive one partition without a partition table.
The new probepart does not detect those, so they do not appear on desktop or pmount, although fully functional.
The following (totally untested) patch should fix this though I doubt is the more efficient, or if we really want to add this functionality. 
So is here for review/discussion (I hope...)
```
--- a/sbin/probepart
+++ b/sbin/probepart
@@ -80,8 +80,11 @@
 	fi
 fi
 
+# Find partitions in DOS disks without partition table
+EXTRAPART="`blkid | cut -f1 -d ':'| cut -f3 -d '/' | grep sd | grep -v [0-9]`"
+
 PARTNAMES="`echo "$PARTITIONS" | cut -f 2 -d ' '`" #120602
-ALLDEVS=$(echo -e "${PARTNAMES}\n${OPTICALDRVS}" | sort -u)
+ALLDEVS=$(echo -e "${PARTNAMES}\n${EXTRAPART}\n${OPTICALDRVS}" | sort -u)
 
 #==========================================================================
 
```
--

**Comment by gyrog** [comment]
If  you are going to run "blkid" at all, why not simply get all the info from "blkid"?

**Comment by mavrothal** [comment]
Actually that's what I was thinking when i was looking at it. blkid provides all the info needed. why bother with all the rest? but I really have no wish to do anything more than providing this (dubious?) option. probepart works just fine as it is.

**Comment by mavrothal** [comment]
Committed in  dddcc5f
We'll see how it goes...
