### ISSUE TITLE
Not able to save puppy-save files in NVMe SSD drive partition

### ISSUE THREAD

**Issue by Mariappan** [puppylinux-woof-CE/woof-CE#1115]
While installing puppy-linux in laptop which has nvm-e ssd drive, I was not abe to puppy-save files even though i selected a valid partition. 

Rootcause:
In shutdownconfig, there is a if check to verify valid partitions. In that check, nvme* is not added, hence even if we select a valid partition with available space, not able to proceed.

**Comment by mavrothal** [comment]
The Slackware-compatible Puppy ISO reported here http://www.murga-linux.com/puppy/viewtopic.php?p=976813#976813 should have sufficient NVMe support.
Please test if you have the chance

**Comment by Mariappan** [comment]
Sure, will test after office hours and report back.

**Comment by Mariappan** [comment]
Hi @mavrothal Does that image not UEFI compatible ? It is not booting in my system

**Comment by mavrothal** [comment]
>  Does that image not UEFI compatible ?

Did not check, but looking at it I do not see any efi.img so probably not. 
Hopefully the next one...

**Comment by wdlkmpx** [comment]
With the latest changes nvme drives should be properly handled by most scripts.. if i didn't mess  something up.

However there's still pup_event_frontend_d.bac .. i'm not going to compile this. I'll try to translate it to C although i lack the motivation and time.

**Comment by wdlkmpx** [comment]
nvme drive support should be in good shape with the current git revision... i will create a dpup with uefi one of these days for you to test.. or maybe someone is willing to build any i686 puppy with uefi support for mariappan to test??

i added a C version of pup_event_frontend_d(.c) with a couple enhancements and a i686 binary.

I can compile the rest of the binaries, but i'll need a 64 bit p****.. not willing to use any other os than my own atm... maybe someone else is willing to compile and add arm and x86_64 binaries to:

woof-arch/arm/target/rootfs-skeleton/usr/local/pup_event/..
woof-arch/x86_64/target/rootfs-skeleton/usr/local/pup_event/..   ... ?

Although i truly believe the that a c app based on udev should replace this, some code can be added to pup_volume_monitor to make it work with the rox desktop as well, but... 

Many birds will die of a heart attack on new year's eve.. it's a phantom world
https://www.justsomelyrics.com/1020730/armitage-iii-phantom-world-lyrics.html

**Comment by ninaholic** [comment]
I think, for uefi_cd.sh to work in Stretch, "syslinux-common" must be added from debian?
https://packages.debian.org/stretch/syslinux-common

puppy-common syslinux-3.73.pet doesn't seem to have some of the /usr/lib/syslinux files:
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/support/uefi_cd.sh#L46

![screenshot](https://user-images.githubusercontent.com/5408521/34484658-47d1f614-ef94-11e7-8872-63d5623b8f01.png)

**Comment by wdlkmpx** [comment]
It probably won't work.. 

https://github.com/puppylinux-woof-CE/woof-CE/commit/b86ae62073f66ba219f53fb5a47195d95ca99005

phil downgraded and used a pet pkg. but it's missing the extlinux binary. 

I'm creating a syslinux 4.0.7 petbuild.. but maybe i'll just pick the same pet pkg.. which i assume is using the official binaries

**Comment by wdlkmpx** [comment]
phil's pkg seems to be unsuitable, it's missing files.. breaks puppyinstaller and bootflash (even more)

**Comment by wdlkmpx** [comment]
Hmm but makebootflash only works with syslinux 3.xx stuff. so it's probably ok. the only mystery is the missing extlinux.. it's probably in a zz pkg alongside the 3.xx required files, or maybe a symlink is created ...

**Comment by wdlkmpx** [comment]
I have a test dpup eufi iso but unfortunately it's not available for download yet, the ftp client on my android phone is buggy, it crashed and overwrote the file twice.. damn

**Comment by wdlkmpx** [comment]
Test iso with all the recent changes up to https://github.com/puppylinux-woof-CE/woof-CE/commit/30cefafbf35c50e6b81699ef26a1548c0032e117..

http://01micko.com/wdlkmpx/stretch-7.0.0b1-uefi-devx.iso
http://01micko.com/wdlkmpx/stretch-7.0.0b1-uefi-devx.iso.md5.txt

**Comment by ninaholic** [comment]
stretch-7.0.0b1-uefi-devx.iso working for me, but I have old ATA hard drive without UEFI. What about you @Mariappan ? I was even able to post this message using QtWeb :)

**Comment by mavrothal** [comment]
does this still needs to be open?

**Comment by wdlkmpx** [comment]
There is no feedback, there it's fixed..
