### ISSUE TITLE
Simplifying the rox desktop (eventmanager) [frontend_*]

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1119]
This is what i'm doing. 

First, there is "experimental" stuff that is just going to be removed.

Second, make the Event Manager dialog more generic by removing some rox specific options that are already implemented somewhere in drive_all, etc and stablishing a default reasonable behavior for the rox  desktop drive icons...

Any comments? The clock is ticking.

**Comment by zigbert** [comment]
The clock is ticking :-D

**Comment by wdlkmpx** [comment]
Should ICONDESK=true imply ICONPARTITIONS=true? .. (and maybe even LABELPARTITIONS=true)?

The whole desktop stuff is faster now after many of my edits, so maybe only keep ICONDESK=false (only one drive and call pmount) and true (icons for partitions (and maybe include label)).

==

Currently POWERTIMEOUT is handled by frontend_timeout.. which is called every 4 seconds "if no uevents have occurred".. i think this should not be handled by frontend_timeout (should not depend on pup_event_frontend_d).. this belongs in a separate script/c_app that sleeps for a whole a minute and checks whether the pc needs to be to shutdown.

**Comment by mavrothal** [comment]
does this still needs to be open? looks like you did these.

**Comment by wdlkmpx** [comment]
I actually can simplify it even more, a lot more.

I added a udev rule the calls frontend_change everytime a block uevent
happens, it works the same way as the pup_event_frontend_d binary but
without polling like there's no tomorrow.

But currently frontend_timeout is not triggered.. maybe
frontend_timeout should be the daemon executing its code every 5
seconds verifying that frontend_change is not running.

The advantage of this, is that udev provides fs and size through env variables.

I edited frontend_change and a few other scripts including
/usr/sbin/eventmanager, and i get the same behavior.

But to make it work as it should i have to remove/replace more code
from the GUI and frontend_funcs... keep simplifying it

**Comment by jamesbond3142** [comment]
> I added a udev rule the calls frontend_change everytime a block uevent happens, it works the same way as the pup_event_frontend_d binary but without polling like there's no tomorrow.

You are taking the same path that I took 6 years ago when Fatdog moved away from pup_frontend_* stuff. I lived with that change for a while, but I can tell you it's not a good move. You still need to have a separation between what you trigger from udev rule, and a front-end daemon (script, C, bacon, or otherwise) to actually update the GUI - eventually, that's what we have today: udev trigger to obtain and pass data for the front-end daemon to display it (in Rox, or whatever you like).

Were I to re-write all that stuff again, I will totally skip the udev trigger stuff altogether and just write front-end daemon using either libudev (if you like C) or "udevadm" stuff (if you like scripts).

**Comment by wdlkmpx** [comment]
Currently the daemon serves two functions:

1) volume monitor that triggers frontend_change, the rox desktop icons
and optionally a more generic handler that triggers a dialog or
pmount, all of this code is in the same place. The more generic
automatic handler actually works fine outside the rox desktop.

2) frontend_timeout, this script is triggered every 4 seconds if
events are detected and opens a bunch of files for reading and
writing.

It serves two functions

2.1) detect if a cd is inserted
With the current code if udev is working properly there's no need for
this check for this check, frontend_change runs a loop for 7 seconds
to properly detect the change.

However in artful pup something is wrong, so the periodic check for cd
insertion/removal was restored.

2.2) detect if a floppy disk is inserted

I won't comment but i think it's hipster stuff.

2.3) handle automatic shutdown and save ram to pupsave as defined in
/etc/eventmanager

--
pup-volume-monitor could handle 1) and 2.1). Adding some lines it
could call frontend_change and give proper support for cd insertion.
As long as udev is working properly

It's has a plugin that provides volume icons to gtk apps. Although i
was deeply disturbed reading DavidS posts trying to ged rid of
something everyone else wants to see.

And needs a fix to make it work with the the modified debian/ubuntu
glib, assuming that glib version actually support gio plugins. It's
also a complex app compared to pup_event_frontend_d.. only alpha males
can improve it.

For 2.2) and 2.3), convert frontend_timeout into a daemon.

That comes to mind..

**Comment by wdlkmpx** [comment]
I found that some help msgs are inaccurate, there is inaccurate info.

I edited the scripts many times and i know what actually happens for every case.

The floppy drive checkbox makes you think that if you tick it, the
function to probe every 4 seconds is enabled... this always happens no
matter what.

The same misleading info was in the dvd/cd autoplay checkbox (now
removed). There was never code to trigger that individually, the auto
play happens for all drives once it's enabled.. HOTPLUGNOISY. And it's
handled gracefully.

**Comment by wdlkmpx** [comment]
i just updated master branch (2018-01-11). it's at commit: https://github.com/puppylinux-woof-CE/woof-CE/commit/5070006711c9393c1335773caef758adb54e3db1

all my pup_event changes are in rationalise in one commit: https://github.com/puppylinux-woof-CE/woof-CE/commit/a9bf4090ede6241341b5a557b39b00fd5ded3281

it's a work in progress, but i think it's just as puppy as it was before but without pup_event_frontend_d, and i'm probably not to going to change anything because it will make it even more dependend on udev.

all the ptheme changes are irrelevant, but i just had to delete references to old stuff.

i found that systemd-udevd does not report hotplug events for optical drives, but frontend_timeout triggers stuff that makes it work (but of course when it's not needed), it's a little tricky but my compiled eudev sends all the correct optical drive changes just in time, with env variables that make frontend_change respond like a compiled libudev based binary.

the eudev petbuild i added should be enforced

/etc/eventmanager clearly explains all the changes
https://github.com/puppylinux-woof-CE/woof-CE/blob/rationalise/woof-code/rootfs-skeleton/etc/eventmanager

i expect feedback and will respond to questions when time permits.
 
if no one complains, i will merge that change to testing in one, two, three, or four weeks.

**Comment by peabee** [comment]
> i expect feedback and will respond to questions when time permits.
> if no one complains, i will merge that change to testing in one, two, three, or four weeks.

What is required to test?? Just a rebuild using 'rationalise' instead of 'testing'? No other changes needed to the system config??
Implications of "my compiled eudev" & "the eudev petbuild i added should be enforced" -
 what does this mean???

**Comment by peabee** [comment]
http://smokey01.com/peebee/downloads/test/artfulpup-17.11+11RationaliseTest.iso
BUILD_FROM_WOOF='rationalise;a9bf4090;2018-01-15 18:53:02 +0800'
Seems generally OK - CD, DVD, USB pendrives appear on desktop
however 2 problems noted:
1. pendrive with 2 partitions - only 1 appears on desktop - vfat partition does not appear - see screenie below

2. error messages in kernel.log e.g.:
```
====> Boot-time Kernel Log (dmesg) <====
udevd[3472]: starting version 234
udevd[3473]: Specified group 'input' unknown
udevd[3478]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[3483]: Process '/sbin/pup_event_backend_modprobe' terminated by signal TERM.
udevd[3505]: Process '/sbin/pup_event_backend_modprobe' terminated by signal TERM.
udevd[3587]: Process '/sbin/pup_event_backend_modprobe' terminated by signal TERM.
udevd[3478]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[3483]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[3654]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
....
udevd[4111]: Process '/sbin/crda' failed with exit code 254.
udevd[4111]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[5540]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[4010]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[4250]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[4111]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[4251]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[4131]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[4045]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[6720]: Process '/sbin/pup_event_backend_modprobe' failed with exit code 1.
udevd[7035]: Process '/sbin/crda' failed with exit code 254.
udevd[7223]: Process '/sbin/crda' failed with exit code 254.
udevd[7521]: Process '/sbin/crda' failed with exit code 254.
udevd[7540]: Process '/sbin/crda' failed with exit code 254.
udevd[7861]: Process '/sbin/crda' failed with exit code 254.
```

![screenshot](https://user-images.githubusercontent.com/5926865/34986745-9f1b3b98-fab0-11e7-84f4-80e58263d562.png)

**Comment by wdlkmpx** [comment]
I havent touched the backend_modprobe script and is behaving as usual,
the same errors etc.

Does the same happens with the old Stuff? (Μissing sdd1?)

**Comment by peabee** [comment]
No such problems on:
ArtfulPup-17.11+10
BUILD_FROM_WOOF='testing;358697d4;2018-01-10 22:32:18 +0800'
![screenshot](https://user-images.githubusercontent.com/5926865/34998909-35ae3c8c-fad8-11e7-8ee8-dbf94d97e4f9.png)

**Comment by wdlkmpx** [comment]
hahaha.. i accidentally pushed stuff to testing that closed this. made a hard reset to a previous commit and reponed the issue

ok thanks peabee. i actually had to undo some changes i made

now it's more like the old stuff, and inserting usb drvs with many filesystems after https://github.com/puppylinux-woof-CE/woof-CE/commit/2474dd8e2e984a55f82cbd023c6eb592752970c4 i finally get  the exact same behavior, there is even a new bugfix that is not present in the old code

i tested in virtual box, but you can confirm in actual hw.

**Comment by wdlkmpx** [comment]
one file did not contain my latest changes, i added the changes and rebased, and now it's https://github.com/puppylinux-woof-CE/woof-CE/commit/a604f787a47305a6c01a938f79d6134314f98eb2

**Comment by peabee** [comment]
ArtfulPup-17.11 build with
BUILD_FROM_WOOF='rationalise;060f01eb;2018-01-16 21:04:05 +0800'
seems OK

**Comment by peabee** [comment]
Hi - Further test build of LxPupSc with
BUILD_FROM_WOOF='rationalise;060f01eb;2018-01-16 21:04:05 +0800'
also seems OK
Noticed that format of /etc/eventmanager had slightly changed ("" removed)....

Can you clarify what you meant by "the eudev petbuild i added should be enforced"??

**Comment by wdlkmpx** [comment]
This petbuild: https://github.com/puppylinux-woof-CE/petbuilds/commit/521f7cc83407a3622aac0eb880846f827cbccffa

There are some key apps that should be kept in sync in all pups for consistency's sake. 
Bash 4.2+
Busybox - always the latest version
Syslinux 4.07 - all should upgrade at the same time
Yad 36+
And more..

That's why i like updating the initrd-progs stuff. There is darkness everywhere else.

By the way i see busybox 1.28 adds minix fs detection based on a patch i sent in early 2016 
https://git.busybox.net/busybox/commit/?id=73c47f6c41c97fb452b4747088543f2c2166830a

**Comment by peabee** [comment]
FYI:
http://www.murga-linux.com/puppy/viewtopic.php?p=980821#980821

**Comment by peabee** [comment]
LxPupSc uses Slackware eudev not a pet.....
:eudev:|compat|Packages-slackware-current-lxpup|eudev-3.2.5|eudev|3.2.5|1|System|7350K|slackware/a|eudev-3.2.5-i586-1.txz||dynamic device directory system|slackware|current||

**Comment by wdlkmpx** [comment]
Yeah but i was talking about the upups. By the way i just read a message in the lxpup artful thread.

This is how i fixed the dbus issue in dpup using the same source package, same version and all.

I attach two files that are not real .petbuilds for the petbuilds repo

[dbus_stretch.petbuild.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/1649792/dbus_stretch.petbuild.txt)
[dbus_stretch.petbuild.service.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/1649793/dbus_stretch.petbuild.service.txt)

 just remove the .txt extension, change the PKGNAME to something else, choose a proper dbus version or you can use the same v. Then run ```sh dbus_XXXXX.petbuild```

I added this to the dpup pkgs specs:

yes|dbus_fake|dbus,libdbus-1-3,libdbus-1-dev|exe>null,dev>null,doc>null,nls>null #FAKE INSTALL > NULL .. see dbus_stretch
yes|dbus_stretch||exe

dbus_fake: no files are copied to the rootfs, but the listed compat distro packages are recorded as installed. otherwise the ppm will reinstall them when installing files, causing havoc.

dbus_stretch: pet pkg .. the real files are here (exe, lib, dev)

**Comment by wdlkmpx** [comment]
I think pup_event_frontend_d is a variant of hotplug2stdout that processes uevents following the udev standard messages.

hotplug2stdout works fine without udev, it just prints uevents that need processing to get the right info, there's a patched version. but it duplicates what udev already provides, the only reason to attempt to make it the new pup_event_frontend_d is to include the whole of frontend_timeout in C code.. this script is not healthy. i think we should remove the routine that checks free space and shows an annoying red message, it should be obvious that you're running out of space when one of the tray icons turns red.

eudev behaves correctly.. there's really no need to probe for oprtical drvs when eudev is being used. the real systemd udev does not (properly) report changes in optical drvs, but it works for other drv types.

and that's when frontend_timeout makes sense and it would make more sense if you udev was not executing frontend_change.

frontend_timeout only makes sense as a daemon, a very simpiflied C version of frontend_tiemout, including code from cddetect_quick.. i simplified it even more.

there's also pup-volume-monitor, i'm more inclined to add and process the hotplug2stdout output in that application so that it works with and without udev. but this is something that requires time. it's interesting. but i probably won't invest time in this, or maybe i will. there's too many things to do in real life
