### ISSUE TITLE
Packages-templates is unmaintainable

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1142]
At least for 1 person.

I was looking in the woofce tree to see what's there. And i thought hmm /usr/share/examples should be deleted, really what is it doing there.. hmm. There are broken .xpm symlinks that should be deleted. Hmmm ... Hmm.

Then i tried to open colorcir.ps with ghostscript. ghostscript segfaulted

The ghostscript pkg template is messing up the package. Both processed and unprocessed pkgs have basically the same size, the unprocessed pkg is slightly bigger, like 0.2MB for debian stretch.

Even though i fixed a lot of pkgs templates, it just upsets me that there are many more to fix.

This is the fix i propose: 

1) delete all pkgs templates that are currently not being used by the default builds (also delete belpup if no one is maintaining it)
2) heavily simplify all the remaining pkg templates
3) only allow _PRE & FIXUPHACK, icons and stuff should to rootfs-skeleton.. seriously.

FIXUPHACK should have a fixed list of files to delete. This "dynamic" stuff is really dangerous, and 2createdpackages should be heavily simplified as well, it has broken code and very unreliable code and logic.

**Comment by woodenshoe-wi** [comment]
About point 3.

Adding stuff to  rootfs-skeleton means it is included whether or not that package is in the build.

Wouldn't it make more sense to add PLUSEXTRAFILES and PLUSEXTRADIRS to the templates, or even change 2createdpackages to only add files from the templates and not delete anything except using the FIXUPHACK script?

**Comment by wdlkmpx** [comment]
Hmm well, PLUSEXTRAFILES & PLUSEXTRADIRS should be default behavior with or without those files. If pkg template dir exists, copy everything to the pkg overwriting existing files.. then post-process with FIXUPHACK.

FIXUPHACK can be inside or outside the pkg template ```pkg_FIXUPHACK``` or ```pkg/FIXUPHACK``` .. this is already implemented, that's why i deleted a lot of dirs, otherwise some dangerous code gets executed..

**Comment by wdlkmpx** [comment]
There's something that worries me and is  the fact that the system does not process debian control files. Many packages installed from the ppm will be broken. It's a miracle that the thing works, in slacko all the doinstall.sh files are executed that ensures everything is in place.

A puppy install requires the whole packages-templates dir for deb based pups and some essential fixes for the slackos, so that puppy can become more scalable with very barebones installs.  i think this design flaw is not fixable.

The more you think about it, the more fatal flaws you find, when you open your mind, you better close it.

Currently packages templates is small dir that wil add 120kb to final .sfs. But it needs to be simplified even more, there should only remain FIXUPHACKS. No matter how much you work to make puppy better following the current paradigm and design flaws, it requires a full time developer with a good salary, because in the navy you can sail the seven seas..

**Comment by wdlkmpx** [comment]
After some tests i have come to the conclusion that the current packages-templates code and stuff is making 2createpackages slow and unreliable for the affected pkgs.

I'm making some changes to make 2createpackages 2-3 times faster and the packages-templates related code gets in the way.
It will be simplified... i'll be doing this slowly.. and will probably add a big change in a single commit sometime in the future. Unless i mess something up..

I know arch linux compat does require something like the current packages-templates dirs (most of them are deleted).. /bin & /usr/local/bin are symlinks to /usr/bin.

But arch compat was removed long ago. So now with normal distributions there's no need fix file locations for all pkgs. 

```packages-templates/$GENERICNAME``` will only have files to add to the pkg (add missing stuff, replace files). Only non-zero files in proper locations.

post-processing will only happen in the FIXUPHACKS

There's not much to fix or post-process.. only in certain packages delete some big files or relocate a couple files/dirs... 2createpackages splits pkgs into components before the FIXUPHACK is called.

And 3builddistro deletes extra docs and nls files that are in the main pkg dir.. so it is kind of pointless to even process them in 2createpackages.
