### ISSUE TITLE
Kernel 3.14.56-tahr-PAE-tar.bz2 checksum says it's corrupted

### ISSUE THREAD

**Issue by Randall-Glass** [puppylinux-woof-CE/woof-CE#1143]
Kernel 3.14.56-tahr-PAE-tar.bz2 checksum says it's corrupted

**Comment by peabee** [comment]
I've edited the md5.txt files on ibiblio - please try again - please close the issue if fixed - ta.

**Comment by peabee** [comment]
Is this fixed?

**Comment by Randall-Glass** [comment]
Seems to work okay.

__________________________
Best Regards!

Randall Glass
7505 Campbell's Corner Rd
McLeansboro, IL 62859
Ph: 618-728-4589
http://RadioTelephoneTutor.com

--------------------------------------------
On Fri, 2/23/18, PB <notifications@github.com> wrote:

 Subject: Re: [puppylinux-woof-CE/woof-CE] Kernel 3.14.56-tahr-PAE-tar.bz2 checksum says it's corrupted (#1143)
 To: "puppylinux-woof-CE/woof-CE" <woof-CE@noreply.github.com>
 Cc: "Randall Glass" <rlglass2@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, February 23, 2018, 4:07 AM
 
 Is this fixed?
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
