### ISSUE TITLE
Error with 00_i686/bin/dialog not found

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1151]
Trying to do a 32-bit build with:
BUILD_FROM_WOOF='testing;9e01ecb7;2018-02-28 19:24:23 -0600'
getting errors in 3builddistro-Z: 

> Now building initial ramdisk in initrd-tree/...
> LANG: en_US.UTF-8
> * Extracting initrd_progs-20170706-2-static.tar.xz...
> Arch: i686
> 
> * Using default locale
> * Using default keymap
> **00_i686/bin/dialog not found**
> mv: cannot stat 'initrd.[gx]z': No such file or directory
> No initrd... exiting

**Comment by wdlkmpx** [comment]
There are 2 ways to fix this... in x86_64 pup go to initrd-progs/, open a terminal window and run ```./build.sh tarball``` it will download stuff and compile for a few minutes.. post a link to the tarball here. Or i can disable the dialog app for the build to work.

**Comment by woodenshoe-wi** [comment]
That happened because wdlkmpx wanted me to recompile the inird-progs and added dialog to inird-progs/build.conf, but I only recompiled the arm initrd-progs because there was nothing wrong with the i686 initrd-progs, but they don't include dialog yet.

**Comment by peabee** [comment]
#2 "disable" is preferred.....
