### ISSUE TITLE
Problems with recent keyboard layout changes

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1152]
BUILD_FROM_WOOF='testing;9e01ecb7;2018-02-28 19:24:23 -0600'
On 1st boot, PrintScreen key is not working - Openbox desktop
Doing a Window Manager restart makes the PrintScreen key start working
but it doesn't work again after a reboot+savefolder creation until another Window Manager restart.
Test iso:
http://smokey01.com/peebee/downloads/test/LxPupSc-18.03T-k64.iso

Anybody done a JWM based build with these keyboard changes?

https://github.com/puppylinux-woof-CE/woof-CE/commit/3a5a039eef5444f332193d2dbd2bda645010dfd5 ???

**Comment by wdlkmpx** [comment]
thanks for the iso.

the only problem i see is when i click on the ok button in quicksetup or chooselayout. or execute xkbconfigmanager in some other way.

there is a big bug in xkbconfigmanager if the evdev xorg.conf is being used.

**Comment by wdlkmpx** [comment]
does this fix the issue?
[adrv_LxPupSc_18.03.sfs__fake.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/1777581/adrv_LxPupSc_18.03.sfs__fake.zip)

**Comment by peabee** [comment]
Yes - thanks - that does the trick....

Any chance of also suppressing the "usage" info from keymap-set that now appears on the console during boot? Thanks.

**Comment by wdlkmpx** [comment]
keymap-set is (only) called by rc.country and it either shows a cli
dialog or nothing (/dev/null)... steps to trigger that bug?

**Comment by peabee** [comment]
Problem has been resolved in recent builds - closing - thanks.
