### ISSUE TITLE
gtk-update-icon-cache fails in recent Dpup

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#1154]
Re: gtk-update-icon-cache fails in recent Dpup

Command:
#gtk-update-icon-cache /usr/share/icons/hicolor -f

Error:
gtk-update-icon-cache: The generated cache was invalid.

---

It seems gtk-update-icon-cache fails due to two misnamed icon symlinks (space in filename) in hicolor-icon-theme_winthose-1.0:

woof-CE/woof-distro/x86/debian/stretch/Packages-puppy-stretch-official
12 - hicolor-icon-theme_winthose-1.0|hicolor-icon-theme_winthose|1.0||BuildingBlock|9140||hicolor-icon-theme_winthose-1.0.pet||No description provided||||

---

Generation of the icon cache is successful after the following symlink corrections:

rm -f /usr/share/icons/hicolor/16x16/status/"net error".png
rm -f /usr/share/icons/hicolor/48x48/status/"net error".png
ln -sf /usr/share/icons/hicolor/16x16/status/nm-no-connection.png /usr/share/icons/hicolor/16x16/status/net-error.png
ln -sf /usr/share/icons/hicolor/48x48/status/nm-no-connection.png /usr/share/icons/hicolor/48x48/status/net-error.png

Thanks

**Comment by wdlkmpx** [comment]
Hello radky. Can you provide a fixed pkg with version 1.1 plz?

**Comment by radky2** [comment]
Fixed winthose-1.1.pet attached.

Remove false gz.

Thanks

[hicolor-icon-theme_winthose-1.1.pet.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/1799536/hicolor-icon-theme_winthose-1.1.pet.gz)

**Comment by wdlkmpx** [comment]
Ok thanks, if you have any other fixes or suggestions or want to become the official dpup maintainer just let me know..
