### ISSUE TITLE
Menu does not follow icon change

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1160]
BUILD_FROM_WOOF='testing;12eb9dec;2018-03-25 00:10:36 -0500'
see:
http://murga-linux.com/puppy/viewtopic.php?p=986677#986677

**Comment by wdlkmpx** [comment]
This was fixed a few hours ago

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/etc/xdg/templates/_root_.jwmrc

Jwm-xdgmenu called by fixmenus require that the .directory files referenced in .../xdg/menus/puppy-xxxx.menu contain an invalid Icon= entry (currently 
.xpm icons)

I can't be bothered to look at the code of that app, all i know is that stuff must be broken for it to work properly and look for the correct .png icons

In fact those .directory files should have a valid Icon=/usr/lib/X11......../xx.png

I don't understand how it can work with broken stuff, and i dont care
