### ISSUE TITLE
Devx builtin files

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1167]
builtin_files.sh is called in 3builddistro-Z before devx is build. Thus is getting tricky to know which files/apps are included in the devx and which package the files are coming from. 
A fast and dirty solution is for builtin_files.sh to be called after devx is build but then can be confusing as in the absence of devx files would show as "builtin" while missing.
Or we could modify builtin_files.sh to detect ```[ -d sandbox/devx ]``` and run it again after devx is build at the end of ```if [ "$BUILD_DEVX" = "yes" ] ; then``` argument, after line 1902 of 3buiddistro-Z, to generate ```0builtin_files_${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}_plusdevx.pet```. Then install ```0builtin_files_${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}/root/.packages/builtin_files``` in ```rootfs-complete/devx/root/.packages```. So when devx is installed the additional files will appear.

**Comment by wdlkmpx** [comment]
I added a commit yesterday that implements this, and thinking about it i see it's a tricky situation.. some pkg_DEV lists reference proper devx apps but also the devx part of the main sfs apps. To get the true devx packages the script must get only the exe>dev packages.

But then it will no be a complete filelist. If you want to debug stuff, it's better to simplify 2creapackages to the max, i have started that process in a pull request... it's still a complex script... but most of the bk dangerous and slow stuff was removed/replaced. so it's faster and the results are more predictable.

Many issues are solved by executing the install script of the deb packages.. although this opens a can of worms that should have been opened right after forking the project to fix all possible issues in the DEB land as soon as possible.

Maybe the devx pet file should just be included in devx/root/.packages/ without filelists or should i make it process only the exe>dev packages without the _DEV suffix?

**Comment by wdlkmpx** [comment]
I reverted the commit, it doesn't seem to be the right approach, i just  found the 'devx-only-installed-packages' file in /root/.packages. i guess i'm kinda lost. so the file lists should follow the same logic.. it's easy to tweak the reverted changes to follow the same logic, but i'll do it later.

I realize once again i said words i shouldn't have said.. have removed those..

**Comment by wdlkmpx** [comment]
Well, builtin_files could just use ```devx-only-installed-packages``` and ```woof-installed-packages``` to get the packages to process.

But there's a problem, in the build system there are no standalone packages, but "generic names"... these generic names may contain one package or many packages.

In distros there are packages and groups (core, xorg, xfce, kde, lxde, etc)

The generic names are groups that are treated like standalone packages in the woofce build system.

**Comment by wdlkmpx** [comment]
I found some inconsistencies between 3builddistro and the helper scripts, they don't follow the same logic, i'll be fixing this.

**Comment by wdlkmpx** [comment]
I found another wall called rootfs-packages, it add stuff here and there.

The puppy stuff with pkgs specs mixing everything was bad enough, and with another layer to take into account... probably a deal breaker. 

The question is... how can we get rid of rootfs-packages?

**Comment by woodenshoe-wi** [comment]
That's easy enough, make them into noarch pets in petbuilds.  That way you can complain about how you can't fix the pets on ibiblio...

I do agree that woof-CE should be more modular, each part doing a clearly defined job, but there are downsides to making everything into pets.

Maybe the stuff that is truly noarch scripts could be in separate repos, so the woof-CE scripts would only need to have the ability to pull in a git repo from its url and whoever maintains the repos doesn't have to worry about ibiblio.  Then the stuff in rootfs-packages would not be part of woof-CE anymore.

**Comment by wdlkmpx** [comment]
I already have working code that lists all files from devx and main
sfs. in separate lists that can be used by the builtin pkg remover
tool or something.

But i see a big issue here that can't be overlooked, its implications
are "deep", how can i say politely without sounding like a
douchebag...

But it's not about rootfs-packages, it's the "generic names". Fixing
this means starting over or follow something more closer to woof-next,
which is basically starting over, and i have no problems doing that

But regarding rootfs-packages, it's a matter of communication. It's
just that there's no one to upload them or the process to make someone
upload them is just too much humiliating.

 But i do believe that rootfs-packages must at least consist of
packages that are not recorded... all of them are just installed,
except the big ones or the conflicting ones with non-woofce packages
where 00build.conf can play a role..

And this is how the problem started... allowing non-woofce packages
when a woofce replacement was already there.
