### ISSUE TITLE
No screens found on TahrPuppy on laptop. X doesn't start

### ISSUE THREAD

**Issue by Suncatcher** [puppylinux-woof-CE/woof-CE#1171]
Well, though it's obviously offtopic here, I'll just put it here, as I have no account on Puppy forum and cannot submit bug there. Please, re-post the bug there.

All variants op Puppy fail to start x on my Dell Inspiron 7559. I tried SlackPuppy, TahrPuppy, XenialPuppy.

Here are the screens of **Xorg.0.log**:

![photo_2018-04-15_17-18-03](https://user-images.githubusercontent.com/6388034/38779435-06c3f5a8-40d1-11e8-8739-68a6e11287f8.jpg)

![photo_2018-04-15_17-18-06](https://user-images.githubusercontent.com/6388034/38779436-0b3f3160-40d1-11e8-98b6-63a8a2d9cd6d.jpg)

![photo_2018-04-15_17-18-09](https://user-images.githubusercontent.com/6388034/38779439-0ee0db5c-40d1-11e8-94c7-8e830bf80364.jpg)

**Comment by wdlkmpx** [comment]
You should try bionic pup with a recent kernel and if your laptop requires intel uxa acceleration, you can add ```intel_uxa``` to the kernel params in the bootloader menu... that param is also available for tahrpup, if a new build is produced...

**Comment by Suncatcher** [comment]
> You should try bionic pup

There is no bionic pup on [official download page](http://puppylinux.com/download.html). Is it unofficial build?
