### ISSUE TITLE
The new DISTRO_PET_REPOS locations break service_pack scripts

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1189]
Both service_pack.sh and devx_service_pack.sh pick up URL from DISTRO_PET_REPOS and then look for service pack pets in URL/pet-packages-${DISTRO_DB_SUBNAME}. The latest changes result in both ping failing and exiting the scripts (which can be easily fixed) but then no service pack can be found because the URL and subfolder is wrong.
Option a) hardcode service pack scripts to ibiblio b) eliminate the service_pack update utility c) instruct builders so service packs are placed in raw.githuusercontent.com/pet-packages-${DISTRO_DB_SUBNAME} d)...

**Comment by wdlkmpx** [comment]
Oops the service pack url could be hardcoded or something.

We're also extending the life of something that it's too complex and too hacky to be maintained as a whole, so yeah I think it's better to remove the service pack support, it's not feasible now that the git repo has taken over some important areas..

I'll take a look at the petget code to identify the service pack stuff.

The distro_pet_repos pkg doc db's can be updated to point to anywhere that follows the same tree as woofce/woof-distro, so with a massive sed everything can be moved again.

Instead a new method to update should be proposed: an official builder releases a puppy every  2 months or so (or after a period of activity),, or someone else can do that, what matters is the ISO ready to be shared.

Just so critical updates that are shared by all builds can be used. I see people are still complaining about xkb stuff, but that was fixed.

**Comment by mavrothal** [comment]
> I'll take a look at the petget code to identify the service pack stuff.

is ```URLSPEC0```

**Comment by wdlkmpx** [comment]
I also remember making checking for updates something that only is
triggered by a button in the main dialog. of course that is code that
was lost long ago.

when you open the ppm, it should not attempt connections before trying
to download or check a pkg..

**Comment by wdlkmpx** [comment]
I think i'll remove the service pack stuff. I deleted the service pack
entries in the tahrpup pkg db: 6.0 to 6.0.2 ... 6.0.2 to 6.0.3,
something like that.

That kind of pkgs shouldn't be listed in the pkgs dbs, that means you
can install an old service pack and break the system.

I guess it was only used in the upups, tahrpup specifically.

Woofce can change too much in time, and i don't think the devs have
enough time to create a service pack with that many changes.

**Comment by mavrothal** [comment]
> Woofce can change too much in time, and i don't think the devs have
enough time to create a service pack with that many changes.

Oh, well... I guess puppy is becoming more of a dev playground and less of a user daily distro, but I guess that's fair as long as all involved have fun. 😺

**Comment by wdlkmpx** [comment]
I must admit that i smiled while i deleted that code, it will help reduce the global warming and the load on ibiblio...

There is this code in sfsget:

```PRIMARYREPO="`echo "$SFS_REPOS0" | grep 'distro\.ibiblio\.org' | head -n 1 | cut -f 2 -d '|'`"```

So the script won't work if you have the sfs files in a server other than ibiblio.

The service pack was (fundamentally) wrong. There is a severe "issue" regarding versioning schemes in puppy. It can be reimplemented differently in the future, with a text file specifying service packs.. an updatable text file. No spiders checking directories, so the stuff works in more cases.

A text file listing sfs files is also the best approach for sfsget. What it currently does is just plain wrong. A file that is updatable with a click just like the pet pkg databases with configurable base url..

And the project should use peabee's sfs's, the only stuff that is updated regularly, he should add version2013's wine pkgs in sfs format, and the circle is complete..

There are only 2 important things, browser and wine, wine to install updated apps of basically anything useful that you can't easily get in linux, specially in puppy...
