### ISSUE TITLE
Remove pupscan in favor of hardinfo / Pup-Sysinfo + Pup-Kview

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1195]
pupscan is a gui app that show info about kernel modules and pci/usb interfaces.. 

This and more detailed info with more options can be found in pup-sysinfo + pup-kview or hardinfo (this gtk app has been seeing heavy development in the last 1-2year(s), but it hasn't released a new version yet)

pupscan also provides some info to pdiag... lspci -nnk and a couple other commands already provide the info in a readable format that it tries to format again wasting many code lines...

So, this app at the very least should be hidden from the menu..

**Comment by wdlkmpx** [comment]
I found some issues in pup-kview, apparently signals triggering stuff when they shouldn't, making the menu options unusable as the info gets overridden by kernel module info, or an empty kernel module info.

I attach a partially fixed version (which include support for 800x600, 640x480 screen resolutions) + patches for @radky2 to check. I believe the menus should go to PupSysinfo -> Drivers
[pup-kview-1.3.6.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/1978235/pup-kview-1.3.6.zip)

And pup-kview should only show info of selected kernel modules + some  menu options that don't show info (the ones that call bootmanager dlgs). It can be a single pkg..

I found a similar issue in the PPM making it run a loop showing splashes and processing stuff time and time again, but the ppm is complex, so i haven't attempted to fix it. it's not my priority either.

Or maybe the gtkdialog compiled in dpup is buggy, but but but

**Comment by radky2** [comment]
@wdlkmpx,

Thanks for considering Pup-Kview for Woof-CE.

Reviewing your func.patch, I understand the advantage of the following addition which assures the kmodules function runs to completion only when a kernel module is specifically selected, but does not spontaneously run when triggered by some keyboard event in the menu:

+	if [ -z "$KMODULE" ] ; then
+		exit
+	fi

However, I'm not sure I understand the purpose of the Pup-Kview.patch which specifically excludes important header text that identifies the source of information displayed for a selected menu item. For example, consider the header text for the 'Menu -> Logs -> Kernel Log' report below:

▶—— Boot-time Kernel Log (dmesg) ——◀

Linux version 4.9.98-stretch (root@puppypc15152) (gcc version 7.3.0 (GCC) ) #1 SMP
x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'

-------

If you could explain how the header text could trigger an inappropriate or malformed report, maybe I could adjust the code accordingly.

Thanks

**Comment by wdlkmpx** [comment]
Excluding important headers .. That was a mistake, it happened while i
replaced '>>' with '>' for no apparent reason when i was trying to
figure out what's wrong. I haven't tested much as the info does not
appear.

That mistake made it to the patches. i edit too much scripts and
stuff, i guess it's finally making me dumb. i often point at things
and can't name them. That thing, that thing, i say.

I'm using gtkdialog 0.8.4 and what i see is a real issue, but i'm not
good at explaining things, and this is probably never going to change.
language barrier..

When i select Reports -> Kernel Log (dmesg)  i see text (the report)
that is quickly replaced by a kernel module info.

It shouldn't happen, the only thing i can of think is the triggering
of a signal that calls 'func -kmodules'... how do i know this? Because
'func -kmodules' is only triggered by a signal, i no see other code
doing that.

When no module is selected i see empty 'kmodule' info replacing what i
want to see by selecting a menu item, and this is fixable.. '-z' test.

When i've already selected a kernel module, that info always
replaces/overrides/overwrites the info i want to see by selecting a
menu item.

I use mostly the keyboard, so can't say that i clicked on the menu items.

I hope it's clear now.

Right now i'm testing again pupkview. i had already forgotten about the patches

**Comment by radky2** [comment]
wdlkmpx wrote:

When i select Reports -> Kernel Log (dmesg) i see text (the report) that is quickly replaced by a kernel module info

---

Yes, I can replicate your finding now.

Your func.patch is working very nicely to circumvent the problem.

I'll adjust the Pup-Kview.patch and upload a fixed Pup-Kview 1.3.6.

Thanks

**Comment by radky2** [comment]
After additional testing, it seems the func.patch does not solve the problem after all.

After initially launching Pup-Kview, logs and reports in the menu are appropriate when the keyboard is used to navigate the menu.

However, after an item is selected in the list of kernel modules in the main window, if I later return to the menu and select Logs -> Kernel Log (dmesg), then the the dmesg report is quickly replaced by the prior kernel module info report.

Maybe it is an issue with gtkdialog since you see a similar problem with PPM?

**Comment by radky2** [comment]
Excellent!

It seems the same code of the Pup-Kview.patch must be applied to Menu -> Reports -> PCI Drivers -> Complete, and now that report is also correct (no overwriting).

I'll prepare an official Pup-Kview 1.3.6.

Thanks

**Comment by wdlkmpx** [comment]
@radky2 is there something preventing you from releasing a patched pupkview?

i found the pukview thread through a shady search engine
http://murga-linux.com/puppy/viewtopic.php?t=87179

I don't know how the script behaves outside dpup, so it may work fine and  my patches break it somewhere else. i don't know. Is gtkdialog unsuitable to compile in modern systems? do newer libs cause unexpected behavior? I don't know..

Or are you expecting the script to be in rootfs-packages? I think rootfs-packages was a mistake. and it's still is.. however it can go directly to rootfs-skeleton haha, but only if it becomes a single file to replace pupscan.. i see it has basically the same functions (plus a few more). 

pupkview is the external and improved pupscan, i knew it...

**Comment by radky2** [comment]
@wdlkmpx,

Sorry for the delay. Testing the updated PupKview code will take a bit longer. I want to confirm the new code functions universally outside dpup, with old and new versions of gtkdialog.

If all testing is successful, the new release should be available tomorrow.

Concerning the inclusion of PupKview or PupScan in standard Pups, I will leave that decision to you and others of the Woof-CE team.

Thanks

**Comment by wdlkmpx** [comment]
Pupscan is no longer a gui app. It's a small script (8 lines) that creates a couple of files needed by pdiag and pmodemdiag. It's in woof-CE/woof-code/rootfs-skeleton/usr/sbin/pupscan, not because of its merits but because it's always been there.. scripts in rootfs-skeleton are edited and tend to be different. Some are deleted to give spotlight to some other apps..

Issue resolved. Closing..

**Comment by radky2** [comment]
Pup-Kview-1.3.6 is now available.

http://murga-linux.com/puppy/viewtopic.php?t=87179

Also, if interested, an updated Pup-SysInfo (2.8) is available.

http://murga-linux.com/puppy/viewtopic.php?t=73101

Thanks
