### ISSUE TITLE
/rootfs-packages/jwm_config/usr/local/jwm_config/tray manual edit

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1198]
@zigbert 
/rootfs-packages/jwm_config/usr/local/jwm_config/tray
upupbb-18.05
right click on tray 2 - "Menu: Applications" 
edit window appears however on save get error below and
edit is not applied

![screenshot](https://user-images.githubusercontent.com/5926865/39809391-8c6d6df0-5379-11e8-8f73-dca712154495.png)

**Comment by zigbert** [comment]
I'll look at it

**Comment by zigbert** [comment]
The reason for not letting user edit directly in the rc file is the lack of verifying which is done when clicking the 'Apply' button in the tray-gui.

I have improved the gui to allow manual editing when left-click on an item
![screenshot](https://user-images.githubusercontent.com/5928708/39993751-392e5b5c-5777-11e8-8857-d5a3f06555b3.png)

See https://github.com/puppylinux-woof-CE/woof-CE/commit/2728972f40df08c51bc190695d09120b09acc915

**Comment by wdlkmpx** [comment]
Another issue... some defaults are not "good".

"Applications" instead of "Menu" doesn't look good. And that "Places" string should be a computer icon, something like this: https://commons.wikimedia.org/wiki/File:Blue_computer_icon.svg

That change alone will make a huge difference..

**Comment by zigbert** [comment]
Default values is a matter of taste, and what you see as defaults in the tray configurator is based on Mickos buntoo and fx themes.
...In my taste, very "good" themes.

It's impossible to please all, so my target is to make as user-friendly as possible. - To make every user please their own taste.

**Comment by zigbert** [comment]
@peabee 
Can we close this one, or... ?

**Comment by peabee** [comment]
It can indeed be closed - with many thanks for fixing.
