### ISSUE TITLE
Kodi works on intel pc, but not on amd pc.

### ISSUE THREAD

**Issue by Randall-Glass** [puppylinux-woof-CE/woof-CE#1206]
I have been testing xenialpup64 woof-ce cd's on my intel pc, and on my amd pc.

Seems that woof-ce has graphical display problems with amd machines.

Kodi can't figure out all the resolutions on the amd machine.

Kodi works perfectly on the intel machine.

**Comment by wdlkmpx** [comment]
I guess few people use AMD machines, i don't have any. You probably need to compile the amd driver or something, it can be missing firmware for the radeon driver, etc. 

Kodi probably needs hardware acceleration or something, not exactly a woof-ce issue, but i guess more can be done with the wizards and firmware.. that's when user expertise comes into play..
