### ISSUE TITLE
pfontview disappeared in master

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1219]
pfontview .pet has been dereferenced
but for master
pfontview has not been added to rootfs_skeleton
and
pfontview .pet is still requested in
DISTRO_PKGS_SPECS-ubuntu-bionic

**Comment by wdlkmpx** [comment]
Hm, the DISTRO-PET_REP0S files will. Be fixed, only the ones in the git repo of course, you can apply the same logic to external c0nfigd
