### ISSUE TITLE
Why is sandbox3/0builtin_files_***.pet created?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1225]
Been meaning to ask for ages....
Why does 3builddistro-Z (quite slowly) make this .pet?
"Now building sandbox3/0builtin_files_***.pet,
which is a PET package with lists of all packages and files builtin to the SFS.."

as far as I can see it's not included in the .iso and is never used??

or am I missing something?

**Comment by wdlkmpx** [comment]
Souvenirs

10-15 lines can be removed. but the slow part creates all the files in /root/.packages/builtin_files

I also don't know why the pet pkg.. i can remove that code, but there must be a hidden meaning behind it
