### ISSUE TITLE
PuppyPin in ROX pet

### ISSUE THREAD

**Issue by woodenshoe-wi** [puppylinux-woof-CE/woof-CE#1235]
If the \<backdrop\> image specified in PuppyPin (which comes from the template in the petbuild) does not exist, the first time ROX starts it kind of locks up.  The next time it starts the \<backdrop\> line has been removed from PuppyPin and ROX runs normally.

I don't know how woof-CE sets the default background image, and I don't have time now to experiment with woof builds, but before I make the final pets of the updated ROX-filer I wanted to know how to handle the stuff in the petbuild template.

If removing the \<backdrop\> line from PuppyPin in the petbuild wouldn't break some sed substitution in woof-CE then it wouldn't matter if the default image is a jpeg, png or svg.

My preference would be to move _everything_ in the petbuild template somewhere else, but I don't know what the consensus is.  rox_config pet? - needs upload to ibiblio for updates.  rox_config in woof-CE rootfs-packages? - I don't know if someone wants to obsolete rootfs-packages.

I have made some changes to the files in the petbuild template, but I haven't made a commit yet because I don't know if I should put it somewhere else?

**Comment by wdlkmpx** [comment]
The problem with rootfs-packages has been minimized.. now all rootfs-packages are included in the build by default (excluding the uefi stuff or jwm_config if a possible conflict is detected or something) unless there is a .conf file, which must be maintained.... The current problem is that 3builddistro is lacking some proper automation, so always have to click on the OK button. And it's boring.

'testing' is currently the experimental branch, so it's ok to add anything there, a bug will be detected as soon as somebody builds an iso.. but it will not be reported as i noticed some issues that i'm about to fix.

Other than that, rox_config rootfs-pkg is the way to go. but it will be overwritten by the pet pkg... the pet pkg in all woofce puppies must be replaced (from common32/64/raspi).. and the rox petbuilds in the petbuilds repo should all be  the same... there are things that need some work and attention, it's better to keep them in the main repo as a rootfs-package.

rootfs-packages/ptheme/pinstall.sh edits the rox <backdrop>. but the backdrop must always exist, i mean it should be default.jpg/png/svg... this default.jpg/etc should be in rootfs-skeleton or the rox_config.. sky.svg -> default.svg and other small backgrounds in jpg or png format.. or maybe... sky.svg ---> default.svg/png/jpg ...

**Comment by woodenshoe-wi** [comment]
Ok.

I will edit the petbuild to remove the stuff that is moved to rox_config, so the new pet will not overwrite rox_config.

I will push my changes to rootfs-packages/rox_config in the testing branch, and I will leave PuppyPin unchanged.

I will work on this as I have time, so I might not be making these changes immediately.

Thanks for the feedback.  😃

**Comment by woodenshoe-wi** [comment]
@peabee

Would it be possible to upload the following pets to ibiblio but only add them to the package list in the testing branch?

https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/pet_packages-common32/rox-filer-8woodenshoe-i686_common32.pet
https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/pet_packages-common64/rox-filer-8woodenshoe-x86_64_common64.pet

They depend on rootfs-packages/rox_config 82f6ed8 which is only in the testing branch.

**Comment by peabee** [comment]
Uploaded - but will leave you or @wdlkmpx to add lines to

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/x86/Packages-puppy-common32-official

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/x86_64/Packages-puppy-common64-official

rox-filer-8woodenshoe-i686_common32|rox-filer|8woodenshoe-i686_common32||Filesystem|1296||rox-filer-8woodenshoe-i686_common32.pet|+gtk+2|Light weight gtk file manager|common32|||

rox-filer-8woodenshoe-x86_64_common64|rox-filer|8woodenshoe-x86_64_common64||Filesystem|1272||rox-filer-8woodenshoe-x86_64_common64.pet|+gtk+2|Light weight gtk file manager|common64|||

**Comment by wdlkmpx** [comment]
The common64/32 rox-filer will be enforced in all builds, i'll build a
couple of isos, if something's wrong people will probably be unable to
get to the desktop and that's good.

In that case new binaries should be compiled for that specific pup,
it's that simple..

When something is in the repo it's just easier to test, those who
build regularly will notice the issues, otherwise asking people to do
something is so old-fashioned

It might be time to compile binaries for the raspbian puppy ...

I'll perform some tests, rox is probably more usable now, it normally
forces you to use the pointer for everything, i mostly use the
keyboard for everything unless i'm on a tablet/phone. so i see it
being useful, but not on a desktop pc/laptop

**Comment by woodenshoe-wi** [comment]
> The common64/32 rox-filer will be enforced in all builds

I had a feeling that would happen...  That is why I wanted to get as much testing done as possible before I asked peabee to upload the pets, there would probably not be any option of individual builders choosing which version that they wanted to use.

> It might be time to compile binaries for the raspbian puppy ...

I did that yesterday, they are located at https://gitlab.com/woodenshoe-wi/petbuilds-out/tree/master/puppylinux/arm and I can make a tarball of the whole set if @peabee wants to upload them to ibiblio, but I am not planning to maintain the raspup build until January or later and currently there are missing packages and of course that nasty bug I found at the bottom of #1147

**Comment by wdlkmpx** [comment]
Well, i built a upupbb with the new rox-filer and it booted to
desktop, no errors in xerrs.log.. tried to crash it by using random
functions

Tested the copy/cut & paste operations and they seem to work fine.
This certainly makes rox a better app. I'm surre some people won't
like the enhancements, they want rox to remain as unusable and hateful
as possible... so this probably means this is for puppy 8

I already have local changes that enforce the new rox-filer in all
x86* builds, people can test it for sometime before this is merged to
master

**Comment by peabee** [comment]
Experimental UPupCC (Cosmic Cuttlefish).....
BUILD_FROM_WOOF='testing;24b5d00c;2018-08-19 13:04:23 +0800'
ISO download:
https://my.pcloud.com/publink/show?code=XZu3is7ZnFMNWV6ntiSJIqzBaP95W8YGdCTk

2 probable woof-ce issues:
- PPM is not showing repo contents, but they do show when a search is done
- there is something wrong with the syslinux_FIXUPHACK package-template - it is deleting files in usr/share/syslinux which doesn't exist in an ubuntu build.....

New rox-filer - bit of a surprise when ctrl-X key no longer worked!
Has Richards analogue modem changes ... I think

![screenshot](https://user-images.githubusercontent.com/5926865/44621717-19c0c700-a8a3-11e8-94e1-b1b362305caf.png)

@wdlkmpx 
@woodenshoe-wi 
@rserwin1

**Comment by woodenshoe-wi** [comment]
> New rox-filer - bit of a surprise when ctrl-X key no longer worked!

But the "Delete" key does work, right?  It was a requested change.  Ctrl-X is now supposed to be "Cut to clipboard".

**Comment by wdlkmpx** [comment]
I'll test the iso and will probably fix a couple of issues

There are many changes, including some functional changes in rox..
this is isn't enough to make rox my primary filemanager, but at least
now i can test any woofce puppy without getting depressed, unless i
hear the first boot barks

I don't how people will react to some changes, but in any case,
releases should happen after some months...

And i'll merge the 'remove the multiarch symlink' pull request next
week.. i haven't identified any particular important bug so far. so
it's mergeable.. i'll comment more about it later (issues in external
scripts are easy to fix)

ROX

File/Dir->Rename... should be triggered by F2, i guess this is
configurable but i don't know how.. rox_config or hard-coded F2..
whatever

Window->Terminal Here: there should be a way to make F4 launch a
terminal window besides the obscure ` key

**Comment by woodenshoe-wi** [comment]
> i guess this is configurable but i don't know how..

https://sourceforge.net/p/rox/mailman/rox-users/thread/20030115112945.GA4385%40everest.ecs.soton.ac.uk/

Quick answer is make a file `/root/.gtkrc-2.0.mine` with the line `gtk_can_change_accels=1` in it and restart the xserver or reboot.  After that you can hold the mouse over the menu entry you want to change and press the key you want.

To make the change in rox_config I think adding the file  
`woof-code/rootfs-packages/rox_config/root/.config/rox.sourceforge.net/ROX-Filer/menus2`  
with the following lines will make the changes the default, but I haven't tested this with a woof build.  
```
(gtk_accel_path "<filer>/Window/Terminal Here" "F4")
(gtk_accel_path "<filer>/File/Rename..." "F2")
```

**Comment by peabee** [comment]
@wdlkmpx  2 more problems.....

- my laptop crashes to unresponsive black screen on reboot/shutdown (desktop is OK)

- /root/.jwm/window_buttons is not being populated correctly by 3builddistroZ

@woodenshoe-wi - yes delete key works - just a "shock"

I don't think this "testing" build is suitable for exposure to a wider testing audience on the forum at this time......

**Comment by wdlkmpx** [comment]
I fixed the ppm issue reported by peabee
also fixed /usr/share/doc/index.html.top (wrong info)
added some more changes
the syslinux pkg is too big and it should be a pet pkg.. but what version ..

Pkg and puppy-get: they work fine even when /root/.packages is now a symlink to /var/packages

puppy-get requires /tmp/pup_event_sizefreem, but doesn't fail
i can patch this, but reaching out to people is so....... boring


For some unknown reason peabee is disapproving an improvement again
but it's up to woodenshoe to make a different rox version the default one

of course i suggested what you see, so i'm the one want to blame

i'm done with rox, i don't want to know anything about it...

Now the new bug report.. does the same reboot issue happen in upupbb?

i also really don't recommend releasing these non-LTS upups..
even when you explain people how things work, they will keep and remaster
the isos even years later..

there's someone uploading every single iso to archive.org.. killing resources for more important things

there should be an alternate forum where this stuff can be safely posted and removed
when testing is finished..

to be able to reproduce the 3builddistro bug, i probably need your config files.. upload them to smokey01 or something..

**Comment by woodenshoe-wi** [comment]
@wdlkmpx Just to make it clear it was Smithy who requested the "Delete" key binding change, I don't want to give the impression that I am blaming you for asking for it and I do think it is a good idea.  I don't think peabee is against the change, just hasn't been following the "ROX-Filer 2.11 patched" thread and was surprised by the change.
http://murga-linux.com/puppy/viewtopic.php?p=995638&search_id=1928932276#995638

There are some other changes to the user interface documented in that thread that need to somehow be communicated to users...

**Comment by woodenshoe-wi** [comment]
> ....just needs explaining in big letters as its a major UI change....

I completely agree, but where would be a good place?

**Comment by peabee** [comment]
Updated version of upupcc-18.08-alpha - same url as above.
https://my.pcloud.com/publink/show?code=XZu3is7ZnFMNWV6ntiSJIqzBaP95W8YGdCTk
BUILD_FROM_WOOF='testing;7d11d6f3;2018-08-26 14:18:11 +0800'
Kernel changed to 4.18.5 64-bit - cures laptop shutdown crash
PPM now working - thanks
window-buttons now fixed - was a problem with rsvg-convert in my build system - cured by building in upupcc
OK now to announce on forum "woof-ce needs you" for wider testing???

Good places to announce rox-filer ui changes = forum (woof-ce needs you + announcements), blog, newsletter etc etc....

**Comment by woodenshoe-wi** [comment]
I can post on the forum as soon as I finish writing the announcement, the deadline for the newsletter was the 20th so that might end up in the next month, but which blog(s), who would I contact?

**Comment by peabee** [comment]
I can post on the official blog (which to be honest isn't much used....)
http://blog.puppylinux.com/

**Comment by woodenshoe-wi** [comment]
http://murga-linux.com/puppy/viewtopic.php?t=114169  
and  
http://murga-linux.com/puppy/viewtopic.php?p=1003118#1003118

At some point I have to update the manual html file and make new pets, but not tonight.

**Comment by woodenshoe-wi** [comment]
@peabee
I have been working on the manual today and was wondering if you or someone you know wants to proofread it before I make new pets.

  - Chapter 2. Invoking
    * Running as root
Updated to reflect that warning has been removed.
  - Chapter 3. Mouse button and key bindings
Added instructions to enable user-defineable key-bindings in
"\~/.gtkrc-2.0", "\~/.gtkrc.mine" or "\~/.gtkrc-2.0.mine" as appropriate.
  - Chapter 5. The toolbar
Added descriptions for new toolbar buttons.
  - Chapter 6. The menus
Updated the menu entries.
    * The display menu
I haven't added an entry for  
Display->Filter Directories With Files  
because I don't know how it works, it doesn't seem to work for me.
  - Chapter 13. Action windows
    * Action window options
Added new options.
  - Chapter 17.  Application directories
Added documentation for comment files.
  - Appendix B. Manual page
Added entry for --url=URL

And fixed broken links.

The changes can be seen at https://github.com/woodenshoe-wi/rox-filer/commit/120406403cc8118319f49721ba418585bcfad1fe

The latest version of the manual is at https://github.com/woodenshoe-wi/rox-filer/raw/master/ROX-Filer/Help/Manual.html but you might have to save it on your computer before the web browser will open it as an html file.

**Comment by peabee** [comment]
> the syslinux pkg is too big and it should be a pet pkg.. but what version ..
Slackware uses 4.07
Bionic Beaver is 6.03
Cosmic Cuttlefish is 6.04
Here's a 32-bit .pet made from the 2createpackages UPupBB version:
[syslinux-6.03.pet-false.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2343395/syslinux-6.03.pet-false.zip)

**Comment by woodenshoe-wi** [comment]
> Slackware uses 4.07

Maybe from this petbuild? 
https://github.com/puppylinux-woof-CE/petbuilds/commit/2a722c5d0f19f2b588a8e8c02a7264162ec0b7e0

I see a readme.txt file that says,

> should not upgrade until stuff is fixed in woof

**Comment by wdlkmpx** [comment]
I'm not fond of syslinux but i guess the version to use should be 5.0
or something. I don't use it, i try to avoid it, so it's hard for me
to properly test it

I remember that in the precise days BK said that syslinux 5 or 4?
didn't show the splash img, so had to revert to an older version

But the syslinux issue in the upups was raised by phil.. xenial also
has syslinux 6.0, this syslinux is split into several directories
(syslinux-common).. bios, efi32, efi64... woofce scripts are confused
by this since they expect to find only 1 file with a certain name, but
they find 3 and may pick the wrong one.

This is info that should in the blog as well... blogging is not my
thing, i kind of lost interest in basically everything and want to
keep to myself

I think it's obvious that i don't hold the murga forum in high regard,
what drives to post there is some sort of negativity rather than true
interest.. but i'll try to read it often, there's info to fix stuff

But peabee or anybody can copy some of my most informative comments
and add them to the blog or something (without mentioning me), i
authorize it..

**Comment by woodenshoe-wi** [comment]
I use extlinux (syslinux 6.03) that I installed myself because I couldn't get grub2 to load memtest86+ on the most recent computer that I assembled.  (An Intel motherboard with a BIOS update from 2009)

With this version it has been broken up into separate modules.  
ldlinux.c32 ldlinux.sys libcom32.c32 libgpl.c32 libutil.c32 menu.c32 vesamenu.c32

If the splash img used gfxboot, according the the readme at https://github.com/openSUSE/gfxboot it only works with syslinux-4

According to the syslinux wiki VGA mode 640x480 16-color graphics are supported directly.

The new version of syslinux is supposed to include EFI support, but I don't have any computers new enough to test it.

I don't know which direction (older or newer) you want to go with this, but I may be able to help test stuff, especially if it can wait until January...

**Comment by wdlkmpx** [comment]
By loading the iso in qemu i see syslinux works.. but it doesn't show
the boot splash, i'm quite happy with that to be honest

It was micko who was testing and fixing syslinux/uefi stuff

I don't know maybe testing this using puppyinstaller/remasterpup2 and
see if the result is bootable or something... i just don't do that.

I think the strategy is a bit different for the eufi build, i haven't
studied how it works.. i do have a couple of pcs that support uefi
boot, but i usually boot puppy in the older ones i want to kill so
badly, so i can find inspiration to test and code a bit, otherwise i i
just want to do something else

**Comment by woodenshoe-wi** [comment]
I have been experimenting with gfxboot and I think I have it working with syslinux 6.03 in QEMU, so I am guessing that the openSUSE readme is out of date.

**Comment by woodenshoe-wi** [comment]
@peabee
New pets,

32 bit
https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/pet_packages-common32/rox-filer-9woodenshoe-i686_common32.pet

64 bit
https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/pet_packages-common64/rox-filer-9woodenshoe-x86_64_common64.pet

and ARM
https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/arm/pet_packages-raspup/rox-filer-9woodenshoe-armv6l_stretch.pet

**Comment by woodenshoe-wi** [comment]
@wdlkmpx I don't know what you want to do with syslinux and woof-CE, but I was able to compile version 6.03 as common32/64 pets.

These should **NOT** be uploaded to ibiblio unless they are tested first and haven't broken anything in woof-CE!

https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/pet_packages-common32/syslinux-6.03-i686_common32.pet

https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/pet_packages-common64/syslinux-6.03-x86_64_common64.pet

You can download them and put them in your local-repositories directory, editing the proper package list file.

Or it is also possible to use my gitlab repo for test woof builds by

   1. adding  
`z|https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/Packages-puppy-common32-woodenshoe|z`  
or  
`z|https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/Packages-puppy-common64-woodenshoe|z`  
as appropriate to PKG_DOCS_PET_REPOS in DISTRO_PET_REPOS,

   2. adding  
`z|https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux|Packages-puppy-*-woodenshoe`  
to PET_REPOS in DISTRO_PET_REPOS

   3. and adding  
`Packages-puppy-common32-woodenshoe`  
or  
`Packages-puppy-common64-woodenshoe`  
as appropriate to PACKAGELISTS_PET_ORDER in DISTRO_PET_REPOS.


All 3 steps are needed.

If you want to be absolutely certain that the pets from my gitlab repo are chosen you can add `|pet:woodenshoe` to the end of the line in DISTRO_PKGS_SPECS-\*

**Comment by woodenshoe-wi** [comment]
@wdlkmpx if you would like me to see if I can fix the missing boot splash could you give me a link to an iso that has the problem?

**Comment by peabee** [comment]
> New pets,
Uploaded.....

**Comment by woodenshoe-wi** [comment]
Thanks peabee, I already submitted an article for the October issue of the Puppy Linux Newsletter, so the ROX-Filer project should be pretty much finished now.

**Comment by woodenshoe-wi** [comment]
>   By loading the iso in qemu i see syslinux works.. but it doesn't show the boot splash, i'm quite happy with that to be honest

I didn't want to randomly download ISOs looking for the problem, so I thought I would test some ISOs I already had.  On my first test, upupbb-18.05.iso I found the problem...  the logo.16 file is 0 bytes.

Looking at 3builddistro-Z, logo.16 is made from logo.gif, which in turn is made with woof-code/boot/boot-dialog/textongif.sh which uses `giftopnm` `ppmlabel` `ppmquant` and `ppmtogif`.

I am guessing that if one of these programs is missing from the host distro running woof-CE it will cause the problem.  The problem might not have anything to do with syslinux.

**Comment by wdlkmpx** [comment]
Hmmm yeah a program is probably missing.. for non-uefi builds this can
be solved by using a g4dos iso..

The uefi cd is created by
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/support/uefi_cd.sh
.. it doesn't use netpbm .. i guess the non-uefi traditional syslinux
cd should use similar code ?

# update and transfer the skeleton files
if [ -n "$PPMLABEL" ];then # label the image with version
	pngtopnm < ${RESOURCES}/${pic}.png | \
	${PPMLABEL} ${GEOM} ${TEXT} | \
	pnmtopng > ${BUILD}/${pic}.png
else
	cp -a ${RESOURCES}/${pic}.png 	$BUILD
fi

I don't know. But the only thing that worries me a bit is peebee's
report about a shutdown issue with kernel 4.xx? (what kernel version?)
in upupcc, i don't have that issue, but it shouldn't happen anywhere,
i wonder if it has something to do with recent changes in rc.shutdown

I'll keep commenting about that issue later..

**Comment by woodenshoe-wi** [comment]
Syslinux-6.03 might cause problems too, I think it needs ldlinux.c32 added to the iso and so far I can't get the boot splash working in my test iso.

I just wanted to let you know about the unrelated problem with the 0 byte logo.16 file.

**Comment by peabee** [comment]
(what kernel version?)
4.14.67 is giving problems - but only on my laptop.....

**Comment by woodenshoe-wi** [comment]
> By loading the iso in qemu i see syslinux works.. but it doesn't show the boot splash, i'm quite happy with that to be honest

Sorry to bring bad news, but I found a patch in the syslinux mailing list archives to get the boot splash working again :grinning: 

The patch was from July 2015, and the maintainers want to switch to using VESA instead of going though the BIOS directly so the consensus seems to be to do nothing and leave it broken, but not remove the broken code or the documentation that references the broken functionality...

I managed to apply the patch to the version tagged syslinux-6.04-pre1 and compile everything, but these are NOT the official binaries, they are what I compiled and the syslinux maintainers probably don't want to hear any bug reports about them :grinning: 

I only tested  isolinux.bin and ldlinux.c32 with qemu, other than that the pets are completely untested, but here they are anyway,

https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/pet_packages-common32/syslinux-6.04-pre1-patched-i686_common32.pet

https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/pet_packages-common64/syslinux-6.04-pre1-patched-x86_64_common64.pet

The patch was originally against syslinux-6.03 but that version wouldn't work for me in qemu, even un-patched.

**Comment by peabee** [comment]
There are reports of shutdown problems with 666philb's new bionicpup64 using kernel 4.14 on the forum:
http://www.murga-linux.com/puppy/viewtopic.php?t=114311

**Comment by wdlkmpx** [comment]
I see other bugs are  being reported. i'll fix some of them testing in dpup.

dancytron reports issues with rox in http://murga-linux.com/puppy/viewtopic.php?p=1005129#1005129

Now onto the shutdown issue.. one or more of these  4 sfs files might fix it.
Load as the adrv in a 'problematic' install
[adrvs4shutdown.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2402425/adrvs4shutdown.zip)
test and report your findings..

I'll test the syslinux pet one of these days..

**Comment by peabee** [comment]
All tests upupcc-18.09 with kernel 4.14.67
1, 2, & 3 all stop reboot hanging on my laptop....but 3 seems to make the process quicker as there is less pause after "logout" appears.
4 doesn't work - drops out to a terminal prompt where commands are not actioned - needing power button shutdown.

**Comment by woodenshoe-wi** [comment]
>   dancytron reports issues with rox in http://murga-linux.com/puppy/viewtopic.php?p=1005129#1005129

I downloaded bionicpup64-7.9.3-uefi.iso from the link in the first post and I cannot reproduce the problems, at least running in RAM on first boot, so without more detailed steps to reproduce I'm afraid I can't do anything about it.
