### ISSUE TITLE
Unmount issue in recent Woof-CE

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#1236]
Testing recent Woof-CE build of Dpup Stretch 7.5
• BUILD_FROM_WOOF='master;2278b7db;2018-08-05 07:53:37 -0400'

Checking xerrs.log: There are no errors or messages when mounting partitions.

However, when unmounting partitions I see the following errors, though the partitions do appear to unmount correctly.

UNMOUNTING sda9 with pmount application:

/usr/sbin/pmount: line 454: [: too many arguments
/usr/sbin/pmount: line 133: * 1024: syntax error: operand expected (error token is "* 1024")
/usr/sbin/pmount: line 148: (-)*120/: syntax error: operand expected (error token is ")*120/")

---

UNMOUNTING sda9 by click of the partition X-overlay, or by selecting unmount in Right-click context menu:

sda9: invalid drive
Device sda9 is not active.
Command failed with code 19: No such device
umount-FULL: /mnt/sda9: not mounted
umount-FULL: /mnt/sda9: not mounted

**Comment by wdlkmpx** [comment]
Thanks for reporting.. i think i fixed both issues
https://github.com/puppylinux-woof-CE/woof-CE/commit/284421f2ae6f6aaa9713c1c2e1882e008997f34e
https://github.com/puppylinux-woof-CE/woof-CE/commit/e206fcca159ed8e1ea3e2a50626d57d65aecc437

I also added more commits i was supposed to add last week, which fix more issues and probably introduce new bugs

You might want to build a new iso and see if the issues are fixed (for you)

**Comment by radky2** [comment]
Thanks wdlkmpx,

New build of Dpup Stretch 7.5

 • BUILD_FROM_WOOF='testing;c43e9d4a;2018-08-07 23:53:12 +0800'

---

LAUNCHING pmount from Puppy XDG menu, with or without a partition already mounted:
 • /usr/sbin/pmount: line 454: [: too many arguments
 • /usr/sbin/pmount: line 133: * 1024: syntax error: operand expected (error token is "* 1024")
 • /usr/sbin/pmount: line 148: (-)*120/: syntax error: operand expected (error token is ")*120/")

LAUNCHING pmount from Right-click context menu of sda9:
 • /usr/local/pup_event/frontend_funcs: line 461: sda9: command not found

MOUNTING or UNMOUNTING a partition with pmount:
 • No error messages in xerrs.log

---

MOUNTING sda9 by click of desktop partition icon:
 • No messages in xerrs.log

UNMOUNTING sda9 by click of X-overlay of desktop icon, or by unmount option in Right-click context menu:
 • sda9: invalid drive
 • Device sda9 is not active.
 • Command failed with code 19: No such device
 • umount-FULL: /mnt/sda9: not mounted
 • umount-FULL: /mnt/sda9: not mounted

**Comment by radky2** [comment]
wdlkmpx,

• BUILD_FROM_WOOF='testing;c43e9d4a;2018-08-07 23:53:12 +0800'

My prior build of Dpup Stretch 7.5 with Woof-CE of 2018-08-07 was corrupt. Sorry!

The following results are from a corrected build, testing mount/unmount/pmount:

---

LAUNCHING pmount from Puppy XDG menu, with or without a partition already mounted:
• No messages in xerrs.log

LAUNCHING pmount from Right-click context menu of sda9. Pmount launches correctly but I see the following error:
• /usr/local/pup_event/frontend_funcs: line 461: sda9: command not found

MOUNTING or UNMOUNTING a partition with pmount:
• No messages in xerrs.log

---

MOUNTING sda9 by click of desktop partition icon:
• No messages in xerrs.log

UNMOUNTING sda9 by click of X-overlay of desktop icon, or by unmount option in Right-click context menu. The partition unmounts properly but I see the following error:
• sda9: invalid drive

**Comment by wdlkmpx** [comment]
Ok the issues are now fixed. Let me know if something's wrong..
