### ISSUE TITLE
sfsget should not be in rootfs-skeleton

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1241]
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/sbin/sfsget

Default build accesses repos which are not updated and contain very old versions of apps....it should not be in rootfs-skeleton

**Comment by wdlkmpx** [comment]
sfsget needs a config file. 1) repo url 2) list of sfs pkgs.. in fact it should be part of the ppm

but the problem is... who is going to do that.

not many people are willing to work with git, you can see all the changes, and know the history of each file.. but it's not enough..

**Comment by peabee** [comment]
default should be no sfs offered if system builder has not provided a config file?

what is the format and location of the config file?

I prefer to use SourceForge for repos but I would guess download from SF is not supported...

**Comment by wdlkmpx** [comment]
Try this mod - it's just a test

- It works without a config file (have yet to verify this) - usual behavior

- The included config file makes sfsget get a list of sfs pkgs of lxpup's browsers (something i sometimes want to download).. this is not static, it downloads the list from sourceforge.

Untar, open a terminal window and and type ./sfsget install a sfs pkg and let me know what you think ..
[sfsget-mod.tar_fake.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2297541/sfsget-mod.tar_fake.zip)

**Comment by peabee** [comment]
Thanks - quick test - yes browser downloaded AOK.
Bit old-fashioned in that it talked about boot manager and rebooting to gain access to the sfs whereas these days sfs-load can be used for instant gratification....
Also, more than 1 repo is needed (probably) - e.g. LxPupSc's devx and kernel sources are stored in a different SF directory from the browsers....
Still not sure that something that is so build dependent should be in rootfs-skeleton though?? 
Unless maybe the sfsget.config contents should be made by 3builddistro-Z from build specific info in __00build.conf ??

**Comment by wdlkmpx** [comment]
I actually didn't download anything, but now i see outdated stuff

What you want is specify only one repo and a special variable listing
sfs packages with relative p5th to the sfs repo

Something like this

SFS_PACKAGES='path/to/file.sfs
p/t/f.sfs
etc'

or

SFS_PACKAGES_LIST='path/to/sfsget.lst'

This list can be updated outside woofce

..to be implemented. Tomorrow ma7be

sfsget should require sfsget.conf indeed and sfsget.conf should b3 in
woof-distro

But what do youthink

**Comment by wdlkmpx** [comment]
In puppy, repos = mirrors

I've implement some features, i added lxpup_* scripts and config files so you don't have to configure anything and just test sfsget.

If you run ./sfsget you'll see an error, it's picking the default config. if you run the lxpup_* scripts you'll see interesting stuff, those scripts have only 1 line, you'll learn how to use sfsget in different ways... test this and tell me what you think about it...
[sfsget_mod.tar_fake.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2299802/sfsget_mod.tar_fake.zip)

**Comment by peabee** [comment]
Looks good - seems to cover most situations....only suggestion is that an option to download to the frugal install subdirectory as well as the partition root would be nice....

**Comment by peabee** [comment]
Can also download other types of file but then sfs-load fails after the download - perhaps another check needed?...
e.g.
SFS_REPOS="https://sourceforge.net/projects/zestypup/files/"
SFS_DIR=Upup-Bionic/devx/
SFS_PKGS='kernel_headers-4.9.96-lxpup-i686.pet'

**Comment by wdlkmpx** [comment]
I think it should also handle pet pkgs, a hidden feature. But it's easy to make it ignore unwanted files

By the way, commit 670759239fd2f3e077d413af9b51939575331f07 assumes that the files in

www.01micko.com/wdlkmpx/puppylinux_arm_pet_packages-stretch.tar

are already uploaded to

http://distro.ibiblio.org/puppylinux/arm/pet_packages-stretch/

I remember saying that days ago, but i can't find the comment, i thought you were just ignoring it, but it probably was considered spam by gmail or something

**Comment by wdlkmpx** [comment]
This sfsget supports a .conf file or exported variable from a script. Lists sfs files from a remote directory, but also supports .pet .tgz .txz .deb pkgs in static lists.. 

I tested a bit and it was working fine, but you can perform more thorough tests and report any issue or request, the more verbose the better

I think this can be useful to provide a generic get_browser script with at least 2/3 versions of some browsers, at least for x86* 

repo/browsers_sfs/i686 (x86)
repo/browsers_sfs/x86_64
repo/browsers_sfs/arm
repo/browsers_sfs/aarch64 (arm64)

The script could just determine the os arch and present a list of available browsers.. oh and wine.. there's someone on the forum that compiles all wine versions

**Comment by wdlkmpx** [comment]
The file is here: 
[sfsget_mod2.tar_fake.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2321115/sfsget_mod2.tar_fake.zip)

**Comment by wdlkmpx** [comment]
I updated sfsget in https://github.com/puppylinux-woof-CE/woof-CE/commit/37b7f2a94b04b37ed1c812ab519504cfed49928a

I edited slightly to allow it to work without a sfsget.conf file

You can add /etc/sfsget.conf in your builds or export variables in a script and call sfsget

.. well, i guess you know how to use it, i haven't tested the script that much, it seemed to work fine.

Testing in slacko i noticed it uses a different sfsget, probably installed by sfs_manager or something ... hmm i couldn't get it work on first boot

**Comment by mrfricks** [comment]
hi wdlkmpx ,
i'm not sure how this works.
can i have an example sfsget.conf that looks in /puppylinux/pet_packages-bionic64/ & /puppylinux/test/bionicpup/

**Comment by wdlkmpx** [comment]
There is a bug in sfsget

replace this line:
if [ -f $KONF ] ; then #CONF_FILE is optional...

with this
if [ "$KONF" ] && [ -f $KONF ] ; then #CONF_FILE is optional...

That should work for /puppylinux/pet_packages-bionic64/

For /puppylinux/test/bionicpup/ create /etc/sfsget.conf
SFS_REPOS=http://distro.ibiblio.org/puppylinux/test/bionicpup

it works with one repo and mirrors of that repo (repos), it can be
improved to support to multiple different repos, but then idea of
mirrors will not apply

sfsget retrieves a file list from the remote directory, so it only
requires one repo and mirrors. you can add and remove sfs files.

Here are more examples, but with an outdated sfsget:
https://github.com/puppylinux-woof-CE/woof-CE/files/2299802/sfsget_mod.tar_fake.zip

**Comment by peabee** [comment]
#!/bin/sh
export SFS_REPOS="https://sourceforge.net/projects/lxpup/files/"
export SFS_DIR=Other/LxPupSc64/browsers
./sfsget $@

produces slightly different duplicate entries for same sfs:
![screenshot](https://user-images.githubusercontent.com/5926865/50476681-e6ad5200-09c0-11e9-9b6b-b7759e49f89a.png)
