### ISSUE TITLE
/lib/firmware/regulatory.db should not be deleted in 3builddistro-Z

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1248]
line 1325 of 3builddistro-Z....

/lib/firmware/regulatory.db and regulatory.db.p7s should not be deleted....they come from package wireless-regdb and are needed for crda

If they are put into zdrv or fdrv instead they won't be kept up to date

**Comment by wdlkmpx** [comment]
Caveat emptor

Yes i want to eliminate support for all-firmware directories and tarballs and i think using udev rules is the standard practice nowadays... so green light

**Comment by rserwin1** [comment]
Thanks.  It is now on my short To-Do list.
