### ISSUE TITLE
/packages-templates/lsb-base

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1253]
there's a problem with /packages-templates/lsb-base/lib/lsb/init-functions.
if you try to restart a DAEMON  such as 
```/etc/init.d/dbus restart ``` 
you don't get a success or fail message so can't tell if it has actually started.

The following image shows restarting dbus first with init-functions from the template, and second with init-functions from the lsb-base.deb

![lsb-base-problem](https://user-images.githubusercontent.com/1454550/45974783-5581b480-c03a-11e8-813f-2f0a3b42b75c.png)

**Comment by wdlkmpx** [comment]
ntpdate is missing. 

/var/packages/builtin_files/ntpdate:
- /usr/src/dev/ntpdate-build-recipe

How to fix:

yes|ntpdate|ntpdate|exe,dev,doc,nls 

Installing nptdate from the PPM might cause unexpected behavior.. can't remember. there's a FIXUPHACK that should also be available for the PPM.. someday

**Comment by mrfricks** [comment]
ha my ntpdate package is empty !
