### ISSUE TITLE
ncurses template

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1256]
i don't know if this is just in bionicpup64 but after the changes to the ncurses template, xdialog doesn't render properly in the terminal. 

It appears to need the /terminfo/x/xterm from the old template
the read me says it's from Puppy 2.17 :)

![img_20180924_221440](https://user-images.githubusercontent.com/1454550/46216801-49e30600-c338-11e8-8d98-5f1748bce06c.jpg)

**Comment by ninaholic** [comment]
Hello mrfricks!

This happens for me too in newest slacko-5.8.2 build when I run xorgwizard from terminal. The only difference is my screen says Xorg 1.12.4.
