### ISSUE TITLE
more xdialog issues

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1257]
Not sure if this is just a bionicpup64 thing but the xdialog yes/no boxes aren't working properly. This is apparent in the first save dialog when shutting down from a prompt, or when you've set your save interval to 0 and are asked if you want to save or not at shutdown.

pressing the right cursor produces random artifacts such as # or simulates pressing enter.
tab seems to work ok. i've tried xenials xdialog and the problem persists

any ideas

in the picture you can see the last thing i typed at the prompt appear on the left (reboot) when presing the cursor keys
![img_20180925_111008](https://user-images.githubusercontent.com/1454550/46218371-4a7d9b80-c33c-11e8-82fd-6a46a299947d.jpg)

**Comment by ninaholic** [comment]
The look and functionality is similarly messed up in slacko 5.8.2 too.

Also, fido has been renamed to finn? :laughing:

**Comment by wdlkmpx** [comment]
It's 'dialog'. I think this issue is fixed, but needs confirmation

The bug was introduced when i added rc.shutdown to /etc/initttab .. it was triggered by busybox reboot/poweroff (init) and this somehow affects dialog/ncurses.. whatever, it just misbehaves.. now rc.shutdown is called by the 'poweroff' script again

**Comment by mrfricks** [comment]
Just tested and this is working for me now.

thanks wdlkmpx

**Comment by wdlkmpx** [comment]
Ok it looks like a major bug is fixed and apparently `export TERM=rxvt` completely fixes the rendering issues in the terminal...

Haven't tested in the slackos, perhaps ninaholic can confirm if this is fixed in slacko.. (a new build is required..)

**Comment by ninaholic** [comment]
@wdlkmpx yes, that did fix both the save box and xorgwizard for me too
