### ISSUE TITLE
librsvg issues

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1258]
Latest librsvg is 2.44.6
Slackware-14.2 and Ubuntu (BB & CC) are still using 2.40.20
Slackware-current has moved to 2.44.6
Besides the huge increase in size (2.40.20 <> 150KB; 2.44.6 <> 1.1MB) some (many?) hand crafted Puppy svg icons are not compatible with 2.44.x
For instance:
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-packages/pt_buntoo/usr/share/jwm/themes_window_buttons/Buntu/close.svg
does not work with 2.44.x (no cross is shown)
and needs
```
  <path style="stroke:#3C3B37;stroke-width:8" d="L 32 35 68 65" />
  <path style="stroke:#3C3B37;stroke-width:8" d="L 68 35 32 65" />
```
replacing with something like:
```
  <line x1="35" y1="65" x2="65" y2="35" stroke="black" stroke-width="8" stroke-linecap="round"/>
  <line x1="35" y1="35" x2="65" y2="65" stroke="black" stroke-width="8" stroke-linecap="round"/>
```

i.e. the changes are not simple....or automatable....
So - Puppy either has to stay using 2.40.20 and current icons in which case 2.40.20 needs to be "captured" as .pet and put into common32 and common64 or
all icons need to be reviewed and converted to a 2.44.x compatible format for the future.

@01micko and @zigbert may wish to comment?

**Comment by 01micko** [comment]
Just change d="L to d="M

**Comment by wdlkmpx** [comment]
ISO file?

I see  d="L only in jwmconfig/ptheme svg icons, it's easy to fix all the affected svg icons by applying 01micko's suggestion, assuming the same change works for all icons, but these 2 pkgs will remain unfixed (if affected):

ptheme_osX-0.4|ptheme_osX|0.4||Desktop;appearance|640K||ptheme_osX-0.4.pet|+ptheme,+jwm_config|Mac like theme for ptheme and jwm||||
ptheme_winXP-0.5|ptheme_winXP|0.5||Desktop;appearance|1136K||ptheme_winXP-0.5.pet|+ptheme,+jwm_config|windows XP look a like theme for JWM||||

**Comment by peabee** [comment]
Searching for d="L in woof-ce I get:

/rootfs-skeleton/usr/lib/gtkdialog/box_splash
/rootfs-skeleton/usr/lib/gtkdialog/svg_bar
/rootfs-skeleton/usr/lib/gtkdialog/xml_info
/rootfs-skeleton/usr/sbin/pmount
/rootfs-skeleton/usr/share/backgrounds/Sky.svg
/rootfs-skeleton/usr/share/doc/home.htm
/rootfs-skeleton/usr/share/doc/index.html.top
/rootfs-skeleton/usr/share/doc/release-skeleton.htm
/rootfs-skeleton/usr/share/pixmaps/puppy/bulb.svg
/rootfs-skeleton/usr/share/pixmaps/puppy/calculator.svg
/rootfs-skeleton/usr/share/pixmaps/puppy/compass.svg
/rootfs-skeleton/usr/share/pixmaps/puppy/graph.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Basix/close.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Basix/min.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Classic/close.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Classic/min.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Unix/close.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Unix/maxact.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Unix/max.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Unix/min.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/XPish/close.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/XPish/maxact.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/XPish/max.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/XPish/min.svg
/rootfs-packages/network_wizard/usr/share/locale/en/LC_MESSAGES/net-setup.mo
/rootfs-packages/pmusic/usr/local/pmusic/func_svg
/rootfs-packages/pmusic/usr/local/pmusic/func_trackinfo
/rootfs-packages/pmusic/usr/local/pmusic/themes/Gtk/album_art_radio.svg
/rootfs-packages/pmusic/usr/local/pmusic/themes/Gtk/icon_audio_cd.svg
/rootfs-packages/pmusic/usr/local/pmusic/themes/Nad5/album_art_radio.svg
/rootfs-packages/pmusic/usr/local/pmusic/themes/Nad5/icon_audio_cd.svg
/rootfs-packages/pt_buntoo/usr/share/backgrounds/buntoo.svg
/rootfs-packages/pt_buntoo/usr/share/jwm/themes_window_buttons/Buntu/close.svg
/rootfs-packages/pt_buntoo/usr/share/jwm/themes_window_buttons/Buntu/maxact.svg
/rootfs-packages/pt_buntoo/usr/share/jwm/themes_window_buttons/Buntu/max.svg
/rootfs-packages/pt_buntoo/usr/share/jwm/themes_window_buttons/Buntu/min.svg
/rootfs-packages/pt_faux_xfwm/usr/share/themes/xfdark/gtk-2.0/check1.svg
/rootfs-packages/pt_faux_xfwm/usr/share/themes/xfdark/gtk-2.0/check2.svg
/rootfs-packages/pt_faux_xfwm/usr/share/themes/xfdark/gtk-2.0/check3.svg
/rootfs-packages/ptheme/usr/share/backgrounds/Stardust bright.svg
/rootfs-packages/ptheme/usr/share/backgrounds/Stardust dark.svg
/rootfs-packages/ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/check1.svg
/rootfs-packages/ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/check2.svg
/rootfs-packages/ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/check3.svg
/rootfs-packages/ptheme/usr/share/themes/Stardust_dark_mouse/gtk-2.0/check1.svg
/rootfs-packages/ptheme/usr/share/themes/Stardust_dark_mouse/gtk-2.0/check2.svg
/rootfs-packages/ptheme/usr/share/themes/Stardust_dark_mouse/gtk-2.0/check3.svg

+ there are pets like netmon_wce .....

**Comment by 01micko** [comment]
Peter, the search is flawed as it returns way to many false positives. Add
preceding space and you get...

/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Basix/close.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Basix/min.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Classic/close.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Classic/min.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Unix/close.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Unix/maxact.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Unix/max.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/Unix/min.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/XPish/close.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/XPish/maxact.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/XPish/max.svg
/rootfs-packages/jwm_config/usr/share/jwm/themes_window_buttons/XPish/min.svg
/rootfs-packages/pt_buntoo/usr/share/jwm/themes_window_buttons/Buntu/close.svg
/rootfs-packages/pt_buntoo/usr/share/jwm/themes_window_buttons/Buntu/maxact.svg
/rootfs-packages/pt_buntoo/usr/share/jwm/themes_window_buttons/Buntu/max.svg
/rootfs-packages/pt_buntoo/usr/share/jwm/themes_window_buttons/Buntu/min.svg

Put that list in a file at the root of woof (I called it 'z') and make a
little script to fix the offenders (Make a backup first if you like)

Script follows:
-------------------------------------------------------------

#!/bin/sh

for i in `cat z`;do sed -i 's/ d=\"L/ d=\"M/g' `pwd`/${i};done
-------------------------------------------------------------
That should fix it.

Delete the file and script and commit.
