### ISSUE TITLE
drive icon issues

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1269]
drive icons seem not to refresh on boot

melon688 has posted the issue here http://murga-linux.com/puppy/viewtopic.php?p=1006518#1006518

 LateAdopter posted a workaround here http://murga-linux.com/puppy/viewtopic.php?t=114311&start=165

**Comment by wdlkmpx** [comment]
That workaround was applied in 
https://github.com/puppylinux-woof-CE/woof-CE/commit/8c8cf30650e59e94736459f7c207bdfb14c40b66#diff-77e66e89466cce60f170671421e4d6ca (May 22, 2018)

**Comment by wdlkmpx** [comment]
I don't understand what lateadopter says. the workaround was added months ago, it's like he's not seeing  it for some reason. it's probably a different .xinitrc

**Comment by mrfricks** [comment]
Yes it's my mistake, an old .xinitrc fix for xfce was getting in.
thanks

**Comment by wdlkmpx** [comment]
Well, people add custom .xinitrcs without the "workaround" and now those are supported as well. If there is something to add or fix in xinitrc, maybe a patch can make it happen
