### ISSUE TITLE
Disappearing desktop drive icons? testing;740d6961;2018-11-02

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1280]
Just done a rebuild with:
testing;740d6961;2018-11-02 19:10:07 +0800
including a full 2createpackages rebuild....

After a wmexit then xwin the desktop drive icons disappear :-((
They reappear if theme is "refreshed" with pTheme.

iso uploaded if anyone cares to investigate (upupcc-18.10+3-uefi.iso):
https://my.pcloud.com/publink/show?code=XZSpWM7ZPcbgp6Vs8lXVK8O6HxFcCjp6AN0V

**Comment by wdlkmpx** [comment]
No issues here. There must a be way to reliably trigger that bug

**Comment by peabee** [comment]
No issues with the uploaded iso? Or with your build?
It's triggered whenever you drop out to console and then restart with xwin....

**Comment by wdlkmpx** [comment]
There is a real bug, after using the eventmanager to change ${ICON_PLACE_ORIENTATION}, drive icons no longer appear after calling wmexit.

pup_event_frontend_d survives after X is killed and that is not expected. /sbin/pup_event_frontend_d refuses to run & call frontend_startup if another instance is already running

Dont release the iso (yet), i'll push a fix in a moment

**Comment by wdlkmpx** [comment]
By the way, there reason i added commit https://github.com/puppylinux-woof-CE/woof-CE/commit/5509b7c3cf66edb0c408535a1207a9b6f74dc68c  

was because it may have a fix for this "withdrawn" issue:
https://github.com/puppylinux-woof-CE/woof-CE/issues/1274

Among other unrelated changes..
