### ISSUE TITLE
Is that fix-usb.sh still works?

### ISSUE THREAD

**Issue by uzilla** [puppylinux-woof-CE/woof-CE#1283]
I saw the fix-usb.sh checking the value `$6` in the script, but on my xenialpup64 7.5 that the `Empty` only on `$7`.

**Comment by wdlkmpx** [comment]
Download this file: https://raw.githubusercontent.com/puppylinux-woof-CE/woof-CE/9653602506f80613bc5087a5aa0063d58cb0c0c7/woof-code/rootfs-skeleton/usr/sbin/fix-usb.sh
chmod +x fix-usb.sh and test

It was recently updated. Needless to say xenialpup64 7.5 is old. stuff gets fixed... i mean anybody can build and release a xenialpup64 iso today, and many issues will be fixed.. but it won't happen.

The latest woofce code can be found at
http://murga-linux.com/puppy/viewtopic.php?t=114505

**Comment by uzilla** [comment]
@wdlkmpx Thanks, i will try it later.
