### ISSUE TITLE
Soft links in /root can trigger filesystem recursion problems 

### ISSUE THREAD

**Issue by RedactedCode** [puppylinux-woof-CE/woof-CE#1284]
Note that the Woof-CE scripts cause the following two soft links to be created in /root:
.usr --> /usr
.etc --> /etc

They appear to be a hangover from the very early days of Puppy Linux, and don't seem to serve any current purpose.

Moreover, they can cause a significant problem for the unsuspecting user who attempts to make a recursive copy of /root, (for instance, rsync, cp or tar) .

These links are found to be referenced in :
woof-code/VCSMETADATA
and
woof-code/rootfs-skeleton/root/

but I may not have found all references.

**Comment by wdlkmpx** [comment]
I'll delete those symlinks this weekend, if nobody else does first
