### ISSUE TITLE
Conditional creation of .desktop files

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1286]
xorg_base_new/FIXUPHACK
The creation of the .desktop files should be conditional on the executables being included in the build.....

**Comment by wdlkmpx** [comment]
Those X apps look really bad, and xfontsel doesn't seem to work

I think none of those apps should have a .desktop file, with the possible exception of xcalc

Xorg-Video-Wizard.desktop is already in rootfs-skeleton

**Comment by peabee** [comment]
xcalc is actually the one causing me problems as it isn't in my build.....
