### ISSUE TITLE
No replacement for "/etc/rc.d/rc.network stop"

### ISSUE THREAD

**Issue by gyrog** [puppylinux-woof-CE/woof-CE#1294]
There's a problem with rc.shutdown in "master", at line 139 it calls "/etc/rc.d/rc.network stop" but there is no longer an "/etc/rc.d/rc.network".
So the wifi network is not stopped, so the save partition remains busy, and the shutdown is not clean.
I see this problem in the currrent bionicpup64.
My quick and dirty workaround, is to comment out lines 131, 138,139,140

**Comment by wdlkmpx** [comment]
I agree with the suggested change

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/etc/rc.d/rc.shutdown#L131

@rserwin1 Might have a say.

**Comment by rserwin1** [comment]
Rc.network has moved to the network wizard directory.  The fix should be to replace line 139 with:
 [ -x /usr/local/network-wizard/rc.network ] && /usr/local/network-wizard/rc.network stop

Network wizard being a separate package, now, presents the possibility that it may not be installed, hence the test.

I can submit that fix.  OK?

**Comment by gyrog** [comment]
NO.
If Network wizard is not installed, then we still end up with the problem,
i.e. the network is not stopped during rc,shutdown, the relevant partion remains "busy" so it's not umounted cleanly.

**Comment by gyrog** [comment]
How about, turn the "if" statement around:
if [ -x /usr/local/network-wizard/rc.network ]; then
 /usr/local/network-wizard/rc.network stop
else
current network stop code in rc.shutdown
fi

**Comment by rserwin1** [comment]
The networking code in rc.shutdown is obsolete.  It should have been 
updated when I reworked networking.  The real solution should be for 
rc.shutdown to run networkdisconnect, which does the same things as its 
code, but more precisely.  I will get on it right away.

wdlkmpx wrote:

**Comment by gyrog** [comment]
After further testing, it seems that the "dire consequences" I've been experiencing are not shared with a "normal " puppy. e.g. bionicpup64.

But of course the code in rc.shutdown still should be fixed.

The quick fix would be rerwin's fix in the bionicpup64 forum.

The proper fix is rserwin1's networkdisconnect suggestion.

**Comment by gyrog** [comment]
FYI.
During the testing of this stuff I also found a problem with "init" using "insmod" for processing "initmodules". It needs to be fixed to use "modprobe", and "initmodules" needs to be simplified to produce a list of just module names. "I will get on it right away. "
My plan is to apply the resultant patches directly to the 'testing' branch.

**Comment by gyrog** [comment]
Do we need  2 calls to "networkdisconnect" in rc.shutdown?
Could the "statistics" one be deleted, and the parameters removed from "networkdisconnect", so that it always did stats first and then killed the newtwork?

**Comment by rserwin1** [comment]
I made those changes in respect of the comment just above the 
network-shutdown code:

#100301 brought down below call to 'stop' service scripts, needed for 
lamesmbxplorer.
#bring down network interfaces (prevents shutdown sometimes)...

I take it that the statistic logic needs to run before the services are 
stopped and the shutdown must be done after that.  I don't know if that 
is still true, but I did not want to risk changing that order of things 
-- and taking responsibility for the consequences.



gyrog wrote:

**Comment by gyrog** [comment]
@rserwin1, I understand that you didn't want to change the rc.shutdown logic.

But I still think it's a reasonable question, is the current rc.shutdown logic necessary?
Can anyone see why the stats need to be updated before the 'stop' service scripts?
I can't.

**Comment by rserwin1** [comment]
I don't see why the "statistics" logic cannot run after the services are 
shut down.  The only network manager that uses a service (init.d) script 
is frisbee, which does not deal with those statistics.  The stats seem 
to be maintained only for simple_network_setup and pupdial, which do not 
have "service" scripts.

I will make the appropriate updates to rc.shutdown and 
networkdisconnect.  I will also move the call to modemdisconnect to 
after the services, for the same reason.


gyrog wrote:
