### ISSUE TITLE
Desktop drive icons disappear after pTheme theme change

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1306]
BUILD_FROM_WOOF='testing;7861abba;2018-12-31 00:59:24 +0800'
Problem with pTheme - after a theme change, desktop drive icons disappear - they reappear if a window manager restart is done.

**Comment by peabee** [comment]
Bump - @zigbert  @wdlkmpx 
Running ptheme in:
https://sourceforge.net/projects/spup/files/ScPup/ScPup-19.01%2B0-uefi-T.iso/download
which has:
GNU bash, version 5.0.0(1)-release (i586-slackware-linux-gnu) & sed (GNU sed) 4.7
gives a sed error:
`/usr/local/jwm_config/theme_switcher: line 42: [: #444: unary operator expected
/usr/local/jwm_config/theme_switcher: line 52: [: #333: unary operator expected
sed: -e expression #1, char 38: unterminated `s' command`
and desktop drive icons disappear after a theme change

whereas
running ptheme in:
https://sourceforge.net/projects/zestypup/files/Upup-Cosmic/upupcc-18.10%2B11-uefi.iso/download
which has:
GNU bash, version 4.4.19(1)-release (i686-pc-linux-gnu) & sed (GNU sed) 4.5
there is no sed error
and desktop drive icons do not disappear on a theme change

**Comment by zigbert** [comment]
I'm on holiday without computer, so can't fix until back home... Next week.

**Comment by peabee** [comment]
Thank you - can confirm now fixed.
