### ISSUE TITLE
Icon pileup - rox pinboard

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1311]
@wdlkmpx 
Vertical drive icon layout (left or right)
Rox -> Options -> Pinboard
Change Icon Grid Step from Fine to either Medium or Coarse
Restart Graphical Server

Result - all partition/drive icons except the first are displayed on top of each other at the same location on the pinboard.....

**Comment by f0xpup** [comment]
I found that only a few values of Spacing for ROX icons give proper line of icons for the drives/partitions when grid step is not Fine. 
The value for Spacing has to be 48 at least. Good values are 64 and 96.
Decreasing this values by 1 at a time, gives a pile for the drive icons on a place closer and closer to the start of the line. Biggest pile and lowest place for the pile is on 2nd place.

I first discovered this in dpup Stretch RC4 from radky. It is the same in ScPup64.

**Comment by peabee** [comment]
pTheme currently sets
ICON_PLACE_SPACING=90
in etc/eventmanager
from values in /usr/share/ptheme/eventmanager_driveicons/Labeled left
and /usr/share/ptheme/eventmanager_driveicons/Labeled right
This value should be a multiple of the Roxfiler Pinboard Icon grid step:
2 for Fine; 16 for Medium; 32 for Coarse
therefore changing it to 96 covers all 3 possible steps.
https://github.com/puppylinux-woof-CE/woof-CE/pull/1315 raised
