### ISSUE TITLE
devx_xenialpup_7.5.sfs

### ISSUE THREAD

**Issue by ibelieveinpup** [puppylinux-woof-CE/woof-CE#1316]
I procured devx from SFS-Load on-the-fly to use gcc.
When invoking gcc I get the following error message 

 fatal error: /usr/include/sys/cdefs.h: Too many levels of symbolic links
compilation terminated.

root# uname -a
Linux puppypc17670 4.4.95 #1 SMP Mon Nov 13 17:15:42 GMT 2017 i686 i686 i686 GNU/Linux

**Comment by ibelieveinpup** [comment]
From SFS-Load on-the-fly, I removed devx.  Then from ppm I removed gcc and all of its dependencies.  Then I reloaded devx from SFS On-the-fly, and am the same message:

In file included from /usr/include/stdio.h:27:0,
                 from hello.c:1:
/usr/include/features.h:367:25: fatal error: /usr/include/sys/cdefs.h: Too many levels of symbolic links
compilation terminated.

root# file /usr/include/sys/cdefs.h 
/usr/include/sys/cdefs.h: broken symbolic link to ../i386-linux-gnu/sys/cdefs.h

root# find / -iname 'cdefs.h' -print
/initrd/pup_ro3/usr/include/bsd/sys/cdefs.h
/initrd/pup_ro3/usr/include/diet/sys/cdefs.h
/initrd/pup_ro3/usr/include/sys/cdefs.h
/initrd/pup_ro3/usr/include/unistring/cdefs.h
/initrd/mnt/dev_save/xenialpup7.5frugal/xenialpupsave-steven/usr/include/sys/cdefs.h
/usr/include/sys/cdefs.h
/usr/include/bsd/sys/cdefs.h
/usr/include/diet/sys/cdefs.h
/usr/include/unistring/cdefs.h
find: ‘/proc/16354’: No such file or directory
find: ‘/proc/16369’: No such file or directory
find: ‘/proc/16370’: No such file or directory
find: ‘/proc/16371’: No such file or directory
find: ‘/proc/16372’: No such file or directory
find: ‘/proc/16373’: No such file or directory
find: ‘/proc/16376’: No such file or directory
find: ‘/proc/16377’: No such file or directory
find: ‘/proc/16378’: No such file or directory

**Comment by gyrog** [comment]
I use gcc in xenialpup via devx_xenialpup_7.5.sfs.

root# ls -l /usr/include/sys/cdefs.h
-rw-r--r-- 1 root root 15412 Jun 17  2017 /usr/include/sys/cdefs.h

Which is the cdefs.h file inside devx_xenialpup_7.5.sfs.

root# ls -l /usr/include/i386-linux-gnu
lrwxrwxrwx 1 root root 2 Nov 23  2017 /usr/include/i386-linux-gnu -> ./

Unfortunately I think you may have confused things by installing gcc from the PPM.
It may be quickest to start with a fresh frugal install.
(Thus removing any strangeness in your current savelayer.)

**Comment by wdlkmpx** [comment]
Well, as gyro said, you shouldn't have installed gcc from the ppm. It's already in the devx.sfs

Xenialpup 7.5 is old and obsolete, a new version should be released. Try using upupbb.

Pull request https://github.com/puppylinux-woof-CE/woof-CE/pull/1224 will make deb-based pups way more compatible with debian/ubuntu, but i get the impression i have to test and debug all of them.. the idea doesn't sound that much appealing to me.

**Comment by ibelieveinpup** [comment]
> Unfortunately I think you may have confused things by installing and uninstalling gcc from the PPM.
> It may be quickest to start with a fresh frugal install.
> (Thus removing any strangeness in your current savelayer.)

I think that you are right about that.  I was able to get gcc to work by booting up without the save folder as if it was fresh.  

Is there any way that I could fix whatever went wrong in the save folder without deleting it and starting over?  If not, is there an easy way to delete the save folder?

**Comment by ibelieveinpup** [comment]
> Xenialpup 7.5 is old and obsolete, a new version should be released. Try using upupbb.
> 
> Pull request #1224 will make deb-based pups way more compatible with debian/ubuntu, but i get the impression i have to test and debug all of them.. the idea doesn't sound that much appealing to me.

Thank you for this suggestion.  I attempted installing this, but I get a warning about using the wrong kernel since my processor doesn't support pae. I'm going to have to do some digging to see if I can install it somehow.  Will a new version of puppylinux be released, or is that what upupbb is considered to be?

**Comment by gyrog** [comment]
Way to delete savefolder:
Easiest way is to boot from a different Puppy and simply delete the folder.
or
re-boot with the boot parameter "pfix=ram".
Mount relevant partition, and delete folder.

**Comment by ibelieveinpup** [comment]
> Way to delete savefolder:
> Easiest way is to boot from a different Puppy and simply delete the folder.
> or
> re-boot with the boot parameter "pfix=ram".
> Mount relevant partition, and delete folder.

Thank you for all of the help!  With the new save folder, the gcc seems to be working as expected!
