### ISSUE TITLE
sfs_load and PUPMODE 7

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1331]
I was reading sfs_load on my phone and PUPMODE 7 is not supported
`PUPMODE7SUPPORT="false" # PUPMODE=7 is buggy`

I think i never used a savepartition, and with savefolders a savepartition becomes irrelevant, unless luks encryption support for savepartitions is added, something that yours truly will never implement

Does anybody use savepartitions? would it be ok to remove support for savepartitions?

**Comment by mavrothal** [comment]
Is quite some time that I did not use pupmode 7 but I never had  issues with extra SFSs. Though I'm not sure was sfs_load or boot manager at the time
Having said that, indeed pupmode7 is obsolete today other that the fact that makes the  root directory of the device to look like a full install while is still frugal.
So I would think it could go. You might also want to post a question in the forum to check if anybody uses pupmode 7 today (just don't ask if it should go because some of the usual suspects will make a fuss...)

**Comment by wdlkmpx** [comment]
That's what i thought, i haven't tested a save partition, or if i ever did, i don't remember when, and i guess more bugs happen in pupmodes 6,7

But, reading shutdownconfig, i see a savepartition can only be the boot partition (PM 5): PDEV1
`[ "$SAVEPART" = "$PDEV1" ] && [ -z "$xPSUBDIR" ] && OFFER_PARTITION="y" || OFFER_PARTITION=""`

That operation "pollutes" PDEV1, and in fact makes it look like a full install.. not good.

Savefolders can be in any partition (that supports posix filesystems) and psavemark and stuff done by gyro is more than enough.

Currently init detects cryptoloop savefiles and tells the user those savefiles are not supported, that filemnt opens those files....  it should mention that they can click on them to open/mount them in order to retrieve their configs, etc.

I guess something similar can happen for savepartitions, unsupported, but init
can still detect them and tell the user to create a savefolder with a specific name
and put all the savepartition files in it, sounds like a good idea

This certainly will simplify stuff and less knowledge will be required to understand PUPMODES..

**Comment by wdlkmpx** [comment]
It has come to my attention that someone labeled me "Enemy #1" in Puppyland, the foe to be taken down no matter what.  I couldn't care less about that, i don't like dogs, it's true.. i deleted 2barks.au and sadly phil6 restored it.

But I certainly don't want to comment on the same forum as him, i still remember when he tried to abuse me, back when he tried to create a dpup jessie or something, and i was the helper, the problem is that we both had little knowledge about the impact of an incompatible udev or kernel, or that the udev package was missing. I see he's having the same problem now.

When i started to reply to technical topics, that sad little man tried to lecture me on things he didn't have a clue about, saying how i was wrong and how he was right.

That's my fear, should i comment about technicalities and attract unwanted attention or annoying attention

**Comment by peabee** [comment]
Please IGNORE him - that's the best course of action - no action. We all know the truth.

**Comment by mavrothal** [comment]
Indeed! Treat him like a troll. 
Think of him as your estranged old great-uncle 😃 . 
Show some understanding and totally ignore.
