### ISSUE TITLE
PPM (gtkdialog) fails on first run

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1342]
On the first run of PPM,  immediately after boot and before anything else but after the the machine has settled, it fails with the error
```
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
gtkdialog: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
```
Immediately rerunning PPM works fine.
Running other gtkdialog apps first thing after boot has no issues.

I think that the problem is the block of code after [line 725](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/local/petget/pkg_chooser.sh#L725) and probably in the xml_info widget, but that's only guesswork (oh and if I comment out that block the issue is gone) 
This is in bionicpup64 so it may also be that gtkdialog needs to be recompiled for bionic.
Anyway is more of an annoyance as PPM eventually runs, but may worth looking at it.

**Comment by wdlkmpx** [comment]
Hard to tell, the ppm needs a cleanup and that gui that is driven by events triggered by complex stuff is very hard to debug. My wip changes simplified it a bit, but i was not willing to waste time in case popular demand made me revert the changes, so i abandoned the idea

**Comment by mavrothal** [comment]
OK. Hopefully I'll find time to take a look over the WE. 
Is likely a gtkdialog/Gtk, or just a call order issue as the second time everything is fine.

**Comment by jamesbond3142** [comment]
See http://lightofdawn.org/blog/?viewDetailed=00193 bug #3. Might be related.

**Comment by mavrothal** [comment]
Yeah, looks like it.
I ca tell that is not a pkg_chooser issue as a bunch of changes I tried and ever a roll back had no effect. Lets hope that Ubuntu updates will fix that. Besides should be pretty rare for norma use.
I'll close this.
