### ISSUE TITLE
Delete empty folders

### ISSUE THREAD

**Issue by linuxcbon** [puppylinux-woof-CE/woof-CE#1344]
Hi,

I found some unused empty folders in bionicpup, surely it applies to other pups.
Can you delete them by default to simplify the puppies ? 
(some are needed by devx but not by default puppies, so can be safely removed).

Here is a list to begin with, you can add yours too : 
/etc/cifs-utils/
/etc/libpaper.d/
/etc/OpenCL/
/etc/rc0.d/
/etc/rc1.d/
/etc/rc2.d/
/etc/rc3.d/
/etc/rc4.d/
/etc/rc5.d/
/etc/rc6.d/
/etc/sysfs.d/
/etc/usb_modeswitch.d/
/root/.avfs-mount/
/root/.compose-cache/
/root/pkg/
/root/Templates/
/usr/etc/
/usr/lib/heimdal/
/usr/lib/i386-linux-gnu/
/usr/lib/modules/
/usr/lib/pymodules/
/usr/lib/qtchooser/
/usr/local/share/doc/
/usr/local/share/mime-info/
/usr/local/share/pixmaps/
/usr/local/share/sounds/
/usr/share/gnome/
/usr/share/gocode/
/usr/share/libsensors4/
/usr/share/qtchooser/
/usr/share/transmission/

Cheers

**Comment by wdlkmpx** [comment]
Sorry but some of those empty folders were added to the git repo. It was phil

The other empty folders are not in other pups, so perhaps phil will listen to you one day..

**Comment by mrfricks** [comment]
/root/.avfs-mount/ was added to tahrpup64 to allow mounting of archives similar to android. the archive would be treated just like a file system with no need to extract. The tahrpup64 release page on the forum has more info (this isn't turned on by default).

/etc/OpenCL/ is needed by some graphic drivers and they won't build unless it's there.

/lib/usr/i386-linux-gnu & /usr/lib/i386-linux-gnu/ are in the 64 bit ubuntu pups as that's where the 32bit libs go.

the /etc/rc*.d folders are needed for vmware-tools

i expect the rest are need by various libs & apps of the system
