### ISSUE TITLE
Puppy Package Manager (PPM) must not use df

### ISSUE THREAD

**Issue by DG12** [puppylinux-woof-CE/woof-CE#1348]
PPM must use `/bin/df `in order to not get the `df `earliest  in the path.

If the user has created a` df` script (perhaps to suppress non disk storage displays and remove blocks, used and percent information) and it is in a directory in their PATH, PPM is unable to correctly parse the output declares there is insufficient space.

**Comment by mavrothal** [comment]
```df``` is used in ~30 woof scripts and many pet packages. If a user wants to modify df (or any other utility) to non-standard behaviour  should valuate all 30+ instances and adjust them accordingly.
