### ISSUE TITLE
make pupmode 12/13 optional

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1349]
Today's flash drives are way more reliable than the ones from yesteryears (actually the last 10 years I only had an old cheap SDcard failing from use)
However the option to save periodically or only at the end if at all, is handy regardless of the medium.
So I would think that would be nice if we keep the default modes but give the option to change p12 to p13 and vice versa

**Comment by wdlkmpx** [comment]
The current init properly supports switching from pupmode 12 to 13 and viceversa.. in the initrd.

Just add pmedia=ataflash or pmedia=usbflash (triggers wait4usb)

The current init also detects if booting from a flash drive or sd card.. and changes pupmode 12 to 13.

So pmedia=ataflash or pmedia=usbflash are basically for hard drives. I guess bootmanager can also add a new  option or something

**Comment by gyrog** [comment]
pmedia=ataflash and pmedia=usbflash are supposed to trigger pupmode=13
pmedia=atahd and pmedia=usbhd are supposed to trigger pupmode=12
"init" should not override the users choice of pmedia=usbhd, even if it detects it is a stick.

**Comment by mavrothal** [comment]
Yeah a bootmanager option to change pmedia in the grub menu.lst would be handy.

Though I was thinking  also something like making a RAMdisk chrooting to it and remounting the filesystem with pup_rw in tmpfs or devsave, without rebooting the system.
The code for that is in /sbin/init (in the fsck routine for full installs) I believe.
But maybe is too much of a trouble

**Comment by wdlkmpx** [comment]
There is no need to modify menu.lst or the initrd, in pupmode 12 or 13
(PUNIONFS=aufs) bootmanager could just create a flag file or something
and init will read it and change pupmode, a reboot will be required.

The code in /sbin/initNEW was completely broken, i rewrote it..

There is a problem with savefiles, once the savefile is added to the
aufs stack (in the initrd) something gets locked. So it will not work.

I noticed the line to check if the pupsave is in a usb flash drive or
sd card is missing '-extended-usb', so it's not working.

If the code was working properly, pmedia=atahd would have no effect in
case the pupsave is in a usb flash drive/sdcard.

I fixed both issues in
https://github.com/puppylinux-woof-CE/woof-CE/commit/bcb12c16aad87409d04bbccc9e981079a9cdaf7d

That code block can be removed ..

**Comment by gyrog** [comment]
Why override the users request for pupmode=12 on a usbstick?
"pmedia=usbhd" SHOULD have an effect on pupmode even if the save device is a usb stick.
This provides the user with a choice.

**Comment by wdlkmpx** [comment]
My comment was about code that (1) detected if the pupsave is in a usb
flash drive and set pupmode 13 and (2) that code prevented pmedia=usbhd
from taking effect (pupmode remains 12), because it ignored $PMEDIA.

But, (1) was broken therefore (2) could not happen. These 2 cancel each
other out.

But now (1) is fixed and (2) will not happen.

But the question is should that code block be deleted?

**Comment by gyrog** [comment]
I thing the answer is yes.
"init" should respect the "pmedia=" parameter as provided by the user.
"pmedia=???hd" should lead to pupmode=12
and "pmedia=???flash" should lead to pupmode=13

**Comment by wdlkmpx** [comment]
I'm not good at explaining things but init does respect pmedia=*hd / *flash

The question is, should init autodetect a usb flash drive/sd card  if
pmedia= is not specified?

**Comment by jamesbond3142** [comment]
That's puppy traditional behaviour.

On Fri, 08 Mar 2019 03:58:05 -0800
wdlkmpx <notifications@github.com> wrote:

> I'm not good at explaining things but init does respect pmedia=*hd / *flash
> 
> The question is, should init autodetect a usb flash drive/sd card  if
> pmedia= is not specified?
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/puppylinux-woof-CE/woof-CE/issues/1349#issuecomment-470904623


-- 
James B

**Comment by mavrothal** [comment]
> The question is, should init autodetect a usb flash drive/sd card  if
> pmedia= is not specified?

We do we *need* to detect pmedia in the init?

**Comment by wdlkmpx** [comment]
If you want init to automatically set pupmode 13 if the pupsave is in
a flash stick/sd card - yes. Without the need the specify boot params.

If you specify pmedia via a boot param, init does not trigger the
automatic behavior.

However, bootmanager (pupmode=12/13 punionfs=aufs) could create a flag
file (that is stored in the pupsave) that init can source and change
pupmode accordingly.. this would override the automatic behavior and
the boot param..

/var/local/pupsave_pmedia:
PMEDIA=ataflash

/var/local/pupsave_pmedia:
PMEDIA=atahd

/var/local/pupsave_pmedia:
PMEDIA=usbflash

/var/local/pupsave_pmedia:
PMEDIA=usbhd

or maybe something new (this requires more changes in init):

/var/local/pupsave_pmedia:
FORCE_PUPMODE=12

/var/local/pupsave_pmedia:
FORCE_PUPMODE=13


Something like that..

Explaining this can confuse people..

**Comment by wdlkmpx** [comment]
The automatic detection of flash sticks/sd cards only happen when
there is a $PUPSAVE .. 12 (savefile/savefolder), 77 (multisession
cd/dvd)

But in pupmode 77 it will fail to detect a flash stick

But the detection should only happen inside this code block:
 # refine pupmode
 if [ $PUPMODE -eq 12 ];then
 fi

So

`if ! [ "$PMEDIA" ] ; then` .. should be relocated a few lines below,
inside if [ $PUPMODE -eq 12 ];then


I get the feeling that changing pupmode after switching root or after
the pupsave is added to aufs stack will require some kind of magic.

I could experiment a bit, but maybe  one of these weeks, i'll be
experimenting with woof-next, i already can produce a iso file using
only 'builders' and 'woof-distro' from woof-next and everything else
from the testing branch

**Comment by gyrog** [comment]
Well, I don't want "init" to automatically detect flash sticks/sd cards.
Always respect the users specification of "pmedia=", even when it is absent.

It is appropriate for Puppy installers to detect flash sticks/sd cards and write "pmedia=usbflash" in the generated boot entry.
But if the user then edits the boot entry, they should live with the result.

**Comment by wdlkmpx** [comment]
That makes sense, i don't remember but apparently the old init did
detect pmedia.

What has been happening since the new init was a progressive
reimplementation of old behaviors, except STRINGID or something.

That's why i wonder, how many people want that code removed, as bug
reports eventually led to the current init.

**Comment by gyrog** [comment]
As I recall, the "classic" init did not change the pupmode based on detecting usb sticks.

Yes, the method for the user choosing between pupmode=12 and pupmode=13,
using "pmedia=usbhd" or "pmedia=usbflash",
is far from obvious, but it's worked like that for quite a long time.
And poking information into "init" other than via boot parameters is a whole other project.

**Comment by wdlkmpx** [comment]
It was probably my idea then, but i also see this:

if [ "$SAVE_FS" = "iso9660" ];then #booting on optical, is it multisession?...

The correct code should be:

if probedisk $SAVEPART | grep -q '|optical|' ; then

I think i'll remove the code to detect sd cards, but probedisk makes
everything easier, a one-liner, accurately detecting pmedia in the
initrd has never been that easy.

**Comment by wdlkmpx** [comment]
I must confess that i don't use the puppy installers, any of them, so
i guess i just wanted the init to be 'intelligent' dealing with modest
and generic boot params that i could use in any storage media

**Comment by gyrog** [comment]
I haven't looked at the current "init" code for a while,
but is that code really checking for an iso9660 filesystem , or is it really checking for an optical drive for multisession?
If it's the latter, then your suggested change is actually more accurate, but remember there could be "iso9660" on a normal disk if someone is booting with "isobooter".

**Comment by wdlkmpx** [comment]
Well, that line Could lead to "undefined behavior", but only in edited isos
containing a directory that matches the regex, but overall i found that
everything's ok.

I often use my cellphone to browse the git repo, the good thing about
github is the online history of each file, that way it's to easier remember
what happened in the past and how it happened
https://github.com/puppylinux-woof-CE/woof-CE/commits/testing/initrd-progs/0initrd/init

Sometimes i browse the ffmpeg and wine repos, and read the commit diffs,
for some reason that i don't understand.

**Comment by mavrothal** [comment]
When I said if init needs to detect pmedia, I basically meant if we could determine file location in the  init and  set layer mount points  and behaviour  immediately after the switch.

Maybe does not worth the trouble. A boot manager flag to take effect after a reboot and a similar option at shutdownconfig, if removable media is detected for the savefile/folder location, should suffice I think.

BTW as far as I remember classic init did not detect or override pmedia, only detect removables to switch pm 6/7 and 12/13

**Comment by gyrog** [comment]
Here is the relevant code from classic "init":
`  REMOVABLEDRVSAVE="`cat /sys/block/$DRVSAVE/removable`"
  [ "$REMOVABLEDRVSAVE" = "1"  -a  "$PMEDIA" != "usbhd" ] && PUPMODE=13  #110116 shinobar.
  [ "$PMEDIA" = "usbflash" ] && PUPMODE=13 #v404 fix classmate, with internal usb flash.
  [ "$PMEDIA" = "ataflash" ] && PUPMODE=13 #w019 constrain writes to internal flash drv.
`
So you could choose pupmode=12 on a flash stick with "pmedia=usbhd",
otherwise it would do pupmode=13.

**Comment by wdlkmpx** [comment]
That's the behavior that was implemented, except that it changed pmedia,
that's accurate as well.

**Comment by wdlkmpx** [comment]
but since i updated probedisk several times, the -arg has been "broken" for
at least 6-12 months.. so many puppies released recently behave differently
than the old init.. no automatic pupmode 13 when there is no pmedia boot
param

**Comment by gyrog** [comment]
I think the only folk who really care are those who provide "pmedia=usbhd" for a usb flash stick and expect pupmode=12.
If they get it, then to my thinking, pupmode 12/13 on a usb stick is optional.

**Comment by wdlkmpx** [comment]
I guess pmedia= is really more than enough, but for those who never
edit the bootloader menu can benefit from this possible feature,
but...

This cannot happen "on the fly". It requires a pupsave and a system reboot.

But a flag file can be created in the pupsave dir

something like /path/to/home/pupsave_mode

a new tab in bootmanager. Pupsave Mode
visible only if init writes PUPSAVE_MODE_SUPPORTED=1
in PUPSTATE.

Credits:
1) underdog flag file
2) $PIMODS in PUPSATE

Althogh if i recall correctly gyro was writing something that
creates a file that is inserted in the initrd boot specs something, i don't know

**Comment by gyrog** [comment]
Yes, I have been developing a much enhanced "bootspecs" facility that acts as an all purpose conduit between the running system and the "init" in the next boot. It's suitable for use by "initmodules", "underdog" and other utilities.
It's pretty much there in the "overlay_init" stuff I released last year.

I would suggest that we leave the pupmode choosing stuff as is, for now.
