### ISSUE TITLE
Updated MSWC

### ISSUE THREAD

**Issue by jamesbond3142** [puppylinux-woof-CE/woof-CE#1353]
Guys, in case you're interested.

I just check Dpup Stretch and I see that it still uses the old MSCW. 
I've written a replacement for MSCW and I thought you may be interested, since (I think) adaptation is easy and it offers much more features. It only uses Xdialog.

In less than 400+ lines, it offer this:

1. configure which soundcard to be used as default, both local soundcard and BT devices (but it's ok if you don't have BT)
2. control features to enable:
a) whether to use sample rate converter or not,
b) whether to use equaliser
c) whether to use software volume control (this is mainly for devices that doesn't have volume control, such as bluetooth)
d) whether to use preamp with the volume control
e) whether multiple programs can output at the same time (i.e, dmix)
f) whether multiple programs can record at the same time (i.e, dmix)
g) tweaks: force output at 48kHz or 44.1kHz
h) swap stereo channels
i) download multi-channel sound to stereo
j) enable mixout recording (ability to record the sound that is being played), without need for special hw support.
h) options to remap OSS devices too (persistently across reboots as well).

One thing that it doesn't have: tweaking stuff to make retrovol happy, since we don't use retrovol by default. You can port that from the old MSCW if you want.

How to adapt it to Puppy:
1. Binary name/location: /usr/bin/fatdog-defaultsoundcard.sh, feel free to rename to something else to avoid some allergic reaction
2. Line 16: set ASOUNDRC=/etc/asound.conf
3. Line 15: ALSADEV_PREFIX=pup
4. Line 14: set the title to anything you want.
5. Line 1: change #!/bin/dash to /bin/sh.

Note: equaliser (if enabled) can be controlled by running "alsamixer -D equal".

If you're interested you can find it here:
http://distro.ibiblio.org/fatdog/iso/hotfix/800/preamp-0.1-noarch-1.txz

**Comment by wdlkmpx** [comment]
A few months ago I added a few small fatdog scripts to rootfs-skeleton.

One of them is get-monitor-names, which is called by report-video.

I don't know if radky's build includes the mscw pet pkg, but there is a mscw script in rootfs-skeleton/usr/sbin. Which is basically the old MSCW with some extra features, i've been meaning to delete about 100 lines and replace  `aplay -D plughw:${cd} /usr/share/audio/2barks.au` with a more pleasant sound

asound.conf:
defaults.pcm.card 0
defaults.pcm.device 0
defaults.ctl.card 0

But your MSCW produces a way more advanced config, which in itself is a good reason to add that script to rootf-skeleton as is, as long as it works.

It can be `/usr/sbin/mscw2` or `/usr/sbin/mscw-fd` or something. 

A button can be added somewhere to call it, maybe an extra button in alsawizard. Maybe it should become the default mscw, but i don't know, people might miss the eye candy or the extra buttons or a alsa config of only 3 lines, this world is a mystery. I think both scripts can become one, in the future..

Which reminds me, woofce introduced a small disturbance in the force with its new dialogs and stuff (it wasn't me, i was a yad user), but it's easy to make those dialogs work by copying:

/usr/lib/gtkdialog
/usr/share/pixmaps/puppy

from the git repo to some other codebase(s).

The scripts in /usr/lib/gtkdialog are sometimes updated, i guess i'll add some yad scripts as well.

Now that you're testing dpup, you might want to make sure your script works fine and then add it to rootfs-skeleton with one of the suggested names ..

**Comment by jamesbond3142** [comment]
> A few months ago I added a few small fatdog scripts to rootfs-skeleton.
> One of them is get-monitor-names, which is called by report-video.
> 

You're welcome. Take any script you need, bits and pieces or wholesale.

> I don't know if radky's build includes the mscw pet pkg, but there is a mscw script in rootfs-skeleton/usr/sbin. Which is basically the old MSCW with some extra features, i've been meaning to delete about 100 lines and replace `aplay -D plughw:${cd} /usr/share/audio/2barks.au` with a more pleasant sound

I checked upupBB too, it seems to have the same MSCW as the one in dpup stretch. I can't tell whether it comes from the pet, or from the rootfs-skeleton.
 
> It can be `/usr/sbin/mscw2` or `/usr/sbin/mscw-fd` or something.

Sound good. I'll keep it mscw2, so when the pup gets build, people can test it, and once people confirm it's working for them, we can just remove mscw (or rename it to mscw-old) and symlink mscw2 to mscw.

> 
> A button can be added somewhere to call it, maybe an extra button in alsawizard. Maybe it should become the default mscw, but i don't know, people might miss the eye candy or the extra buttons or a alsa config of only 3 lines, this world is a mystery. I think both scripts can become one, in the future..

Don't worry about the way to access it. Once it is in, then PB and mrfricks can ask others to use it if the current version is not featureful enough. Just open terminal and type "mscw2" for example.

> 
> Which reminds me, woofce introduced a small disturbance in the force with its new dialogs and stuff (it wasn't me, i was a yad user), but it's easy to make those dialogs work by copying:
> 
> /usr/lib/gtkdialog
> /usr/share/pixmaps/puppy

This updated script only uses Xdialog and nothing else, so hopefully the disturbance in the force isn't going to cripple it :rofl: 

> Now that you're testing dpup, you might want to make sure your script works fine and then add it to rootfs-skeleton with one of the suggested names ..

Yes, I will do that. I'll test on both dpup and upup (simply because that's what I have downloaded), I'm happy to test it in other pups too as needed.

I'll keep this issue open until the time I issue a pull request, and then I'll close it.

cheers!

**Comment by peabee** [comment]
In UPupBB mscw comes from rootfs-skeleton....HOWEVER as UPupBB is built using woof-ce master;ec80b41b;2018-06-23 11:36:40 +0800 this may not be the same as currently in testing....

**Comment by mavrothal** [comment]
I know that no serious coder care much about the looks but having most (all of puppy apps in gtkdialog and some in yad or Xdialog really stands out. Specially as they are called from another "dialogued" little app.

..and wdlkmpx, leave the barks alone man! You already change fido (a classic dog name) to finn, a star wars hero (and not even a classic one) 👅

**Comment by wdlkmpx** [comment]
The only thing that matters is the code that applies the changes and
stuff, i can add the woofce look and feel anytime, along with some
extra buttons and stuff. It's not a problem.

But it will become woof-ce specific, and from then on jamesbond will
have trouble updating or improving it.

Overall i think woofce should start copying the best apps, including
the best code by default, with a different name, with a different
GUI... it doesn't matter.

I wasn't thinking of that Finn, my mind was just trying to come up
with something fi.. zz .. nn.. Finn the Human.  I still haven't
watched the farce awakens

**Comment by wdlkmpx** [comment]
This script was merged
