### ISSUE TITLE
problem sha256 instead of md5.txt hugekernel file in ibiblio repo

### ISSUE THREAD

**Issue by wiake** [puppylinux-woof-CE/woof-CE#1355]

**Comment by wiake** [comment]
Sorry, forgot to describe - out of practice using github...

support/hugekernel.sh does not cater for ssh256 file. It only caters for md5.txt. So ibiblio huge kernel repo needs a:

huge-4.19.12-bionicpup64.tar.bz2.md5.txt

rather than a:

huge-4.19.12-bionicpup64.tar.bz2.sha256

or support/hugekernel.sh would have to be modified to deal with sha256 case (and not get the choice count wrong (which is messing up makepup, where currently I avoid counting the sha256 file as an actual huge kernel....

For more detail, in case I am mistaken, refer to my posts starting here: 

http://www.murga-linux.com/puppy/viewtopic.php?p=1021672#1021672

**Comment by wiake** [comment]
Or just remove that kernel version's entry altogether from huge kernel repo would do
...

**Comment by mavrothal** [comment]
There are actually 2 hash files that need renaming ```huge-3.14.79-tahr_noPAE.tar.bz2.md5``` and ```huge-4.19.12-bionicpup64.tar.bz2.sha256```. (Phil?... 👿 )
The ```download_kernel()``` of the script could be easily amended to look for these file suffixes instead, but consistent naming in better I think.

And while at it, @peabee  I do not see the lxpup_n_friends kernels in ibiblio or a link in _00build.conf or the pupplet "woof-built.conf". You may want to consider it as the pupplets would not be woof-producible (without manual addition to the local huge_kernels repository). At least the kernel of the bionicpup32/UPup Bionic Beaver should be there.

**Comment by mrfricks** [comment]
sorry about that ..... fixed
