### ISSUE TITLE
A 'generic' or a 'common' jwm?

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1371]
A month ago i updated technousarus' patches for jwm that add support for "lightweight" image loaders: stb_image & nanosvg. 

https://github.com/wdlkmpx/jwm/commits/master 

I also included the latest version of stb_image & nanosvg

With `./configure --prefix=/usr --enable-stb_image --enable-nanosvg --disable-png --disable-cairo --disable-rsvg --disable-jpeg --disable-xbm`
the result is a mostly portable or generic build.

jwm is faster and more lightweight. Images look ok, but a few svg images (1% in my jwm menu) are not rendered properly. Overall it looks ok to me..

I know i should have provided binaries, i need to compile those in a slacko14 32/64 bit build... i don't have isos at the moment, but it's easy to compile.

**Comment by ninaholic** [comment]
Hi wdlkmpx,

It looks like it wants gettext-0.19 and slackware 14 and 14.1 are both on 0.18:
https://github.com/wdlkmpx/jwm/blob/master/configure.ac#L643

![Screenshot](https://user-images.githubusercontent.com/5408521/56699585-23b1f880-66c4-11e9-9f81-36fd26d74036.png)

**Comment by wdlkmpx** [comment]
I fixed the issue, in fact two issues.

I also used the experimental branch to test my 1st slacko14.0 build. I fixed a regression.

With slacko kernerls 3.4 & 3.14 and probably other kernels, i get a garbled display (intel driver, old pc), so i used kernel 3.2.102. Maybe 3.2.102 should the default hardcoded kernel, it's specified in 00build.conf, but it's "commented out". Or maybe it should be 3.18, but without spectre/meltdown mitigation, i want the maximum speed and i want to be hacked.

I compiled the generic jwm in slacko14.0*32 
[jwm32.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3117414/jwm32.gz)

I restarted X and i see this jwm is not that compatible with the old jwmconfig, or so it seems.

It looks like it takes a bit longer to load all the icons, probably 2 seconds, but it's a generic build, it also works fine in dpup stretch. I like portable stuff.

**Comment by wdlkmpx** [comment]
So far the only problem i see is that key bindings to show the jwm menu don't work the first time X is started, don't know maybe something fails to initialize. Other keybindings work fine.

After restarting X everything  is ok. I never use the mouse or pointer when i'm explicitily using puppy (not using a VM), so i tend to find bugs other people don't notice. 

F12 should not trigger the menu. Sometimes i need to open a document with Microsoft Word (through WINE), and F12 shows the "Save as.." dialog.

I could use Abiword, but that program is dangerous when you open important documents or any document to be honest. Libre office doesn't have proper compatibility with MS office. Softmaker Free Office is the perfect app for this, and the most lightweight of all known office suites, pure X & C/C++ , but it shows a warning if it finds macros or something. So to avoid any possible issue when dealing with somebody else's documents, i use ms word.

**Comment by ninaholic** [comment]
Hi wdlkmpx,

Nice. I had to disable the F12 menu once too, I think because goattracker used it. :laughing:

I tried Slacko 14.1 experimental woof-ce build with jwm-2.4.0w binary too
https://transfernow.net/26k0n7e1742f (the link says good for 6 days)

It seemed to work ok. Slacko 14.1 is slower to boot than 14.0 for me but I think it might be mostly the Sky.svg default backdrop. Using ptheme to switch themes always gave errors but normally worked after restarting X. Quicksetup did not appear on 1st boot and when I added "tap to click" to trackpad settings it didn't always remember after reboot but I think those two things might have been related. Just testing it out for fun. :D

I think 3.2 was too old to be compatible with some wifi in the 2014 firmware pets for me, or something like that, so I use 3.14 and 3.18 in kernel-kit with the firmware pet usually. I'm glad 3.2 works good for you though. It might be handy to have a 4.14 and 4.19 LTS config too I guess someday.

**Comment by wdlkmpx** [comment]
I tested the provided iso. Indeed it doesn't show welcome1stboot or quicksetup. It may be a timing issue. I'll look into it later. I need a glass of water.

But i'll comment about an important issue. I get this error:

```
kern.info kernel: [drm] GPU crash dump saved to /sys/class/drm/card0/error
kern.info kernel: [drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
kern.info kernel: [drm] Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
kern.info kernel: [drm] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
kern.info kernel: [drm] The gpu crash dump is required to analyze gpu hangs, so please always attach it.
kern.err kernel: i915: render error detected, EIR: 0x00000010
kern.err kernel: [drm:i915_report_and_clear_eir] *ERROR* EIR stuck: 0x00000010, masking
kern.err kernel: i915: render error detected, EIR: 0x00000010
```

This lines should be deleted:
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/3builddistro-Z#L1049

Or changed to `xxx modeset=0`

The xorg driver priority (info available in /var/log/Xorg.0.log) for this video chip is something like this:
1)  Intel
2) Vesa
3) Modesetting 
4) Fbdev
5) etc

One of the generic drivers should be loaded by default and xorg wizard should add an option to enable KMS for the Intel, Radeon or Nouveau drivers.

I can't disable KMS with kernel param `nomodeset` (boot menu)... /etc/modprobe.d/i915.conf seems to override `nomodeset`. That file should not exist.

I also compiled a new jwm with extra patches for nanosvg, i'm not sure how good or bad this is, some patches from https://github.com/memononen/nanosvg/pulls are applied here:
https://github.com/wdlkmpx/nanosvg/commits/master
Need to update the nanosvg.h in my jwm repo.

[jwm32.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3124374/jwm32.gz)

**Comment by wdlkmpx** [comment]
Continuing testing slacko 14.1 6.3.2 
BUILD_FROM_WOOF='experimental;b237d173;2019-04-26 02:28:20 +0800'

It works fine with the vesa driver, you have to delete `/etc/modprobe.d/i915.conf`.
1) KMS is enabled by default in the kernel, Intel driver is selected.
2) Boot with `nomodeset` and xorg picks vesa or modesetting or something else. In slacko 14.2 the modesetting driver is missing, i think it's in one of the unused repos. Well, i noticed that building with woof-next

3) xorg wizard should determine whether an accelerated driver is available by grepping `autoconfigured driver 0` or something like this
```
[    32.141] (==) Matched intel as autoconfigured driver 0
[    32.141] (==) Matched vesa as autoconfigured driver 1
[    32.141] (==) Matched modesetting as autoconfigured driver 2
[    32.141] (==) Matched fbdev as autoconfigured driver 3
```

And offer the option to activate KMS for the next boot (persistence is required).. create one of the /etc/modprobe.d/*.conf files.

With the VESA it boots to a usable desktop, but i don't see welcom1stboot or quicksetup, there is something going on, but i do like it this way ahaha, it's such a good feeling..

**Comment by ninaholic** [comment]
haha, a bit off-topic but
I found that Firefox 66 does work in Slacko 5.8.3 from reading this
http://no-windows.blog.jp/archives/79673738.html

You just have to add libatomic.so.1 manually and run it as "apulse firefox". Neat (I never knew :laughing: )

**Comment by wdlkmpx** [comment]
I'll add that lib, but if i don't i'll need to be reminded of it

This ydrv fixes the jwm issue in dpup stretch, but it's not enough for slacko 14.1.. in this machine, at least the jwm menu key bindings work without restarting X
[ydrv_slacko_6.3.2.sfs.fake.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/3125370/ydrv_slacko_6.3.2.sfs.fake.zip)

I also noticed that xorg 1.14.3 is not the latest 1.14.x stable xorg... it's 1.14.7, no wonder slacko 14.1 is quite buggy. Slackware provides security updates after 8 years of the original release, but they never updated xorg in slackware 14.1. Ain't it sad.

But indeed there is a timing issue when the system is starting, the generic jwm causes a disturbance in the force. I guess it would be more adequate to compile a static libpng, libjpeg and librsvg (now a Rust app, insane).

**Comment by wdlkmpx** [comment]
It would a lot easier if jwm was a gtk app. It'd probably use gdk_pixmap or something.

There is also an issue with themes, old and new are a bit different.

This is may plan: compile the latest libpng, libjpeg-turbo, librsvg (C) and a jwm-w linked to those libs. A launcher script: exec /usr/local/bin/jwm "$@"

I know ptheme is not exactly bug-free, but it already includes jwm themes, gtk themes, and various themes, all in a single package, i'll add
http://chanae.walon.org/pub/images/desktop-backgrounds/space/near_earth_moon.jpg

to the dark blue ptheme, which is a minimal theme, a classic theme

And the new jwm will be the default in slacko 14+, with default theme dark blue in slacko 140.

Would it be considered and act of hostility? Are recent versions of jwm too buggy? Or too ugly? I doubt joe will continue its development, that's all there is, jwm themes don't apply to other WMs..

**Comment by ninaholic** [comment]
I will test this again in a new Slacko 14.1 build soon. The jwm 2.3.2 that comes with it is not compatible with some of the ptheme changes recently so maybe this will behave better. :smile_cat:
