### ISSUE TITLE
Makefile:558: recipe for target 'menuconfig' failed

### ISSUE THREAD

**Issue by scsijon** [puppylinux-woof-CE/woof-CE#1382]
Fresh download of woof-CE and moved into the kernel-kit; edited build.conf to suit kernel and new aufs5.0, etc.; ran ./build.sh; all is as per standard until I try to configure the kernel.

And it "bombs out" as they say.

Log and build.conf below

-log
----------------------------------------------
# ./build.sh
Quirky Xerus64 8.5 [x86_64]
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
git version 2.7.4
mksquashfs version 4.3 (2014/05/12)

Jobs for make: 1

Select the config file you want to use
1. DOTconfig-3.14.79-x86_64
2. DOTconfig-3.16.43-x86_64
3. DOTconfig-3.18.105-x86_64
4. DOTconfig-4.1.39-x86_64
5. DOTconfig-4.14.20-Atom-cherrytrail
6. DOTconfig-4.4.70-x86_64
7. DOTconfig-4.9.30-x86_64
n. New DOTconfig
Enter choice: n

You chose New. 
If this is ok hit ENTER, if not hit CTRL|C to quit: 
Enter kernel version (ex: 3.14.73) : 5.0.13
kernel_version=5.0.13
kernel_version_info=

Press ENTER to begin
Linux: 5.0.13
aufs=5.0
Downloading: ftp://www.mirrorservice.org/pub/linux/kernel/v5.x/linux-5.0.13.tar.xz
linux-5.0.13.tar.xz             100%[=======================================================>] 100.39M  2.38MB/s    in 55s     
Cloning into 'aufs5_sources_git'...
remote: Enumerating objects: 1560, done.
remote: Counting objects: 100% (1560/1560), done.
remote: Compressing objects: 100% (415/415), done.
remote: Total 1560 (delta 901), reused 1552 (delta 893), pack-reused 0
Receiving objects: 100% (1560/1560), 444.92 KiB | 341.00 KiB/s, done.
Resolving deltas: 100% (901/901), done.
Checking connectivity... done.

-- Pausing
Extra firmware to be added after compiling the kernel
Choose an option (generating list...):
1 firmware-140621-big.tar.bz2
2 firmware-140621-cut.tar.bz2
3 I'll copy in my own.
4 I'll grab the latest firmware from kernel.org. (slow)
Enter a number, 1 to 4:  4

You have chosen to get the latest firmware from kernel.org
Updating the git firmware repo
Already up-to-date.
Extracting the Aufs-util sources
* aufs-util branch: 4.9
Branch aufs4.9 set up to track remote branch aufs4.9 from origin.
Switched to a new branch 'aufs4.9'
Extracting the Aufs sources
Branch aufs5.0 set up to track remote branch aufs5.0 from origin.
Switched to a new branch 'aufs5.0'
Extracting the kernel sources
Adding Aufs to the kernel sources
--- Makefile-orig	2019-05-07 13:01:46.999750065 +1000
+++ Makefile	2019-05-07 13:01:47.013083398 +1000
@@ -2,7 +2,7 @@
 VERSION = 5
 PATCHLEVEL = 0
 SUBLEVEL = 13
-EXTRAVERSION =
+EXTRAVERSION = scsijon5
 NAME = Shy Crocodile
 
 # *DOCUMENTATION*
Reducing the number of consoles and verbosity level
Cleaning the kernel sources
grep: .config: No such file or directory

For your kernel to boot AUFS as a built in is required:
File systems -> Miscellaneous filesystems -> AUFS

You must now configure the kernel
Hit a number or s to skip:
1. make menuconfig [default] (ncurses based)
2. make gconfig (gtk based gui)
3. make xconfig (qt based gui)
4. make oldconfig
s. skip

Enter option: 1
make menuconfig
  HOSTCC  scripts/basic/fixdep
  UPD     scripts/kconfig/mconf-cfg
  HOSTCC  scripts/kconfig/mconf.o
  HOSTCC  scripts/kconfig/lxdialog/checklist.o
  HOSTCC  scripts/kconfig/lxdialog/inputbox.o
  HOSTCC  scripts/kconfig/lxdialog/menubox.o
  HOSTCC  scripts/kconfig/lxdialog/textbox.o
  HOSTCC  scripts/kconfig/lxdialog/util.o
  HOSTCC  scripts/kconfig/lxdialog/yesno.o
  HOSTCC  scripts/kconfig/confdata.o
scripts/kconfig/confdata.c: In function ‘conf_touch_dep’:
scripts/kconfig/confdata.c:102:16: error: ‘ENOENT’ undeclared (first use in this function)
   if (errno != ENOENT)
                ^
scripts/kconfig/confdata.c:102:16: note: each undeclared identifier is reported only once for each function it appears in
scripts/kconfig/confdata.c: In function ‘conf_set_all_new_symbols’:
scripts/kconfig/confdata.c:1219:13: error: ‘ERANGE’ undeclared (first use in this function)
     errno = ERANGE;
             ^
scripts/Makefile.host:107: recipe for target 'scripts/kconfig/confdata.o' failed
make[1]: *** [scripts/kconfig/confdata.o] Error 1
Makefile:558: recipe for target 'menuconfig' failed
make: *** [menuconfig] Error 2
# 
------------------------------------
-build.conf file
------------------------------------
#--
#             Configuration options
#             =====================
# 
#  **NOTE**: check the original file every once in a while
#            settings might be added or removed...
#
# see http://www.kernel.org/ for the latest kernel info..
#--

################################################################
################################################################

## speed up the process by specifing a DOTconfig file:
#DOTconfig_file=DOTconfig
#DOTconfig_file=configs_x86/DOTconfig-3.14.79-i686-4g

## (in case it doesn't have usable version info inside)
kernel_ver=5.0.13

##       the new settings take effect..
#x86_disable_pae=yes
#x86_enable_pae=yes
#x86_set_i486=yes
#x86_set_i686=yes

## example:
#custom_suffix=-4G
custom_suffix=scsijon5

## if you leave empty the script will determine a proper package suffix
package_name_suffix=qthud

##-----------------------------------------------------------------------

## remove kernel sublevel, or not : set yes or no
remove_sublevel=no

## you must specify it here:
#aufsv=3.14.40+
aufsv=5.0

## DO NOT set it to 0 (zero) >> cooked machine
#JOBS=-j6
JOBS=-j1

## the Linux-libre scripts after the patching procedure
LIBRE=0

## 'xz' / 'gzip' ..
#COMP="-comp xz"

## Firmware tarballs repository
FW_URL=http://ftp.nluug.nl/ftp/pub/os/Linux/distr/puppylinux/firmware

## specify pkg url to automate the process
#FW_PKG_URL="http://ftp.nluug.nl/ftp/pub/os/Linux/distr/puppylinux/firmware/firmware-140621-big.tar.bz2"

## Kernel download mirrors
kernel_mirrors='https://www.kernel.org/pub/linux/kernel
ftp://ftp.ntu.edu.tw/linux/kernel
ftp://ftp.heanet.ie/pub/kernel.org/pub/linux/kernel
ftp://ftp.yandex.ru/pub/linux/kernel/
https://mirror.aarnet.edu.au/pub/ftp.kernel.org/linux/kernel
ftp://ftp.jaist.ac.jp/pub/Linux/kernel.org/linux/kernel
ftp://www.mirrorservice.org/pub/linux/kernel
ftp://ftp.be.debian.org/pub/linux/kernel'

## To set the 'big' variable uncomment the folowing line:
#fw_flag=big

## - or theoretically you could choose your own
#CUTBYTES=1500000

## Every error is fatal, so you must specify all the needed stuff in build.conf first..
#AUTO=yes
------------------------------------

**Comment by scsijon** [comment]
and again it has stuffed up the formatting!

and they wonder why I hate using git for errors!

Could someone sort it out please and let me know if there is a simple way to stop this happening please.

**Comment by mavrothal** [comment]
> Could someone sort it out please and let me know if there is a simple way to stop this happening please

multiple hashes define header level. Wild cards and underscores emphasis
Wrap code in triple back ticks to avoid this.
Ref: https://guides.github.com/features/mastering-markdown/ (the link at the bottom right of the browser input window )

**Comment by ninaholic** [comment]
The menuconfig option works for me. I think the problem might be that Quirky Xerus is not a true woof-CE puppy, but the only time I tried "new config" option it did not successfully compile to the end as it needed some patchwork (I think). You'll probably have better luck with the configs included if this is your first attempt. Including a newer LTS config than 4.9 would be useful though if anyone has managed to make one successfully with kernel-kit.

**Comment by scsijon** [comment]
Well, after changing quirky versions I can build it, but it crashes on startup so I shall work further on it.

By the way, sorry, but i'm only interested in the kernel-kit from woof-CE, I build with Quirky. I may in the end go back to my older kernel-kit and use that, I am planning to use 5.0.x for some of it's auto-settings and fixes to deal with multiple touchscreens in the one system, 4.x doesn't have these facilities.

I won't close this at present, but will if I can sort out what's going on in a single screen configuration as it looks like something is missing in Xerus.

**Comment by wdlkmpx** [comment]
peabee releases kernels 5.x in...... his lxpupSc thread, you might want to open his kernel sfs's and use the /etc/modules/DOTconfig..

The kernel-kit deals gracefully and automatically with all v3+ kernels, and aufs3.0-4.10... you need to add code to automatically handle newer aufs versions, otherwise you must specify aufsv in build.conf. 

aufsv=

I'll update the stuff, one day.

We basically use fatdog kernel configs, and in fact the puppy configs include more modules.

**Comment by scsijon** [comment]
Ok, you beat me by one day, I usually close things a month after I say i'm leaving things for now, it goes on my todo date list.

Problem is with Xerus, and not just puppy's, seems like there a number of config files with missing include ?.h statements in them as they expect you to have other packages that we don't use in puppy (and a couple of other disrts that work similarly) that link them in from other links. I chased one of them and found it needed 17 other package parts to be installed, just to have a include ?.h link work, yuck.

and thanks for the peebee kernel 5.x.x link, I shall have a look and see what he does differently, maybe combine them. I shall download and install on one of my test boxes anyway.
