### ISSUE TITLE
Woof-Next: losetup: illegal option -- r

### ISSUE THREAD

**Issue by s243a** [puppylinux-woof-CE/woof-CE#1405]
Typing out the error from a video I took on my phone:

```
Loading the 'puppy.sfs' main file... copying to ramlosetup: illegal option -- r ussage:
  losetup loop_device                    #gives info
losetup -d loop_device                  #delete 
losetup -f                                         #find unused 
losetup [ -e encryption] [-o offset] ( -f loop_device) file #659 
 
```

I checked and the busybox available at:
https://github.com/puppylinux-woof-CE/woof-CE/tree/woof-next/woof-arch/x86/target/boot/initrd-tree0/bin

supports this option (i.e. readonly loop device) but odly the losetup binary provided in this folder doesn't. We can either use "busybox losetup" as the command or we can provide a more capable version of the losetup binary. 

On another note this file does not exist at all in the experimental branch:
https://github.com/puppylinux-woof-CE/woof-CE/tree/experimental/zwn 

Where woof-next was moved. 

P.S. I created a new issue because this is a pretty major issue for anyone trying to use woof-next from the experimental branch.

**Comment by s243a** [comment]
Here is where losetup is called:

```
setup_loop_sfs() {
# "$1" - sfs filename - ex: /mnt/dev_save/puppy/tahr/puppy_tahr_6.0.5.sfs
 ONE_LOOP="$(losetup -f)"
 losetup $LO_OPT $ONE_LOOP ${1}
 [ $? -eq 0 ] || { LO_OPT=""; losetup $LO_OPT $ONE_LOOP ${1}; }
}
```
[/initrd-progs/0initrd/init#L329](https://github.com/puppylinux-woof-CE/woof-CE/blob/6fabefa75b3c814ccf6079487a08f3b269db5c2e/initrd-progs/0initrd/init#L329)

This might be where the "-r" option is set:
`LO_OPT="-r"`
[/initrd-progs/0initrd/init#L938](https://github.com/puppylinux-woof-CE/woof-CE/blob/6fabefa75b3c814ccf6079487a08f3b269db5c2e/initrd-progs/0initrd/init#L938)

**Comment by jamesbond3142** [comment]
I wonder why the need for the "-r" flag? SFS is read-only files already, no need for that -r flag altogether?

**Comment by wdlkmpx** [comment]
This probably can be fixed by using a recent busybox 
http://01micko.com/wdlkmpx/woof-CE/initrd_progs-20190714-static.tar.xz

Current busybox supports the -r option:
```
BusyBox v1.31.0 (2019-08-05 23:22:55 +08) multi-call binary.

Usage: losetup [-rP] [-o OFS] {-f|LOOPDEV} FILE: associate loop devices
	losetup -c LOOPDEV: reread file size
	losetup -d LOOPDEV: disassociate
	losetup -a: show status
	losetup -f: show next free loop device

	-o OFS	Start OFS bytes into FILE
	-P	Scan for partitions
	-r	Read-only
	-f	Show/use next free loop device
```
