### ISSUE TITLE
set-hidpi-font-size missing

### ISSUE THREAD

**Issue by s243a** [puppylinux-woof-CE/woof-CE#1421]
I did a search for "set-hidpi-font-size" in woof-CE and I can't find it. 

What package is it from?

```
# Try to make the font a reasonable size on high dpi displays. #rc.platform
/usr/bin/set-hidpi-font-size
```
[https://github.com/puppylinux-woof-CE/woof-CE/blob/6fabefa75b3c814ccf6079487a08f3b269db5c2e/woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit#L648](https://github.com/puppylinux-woof-CE/woof-CE/blob/6fabefa75b3c814ccf6079487a08f3b269db5c2e/woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit#L648)

**Comment by mavrothal** [comment]
I guess this lines are copied from fatdog as puppy has neither rc.platform nor set-hidpi-font-size. 
However, ROX/jwm look really poor in hi dpi screens and this hack, so might be better to comment this line out.

**Comment by wdlkmpx** [comment]
The script was there, i copied it from a fatdog pkg i had, i added a few more checks. Later i moved it to `set-hidpi-font-size`, i think i also changed the line in rc.sysinit... but a rebase with a local branch probably reverted it.

If rox&jwm don't look good in high dpi screens, it also makes sense to remove that line.
