### ISSUE TITLE
flSynclient touchpad sensitivity resets

### ISSUE THREAD

**Issue by karthussss** [puppylinux-woof-CE/woof-CE#1454]
flSynclient bug

Touchpad sensitivity settings does not persist after reboot and resets to default. Sometimes it resets during use. Im running BionicPup64 8.0 on an external SD card plugged to USB.

[pdiag-20190605.tar.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3255090/pdiag-20190605.tar.gz)

**Comment by karthussss** [comment]
Im closing this, this is probably because im running on PUPMODE=5 despite have pup64save4fs. I was told that when its in PUPMODE=5 no partitions are loaded including pupsave. Problem is, no matter what I select at menu screen Puppy always boot as PUPMODE-5 (new install). Ive restarted probably 12x  already. Second restart should have loaded the new pupsave and followed the rc.sysinit boot script to create some dir and merge old pupsave to new pupsave but that never happens. Hence, settings, configuration files, etc does not carry over after reboots. Ill just reinstall Puppy64 from live CD again to fix and hopefully fix this problem.

**Comment by wdlkmpx** [comment]
flSynclient is a frontend to synclient, which is part of one the xorg packages. 

If you're always booting in pupmode 5 it means no pupsave has been created, it happens at shutdown.. "do you want to save session?".

If you did save session and the system cannot find it, it's a bug, that requires providing detailed info and comments and insights from the reporter, so it's easier to identify the root of the problem.

Although i personally don't know much about bionicpup64... i build a bionicpup64 using the git repo, but the official release has different results. I also happen to use a very old 32 bit machine, so i usually don't test 64bit pups.

There are some puppy users who always boot in pupmode 5 on purpose, it's no accident. They never create a pupsave or always use pfix=ram boot/kernel param..
