### ISSUE TITLE
Wrong calculated used partition size

### ISSUE THREAD

**Issue by karthussss** [puppylinux-woof-CE/woof-CE#1455]
Bug report #1
wrong calculated used partition size

Looking up a partition size of a hard drive via hardinfo, gparted, pupsysinfo and /mnt/sda(1-3) properties yields varying results.

hardinfo>filesystem>sda1-3 says 16.7 GiB used 
gparted>sda1-3 says 4.71 GiB used
properties window>sda1-3 says 60 M used
PupSysinfo>filesystems> says 60 M used

2 days later:
hardinfo>filesystem>sda1-3 says **11.7** GiB used 
gparted>sda1-3 says 4.71 GiB used
properties window>sda1-3 says 60 M used
PupSysinfo>filesystems> says 60 M used

In actuality the partitions have zero files in it
and verified by terminal dir -a

Im running BionicPup64 8.0 on an external SD card plugged to USB and harddrive is internal used as storage formatted as ext4 with 4 partitions. I didnt list sda4 because I have files in it which is what led me to seek how big sda4 is. Now i dont know if I can trust the readings.

Suggestions to devs:
Aside from fixing the above bug, please,
1.) specify what unit M and G stands for in file/folder properties window and pupsysinfo>sys-specs>filesystem. Is it MB or MiB/ GiB or GB?
2.) and please standardize the use of kilo, mega, giga, tera so forth as capacity calculation output instead of kibi, mibi, gibi, tebi... because us common users are only familiar with the former than latter.

Attached is a pupsysinfo generated report
[pdiag-20190605.tar.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3255110/pdiag-20190605.tar.gz)

**Comment by mavrothal** [comment]
Could not spot anything in the logs to explain this.
Of course different programs look at different background apps that could explain the discrepancies, but still 
Are these primary, logical, or extended partitions? (gparted or ```fdisk -l /dev/sda``` should provide some relevant info).  
Are the "used" parts in all 3 partitions or in specific one?
What ```df -h /dev/sda*``` shows use-wise?

**Comment by karthussss** [comment]
root# fdisk -l /dev/sda
Disk /dev/sda: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: B3A6018D-7B37-40F1-B8CB-3E95ABA8AA6D

Device          Start        End   Sectors   Size Type
/dev/sda1        2048  488382463 488380416 232.9G Linux filesystem
/dev/sda2   488382464  976762879 488380416 232.9G Linux filesystem
/dev/sda3   976762880 1465143295 488380416 232.9G Linux filesystem
/dev/sda4  1465143296 1953523711 488380416 232.9G Linux filesystem



root# df -h /dev/sda*
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.7G     0  1.7G   0% /dev
/dev/sda1       229G   60M  217G   1% /mnt/sda1
/dev/sda2       229G   60M  217G   1% /mnt/sda2
/dev/sda3       229G   60M  217G   1% /mnt/sda3
/dev/sda4       229G  5.1G  212G   3% /mnt/sda4



The used size are for each partition sda1 sda2 sda3. Actually, I backed up files in sda1 like shutdown and bootup scripts, config file of htop and 4 document just now. All text files but as you can see it still says 60M for sda1.

**Comment by mavrothal** [comment]
If the files are not more that 0.5MB will still say 60. Try ```df  /dev/sda*``` fro an output in KB that should be more accurate.
I _think_ that the 60MB are taken/reserved by the filesystem when the partitions are generated.
Now why the other programs report more files is up to the programs. Certainly not much can be done about Gparted other than looking for a newer version.
Hardinfo is also a binary compiled program that other than updating we have very limited options.

**Comment by karthussss** [comment]
ok. im still new to this OS and apt-get doesnt seem to work. I read apt-get doesnt work on Puppy so I have to use PPM.

PPM says,
 i have the latest version of gparted which is 0.30.0
I have 3 versions of hardinfo installed from 3 different repos. For some reason the listed installed versions by PPM doesnt even match the hardinfo version i have which is 6.0.
No pupsysinfo or PSI in PPM to upgrade to.

Ill just give up at this point and return to this problem some other time. Maybe a reinstall of bionicPuppy64 or reformat of hard drive or both. Ill update this when i get a chance. Thnx for the help.
