### ISSUE TITLE
Kernel-kit should be moved to its own repo

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1459]
To properly use/test/update the kernel-kit, it should be in its own repo. I was about to do that but it would just reflect what's happening somewhere

The initrd-progs dir is probably going to disappear from the main repo, the initrd-tree will probably be moved to woof-code/boot/ again
https://github.com/puppylinux-woof-CE/woof-CE/tree/experimental/initrd-progs

Although the current simplified code does seem to be good enough to create a initrd using the latest code and the latest static binaries, for 4 different cpu architectures... good enough for testing without building a ISO.

When it comes to compiling, it's just easier to compile binaries (of many apps) and create initrds for experimentation with the initrd_progs repo, i think the same logic applies to the kernel kit..

**Comment by mavrothal** [comment]
It is true that the puppy forum is getting most posting activity from experimenting builders rather than users, but a continuos flow I think is important.
Regardless of how many repos the components are spread across should be en entry point that guide you through the entire build, fetching what ever components are needed. Repos or anything else.
So if you move them out, you may want to to also amend merge2out to ask and fetch any moved repos.

**Comment by scsijon** [comment]
As someone who uses only the kernel-kit part of woof-ce, I'd like to second the request to separate it please. However I was considering asking it to become a daughter package, where if you (only) want it you can get it as a complete package in itself, but if you want the full woof-ce you get it automatically included as part of that.

**Comment by wdlkmpx** [comment]
I wasn't thinking about that. It's just that kernel-kit gets messy when you compile something, so i  copy that directory to some other location and compile something, and if i make changes, i have to copy those files back.

And having many other git repos and stuff, i get confused  easily.

**Comment by wdlkmpx** [comment]
Github allows people to add and edit files without using the git cli app.. so i think it's not a big deal having one more repo.

The mechanism to update kernel configs  by renaming a file.. apparently adds thousands of changed lines to the statistics. With actual 0 changes.

Overall i think the project should be restarted, it's getting heavy, too much stuff has been deleted (firmware, binaries, packages templates, files, scripts, etc), and the repo is quite small... without the git history full of deleted stuff.

**Comment by scsijon** [comment]
I think this is OT, but, I have to disagree with having a new woof-ce Project, maybe of better use would be to rename the current master branch to master-old and cloning the current testing one to create a new Master branch. This would then still make the current and still leave the stale / active branches available for anyone needing their content. I've used the Legacy branch a number of times to work out what I and others did back in the early days, (my memory's not that great,) and gone forward from there with a number of groups I support.

And you don't have to clone the complete woof-ce, you can just d/l a single branch. I don't use an app for git, I prefer using commands from a console terminal, so I only get what I ask for.

**Comment by scsijon** [comment]
Darn, forgot that I can't edit even my own comment.

And back on topic, any changes to the kernel kit needs the output to be backward compatable still. 

I don't know how many times now that i've used it to just update the kernel for a puppy /. quirky / other, leaving the rest of the system's version as is except for an odd couple of packages (usually  the reason for the updated kernel to start with).

**Comment by wdlkmpx** [comment]
I've known about git sub modules for some time but i've never used it. This might be the solution

https://git-scm.com/book/en/v2/Git-Tools-Submodules

I don't use the kernel-kit after ./merge2out, i have several woof-out* directories, and i can easily forget what i'm doing.

In fact updating the kernel-kit right now i got confused a few times already..

One outstanding feature is the ability to cross compile kernels for the raspi's. I'll compile the latest kernel for the raspi 0 1 2 3, also a aarch64 kernel

Excellent work by woodenshoe-wi.

**Comment by sc0ttj** [comment]
Yes to git sub-modules... They are a little bit of a pain in the neck, but not too bad considering all the benefits 

We should separate `kernel-kit` out to its own repo, make is a git sub-module.

We should do the same with any important, self contained Puppy programs - when they get their own repos, they also get their own READMEs, Issues lists, etc, etc ..

That makes it a lot easier for new developers to get involved - they can find the programs a lot easier for a start..

**Comment by wdlkmpx** [comment]
It's not easy either way, people can barely handle a single repo, they
won't bother looking to other repos.

Puppy is not a full distro, and puppy users don't use github.

As there's too many things fix at the same time, it wasn't that bad
idea to keep everything together, well at least until stuff gets
sorted.

Let's put it this way: absolutely everything was wrong.

The problem is that there are some big non-essential apps, those
should be moved to their own repos or something. But I'll keep myself
shut to avoid hurting sensibilities again...

**Comment by Butterfly** [comment]
On 10/24/19, wdlkmpx wrote:
> It's not easy either way, people can barely handle a single repo, they
> won't bother looking to other repos.

> The problem is that there are some big non-essential apps, those
> should be moved to their own repos or something. But I'll keep myself
> shut to avoid hurting sensibilities again...


Am replying via email (in case this displays weird)..

My.. not-so-humble opinion is that it should *never* hurt
sensibilities to be considered large enough, self-contained enough to
have one's own repository. That should instead be a very proud day.

Saw GIthub get the head nod in the way Woof-CE is on here. That kind
of move offers the opportunity for repetition of one's package name,
just for starters.

The way things work on the Net, that repetition is a very positive..
side effect, for lack of a better word just this second. It's about
repetition of important keywords, yada-yada. That incidental
repetition helps one gain more exposure over time.

PS Am still out here lurking and learning. Had a hardware/software
crash-and-burn that lasted almost 3 weeks last month (September into
October). Puppy Wary5.5 to the rescue (again!) when it was over. In
fact am emailing from it right now.

The significance in saying that is that, THIS TIME 'round, I spent
some time really nosing around the Ibiblio type of "repositories".
Ended up becoming a little more familiar with the various Puppies out
there so the names and especially the timing of their creation are
starting to make more sense when they're mentioned.

Am getting real close to FINALLY understanding Puppy's way of doing
things overall. It's definitely one of the most unique projects out
here. Sure wish I could (also FINALLY) find my place in helping you
all do this to repay the fact that Puppy remains the ONLY reason I'm
able to access dialup Internet right now.

*woof!*

**Comment by wdlkmpx** [comment]
I think it's good to have stuff in the main repo so that external builds are not broken, but the kernel kit produces a tarball and that tarball must be uploaded to somewhere. 

So it's not mandatory for the kernel-kit to be in the main woofce repo.

The only problem here is that there needs to be a huge_kernel repo for every woofce pup, at least 3 kernels + sources for each woofce pup.

I've been having severe headaches and a killing pain in the neck these last 2 weeks and can no longer think properly.. is  anybody going to include kernel configs for newer lts kernels... is anybody going to edit the current kernel configs?

Reply within the next 3 days.

> Am getting real close to FINALLY understanding Puppy's way of doing things overall. It's definitely one of the most unique projects out here. Sure wish I could (also FINALLY) find my place in helping you all do this to repay the fact that Puppy remains the ONLY reason I'm able to access dialup Internet right now.

You are using wary puppy to access dialup internet, right?

**Comment by s243a** [comment]
> It's not easy either way, people can barely handle a single repo, they
won't bother looking to other repos.

I disagree, because when people try to contribute to woof-CE they are told they are running code that is too old. It is much easier to update the package on a given puppy then update the whole puppylinux system to the latest woof-CE.
