### ISSUE TITLE
Is the woof-CE repo rebased???

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1460]
Looks like that the entire woof-CE repo is rebased or something.
Recent commits have disappeared (the last in testing is from 28days ago!) and code has changed
I do not know who and why did that but it is [not a good idea to rebase rebase a collaborative project](https://www.atlassian.com/git/articles/git-team-workflows-merge-or-rebase) as commit history pull requests etc after the rebase commit is gone.
So if someone has a git version before this, please reinstate the original.

**Comment by wdlkmpx** [comment]
Only the experimental branch..

The testing/master branch is never rebased, i cherry-picked some commits from the experimental branch, and then rebased experimental on top of testing again.

When you cherry-pick commits from another branch, the commits are added as new commits to the target branch, it's not altered in any way, but you see commits from different dates.

Since i tend do do everything in the experimental even some minor and trivial bugfixes.

**Comment by ghost** [comment]
Hi mavrothal,

I think it's just a date syncing issue. The testing commits are new and say "June 7th" at the top but earlier date at the bottom :cat2: 

![Screenshot](https://user-images.githubusercontent.com/5408521/59119547-1aea4e80-8921-11e9-9633-a4c9793e6a80.png)

**Comment by wdlkmpx** [comment]
Most commits from the experimental branch are (more or less) safe to add to the testing branch, except the commits that simplify the ppm and the commit to "get rid of the multiarch symlink".

The ppm in the experimental branch probably needs some more testing and a few more fixes, i.... don't feel like doing that. And in fact it needs to be simplified even more.

It's basically a massive cleanup with some optimizations, one of the many massive cleanups in the history of woofce performed by yours truly.

**Comment by wdlkmpx** [comment]
Many of the commits i add are in fact... old. Already committed days, weeks, or months ago.

When i rebase something, i change the commit date with something like this:

```
GIT_COMMITTER_DATE="$(date)" git commit --amend --no-edit --date "$(date)"
git rebase --continue
```

Recently my local git repo got corrupted, and guess what,  i don't have a backup, some  changes were lost, fortunately i had already pushed most of it to the experimental branch.. so you're seeing what i always do .. without the tricks to change the commit date.

**Comment by wdlkmpx** [comment]
The issue has been clarified, more "old" commits will be added to the testing branch, nothing is being disrupted, except the experimental branch, it will not suffer the same fate as other branches i created before, i'm not sure it will be fully merged though, so far all the changes  qualify as only cleanups, fixes and optimizations, but some people might view them as too disruptive and i laugh at hem.

Some more commits will be cherry-picked and added to the testing branch..
