### ISSUE TITLE
/usr/sbin/indexgen.sh no longer in master branch

### ISSUE THREAD

**Issue by s243a** [puppylinux-woof-CE/woof-CE#1466]
I noticed that indexgen.sh is no longer in the master branch. 

https://github.com/puppylinux-woof-CE/woof-CE/blob/legacy/woof-code/rootfs-skeleton/usr/sbin/indexgen.sh 

Missing this fire broke mistfire's version of the puppy package manager. See my posts:
[alternative puppy build system](http://murga-linux.com/puppy/viewtopic.php?p=1030385#1030385)
[Puppy Package Manager (modified) v3.0](http://murga-linux.com/puppy/viewtopic.php?p=1030387#1030387)

I don't know if this file is required or not given more recent changes to the package manager.

**Comment by mavrothal** [comment]
As far as I can see it was deleted back in November 24 in 8103b84f 
Was part of a [group of changes that day](https://github.com/puppylinux-woof-CE/woof-CE/commits/testing?since=2018-11-20&until=2018-11-25)
Would be probably easier to modify mistfire's code at this point.

**Comment by s243a** [comment]
If the code isn't used any logger then it doesn't really hurt anything and as a bonus it provides some legacy support. That said when the updates are ready for either the official ppm or mistfires version then I can try it. In the short term I have made some progress in getting mistfires version of the ppm to work and yes this includes adding back some legacy files.

**Comment by wdlkmpx** [comment]
It is kind of sad, but there is another app that was deleted that was also used by the ppm.. "printcols"... it was replaced with `cut -f x,x,x -d '|'`

In fact many puppy apps were replaced with something more "standard", and that's a neverending process.

There is a problem when people assume that woofce code doesn't change.
