### ISSUE TITLE
lack of /initrd/pup_ro1 -> backcompatibility issues in pupmode 13 (i.e. usbflash mode)

### ISSUE THREAD

**Issue by s243a** [puppylinux-woof-CE/woof-CE#1469]
As noted, I'm not sure what errors might be cause by: my unusual build, woof-CE changes or mistfire's package manager, but I noticed some errors related to the directories which puppy mounts (or related directories). For example in mistfire's version of the package manager there is the following section of code:

```
 if [ ! -f /tmp/pup_event_sizefreem ]; then
   . /etc/rc.d/PUPSTATE
   case $PUPMODE in
    2) AVAILABLE=$(df -m | grep / | head -n 1 | awk '{print $4}');;
    5|6) AVAILABLE=$(df -m | grep pup_rw | awk '{print $4}');;
    7|13) AVAILABLE=$(df -m | grep pup_ro1 | awk '{print $4}');;
    12) AVAILABLE=$(df -m | grep pup_rw | awk '{print $4}')
      [ "$AVAILABLE" = "" ] && AVAILABLE=$(df -m | grep dev_save | awk '{print $4}');;
   esac 
```

According to the documneation at the top of /initrd0/init pup_ro1 is not the save layer in pup mode 5 or 13. The correct save layer is:
`/initrd/mnt/dev_save `

I reported this size issue at:
http://murga-linux.com/puppy/viewtopic.php?p=1030761#1030761

A quick search reveals other places in mistfire's package manager where pup_r01 is used:

```
# grep -rn . -e 'pup_ro1'
./configure.sh:63:   if [ -L /initrd/pup_ro1 ]; then
./configure.sh:66:    SIZEFREEM=`df -m | grep ' /initrd/pup_ro1$' | tr -s ' ' | cut -f 4 -d ' '`
./installed_size_preview.sh:45:   if [ -L /initrd/pup_ro1 ]; then
./installed_size_preview.sh:48:    SIZEFREEM=`df -m | grep ' /initrd/pup_ro1$' | tr -s ' ' | cut -f 4 -d ' '`
./installmodes.sh:224:    7|13) AVAILABLE=$(df -m | grep pup_ro1 | awk '{print $4}');;
./petget:237:   if [ -L /initrd/pup_ro1 ]; then
./petget:240:    SIZEFREEM=`df -m | grep ' /initrd/pup_ro1$' | tr -s ' ' | cut -f 4 -d ' '`
./pkg_chooser.sh:38:   if [ -L /initrd/pup_ro1 ]; then
./pkg_chooser.sh:41:    SIZEFREEM=`df -m | grep ' /initrd/pup_ro1$' | tr -s ' ' | cut -f 4 -d ' '`
./removepreview.sh:131:    Sx=$(echo $ALLF | grep -v '^/initrd/pup_ro1/')
./removepreview.sh:134:     S=$(ls /initrd/pup_{a,y}"$ONESPEC" 2>/dev/null| grep -v '^/initrd/pup_ro1/'| tail -n 1)
./removepreview.sh:136:     S=$(ls /initrd/pup_ro{?,??}"$ONESPEC" 2>/dev/null| grep -v '^/initrd/pup_ro1/'| head -n 1)
./removepreview.sh:163:      [ -f "/initrd${SAVE_LAYER}${ONESPEC}" ] && rm -f "/initrd${SAVE_LAYER}${ONESPEC}" #normally /pup_ro1 
```
We need to watch for these kinds of things as rizalmart makes improvements to puppies package manager by merging in concepts from mistfire's package manager. 

I'm not sure if the philosophy is to try to preserve legacy compatibility or just to make sure that everything works. However, speaking of things that will break legacy compatibility; I noticed that in the "test" branch "df" was replaced with "df-pup", while in theory this makes more sense it might break back compatibility. 

On another note regarding the computation of free space; I noticed that there is now a separate function to do this:

```
fx_personal_storage_free_mb() {
	[ $PUPMODE ] || . /etc/DISTRO_SPECS
	[ $SAVE_LAYER ] || . /etc/rc.d/PUPSTATE
	local F1 F2 F3 F4 F5plus SIZEFREEM
	case $PUPMODE in
		12|13|21|93)
			# PTN=" /initrd/mnt/dev_save" (savefolder)
			# PTN=" /initrd/pup_rw"       (savefile)
			#    -get mountpoint regardless of filetype-
			PTN=" $(stat -Lc %m /initrd/${SAVE_LAYER})" ;;
		*)
			PTN=" /" ;;
	esac
	while read F1 F2 F3 F4 F5plus ; do
		case "$F5plus" in *"$PTN")
			SIZEFREEM=${F4} ; break ;;
		esac
	done <<EOF
$(df -m)
EOF
	echo "$SIZEFREEM"
}
```
[/woof-code/rootfs-skeleton/etc/rc.d/functions_x#L61](https://github.com/puppylinux-woof-CE/woof-CE/blob/43e8154f42666d2f4fc83a4ef914a9a5ce72a46d/woof-code/rootfs-skeleton/etc/rc.d/functions_x#L61)

So for maintainability reasons perhaps the puppy package manager should use this functions when calculating free space.

**Comment by mavrothal** [comment]
I would thing if someone changes any woof program should try to push the changes back in woof rather than asking for specific changes that will facilitate out of repo modifications.
The reason is that is harder to evaluate, test and maintain such an approach/changes.
Just my 2c...

**Comment by gyrog** [comment]
Actually the best way to referrence the save layer is to include /etc/rc.d/PUPSTATE,
then use "/initrd${SAVE_LAYER}".
All versions of 'init' maintain the variables in PUPSTATE so that Puppy utilities can be simpler, and more future proof, by using them, rather than hard coding a currrent value.

**Comment by s243a** [comment]
> Actually the best way to referrence the save layer is to include /etc/rc.d/PUPSTATE,
> then use "/initrd${SAVE_LAYER}".
> All versions of 'init' maintain the variables in PUPSTATE so that Puppy utilities can be simpler, and more future proof, by using them, rather than hard coding a currrent value.

Thanks for the tip :)

I notice this is how petget currently does it in woof-CE:

`DIRECTSAVEPATH="/initrd${SAVE_LAYER}" #SAVE_LAYER is in /etc/rc.d/PUPSTATE.`
[/woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh#L216](https://github.com/puppylinux-woof-CE/woof-CE/blob/3cbb6145d399745eebb454c02b3cd10f5ccf0c4c/woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh#L216)

I also found a commit that might be relevant [43e8154f42666d2f4fc83a4ef914a9a5ce72a46d](https://github.com/puppylinux-woof-CE/woof-CE/commit/43e8154f42666d2f4fc83a4ef914a9a5ce72a46d) 

In this commit I see where the symlink is supposed to be being created:

```
if [ -d /pup_new/initrd/mnt/tmpfs/pup_ro1 ] ; then
  rm -rf /pup_new/initrd/pup_ro1
  ln -sv /initrd/mnt/tmpfs/pup_ro1 /pup_new/initrd/pup_ro1 #for after switch
fi
```
[/0initrd/init#L1408](https://github.com/puppylinux-woof-CE/woof-CE/blob/43e8154f42666d2f4fc83a4ef914a9a5ce72a46d/initrd-progs/0initrd/init#L1408) 

So for starters I need to look at my 0initrd/init

**Comment by gyrog** [comment]
That symlink is there for old utilites that have /initrd/pup_ro1 hardcoded, rather than being coded the better way.

**Comment by s243a** [comment]
> Actually the best way to referrence the save layer is to include /etc/rc.d/PUPSTATE,
> then use "/initrd${SAVE_LAYER}".
> All versions of 'init' maintain the variables in PUPSTATE so that Puppy utilities can be simpler, and more future proof, by using them, rather than hard coding a currrent value.

I"m pretty sure this approach still gives a symlink. I looked at my PUPSTATE for dup stretch in pup mode 13 and it said 
`SAVE_LAYER=pup_ro1 `
but /initrd/pup_ro1 is a symlink. To get the realpath (your way) one must use either the relpath or readlink function. 

Altnerativly one can do something like:
```
. /etc/rc.d/PUPSTATE
SAVE_REL="$(echo $PUPSAVE | cut -d',' -f3)"
SAVE_PATH="/initrd/mnt/dev_save$SAVE_REL"
```
and I don't know if this latter approach is more or less future proff than the prior techniques. Anyway, I think I unearthed an old issue (prior to woof-CE being on github) that was fixed in the puppy package manager but might possibly affect sc0ttman's package manager (i.e. pkg). See post:
http://murga-linux.com/puppy/viewtopic.php?p=1030958#1030958

**Comment by gyrog** [comment]
Now you have hard coded another current particular, i.e. the mount point used by "init', "/initrd/mnt/dev_save".
Better to use:
. /etc/rc.d/PUPSTATE
SAVE_PATH="$(readlink -f "/initrd${SAVE_LAYER}")"

**Comment by s243a** [comment]
> Now you have hard coded another current particular, i.e. the mount point used by "init', "/initrd/mnt/dev_save".
> Better to use:
> . /etc/rc.d/PUPSTATE
> SAVE_PATH="$(readlink -f "/initrd${SAVE_LAYER}")"

I noticed in my build ( a woof-next fork) clicking the save button on the desktop causes the symlinks /initrd/pup_ro1 and /initrd/pup_rw to disapear. I looked in both the files snapmergepuppy and save2flash and I can't see any place where these symlinks are recreated and I don't know what layer in which these symlinks are supposed to reside. I did notice though that in a lot of the snapmergepuppy code the initrd directory is excluded. 

This means that I can't troubleshoot this issue at the moment. Maybe, I'll add a hack at the end of snapmerge puppy to fix these symlinks if they are missing.

**Comment by wdlkmpx** [comment]
This certainly is not a woof-ce issue.

**Comment by wdlkmpx** [comment]
It would take a whole day to explain to @s243a how things work

```
 I noticed that in the "test" branch "df" was replaced with "df-pup", while in theory this makes more sense it might break back compatibility.
```

df-pup is renamed to df and df is rename to df-FULL. df-pup is a way to prevent issues in the build system(s).

Now i could go on explaining, even the old code that is no longer in woofce you paste .. but insert coins first..

**Comment by s243a** [comment]
> Now you have hard coded another current particular, i.e. the mount point used by "init', "/initrd/mnt/dev_save".
> Better to use:
> . /etc/rc.d/PUPSTATE
> SAVE_PATH="$(readlink -f "/initrd${SAVE_LAYER}")"

I did find some places in the code that get the save directory in the way I suggest. For instance:

```
get_save_dir() {
	SAVE_DIR="${PUPSAVE##*,}"
	[ "$SAVE_DIR" ] && SAVE_DIR="${SAVE_DIR%/*}"
}
```
https://github.com/puppylinux-woof-CE/woof-CE/blob/d960a32c274504b94262f5cba5f7bc6a7b8fbf19/woof-code/rootfs-skeleton/usr/sbin/initmodules#L19

```
SAVEFILE="`echo -n "$PUPSAVE" | cut -f 3 -d ','`"
```
https://github.com/puppylinux-woof-CE/woof-CE/blob/706136386d1fb9f3eb92d8d9178b70c4ccd68f71/woof-code/rootfs-skeleton/usr/sbin/resizepfile.sh#L28
