### ISSUE TITLE
Quicksetup in kms/modesetting

### ISSUE THREAD

**Issue by ghost** [puppylinux-woof-CE/woof-CE#1481]
On one of my netbooks, I type xorgwizard and select kms/modesetting video driver to see the desktop. After I do this recently, quicksetup first-run dialog does not pop-up any more and Puppy immediately barks at me instead :dog2: Running quicksetup from terminal gives an error about gtkdialog (attached below). This error started after experimental branch was made, maybe around commit 7000-7200 but I'm not sure exactly from which commit in that range yet. Reverting /usr/sbin/quicksetup itself did not fix anything so I am guessing it happens because of something in the underlying system, maybe recent busybox update or some update in part of gtkdialog itself? I don't think 1019 on quicksetup is the problematic line because if I remove that section it just gives me an error somewhere else, the line 1019 error message is slightly cryptic to me :laughing: It happens in both slacko 14.0 and 14.1 but I have not tried 14.2 or dpup yet, and don't know if it's a universal problem introduced or just on specific computers when using kms/modesetting.

I made a current slacko 14.0 iso here if you want to use it for testing:
https://transfernow.net/4978d1x06ca3
md5sum: 3d6047894dcd72c3751a9c0417252ebc

![quicksetup](https://user-images.githubusercontent.com/5408521/60736038-a3a9d980-9f23-11e9-9b1b-9912a75f7875.png)

Also I notice that when using Desktop Icon Switcher to change icon theme it does not refresh mounted or home drive icons (think 01micko might have mentioned something about this, might relate to the new cairo or theme changes).

![notrefreshed](https://user-images.githubusercontent.com/5408521/60736068-b91f0380-9f23-11e9-8bab-26497329a209.png)

Also noticed that the first dialog for slackware Gparted is missing the icon, which was easy to fix though by adding this to 00build.conf:

`ln -s /usr/share/icons/hicolor/32x32/apps/gparted.png /usr/share/pixmaps/gparted.png`

![gparted](https://user-images.githubusercontent.com/5408521/60736087-c50ac580-9f23-11e9-88b8-c2884264b01b.png)

With the new ram system it was a challenge to find where /mnt/sda4 was using PUPMODE=5 in Rox (the drive where puppy was loaded from) but I did end up finding my sda4 drive eventually in /initrd/mnt/dev_save instead :balloon: 

If you can't duplicate the quicksetup kms/modesetting issue feel free to close this, just thought I would report. Note that running /usr/sbin/**quickcountry** still works for me in kms/modesetting though, so I was able to change the setting I wanted.

**Comment by 01micko** [comment]
Firstly, try doing a dump of the `quicksetup` xml code for gtkdiaog.
eg: `echo "$QUICKSETUP_DIALOG" > ~/zxml` @ around line 1086 (before RETVALS=). Check line 1019 in that resulting xml code.

Secondly, make sure `/usr/sbin/pngoverlay-cairo` got installed from `woof-arch` and not overwritten by a package. If it did then try and convert any icon with any overlay using `pngoverlay-cairo source.png overlay.png output.png`  (48x48 png only) and report any errors.

**Comment by ghost** [comment]
Thanks 01micko!

Here is line 1019 when it works (video driver: Automatic):

![Screenshot](https://user-images.githubusercontent.com/5408521/60746331-3d857c80-9f4c-11e9-9556-536cab0591f4.png)

And an example of line 1019 when it doesn't (video driver: KMS / modesetting):

![Screenshot(1)](https://user-images.githubusercontent.com/5408521/60746342-46764e00-9f4c-11e9-8b14-0831e1d9b989.png)

You helped me realize what the 1019 line means and that the field seems to be empty.

I will play with converting the icons with pngoverlay-cairo in a bit. :smile_cat: Thanks for the pointers.

**Comment by 01micko** [comment]
Ah good. Just need to find the reason why `${XWIZARDXML}` and/or `${XYRESXML}` are empty. Hmmm .. does `xrandr` work on that chip? It's a Xorg extension and isn't always available which would explain the error, but of course it could be something else.

I found the bug with icon switching, rather silly really because the function can't see the `PNGOVERLAY` variable near the top of `usr/sbin/icon_switcher` ... just export it an *voila*!
eg: `export PNGOVERLAY='pngoverlay-cairo'`

**Comment by 01micko** [comment]
@ninaholic .. I guess `report-video driver` is failing for you and that would explain the empty first var `XWIZARDXML`
The second `XYRESXML` seems to depend on `xrandr`

**Comment by ghost** [comment]
Yes! Before commit ~7000 it looks like **report-video driver** said modesetting, after it said nothing, so that entire if statement at line 937 in quicksetup would now get ignored.

[netbook1_automatic.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/3364184/netbook1_automatic.txt)
[netbook1_modesetting.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/3364185/netbook1_modesetting.txt)

[netbook2_commit6990.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/3364169/netbook2_commit6990.txt)
[netbook2_commit7248.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/3364170/netbook2_commit7248.txt)

As my /var/log/Xorg.0.log looks the same before and after, I am guessing something in this commit might be the issue https://github.com/puppylinux-woof-CE/woof-CE/commit/ee155a71a742c4aae13f23f0a0d44cae9f0fd22a#diff-8c7e7766b7352fae8897e16d881850e4

I tried doing a test comparing the $LOADED and $drivers line with my [Xorg.0.log](https://github.com/puppylinux-woof-CE/woof-CE/files/3364226/Xorg.0.log)

![Screenshot](https://user-images.githubusercontent.com/5408521/60748983-81cf4780-9f61-11e9-81e2-a6e1e3df8cdd.png)

**Comment by 01micko** [comment]
Oh dear... `report-video` is a bit of a mess

- it can't handle 2 chips as in my laptop that has an intel and a radeon

- it can't handle if a driver isn't autoconfigured

So my lappy reports nothing for the driver (`intel` is in use) and the chip(s) is/are unknown.

**Comment by 01micko** [comment]
Ok, fixed it for me

Give it a try

```shell
#!/bin/sh
#note, this is the original report-video script, builtin to Woof.
#TaZoc has written a more advanced version, available as a pet pkg (sys-info).
#121128 BK complete rewrite.
#130127 internationalised.
#130207 don570: a translation was missing.
#130215 a module may get loaded, then attempted loaded again, then unloaded, 1st load still there.

export TEXTDOMAIN=report-video
export OUTPUT_CHARSET=UTF-8

function help() {
  echo
  echo " Syntax: "
  echo "   ${0##*/} [option]"
  echo
  echo "[option] can be:"
  echo "   driver  - get Xorg video driver (from /var/log/Xorg.0.log)"
  echo "   modules - get xorg loaded modules (from /var/log/Xorg.0.log)"
  echo "   chip    - get graphics chip description"
  echo "   res     - get actual resolution"
  echo "   depth   - get actual bit depth"
  echo
  echo "   xorgconf <opt>  - query /etc/X11/xorg.conf"
  echo "        videodepth - requested depth (bits or planes)"
  echo "        videores   - requested resolution"
  echo "        reqmods    - modules requested to be loaded"
  echo "        disabledmods - modules requested to not be loaded"
  echo "        reqdriver    - drivers requested to be loaded"
  echo
  echo " If no option is given then a full report is printed"
  echo
}

function XorgVideoDriver() {
	drivers=$(grep -o 'Matched .* as autoconfigured driver' /var/log/Xorg.0.log | cut -f 2 -d ' ')
	for ALOADED in $drivers ; do
		CNTload=`grep "LoadModule: \"$ALOADED\"" /var/log/Xorg.0.log | wc -l`
		CNTunload=`grep "UnloadModule: \"$ALOADED\"" /var/log/Xorg.0.log | wc -l`
		[ $CNTload -eq 0 ] && continue #not loaded
		if [ $CNTload -gt $CNTunload ] ; then
			#echo VIDEODRIVER="$ALOADED"
			VIDEODRIVER="$ALOADED" #times loaded greater than unloaded
		fi
	done
	# nothing found, fallback to older method
	if [ -z "$VIDEODRIVER" ] ; then
		LOADED=$(grep 'Loading .*/xorg/modules/drivers/.*_drv.so' /var/log/Xorg.0.log | sed -e 's/.*\///' -e 's/_.*//')
		for ALOADED in $LOADED
	    do
	      bPTN="LoadModule: \"$ALOADED\""
	      aPTN="UnloadModule: \"$ALOADED\""
	      CNTload=`grep "$bPTN" /var/log/Xorg.0.log | wc -l`
	      CNTunload=`grep "$aPTN" /var/log/Xorg.0.log | wc -l`
	      [ $CNTload -eq 0 ] && continue #not loaded
	      VIDEODRIVER="$ALOADED" #times loaded greater than unloaded
	      break
	    done
	fi
	[ ! "$VIDEODRIVER" ] && return 1
	echo -n ${VIDEODRIVER} > /tmp/xorg_video_driver
	echo ${VIDEODRIVER}
}

function XorgLoadedModules() {
  if [ "$video_driver" ] ; then
    VIDEODRIVER=${video_driver}
  else
    VIDEODRIVER=$(XorgVideoDriver)
  fi
  ALLLOADED="$(grep 'LoadModule: ' /var/log/Xorg.0.log | rev | cut -f 1 -d '/' | rev | cut -f 2 -d '"' | sort -u | tr '\n' ' ')" #'geany
  for ALOADED in $ALLLOADED
  do
    [ "$ALOADED" = "$VIDEODRIVER" ] && continue
    aPTN="UnloadModule: \"$ALOADED\""
    bPTN="LoadModule: \"$ALOADED\""
    #130215 Xorg loaded noauveau, then tried to load it again, failed, then unloaded, so count them...
    CNTload=`grep "$bPTN" /var/log/Xorg.0.log | wc -l`
    CNTunload=`grep "$aPTN" /var/log/Xorg.0.log | wc -l`
    [ $CNTload -eq 0 ] && continue
    [ $CNTunload -ge $CNTload ] && continue
    ALLMODS="${ALLMODS} ${ALOADED}"
  done
  echo "$ALLMODS"
}

function VideoChip() {
  local GRAPHICSCHIP
  CHIPID="`lspci -v | grep -i -E 'graphic|video|display|vga' | cut -f 1 -d ' '`" #130214
  if [ "$CHIPID" ] ; then
    for i in `echo $CHIPID`; do
    GRAPHICSCHIP="$GRAPHICSCHIP 
$(lspci -nnk -s $i)"
    done
  fi
  [ -z "$GRAPHICSCHIP" ] && GRAPHICSCHIP=" unknown"
  echo "$GRAPHICSCHIP"
}

function XorgConf() {
  [ ! -f /etc/X11/xorg.conf ] && return 1
  local sPTN='/^Section "Screen"/,/^$/p' #this is a multi-line block find expression.
  case $1 in
    videodepth)
      echo "$(sed -n "$sPTN" /etc/X11/xorg.conf | tr '\t' ' ' | tr -s ' ' | grep '^[^#][ \t]*Depth ' | cut -f 3 -d ' ')"
      ;;
    videores)
      echo "$(sed -n "$sPTN" /etc/X11/xorg.conf | tr '\t' ' ' | tr -s ' ' | grep '^[^#][ \t]*Modes .*#screen0modes' | cut -f 2 -d '"')"
      ;;
    reqmods)
      echo "$(grep '^[^#][ \t]*Load ' /etc/X11/xorg.conf | cut -f 2 -d '"' | tr '\n' ' ')"
      ;;
    disabledmods)
      echo "$(grep '^[^#][ \t]*Disable ' /etc/X11/xorg.conf | cut -f 2 -d '"' | tr '\n' ' ')"
      ;;
    reqdriver)
      sPTN='/^Section "Device"/,/^$/p' #this is a multi-line block find expression.
      echo "$(sed -n "$sPTN" /etc/X11/xorg.conf | tr '\t' ' ' | tr -s ' ' | grep '^[^#][ \t]*Driver ' | cut -f 2 -d '"' | tr '\n' ' ')"
      ;;
    *) echo "Valid parameters for xorgconf: videodepth videores reqmods disabledmods reqdriver" >&2 ; return 1 ;;
  esac
}

function ScreenResolution() {
  if which xdpyinfo &>/dev/null ; then
    VIDEORES="$(LANG=C xdpyinfo | grep ' dimensions: ')"
    read -r ZZ VIDEORES <<< $VIDEORES
  elif which xrandr &>/dev/null ; then
    VIDEORES=$(xrandr 2>/dev/null | grep '\*' | awk '{print $1 $2}' | head -1)
  else
    VIDEORES=$(gettext 'unknown')
  fi
  echo $VIDEORES
}

function ScreenColorDepth() {
  VIDEODEPTH="$(LANG=C xdpyinfo | grep 'depth of root window:')"
  VIDEODEPTH="${VIDEODEPTH##*: }"
  [ "$VIDEODEPTH" = "" ] && VIDEODEPTH=$(gettext 'unknown')
  echo $VIDEODEPTH
}

function get_glxinfo() {
	if [ `which glxinfo` ]; then 
		glxinfo 2>/dev/null | grep -E -A2 "direct rendering|OpenGL vendor" | grep -v '\-\-'
	elif [ `which fglrxinfo` ]; then #120807 ATI proprietary driver info
		fglrxinfo
	elif [ `which nvidia-xconfig` ]; then #120807 NVIDIA proprietary driver info
		nvidia-xconfig --query-gpu-info
	fi
}

case $1 in
  driver)   XorgVideoDriver   ; exit $? ;;
  modules)  XorgLoadedModules ; exit $? ;;
  chip)     VideoChip         ; exit $? ;;
  res)      res=$(ScreenResolution) ; echo ${res%% *} ; exit ;;
  depth)    depth=$(ScreenColorDepth) ; echo ${depth%% *} ; exit ;;
  xorgconf) XorgConf $2       ; exit $? ;;
  -h|--help|-help) help ; exit ;;
  ""|-q) continue=1 ;;
  *) echo "Invalid option: $1" >&2 ; exit 1 ;;
esac

##############################################
#                 REPORT
##############################################

XSERVER="$(readlink /usr/bin/X)"
. /etc/DISTRO_SPECS

(
echo "$(gettext 'VIDEO REPORT:') ${DISTRO_NAME}, $(gettext 'version') ${DISTRO_VERSION}"
processor=`cat /proc/cpuinfo | grep "model name" | head -1`
echo "Processor: ${processor##*:}"
Xorg -version 2>&1 | head -n 3
echo -e "\n$(gettext 'Chip description:')\n$(VideoChip)"

if [ "$XSERVER" = "Xorg" ];then
  if [ -f /etc/X11/xorg.conf ];then
    sPTN='/^Section "Screen"/,/^$/p' #this is a multi-line block find expression.
    reqVIDEODEPTH=$(XorgConf videodepth)
    reqVIDEORES=$(XorgConf videores)
    echo -e "\nRequested by /etc/X11/xorg.conf:"
    [ "$reqVIDEORES" ] && echo "  $(gettext 'Resolution (widthxheight, in pixels): ')${reqVIDEORES}"
    [ "$reqVIDEODEPTH" ] && echo "  $(gettext 'Depth (bits, or planes):              ')${reqVIDEODEPTH}"
    REQMODS=$(XorgConf reqmods)
    [ "$REQMODS" ] && echo "  $(gettext 'Modules requested to be loaded:       ')${REQMODS}"
    DISABLEMODS=$(XorgConf disabledmods)
    [ "$DISABLEMODS" ] && echo "  $(gettext 'Modules requested to not be loaded:   ')${DISABLEMODS}"
    #this section is normally commented out...
    reqDRIVER=$(XorgConf reqdriver)
    [ "$reqDRIVER" ] && echo "  $(gettext 'Drivers requested to be loaded:       ')${reqDRIVER}"
  else
    echo -e "\n$(gettext 'NOTE: there is no /etc/X11/xorg.conf configuration file.')"
  fi

  echo -e "\n$(gettext 'Probing Xorg startup log file (/var/log/Xorg.0.log):')"
  video_driver=$(XorgVideoDriver)
  [ "$video_driver" ] && echo "  $(gettext 'Driver loaded (and currently in use):') ${video_driver}"
  loaded_modules=$(XorgLoadedModules)
  echo "  $(gettext 'Loaded modules:')${loaded_modules}"

  echo -e "\n$(gettext 'Actual rendering on monitor:')"
  actual_res=$(ScreenResolution)
  echo "  $(gettext 'Resolution:  ')${actual_res}"
  actual_depth=$(ScreenColorDepth)
  echo "  $(gettext 'Depth:       ')${actual_depth}"
fi

echo
get_glxinfo
echo

while IFS=":" read MON NAME WH
do
	case "$MON" in '#'*|"") continue ;; esac
	[ -z "$NAME" ] && continue
	echo
	echo "Monitor  :" $MON
	echo "Model    :" $NAME
	echo "WxH (cm) :" $WH
done <<< "$(get-monitor-names)"

) > /tmp/report-video

cat /tmp/report-video
echo
echo "$(gettext '...the above also recorded in /tmp/report-video')" #130207

### END ###
```

**Comment by wdlkmpx** [comment]
Using both methods is the solution.

I found that sometimes it reported the wrong driver. I was testing the kms stuff. Booting with and without kms enabled.

I notice an inconsistent behavior in the system. After the second boot with a pupsave, something that failed on first boot started to work (could not restart X on first boot). It was a bit confusing.

I tested in a couple machines and it worked, it even worked in my dead raspi 1.  But the logic in the xorg log is highly inconsistent.

**Comment by wdlkmpx** [comment]
Xorg.0.log from my raspi 1

```

[  3862.831] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  3862.867] (II) Module glx: vendor="X.Org Foundation"
[  3862.867] 	compiled for 1.19.2, module version = 1.0.0
[  3862.867] 	ABI class: X.Org Server Extension, version 10.0
[  3862.868] (==) Matched modesetting as autoconfigured driver 0
[  3862.868] (==) Matched fbdev as autoconfigured driver 1
[  3862.868] (==) Assigned the driver to the xf86ConfigLayout
[  3862.868] (II) LoadModule: "modesetting"
```

The problem with the old logic is that sometimes xorg doesn't report it has unloaded a driver, theoretically it has 2 or more active drivers.

So when i had kms enabled it reported that the vesa driver was currently in use.. that's not possible.

**Comment by 01micko** [comment]
I notice that if evdev (auto add devices) is used the log takes on a whole different persona :face_with_head_bandage:

**Comment by ghost** [comment]
Thanks 01micko and wdlkmpx! I learned a lot I didn't know here. The fallback script posted worked on both my netbooks. :cat2: I also tried a dpup build and in that OS modesetting worked even without the fallback (but using xorg 1.11 modesetting instead of xorg 1.19).

**Comment by ghost** [comment]
Sorry that it shows 3 pull request attempts for the same thing, I tried to preserve the original "no newline at the end of file" using web interface but without success, even when keeping the old ending. I wonder if that matters or maybe github thinks their ending is better. :thought_balloon: :thinking: :joy_cat:
