### ISSUE TITLE
xwin hangs when using pfix=nox

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1484]
The problem is at the top of `/usr/bin/xwin`

`which` is called and by using `&` seems to get forked and all you see at the prompt is `/usr/bin/Xorg`, which kind of defeats the purpose of `& > /dev/null` which is *supposed* to send all output to oblivion. A return key press is required to finish the script.

I'm not a big fan of `which`. Its behaviour varies radically between full and busybox versions. Better off to use the internal `type` IMO. And `2 > /dev/null` is enough in this case.

**Comment by wdlkmpx** [comment]
`&>/dev/null` is used in many many many many many scripts.

It works with:
- ash (busybox)
- bash

And fails with:
- dash

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/bin/xwin#L22

I guess `which ... &>/dev/null` should be replaced with `type ... 1>/dev/null 2>&1`. `which` -> `type`

A massive operation, easy to do 

Type is a shell builtin in:
- bash
- ash 
- dash
- what else?

**Comment by 01micko** [comment]
Probably fish, zsh, maybe csh, hush
