### ISSUE TITLE
/etc/rc.d/rc.sysinit

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1490]
boolean1 on the forum has posted this ....
```
if i am not mistaken , there is a line dropped from
/etc/rc.d/rc.sysinit

LINE 565:modprobe $MODULE $MPARAMS

to parse ADDLIST= variable
```

**Comment by wdlkmpx** [comment]
That line seems to be missing, but i didn't edit that part, i rebased so many times from so many branches, and this probably happened somehow
