### ISSUE TITLE
Maybe we need a new overlayed icon

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1491]
On the pi, from commit f1ffba2db8897bc83bb26da57eb90166beacee4c it no longer boots into ram.. no problem, probably better that way, however on most pi's running puppy in RAM they are set up on 2 partitions so I get 2 'home' partition icons. No big deal except for aesthetics.

Maybe, if we could have a new overlayed icon with something other than the home icon or eject icon. I did knock up a quick overlay icon .. I called it boot_outline48.png

![boot_outline48](https://user-images.githubusercontent.com/1019119/61164913-433b1d80-a55d-11e9-9280-11f5661f4ec2.png)

Hmm.. that's a bit hard to see..

![usb48](https://user-images.githubusercontent.com/1019119/61164946-a88f0e80-a55d-11e9-8455-ca6cfe6102c3.png)
![card48](https://user-images.githubusercontent.com/1019119/61164967-d70ce980-a55d-11e9-8df3-c693762d2d07.png)

**Comment by wdlkmpx** [comment]
Yes probably.

For pupmode 13 to be effective it must default to manual saves.. i think i'll also add a tray floppy icon with options [yad] (can be disabled) for newbies, so that they know they're in special mode that requires their attention and understanding.

I've been meaning to implement that, but i'm being slow.

**Comment by wdlkmpx** [comment]
In pupmode 13 the timer should be a global service, so that it works with and without X, for cli-only builds, probably a small ncurses dialog can be added.

This probably means the end of pup_event_frontend_d

**Comment by 01micko** [comment]
I might name this icon `boot-nocopy' or something. I'll have a look.

**Comment by 01micko** [comment]
Ok I've implemented this in my fork - PR soon, just doing some testing. Works as expected on the raspi and in qemu with a qcow2 VHD booting off virtual cdrom - see pic.

![qemu](https://user-images.githubusercontent.com/1019119/64507059-3b54eb00-d30c-11e9-8384-6604d523c4d0.png)

**Comment by 01micko** [comment]
Next I'll do a bare metal USB install (2 parts on USB) but because I have no machine with `<`1024MB RAM I'll have to use `pfix=nocopy` on the kernel line.

**Comment by 01micko** [comment]
A closer look.. I chose a lilac sort of colour, less boring than the grey..

![qemu2](https://user-images.githubusercontent.com/1019119/64507407-44928780-d30d-11e9-8524-05a664e9e41c.png)

**Comment by 01micko** [comment]
..and here we are on the raspberry pi 3 ..

![Screenshot](https://user-images.githubusercontent.com/1019119/64509602-6e56a900-d323-11e9-8ed7-7011155632a6.png)


![Screenshot2](https://user-images.githubusercontent.com/1019119/64509721-acec6380-d323-11e9-9537-4b10bb511043.png)

I think the 2 most common use cases are pretty clear. While it may not seem like much I'm sure it will avoid some confusion.
