### ISSUE TITLE
newer busybox dc breaks functions_x (and other scripts)

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1492]
Well I suppose we can do a test for newer busybox...

I'm comparing in the below snippet against BB 1.30.. is that where `dc` changed? I dunno.

```shell
fx_format_bytes() {
	[ $1 ] || return
	local BYTES=$1
	local FORMATTEDSIZE="${BYTES}B" # bytes
	# newer busybox dc has different syntax after bb-1.30
	local BBVER=`busybox | awk 'NR==1 {gsub("v",""); print $2}'` # eg: 1.31.0
	local DCNEW=1 # initiate in case vercmp is broken/missing
	vercmp $BBVER ge 1.30
	DCNEW=$?  #0 if true
	if [ ${BYTES} -ge 1099511627776 ] ; then
		if [ $DCNEW -eq 0 ] ; then
			FORMATTEDSIZE="`dc -e"$BYTES 1099511627776 2 k / p"`"
		else
			FORMATTEDSIZE="`dc $BYTES 1099511627776 \/ p`"
		fi
		FORMATTEDSIZE="`LANG=C printf "%.2f" $FORMATTEDSIZE`T" #terabytes
	elif [ ${BYTES} -ge 1073741824 ] ; then
		if [ $DCNEW -eq 0 ] ; then
			FORMATTEDSIZE="`dc -e"$BYTES 1073741824 1 k / p"`"
		else
			FORMATTEDSIZE="`dc $BYTES 1073741824 \/ p`"
		fi
		FORMATTEDSIZE="`LANG=C printf "%.1f" $FORMATTEDSIZE`G" # gigabytes
	elif [ ${BYTES} -ge 1048576 ] ; then
		FORMATTEDSIZE="$(( $BYTES / 1048576 ))M" # megabytes
	elif [ ${BYTES} -ge 1024 ] ; then
		FORMATTEDSIZE="$(( $BYTES / 1024 ))K" # kilobytes
	fi
	echo "$FORMATTEDSIZE"
}
```

The busybox version test uses awk to avoid bashisms.

**Comment by 01micko** [comment]
Hmmm.. other scripts calling dc - rootfs-skeleton only

```
/usr/bin/pmediainfo
/usr/sbin/inputwizard
/usr/sbin/puppyinstaller
/usr/sbin/remasterpup2
/usr/sbin/sfs_load
/usr/sbin/shutdownconfig
```

**Comment by 01micko** [comment]
hmmmm... maybe a wrapper script?

The following is very simple and basically works with old bb dc and new bb dc. Could be improved immensely!

I don't propose to replace the dc >> busybox link just use the script as `dc-wrapper` or `dc-shell` or whatever. It's either that or put if/else statements everywhere that dc appears in a script. Might make it easier too if `BBVER` is exported as an environment variable.

```shell
#!/bin/ash
#wrapper for busybox dc

BBVER=`busybox | awk 'NR==1 {gsub("v",""); print $2}'` # eg: 1.31.0
DCNEW=1 # initiate in case vercmp is broken/missing
vercmp $BBVER ge 1.30
DCNEW=$? # 0 means we use the new syntax

# the new version requires at least '-e' option and also needs an 
# integer preceding 'k' operator for floating point precision
# also can't handle escaping '/', so '\/' is not allowed
# PLUS everyting after the option(s) must be quoted!

# we'll try and emulate the old version
echo "old args: $@" # debug
if [ $DCNEW = 1 ] ; then # using old version so pass whole lot to dc
	exec busybox dc $@
else
	args="`echo "$@" | sed -e 's%\\\/%/%' -e 's%\/%3 k /%'`"
	echo "new args: $args" # debug
	exec busybox dc -e "$args"
fi
```

notes:
- only supports the `k` operator on division at this stage, although it could be made global
- hard coded to 3 decimal places

**Comment by wdlkmpx** [comment]
I already have a fix for everything

**Comment by wdlkmpx** [comment]
But as i haven't released a tarball, i haven't pushed the changes. I'll prepare a tarball

**Comment by wdlkmpx** [comment]
I guess zwm has some broken stuff, but currently i'm not interested in fixing stuff in zwn, you're adding your own builds, but the zwn slacko will have broken stuff. When I say a tarball i mean a initrd-progs tarball + static busybox for the main sfs.

It's simpler when a build is so generic that nobody else has to compile it.

**Comment by 01micko** [comment]
That's good. Have you a patch for dc?

Don't worry about zwn. I had a bit of fun with it but apt is a pain. My goal is to build from slackware-current for arm in zwn. I have a pi 0 on order and toying with the idea of a pi 4 soon.  

> It's simpler when a build is so generic that nobody else has to compile it.

Should go into woof-arch then.

I'll close this and await the new tarball.

**Comment by wdlkmpx** [comment]
Yes i do have a patch for dc.. i applied it for busybox 1.30.1, to make it

dc behaves like the full dc but without --long options.

I actually sent a patch to the busybox mailing list implementing the
standard behavior, it was simple, a hack.

But then someone posted a full rewrite with 7000+ lines that included
bc, and that bc is what i patched to get the old behavior.. a hack

I deleted that patch for 1.31.0.

And decided to patch the whole woof-ce instead... changes are in a local branch

**Comment by wdlkmpx** [comment]
I think slackware arm current only supports armv7, so you won't be
able to use a raspi zero or 1.

woodenshoe-wi seems to be willing to compile stuff in his raspi 1 with
raspup, so i guess it's a matter of asking him politely to compile
something

Yesterday i bought many things, i kind of regret it

- hard drives
- hdmi cable + mini & micro hdmi adapters
- 1 tb external drive
- cases/converters sata hdd/ssd 2.5 to usb [2.0 & 3.0]
- hdmi to vga adapter
- otg/mini usb to usb adapters
- misc adapters including an audio to usb adapter, wifi adapter
- an internal pci wifi adapter for laptop
- etc

And before i knew my pocket was completely empty and i guess i should
start selling what i bought

**Comment by wdlkmpx** [comment]
see PR #1493 .. 

I may update the zwn tarball one of these days, because both build systems will use the same tarball and the woof-ce git repo will be smaller and smaller... if i get around to unify both build systems even more.

**Comment by 01micko** [comment]
yes -current arm is armv7. That's ok. There are a lot more boards than pi! Unfortunately my odroid-u3 USB died so no input. Might use it as a server.

In zwn I just get the arch files straight out of woof as of 0687c765af7f1cb24c0a55ac9516791ee563ebb1

**Comment by drscavngr** [comment]
also in /etc/rc.d/functions, pidof uses the -x switch, which doesnt exist in busybox pidof

for example : statusproc hddtemp
pidof: unrecognized option: x
BusyBox v1.29.3 (2018-09-25 16:13:15 +08) multi-call binary.

**Comment by wdlkmpx** [comment]
I don't have the full pidof.

In debian/ubuntu `pidof` is in `sysvinit-utils`.. not included in my build

In slackware 14.2+  `pidof` is in `procps-ng`.. i686 has it, x86_64 uses `|procps|procps|` .. a package that doesn't exist?

In slackware 14.0 & 14.1 `pidof` is in `sysvinit`.. but only the manpage, there are no binaries in the search results..?

Certainly not included in slacko 14.0 & 14.1

So we have a problem here. I'll think about how to fix this

**Comment by wdlkmpx** [comment]
Hmmm dr-scavenger already had a fix for the pidof issue, but had opened a pull request to the wrong repo, his own repo.

Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/d43ae3b0756b0fa80d097146dbf11045373865c3 fixes the issue

**Comment by drscavngr** [comment]
i am new to this git thing :-)

**Comment by wdlkmpx** [comment]
There's no need to open a pull request, you can just provide a diff file or a complete file with the changes, as long as the changes are made to the latest version of the file.

Fixes are merged immediately, that's for sure, new features and stuff might need further review, and in some cases a clash of philosophies happen, and that's when things get stalled, but will try to review, fix and more merge stuff

**Comment by wdlkmpx** [comment]
Hahaha the commit has "dr-scanvenger" as the author, well it can't be fixed now...

When someone has already contributed to the git repo, it's easy to assign the author field, git autocompletes, for everyone else i have to add the author in a more manual way. I mean when i merge stuff manually (not pull requests).
