### ISSUE TITLE
[Suggested Enhancement]Allow partitions to show custom icons in rox desktop, by using .DirIcon

### ISSUE THREAD

**Issue by drscavngr** [puppylinux-woof-CE/woof-CE#1499]
```
--- frontend_rox_funcs	2020-07-19 01:12:38.165714834 +0300
+++ /usr/local/pup_event/frontend_rox_funcs	2019-07-19 01:18:51.417698835 +0300
@@ -87,34 +87,38 @@
 
 rox_icon_mounted_func() {
 	[ "$ROX_DESKTOP" != "yes" ] && return
-	#passed params: drivename category  ex: sda usbdrv
-	DRVICON="drive_mntd48.png" #default.
-	[ "$2" = "usbdrv" ] && DRVICON="usbdrv_mntd48.png"
-	[ "$2" = "card" ] && DRVICON="card_mntd48.png"
-	[ "$2" = "floppy" ] && DRVICON="floppy_mntd48.png"
-	[ "$2" = "optical" ] && DRVICON="optical_mntd48.png"
-	imPATTERN="^/dev/${1} |^/dev/mapper/lukspartition_${1} " #support luks-encrypted partitions
-	if [ "`mount | grep -E "$imPATTERN" | cut -f 1,3 -d ' ' | grep -v ' /initrd/' | grep -v ' /$'`" = "" ];then
-		#only partitions mntd on /initrd/* then must be mntd at boot. cannot unmount.
-		#also, full hd install has partition mntd on '/'.
-		DRVICON="drive_mntd_boot48.png" #default.
-		[ "$2" = "usbdrv" ] && DRVICON="usbdrv_mntd_boot48.png"
-		[ "$2" = "card" ] && DRVICON="card_mntd_boot48.png"
-		[ "$2" = "floppy" ] && DRVICON="floppy_mntd_boot48.png"
-		[ "$2" = "optical" ] && DRVICON="optical_mntd_boot48.png"
-	fi
-	#find out if already done...
-	if [ -f /root/.config/rox.sourceforge.net/ROX-Filer/globicons ];then
-		GLOBLINES="`cat /root/.config/rox.sourceforge.net/ROX-Filer/globicons | tr '\n' '|' | sed -e 's%</rule>|%\n%g'`"
-		diPATTERN='/tmp/pup_event_frontend/drive_'"${1}"'"'
-		[ "`echo "$GLOBLINES" | grep "$diPATTERN" | grep "$DRVICON"`" != "" ] && return
-	fi
+	mounted_Icon_Path="$(findmnt  --output=TARGET --first-only /dev/$1 |tail -1)/.DirIcon"
+	if [[  ! -f "${mounted_Icon_Path}" ]];then 
+		#passed params: drivename category  ex: sda usbdrv
+		DRVICON="drive_mntd48.png" #default.
+		[ "$2" = "usbdrv" ] && DRVICON="usbdrv_mntd48.png"
+		[ "$2" = "card" ] && DRVICON="card_mntd48.png"
+		[ "$2" = "floppy" ] && DRVICON="floppy_mntd48.png"
+		[ "$2" = "optical" ] && DRVICON="optical_mntd48.png"
+		imPATTERN="^/dev/${1} |^/dev/mapper/lukspartition_${1} " #support luks-encrypted partitions
+		if [ "`mount | grep -E "$imPATTERN" | cut -f 1,3 -d ' ' | grep -v ' /initrd/' | grep -v ' /$'`" = "" ];then
+			#only partitions mntd on /initrd/* then must be mntd at boot. cannot unmount.
+			#also, full hd install has partition mntd on '/'.
+			DRVICON="drive_mntd_boot48.png" #default.
+			[ "$2" = "usbdrv" ] && DRVICON="usbdrv_mntd_boot48.png"
+			[ "$2" = "card" ] && DRVICON="card_mntd_boot48.png"
+			[ "$2" = "floppy" ] && DRVICON="floppy_mntd_boot48.png"
+			[ "$2" = "optical" ] && DRVICON="optical_mntd_boot48.png"
+		fi
+		#find out if already done...
+		if [ -f /root/.config/rox.sourceforge.net/ROX-Filer/globicons ];then
+			GLOBLINES="`cat /root/.config/rox.sourceforge.net/ROX-Filer/globicons | tr '\n' '|' | sed -e 's%</rule>|%\n%g'`"
+			diPATTERN='/tmp/pup_event_frontend/drive_'"${1}"'"'
+			[ "`echo "$GLOBLINES" | grep "$diPATTERN" | grep "$DRVICON"`" != "" ] && return
+		fi
+		mounted_Icon_Path="/usr/local/lib/X11/pixmaps/${DRVICON}"
+	fi	
 	echo "<?xml version=\"1.0\"?>
 <env:Envelope xmlns:env=\"http://www.w3.org/2001/12/soap-envelope\">
  <env:Body xmlns=\"http://rox.sourceforge.net/SOAP/ROX-Filer\">
   <SetIcon>
    <Path>/tmp/pup_event_frontend/drive_${1}</Path>
-   <Icon>/usr/local/lib/X11/pixmaps/${DRVICON}</Icon>
+   <Icon>${mounted_Icon_Path}</Icon>
   </SetIcon>
  </env:Body>
 </env:Envelope>"  | roxfiler_R
@@ -657,4 +661,4 @@
 	$@
 fi
 
-### END ###
\ No newline at end of file
+### END ###
```

**Comment by mavrothal** [comment]
Interesting. The icon changes when the device/partition is mounted.
However, with this you lose the ability to unmount the partition using the arrow in the upper right corner. 
So unless you come up with a solution for unmounting, I think is not going to make it.

**Comment by wdlkmpx** [comment]
You can still unmount partitions, but there is no special icon, just click on the top right of the icon

Icon_switcher creates special icons for mounted partitions, when you change a theme

```
$PNGOVERLAY ${ONEDRV}48.png closebox_outline48.png ${ONEDRV}_mntd48.png 
```

The .DirIcon (.png) must be converted to 48x48 (current pngoverlay only accepts 48x48) and with pngoverlay a tmp icon could be created

**Comment by wdlkmpx** [comment]
Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/4f68de481d54e9de76fa7099b3582da0d7781471 implements this feature in a proper way

But the icon is not resized, only 48x48 icons look good.

I think that's enough, but is resizing is to be added... netpbm is big, imagemagick is big, it can happen with picscale... after it has been converted to C
[picscale.bac.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/3427891/picscale.bac.zip)

I certainly won't do that. But referencing @01micko

**Comment by 01micko** [comment]
I could rewrite `pngoverlay-cairo` sure, but I don't think encouraging other sized icons is a good idea... 

I'm open to other opinions.

**Comment by wdlkmpx** [comment]
I edited the old pngoverlay.c and somehow it was quite easy to make it work for this special case:

[pngoverlay-gtk2.c.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3432657/pngoverlay-gtk2.c.gz)

Adding a .png/.jpg/.svg .DirIcon images with any size, i see it creates a proper png custom icon for mounted drives

It only scales the image(s) if the size is not 48x48.. sounds fair. It only works with X.. and this feature  requires rox to be running

**Comment by wdlkmpx** [comment]
I added (optional) support for pngoverlay-gtk2 (frontend_rox_funcs)

I also added a i686 binary

pngoverlay 0.2:
https://github.com/puppylinux-woof-CE/petbuilds/commit/0cb36a9584264726f1169a405fae35d7d670e7cc

I think i'll also convert picscale.bac to picscale.c and will probably add it to the pngoverlay .petbuild

I think there should be a special package where many of the tiny puppy apps are compiled at once. All of them part of a single package.

**Comment by 01micko** [comment]
ugh... multiple utilities for the same thing. I *can* fix pngoverlay-cairo to do all this (scale, etc) but..

> I don't think encouraging other sized icons is a good idea...

**Comment by wdlkmpx** [comment]
It's certainly duplicade code, and it's not in icon_switcher so it's
only used when a partition is mounted and a .DirIcon is found, only
when you click on a drive icon. This certainly makes rox a bit more
interesting, as it has some important drawbacks at least this is
another plus..

But reading a bit about cairo, it seems to need specific functions to
open specific file formats or something (_from_png).

With gdkpixbuf everything is already wrapped in a single function and
many image formats are supported (input/output). And it will not crash
when invalid data is provided. It's just a simple way to achieve many
things.. as long as xorg is running.

That's why i see potential in picscale, i already converted it to C,
but i see it can be considerably improved to make it a tiny pro app.

I see a generic jwm can be created if gdkpixbuf is added as the only
image loader. Pure X+GTK2.. hmmm

**Comment by wdlkmpx** [comment]
Talking about converting and scaling pics, peasyscale's image-changer
seems to be the same kind of tool, using the same functions, but i
can't find the source, it's based on scale2pic

http://dotpups.de/dotpups/Graphics/Scale2pics.pet .. i'll see what's
in there later

peasyscale also needs an update to make it process files faster.

It's so easy to waste time, but at least stuff is getting to some repo hahaha

I guess i should now focus and performing and testing pirated windows
10 installs and automate the process, people pay $$ for that simple
task. My pal being my first client.
