### ISSUE TITLE
Incorrect driver reported by QuickSetup

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1500]
BUILD_FROM_WOOF='testing;36ae4e6f7;2019-07-16 09:25:58 +0800'

QuickSetup shows fbdev driver and is incorrect
whereas PupSysInfo shows modesetting / nouveau

![Screenshot](https://user-images.githubusercontent.com/5926865/61580837-1dd68280-ab0e-11e9-9d32-099ba872aa55.png)

▶—— DISPLAY ——◀

Display Specifications:
• Monitor VertRefresh: 59.79 times/s
• Screen Dimensions: 1366x768 pixels (361x203 millimeters)
• Screen Depth: 24 bits (planes)

Xorg Startup Log (/var/log/Xorg.0.log):
• Xorg Driver in use: modesetting
• Loaded Modules: dbe evdev fb fbdev glamoregl glx libinput
• X.Org version: 1.20.5

OpenGL 2D/3D Rendering:
• Direct Rendering: Yes
• Vendor: nouveau
• Renderer: NVA8
• Version: 3.3 (Compatibility Profile) Mesa 19.1.2

VGA controller [0300]: NVIDIA Corporation GT218 [NVS 300] [10de:10d8] (rev a2)
• Kernel Driver: nouveau
• Memory Used by Driver: 1700.00 KB
• Path: /lib/modules/5.1.6-lxpup64/kernel/drivers/gpu/drm/nouveau/nouveau.ko
• Description: nVidia Riva/TNT/GeForce/Quadro/Tesla/Tegra K1+
• Video RAM: 503M total, 64M 32M prefetchable

**Comment by 01micko** [comment]
@peabee I'll take a look because I'm currently working on a GUI for raspi config.txt to fix over/underscan and that needs to be inserted into quick setup.

**Comment by 01micko** [comment]
@peabea there is a problem here. Radky is using Barry's old method to pickup the driver but that fails when evdev is exclusively in use in some situations. We use that as the fallback. For some reason the code is reporting `fbdev` in the first part and not falling through. We'll need a look at your `/var/log/Xorg.0.log`

**Comment by peabee** [comment]
[Xorg.0.log.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3414396/Xorg.0.log.gz)

Here you go - false .gz
Same problem manifests on my laptop with intel graphics BTW

**Comment by 01micko** [comment]
Wow. bugs everywhere, including Roger's code.

First - fix your fbdev module, it's broken, (version mismatch) and *is not* loaded, therefore can't be unloaded.

Second - include evdev xorg module - not there according to the log - not loaded.

Third - provide a new log when these are done.

**Comment by peabee** [comment]
Fixed - had to update xf86-video-fbdev from current/extra
Quicksetup is now showing correct modesetting driver

[Xorg.0.log.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3414544/Xorg.0.log.gz)

**Comment by 01micko** [comment]
Ok, good. I do believe `report-video` probably can and should be improved but we'll wait and see.
