### ISSUE TITLE
loglevel=[1-15] does not gets passed to init, where it gets reset to the default 3

### ISSUE THREAD

**Issue by drscavngr** [puppylinux-woof-CE/woof-CE#1514]
loglevel , is a _recognized_ kernel parameter , 

> The kernel parses parameters from the kernel command line up to “–”; if it doesn’t recognize a parameter and it doesn’t contain a ‘.’, the parameter gets passed to init: 

so it does not gets passed to init enviroment , so $loglevel is always NULL , it needs to be extracted from cmdline:

```

--- init_original	2019-07-28 01:47:24.549383014 +0300
+++ init	2019-07-28 01:51:44.956397947 +0300
@@ -85,9 +85,9 @@

-if [ $loglevel ] ; then
-  LOGLEVEL=$loglevel
-else
+LOGLEVEL="$(tr ' ' '\n' < /proc/cmdline | grep '^loglevel=' | cut -d= -f2 )"
+
+if [ ! $LOGLEVEL ] ; then
   echo '3' > /proc/sys/kernel/printk # '3' is the standard loglevel.
 fi


```

**Comment by drscavngr** [comment]
init_full_install also contain this bug

**Comment by s243a** [comment]
Why was this thread closed? If we can't set the log_level then we can't control the amount of debugging info that we get at boot. 

P.S. thankyou drscavngr  for this info.

**Comment by wdlkmpx** [comment]
Because the fix was applied, the commit that merged the patch closed
this. I forgot to apply the same fix to init_full_install, will do
that later
