### ISSUE TITLE
PPM is broken

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1520]
I keep getting this in slacko and raspup recent builds
![Screenshot](https://user-images.githubusercontent.com/1019119/62827949-b5675680-bc1e-11e9-8e33-ebfa1d3bd38e.jpg)

I'm only trying to install the package!

I'm not fixing it either, because at the released slacko-6.9.9.9 it worked fine, still have the original jun-11-2017 save file running sweetly.

**Comment by wdlkmpx** [comment]
I tested with dpup and the packages install, it's quite recent but it already has a pupsave, the issue might get trigered in pristine installs

The code is just too ugly and relies too much on external commands, but i'm being forced to take a look again, it will probably lose more lines

**Comment by wdlkmpx** [comment]
I mean has anybody tested in bionicpup64 without phil's hacks? It was partially broken in bionicpup64 but only in bionicpup64.

**Comment by wdlkmpx** [comment]
Confirming the issue, stuff happened, i merged some rizaltmart's patches, code from the experimental branch and i guess something got broken along the way

**Comment by wdlkmpx** [comment]
The issue only happens in the "Step by step" mode in pupmode 5?, it does not affect the "auto install" mode

**Comment by 01micko** [comment]
> The issue only happens in the "Step by step" mode in pupmode 5?

Hmm... pupmodes 12 and 13 respectively here (refer OP) 

Busy building kernels on pi atm but may have an update later.

**Comment by 01micko** [comment]
Auto install seems ok, step by step is broken. Auto should be default anyway. Who wants to click 4 or 5 times?

**Comment by wdlkmpx** [comment]
The issue seems to happen only with pet packages.

I really doubt most people who have edited the ppm properly understand
how it works, there are a bunch of /tmp files that are read and
processed by a bunch of scripts, taking notes seems to be the only way
to deal with it. I need a pen and a sheet of paper

The build system lost all if its gtk code while i was simplifying it
so that it can work without x and share code with zwn

But by simplifying the ppm even more i might get some unwanted attention

**Comment by s243a** [comment]
> The issue seems to happen only with pet packages. I really doubt most people who have edited the ppm properly understand how it works, there are a bunch of /tmp files that are read and processed by a bunch of scripts, taking notes seems to be the only way to deal with it. I need a pen and a sheet of paper The build system lost all if its gtk code while i was simplifying it so that it can work without x and share code with zwn But by simplifying the ppm even more i might get some unwanted attention

I suppose, let's see the results. Having the package manager work without X is a good thing :)

**Comment by 01micko** [comment]
Thanks @ninaholic , @wdlkmpx 

I'll close this but PPM sure needs work... or deleting!

I was looking forward to a pet format change re #1494 but alas the conservatives won out. We can learn a hell of a lot from `zwn`, especially the awk code. So simple, clean and effective.

**Comment by wdlkmpx** [comment]
I would be lying if i said i was working on fixing this issue, but
i'll have to fix it, and i'll delete lines.

I have an update for common32/common64, all pet packages. To update
the older pups including slacko 14.2,

I just googled pet2deb and found this:
http://www.murga-linux.com/puppy/viewtopic.php?p=783785#783785

Maybe there's a more advanced version in the ddog repositories,
perhaps it should be included in wce. Maybe fdog has a conversion tool
from pet to a proper txz

I think slackware current has ffmpeg and many more packages, it's no
longer the most barebones distro in history

I think zwn should start with slackware 15.0 (x86 += salix) / debian
buster or devuan equivalent.. and that's it basically
