### ISSUE TITLE
github warning

### ISSUE THREAD

**Issue by ghost** [puppylinux-woof-CE/woof-CE#1525]
![warning](https://user-images.githubusercontent.com/5408521/63594260-fbf47380-c583-11e9-81b1-e6cc06afa38c.png)

stupid github, I like my password just fine, I would never be able to remember anything more complicating anyway

yes this is not really puppy related, but I disappear after Sept 1st you will know why

:octocat: :hammer:

**Comment by mrfricks** [comment]
i had this
just add a number or symbol to the end of your password

**Comment by ghost** [comment]
That worked. Thanks @mrfricks
