### ISSUE TITLE
dir2pet feature request

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1527]
it would be good it dir2pet used more than one core when creating an xz compressed .pet
```
xz
Regarding multithreaded XZ support. If you are running version 5.2.0 or above of XZ Utils, 
you can utilize multiple cores for compression by setting -T or --threads to an appropriate 
value via the environmental variable XZ_DEFAULTS (e.g. XZ_DEFAULTS="-T 0").
```

**Comment by peabee** [comment]
2nded
I have 8 cores ;-)  and the only time they are fully used is during mksquashfs and compiling....

**Comment by mavrothal** [comment]
Since ```lscpu``` is commonly left out in puppies, something like ```CN="$(grep -i processor /proc/cpuinfo | wc -l)``` will detect number of cores. 
Then amend line 523 (and 558 for good measure) of dir2pet with ```-T $CN```

**Comment by drscavngr** [comment]
I want to add a related request: 

in /usr/bin/petspec 
```
    <button>
     <label>Generate package database entry</label>
     <action type=\"exit\">GENERATE_DB</action>
    </button>
```
I wish there was a way , to set this button , as the default button when running dir2pet from terminal , i have to find my mouse to click "Generate package database entry" , which is annoying , i searched online but i didn't  figure out how to do it

**Comment by sc0ttj** [comment]
Could also use `pigz`, a multi core replacement for gzip ..

**Comment by scsijon** [comment]
And that's the problem, a lot of compression packages won't sucessfully run multi-core. You will need to add a test against the version for each used to ensure both the machine and compression application is suitable to run multi-core first, with fallback of course. And don't just say you need to upgrade your version of ..., that doesn't always work and if using an earlier version of puppy, it becomes a not-possible action.
