### ISSUE TITLE
swap file or partition may be present on removable drives

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1529]
I have a couple of portable harddrives (USB) that have swap partitions.

If I unmount the normal partitions and pull the USB plug out and the swap is on I get errors.

I suppose we should detect if there is a swap partition / file on the device (doesn't need to be a hdd) and if it is in use ie: `cat /proc/swaps`. We have no way of knowing if the user is going to unplug the device so if all partitions are unmounted on the device (from clicking the partition icon) perhaps a warning gui could be popped  asking them if they want to turn off the swap - with words to the effect 'if you are going to unplug `<device>` then swap needs to be turned off', with buttons 'swap off' and 'dismiss'.

Of course most people wont have swap on their portable devices, and if so it is unlikely to be turned on unless it was plugged in at bootup.

TBH, I can't think of a better way.. I hate nag screens! I suppose we can just do nothing and close this issue. Whatever.

Thoughts?

**Comment by gyrog** [comment]
You could patch 'drive_all' (I think it is), so that when clicking on a desktop icon to umount it, if the partition is on a usb device and the usb device contains any active swap, then a dialog opens that asks if you want to "swapoff" the swap, or do nothing.
i.e. it's not just a "nag" screen.

Of course the obvious thing is to not place any swap on a usb device that you are likely to want to unplug from the running system.

**Comment by 01micko** [comment]
@gyrog yeah that was pretty much the way I was heading. I *may* dive in but I have been very busy with raspup development. Hence my noticing the 'bug'. I have been shifting around hdd's to compile on between 3 pi's and my main computer.

**Comment by mavrothal** [comment]
I remember this issue from the XO era. 
Swap partition should be ignored if not on a HD or at least an SDcard.
If the user enforces swap on a removable USB then something permanent should be showing on the desktop. Like a drive icon with an S or a lock. 
Of course nothing protects from unplugging in a hurry even with a permanent big red banner across the screen ( 😄 ), so may not worth the hassle.

**Comment by 01micko** [comment]
I have this basically working. It makes sure that it is a `usbdrv` . If swap is on sdcard it is 99% likely to be boot media and a swapfile is pretty much the same deal, so those cases will be ignored. It's an unlikely case in any event but nevertheless it can happen, especially when developing.

It also makes sure it is the last partition mounted, so the nag screen (lol @gyrog ) doesn't appear when there is another partition still mounted on the drive. Code later.

**Comment by 01micko** [comment]
Ok, here is a diff

```diff
--- /initrd/pup_ro2/usr/local/pup_event/frontend_rox_funcs	2019-06-07 18:19:41.000000000 +1000
+++ /usr//local/pup_event/frontend_rox_funcs	2019-09-02 07:05:34.694028822 +1000
@@ -556,6 +556,21 @@ $(gettext "PLEASE PRESS THE 'EXIT' BUTTO
 #
 # drive_all
 #
+
+chk_swap() {
+	# $1 = $ONEDRVNAME
+	ONEDRVNAME=$1
+	DNAME=$(fx_get_drvname $ONEDRVNAME)
+	TESTDRV=`grep $DNAME /proc/mounts |grep -v $ONEDRVNAME`
+	[ -n "$TESTDRV" ] &&  return 0 # nothing to do here
+	SWAP=`grep $DNAME /proc/swaps | cut -d ' ' -f1`
+	[ -z "$SWAP" ] && return 0 # nothing to do here
+	# pop a fancy gui
+	/usr/lib/gtkdialog/box_yesno "$(gettext 'Swap is on')" "$SWAP $(gettext 'swap partition is mounted on') $DNAME $(gettext 'drive.')"  "$(gettext 'If you intend to remove the drive then please turn swap off.')" "$(gettext 'Do you want to turn swap off?')"
+	[ $? = 0 ] && swapoff $SWAP
+	return 0
+}
+
 rox_desktop_icon_clicked() {
 	[ "$ROX_DESKTOP" != "yes" ] && return
 	ONEDRVNAME="$1" # /tmp/pup_event_frontend/drive_<ONEDRVNAME>/AppRun
@@ -606,6 +621,7 @@ rox_desktop_icon_clicked() {
 				DRV_CATEGORY=$(probedisk $ONEDRVNAME | cut -d'|' -f 2)
 				[ "$MNTPT" = "" -a "$DRV_CATEGORY" = "optical" ] && eject /dev/$ONEDRVNAME
 			fi
+			probedisk ${ONEDRVNAME:0:3} | grep -q 'usbdrv' && chk_swap $ONEDRVNAME
 			[ "$MNTPT" = "" ] && exit #precaution.
 			if [ "$MNTPT" = "/" -o "`echo "$MNTPT" | grep '/initrd/'`" != "" ];then
 				/usr/lib/gtkdialog/box_ok "$(gettext 'Puppy drive manager')" error  "$(eval_gettext "/dev/\${ONEDRVNAME} mounted on \${MNTPT}
@@ -657,4 +673,4 @@ if [ "$1" ] ; then
 	$@
 fi
 
-### END ###
\ No newline at end of file
+### END ###
```
What do ya reckon @wdlkmpx @gyrog @mavrothal ?
Swap goes off when 'yes' is chosen in gui. Stays on if cancelled or 'no' pressed.

**Comment by gyrog** [comment]
Looks reasonable.

Is it worth it?
Well since you've produced the code, might as well do it.
We know at least 1 person who might find this useful.

**Comment by wdlkmpx** [comment]
The dialog is triggered when you unmount a partition that is in a usb drive and a loaded swap (partition) (in the same drive) is detected. Looks good to me.

The patch doesn't work with mmcblkX and nmveX devices. $(fx_get_drvname) should be called before chk_swap, like this:

drvx=$(fx_get_drvname $ONEDRVNAME)
probedisk ${drvx} | grep -q 'usbdrv' && chk_swap $ONEDRVNAME

or

probedisk $(fx_get_drvname $ONEDRVNAME) | grep -q 'usbdrv' && chk_swap $ONEDRVNAME

fx_get_drvname() is in /etc/rc.d/functions_x

**Comment by 01micko** [comment]
I purposely omitted  everything except usb (see reason in earlier post). If I understand correctly, nvme is not usually removable (correct me if I'm wrong, I've never had experience with this media) . The likelihood of an mmcblkX device being anything other than boot media is low and if swap is on the device and it is not the main boot media then it should be ignored. Perhaps what @mavrothal says makes more sense than to proceed down the path I am on.

Another, thing. It would be nice if `probedisk` distinguished between an usbhdd (or ssd) and an usbflash device by default.

**Comment by 01micko** [comment]
OTOH, it may be intentional to plug in a portable drive with swap, especially on a restricted system. My main box has 8GB RAM and no internal swap. When compiling big stuff it is handy to have the swap there as backup.

Consequently, I can't agree with this from @mavrothal 

> Swap partition should be ignored if not on a HD or at least an SDcard.

So, in a restricted RAM environment it may be inadvisable to turn off the swap at all. I might rethink my patch.

**Comment by 01micko** [comment]
Righto.. this is close to final

```patch
--- /initrd/pup_ro2/usr/local/pup_event/frontend_rox_funcs	2019-06-07 18:19:41.000000000 +1000
+++ /usr//local/pup_event/frontend_rox_funcs	2019-09-02 20:20:37.054555303 +1000
@@ -556,6 +556,26 @@ $(gettext "PLEASE PRESS THE 'EXIT' BUTTO
 #
 # drive_all
 #
+
+chk_swap() {
+	# $1 = $ONEDRVNAME $2 = $DRVX
+	ONEDRVNAME=$1
+	DRVX=$2
+	TESTDRV=`grep $DRVX /proc/mounts | grep -v $ONEDRVNAME`
+	[ -n "$TESTDRV" ] &&  return 0 # nothing to do here
+	SWAP=`grep $DRVX /proc/swaps | cut -d ' ' -f1`
+	[ -z "$SWAP" ] && return 0 # nothing to do here
+	SWAPKB=`free -k | grep '^Swap:' | awk '{print $3}'`
+	if [ "$SWAPKB" != '0' ] ; then
+		  /usr/lib/gtkdialog/box_ok "$(gettext 'Swap is in use')" info "${SWAPKB}Kb $(gettext 'of swap space is in use. The') $ONEDRVNAME $(gettext 'partition will be unmounted however you are advised not to remove the drive.')"
+		  return 0
+	fi
+	# pop a fancy gui
+	/usr/lib/gtkdialog/box_yesno --yes-first --yes-label "$(gettext 'Turn Swap Off')" --no-label "$(gettext 'Dismiss')"  "$(gettext 'Swap is on')" "<b>$SWAP</b> $(gettext 'swap partition is active on') <b>$DRVX</b> $(gettext 'drive.')"  "$(gettext 'If you intend to remove the drive then please turn swap off.')" "$(gettext 'Press the ') <b>$(gettext 'Turn Swap Off')</b> $(gettext 'button to release the drive or ') <b>$(gettext 'Dismiss')</b> $(gettext ' to cancel.')"
+	[ $? -eq 0 ] && swapoff $SWAP
+	return 0
+}
+
 rox_desktop_icon_clicked() {
 	[ "$ROX_DESKTOP" != "yes" ] && return
 	ONEDRVNAME="$1" # /tmp/pup_event_frontend/drive_<ONEDRVNAME>/AppRun
@@ -606,6 +626,8 @@ rox_desktop_icon_clicked() {
 				DRV_CATEGORY=$(probedisk $ONEDRVNAME | cut -d'|' -f 2)
 				[ "$MNTPT" = "" -a "$DRV_CATEGORY" = "optical" ] && eject /dev/$ONEDRVNAME
 			fi
+			DRVX=$(fx_get_drvname $ONEDRVNAME)
+			probedisk $DRVX | grep -q 'usbdrv' && chk_swap $ONEDRVNAME $DRVX
 			[ "$MNTPT" = "" ] && exit #precaution.
 			if [ "$MNTPT" = "/" -o "`echo "$MNTPT" | grep '/initrd/'`" != "" ];then
 				/usr/lib/gtkdialog/box_ok "$(gettext 'Puppy drive manager')" error  "$(eval_gettext "/dev/\${ONEDRVNAME} mounted on \${MNTPT}
@@ -657,4 +679,4 @@ if [ "$1" ] ; then
 	$@
 fi
 
-### END ###
\ No newline at end of file
+### END ###
```
