### ISSUE TITLE
Include simple-mtpfs to woof builds

### ISSUE THREAD

**Issue by rizalmart** [puppylinux-woof-CE/woof-CE#1531]
Since pupmtp was a part of puppy. Out of the box MTP support is needed. simple-mtpfs must be added on woof build. Adding libmtp to build recipe is quite easy through pull request. The only problem was how to include simple-mtpfs. Maybe putting it the executable files on build support folder of woof.

**Comment by wdlkmpx** [comment]
I'll compile a generic build of simple-mtpfs, I was experimenting with this months ago, but I've doing other things. I already had a generic build that worked with libmtp compiled several compat distro versions, it worked in slacko 14.0 and dpup stretch, but I deleted it. I don't remember.

It's my understanding that a generic build of libmtp is also possible, a bit restricted without support for Z XXXX devices or something, as long as it doesn't link to libudev, I don't remember whether libudev is required or only udev rules.

I could also compile a proper libmtp for all the slackos and dpup.

But one thing is for sure, slacko 14.0 and slacko 14.1 will receive some upgrades
- z_libc-2.23-gcc5.5_libs-i586-1.pet
- z_libc-2.23-gcc5.5_libs-x86_64-1.pet

After upgrading util-linux it will be possible to compile the latest eudev.

And probably eudev 3.2.8? That would cause a disturbance in those old distros, but the result will be a consistent x86 pup ecosystem, where stuff just works. But xorg udev would only work in slacko 14.2+, dpup stretch+, upup xenial+

I don't know.

**Comment by peabee** [comment]
@rizalmart @wdlkmpx 
It cannot be correct that rootfs-skeleton has items - /usr/sbin/pupmtp & desktop - which have dependencies - simple-mtpfs - that cannot be satisfied since simple-mtpfs is not available in any repositories nor present in woof-ce. libsmtp is also a dependency but can be satisfied.
Currently, broken builds are created with pupmtp unable to run. pupmtp should be deleted until both 32 & 64-bit simple-mtpfs are readily available.

**Comment by wdlkmpx** [comment]
I won't delete anything. I'll compile libtmp and simple-mtpfs today,
but who knows when it will land in ibiblio.

**Comment by wdlkmpx** [comment]
This file contains libmtp, simple-mtpfs and other updates, all files
are required otherwise nothing will work.
www.01micko.com/wdlkmpx/tmp/ibiblio_update_nowz.tar.gz

**Comment by peabee** [comment]
Thought you now had access - have you asked @01micko ?
Uploaded.
Note: no need for slacko 14.1 - it is symlink to 14

**Comment by wdlkmpx** [comment]
Talking about broken apps.

peasyport (network scanner) requires:
- pnscan
- mpscan (turbo mode)
- arp-scan

peasyport includes 32bit versions of pnscan and arp-scan (doesn't work in dpup32).. it's broken or partially broken in most pups.

pnscan and mpscan are already in common32/64

**Comment by wdlkmpx** [comment]
Another broken app is peasyscale, it only works in 32-bit operating systems

**Comment by mrfricks** [comment]
there is a 64bit peasyscale https://distro.ibiblio.org/puppylinux/pet_packages-bionic64/peasyscale_64bit-2.1.pet

**Comment by wdlkmpx** [comment]
Do you have the source code fpr image-changer?

**Comment by mrfricks** [comment]
no I don't. I think rcrsn51 made the 64 bit version after a request from Barry. I'll pm rcrsn51 and see what he says
