### ISSUE TITLE
3builddistro - ../support/rootfs-hacks.sh rootfs-complete too late

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1533]
@wdlkmpx 
../support/rootfs-hacks.sh rootfs-complete
needs to be called before the chroot at line 488
it is too late at line 755

**Comment by wdlkmpx** [comment]
You have a to be a little more specific

**Comment by peabee** [comment]
Symlinks are created by rootfs-hacks.sh and these are needed during the build otherwise jwm-config fails with no libpcre.so.1 (from memory)
