### ISSUE TITLE
Anomalies in $PATH ?

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1556]
https://unix.stackexchange.com/questions/8656/usr-bin-vs-usr-local-bin-on-linux

> /usr/local/bin is for normal user programs not managed by the distribution package manager, e.g. locally compiled packages. You should not install them into /usr/bin because future distribution upgrades may modify or delete them without warning.

> Local programs and scripts belong in /usr/local/bin/

What does that mean? the local apps the user wants to run without breaking the system and without specifying a full path?

So when you install something to /usr/local/bin, it should override the system app.. or something.

Puppy follows exactly the opposite approach:

```
# echo $PATH
/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/root/my-applications/bin:/usr/games
 ```

- /root/my-applications/bin

It's a "local" dir, even "more" local than /usr/local/bin, but the opposite logic applies.

I was creating sfs packages (static ffmpeg), and was thinking, where should this go.. /usr/local/bin perhaps?

**Comment by 01micko** [comment]
No. In multiuser *nix `/bin` and `/sbin` are not in `$PATH`. A normal user's `$PATH` is usually `/usr/bin:/usr/games:/usr/sbin:/usr/local/bin:/usr/local/sbin` but this can be different across distros.

All that post is saying is that to _not_ break package management don't install apps in `/bin,/sbin/,/usr/{bin,sbin}`

That is why by default most packages if you use default `./configure` options , `PREFIX` is set to `/usr/local` so everything gets installed to `$PREFRIX/{bin,sbin,etc,var}` and so on.

To override an installed app from package manager then you compile it with defaults (supposedly, even though `/usr/local/etc` , for example, will unlikely be sourced)  and uninstall the shipped version. Make sense?

**Comment by wdlkmpx** [comment]
Hmm I guess it makes sense
