### ISSUE TITLE
we need to fix missing icons

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1560]
Potentially all these svg icons are needed...
This addresses issues with missing icons in .desktop files

```
Desktop-Sub
Desktop-appearance
Desktop-settings
Desktop-windows
Desktop-sleep
Desktop-applet

System-Sub
System-process
System-memory
System-print
System-storage
System-security

Setup-Sub
Setup-puppy
Setup-wizard
Setup-installation

Utility-Sub
Utility-development
Utility-package
Utility-shell
Utility-help

Filesystem-Sub
Filesystem-filemanager
Filesystem-mount
Filesystem-find
Filesystem-storage

Graphic-Sub
Graphic-paint
Graphic-draw
Graphic-flow
Graphic-viewer
Graphic-camera
Graphic-scanner
Graphic-print
Graphic-utility

Document-Sub
Document-layout
Document-catalog
Document-edit
Document-viewer
Document-utility

Business-Sub
Business-spreadsheet
Business-planner
Business-finance
Business-calc

Personal-Sub
Personal-database
Personal-date
Personal-organizer
Personal-security
Personal-timing
Personal-education

Network-Sub
Network-firewall
Network-phone
Network-connect
Network-transfer
Network-utility

Internet-Sub
Internet-browser
Internet-chat
Internet-mailnews
Internet-transfer
Internet-login
Internet-block
Internet-utility

Multimedia-Sub
Multimedia-mediaplayer
Multimedia-audiovideo
Multimedia-sound
Multimedia-video
Multimedia-optical
Multimedia-utility

Fun-Sub
Fun-adventure
Fun-boardgame
Fun-cardgame
Fun-puzzle
Fun-shooter
Fun-arcade
```

Most can be symlinks to existing icons in /usr/share/pixmaps/puppy/

**Comment by wdlkmpx** [comment]
I remember editing these files:
https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-code/rootfs-skeleton/usr/share/desktop-directories

with a valid `Icon=fullpath` .. the menu would use those icons and the icon themes no longer worked, had to revert due to pressure. I was under pressure pushing down on me.

Apparently, the .desktop files in /usr/share/desktop-directories must
- specify a generic icon name that is available in the gtk icon themes, including hicolor probably.. That's when I realized that by not using proper (lighweight) full gtk icon themes and icon names in the apps, everything is just more difficult to handle

Of course this is only about the category icons in the xdg menu ...

**Comment by 01micko** [comment]
Yeah I see your point but it is, in the context of 2createpackages, not the fix. Perhaps that can be revisited some day since we do have a light weight theme now (may need a few more icons/links) and the mini xpms are long gone.

I was thinking, to be more WM agnostic, that the new links I am going to make should be linked up a level to `/usr/share/pixmaps`. I'm fairly certain that all WMs look there for icons.  I think I'll change the 2 I've done and do that with the rest. If there is no appropriate icon I'll make one in `/usr/share/pixmaps/puppy/` and relative link up a level.

**Comment by wdlkmpx** [comment]
I added symlinks for all Fun-xxxx categories
https://github.com/puppylinux-woof-CE/woof-CE/commit/bf66f1dd8b0a37cd06ee36526096413a5f63ff0c

Also opened PRs
https://github.com/puppylinux-woof-CE/puppy_flat_theme/pull/2
https://github.com/puppylinux-woof-CE/puppy_icon_theme/pull/7
https://github.com/puppylinux-woof-CE/Pmaterial/pull/2

This will take some time.

**Comment by 01micko** [comment]
Leave it, I'm commiting shortly - saw your commit, doesn't break mine

**Comment by 01micko** [comment]
@wdlkmpx if you want to fix up the icon themes in the other repos, go for it, I'll wait.

Then they'll have to be updated in `rootfs-packages`.. 

OR, we can delete PMaterial and puppy flat leaving just Puppy Standard which can migrate from `rootfs-packages` to `rootfs-skeleton` once all commits are done and files updated. 

Pmaterial and puppy flat can then go to no-arch (or keep them in rootfs-packages, whatever).

**Comment by wdlkmpx** [comment]
I have a better idea. I like packages that start with p

How about pIcon_theme, that will contain 3 or more icon themes:
- pStandard
- pFlat
- pMaterial

20 jwm themes (6kb 20)= 1 jwm_themes (120k)

I like the idea of agglutinating themes and apps, that way stuff is
easier to manage. But the package will keep getting bigger... that's
not a problem, edits may happen every once in a while or never.

**Comment by 01micko** [comment]
Sure, why not.

I'm sitting on a new JWM theme called 'beach' (has a gtk theme too)

![beach](https://user-images.githubusercontent.com/1019119/65824389-639c8d80-e2ab-11e9-8d21-b269f193c090.jpg)

**Comment by 01micko** [comment]
BTW, I think the -sub icons aren't needed, just the main name. I couldn't find `|Desktop;sub|` etc in the package databases, but `|Desktop|` is there in some.
