### ISSUE TITLE
About puppy gtkdialog design using <notebook>

### ISSUE THREAD

**Issue by rizalmart** [puppylinux-woof-CE/woof-CE#1561]
For puppy core apps that using <notebook> on gtkdialog. The gui appearance will look much better if we use margin="8" attribute on every tab part

For example:

`<notebook labels="Tab 1|Tab 2|Tab 3">
 <vbox margin="8">
   [Tab 1]
 </vbox>
 <vbox margin="8">
   [Tab 2]
 </vbox>
 <vbox margin="8">
  [Tab 3]
 </vbox>
</notebook>`

**Comment by wdlkmpx** [comment]
I guess so.. pull requests, patches or files are accepted..

**Comment by rizalmart** [comment]
All pull requests regarding gui improvements are created

**Comment by wdlkmpx** [comment]
It all looks mostly good, but there are changes I do not agree with. I use lines as spaces in some dialogs and msg boxes, to make them more visually appealing.
https://github.com/puppylinux-woof-CE/woof-CE/pull/1575/files#diff-4d582a0bfbdcc98a2e35e5fe8d2895a4L288

**Comment by rizalmart** [comment]
Most of my pull request was just putting resizable attributes on `<window>` for those puppy core apps which was not intended to maximize. Also adding margin attributes for tabs in `<notebook>` for better visual appearance. These two most common pull requests are safe to merge on woof-ce

I tested every puppy core apps upon modifications before submitting it here
