### ISSUE TITLE
pm13tray uses too much RAM

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1603]
.. so I wrote one in `C` .. very simple, compiles ~10k stripped on armhf

```C
#include <stdlib.h>
#include <gtk/gtk.h>

GtkStatusIcon *tray_icon;
GdkPixbuf *pixbuf;

/* XPM */
static char *floppy_xpm[] = {
"26 26 62 1",
" 	c None",
"A	c #2B2B2B",
"B	c #424242",
"C	c #454545",
"D	c #434B43",
"E	c #404040",
"F	c #202020",
"G	c #787878",
"H	c #6C6C6C",
"I	c #389F40",
"J	c #33A33C",
"K	c #767676",
"L	c #3D3D3D",
"M	c #434343",
"N	c #676767",
"O	c #383838",
"P	c #4A4A4A",
"Q	c #309738",
"R	c #2C9C35",
"S	c #555555",
"T	c #6B6B6B",
"U	c #686868",
"V	c #414141",
"W	c #4E4E4E",
"X	c #AAB9AB",
"Y	c #B2C0B3",
"Z	c #E2E2E2",
"a	c #EEEEEE",
"b	c #BFBFBF",
"c	c #BDBDBD",
"d	c #939393",
"e	c #989898",
"f	c #565656",
"g	c #595959",
"h	c #585858",
"i	c #A3A3A3",
"j	c #ABABAB",
"k	c #858585",
"l	c #7B7B7B",
"m	c #9F9F9F",
"n	c #9D9D9D",
"o	c #575757",
"p	c #5A5A5A",
"q	c #BBBBBB",
"r	c #969696",
"s	c #515151",
"t	c #535353",
"u	c #636363",
"v	c #909090",
"w	c #525252",
"x	c #656565",
"y	c #646464",
"z	c #393939",
"0	c #626262",
"1	c #5E5E5E",
"2	c #ADADAD",
"3	c #848484",
"4	c #000000",
"5	c #3A3A3A",
"6	c #6D6D6D",
"7	c #4D4D4D",
"8	c #2D2D2D",
"                          ",
"  BCCDDDDDDDDDDDDDDDDCCE  ",
" BGHHIJJJJJJJJJJJJJJIHHKL ",
" MNOPQRRRRRRRRRRRRRRQSSTM ",
" MUVWXYYYYYYYYYYYYYYXSSTM ",
" MTSSZaaaaaaaaaaaaaaZSSTM ",
" MTSSZbccccccccccccbZSSTM ",
" MTSSZaaaaaaaaaaaaaaZSSTM ",
" MTSSZaaaaaaaaaaaaaaZSSTM ",
" MTSSZbccccccccccccbZSSTM ",
" MTSSZaaaaaaaaaaaaaaZSSTM ",
" MTSSZaaaaaaaaaaaaaaZSSTM ",
" MTSSZbccccccccccccbZSSTM ",
" MTSSZaaaaaaaaaaaaaaZSSTM ",
" MTSSdeeeeeeeeeeeeeedSSTM ",
" MTSSSSfggggggggggSSSSSTM ",
" MTSSShijklmjjjjjjnoSSSTM ",
" MTSSSpqrstuqqqqqqqpSSSTM ",
" MTSSSpqvwSxqqqqqqqpSSSTM ",
" MTSSSpqvwSxqqqqqqqpSSSTM ",
" MTSSSpqvwSxqqqqqqqpSSSTM ",
" MHSSSpqvwSyqqqqqqqpSSSTM ",
" z01SSpq2Nx3qqqqqqqpSSSTM ",
"  5u6HuqqqqqqqqqqqquHHHGV ",
"   zCC7pppppppppppp7CCCV  ",
"                          "
};

void tray_icon_on_click(GtkStatusIcon *status_icon, gpointer user_data) {
		system("eventmanager pm13 & ");
}


/* -create icon and 'click' properties */
static GtkStatusIcon *create_tray_icon() {

	tray_icon = gtk_status_icon_new();

	g_signal_connect(G_OBJECT(tray_icon), "activate", G_CALLBACK(tray_icon_on_click), NULL);
	pixbuf = gdk_pixbuf_new_from_xpm_data ((const char **)floppy_xpm);
	//gtk_status_icon_set_from_file(tray_icon,"/root/raspi-icons/floppy.xpm" );
	gtk_status_icon_set_from_pixbuf (tray_icon, pixbuf);
	gtk_status_icon_set_tooltip(tray_icon, "Pupmode 13 - press for settings");
	
	gtk_status_icon_set_visible(tray_icon, TRUE);

	return tray_icon;
}

int main(int argc, char **argv) {

	gtk_init(&argc, &argv);
		
	tray_icon = create_tray_icon();
                        
	gtk_main();

	return 0;
}
```

Below is a screeny .. new one on left
![tray](https://user-images.githubusercontent.com/1019119/66201604-11160380-e6e7-11e9-9b1d-292a835a7c0f.png)

and here is mem usage in `top` (on raspi 3b+)
![top](https://user-images.githubusercontent.com/1019119/66201768-68b46f00-e6e7-11e9-8d26-c9fe7bfcb157.png)

That's significant in a low RAM situation.

And here's the makefile

```make
CC = gcc
PROG = pm13tray
GTKFLAGS = gtk+-2.0
CFLAGS = -Wall -pedantic -std=gnu99 -g -I/usr/include `pkg-config --libs --cflags $(GTKFLAGS)`
LDFLAGS = -Wall -g `pkg-config --libs $(GTKFLAGS)`

all : $(PROG)

$(PROG) : $(PROG).o
	$(CC) -o $@ $(LDFLAGS) $^
	
$(PROG).o : $(PROG).c
	$(CC) -o $@ $(CFLAGS) -c $^
	
clean:
	-rm -f *.o $(PROG)
```

It uses much less RAM because we aren't polling for an icon update. Yad's implementation would have to do this for it to be useful. Plus (read the code) we have a nicer tooltip which can easily be gettext'd with a few more lines.

**Comment by wdlkmpx** [comment]
Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/248e72fd129caa22bcc0979d8f197f1c1c98c646 adds support for the compiled binary and changes the yad tray icon tooltip. Although I guess I'll just remove the tooltip with an empty string.

The compiled binary overrides yad, both work fine. `pm13tray` can be placed anywhere in path.. the yad notification is a symlink to yad (/tmp/pm13tray).

**Comment by 01micko** [comment]
Cool. I'll package the compiled bin and add to the repo, specs etc.

**Comment by wdlkmpx** [comment]
https://github.com/puppylinux-woof-CE/petbuilds/tree/generic/basic/pkgs/pngoverlay

That also contains picscale, pm13tray might  end end there too. There are many small pup-related C apps, all of them should be in single package.

I have to write a replacement for image-changer, the C picscale is close, about 70% of image-changer, but without the "transformation" setting.

A new woofce repo and package only for pup-related C/C++ apps

Think of the linux firmware, they add firmware and release bigger and bigger tarballs, every 2 months they upload a bigger tarball. Their bandwidth must be good. In this case it's just tiny  C apps compiled through a single makefile.

Otherwise keeping track of all these small files ensures brain damage.

**Comment by wdlkmpx** [comment]
I renamed the pngoverlay petbuild to `aaa_pup_c`
https://github.com/puppylinux-woof-CE/petbuilds/tree/generic/basic/pkgs/aaa_pup_c

Following slackware's and opensuse's naming conventions
https://software.opensuse.org/package/aaa_base
https://packages.slackware.com/?r=slackware-14.2&p=aaa_elflibs-14.2-i586-23.txz

Current apps in v0.7
- gtksplash
- mkwallpaper
- picscale
- pm13tray
- pmusic_trayapp
- pngoverlay-cairo (pngoverlay is a symlink to this)
- pngoverlay-gtk2 

aaa_pup_c-0.7-i686_stretch.pet = 15kb

**Comment by 01micko** [comment]
I'll commit my binary to `woof-arch/arm` then. If you wanna do the same with x86 then that's all that's needed coz 64 should have plenty of RAM available, the yad version would barely use 0.1% in the majority of cases.

**Comment by 01micko** [comment]
ok, so I should build that and we delete the bins from woof?

**Comment by wdlkmpx** [comment]
Yes, maybe in 2 weeks, I'll add more apps. I think freememappplet tray qualifies

Then you might want to write a blog post about it or something. The
problem here is what is outside the woofce repo, we have to inform
people, although I really don't want to do that.

People will be forced to use aaa_pup_c sooner or later, as I'm
deleting petbuilds and merging the C apps into aaa_pup_c

**Comment by wdlkmpx** [comment]
There are some pup-related apps that were deleted or no longer really needed:
- gfontsel - yad
- minixcal or igucal? - yad
- sfontview - pfontview provides exactly the same without a binary
- gcolor2 (not deleted, but there is good yad replacement)

gfontsel/minixcal can be restored, but I guess yad even provides a gtk3 version of those apps.

Several cli apps were deleted and replaced with busybox and scripts, I performed a massive cleanup but it's still a mess. But aaa_pup_c can bring balance to the PKGS_SPECS

**Comment by wdlkmpx** [comment]
As you can see in the Makefile, the `all` target specifies all the included apps...
https://github.com/puppylinux-woof-CE/petbuilds/blob/generic/basic/pkgs/aaa_pup_c/aaa_pup_c/Makefile#L11

What other apps should be included? setvol perhaps? powerapplet tray? 

Something that is likely to produce a generic buid, that's why I haven't included xcur2png yet, there should be a way to use gtk instead (pngoverlay-gtk2.c, picscale) to produce the output file

**Comment by 01micko** [comment]
Here is my tray on pi zero

![Screenshot](https://user-images.githubusercontent.com/1019119/66262044-26407e80-e81c-11e9-902b-966a7e89c4d1.jpg)


Icon may need more padding.

**Comment by 01micko** [comment]
I suppose setvol and powerapplet can go in. 

Anyway, I'll close this issue, it's solved, I can always tweak the icon later.
