### ISSUE TITLE
Improving package dependency resolution for PPM

### ISSUE THREAD

**Issue by rizalmart** [puppylinux-woof-CE/woof-CE#1604]
This an odd idea I guess. But we need to improve further the package dependency resolution of ppm especially in step by step mode.

**Comment by wdlkmpx** [comment]
There are issues that must be resolved first.

- restore the dependency dialog
- fix the step by step method
- delete dead code

After that things can happen.

And did I mention it's always good to use a recent ISO? 

I noticed that the pull request to  improve filemnt contained broken box_yesno code that probably works in old versions or something. It's easy to merge stuff but it's hard to test, it's time consuming. I know some extensive testing is probably needed before this kind of stuff is implemented. That probably requires a forum, a new forum. I won't merge stuff that I don't properly verify, and apparently nobody else in the git repo is able to review stuff.

The ppm needs a rewrite, I guess we all have some code that replaces it.

It's easy to break the system, specially if installing alien packages or core packages and files on top of the current ones.

Is there a solution for that? I don't think so, but removing or hiding the option to perform a full install (only for power users)  might help. It's easy to recover the system by deleting the pupsave.. I noticed that it's easy to delete a savefile within the running system, but to delete a savefolder you need to boot from another puppy.

**Comment by wdlkmpx** [comment]
I get stressed just by reading the ppm, if I'm to fix stuff the whole thing will look different after that

**Comment by wdlkmpx** [comment]
There is also stuff that should change... i.e.: keep debian/ubuntu-updates as a separate pkg db.

Those should be specified in DISTRO_COMPAT_REPOS and $PKG_DOCS_DISTRO_COMPAT should define the pkgs dbs and the priority.

But doing this stuff... is it even worth it? It will cause breakage, outside woofce of course, that's the only problem, otherwise many things can be done if we forget that there's stuff out there.
