### ISSUE TITLE
Integrate Pkg

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1623]
So I was testing a build with a broken X and needed to install a pkg to start debugging but that's not possible with the ppm.

Pkg includes and replaces many things including the .petbuilds, it has recipes to build obsoleted apps that no longer are needed in woofce I think.. a replacement for sfs_load.. this can't be replaced.

There is legacy code that should be deleted, and stuff simplified a bit probably. In other words, it should be included in a new branch until it's ready or something.

**Comment by wdlkmpx** [comment]
Pkg was not compatible with current stuff in the testing branch

This Pkg is somewhat fixed to work with current woofce
https://github.com/puppylinux-woof-CE/Pkg/commits

But requires a patched 0setup:
https://github.com/puppylinux-woof-CE/woof-CE/commit/f99cf474e18c0881dc5b6512e271716d6333cbd0

In puppy/woof/fyhk everything is tightly integrated and the design is terrible, it's surprisingly easy to break stuff for everyone else just by making improvements to the code. It's not that hard to understand that.

**Comment by sc0ttj** [comment]
Happy to look into these changes and merge into Pkg proper .. Or take any advice on what needs doing

I know that `buildpet` _could_ be removed.. But frankly, it's nicer (IMHO) than petbuild ... If some petbuild/woof stuff could be backported into `buildpet` and the build scripts updated (mostly changing source archive urls and version numbers), then `buildpet` would be great.

I also think the code that builds packages from source should live in the package manager .. and there fore the repo of build scripts _can_ too ... although prob better to move them to their own repo, for various reasons.

Also, the way Pkg uses `src2pkg` is very limited, that could be improved .. `src2pkg` is great..

**Comment by sc0ttj** [comment]
There is a list of issues for Pkg .. 

And speeding up dep resolution is top off my personal preferences.

Pkg could handle builtins and updating packages better, that would be another one.

I also had the idea of auto-installing `-dev` or `_DEV` packages when any libs are installed while the devx is installed/mounted.

**Comment by wdlkmpx** [comment]
In puppy there's the tradition to keep backwards compatibility.

The removal of the multiarch symlinks is a major change, builders were
not able to cope with it... it was a simple change that took years to
materialize.

The patched Pkg does not include code to handle multiarch symlinks,
therefore it's not backwards compatible.

I only care about the latest git stuff, new isos must be built.
Distros in woofce:
- slacko32/64 14.0 / 14.1 / 142
- upup 32/64 tahr / xenial / bionic
- dpup 32 stretch
- dpup 32/64 buster
- raspup armhf buster

 I don't have time to deal with old versions, that's why the changes
can't be added to upstream Pkg.. so it doesn't follow the vicious
cycle. My approach is exactly the opposite.

Things are being simplified and "normalized" a bit setting the scene
for possible new changes, but it will take forever. I'm having
headaches, I'm probably trying too hard.

The good thing is that there's no need to rely on the builders,
anybody can build a puppy with one command and test what's available
even though it might a bit broken.. merge2out-gui / cd woof-out... /
./build.sh

The slackos seem to be in good shape.
