### ISSUE TITLE
x32 or ia32 in kernels of 32-bit Puppies

### ISSUE THREAD

**Issue by sc0ttj** [puppylinux-woof-CE/woof-CE#1626]
I got an error in a 32-bit Dpup Stretch, kernel `Linux foopc 4.9.101-stretch #1 SMP ... i686 GNU/Linux` .. It got me investigating..

I was trying to compile https://github.com/yue/muban

```shell
# npm install
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for cmake-binaries@1.0.5-2: wanted {"os":"win32,linux,darwin","arch":"x64,x32"} (current: {"os":"linux","arch":"ia32"})
npm ERR! notsup Valid OS:    win32,linux,darwin
npm ERR! notsup Valid Arch:  x64,x32
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: ia32

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-24T15_07_10_679Z-debug.log
```

I know nothing about kernels, so this is a vague question..

**Is it better (possible?) to build 32-bit Puppies to support x32?**

---

From https://stackoverflow.com/a/32663236:

> x32 is an ABI for amd64/x86_64 CPUs using 32-bit integers, longs and pointers. The idea is to combine the smaller memory and cache footprint from 32-bit data types with the larger register set of x86_64. (Reference: Debian X32 Port page).
> 
> x32 can provide up to about 30% reduction in memory usage and up to about 40% increase in speed. The use cases for the architecture are:
> 
>     vserver hosting (memory bound)
>     netbooks/tablets (low memory, performance)
>     scientific tasks (performance)
> 
> x32 is a somewhat recent addition. It requires kernel support (3.4 and above), distro support (see below), libc support (2.11 or above), and GCC 4.8 and above (improved address size prefix support).

**Comment by 01micko** [comment]
Debian/Ubuntu etc ship i386, amd64 (same as x86_64) plus arm, mips, and others but not _x32_. Personally, I'd leave x32 alone. Do a search for what _x32_ is and then decide if it is worth pursuing. It's not on my radar.

**Comment by sc0ttj** [comment]
If no one is interested in this, and as I was only asking (and know nothing about x32, other than some people say it uses less memory and is faster) then should we close this issue?

And do we have a tag that we use for closed, useless issues we never wanna return to? Like `wont do`?

**Comment by jamesbond3142** [comment]
My personal opinion: x32 is a solution looking for a problem.

**Comment by woodenshoe-wi** [comment]
The only thing that comes to mind would be the “Year 2038 problem” https://en.wikipedia.org/wiki/Year_2038_problem

According to the Wikipedia article the x32 ABI uses a 64-bit `time_t`.

But there are probably a lot of other 32 bit date issues to be sorted out too.  Good thing is that there are still 18 years to figure it out.  If they do as good a job as Y2K we shouldn’t notice much.  😃

**Comment by 01micko** [comment]
There you go, made a 'wont do' tag
