### ISSUE TITLE
Bug in sfs_load?

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1630]
This is something I noticed a long time ago.

I have palemoon as the adrv, it's part of the default build. But what if I want to use another version?

I created a new palemoon sfs with a later version. After loading it with sfs_load I don't see the expected results, it doesn't override the adrv.. it should be in a higher layer or something.

I rebooted and the issue is still there.

Is this a bug or the expected behavior?

```
# losetup -a
/dev/loop0: [2049]:143222 /initrd/mnt/dev_save/PLINUX/32bit/puppy_stretch_7.0.0b3.sfs
/dev/loop1: [2049]:143223 /initrd/mnt/dev_save/PLINUX/32bit/zdrv_stretch_7.0.0b3.sfs
/dev/loop2: [2049]:143220 /initrd/mnt/dev_save/PLINUX/32bit/adrv_stretch_7.0.0b3.sfs
/dev/loop3: [2049]:143221 /initrd/mnt/dev_save/PLINUX/32bit/devx_stretch_7.0.0b3.sfs
/dev/loop4: [2049]:143 /initrd/mnt/dev_save/frugalpup_15.sfs
/dev/loop5: [2049]:134 /initrd/mnt/dev_save/sfsw_ffmpeg_static-4.2.1-i686_x86_64.sfs
/dev/loop6: [2049]:263959 /initrd/mnt/dev_save/sfsw_edk2-20190718-git.sfs
/dev/loop7: [2049]:150 /initrd/mnt/dev_save/sfsw_palemoon-28.7.2-i686-x86_64-ubo.sfs

# cat /sys/fs/aufs/si_72e6341/*
/initrd/mnt/dev_save/PLINUX/32bit/stretchsave=rw
/initrd/pup_a=rr
/initrd/pup_ro2=rr
/initrd/pup_z=rr
/initrd/pup_ro3=rr
/initrd/pup_ro4=rr
/initrd/pup_ro5=rr
/initrd/pup_ro6=rr
/initrd/pup_ro7=rr
68
67
65
66
69
70
71
72
73
/initrd/mnt/tmpfs/.aufs.xino
```

**Comment by 01micko** [comment]
Well adrv goes above. sfs_load loads beneath as there is no need to load above if the sfs is constructed to conform to the current distro. That's how sfs have always worked.

Running off live cd it would be impossible to override the adrv as the cd is ro, unless perhaps using a cd in pupmode 77 (write back).

The adrv would have to be 'uninstalled' I suppose, but that may create problems in and of itself.

In a frugal to writeable media you should be able to unload the adrv then reload a new adrv. There would need to be some heavy testing to get this to work correctly in OTF mode.

**Comment by 01micko** [comment]
On second thought, the stack is built in init, so I don't think it's possible to rearrange the stack OTF, so a reboot would be needed to load any sfs above - OTF kind of implies 'appending' to the stack.

**Comment by wdlkmpx** [comment]
What does OTF mean?

I've always noticed that when I want to replace a built-in app with another version using sfs_load I don't get the expected results.

I've never used the "Porteus" distribution but I've been (partially) aware of how it works:
http://ftp.nluug.nl/os/Linux/distr/porteus/i586/Porteus-v4.0/modules/

sfs_load should have been written with the modules directory in mind.. pmodules in this case...  $HOME/$PSUBDIR/pmodules

I guess it's possible to extend sfs_load to include pmodules and the browser would be 01-browser-version.sfs.. something you can easily replace... in frugal mode.

**Comment by 01micko** [comment]
OTF = _on the fly_ as opposed queue and reboot

**Comment by gyrog** [comment]
@wdlkmpx,
If you load an sfs with sfs_load, it gets appended to the bottom of the stack, i.e it's files will only be seen by the system if they don't already exist in the stack.
To try a new adrv, you need to rename  the old one out of the way and rename the new one into place and reboot. There can still be problems, if any of the files in the old adrv have been "modified", thus copying them up into the RW layer at the top of the stack.
Just make sure that you are not running with "pfix=nocopy", renaming an sfs that is actually loaded into the stack causes problems, but if they were copied to ram, then itls the copies in tmpfs that are actually in the stack.

@01micko,
With "aufs" there is no problem with changing the layers of the stack OTF.
So theoretically, a utility could be written to remove the current adrv from the stack, umount it, mount the new one, and then insert it into the stack.
The difficulty with doing such a thing is ensuring that no files on the current adrv are in use, causing problems with removing it from the stack.
Sfs_load, does not do this, it is meant to handle "extra" sfs files, which introduce new stuff by being appended to the bottom of the stack,

**Comment by wdlkmpx** [comment]
When it comes to Live CD/multisession CD/DVD it doesn't really matter what happens. Live CD = basic testing/installer. Multisession CD/DVD = Flash/tallboy and no one else.

Apparently in porteus you only need to add squashfs files to ./modules and all of them will be loaded. I guess it's a dynamic thing, if you remove/add stuff an update should be triggered in the next boot... that's how it works in puppy... but the /pmodules directory would make it powerful without sfs_load.

What I'll do now is delete the adrv and reboot, that will trigger an update.

**Comment by wdlkmpx** [comment]
I found a bug, the update was not triggered, but now I'm using the palemoon mounted by sfs_load. It shall be fixed one day.

By reading sfs_load I came to know that some people add a rox pinboard file and the script would resort to some voodoo to fix and unfix the pinboard [in the higher layer].

I removed that code in https://github.com/puppylinux-woof-CE/woof-CE/commit/d93b3c09987d1b894ae580a28de1847e1eaaac6e#diff-6a0aff03eae82ce8c1c565506e37f3ea

I felt a little guilty thinking that maybe their pinboard file will override stuff and make things look bad, but now it's obvious that it won't cause any harm, what a relief.

What I explained in my previous comment.. I think it's the future. They got it right since day or day two or three..

**Comment by gyrog** [comment]
When mounting and adding sfs files to a stack, order matters.
So I use lists, rather than directories, to specify the sfs files to load.
Provided you are perpared to prepend a few characters to the front of sfs filenames, to provide a specific order, using a directory/diretories to specify sfs files to load, would be easy to maintain.
