### ISSUE TITLE
Puppy Linux developed for Raspberry Pi

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1632]
Wikipedia has some excellent information on RasPi (the hardware).
![Raspberry Pi 4 Model B](https://cdn.xingosoftware.com/elektor/images/fetch/dpr_1,w_300/https%3A%2F%2Fwww.elektormagazine.com%2Fassets%2Fupload%2Fimages%2F42%2F20190620210500_190324-025-94-ORIGINAL-Store-Rasberry-Pi-4-01.jpg)
It has a section which list the links to distros built to run on the Pi hardware.

Puppy Linux is **NOT** one of them even as there are no less than 4 PUPs available for the Pi hardware.

Is there any developers on PUP's GIT who have purpose-built PUPs that are willing to make your versions known on Wikipedia? I am sure some are proud enough to update directly to Wikipedia (YES you can update without asking anyone's permission). It can be done, by you, here ===> https://en.wikipedia.org/w/index.php?title=Raspberry_Pi&action=edit&section=23

This post is a mere **FYI** for any developer(s) who have built a Pi version of PUP.

**Comment by 01micko** [comment]
GC, follow the commits.. I've got this :wink:
