### ISSUE TITLE
boot issues-bionicpup64

### ISSUE THREAD

**Issue by wepntech** [puppylinux-woof-CE/woof-CE#1662]
bionicpup64 Lix
Limx 4.19.23 Ix86 64 arch
logint32931: root login on ttyl
Starting X, specs in retc1lrxorg.conf. startup apps root/.xinitrc...
Exited fron X、 Type "main [ 1" to restart X (11 nean optional).
Type "nin-default [jun " to restart Х uith the default xorg.conf
To slutdoum PC type "pover
roff", to reboot PC type "reboot")

the thing keeps giving me this on boot (it used to work fine) from a full install IDK what to do from here.
![image](https://user-images.githubusercontent.com/57373220/68503781-48278980-023e-11ea-81e3-3a663ac2bc6e.png)

**Comment by bigpup1** [comment]
This is really not something that Woof-CE is going to control.
This is a Bionicpup64 specific problem caused by something going bad about your install.
Go to the Puppy Forum Beginners section and make a topic on this problem.
http://www.murga-linux.com/puppy/
People there can help you figure out  a fix.

**Comment by 01micko** [comment]
Agree with @bigpup1 

Firstly 'full' installs are dangerous and not recommended.

Second, did you run `xorgwizard` ? (as the text suggests)

**Comment by wdlkmpx** [comment]
I'm going to hide the option to perform full installs. It will be possible to perform full installs by exporting a variable before running the puppy installer. Newbies will never perform full installs again. And the installer script has too many bugs, I fixed most of them recently, but there are more bugs to fix.

The only problem here is that updates and fixes will take years to find their way to official releases.
