### ISSUE TITLE
File(s) that get any user started in PUP use

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1668]
Yes, PUPs have a start HTML page included in each ISO. But, I think 1 of several useful things should be added for any WOOFCE generated PUP; 
* A file Cheatcodes.txt
* Or, put the Cheatcodes in the README.txt 
* Or, an entry in the README.txt that points to where Puppy Cheatcodes can be found

I think we all understand the intent of such.

**Comment by wdlkmpx** [comment]
A html file was included in the ISO's root directory, it was deleted 2 years ago I think. 

The cheatcodes file is /initrd/README.txt (running OS). I guess that readme file can be added to the iso / zip / tar file (root directory).

The start page is /usr/share/doc/index.html which contains mostly outdated info. I guess it should be deleted and the project renamed to PLInux

A recurring problem I see is that people are probably using very old stuff and have probably not seen a recent iso.

**Comment by wdlkmpx** [comment]
This is the file you're looking for:
https://raw.githubusercontent.com/puppylinux-woof-CE/woof-CE/testing/initrd-progs/0initrd/README.txt

It will be included in future builds https://github.com/puppylinux-woof-CE/woof-CE/commit/2e49a18cbddc1eedb1f0f99cc9035554df9a8382
(currently only x86* isos)

It looks ok, I'll test the change tomorrow. Today I built and deleted like 10 isos. it's so easy.

**Comment by CollaboratorGCM** [comment]
Thanks for understanding.
