### ISSUE TITLE
PPM: some apps don't work ootb

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1670]
With many `internet` apps and some others like VLC they refuse to run as root. Others like X-chat moan .. " Running IRC as root is stupid!" .

The simplest of solutions is to prepend `run-as-spot` to the `Exec=` line in the .desktop file.

eg:
```
[ $UID -eq 0 ] && sed -i 's/Exec=/Exec=run-as-spot /g' /usr/share/applications/${APP}.desktop
```

IDK if it should be automated, because we just don't know which apps refuse to run.

Perhaps a menu entry in _Setup_?

**Comment by wdlkmpx** [comment]
Packages-templates = /usr/local/petget/hacks-postinstall.sh

2 years ago I realized that the build system and the PPM should share the same packages-templates (or hacks).. packages-templates/* should be copied to /usr/share/petget/postinstall-hacks/* or something.

It's a bit hard to fix the ppm, well, it's not that hard, but I have a massive headache everytime I want to edit the code.

Pkg should replace PPM, hacks and stuff should ported to Pkg.

**Comment by 01micko** [comment]
`hacks-postinstall.sh` needs a serious update. I think it predates `run-as-spot`. Hacking a binary is unsafe - could cripple the binary. Plus more apps need to be added. I'll take a look tonight.

**Comment by sc0ttj** [comment]
> Pkg should replace PPM, hacks and stuff should ported to Pkg.

There is a PR for Pkg here that I mean to merge, which does some post install stuff:

 https://gitlab.com/sc0ttj/Pkg/merge_requests/2/diffs?commit_id=7e80d094aa6167688a934c9e09e1eadaf94a4c76

But I was planning to create a new `post_install` function for Pkg that runs the above code (and similar stuff), but also parses a dir containing post install scripts for various packages/programs..

**Comment by 01micko** [comment]
I agree that `pkg` should replace `ppm` 100%

But not yet. Let's get dpup and raspup out the door before Xmas then create a branch for them to keep 'em patched up. I'll patch up the ppm for now and then we should _**delete**_ the whole mess.

**Comment by wdlkmpx** [comment]
Pkg is already patched enough to work properly [don't trust me] in new builds. At least .pet, .deb, and .txz install fine.. that's all we need to know. All of them use a temporary directory, the most sensitive app is busybox, a temp dir requires ram or something but it fixes issues... i.e: by installing certain apps it's easy to wipe busybox and replace it with something else, symlinks remain intact but busybox becomes something else. It happened to me several times.

Pkg also has the postinstall script in a function. So both apps need the same patches, and some recent changes should be ported to Pkg.

PPM will not be removed, it will take time for people to get used to Pkg, so both should coexist for a while.

I find Pkg a bit confusing but they say it's way less buggy than the ppm.. it's time to include Pkg by default. Pkg = WOOF_VERSION=10

Pet pkg? I don't think so... it's not compatible with older releases.
rootfs-package: probably
rootfs-skeleton: this could be the place

I caught the flu, so time is running out, stuff should be integrated as fast as possible.

Hmm.. it will be a rootfs-package, development will continue in its own repo and the rootfs-package will be updated when needed.. just by replacing the whole dir.

**Comment by sc0ttj** [comment]
I'm personally in no great rush to get Pkg into Puppy before the next official releases... maybe as an additional tool to play with, but that's it.. 

I think we likely get the 3 (arm, 23bit, 64bit) buster pups out before Pkg is considered "stable" ..

**Comment by sc0ttj** [comment]
> Pet pkg? I don't think so... it's not compatible with older releases.

It should be very easy to keep Pkg compatible with older pups... BTW.. without lots of legacy code in Pkg itself.. 

We simple need a packaged called `pkg-compat-0.1.pet`, designed to be installed on older pups, which contains certain files.:

- any additional funcs not in older Pups or main Pkg a scripts in $PATH
- any additional scripts not in older pups or main Pkg in $PATH
- append more repos to `sources-all` file using `pinstall.sh`
- append MULTI_ARCH_SYMLINKS=true to some rc file (bashrc, pkgrc, etc)

And we revert/fix one or two changes you made already:

- dont remove multi arch symlink it stuff, it's ONE small block of code:
  - it doesn't need to be maintained, does't affect other bits of code
  - so put it back in, then in Pkg..
  - if MULTI_ARCH_SYMLINKS is true, run code block, else don't

..basically, having a `pkg-compat` package will allow users to install package containing any missing funcs, and a great big `sources-all` file, with loads of pups in there, they can delete what they don't want..

**Comment by dimkr** [comment]
#2846 will fix this.
