### ISSUE TITLE
Replace 2barks.au with a more pleasant sound

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1674]
Most people don't enjoy [or tolerate] distressing sounds, by keeping that file many potential users will look for other alternatives.

So we have a problem here. It's easy to solve.

But do we really want to do something this good? Do we really care about the majority of people?

**Comment by peabee** [comment]
Maybe only a small minority of people find it "distressing"....
and given that it only sounds once on first boot then probably a majority of that small minority don't care.....
I don't think there's any evidence on the forum of any "distress" or of anybody abandoning Puppy for this reason....

**Comment by wdlkmpx** [comment]
Isn't obvious that the majority of normal people don't enjoy when an
adult dog barks?, it's an aggressive sound, I've heard it many times
from dogs that tried to kill me with their barks.. perhaps they were
insulting in their language.

Do we really care about normalcy?

**Comment by rizalmart** [comment]
wdlkmpx I have suggestion just search a sound clip on youtube audio library or use kde-4 login sound. Or a single soft woof sound

**Comment by 01micko** [comment]
I could record my chihuahua when he's trying to talk, sounds kinda cute.

**Comment by sc0ttj** [comment]
I feel like a nice, soft "ta da!" type sound is good.. Quick, fun, plesant - evokes some kinda idea of "it's finished, and it's good"

**Comment by mavrothal** [comment]
Any sound will have proponents and opponent. There is little reason to change the  "trademark" sound of puppy first run because someone might be cynophobic. Besides, if (s)he is a cynophobic [masochist](https://github.com/puppylinux-woof-CE/woof-CE/issues/1677#issuecomment-559100057), may even enjoy it 😆

**Comment by wdlkmpx** [comment]
When booting from usb flash I often boot in pupmode 5. That sound can be
heard miles away. People get alerted.

It's embarrassing, just because we have to keep a stupid trademark sound.

**Comment by wdlkmpx** [comment]
I knew

**Comment by wdlkmpx** [comment]
What happens if I change the sound again.. an identity crisis, LGTB, minority.  Shame on me and a beach will revert it

**Comment by CollaboratorGCM** [comment]
I have been involved in placing office systems and helping people for 5 decades. Most people I know, welcome any sound that the system is ready for operations. Whether that is a "ding" or a ringing or ... (just about any sound). Just about every new IoT product, today, has a type of announcement.

Peebee, TaZoC, ETP and others over the years have been supportive of this kind of announcement in Puppyland. As many of you know, phones and tablets have been doing this for years, too. So, I think almost everyone dont/will find the sound an offense as is suggested.

In my showing to seniors, unfamiliar with Linux/Puppy, I have not observed a negative response when they arrive at desktop. Everyone "seem" happy for the "Puppy Bark".

I, personally see an advantages to these types of noises for announcement of system's availability.

**Maybe, this can support a middle ground:** How about within one of the initial setup screens, it "alerts" the user to an option to turn off the "initial system availability announcement" OR better maybe a suggestion at that time to change it to something a user might choose.

If the suggestion approach is used, then an appeal, to users who do use their own sound file, to upload their "choice sound" to a common place such that others may, too, choose to use any sound found at that location for their personal system use. 
This would give a common place for anyone who wants to change to see some files that they might take advantage of; kinda "open source" theme for these sounds in practice.

Mine would be the voice from the movie 2001...OR use the "horn blaring" that @ETP uses when the internet is not available, are examples of others. But, the Puppy-bark tells me that Puppy is ready for a treat. Or maybe a Halle Berry voice telling me she's ready (ha).

This post neither agrees or disagrees. Its a mere statement of factual observations. It intents to offers some thoughts with the historical observations I've seen.

**Comment by wdlkmpx** [comment]
I showed puppy to some people, everybody hated it, no exceptions. I
used an official puppy, everybody hated it.

I deleted the annoying sound, whoever reverts it will mark the commit
where my definitive fork starts (the previous commit).
