### ISSUE TITLE
Add some kernel compile options

### ISSUE THREAD

**Issue by rizalmart** [puppylinux-woof-CE/woof-CE#1685]
Is it possible to add these options when compiling a kernel on woof especially creating zdrv sfs file.
1. Include exfat driver patch for linux kernel 5.4 below (Source patch: https://github.com/arter97/exfat-linux)
2. Include ndiswrapper driver and its utils

**Comment by 01micko** [comment]
Why and why?

`exfat` taints the kernel as does ndiswrapper. I'm almost certain ndiswrapper cannot be built 'in tree' anyway. I can't think of a reason why one would want to do that. Any hardware that old (XP era) is either supported in the kernel or probably suffers from 'old age'.

As for exfat, well I've never used it and never intend to. I cringe to use vfat and ntfs. If you need it, write a routine to include it in `kernel-kit`. If the patch is sound it will be included.
