### ISSUE TITLE
HardInfo 0.5.2pre

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1686]
**This is of MINOR importance**, yet, as progress continues toward PUP releases: The kernel modules listing has all but about 5 of the modules with a description.

Seem to remember @Kirk (or someone in PUppyland) tailoring Hardinfo for Puppy needs. I am not sure how modules get their descriptions into Hardinfo, but if that is a local Puppy change, those few items would benefit in review. 

Specifically, the KVM modules description and couple others.
![HardInfo 0 5 2pre](https://user-images.githubusercontent.com/15698050/69887702-3e7dc880-12b6-11ea-92bc-f633ae7c6658.png)

**Comment by 01micko** [comment]
This is beyond the scope of woof.
