### ISSUE TITLE
wireless credentials could be passed on the kernel commandline

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1692]
Fatdog can do this however they use the huge inirtrd with the main sfs builtin. This need not be the case as it can be passed down to the main system from the initramfs.

Why would we want o do this?

So we can run headless of course and perhaps only wireless infrastructure is available. 

Case in point would be the raspberry pi zero, which has only 1 USB port available (could use a wireless dongle), and the zero w which has wireless and bluetooth also, but I'm sure there are other situations where this would be a handy feature.

Thoughts?

**Comment by 01micko** [comment]
### proposal

pass something like `pwireless=myessid:mypassword`

then further down `init`

```sh
if [ "$PWIRELESS" ];then
 echo "$PWIRELESS" | grep -qE '[a-zA-Z0-9]*:*' && SSID=${PWIRELESS%:*} PSWD=${PWIRELESS#*:} # check for valid entry
 echo "$SSID" > /tmp/wireless
 echo "$PSWD" >> /tmp/wireless
fi
```

then after switch root, somewhere in `rc.sysinit`, `bbwireless.sh` (if installed) can be called with $SSID and $PSWD as the arguments, grokking those values out of `/initrd/tmp/wireless`. Or a separate routine could easily be written to allow connection passing the ssid and password.

**Comment by jamesbond3142** [comment]
In Fatdog we process this in init itself, in initrd. We don't need the basesfs. All the necessary tools (basically ifconfig, iwconfig and wpa_supplicant) were statically compiled and included in initrd. All we need is the kernel-modules.sfs (=zdrv.sfs) which is also included in initrd. For this to work, we need the wireless kernel modules loaded too, but that's not a problem: we have a script that would load all the necessary kernel modules too (doing what udev would have done in the basesfs).

This worked in FatdogArm too - I had the static binaries in its initrd too. Feel free to adapt any of the code for Puppy 😄

**Comment by jamesbond3142** [comment]
But if you do it the Fatdog way, the rest of the network managers must be made aware of this fact so that they don't attempt to connect again (and dropping the connection). Doing it in the basesfs (in rc.sysinit) is probably better in the case of Puppy because of the multitude of network managers that it supports.

**Comment by 01micko** [comment]
Haha! Works great!

I'm gonna commit this shortly but here's what I did..


1. edit `init` by adding `pwireless` boot param
2. edit `/etc/rc.d/rc.sysinit` _before_ services are run - depends `bbwireless.sh`
```shell
# wireless passed from init
if [ -e /initrd/tmp/wireless.conf ] ; then
	if type bbwireless.sh >/dev/null 2>&1 ; then
		if [ ! -e /etc/init.d/01bbwireless.sh ] ; then # only do it once
			. /initrd/tmp/wireless.conf
			bbwireless.sh $SSID $PSWD >/dev/null 2>&1 # creates wpa_supplicant.conf and friends
			echo -e "y\ny" | bbwireless.sh -s >/dev/null 2>&1 # should start network and make bbwireless default network tool
		fi
	fi
fi

```
3. built **image** (zipped) with `3builddistro`
4. unzipped image _directly_ to micro sd (no `dd` necessary)
5. reboot into windows - don't worry it isn't connected to my network :joy_cat: 
6. plug in the micro sd - 3 partitions recognised but windows wants to reformat 2 of them (card is formatted vfat|swap|ext4), shown to me as `F:`, `G:` and `H:`, of course only F works (vfat).
7. openned 'F' in 'explorer' (file manager)
8. created a **text** file called `cmdline` - __no extenstion__. Windows is very intuitive you know, adds `.txt` all by itself! `</sarcasm>`
9. right clicked `cmdline` emty file and chose "Open with Notepad"
10. in notepad I typed `pwireless=my_wireless_network:my_wireless_password` - look away NOW if I need to explain that!
11. saved the file and safely rejected the drive. Turned off windows. (phew!)
12. plugged the card into raspi 4, booted and was connected .. _voila!_

Typing in midori now.

![Screenshot](https://user-images.githubusercontent.com/1019119/70433175-f0688200-1a78-11ea-8208-33a447bfc305.png)
