### ISSUE TITLE
can't create save file when using ssh (headless)

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1716]
I've solved the issue of booting headless and connecting via wifi in e8647f4 in PUPMODE=5 so I logged in to a pi over ssh, using ` mpscan -t 6 -p 22 10.1.1.1 - 10.1.1.254` to find the IP.

However I've tried a few methods to save session; 
- log in with X forwarding
- without X forwarding
- killing X
- `nohup wmreboot` (in X)
- `nohup reboot` (no X)
- a few other ways

I didn't try `shutdown-config` directly. Maybe it will work?

Wondering if @gyrog or @woodenshoe-wi have any ideas?

This is not a raspberry pi specific problem.

**Comment by s243a** [comment]
Isn't there some flag that is set that triggers snapmergepuppy? I think said flag is created when you press the save button.

**Comment by 01micko** [comment]
@s243a you misunderstand, I can't create the save file from pupmode 5. Perhaps I should change the title.

**Comment by gyrog** [comment]
shutdownconfig is interactive, but it is supposed to have a non-X mode, so maybe it will work with ssh.
The alternative would be to write what is needed diretly to /tmp/shutdownconfig_results.

**Comment by 01micko** [comment]
Thanks @gyrog 

I'm using X forwarding so running shutdownconfig directly _does_ work - with bugs.

1. There is constant loop of a 'broken pipe', varies in frequency but doesn't seem to affect the result.

2. No matter what reboot routine I try to use, the only one that works is `nohup busybox reboot`. The touble with that though is that the ssh VT is left hanging, a simple close of the window seems sufficient.

3. On the pi though (this is a pi specific anomaly) it reboots to pupmode 5. Luckily, I have a gtkdialog GUI to set the default boot option and set it to the raspupave. I can ssh in and run that GUI. Another reboot and we land in pupmode 13, however stuff isn't saved. I need to run `save2flash` then kill stuff and run `nohup busybox reboot`

It would be nice to fix all this but I can live without as long as I carefully document my steps. It probably would be better booting `pfix=nox` and not using X forwarding. I'll try that on the weekend.

**Comment by 01micko** [comment]
`shutdownconfig` actually works with X forwarding. A save folder is created where I want it.

The problem seems to be rebooting and shutting down, even prepending with `nohup `.

With out X forwarding may well be the go, but we don't have CLI utils for some things, such as syncing to a time server, need to fix that.

**Comment by s243a** [comment]
The following issue sounds related to me:
"On-the-fly save session on first boot #951"
https://github.com/puppylinux-woof-CE/woof-CE/issues/951 

found by googling "[Pupmode 5](https://www.google.com/search?ei=DfHwXeLTJuTb9AOX4aCIAw&q=pupmode+5&oq=pupmode+5&gs_l=psy-ab.3..0i30j0i8i13i30l4.5196.5196..5335...0.2..0.81.81.1......0....1..gws-wiz.......0i71.A54AKvAuP-0&ved=0ahUKEwiijrnR263mAhXkLX0KHZcwCDEQ4dUDCAs&uact=5)"

**Comment by woodenshoe-wi** [comment]
I don’t know if this will help with the creation of a save file, but this is how I handle remotely rebooting/shutting down a PC.  (I’ve always used a monitor/TV with my pis.)


remote-helper
```
#!/bin/sh

while [ "`ps -f -C sshd | grep 'sshd:'`" != "" ]
do
 sleep 5s
done

exec "$@"
```

remote-poweroff
```
#!/bin/sh

nohup remote-helper wmpoweroff > /dev/null 2> /dev/null < /dev/null &
```

remote-reboot
```
#!/bin/sh

nohup remote-helper wmreboot > /dev/null 2> /dev/null < /dev/null &
```

I put them in /root/my-applications/bin but anywhere in PATH should work.

**Comment by 01micko** [comment]
Thanks @woodenshoe-wi , I'll try that.

**Comment by CollaboratorGCM** [comment]
@Mike, et. al.

Hasn't anyone ever heard of *XRDP?* It does NOT require ANY software
installation on PUP or on Windows or Macs to gain a Multimedia desktop
session on a PC where it is actively running. And this open-source uses an
encrypted protocol.
It has a relatively small footprint and extends services beyond just
headless PCs because of its multimedia built-in component. In other words,
developers and users alike benefit. It addresses security concerns while
providing desktop services beyond that of SSH without the usual headaches
associated with SSH use.

Please evaluate for all PUP distributions.

**Comment by 01micko** [comment]
@woodenshoe-wi 

Unfortunately I'm using `dropbear` lightweight ssh daemon so substituting 'dropbear' in your script fails.

However, I can establish if there is an ssh connection with netstat so I modified `remote-helper` like so:

```shell
#/bin/sh 

while netstat | grep 'ssh' | grep -qi 'ESTABLISHED'
do
  sleep 5
  exec "$@"
done
```

That performs a clean shutdown or reboot whether X is running on the remote or not, whether I request X forwarding (`ssh -Y root@$IP_ADDRESS`) or not.

Now to test if it works in PUPMODE=5 and makes a save file. If not I can work around that I think, so we can run a remote puppy without ever plugging in a monitor.
