### ISSUE TITLE
update to usb-modeswitch-data-20191128?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1724]
http://distro.ibiblio.org/puppylinux/pet_packages-noarch/usb-modeswitch-data-20170806-noarch_noarch.pet

needs updating? 487 items currently, 513 in usb-modeswitch-data-20191128

Is it just a case of copying the /usr/share/usb_modeswitch from Slackware into the existing pet and making a new pet?

**Comment by 01micko** [comment]
Just make a pet from source.

petbuilds > generic branch, update the version number in the petbuild script.

**Comment by peabee** [comment]
Done - usb-modeswitch-data-20191128
