### ISSUE TITLE
init agnostic puppy

### ISSUE THREAD

**Issue by rizalmart** [puppylinux-woof-CE/woof-CE#1727]
This suggestion might triggered a debate yet I want to share some ideas and concepts might help puppy.

The idea here was upon building a puppy. Puppy can able to boot and shutdown regardless of what init systems is used whether sysvinit, runit, upstart, systemd, openrc, etc.

We already knew that the basic linux boot was mount the rootfs and execute init program.
Also in puppy on frugal mode. It builds up a virtual rootfs with the help initrd and execute the init.

Sysvinit has very straightforward so there is no problem for that. But in order to support the other init system. Puppy will just prepare a virtual rootfs then call the init system. All it have to do was create configuration files for each init system and some modifications in /sbin/init script.

**Comment by s243a** [comment]
The first thing that would need to be done would be do move busybox specific init code from rootfs-skeleton to a separate package in rootfs-packages. It sounds like a lot of work and it will mean some relearning about how puppy init scripts work for those who want to understand the internals of how puppy works. 

It's not a horrible idea but I see much simpler merge requests being rejected. I suggest creating a new branch for this and if anyone wants to help they can merge code into that branch. Really though it's up to the woof-CE care-takers whether or not such code gets merged into woof-CE official. 

Another option might simply be an optional package in rootfs-packages (that the woof-CE builder can select at build time), that simply overwrites the default init code.

**Comment by rizalmart** [comment]
I made an experiment on systemd on ubuntu. I replaced the /sbin/init with a shell script containing a command to show a dialog then execute systemd. And it works, so init agnostic was almost feasible. What we need was to ensure the puppy's virtual filesystem is ready before executing the init. It means the upgrading savefiles was performed and updating system cache files first before kick-starting the init.

Also some init configurations to execute the /etc/rc.d/rc.shutdown upon shutting down or reboot

**Comment by s243a** [comment]
My guess is that if the change is simple (i.e. just changing puppy's virtual file system slightly) than the code will get merged. However, for branding purposes, there might be some requirement that "official puppies" use busybox init. In my opinion a big selling point of puppy is that it is systmd free. 

Anyway, why not do a merge request and see if it gets accepted? 

So in short. In the future woof-CE might give the option to use a different init but puppies built this way won't be considered official.
