### ISSUE TITLE
aufs-utils repos out of synch

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1729]
https://github.com/puppylinux-woof-CE/aufs-util/branches
needs to brought into synch with
https://sourceforge.net/p/aufs/aufs-util/ref/master/branches/
as there are new branches 4.19 and 5.0 that aren't in the woof-ce version

I don't know how to do this - does anybody??

**Comment by 01micko** [comment]
Frankly, IDK why it even exists, although I do recall there was a problem at sourceforge around that time. 

It looks like this is a direct export from the sourceforge aufs-util repo. IDK if you can update it without totally screwing up the commit history.

Whenever I have problems with aufs or aufs utils I normally patch it if I can and let Junjiro know on the aufs mailing list. He is usually very responsive.

**Comment by Butterfly** [comment]
I don't know, either. The most I've done is play with a couple silly one or two line examples that are out there for getting your feet wet in Github, BUT I tried a search anyway. It took a couple pokes at keywords for it to hit something that actually addressed those two by name:

[Stackoverflow: How do I mirror and synchronize GitHub and SourceForge repositories?](https://stackoverflow.com/questions/19080910/how-do-i-mirror-and-synchronize-github-and-sourceforge-repositories)

I'm seeing references to needing a third resource, either locally or "in the cloud" or something. One comment also mentions the term "webhook". I see that on rare occasion around the Net. The comment that suggests "webhook" makes it sound interesting *IF* you know what you're doing...... :smile: :dog2:

**Comment by peabee** [comment]
Should we just delete (comment out) the woof-ce clone url from build.sh???

**Comment by 01micko** [comment]
Probably.

I'm trying to update it on the CLI - **very** tedious and I suspect thankless..

I got to pull from sourceforge for 4.14 then tried to push to github but failed with stupid errors.

```
# git checkout origin/aufs4.14
Previous HEAD position was bb75870... aufs-util 20170220
HEAD is now at 5936fc0... aufs-util 20190211
# git push origin/aufs4.14
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin/aufs4.14 HEAD:<name-of-remote-branch>

# git push origin/aufs4.14 HEAD:aufs-util
fatal: 'origin/aufs4.14' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by 01micko** [comment]
Ok, its fixed as far as I can tell.

```
# git checkout origin/aufs5.0
Previous HEAD position was e6e29dd... Merge branch 'aufs4.9' into aufs4.x-rcN
Switched to branch 'origin/aufs5.0'
# git push origin HEAD:aufs5.0
Username for 'https://github.com': 01micko
Password for 'https://01micko@github.com': 
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 1.16 KiB | 0 bytes/s, done.
Total 9 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 4 local objects.
remote: 
remote: Create a pull request for 'aufs5.0' on GitHub by visiting:
remote:      https://github.com/puppylinux-woof-CE/aufs-util/pull/new/aufs5.0
remote: 
To https://github.com/puppylinux-woof-CE/aufs-util.git
 * [new branch]      HEAD -> aufs5.0
# git checkout origin/aufs5.x-rcN
Switched to branch 'origin/aufs5.x-rcN'
# git push origin HEAD:aufs5.x-rcN
Username for 'https://github.com': 01micko
Password for 'https://01micko@github.com': 
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 1.00 KiB | 0 bytes/s, done.
Total 9 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 4 local objects.
remote: 
remote: Create a pull request for 'aufs5.x-rcN' on GitHub by visiting:
remote:      https://github.com/puppylinux-woof-CE/aufs-util/pull/new/aufs5.x-rcN
remote: 
To https://github.com/puppylinux-woof-CE/aufs-util.git
 * [new branch]      HEAD -> aufs5.x-rcN
```

Yep, shows up in the link in the OP.

**Comment by 01micko** [comment]
just for the record, just incase someone wants to update https://github.com/puppylinux-woof-CE/aufs3-standalone here is the procedure I used for `aufs-util` ...

Clone
```
git clone https://github.com/puppylinux-woof-CE/aufs-util.git
```
Add remote
```
cd aufs-util
git remote add upstream https://git.code.sf.net/p/aufs/aufs-util
```
Update the local repo
```
git fetch upstream
git pull upstream master
```
Now for the tedious, thankless bit...
Get a list of branches
```
git branch -a
```
You will find that there are more `upstream` (sourceforge) branches than `origin` (our local) branches.
Old ones will likely be ok, so work backwards from the last one that was ok, in our case it was `aufs4.14`
```
# git checkout origin/aufs4.14
Previous HEAD position was d7f9184... Merge branch 'aufs3.0' into aufs3.2
HEAD is now at 5936fc0... aufs-util 20190211
# git pull upstream aufs4.14
From https://git.code.sf.net/p/aufs/aufs-util
 * branch            aufs4.14   -> FETCH_HEAD
Updating 5936fc0..1542e75
Fast-forward
 Makefile   |  2 ++
 README     | 14 +++++++++++++-
 au_util.h  |  2 +-
 auibusy.c  | 11 +++++++++++
 aumvdown.c | 15 +++++++++++++--
 auplink.c  | 10 ++++++++++
 proc_mnt.c | 34 ++++++++++++++++++++--------------
 7 files changed, 70 insertions(+), 18 deletions(-)
```
Push it!
```
git push origin HEAD:aufs4.14
```
Do the same for `aufs4.9, aufs4.x-rcN` (etc) until we see `Already up-to-date.` when pulling from upstream.
Now go back to 4.19
Because there is no local branch of that name we create it and update it
```
# git checkout -b origin/aufs4.19
Switched to a new branch 'origin/aufs4.19'
# git pull upstream aufs4.19
From https://git.code.sf.net/p/aufs/aufs-util
 * branch            aufs4.19   -> FETCH_HEAD
Already up-to-date.
```
Push!
```
 git push origin HEAD:aufs4.19
```
Now `aufs5.0`
```
# git checkout -b origin/aufs5.0
Switched to a new branch 'origin/aufs5.0'
# git pull upstream aufs5.0
From https://git.code.sf.net/p/aufs/aufs-util
 * branch            aufs5.0    -> FETCH_HEAD
Updating 8634564..bae0b9e
Fast-forward
 au_util.h |  2 +-
 ver.c     | 12 +++++++++++-
 2 files changed, 12 insertions(+), 2 deletions(-)
# git push origin HEAD:aufs5.0
```
Do the same for `aufs5.x-rcN` and it's all over red rover.

**Comment by peabee** [comment]
Great - thanks - all triggered by some posts on the forum.....
