### ISSUE TITLE
Multisession CD/DVD support should NOT be removed

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1731]
This thread is in response to a thread closed earlier here ===> https://github.com/puppylinux-woof-CE/woof-CE/issues/1675#event-2921226916

**Please consider these comments ===>** https://github.com/puppylinux-woof-CE/woof-CE/issues/1618#issuecomment-570725091

**Comment by wdlkmpx** [comment]
Relax man, it will not be removed.  **I forked the whole thing,**  stuff happens in my fork, "somewhere else", a great deal of scripts is being removed or edited to make my new project somewhat simple to maintain using basically my own scripts and more mainstream applications, as a side effect broken stuff will start working.

I am not removing anything from the puppy codebase, I am no affiliated with puppy in any shape or form.

So please kindly close this issue.

**Comment by wdlkmpx** [comment]
Close this issue dammit. I'm putting this repo on ignore again. 0 notifications.

**Comment by CollaboratorGCM** [comment]
This thread was/is **not** any attempt directed at you or anyone. It is merely an FYI of
the merits of the PUPPY ISOs that are being generated out of WOOFCE. 

The thread intends to draw attention to those PUPs which have taken steps to improve GRUB2 is easily set to afford future PUP needs without further developer attention. Please review to understand that, here ===> #1618 (comment)

Thanks goes to you and the other developers improving the life of Puppy via WOOFCE achievements. It is a "tribute".

Please dont take this directing of information as ANYTHIING personal. IT IS NOT!

**Comment by 01micko** [comment]
Not removed. Closing
