### ISSUE TITLE
Author of SuperGRUB2 ask if Puppy Developers have any more concerns.

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1734]
[**A request to Puppy Linux developers is here.**](https://github.com/supergrub/supergrub/issues/61#issue-545950953)

Most know that #PeaBee, @JamesBond, and others have released their distro(s) whose ISOs have "No Problems" booting when their ISOs are launched from the SG2D menu. I and another forum member have tested SG2D using these PUP ISO file boots on both BIOS and UEFI systems with no issues in getting desktops, saving sessions, and all other things that the standalone PUPs do when not launched directly from their ISOs.

For those who did test, if you found some ideas to pass along or requests, now your time.

**Comment by dimkr** [comment]
Can this issue be closed?

**Comment by CollaboratorGCM** [comment]
I concur. Since 2019 every WoofCE PUPs boots without issues directly from their ISO files along with Ubuntus, MXs, Manjaros, and others via SG2D. **Great!**
