### ISSUE TITLE
Support for .tar.zst archives is needed

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1738]
Packages are begining to appear in .tar.zst format from Arch Linux....
Xarchive needs a new wrapper for this new archive format.
Other changes are maybe needed to recognise the the new mime type?

**Comment by peabee** [comment]
Support has now been added to Woof-CE, however the common32/64 pets for xarchive and shared-mime-info also need to be updated and I'm unsure how to do this? @woodenshoe-wi  or @01micko  can you advise where the sources are held and how the pets should be updated?

**Comment by woodenshoe-wi** [comment]
Well, I haven’t been compiling pets lately, so there could have been some changes to how it is done that I don’t know about, but this is what I remember...

The petbuilds from the generic branch are used to compile common32/64 pets,  
https://github.com/puppylinux-woof-CE/petbuilds/blob/generic/basic/pkgs/xarchive/xarchive.petbuild  
https://github.com/puppylinux-woof-CE/petbuilds/blob/generic/basic/pkgs/shared-mime-info/shared-mime-info.petbuild

According to the xarchive petbuild, its source code is downloaded from http://distro.ibiblio.org/puppylinux/sources/x/

The source code for shared-mime-info comes from http://freedesktop.org/~hadess but it seems that the newest versions are now using a gitlab interface at freedesktop.org https://gitlab.freedesktop.org/xdg/shared-mime-info/uploads/b27eb88e4155d8fccb8bb3cd12025d5b/shared-mime-info-1.15.tar.xz

If the newer version doesn’t fix the problem, the other approach would be to redo the magic_fix.patch to include the needed changes.  
https://github.com/puppylinux-woof-CE/petbuilds/blob/generic/basic/pkgs/shared-mime-info/magic_fix.patch

**Comment by peabee** [comment]
Thanks @woodenshoe-wi 
I'm not convinced that the xarchive source on ibiblio (dated 2014-Oct-18) is up to date as the .tar wrapper does not match the .tar wrapper in the current .pet......
I suspect @wdlkmpx had source "somewhere else" - maybe on 01micko server which has restricted access so I can't search it ( @01micko ) ???

**Comment by peabee** [comment]
From:
https://github.com/puppylinux-woof-CE/woof-CE/commit/1d5a0349c2cb17ff8b9a1c44ac0b86193bd831d0
looks like
xarchive-0.2.8-6-i18n-i686_rev2 
is the updated source - but where is it???

**Comment by 01micko** [comment]
It's the same source, just wrappers modified. Refer to the generic petbuild for wrappers.

There is no xarchive sources anywhere on my hosting.

**Comment by peabee** [comment]
Thanks @01micko - got it...
https://github.com/puppylinux-woof-CE/petbuilds/tree/generic/basic/pkgs/xarchive/wrappers

**Comment by peabee** [comment]
xarchive is updated to rev3 to support zstd
not changing shared-mime-info for now as latest version upstream does not include archlinux packages....
There is still some work needed on icons....but closing this issue.
