### ISSUE TITLE
/support/findpkgs fails to find some wildcards with multiple package db's

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1749]
If wildcards such as xf86-video-*
are specified
and there are multiple package db's
and the wildcard is matched in a package db
then searching for wildcards ceases and other subsequent package db's are not searched

**Comment by woodenshoe-wi** [comment]
I looked through the history of the findpkgs script, and as far as I can tell, this has always been the case.

I think findpkgs won’t search the remaining package db’s whenever a package is found, not just when wildcards are used.

Is there a reason why it is causing problems now?  It is faster to abort the search when something is found and move on to the next package.

**Comment by jamesbond3142** [comment]
Sorry for OOT. @woodenshoe-wi, since I catch you here, can you please reply to my question about your rox-filer patch, here: https://github.com/woodenshoe-wi/rox-filer/issues/5 ? Thank you.

**Comment by peabee** [comment]
Yes - in the build I was trying to do (Arch32), there were 3 package repos - community, core and extra, and it happens there is 1 xf86-video in community and all the rest are in extra. Therefore with the db's in alphabetical order only the community wildcard was found and all the ones in extra were ignored. Logically, for wildcards, all matches should be found? Fixed by changing the order to core, extra, community so that it is only the singleton in community that's ignored.

**Comment by woodenshoe-wi** [comment]
I guess it wouldn’t slow things down too much if findpkgs would only search through all the dbs when a wildcard is involved...

**Comment by woodenshoe-wi** [comment]
You could try this modified version (based on the current testing branch), woodenshoe-wi/woof-CE@6256159,  

https://github.com/woodenshoe-wi/woof-CE/raw/6256159c1150774f9d038de2f5c1f920820a9c7c/woof-code/support/findpkgs

You will have to delete the findpkgs-search-helper binary or it will override the changes in the findpkgs script.

**Comment by peabee** [comment]
Hi @woodenshoe-wi - many thanks for doing this..... haven't been able to test as yet...
Bit worried about the suggestion to delete the binary as this is what speeds up the process considerably I believe? Do we know how to update the binary to be compatible with your changes?? Cheers @peabee

**Comment by woodenshoe-wi** [comment]
Don’t worry, if the script works the way it is supposed to I will update the binaries (x86, x86_64, ARM) too.

It’s just easier to modify one script than C source code that has to be compiled in triplicate.

I couldn’t find the Arch build, so I cut and pasted some of the Slackware package lists to test this.

On some of my early attempts entries were being skipped, so I tried adding a newline when concatenating xFNDSPECS, but that was causing errors elsewhere, so I ended up adding a newline on the condition that there were preexisting entries in xFNDSPECS.

I haven’t thoroughly tested this, and don’t have time to.  But I figured you are an active builder and when you are confident that it is working properly let me know and I will start working on updating the binaries.

**Comment by woodenshoe-wi** [comment]
Is this something I still need to finish?

I hadn’t heard back from you about the results of testing.

The source code for the binaries was moved to the initrd_progs repo back in 2019 53eda43 and the last modification was was in September 2019 puppylinux-woof-CE/initrd_progs@5d177c7 unless there is newer source code somewhere else that I don’t know about.

**Comment by peabee** [comment]
Apologies @woodenshoe-wi but I haven't got around to testing your mods.........
The problem related to Arch builds and these are on a very low back burner........
Also there was a "fix" by altering the order in which the repos were specified.
I think it can be closed now.
Many thanks.

**Comment by woodenshoe-wi** [comment]
Okay

I don’t want to change anything (and potentially break things, I’m not an expert C programmer) unless you would be ready to test things.

It’s probably a good idea to eventually fix this so repo order isn’t important, but with limited time and other priorities, not everything on the todo list can get done.

At least I was able to locate what I _think_ is the current source code for findpkgs, and if you get around to Arch builds or the problem shows up elsewhere you can always reopen this issue.
