### ISSUE TITLE
README should mention "devx" as a prerequisite

### ISSUE THREAD

**Issue by brandonlichtenwalner** [puppylinux-woof-CE/woof-CE#1751]
I stumbled on to this wonderful project and got up and running quickly except that my first few builds failed -- even when I attempted an unmodified build to troubleshoot. It took a bit of googling to realize that my Puppy host box needed to have "devx" installed for my created ISOs to work.

I definitely got some errors/warnings as I was building, but no outright failures or even indications of what I might need. The process went straight through to spitting out an ISO (that actually even booted) but failed to a shell (and surely had other broken bits).

**Comment by 01micko** [comment]
Ok, good point.

**Comment by mavrothal** [comment]
Is probably an overkill but you might want to add something like that in merge2out
```
if [ -f /etc/rc.d/BOOTCONFIG -a "$( grep devx /etc/rc.d/BOOTCONFIG)" = "" ]; then
	echo "Please install the devx sfs and try again"
	exit 1
fi 
```
