### ISSUE TITLE
xarchive and opening 7z and rar

### ISSUE THREAD

**Issue by ghost** [puppylinux-woof-CE/woof-CE#1752]
I noticed clicking on 7z or rar file doesn't work any more, it will either open them as blank (no contents) or post a message about encrypted headers in xarchive, so I end up having to extract them from command line with 7z x or unrar x. Removing the p7zip-16.02-i686/common64_rev2 with "Remove Builtin Packages" then installing the salix/slackware one from ppm fixes both filetypes in xarchive, though maybe there is a better way to fix the incompatibility with the newest 16.02_rev2 "puppy-common" ones?

Tested with latest build of slacko64-14.2 (Slacko64 6.9.9.9) and slacko-14.0 (Slacko 5.8.10).

**Comment by 01micko** [comment]
So, @ninaholic are recent changes to blame or the 'common' package? 

TBH, I'm _not_ a fan of _common_. I tried to reduce these as much as possible in early slacko development.

**Comment by ghost** [comment]
Hi 01micko,

I tried a recent slacko64 build with your newly added p7zip-16.02-x86_64_s701 pet and both the 7z and rar files I tried open great again with xarchive! Thank you :smile:

**Comment by 01micko** [comment]
Oh, I meant to mention that here.. :sob: 

Glad you found out! Thanks!
