### ISSUE TITLE
/run/sshd get's deleted upon reboot. 

### ISSUE THREAD

**Issue by s243a** [puppylinux-woof-CE/woof-CE#1755]
This is probably a woof-CE issue so I'll report it here:

> I installed ssh-server on DpupBuster. The folder /run/sshd seems to get deleted upon reboot. I recreated this folder with the standard permissions...that you get by creating a new folder in the file manager. Not sure if these permissions are correct. For the ssh server /run/sshd is needed when using the privilege separation option on your ssh server. Privilege separation is the default behavior for the ssh server in openssh. This is probably a woof-CE bug, so I'll also report it on github.
http://murga-linux.com/puppy/viewtopic.php?p=1050603#1050603 

The same issue probably applies to other folders in the /run folder. I remember a related issue on TazPup.

**Comment by 01micko** [comment]
/run is a symlink to /tmp  so this is why. In puppy /tmp has always been cleared between boots.

**Comment by 01micko** [comment]
I reinstated /run as a real directory. In my slackware install it has 0755 perms. If anyone knows better, feel free to adjust perms on /run.
