### ISSUE TITLE
Your recent release does not boot via SuperGrub2

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1765]
@gyrog 

Have you tried?

The SG2D needs to find the file loopback.cfg to present the ISO for boot selection. If it does, it will launch the ISO same as it does for other 2020 PUPs (i.e. @Peabee's and @ Jamesbond and Bionic...)

@ETP published on the forum about a simple folder for PUPs (and other Linux distros) ISOs that if will locate,present, and allow the PUP ISOs to launch to their normal Boot Menus. ALL PUP functions that exists in each ISO works as they always have.

Try it if you would,please.

**Comment by s243a** [comment]
What version of puppy are you testing SuperGrub2 with?

**Comment by gyrog** [comment]
@CollaboratorGCM,
I don't produce iso's, and it's very unlikely I will do so in the future.
FrugalPup is just a Puppy installer utility that installs existing Puppies to boot using Grub2.

**Comment by CollaboratorGCM** [comment]
@gyrog PLEASE accept my apology!!!

I was reviewing another PUP in one window while having another murga-linux window open to FrugalPUP..

I'm old and made an error in this thread's post.

OLD is not an excuse, but, I made one here! (and I am one who criticize other old people driving...HA!)

**Comment by gyrog** [comment]
@CollaboratorGCM
No worries.
