### ISSUE TITLE
New kmod produces different modinfo output affecting /etc/rc.d/rc.sysinit

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1793]
Slackware current has new version of kmod - kmod-27-i586-1.txz
this produces different output from:
modinfo ehci_hcd
which means that line 474 of /etc/rc.d/rc.sysinit
no longer triggers to set USBBUILTIN=yes

New kmod / modinfo output from modinfo ehci_hcd is:
name:           ehci_hcd
filename:       (builtin)
license:        GPL
author:         David Brownell
description:    USB 2.0 'Enhanced' Host Controller (EHCI) Driver
parm:           log2_irq_thresh:log2 IRQ latency, 1-64 microframes (int)
parm:           park:park setting; 1-3 back-to-back async packets (uint)
parm:           ignore_oc:ignore bogus hardware overcurrent indications (bool)

**Comment by 01micko** [comment]
Try this:

```sh
#note, if initrd then usb-storage will have already loaded...
USBBUILTIN='no'
if [ "`modinfo ehci_hcd 2>/dev/null`" = "" ];then #110712 shut this up.
 #kernel has usb core drivers (and usb-storage) builtin.
 USBBUILTIN='yes'
elif modinfo ehci_hcd | grep -q 'filename: (builtin)' ;then
 USBBUILTIN='yes' 
else
 PCIUSB="`lspci -n | grep -o -E ' 0c03: '`" #160609
 if [ "$PCIUSB" != "" ];then #this may be slow to respond.
  echo -n " usb"  >/dev/console
  PCIUSBNUM=`echo "$PCIUSB" | sort -u | wc -l`
  while [ $WAITCNT -lt 10 ];do
   [ `lsmod | grep -o -E '^uhci_hcd|^ohci_hcd|^ehci_hcd|^xhci_hcd' | wc -l` -ge $PCIUSBNUM ] && break #160609
   WAITCNT=`expr $WAITCNT + 1`
   sleep 1
   echo -n " $WAITCNT" >/dev/console
  done
 fi
fi
```

**Comment by peabee** [comment]
Thanks Mick - I was sort of heading that direction, but....
No [] ?

**Comment by 01micko** [comment]
`grep -q 'something'` returns an exit code (0 if successful) and is quite efficient, even though an external is called.

Try it :smile_cat:

**Comment by peabee** [comment]
Thanks again...
elif modinfo ehci_hcd | grep -q '(builtin)' ;then #kmod new version
 USBBUILTIN='yes' 

tested and works OK - will commit
