### ISSUE TITLE
Remaster and Puppy Boot Facility

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1803]
At the beginning of 2020, Puppy Linux has improved its boot ability in several ways ranging from UEFI to BIOS strategies. Those were brought to bear particularly from the PUPs of FD810 and those from PeaBee. One of the most notible changes is that their PUPs ISOs can be saved in a Common folder; namely /bootisos (for me), and booted directly from that folder thru a 15MB facility which lets one select any distro in that folder to be booted with persistence if chosen. How to boot is expressed in the PUP forum by **[@ETP here](http://www.murga-linux.com/puppy/viewtopic.php?t=118043)**

I've discovered that when running their PUPs, one PUP feature that is overlooked is PUP's remaster. When the FD810 is remastered, for example, it continues to created an ISO of the running system as it has alway done. But, the new 2020 boot ability is NOT copied into the remastered ISO such that it, too, can be found in /bootisos and booted...same as the original running FD810.

This is an oversight, I am sure and am hopeful that other developers notice a similar change will be needed in the Remaster app to include the original Boot features that should be carried over into the remaster ISO.

**Comment by CollaboratorGCM** [comment]
Thanks @jamesbond3142 for the update to FD810 Remaster subsystem.

**Comment by jamesbond3142** [comment]
@CollaboratorGCM - I replied to you in private email on purpose because I don't think it is appropriate to discuss or announce anything about Fatdog here. 

While Fatdog64 and the Puppy Linux has warm brotherly relationship to each other, and the team on both sides exchange ideas and help each other freely from time to time, Woof-CE is a Puppy-specific tool that has nothing to do with Fatdog64 - so issues and comments about Fatdog64 (other than ones intended to improve Woof-CE/Puppy Linux) should not be discussed here.

That being said, I'm sure you don't meant it at all, so just treat the above as a friendly reminder :smile:

 I'll leave this thread open for anyone who wants to do the same thing in Puppy.

**Comment by CollaboratorGCM** [comment]
@jamesbond3142 Thanks! And your message, above, is rightly appropriate. I'll try NOT to repeat that err in judgement.

ON Another note
This is another idea that I would like the developers who support the trusty GRUB2-EFI facility that some of the 2020 distros exhibit. 

The WoofCE does not appear to be generating the same boot facilities that @Peebee and other developers have shown us. What appears to be missing in those 32bit and 64bit distros that users are generating do not have the loopback.cfg  which allow their ISOs to boot directly without writing to DVD or USB.

Could that be an oversight? If so, can it be remedied to match the 2020 distros that do contain the needed file? I can only assume that this is a one-time change that will endure the test of time now that GRUB2-EFI is satisfying boot processing on the BIOS & UEFI PCs; thus, once done, it would remain consistent for a long time or until the world moves to some other form of firmware.

Thanks to all those who review what I am sharing and will consider the WOOFCE need.

**Comment by peabee** [comment]
> WoofCE does not appear to be generating the same boot facilities that @peebee and other developers have shown us. 

My builds are 100% generated by Woof-CE (usually relatively current version) - I add nothing to do with booting. If there are recent builds that are different (?? are there ??) then the developer needs to be informed and work out why - it is not a Woof-CE problem.
The Woof-CE version status should be in /etc/DISTRO_SPECS but this is not guaranteed.

**Comment by CollaboratorGCM** [comment]
Testing FossaPUP Alpha: Remaster generates the new ISO with all features that replicate the original ISO's boot process. Thus it carries the same boot features for BIOS & UEFI across. And in addition, the ISO can be booted directly via SG2D without writing it to media. Persistence (session saving to folder/files) continues as one would expect.

Thanks to WOOFCE developers!
