### ISSUE TITLE
svg format errors

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1806]
Newer svg libraries are much less tolerant of svg errors. xml version=1.1 is invalid. xlink:href should not be used if xlink has not been defined.

The Puppy icons with these problems can be located with the following commands run in rootfs-skeleton and rootfs-packages:

find . -name *.svg | xargs -n 1 -d \\n grep -l 'xml version=\"1.1'
find . -name *.svg | xargs -n 1 -d \\n grep -l 'xlink:href'

The Puppy icons with xml version=1.1 which needs to be changed to 1.0 are:
./ptheme/usr/share/themes/xfdark/gtk-2.0/check3.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/blank.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/arrow_right2.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/arrow_right1.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/radio1.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/radio2.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/arrow_up2.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/arrow_down1.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/check2.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/arrow_down2.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/arrow_left2.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/check1.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/arrow_left1.svg
./ptheme/usr/share/themes/xfdark/gtk-2.0/arrow_up1.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/check3.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/blank.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/arrow_right2.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/arrow_right1.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/radio1.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/radio2.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/arrow_up2.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/arrow_down1.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/check2.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/arrow_down2.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/arrow_left2.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/check1.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/arrow_left1.svg
./ptheme/usr/share/themes/Stardust_bright_mouse/gtk-2.0/arrow_up1.svg
./ptheme/usr/share/themes/Stardust_dark_mouse/gtk-2.0/check3.svg
./ptheme/usr/share/themes/Stardust_dark_mouse/gtk-2.0/radio1.svg
./ptheme/usr/share/themes/Stardust_dark_mouse/gtk-2.0/radio2.svg
./ptheme/usr/share/themes/Stardust_dark_mouse/gtk-2.0/check2.svg
./ptheme/usr/share/themes/Stardust_dark_mouse/gtk-2.0/check1.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_audio_youtube.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_stop.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_pause.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_directory.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_podcast_played.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_previous.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_genre.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_go_left.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_next.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_go_right.svg
./pmusic/usr/local/pmusic/themes/Gtk/question.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_tempo.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_podcast_channel.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_play.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_podcast_dead.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_podcast_available.svg
./pmusic/usr/local/pmusic/themes/Gtk/info.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_info.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_audio_youtube.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_stop.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_pause.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_directory.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_add_more.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_podcast_played.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_previous.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_genre.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_go_left.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_next.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_go_right.svg
./pmusic/usr/local/pmusic/themes/Nad5/question.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_tempo.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_audio_podcast.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_preferences.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_help.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_podcast_channel.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_play.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_podcast_dead.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_podcast_available.svg
./pmusic/usr/local/pmusic/themes/Nad5/info.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_dialog_warning.svg

The Puppy icons containing xlink:href which needs to be changed to just href are:
./usr/share/pixmaps/puppy/cd_no.svg
./usr/share/pixmaps/puppy/shield_no.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/64/mimetypes/inode-chardevice.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/64/actions/tools-check-spelling.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/64/actions/spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/64/actions/gtk-spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/16/mimetypes/inode-chardevice.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/16/actions/tools-check-spelling.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/16/actions/spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/16/actions/gtk-spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/scalable/mimetypes/inode-chardevice.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/scalable/actions/tools-check-spelling.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/scalable/actions/spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/scalable/actions/gtk-spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/22/mimetypes/inode-chardevice.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/22/actions/tools-check-spelling.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/22/actions/spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/22/actions/gtk-spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/32/mimetypes/inode-chardevice.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/32/actions/tools-check-spelling.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/32/actions/spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/32/actions/gtk-spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/48/mimetypes/inode-chardevice.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/48/actions/tools-check-spelling.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/48/actions/spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/48/actions/gtk-spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/24/mimetypes/inode-chardevice.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/24/actions/tools-check-spelling.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/24/actions/spell-check.svg
./puppy_standard_icons/usr/share/icons/Puppy Standard/24/actions/gtk-spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/64/mimetypes/inode-chardevice.svg
./pmaterial_icons/usr/share/icons/PMaterial/64/mimetypes/text-x-c++src.svg
./pmaterial_icons/usr/share/icons/PMaterial/64/mimetypes/text-x-csrc.svg
./pmaterial_icons/usr/share/icons/PMaterial/64/actions/insert-text.svg
./pmaterial_icons/usr/share/icons/PMaterial/64/actions/tools-check-spelling.svg
./pmaterial_icons/usr/share/icons/PMaterial/64/actions/spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/64/actions/gtk-spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/64/status/caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/64/status/gtk-caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/16/mimetypes/inode-chardevice.svg
./pmaterial_icons/usr/share/icons/PMaterial/16/mimetypes/text-x-c++src.svg
./pmaterial_icons/usr/share/icons/PMaterial/16/mimetypes/text-x-csrc.svg
./pmaterial_icons/usr/share/icons/PMaterial/16/actions/insert-text.svg
./pmaterial_icons/usr/share/icons/PMaterial/16/actions/tools-check-spelling.svg
./pmaterial_icons/usr/share/icons/PMaterial/16/actions/spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/16/actions/gtk-spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/16/status/caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/16/status/gtk-caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/scalable/mimetypes/inode-chardevice.svg
./pmaterial_icons/usr/share/icons/PMaterial/scalable/mimetypes/text-x-c++src.svg
./pmaterial_icons/usr/share/icons/PMaterial/scalable/mimetypes/text-x-csrc.svg
./pmaterial_icons/usr/share/icons/PMaterial/scalable/actions/insert-text.svg
./pmaterial_icons/usr/share/icons/PMaterial/scalable/actions/tools-check-spelling.svg
./pmaterial_icons/usr/share/icons/PMaterial/scalable/actions/spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/scalable/actions/gtk-spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/scalable/status/caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/scalable/status/gtk-caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/22/mimetypes/inode-chardevice.svg
./pmaterial_icons/usr/share/icons/PMaterial/22/mimetypes/text-x-c++src.svg
./pmaterial_icons/usr/share/icons/PMaterial/22/mimetypes/text-x-csrc.svg
./pmaterial_icons/usr/share/icons/PMaterial/22/actions/insert-text.svg
./pmaterial_icons/usr/share/icons/PMaterial/22/actions/tools-check-spelling.svg
./pmaterial_icons/usr/share/icons/PMaterial/22/actions/spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/22/actions/gtk-spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/22/status/caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/22/status/gtk-caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/32/mimetypes/inode-chardevice.svg
./pmaterial_icons/usr/share/icons/PMaterial/32/mimetypes/text-x-c++src.svg
./pmaterial_icons/usr/share/icons/PMaterial/32/mimetypes/text-x-csrc.svg
./pmaterial_icons/usr/share/icons/PMaterial/32/actions/insert-text.svg
./pmaterial_icons/usr/share/icons/PMaterial/32/actions/tools-check-spelling.svg
./pmaterial_icons/usr/share/icons/PMaterial/32/actions/spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/32/actions/gtk-spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/32/status/caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/32/status/gtk-caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/48/mimetypes/inode-chardevice.svg
./pmaterial_icons/usr/share/icons/PMaterial/48/mimetypes/text-x-c++src.svg
./pmaterial_icons/usr/share/icons/PMaterial/48/mimetypes/text-x-csrc.svg
./pmaterial_icons/usr/share/icons/PMaterial/48/actions/insert-text.svg
./pmaterial_icons/usr/share/icons/PMaterial/48/actions/tools-check-spelling.svg
./pmaterial_icons/usr/share/icons/PMaterial/48/actions/spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/48/actions/gtk-spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/48/status/caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/48/status/gtk-caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/24/mimetypes/inode-chardevice.svg
./pmaterial_icons/usr/share/icons/PMaterial/24/mimetypes/text-x-c++src.svg
./pmaterial_icons/usr/share/icons/PMaterial/24/mimetypes/text-x-csrc.svg
./pmaterial_icons/usr/share/icons/PMaterial/24/actions/insert-text.svg
./pmaterial_icons/usr/share/icons/PMaterial/24/actions/tools-check-spelling.svg
./pmaterial_icons/usr/share/icons/PMaterial/24/actions/spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/24/actions/gtk-spell-check.svg
./pmaterial_icons/usr/share/icons/PMaterial/24/status/caps-lock-warning.svg
./pmaterial_icons/usr/share/icons/PMaterial/24/status/gtk-caps-lock-warning.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/64/mimetypes/inode-chardevice.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/64/actions/tools-check-spelling.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/64/actions/spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/64/actions/gtk-spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/16/mimetypes/inode-chardevice.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/16/actions/tools-check-spelling.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/16/actions/spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/16/actions/gtk-spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/scalable/mimetypes/inode-chardevice.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/scalable/actions/tools-check-spelling.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/scalable/actions/spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/scalable/actions/gtk-spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/22/mimetypes/inode-chardevice.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/22/actions/tools-check-spelling.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/22/actions/spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/22/actions/gtk-spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/32/mimetypes/inode-chardevice.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/32/actions/tools-check-spelling.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/32/actions/spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/32/actions/gtk-spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/48/mimetypes/inode-chardevice.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/48/actions/tools-check-spelling.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/48/actions/spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/48/actions/gtk-spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/24/mimetypes/inode-chardevice.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/24/actions/tools-check-spelling.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/24/actions/spell-check.svg
./puppy_flat_icons/usr/share/icons/Puppy Flat/24/actions/gtk-spell-check.svg
./pmusic/usr/local/pmusic/themes/Gtk/album_art_radio.svg
./pmusic/usr/local/pmusic/themes/Gtk/icon_audio_cd.svg
./pmusic/usr/local/pmusic/themes/Nad5/album_art_radio.svg
./pmusic/usr/local/pmusic/themes/Nad5/icon_audio_cd.svg

**Comment by mrfricks** [comment]
this is also affecting stuff in /usr/lib/gtkdialog ... box_splash for one

**Comment by 01micko** [comment]
I found out about the version foobar in the header ages ago and did inform @zigbert 

As for the xlink thing, if it's defined in the `<svg ...>` header does that still cause a 
problem?

eg 
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" height="48px" width="48px" viewBox="0 0 192 192">
```

 PMaterial should have that in all calls to xlink

Remember, before madly 'fixing' icons the sources are the key :wink:

**Comment by 01micko** [comment]
What about wallpapers produced by `mkwallpaper` ? They have the xlink def in the svg header and xlink calls for each glyph. These are produced by cairo.

**Comment by 01micko** [comment]
running this one liner in `rootfs-packages` is a quick fix for the xml version bug
```
find . -type f -name "*.svg" -exec sed -i 's%xml version=\"1.1\"%xml version="1.0"%' '{}' \;
```

**Comment by peabee** [comment]
> As for the xlink thing, if it's defined in the `<svg ...>` header does that still cause a
> problem?

If xlink is defined in the svg header then this suppresses the problem ..... however all the xlink:href can be changed to just href with no apparent consequential problem.

The xml version can indeed be changed - should this go into 3builddistro?

Likewise for xlink: ?

**Comment by peabee** [comment]
> this is also affecting stuff in /usr/lib/gtkdialog ... box_splash for one

box_spash should be OK as it does not include either of the problems - SVG version 1.1 is OK - just XML that is problem

My commit https://github.com/puppylinux-woof-CE/woof-CE/commit/5b360b87835cbadef5003aaaee88ccc1f1f535c4 fixes svg_bar which did have problems.

**Comment by 01micko** [comment]
> If xlink is defined in the svg header then this suppresses the problem ..... however all the xlink:href can be changed to just href with no apparent consequential problem.

Not quite true. It does wreck many icons removing the `xlink:`

**Comment by 01micko** [comment]
Ok, so I've 'fixed' the pmusic icons now .. that should be it.

With older implementations the icons are broken if the `xlink:` is left off. The `xlink` call depends on the svg namespace being correctly set too, `xmlns`. Hopefully this should keep newer svg implementations happy. I'm closing but if there are further issues feel free to re-open.
