### ISSUE TITLE
xorg-autoconf touchpad problem

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1814]
@rizalmart 

Marv on the forum has reported that he has no scrolling on his laptop touchpad with xorg-autoconf dated 2-may-2020

If he reverts to xorg-autoconf dated 21-mar-2020 then scrolling works.

He reports:
PupSysinfo gives:
Code:
Bus=0011 Vendor=0002 Product=0007 Version=01b1
Name="SynPS/2 Synaptics TouchPad"
Connected to: isa0060/serio4/input0

**Comment by 01micko** [comment]
@peabee I see marv fixed by changing false to true for auto add devices (IIRC)

@rizalmart ?

**Comment by peabee** [comment]
Yes - needs to be done inside xorg-autoconf
probably at line 769..... maybe use output from xinput to determine if needed?

**Comment by rizalmart** [comment]
@01micko sorry for late reply. It seems we need a better method to detect whether AutoAddDevices was needed to turn on or turn off

**Comment by 01micko** [comment]
@peabee @rizalmart I merged #1819 and hopefully that may cure marv's issue.

Just digressing, on modern kit (even this lappy I type on, a HP G6 ~2011 vintage) `AutoAddDevices = "true"` works fine. I believe it is older kit that have issue with that. But I wonder if there is a way where we can tell if that setting is OK?

**Comment by 01micko** [comment]
Actually, a thought just occurred to me. 

If you want to use the HDMI port then I believe `AutoAddDevices = "true"` must be set. HDMI is a fairly modern feature so maybe detecting a HDMI port could be the defining thing for the state of `AutoAdddevices` ?

**Comment by rizalmart** [comment]
I just wonder, what Xorg version did AutoAddDevices option first implemented?

**Comment by rizalmart** [comment]
I noticed that Xorg drivers were version sensitive against Xorg server. What if ignoreABI option is enabled on xorg.conf, what do you think?

**Comment by 01micko** [comment]
@rizalmart it was a long time ago, I think back in Ubuntu Jaunty days.

Anyway, detecting HDMI is easy with this:
```
udevadm info --export-db | grep 'HDMI'
```

**Comment by rizalmart** [comment]
@01micko it seems HDMI detection works for detecting newer hardware only. I think detection of xorg version might do the trick.

**Comment by 01micko** [comment]
I agree but that is my point exactly. Some older hardware (old P4, older Athlon, and some older video chips) are not comfortable with hardware auto detection. All xorg versions currently in woof supported distros will be capable of udev hardware auto detection but that doesn't mean that the hardware is capable.

**Comment by 01micko** [comment]
Another thought, a cli option to override auto.. say `pautoadd=true` or `pautoadd=false` to give user control. No matter what we choose for them this option will override that choice.

**Comment by rizalmart** [comment]
@01micko I dug into the past xorg docs from xorg official website. It turns out that udev support for xorg server starts at version 1.8

So it means if xorg version was 1.8 above AutoAddDevices will be automatically set to true

**Comment by jamesbond3142** [comment]
> I agree but that is my point exactly. Some older hardware (old P4, older Athlon, and some older video chips) are not comfortable with hardware auto detection. All xorg versions currently in woof supported distros will be capable of udev hardware auto detection but that doesn't mean that the hardware is capable.

Some considerations:

The question is how far back is the hardware you want to support? P4 is from 2000-2003 days. Athlons (the 32-bit version, not the 64-bit ones) were from 2000s too. That is hardware from 20 years ago. No doubt there are people who still have those hardware and manage to keep them working, but do we really expect today's latest software to run on 20-year old machines?

If I remember correctly, Puppy's target market is -10 year hardware. That is, a Puppy released today needs to work on hardware from 2010 onwards. 

xorg-server 1.8 was released in April 2010. That was over 10 years ago. Fatdog started to support full auto-configuration (no xorg.conf - this implies AutoAddDevice "true") - as early as August 2011. The oldest 64-bit machine I had was from 2007 and it worked with auto-configuration (this was an Athlon X2 with built-in nvidia graphics).

**Comment by CollaboratorGCM** [comment]
In support of what James presents, this is an IMPORTANT issue! (This post is NOT about xorg, rather about the developers time and "support")

Having been in this industry for "life" in my case, I am aware of the time everyone contributes.

Puppy Linux has SOLVED old hardware in the ISOs presented. There are countless copies of PUPs that actually run on old hardware with developer utils built back then to support them. Thus ISOs built in the days of those PCs work and continue to work, even today.

Thus developers should distinguish a "term" for which they will support without trying to build for EVERY PC ever built.

Maybe it serves all, developers & users, that a term exist and was made plain. All too often I have seen users demands for fixes in old 32bit hardware. I tested a 2006 64-bit Athlon (my first for KVM testing back then) last week before scrapping. Its performance, though adequate, pales in comparison.  

Developers could express this, not as something new, rather about the fact that the old ISOs do work for old PC. And, that 2020 PUPs going forward focus on INSURING that PC less than 11 years old will work on latest ISO versions produced ... with no guarantees for hardware older than 11. If an older distro works on old hardware, unless there is 'broken' software, developers should not be expected to fix current software for old hardware.

Again, this is just an FYI

**Comment by rizalmart** [comment]
I made an overhaul on xorg-autoconfig. It now works effectively on both old and new pups. The overhaul is on pull request
