### ISSUE TITLE
Rubix game in Slacko64 6.9.9.9

### ISSUE THREAD

**Issue by ghost** [puppylinux-woof-CE/woof-CE#1816]
I notice to get Rubix in Fun to work, typing rubix -font 6x13 in terminal was needed:

![Screenshot](https://user-images.githubusercontent.com/5408521/81618102-b0555480-93b4-11ea-9033-1b55ba63da05.png)

Another way to fix was to re-compile 1.0.6 code here changing 7x13 in main.c to 6x13:
http://sed.free.fr/rubix/

![Screenshot(1)](https://user-images.githubusercontent.com/5408521/81618268-f4485980-93b4-11ea-9151-43d4440bb055.png)

Not sure if changing this is good solution or finding missing 7x13 font so I place here. :smile:

**Comment by ninaholic** [comment]
A few other minor things in Slacko64 14.2 build noted:

PMirrorGet - icon used for "Grab it Now" button missing
/usr/local/lib/X11/mini-icons/mini.checkmark.xpm

PWSGet - icon used for "Dest dir" missing
/usr/local/lib/X11/mini-icons/mini-ofolder.xpm

pSynclient - shows up in both Desktop and System

CUPS Printing - has two entries that lead to the same, one in System one in Setup

**Comment by ninaholic** [comment]
Interestingly a new slacko32 6.9.9.9 build does not have the issue. I wonder what the difference could be, maybe the evdev change? https://github.com/puppylinux-woof-CE/woof-CE/issues/1717#issuecomment-565160663

**Comment by ninaholic** [comment]
Will try the slacko64 with a different ptheme and see if that helps in a bit.

**Comment by 01micko** [comment]
Duly noted,

For the record, here's the patch (i called it  `font.patch`)

```patch
diff -up rubix-1.0.6.orig/main.c rubix-1.0.6/main.c
--- rubix-1.0.6.orig/main.c	2008-11-20 05:40:12.000000000 +1000
+++ rubix-1.0.6/main.c	2020-05-16 09:54:10.279992723 +1000
@@ -73,7 +73,7 @@ int main(int nb, char **argv)
   char *filename = NULL;
   char *ptr;
    
-  FONT = "7x13";
+  FONT = "6x13";
   EDGE = 0.475;
 
   SCREEN_X = 320;
```

Apply it in the same dir as the source dir resides (that is immediately outside the src dir)

```
patch -p0 < font.patch
```

New packages 64 and 32 uploading soon, when done will close this.

There is a bug report about this in red hat. Apparently there is a patch set for x11 but it seems latest stable slackware omits these for some reason.
