### ISSUE TITLE
GRUB2 in PUPs

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1820]
Puppy continues to mature across the board. The refinements this year are incredible. Great efforts in modernizing and taking advantages of the Linux developer improvements.

GRUB2 incorporation in WOOFCE PUPs has certainly impacted a new change and with those changes, we are now aware that a central ISO library (/boot-isos, for example) can forego any need to run frugal as well as burn any ISO to DVD or media.

As the year moves forward, does this forum link suggest a need to include GRUB2 package/utilities in the WOOFCE builds to support old and new PCs? ===> http://murga-linux.com/puppy/viewtopic.php?p=1058340#1058340

FYI

**Comment by 01micko** [comment]
@jamesbond3142 has sent me some grub2 files and I'm looking into it as soon as my new UEFI computer arrives some time early this week :crossed_fingers:

**Comment by gyrog** [comment]
I'm not sure what kind of grub2 thing users are expected to do with this.
Yes, it might be nice to include support for grub2 compiling in the devx.
If there are support packages for generating grub.cfg files then these could be useful to include in Puppy.
If you are thinking of users installing grub2 to a device for uefi booting, then "Secure Boot" will require a signed "shim", a signed grub2 ".efi" file and of course a public key.

FrugalPup contains a tar file that can be used to install grub2 to a fat32 partition.
For a uefi boot simply extract 'grub2-efi.tar.xz' into the root of the fat32 partition,
then provide a suitable 'grub.cfg' file in the root of the fat32 partition.
'grub2-efi.tar.gz' contains 32bit and 64bit  "shim", grub2 ".efi" and  public key file 'puppy.key'. All provided by @jamesbond3142.

FrugalPup also contains a 'grub2-mbr.tar.gz' that can be used in a similar way for non-uefi booting. The grub2 in this file was compiled by me.

**Comment by gyrog** [comment]
One thing that really would be useful to be included in Puppy is full support for MOK-utils.
These enable the MOK's in the uefi bios to be viewed, and deleted etc...

**Comment by CollaboratorGCM** [comment]
By now, we have benefited from the additions of GRUB2-EFI in the 2020 WoofCE PUPs.

Many/most already know the benefits provided by GRUB2 in both its international development, hardware manufacturer support, and improvements to stay in parallel with the advancements in 64bit systems and new I/O devices.

One other benefit is the fact that Block0 and Block1 of disk technology is a no-brainer whether we are using MSDOS or GPT units, not to mention that those users with Linux backgrounds who use/test 2020 PUPs will find GRUB-EFI that has been used in mainstream discos for years. So, there is no learning curve for boot understanding: And, they are the people who already are trained and will be helping others in the forum going forward into PUP's future. This, among other efforts by this development team is an example of how these selections reduce the workload on this PUP developer community when some useful international utilities are included.

Thus, inclusion of the GRUB2 utilities has positive benefit...in the event those utilities become added for WoofCE system builds, OOTB.

**Comment by CollaboratorGCM** [comment]
As we plunge further into 2020, I ask: Is it time to add 2 features to WoofCE created PUPs understanding that UEFI has been widespread for past dozen (YES 12) years?

We all know how effective GRUB2-EFI is. So: 
- Can WoofCE start by adding GRUB2-EFI utils to newly generated PUPs for very obvious reasons? 
- Also, if this does start to show up, could the GRUB Customizer be a part so that it makes easy for Menu changes to occur within any given PUP?
Users should not have to LOOK for these utils as the 2020 PUPs are currently built with GRUB2-EFI. I think they really should be a part of the booted system(s) making ease for use. All over the internet are instructions for using GRUB2-EFI for anyone. Yet to use, there's problems with missing needs, etc associated with attempts thru PUP package managers.

Its a mere thought based on observations. FATDOG has the similar use issues, as well.
