### ISSUE TITLE
Placement of the "rgb.txt"

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1821]
**THIS IS MINOR!**

Reading this ==> http://murga-linux.com/puppy/viewtopic.php?p=1058478#1058478
To use a 'rgb.txt' requirement, PUppy has it in a "awkward" location requiring multiple products to be symlinked

Should PUP's rgb.txt be move to either
/usr/X11R6/lib/X11/rgb.txt
/usr/lib/X11/rgb.txt
/usr/openwin/lib/X11/rgb.txt

Thereby, symlinking only needed for Pup's YAD and not for any others?
/etc/X11/rgb.txt

NOT a priority of any sort. No response necessary.

**Comment by 01micko** [comment]
I'm adding symlinks in `/etc/X11` and `/usr/lib/X11`. That should be enough.
