### ISSUE TITLE
Running as user 'Finn' has some problems

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1824]
I've been running as user `finn` today. The good thing is that finn has his own home in `/home/finn` however there are numerous problems. Enabling `/tmp/xerrs.log` shows them up.

1. error writing to `/var/local/` directory - fix: change perms on `/var/local` to 1777
2.  firewall won't run. `iptables` spits out _permission denied_ errors. - fix: change perms on `iptables` (or it's source if a symlink) to 4755 (setuid)
3. finn's home is populated from `/root`. That's fine until we get to the symlinks. Because finn's home is 2 deep (/home/finn) the _relative_ symlinks get broken. I wrote a crude script to find and fix -

```sh
#!/bin/sh
find /home/finn -type l ! -exec test -e {} \; -print > /tmp/invalid
while read line; do
	dir=${line%/*}
	#echo $dir
	file="${line##*/}"
	#echo $file
	cd $dir
	pth=$(readlink "${file}")
	#echo "$pth"
	ln -sfv ../${pth} "${file}" # up one dir. remove 'v' in options for quiet output
	cd - >/dev/null 2>&1 # shut this up
done < /tmp/invalid
```
4. Mounting drive icons works ok but unmounting works however the icon doesn't refresh. This is due to **hard coding to root** which we have tried to get away from over the years. The culprit files reside in `/usr/local/pup_event`. fix - replace all instances of `/root` with `~` (tilde - which expands to $HOME, even inside single quotes).

5. plugging in a usb hdd with 2 or more partitions overlap each other - needs fixing
6. problems with `ptheme` - some hard coding to `/root`?

I'm sure there will be more problems but if users don't test we don't find. Remember, we are **users** too, :wink:

**Comment by bigpup1** [comment]
Finn was never completely working, when it was first put into Puppy by Barry K.
It was a work in progress.
Barry K liked to drop stuff into Puppy, to get people using it, to find bugs and fixes.
Not much fixing and bug uncovering, was done, before Barry K stopped working on Puppy Linux.
So, finn does need much fixing or just removed from Puppy.
Really, does Puppy need finn?

**Comment by 01micko** [comment]
>  Really, does Puppy need finn?

No.

However there are tin foil hats out there that bag Puppy for running as root. 'Finn' _is_ a viable alternative. It _does_ work satisfactorily. The main problem is the bad _developer_ habit of hard coding stuff to `/root`.

If nothing less, 'Finn' can teach good developer habits.

As a side note, all my 'C' programs are designed to run in multiuser systems. This means they are not Puppy exclusive. I test my stuff in Slackware proper, and sometimes Ubuntu.
