### ISSUE TITLE
Sound Wizard in Puppy Linux

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1830]
The ALSA Sound Wizard in Menu>Setup is wonderful in both its logical hierarchy and functions. **It works!**

Another all-in-one view of an additional sound tool, adds a element of utility functions where a user can visualize and address sound within their system.

Would this additional tool provide the ability to reduce distro developers answering user audio related questions? It is mentioned on the forum here. http://murga-linux.com/puppy/viewtopic.php?p=1059462#1059462

**In NO WAY is this tool is to replace the current Wizard!** If added, it would be a mere addition for users to visually manage or analyze their system sound.

As usual, most of my ideas aim at trying to reduce distro developer support of users so that they can focus on Puppy directional achievements when there are ample tools for user self-sufficiency.

**Comment by dimkr** [comment]
Can this issue be closed now? Future Puppy releases will probably use pavucontrol.

**Comment by CollaboratorGCM** [comment]
I concur
