### ISSUE TITLE
BionicPup64 8.0: Removing homebank messes with all icons

### ISSUE THREAD

**Issue by lobopraveen** [puppylinux-woof-CE/woof-CE#1831]
Day 2 with BionicPup64 8.0 puppy. 
USB frugal installation 

### Observed behavior
Removing built in package homebank messes with all desktop icon images (they look like missing image with ! mark), desktop background becomes grey. 

### Expected behavior
Removing homebank should not mess with any icons.

### Additional details
Restarting graphical server or window manager (don't remember which one or if it is both) throws an error dialog with text:
Error loading backdrop image: image file /usr/share/backgrounds/default.jpg contains no data Backdrop removed

I ran into this issue when I selected a bunch of packages and removed them. I thought I inadvertently removed something so I did a bunch at a time until I narrowed it down to homebank. To verify, I went in with a fresh puppy and removed only homebank and I ran into the same issue. 

Guessing that homebank uninstall might be doing something unexpected.

**Comment by mrfricks** [comment]
hi  lobopraveen,
thanks for reporting this.
i'll fix the homebank package in the repo for some reason shared-mime-info seems to have gotten into the .pet, and i'll issue an update for bionicpup to fix the issue.
for any other bionicpup64 issues please report here http://murga-linux.com/puppy/viewtopic.php?t=114311

**Comment by mrfricks** [comment]
this should be fixed now. use 'quickpet' >> 'bionicpup updates' before uninstalling homebank.

**Comment by lobopraveen** [comment]
Sure, will report on the forum as asked. Thank you for fixing it!
