### ISSUE TITLE
SFS Manager

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1833]
@gyrog

**[The StackExtra PET](http://murga-linux.com/puppy/viewtopic.php?p=1060350#1060350)** works. 

Seems to head toward an improved SFS-Load-On-the-Fly replacement or upgrade in WoofCE.

P.S. Your forum post raises concerns of the use of "mount". Is this a WoofCE concern?

**Comment by gyrog** [comment]
While I think that this is a useful direction for Puppy sfs handling into the future, "SfsExtra" does not do all the things that 'SFS-Load on-the-fly' does, so it cannot be used as  direct replacement in Woof-CE.
