### ISSUE TITLE
Kernel support for mmc storage devices.

### ISSUE THREAD

**Issue by gyrog** [puppylinux-woof-CE/woof-CE#1835]
Current Puppy kernels contain a minimum support for mmc storage devices.
Support for many devices are kernel modules, so if you are trying to boot off the mmc device, the module required to access the device is on the device.

"initrdmodules" can be used as workaround for this, but it's fairly messy to setup because it doesn't work for first boot (even with a patched 'init' script),
and it involves copying kernel modules for this specific hardware into the "initrd.gz".

Since access to storage is such a basic thing, it would seem like a good idea to greatly increase the "builtin" support for mmc devices in Puppy kernels.

To that end, I have uploaded 4 kernels to [http://www.mediafire.com/folder/21fyvbi4xglau/kernels](http://www.mediafire.com/folder/21fyvbi4xglau/kernels).
huge-4.9.227-gyro-pae.tar.bz2 for BionicPup32
huge-4.14.184-gyro-pae.tar.bz2 for ScPup
huge-4.19.128-gyro-64.tar.bz2 for BionicPup64
huge-5.4.46-gyro-64.tar.bz2 for ScPup64

Each of these contains extended mmc storage support, based on the '/etc/modules/DOTconfig...' from BK's 'linux_kernel-5.4.12-buster64.pet'
They have only 1 module in 'kernel/drivers/mmc/host', and that's for a usb cardreader.

However some of the newer kernels contain some "is not set" config lines in the "# MMC/SD/SDIO Host Controller Drivers" section of the DOTconfig... file,
which means that there is no support for thsese devices, even as modules.

We could opt to compile all future kernel's with 3 different approaches:
1. The way I have done the above, e.g. most mmc devices have "builtin" support, 1 mmc device has module support, and a few mmc devices have no support.
2. Most mmc devices have "builtin" support, all other mmc devices have module support.
3. All mmc devices have "builtin" support.
Where,
"builtin" means the relevant kernel config variable is set "=y",
"module" means the relevant kernel config variable is set "=m",
"no" means the relevant kernel config variable "is not set".

I suggest that we adopt option 3. as our policy.
It's fairly easy to do, just edit the DOTconfig to set all enties in the "# MMC/SD/SDIO Host Controller Drivers" section to "=y",
(taking notice of the following "note").
Then check the generated ".config" to ensure that there are no "is not set" or "=m" lines in the "# MMC/SD/SDIO Host Controller Drivers" section.
If it's all worked out, there should be no modules in 'kernel/drivers/mmc/host'.

Note: There is something a little odd about configuring for "Realtek" mmc devices,
if the following configurations are to stick:
CONFIG_MMC_REALTEK_PCI=y
CONFIG_MMC_REALTEK_USB=y

In older kernels (4.14 and older) you need to set these extras:
CONFIG_MFD_RTSX_PCI=y
CONFIG_MFD_RTSX_USB=y

But in newer kernels (4.19 and newer) you need to set the following extras instead:
CONFIG_MISC_RTSX=y
CONFIG_MISC_RTSX_PCI=y
CONFIG_MISC_RTSX_USB=y

**Comment by 01micko** [comment]
Yeah I found out myself that the realtek drivers for mmc/sd can be a pain  (4.19.x). 

I agree that these should be defaults (option 3)

`kernel-kit` does need an overhaul as far as x86 and x86_64 DOTconfigs go. Feel free to commit whatever you see fit if you have appropriate configs.

**Comment by gyrog** [comment]
I've compiled 5.4.46 in ScPup to try to implement option 3.
I didn't quite make it, I ended up with an option 2.
In the "# MMC/SD/SDIO Host Controller Drivers" section of the DOTconfig, all are set to "=y", except for "CONFIG_MMC_SDRICOH_CS=m", so we end up with 1 module, 'kernel/drivers/mmc/host/sdricoh_cs.ko'.
I gather it's for a pcmcia card, so I assume it's quite old, and this means that a user can't boot off it, (without "initrdmodules"). 
The issue with this config entry is that it depends on pcmcia being builtin as well.
So I'm happy to live with this compromise.

This added approx 5.7KiB to the size of the kernel, compared to the release kernel in ScPup32.
I can live with that as a trade off for supporting virtually all mmc storage devices out of the box.

**Comment by ghost** [comment]
I have two laptops with eMMC 32GB drives as main hard drive, that show up as SD card with the weird mmpblk0 numbers. I noticed there was no option in Puppy Installer to install Puppy to these hard drives, even one to erase everything and install, so I install Ubuntu and Lubuntu on them for now and those work well. When I installed grub2 then copied the puppy files to it manually,  with most newer puppies grub2 loads the vmlinuz, then cannot find the puppy.sfs files and looks on USB drive instead, which sounds like it might be a similar issue (not mounting the mmc drive at all to look in it for the puppy.sfs files)? It would certainly be nice for puppy to be able to look in mmc drive for these files so I can boot puppy from hard drive, and once that is working maybe an option in Puppy Installer to do it all automatically. I was always afraid of UEFI and secure boot because of the added headaches but it seems the only issue is that puppy doesn't mount the mmc drives on them, from what I can tell, I even tried using pmedia=atahd and pdev=mmpblk0 or whatever it's name is without success. will have to try these kernels by gyro and see if they help :smile: :sunglasses:

**Comment by gyrog** [comment]
To provide examples, I have uploaded 3 "mmc" kernels to [http://www.mediafire.com/folder/21fyvbi4xglau/kernels](http://www.mediafire.com/folder/21fyvbi4xglau/kernels).
huge-4.9.227-mmc-pae.tar.bz2 for BionicPup32
huge-4.19.128-mmc-64.tar.bz2 for BionicPup64
huge-4.4.227-mmc-pae.tar.bz2 for Xenialpup

The BionicPup kernels are option 2 with 'kernel/drivers/mmc/host/sdricoh_cs.ko' as the only module.

The Xenialpup kernel is option 3, with no 'kernel/drivers/mmc/host/' modules.
("CONFIG_MMC_SDRICOH_CS=y" worked without any other changes to DOTconfig.)

All of these kernels need an 'fdrv...sfs' to provide firmware.

**Comment by bkauler** [comment]
Thanks for the recommendation, I have changed these from "m" to "y":

CONFIG_MISC_RTSX_USB
CONFIG_MMC_REALTEK_PCI
CONFIG_MMC_REALTEK_USB

No firmware required. 

I am using the 5.4.x kernel in my EasyOS Buster-series, even though Debian Buster uses 4.19.x. There have been no issues using the 5.4.x kernel.

Compiling 5.4.84 right now, with those changes. .config file attached...

**Comment by bkauler** [comment]
Hmmm, what happened to the attached file, trying again...

Nup, cannot attach. It is gzipped, so should work. Clicking on "Preview" tab does nothing. Hmmm again.

Using SeaMonkey 2.53.5

**Comment by 01micko** [comment]
Barry just copy paste the text
