### ISSUE TITLE
FossaPUP

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1837]
I noticed that the author has asked on the forum for the RC to be thoroughly tested and I clearly understand.

This thread is just an idea **posted as a question**; thus does not expect any replies.

If the RC is posted as an RC on DistroWatch, would it attract many more tests that could prove helpful?

**Comment by mrfricks** [comment]
hi @CollaboratorGCM,
sorry for the late reply .... i did see this.
it is a good idea but i wasn't sure i could deal with anymore issues on top of what i was trying to fix in fossapup and the idea struck fear into me :)

**Comment by CollaboratorGCM** [comment]
Ha! Dont want a scare! Keep up the great work. I'm loving the current iteration you released.

Thanks for all your efforts, going forward!
BTW, where is the _**best**_ place, currently, to post issues we find in FossaPUP?

**Comment by mrfricks** [comment]
there's a thread on the new forum here https://puppylinux.rockedge.org/viewtopic.php?f=40&t=88
