### ISSUE TITLE
64bit WOOFCE Pups on "Enabled" Secure Boot PCs

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1839]
Are there instructions that ship as help file(s) with the 2020 WOOFCE PUPs explaining the steps to setup and register on a PC which has Secure Boot "enabled"? Or is there a Readme entry for such registration steps of the CER?

I know of FATDOG's webpage addressing this ability and have looked for similar documentation of WOOFCE Pups.

**Comment by gyrog** [comment]
You can find help for MOK Manager at  [http://www.fishprogs.software/puppy/frugalpup/frugalpup-mok.html](http://www.fishprogs.software/puppy/frugalpup/frugalpup-mok.html).
It's part of the "FrugalPup" help.

**Comment by 01micko** [comment]
There is also a wikka entry with links to @gyrog 's pages.

[FrugalPup at the wikka](http://wikka.puppylinux.com/FrugalPup_Installer)

**Comment by CollaboratorGCM** [comment]
I know how busy things are right now!

But, I wonder if on the WOOFCE list, there is a item about how/when to add MOK registration for its PUPs such that they will register and boot on Secure Boot enabled 64bit PCs as well.

Just a thought as I feel it may have been overlooked.

**Comment by gyrog** [comment]
@CollaboratorGCM,
I don't quite get what you are are on about.

If you install a Puppy using  any "FrugalPup" utility,
the first time you  boot it on a uefi machine (32bit or 64bit), with "Secure Boot" enabled,
the MOK registartion utility should be activated.
On subsequent boots of this Puppy, or any other Puppy installed with any "FrugalPup" utility,
should proceed directly to the "grub2" screen.
The MOK contained in "puppy.cer" needs to be registered only once on each  machine.

If you don't want to use "FrugalPup", you can provide the uefi booting support that is contained in "FrugalPup", by downloading "grub2-efi.tar.xz" from the "FrugalPup" download directory,
extracting it into your fat32 boot partition, and provoding an appropriate "grub.cfg" in the root of the fat32 boot partition.

**Comment by CollaboratorGCM** [comment]
Thanks. And, I get this. I am commenting about this as am hopeful that all WOOFCE PUPs going forward contains this support OOTB, rather than users (especially those coming over from MS/Apple/Others) needing to have knowledge to for an extra set of instructions to prepare their ISOs/PUP-distros.

Knowledgeable Linux personnel with 64bit experience will not have problems. But, we know others will. 
My concern is merely the ease of use, ease of boot with little to no knowledge excepting to merely register when it the UEFI request pop up at boot time. All of what is happening is to get tire-kickers to get PUP operational EASY as if encourages them to stay and contribute going forward. PUPs have been crafting such over the past years (yes I know we all know this).

My focus has been looking at how to make it all TOO simple for users to get past BIOS/UEHI to successful desktops as easy as can be possible; with as little operational questions to developers and support as is humanly possible. Doing this is a testament to what everyone here is doing while it also encourages many to continue its use once tested.

My PUP test in WOOFCE thus far is NOT generating a MOK capable PUP OOTB. That is the aim and am curious if this should be considered as a build ability for all 64bit PUPs?

I do understand how our past has led us to disabling Secure Boot. And now wondering if current technology such as yours should be part+parcel to WOOFCE. If the technology is already in WOOFCE, I have been missing it.

BTW, your wiki and your work (which I have followed for some time) is EXCELLENT with matching guiding screens. THANKS!!!

**Comment by gyrog** [comment]
@CollaboratorGCM 
Again, what do you mean booting Puppy OOTB?
Since Puppy is distributed as an iso file, the only thing I would call booting Puppy OOTB, would be to burn the iso to a CD and boot that.
Any other way requires either a "something" to create a bootable partition using the iso file, or a "something" that can "boot" the iso directly.
Either way it's the responsibility of the "something" to ensure MOK capability.

**Comment by CollaboratorGCM** [comment]
@GyroG, you are right! 

AND, thanks to you and others, the 2020 WOOFCE PUPs can also, now, be booted by a Boot Launcher via SuperGrub2 (SG2D). Now, this year, PUP users, myself included, can merely download the PUP ISO to a folder on the system (ie /boot-isos) and using SG2D, anyone can boot ANY of these PUPs and other ISOs in that folder without creating or exploding the ISO to any other media....**_with persistence!_** (Yes, I know you know this).

**This works fabulously for Secure Boot disabled PCs or BIOS PCs.**

FATDOG and your efforts with Frugalpup produce ISOs which when booted on Secure Boot enabled PCs will guide to MOK registration enabling **subsequent** booting for them to boot on 64bit PCs. You guys have solved this for your presentations. FATDOG ISO, as an example of what I am referring can be booted straight-away on any PC with Secure Boot Enabled or Disabled, from the same single ISO.

My references of late is whether WOOFCE generations going forward will incorporate these technologies into upcoming PUPs generated where new PUPs, without an afterthought on the part of a person creating a PUP, having to KNOW additional steps are required to run on a Secure boot enabled PC.

Currently, this is not present in the OOTB build of a WOOFCE PUP.

AGAIN, I KNOW how busy things are right now! But, am hopeful this we find a moment to bang your technologies into WOOFCE's build process.

I am hopeful this gives some clarity with what I am referencing. Thus the idea, here, is that any PUP generated from WOOFCE will boot on ANY 64bit PC whether Secure Boot is enabled or disabled with no user or developer special intervention for UEFI/BIOS changes.

As such, new users get past these boot-time issues and concentrate on mere desktop concerns. And acceptance into the PUP-fold become simple and easy with one less item to concern oneself.

I am still of the mindset that PUPPY Linux is the best Linux distribute for new users to acquaint themselves. Its simple, clean, and straight-forward, where possible.

**BTW:** I am not exactly sure how to simply include this within WOOFCE built PUPs.
