### ISSUE TITLE
xorg-autoconf fails in vmware

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1841]
@rizalmart 

as the title says xorg-autoconf fails in vmware and i'm getting a black screen with flashing cursor.
virtualbox & qemu seem to work fine.
added a quick fix which i'll put into fossapup as quite a few users try in a VM first. but will need looking at for a universal fix.
```
write_vmware(){

cp -r /etc/X11/xorg.conf.udev etc/X11/xorg.conf

}
```

**Comment by rizalmart** [comment]
> @rizalmart
> 
> as the title says xorg-autoconf fails in vmware and i'm getting a black screen with flashing cursor.
> virtualbox & qemu seem to work fine.
> added a quick fix which i'll put into fossapup as quite a few users try in a VM first. but will need looking at for a universal fix.
> 
> ```
> write_vmware(){
> 
> cp -r /etc/X11/xorg.conf.udev etc/X11/xorg.conf
> 
> }
> ```

@mrfricks 

Could you please post the generated xorg.conf  made by xorg-autoconf for vmware on FossaPup?
Also could you please post here the Xorg.0.log if you sucessfully start Xorg using xorg.conf.udev on vmware?

I think it seem to need a deeper analysis for vmware

**Comment by mrfricks** [comment]
@rizalmart 
here you go
[xorg-stuff.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/5012036/xorg-stuff.zip)
had a play and it seems it's this line that scuppers it.
```
	BusID       "0:f:0" #card0busid
```

**Comment by rizalmart** [comment]
@mrfricks I finally found the problem. The bus id  in xorg.conf was all decimal unlike in lspci which was hexadecimal. I tried to run pristine fossapup and configure xorg using xorg-autoconf. It failed to start xorg when I changed the busid from "0:f:0" to "0:15:0". The Xorg works. The fix was now on pulling request.

**Comment by mrfricks** [comment]
this is now working.  thanks @rizalmart
