### ISSUE TITLE
export XLIB_SKIP_ARGB_VISUALS=1

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1842]
in /etc/profile there's 
```
export XLIB_SKIP_ARGB_VISUALS=1 #rox crashes with DRI modules. solution:
```
is this still an issue? as it blocks true transparency in things like conky.

i've experienced no problems so far with it commented out.

**Comment by 01micko** [comment]
Probably not a good idea on older hardware or poor graphics. That said, if we can detect that a `kms` driver or a proprietary video driver is running at early boot then we can probably sed that 1 for a 0 (or just delete the line).

**Comment by dimkr** [comment]
#3867
