### ISSUE TITLE
/usr/share/X11/fonts/misc

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1856]
i had some issues in fossapup with certain apps not working (pmwget, rubix, xfreecell) . It turned out that xorg-autoconf doesn't read /usr/share/X11/fonts/misc which i presume is a cut down xfonts-base (usually 5-6mb)

this can be fixed by either moving /usr/share/X11/fonts/misc to /usr/share/fonts/X11/misc and symlinking 
```
ln -s /usr/share/fonts/X11/misc /usr/share/X11/fonts/misc
``` 
or by fixing xorg-autoconf .
xfonts-base  installs to /usr/share/fonts/X11/misc so rather than changing xorg-autoconf maybe the symlink in woofce is the best way.

**Comment by peabee** [comment]
Hi Phil @mrfricks 
Are you looking for this link to be part of rootfs-skeleton or for it to be created dynamically in 3builddistro ? e.g. /support/rootfs-hacks.sh
Does it only affect Ubuntu builds? Rubix gives the error for me in UPupEF but works fine in LxPupSc....
pmwget works OK for me - calls pmirrorget... don't have xfreecell.
I don't have a package called xfonts-base......

**Comment by mrfricks** [comment]
hi @peabee 
it will affect all future builds that use xorg-autoconf .  
we already have this folder in rootfs-skeleton(a cut down xfonts-base) so we don't need the actual xfonts-base package which is 5-6 mb (I presume).

it either just needs moving and symlinking, or xorg-autoconf needs changing to read the folder path.

**Comment by rizalmart** [comment]
@mrfricks /usr/share/X11/fonts/misc is now added to xorg-autoconf. Now on pull request

**Comment by 01micko** [comment]
@mrfricks does @rizalmart 's change fix your issue? I'm going to merge it anyway as it is a better idea than symlinking.
