### ISSUE TITLE
FosssaPUP consideration

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#1868]
**Hello @666PhilB. @ETP** has introduced some worthy ("forward thinking") utilities which, not only, support your contributions in the FossaPUP desktop but also adds things which are a benefit to today world of users.

The benefit **is not** a novelty, rather, it is useful administrator messages which has "value" should something monitored goes awry.

Further he adds a feature making the PC more useful in the services we use for OTA TV broadcast as well as other media tools that we use. Thus, seemingly with one of his tools he is bringing forth the ability for users to combine PC, radio, and TV into the swell of services that keeps expanding as technology advances us into the future.

Because this is so forward thinking I wonder if as you march toward a General Availability (GA) Release, you "might" give the community something to think about by not only releasing a GA, but also side by side release a multimedia version, as well which is the GA combined with what @ETP presents. This would gives the community 2 simultaneous OOTB FossaPUP solutions (kinda similar to Ubuntu announcements) where users would pound and generate feedback.

This way, the vast Puppy community could not just see what they expect along the traditional lines, but also could test and evaluate taking advantage of a multimedia solution as well.

It would have a secondary benefit for development to see the community reaction to this kind of built-in use of their PCs from those who would respond, albeit positively or negatively.

Each generation, over the years, we have seen user reactions to things which has furthered the current advancements PUP has had, especially, over the last decade. 

This is just a thought that might prove a new path as users response and/or contributes going forward. And it gives development a sense of benefit, at the same time.

I know this is easier said than done (or it may be as simple of a WoofCE generation tick), but, thought it timely to lay this out here in WoofCE for consideration.

His work, as I am sure you may know, **[is here](url=https://forum.puppylinux.com/viewtopic.php?f=91&t=636&p=3616)**

**Comment by 01micko** [comment]
This is way beyond the scope of woof-CE and should be posted in the forum.
