### ISSUE TITLE
xorg-autoconf does not respect pkeys= kernel switch

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1874]
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/sbin/xorg-autoconf
for @rizalmart 
pkeys=xx on kernel line sets /etc/keymap to xx but xorg-autoconf does not use this value when constructing /etc/X11/xorg.conf 
should be
Option      "XkbLayout" "xx"

**Comment by jamesbond3142** [comment]
On Sat, 19 Sep 2020 02:39:21 -0700
PB <notifications@github.com> wrote:

> https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/sbin/xorg-autoconf
> for @rizalmart 
> pkeys=xx on kernel line sets /etc/keymap to xx but xorg-autoconf does not use this value when constructing /etc/X11/xorg.conf 
> should be
> Option      "XkbLayout" "xx"
> 

It has been a while since I looked at this, but as far as I remember pkeys is meant to set the keyboard layout for the console. Xorg should have its own settings, if not for the simple reason that Xorg has a lot more keyboard layout and variations compared to what pkeys can support.

-- 
James B

**Comment by peabee** [comment]
Hi James
The report came from @Norgo who expects pkeys to have more general applicability - which is sort of borne out by the wiki which does not mention any constraint to just the console:
http://wikka.puppylinux.com/BootParametersPuppy
http://wikka.puppylinux.com/BootParametersPuppy1

**Comment by rizalmartin** [comment]
> https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/sbin/xorg-autoconf
> for @rizalmart
> pkeys=xx on kernel line sets /etc/keymap to xx but xorg-autoconf does not use this value when constructing /etc/X11/xorg.conf
> should be
> Option "XkbLayout" "xx"

@peabee 
@jamesbond3142 

This issue is now fixed. It is now on PULL REQUEST. Please merge it, thanks

**Comment by jamesbond3142** [comment]
> Hi James
> The report came from @norgo who expects pkeys to have more general applicability - which is sort of borne out by the wiki which does not mention any constraint to just the console:
> http://wikka.puppylinux.com/BootParametersPuppy
> http://wikka.puppylinux.com/BootParametersPuppy1

Yeah but it doesn't make sense. Imagine you install puppy with pkeys in the boot parameter.
The first time it boots up you get QuickSetup asking for keyboard configuration.
You choose it, and shutdown, creating a savefile.
Next time it boots up, the chosen keyboard layout from QuickSetup is overwritten again from pkeys.

Unless you're saying that xorg-autoconf is only created once? But when?

**Comment by norgo70** [comment]
I modified xorg-autoconf and  this is working for me in [SLK64-2023.04](https://smokey01.com/norgo/slacko/064/064.php)
[xorg-autoconf.diff.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/13232910/xorg-autoconf.diff.txt)
