### ISSUE TITLE
Make `new2dir` support more build methods

### ISSUE THREAD

**Issue by sc0ttj** [puppylinux-woof-CE/woof-CE#1904]
Currently the `new2dir` script must be used like so: `new2dir make install`

It checks to make sure ` make install` is indeed what it was passed.

```
if [ "$1 $2$3" != "make install" ];then #180915
```

I changed this to 

```
if [ "$1 $2$3" != "make install" ] && \
   [ "$1 $2 $3 $4" != "ninja -C build install" ] && \
   [ "$1 $2 $3 $4" != "ninja -C _build install" ] && \
   [ "$1 $2$3$4" != "ninja install" ]
then #180915
```

And this enabled me to package up some stuff that was built using `ninja`. 

It should should be easy enough to do the same for `meson` and `samurai` (a ninja-compatible build tool).

**Comment by 01micko** [comment]
No worriies, why don't you include fixes for meson and samurai and issue a PR?
