### ISSUE TITLE
Should Woof-CE now be licensed under GPL v3

### ISSUE THREAD

**Issue by bigpup1** [puppylinux-woof-CE/woof-CE#1947]
As I understand it.
GPL v3 is much improved over GPL v2
https://www.gnu.org/licenses/quick-guide-gplv3.en.html
Seems things that are wrong with GPL v2 have been corrected by GPL v3.

**Comment by 01micko** [comment]
Hi @bigpup1 

Not IMO. As a matter of fact Linus uses GPLv2 for the Linux Kernel. See [the kernel archives FAQ](https://www.kernel.org/category/faq.html).

**Comment by CollaboratorGCM** [comment]
I wonder if the question should be reworded: Should WoofCE upgrade its GPL
based upon new V3 benefits

I dont have any position, personally. If development is NOT restricted,
would we lose or benefit by the upgrade?

**Comment by dimkr** [comment]
License compatibility could be an issue. Busybox is GPLv2 - is the combination of GPLv3-licensed woof-CE bits and Busybox in initrd.gz legal?
