### ISSUE TITLE
Sound settings being lost after reboot

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1949]
I am getting reports (confirmed by my own tests) that for recent builds, sound settings are being lost after a reboot and are reverting to their default values (BTW the volume default also seems to have changed from 80% to 65% as a possible clue)....
I think @rizalmart has made recent changes in the sound area?

**Comment by rizalmart** [comment]
@peabee did you change computer or add/remove a sound device? Alsa settings will revert to default if there's a change on sound device detected on boot

**Comment by peabee** [comment]
No - no changes whatsoever - happens on more than one computer .....

**Comment by rizalmart** [comment]
> @peabee did you change computer or add/remove a sound device? Alsa settings will revert to default if there's a change on sound device detected on boot

My apologies for this statement. Upon checking my commits on alsa. Alsa auto configuration is not yet implemented. I just add support for pulseaudio in alsa service script, the alsa stream will redirected to PulseAudio if pulseaudio was installed and also implement hot restart of alsa

**Comment by rizalmart** [comment]
> @peabee did you change computer or add/remove a sound device? Alsa settings will revert to default if there's a change on sound device detected on boot

@peabee 

My apologies for this statement. Upon checking my commits on woof regarding alsa. The auto configuration is not yet implemented. I just add support for pulseaudio in alsa service script, the alsa stream will redirected to PulseAudio if pulseaudio was installed and also implement hot restart of alsa

**Comment by CollaboratorGCM** [comment]
@peabee  ... Confirmed! I thought it was my imagination up until now. I have ONLY an HDMI cable to the 3 PCs and this happens consistently although I rarely reboot them. Requires manual resetting, again, upon each reboot.
P.S. And YES, sessions are save upon shutdown before reboot.

**Comment by rizalmart** [comment]
This link might help
[Woof-CE search link asound](https://github.com/puppylinux-woof-CE/woof-CE/search?q=asound&type=code)

**Comment by peabee** [comment]
I have created savefolders after setting volume to 100% for pristine frugal installs of UPupBB (old Woof-CE build which doesn't have problem) and UPupGG which does have the problem....
I notice that UPupBB has /etc/asound.state (762 lines) whereas this is missing in UPupGG
UPupGG does have /etc/asound.conf which UPupBB doesn't but this is just a small file of 3 lines

**Comment by peabee** [comment]
Pretty sure the problem is caused by commit:
https://github.com/puppylinux-woof-CE/woof-CE/commit/07243a4be599b2b83a43315c8b8b8416d761fbf8
by @rizalmart 
which changed /etc/init.d/10alsa

Proved by reverting the 10alsa in UPupGG to that from UPupBB (using a ydrv) when /etc/asound.state was created and was stored in the save folder and the volume was set to the correct value after a reboot.

**Comment by rizalmartin** [comment]
> Pretty sure the problem is caused by commit:
> [07243a4](https://github.com/puppylinux-woof-CE/woof-CE/commit/07243a4be599b2b83a43315c8b8b8416d761fbf8)
> by @rizalmart
> which changed /etc/init.d/10alsa
> 
> Proved by reverting the 10alsa in UPupGG to that from UPupBB (using a ydrv) when /etc/asound.state was created and was stored in the save folder and the volume was set to the correct value after a reboot.

@peabee 
That will work if pulseaudio executable binary was present. Do you have pulseaudio binary file installed?

**Comment by peabee** [comment]
Definitely NO pulseaudio executable binary

**Comment by rizalmart** [comment]
> Definitely NO pulseaudio executable binary

Did you try to run this command on your system?

`which pulseaudio`

**Comment by peabee** [comment]
Of course - no response....

**Comment by peabee** [comment]
Syntax error line 80 - delete $

**Comment by rizalmartin** [comment]
> Of course - no response....

Then it should be skipped the asound.conf routine for pulseaudio if no pulseaudio was installed

**Comment by peabee** [comment]
10alsa could not run at all due to the syntax error on line 80
