### ISSUE TITLE
Support for periodic fstrim

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#1959]
Chrome OS does this even on low-end ARM Chromebooks, and this could extend the lifespan of cheap eMMC storage.

**Comment by rizalmart** [comment]
I'm highly doubt about periodic fstrim. I think should be add as an option. Puppy has so called PUPMODE 13. The working data was cache in ram but it saves the working data from ram to save file periodically depending on user settings. This greatly reduces the number of writes of a flash media. However it has disadvantage it requires a good stable power source or good battery. Otherwise the latest user data on ram will be lost if power was lost

**Comment by dimkr** [comment]
PUPMODE 13 means less writing to the SSD, but more data written every time. The bottom line - more writing, or less writing, is an empirical question.

Also, I'm not sure how save files interact with TRIM. The whole idea of an SSD is to move files around as they change, so the flash cells that store a frequently changing file don't fail before all others. If all files are inside a save file, and it's a big file, the SSD has less freedom to move the file around, and TRIM is less likely to kick in. Is PUPMODE 12/13 really safe for SSDs? I don't know.

Finally, PUPMODE 13 is not the case I'm worried about. For example, PUPMODE 2 doesn't fstrim periodically like other distros.

**Comment by gyrog** [comment]
How does this relate to booting with "pfix=trim"?

**Comment by dimkr** [comment]
@gyrog According to https://wiki.archlinux.org/index.php/Solid_state_drive#Periodic_TRIM, the `discard` mount option (aka `pfix=trim` has its cons.

**Comment by gyrog** [comment]
"pfix=trim" is also honoured by the 'init' script only, so unless your SSD is mounted by 'init', and left mounted, 'discard' won't be active.

So, what would it need?
A "cron" job to run weekly, or use "Puppy Event Manager"?
A dialog to configure it somewhere, or competely automatic?

Are you working on code for this?

FYI, the 'init' script has some code to workout if a partition is on an SSD.

Probably be useful if there was a "flag" that the 'init' script could check before the save-layer is available
so it can ignore any "pfix=trim".

**Comment by dimkr** [comment]
> Are you working on code for this?

Not yet. I'm not sure how I want  to do this.

**Comment by dimkr** [comment]
This is fixed by #2679, when `BUILD_ISO=no FRUGALIFY=yes`. I don't care about ISO images anymore, so I'm closing this.
