### ISSUE TITLE
merging init-experiment

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1963]
@gyrog has made some great improvements to saving with the introduction of [SAVESPEC](https://forum.puppylinux.com/viewtopic.php?p=10002#p10002) file. Since he hasn't committed to the `init-experiment` branch for around 3 weeks then I think it's time to merge it into testing and deal with the fall out.

Some of the fallout _may_ be conflicts in some of the recent pull requests. @dimkr @rizalmart  @sc0ttj  and @rserwin1 have PRs open on `testing`. It is not my intention to cause pain but I think @gyrog 's work should take priority since his changes in init have really improved reliability in booting off of removeable media (USB sticks, sd/mmc cards and booting from ISO from HDD or USB) and the `SAVESPEC` facility is the "icing on the cake".

If your PRs are affected (many wont) please don't hesitate to resolve conflicts an re-issue or update them. I will be going over some of them today but then I will be offline for over a week, probably until new year. Of course there are others here that have full write access to `woof-ce` so you folk can merge any of these as you see fit.

Merry Christmas :santa: :christmas_tree: :snowman_with_snow: :penguin:

**Comment by dimkr** [comment]
Thanks for the heads up @01micko, #1948 won't conflict, unless there are new cases where PUPMODE=6 needs to be handled differently. I'll take a more serious look later.

**Comment by 01micko** [comment]
Anyway, I'm back and merged a lot today.. only a few outstanding PRs left now so closing.
