### ISSUE TITLE
Missing source code for Puppy packages

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#1973]
- [x] powerapplet_tray >2.7
- [x] pngoverlay-cairo
- [x] pngoverlay-gtk2
- [x] losetup-222
- [x] pm13tray

**Comment by 01micko** [comment]
Here it is..
[powerapplet_tray-2.7-petbuild.tar.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/5753253/powerapplet_tray-2.7-petbuild.tar.gz)

**Comment by dimkr** [comment]
Thanks @01micko!

**Comment by dimkr** [comment]
@wdlkmpx maybe you know where I can find some of these

**Comment by woodenshoe-wi** [comment]
I think the source code for pngoverlay-cairo is in the first comment of issue #1470

**Comment by 01micko** [comment]
https://github.com/puppylinux-woof-CE/petbuilds/tree/generic/basic/pkgs/aaa_pup_c

That has pngoverlay-cairo, pngoverlay-gtk and pm13-tray as well as some others.

losetup-222 is actually losetup-2.22 from util-linux. ~~No source or build script has ever been posted AFAIK, but it is statically built.~~
See next..

**Comment by 01micko** [comment]
losetup-222 buildscript (with link to src) and patch see 44e15f2

**Comment by dimkr** [comment]
Thanks! I'll re-open this issue if I find more packages like this.
