### ISSUE TITLE
Boot times are slow because of many sleep calls

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#1991]

**Comment by 01micko** [comment]
Not just sleep, but many external calls. POSIX shell could be utilised a lot more IMHO.

**Comment by dimkr** [comment]
Partially fixed by #1995, which probably removes the biggest delay during the init process. I'll do some profiling of rc.sysinit with strace -tt, to see what other low hanging fruits can be fixed without destabilizing Slacko 7.0.

**Comment by bigpup1** [comment]
A lot of those sleep commands where put into code for older computers.
Puppy was doing things so fast, that the older hardware was not keeping up with totally completing stuff, before going to the next.
This is probably not so much of an issue anymore, with newer computers, that have faster hardware.
But do not go overboard with changing stuff.
Puppy still needs to support older computers.

**Comment by dimkr** [comment]
#1995 is safe because it keeps that `sleep 5`. It only makes it happen in the background, and lets the boot process continue, so the desktop is ready by the time the internet connection is up.

I'm thinking - maybe the other `sleep`s can be restricted to x86, and skipped on x86_64 and ARM.

**Comment by 01micko** [comment]
> I'm thinking - maybe the other `sleep`s can be restricted to x86, and skipped on x86_64 and ARM.

Hmmm.. maybe aarch64 instead of arm - or at least _some_ additional condition - just considering the slow case of pi-zero.

**Comment by dimkr** [comment]
The additional condition can be ARMv7. Pi Zero and 1 are both ARMv6, and the ARM Chromebooks I'm targeting are ARMv7, like the other Pis (newer Chromebooks are AArch64).
