### ISSUE TITLE
GRUB2 Support needed

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2003]
We should add full GRUB2 to 2021 WoofCE PUP generation: The utilities are solely needed. We have utilities for GRUB4DOS, but have overlooked those same needs for GRUB2 needs.

**Comment by 01micko** [comment]
At this stage, frugalpup by @gyrog can install grub2, with secure boot alongside windows or another Linux distro on the hard drive or create a frugal install to USB or SD/MMC card. Closing.
