### ISSUE TITLE
CI that builds Slacko from testing

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2025]
#1948 adds a CI flow that runs woof-CE from start to finish, including kernel-kit (and my woof-CE fork uploads bootable images to https://github.com/dimkr/woof-CE/releases, so I can test my changes before I open PRs to woof-CE).

It would be nice to have something like this for Slacko, which AFAIK gets built from testing, the way it is and without manual intervention during the build. CI is a huge time saver for developers, especially when it's a small team.

More ideas that I have in mind:

- Publish a GitHub release every time a tag of the form `slacko-%d` is created
- Publish a GitHub pre-release every time a tag of the form `slacko-%d-beta` is created
- Boot Slacko in qemu, get a screenshot and compare it to what Slacko is supposed to look like

**Comment by 01micko** [comment]
This is interesting and #2026 will be getting pulled shortly. I had no idea about CI and have read a bit about it now.

**Comment by 01micko** [comment]
I can see this being very useful when slackware-15.0 lobs onto the linux scene and automated builds of slacko64-8.0 (or whatever version) can be built remotely and tested locally in initial development stages.

**Comment by dimkr** [comment]
In addition, we can use CI to maintain existing Puppies. For example: release a new Slacko 7.0.x every month, as a GitHub release that contains the ISO and the devx, incorporating all Slackware package updates and woof-CE changes. My idea, for the ARM Chromebook, is to have an "over-the-air" update mechanism that pulls the latest release from GitHub, with all the latest security fixes and bug fixes.

If we standardize on letting CI produce the "final" version of each Puppy, this could be a great way to keep all "official" Puppy versions (Fossa, Slacko, etc') reproducible and easy to maintain within the woof-CE repo, without manual intervention or hacks in the build process.

**Comment by 01micko** [comment]
I notice ibiblio takes an age to authenticate - it may be useful to change all default pet repos to nluug.

**Comment by dimkr** [comment]
Yesterday I had a 1download that took way more than one hour, with either ibiblio or nluug. Slackware has much faster mirrors in https://mirrors.slackware.com/mirrorlist/.

Luckily, local-repositories is cached between CI runs, so slow mirrors shouldn't be a huge problem. But fast mirrors are good for users too.

**Comment by dimkr** [comment]
@01micko Would you like me to add something that publishes a GitHub release once a week or month? This will create a tag, and allow people to try the next Slacko and the current state of the testing branch.

**Comment by 01micko** [comment]
Not yet. There are a few issues when looking at the logs - mostly 3builddistro
- kernel modules don't get renamed
-  /bin/ash not in ubuntu
Perhaps a few other issues to fix

**Comment by 01micko** [comment]
Ah, see you're onto it!

Just have to fix `pkg`

![s64-19](https://user-images.githubusercontent.com/1019119/106532218-7d06b700-653b-11eb-850d-bd6b0b1c13c1.jpg)

**Comment by 01micko** [comment]
Ok, I think the CI will handle pkg ok now.

**Comment by 01micko** [comment]
```
Processing cups
 processing cups-2.1.4-x86_64-1.txz
 executing (Slackware) install script
'/home/runner/work/woof-CE/woof-out_x86_64_x86_64_slackware64_14.2/packages-slacko64/cups/usr/share/pixmaps/cups.png' -> '/usr/share/icons/hicolor/64x64/apps/cups.png'
 executing packages-templates/cups_FIXUPHACK
/home/runner/work/woof-CE/woof-out_x86_64_x86_64_slackware64_14.2/packages-templates/cups_FIXUPHACK: line 86: pngtopnm: command not found
/home/runner/work/woof-CE/woof-out_x86_64_x86_64_slackware64_14.2/packages-templates/cups_FIXUPHACK: line 86: pnmtopng: command not found
```

Ubuntu host misses netpbm?

Also `Pkg` installation is still broken - maybe need an absolute path. Soon I'll get to it. 

```
cp: target '../../woof-out_x86_64_x86_64_slackware64_14.2/sandbox3/rootfs-complete/' is not a directory
Pkg was NOT installed! 
```

**Comment by 01micko** [comment]
WOOHOO! :homer:

```
--2021-02-02 02:54:02--  https://github.com/puppylinux-woof-CE/Pkg/archive/master.zip
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/puppylinux-woof-CE/Pkg/zip/master [following]
--2021-02-02 02:54:02--  https://codeload.github.com/puppylinux-woof-CE/Pkg/zip/master
Resolving codeload.github.com (codeload.github.com)... 140.82.112.10
Connecting to codeload.github.com (codeload.github.com)|140.82.112.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: 'master.zip'

     0K .......... .......... .......... .......... .......... 2.74M
    50K .......... .......... .......... .......... .......... 3.40M
   100K .......... .......... .......... .......... .......... 1.20M
   150K .......... .......... .......... .......... .......... 5.33M
   200K .......... .......... .......... .......... .......... 7.88M
   250K .......... .......... .......... .......... .......... 2.58M
   300K .......... .......... .......... ..                    36.7M=0.1s

2021-02-02 02:54:03 (3.00 MB/s) - 'master.zip' saved [340619]
```

**Pkg installed OK** 

6ec501a fixed it.. probably could have left the git download routine alone but the zip method is simple enough.
