### ISSUE TITLE
Add automated testing of Slacko64 images produced by CI

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2027]
#2025 is fixed, but we want to ensure that the images we build are bootable and working, because making sure that 3builddistro succeeds is not enough.

For example:
- Take a screenshot and compare it to a Slacko64 7.0 screenshot
- Automate boot, do some visible change like changing the theme, reboot with creation of a savefile, and take a screenshot

**Comment by 01micko** [comment]
Probably should bring dpup buster up to date in woof and add that too. @mrfricks  might want to apply the same to ubuntu derivatives.

**Comment by dimkr** [comment]
My plan is to do set up a second CI job with dpup bullseye. My ARM Chromebook port is a dpup and I want to do a 1:1 (or, as close as possible) x86_64 version, with the new PUPMODE 6, etc'. It will be easy to test: there's no save file (always writing to a partition) and it should be easy to make it run a SSH server on first boot, then do the testing over SSH.

**Comment by CollaboratorGCM** [comment]
Hi @dimkr. Just a question for a build of SSH on Firstboot. Is this step intended to be used for a cloud system? Will it transmit sound?

in the real console world of operation, we get to see the video and the audio and the user behavior for desktop use. Most PUPs have had this as their expected use.

I know the advantage of SSH, though; but there still remains the 99 & 44/10 percent of our users where the desktop at the console will be our community with a plethora of video cards, monitors, and audio units that they will use for the experiences sort.

I am NOT discouraging SSH, just pointing to considerations. 

If I can offer an idea, In the PUP's FirstRUN (the 2 screens) there could be an options for SSH activation. That will require a FirstRUN sequence change should you take that approach.

Another option, of course, is to have a "Developer's Build" in the WoofCE generation process which would build-in DEVX, SSH, along with the tools that developers use regularly.

Trying to be helpful.

**Comment by dimkr** [comment]
> Hi @dimkr. Just a question for a build of SSH on Firstboot. Is this step intended to be used for a cloud system? Will it transmit sound?

Nope.

My idea is to auto-start a SSH server (only if a special "developer mode" is active), then use it to upload and run a VNC server, or use X11 forwarding to test GUI applications.

Another option is to automate keyboard and mouse input somehow, but I'm not sure exactly how to do it in a way that requires only minimal changes to Puppy itself. One of the ideas I had in mind is to use a browser-based VNC or RDP client in the style of  https://guacamole.apache.org/, connect to a VM running Puppy, then run a Selenium-based test script on the host.

I definitely need to think how to do this, but I'm sure there's a cheap and effective way to do at least some basic sanity testing of woof-CE's output.

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/pull/1948 goes through automated testing in every push (look at the ci/ directory).

For example, I had a bug where petbuild output is cached between CI runs, and when the cache gets unpacked after a successful build, the ownership of files changes to the UID:GID of the regular user on the machine that runs CI. The ownership of /root has changed, and Firefox refused to start. Therefore, the automated tests start Firefox and the new tab page, to make sure Firefox is able to start and the Puppy-specific settings (like disabling the heavy "new tab" page) are working.
