### ISSUE TITLE
Improving internationalization of puppy core desktop files

### ISSUE THREAD

**Issue by rizalmart** [puppylinux-woof-CE/woof-CE#2037]
Upon reviewing the Puppy language packs due to 
my boredom. I noticed that almost all language packs on puppy required run post-install script to modify puppy components to achieve localization. It's understandable on ROX part, however the part that is not a good idea was to modify the desktop files for the sake of translation. Puppy core applications require modifying the desktop file to localize it instead of put the translation on the desktop file like this
`
[Desktop Entry]
Name=Document
Name[es]=Documentos
`
Also some puppy desktop files for menus in /usr/share/desktop-directories was not yet added locales. Putting this translations on desktop files will make localization faster and consistent. This makes lessen scripting for translation.

**Comment by dimkr** [comment]
This one is almost fixed.

Packages built from source during 3builddistro use unmodified .desktop files (except the categories and icon, mostly), and this issue will be fixed when old PET packages without `[$lang]` fields go extinct.

**Comment by dimkr** [comment]
Closing this.

Locales are included in dpup OS (https://forum.puppylinux.com/viewtopic.php?f=33&t=2495) by default, and I switched from English to German and Spanish. Menu entries and menu tooltips are translated when the .desktop file has translations.

This issue is fixed, when Puppy has locales.
