### ISSUE TITLE
CI job that builds Slacko 8.0 with weekly releases

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2046]

**Comment by dimkr** [comment]
@01micko WIP in the ci branch: manually-triggered builds have a "release name" parameter and on successful build, a new tag+release should be created with the ISO and devx:

![Screenshot 2021-02-20 at 16 03 35](https://user-images.githubusercontent.com/1471149/108598258-459a6600-7395-11eb-842f-e3d22b514db9.png)

**Comment by 01micko** [comment]
Cool! I noticed my push build stopped at `disktype`, I guess ibiblio was having troubles at the time.

**Comment by dimkr** [comment]
ibiblio times out very very very often. To compensate for that, I separated caching of petbuild sources from other cached directories, and a cached sources directory can be safely shared between builds on different branches (unlike petbuild output, for example).

After one successful build on each branch, CI is stable and fast, but I think I'll increase the timeout and add more retries in all petbuilds.
