### ISSUE TITLE
Remove libtool .la files

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#2048]
Apparently these are obsolete so maybe they should be deleted?

I refer to [this post](https://www.linuxquestions.org/questions/slackware-14/slackware-current-missing-la-files-4175628441/#post5847597) on LQ slackware forum..

Plus, many packages come with newer stuff than autotools, like cmake, ninja, waf and others.

Thoughts?

**Comment by 01micko** [comment]
Hmmmm was having trouble building abiword-3.0.4 but removing _all_ .la files on the system fixed it :thinking:

**Comment by 01micko** [comment]
Thoughts @dimkr ?

**Comment by dimkr** [comment]
Let's delete them!

**Comment by 01micko** [comment]
global delete when in 3builddistro should do it.

**Comment by 01micko** [comment]
Ok, proposed simple patch (maybe add `-maxdepth 4` ?)

```patch
--- 3builddistro.orig	2021-02-22 18:55:25.487441955 +1000
+++ 3builddistro	2021-02-22 19:10:19.794094446 +1000
@@ -294,6 +294,9 @@ if [ "$BUILD_DEVX" = "yes" -o "$PETBUILD
 	echo
 fi
 
+echo "removing obsolete libtool *.la files"
+find sandbox3/rootfs-complete/ sandbox3/devx/ -type f -name "*.la" -delete # delete old libtool files
+
 QEMU=`command -v qemu-${WOOF_TARGETARCH}-static`
 [ -n "$QEMU" ] && install -D -m 755 $QEMU rootfs-complete/${QEMU}
 
```
