### ISSUE TITLE
PPM v2.5 doesn't restart after update package database

### ISSUE THREAD

**Issue by norgo70** [puppylinux-woof-CE/woof-CE#2049]
PPM v2.5 doesn't restart after update package database
Affect the update button in the PPM main window only (between help and configure PM button)

PPM launch via terminal is showing following error message
sh: restart_ppm: command not found

function restart_ppm will be called (see line 445) pkg_chooser.sh

here the modification I did to fix it

/usr/local/petget/pkg_chooser.sh (line 224)

-export -f pkg_info do_install change_mode
+export -f pkg_info do_install change_mode restart_ppm

**Comment by dimkr** [comment]
Thanks for the detailed bug report @norgo70!
