### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#206]
I intend to add some files for this over the coming weeks.

Many of zigbert's new gui are already touchscreen friendly (in a size sense)

**Comment by mavrothal** [comment]
Does this one needs to be still open?
GUI-wise is probably OK but should we start including evtouch, tslib libinput/xinput in puppies as standard?

**Comment by 01micko** [comment]
Yes they are all there anyway. The BIG problem is Xorgwizard #583

**Comment by mavrothal** [comment]
Right. But if we can detect the presence of a touch screen we can deactivate xorgwizard (with a relevant message) or see if we can only work around the input devices section of the server. 
Maybe close and open another or just reference #583 ?

**Comment by dimkr** [comment]
IMHO, the effort required to disable xorgwizard under one use case is very close to the effort required to remove it entirely.

**Comment by 01micko** [comment]
Closing this - dealt with in other issues.
