### ISSUE TITLE
QEMU

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2069]
There is an outstanding request on the forum **[here](https://forum.puppylinux.com/viewtopic.php?p=18159#p18159)** asking for an updated QEMU to be awarded. 

As the WoofCE teams moves to it upcoming distro versions, could v5.2 be added?

Thanks for considering.

**Comment by 01micko** [comment]
It's in the next iteration of slacko64-8 (devx), works ok, so closing
