### ISSUE TITLE
Applications running as spot use the default GTK theme

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2074]
Maybe only true to my dpup, Firefox or GTK 3

**Comment by rizalmart** [comment]
> Maybe only true to my dpup, Firefox or GTK 3

Did you put gtkrc file on /home/spot?
gtk3 themes can be set by default by putting gtk.css on /etc/gtk-3.0

**Comment by dimkr** [comment]
> Did you put gtkrc file on /home/spot?

Nope.

As a user, I expect applications to use the theme I chose, and the fact my browser runs as spot is an implementation detail.
