### ISSUE TITLE
Missing icons in the Puppy Standard icon theme

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2082]
A GTK 3 build of PCManFM looks really bad and icons like the new tab icon are missing. The problem is fixed by adding `Inherits=Adwaita,Hicolor` to index.theme, but I'm not sure if this is the right way to solve this.

@zigbert @01micko Ideas?

**Comment by 01micko** [comment]
Fix the themes I reckon. I'll take a look tonight or tomorrow. `PMaterial` is relatively complete.

edit: What about `Inherits=PMaterial,Hicolor` for now ?

**Comment by dimkr** [comment]
> edit: What about Inherits=PMaterial,Hicolor for now ?

Works! I think I'll change the icon theme of Dark Gray to PMaterial then, if that's the theme that works best.

**Comment by 01micko** [comment]
I'll get Puppy Standard and Puppy Flat up to speed this weekend.

**Comment by dimkr** [comment]
Honestly, I think we're better have one theme that works great across GTK 2 and 3. The variety is not very big, and all SVG themes are simple and flat, so a user that doesn't like this style won't be satisfied with any of them.

I thought "Puppy Standard" was the best candidate for this, but now I understand that PMaterial is the most complete theme. I'll do some extra testing, to see if I can spot more missing icon bugs (other than the Geany menu bug, which remains a mystery).

**Comment by dimkr** [comment]
Wow, PMaterial solves the Geany icons problem!

**Comment by 01micko** [comment]
Geany menu? see my recent commits.

**Comment by dimkr** [comment]
efc344ef0d1fd121c12d6338100de948d5302644 explains everything.

The issue is not really solved, but I don't see missing icons with PMaterial, and that's good enough.

**Comment by 01micko** [comment]
Nearly there with `Puppy Standard`. It's tedious!

`Puppy Flat` will be at a later date.

Also see 79356aa

**Comment by 01micko** [comment]
All 3 icons themes should be ok now.
```
[Icon Theme]
Name=Puppy Flat
Inherits=PMaterial,Hicolor
Comment=A GTK Icon Theme by zigbert, technosaurus and 01micko
```
flat and material are a lot closer in design.

**Comment by dimkr** [comment]
Thank you! Amazing work.
