### ISSUE TITLE
*.desktop files in Puppy is somewhat wrong

### ISSUE THREAD

**Issue by zigbert** [puppylinux-woof-CE/woof-CE#2089]
Looking into the *.desktop files in /usr/share/applications is a bit messy. Many different ways of using the terms
Name=
GenericName=
Comment=

Some times all 3 have hold the same info, sometimes not... This hurts the menu. I have done some cleanup to make it look better in the Menumanager, but the problem is more fundamental... Puppy is using the "Name=" tag when building the menus, and it holds both the name of the app, and a brief description. This is the case for Puppy apps, but not when we install others like libreoffice, Gimp, etc. They follow the standard that "Name=" holds the name, and the description is in the "Comment=".

In Puppy, No tag holds only the name of the app, so I have used the "GenericName=" to do that when possible. This will of course also be wrong when comparing to EG. Gimp where generic name is 'Image editor'.

Would it be possible for us to use the "Name", "GenericName" and "Comment" correctly, or do we have to live with this?... not a showstopper, but I am looking into improving the Puppy desktop, and this is one of the weakest points.

**Comment by 01micko** [comment]
Yes, I did notice this. Part of the problem is `dir2pet` which I'll keep on  my radar. It is over simplified. Thanks for the effort on this @zigbert !

**Comment by gyrog** [comment]
The other part is simply contributors creating crappy .desktop files. I just grab a copy of one from the target menu category and edit it.
My 'frugalpup.desktop' has exactly this problem.

@zigbert ,
If I change 'frugalpup.desktop' to have:

Name=FrugalPup
Comment=flexible frugal installer
GenericName=Puppy Linux installer

Would that be proper?
What would the menu entry look like?

**Comment by dimkr** [comment]
Can we change the menu generator to put "$name $comment" in the menu entry instead of "$name", or just "$name" if the name contains spaces (backwards compatibility)?

**Comment by zigbert** [comment]
> Can we change the menu generator to put "$name $comment" in the menu entry instead of "$name", or just "$name" if the name contains spaces (backwards compatibility)?

I have thought the same way - should be doable... but jwm-xdgmenu would require some hacking...
Who knows C?

I can update the *.desktop files in Woof-CE

As mick pointed out, we need to update dir2pet - is it more?

**Comment by dimkr** [comment]
> I have thought the same way - should be doable... but jwm-xdgmenu would require some hacking...
> Who knows C?

I can do it, I fixed two bugs there recently. And because now we have petbuilds during 3builddistro and automated releases, it should be very easy to change something in jwm-xdgmenu and build another Slacko 8.0 pre-alpha we can play with.

**Comment by zigbert** [comment]
I have updated the *.desktop files inside Woof-CE. BUT, I'm not the man to tell what's right and what's wrong, so please correct me...

**Comment by dimkr** [comment]
#2096 should fix most remaining issues.

**Comment by dimkr** [comment]
Looks great!

The menu entry specifies the application name:

![network](https://user-images.githubusercontent.com/1471149/110829156-b98ea680-828f-11eb-8b75-d0618cff94ee.png)

The tooltip contains the Comment field:

![tooltip](https://user-images.githubusercontent.com/1471149/110829163-bb586a00-828f-11eb-9f30-eba282f0a646.png)

The Name[language] and Comment[language] field are used if they exist in the .desktop file:

![hebrew](https://user-images.githubusercontent.com/1471149/110829348-e9d64500-828f-11eb-8a4b-b2f927990602.png)

**Comment by zigbert** [comment]
I think dir2pet still is an issue... as it builds *.desktop files with extended Name tag

**Comment by dimkr** [comment]
Also, it seems like some package templates replace the .desktop files, or modify them 😠

**Comment by dimkr** [comment]
Quick help if you want to see the current state quickly:

```
wget https://github.com/dimkr/woof-CE/releases/download/dpupos-x86_64-cros-8.0-menus1/dpupos-8.0-ext4-2gb-legacy.img.gz
gunzip dpupos-8.0-ext4-2gb-legacy.img.gz
qemu-system-x86_64 -enable-kvm -m 1024 -drive format=raw,file=dpupos-8.0-ext4-2gb-legacy.img
```

dpup is in pretty good shape, because it doesn't use any PET packages with old .desktop files.

**Comment by 01micko** [comment]
Nice! Dpup looks good!

@zigbert I think dir2pet is a very simple fix.

Just 2 variables need to change.

Example:

```diff
--- /usr/bin/dir2pet.orig	2020-07-09 08:32:28.000000000 +1000
+++ /usr/bin/dir2pet	2021-03-12 05:58:47.780728998 +1000
@@ -422,9 +422,9 @@ the main package
      mkdir -p $DIRPKG/$BASEPKG/usr/share/applications
      echo '[Desktop Entry]' > $DIRPKG/$BASEPKG/usr/share/applications/${NAMEONLY}.desktop
      echo 'Encoding=UTF-8' >> $DIRPKG/$BASEPKG/usr/share/applications/${NAMEONLY}.desktop
-     echo "Name=${PUPAPPLICATION} ${PUPMENUDESCR}" >> $DIRPKG/$BASEPKG/usr/share/applications/${NAMEONLY}.desktop
+     echo "Name=${PUPAPPLICATION}" >> $DIRPKG/$BASEPKG/usr/share/applications/${NAMEONLY}.desktop
      echo "Icon=${PUPICON16}" >> $DIRPKG/$BASEPKG/usr/share/applications/${NAMEONLY}.desktop
-     echo "Comment=${PUPAPPLICATION} ${PUPMENUDESCR}" >> $DIRPKG/$BASEPKG/usr/share/applications/${NAMEONLY}.desktop
+     echo "Comment=${PUPMENUDESCR}" >> $DIRPKG/$BASEPKG/usr/share/applications/${NAMEONLY}.desktop
      echo "Exec=${PUPEXECUTABLE}" >> $DIRPKG/$BASEPKG/usr/share/applications/${NAMEONLY}.desktop
      echo "Terminal=false" >> $DIRPKG/$BASEPKG/usr/share/applications/${NAMEONLY}.desktop
      echo "Type=Application" >> $DIRPKG/$BASEPKG/usr/share/applications/${NAMEONLY}.desktop
```

**Comment by 01micko** [comment]
Yeah, the package templates.

```
# grep 'Name=' *
abiword_FIXUPHACK:		-e 's%Name=.*%Name=AbiWord word processor%' \
asunder_FIXUPHACK:		-e 's%Name=.*%Name=Asunder audio CD ripper%' \
grep: ca-certificates: Is a directory
fpm2_FIXUPHACK:		-e 's%Name=.*%Name=Figaros Password Manager 2%' \
gadmin-rsync_FIXUPHACK:		-e 's%Name=.*%Name=GAdmin-Rsync remote backup%' \
galculator_FIXUPHACK:		-e 's%Name=.*%Name=Galculator scientific calculator%' \
gcolor2_FIXUPHACK:Name=Gcolor2 color chooser
gcolor2_FIXUPHACK:GenericName=Gcolor2
gdmap_FIXUPHACK:		-e 's%Name=.*%Name=Gdmap graphical disk usage%' \
geany_FIXUPHACK:		-e 's%Name=.*%Name=Geany text editor%' \
gexec_FIXUPHACK:Name=Gexec execute a command
gexec_FIXUPHACK:GenericName=Gexec
gftp_FIXUPHACK:		-e 's%Name=.*%Name=gFTP ftp client%' \
gnumeric_FIXUPHACK:		-e 's%Name=.*%Name=Gnumeric spreadsheet editor%' \
gparted_FIXUPHACK:		-e 's%Name=.*%Name=GParted partition manager%' \
gtk-chtheme_FIXUPHACK:Name=Chtheme GTK/Qt theme chooser
gtk-chtheme_FIXUPHACK:GenericName=Chtheme
hardinfo_FIXUPHACK:		-e 's%Name=.*%Name=HardInfo hardware information%' \
homebank_FIXUPHACK:		-e 's%Name=.*%Name=HomeBank finance management%' \
isomaster_FIXUPHACK:		-e 's%Name=.*%Name=ISOMaster iso file editor%' \
leafpad_FIXUPHACK:		-e 's%Name=.*%Name=Leafpad text editor%' \
mhwaveedit_FIXUPHACK:		-e 's%Name=.*%Name=mhWaveEdit audio recorder/editor%' \
mtpaint_FIXUPHACK:		-e 's%Name=.*%Name=mtPaint image editor%' \
mtpaint_FIXUPHACK:Name=mtPaint-snapshot screen capture
mtpaint_FIXUPHACK:GenericName=mtPaint-snapshot screen capture
grep: nscd: Is a directory
picom_FIXUPHACK:Name=picom
pulseaudio_FIXUPHACK:Name=ppavol
transmission_FIXUPHACK:		-e 's%Name=.*%Name=Transmission BitTorrent client%' \
grep: usr: Is a directory
grep: xorg_base_new: Is a directory
xsane_FIXUPHACK:		-e 's%Name=.*%Name=Xsane image scanner%' \
# 

```

NOTE: ppavol is only for a startup file and only if pa-applet is absent

**Comment by 01micko** [comment]
also support/rootfs-hacks.sh_desktop

```
# grep 'Name=' rootfs-hacks.sh_desktop 
Name=Midori web browser
GenericName=web browser
		-e 's%Name=.*%Name=mpv Media Player%' \
Name=Urxvt terminal emulator
GenericName=Urxvt' > ${SR}/usr/share/applications/rxvt-unicode.desktop
# 
```
