### ISSUE TITLE
Support for dhclient and udhcpc in SNS

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2116]
https://roy.marples.name/archives/dhcpcd-discuss/0003457.html

**Comment by 01micko** [comment]
Further to that discussion `dhcpcd` has been forked on github by Roy. https://github.com/NetworkConfiguration/dhcpcd

Sure the support can be add as mentioned for dhclient and udhcpcd but I don't see it as a pressing issue. Closing. Feel free to re-open.
