### ISSUE TITLE
Browsers in all future PUPs

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2126]
There are a few "standard" browsers that PUPs via WoofCE come with. I count 4. But to support installation of any one of the other 3 onto a pristine PUP which has 1 of them built-in is generally met with some problems. And, I know there are helper installation routines, but I was just curious to a concept that might be helpful.

Could WoofCE PUPs be shipped with a common set of libraries built-in to new PUPs such that any of the 4 browsers could be installed successful from their deb files vs the patchwork of today?

Or is today the best?

**No answer requested or required**. But **iff** it makes any sense, I am sure a **common browser subset** will show up built-into all new generations of PUPs coming out of WoofCE.

Seems that if this were the case, no helper installation routines; namely "get Chrome", "get browser", Download ...  (PETs) would be needed with their accompanying development-management...because the common browser subset would allow any of the 4 browsers to be installed from their DEBs.

The browsers I see are Firefox, Seamonkey, Palemoon, and Chrome depending which pristine PUP-DOG I boot.

**Comment by bigpup1** [comment]
What do you do about, the browsers, constantly changing what they need, to run?
Those things, constantly update, and change what they now need, to run.
Pale Moon and Seamonkey, not so bad about this.
Other browsers, seem to think, you are using a Linux OS, that is constantly updating, all the needed dependency stuff.

**Comment by s243a** [comment]
There seems to be a lot of good browsers not mentioned such as waterfox, ungoogled chromium, iron, ulight, midori, decenter, etc. I'm not saying that puppy support should be aimed at any of these other browsers just that I'm somewhat agnostic on which browsers to support. As it stands, most major flavours of browser seem to be chrome based or firefox based, so if a puppy supports at least one clone of the two major flavours then that covers a lot of browsers.

**Comment by CollaboratorGCM** [comment]
Having thought this thru, my idea of a common library-set for mainstream browsers is probably not within the scope of a PUP. Certain members in the wild will find the library additions as "bloatware" when it does NOT support their mainstream or is in addition to their mainstream.

The "bloatware factor that is thrown" can have a negative impact. So an idea of "common" for a variety of browsers has that potential. 

I consider my idea, personally, to be a bad one.

**Comment by s243a** [comment]
> Having thought this thru, my idea of a common library-set for mainstream browsers is probably not within the scope of a PUP. Certain members in the wild will find the library additions as "bloatware" when it does NOT support their mainstream or is in addition to their mainstream.
> 
> The "bloatware factor that is thrown" can have a negative impact. So an idea of "common" for a variety of browsers has that potential.
> 
> I consider my idea, personally, to be a bad one.

The install-whatever browser script, could use pkg (if available) or maybe petget, to install the needed dependencies if they aren't already on the system and if they are available in supported repos. There could be a prompt to confirm that people want to install the needed dependencies.

**Comment by CollaboratorGCM** [comment]
Your view is a more appropriate approach, I feel.

**Another idea** that the community could adjust to is when a pristine boot occurs, a choice is given in one of the two windows that initially open (FirstRUN and the completion after FirstRUN): 

- An offer for the users to choose another browser or not

Just a thought, as there are many various browsers that the community continues to toss requests for.

For assistance to RAM challenged systems (2GB or less), a future option to move browser out of save-session space (portable) could be an option for the default browser built in the ISO.

I only suggest this as so many now, including myself, are conducting 90% of work in the cloud. Local information storage and use is via SAMBA. This is an incline witnessed everywhere including academia.
