### ISSUE TITLE
rootfs-petbuilds: 'guess_fstype' should be in 'aaa_pup_c'

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#2143]
In the old busybox-1.31.1 it was a patch so the pet was excluded from all builds.

http://distro.ibiblio.org/puppylinux/sources/g/

**Comment by dimkr** [comment]
Will do!

**Comment by dimkr** [comment]
@01micko Do you have the busybox patch somewhere?

**Comment by 01micko** [comment]
Yes in the initrd_progs repo

https://github.com/puppylinux-woof-CE/initrd_progs/tree/master/pkg/busybox_static

**Comment by dimkr** [comment]
The busybox implementation is probably better, because it uses busybox code for partition type guessing, so it should support more file systems and it doesn't have to be maintained by Puppy. I'll add this patch to the busybox petbuild later.
