### ISSUE TITLE
The default mixer is retrovol even when using PulseAudio+pa-applet

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2149]
Probably needs to be changed to pavucontrol. Also, the "generic sound mixer" menu entry is useless if pavucontrol has a separate menu entry.

**Comment by 01micko** [comment]
maybe the FIXUPHACK can add to the pinstall.sh to remove 'generic sound mixer' and make pavucontrol the default mixer.

**Comment by dimkr** [comment]
> maybe the FIXUPHACK can add to the pinstall.sh to remove 'generic sound mixer' and make pavucontrol the default mixer.

I think I'll delete that .desktop file in the PulseAudio FIXUPHACK, through a pinstall.sh. That will solve the problem for puplets that use alsamixer+pa-applet and don't have pavucontrol.

**Comment by s243a** [comment]
As a side-note, I use alsa-mixer on even dpup buster and it seems to work. I like the features of alsa-mixer like the ability to disable auto-mute.

**Comment by dimkr** [comment]
Same here, I use it too, even if I have PulseAudio. I have a problematic laptop where I have to unmute the speaker to get the headphones jack to work, or vice versa 😠 

The problem is that this menu entry runs retrovol by default, and nothing makes it run alsamixer on a PulseAudio+pa-applet+pavucontrol setup, so it's either broken or useless.

I hope it's the last broken or useless menu entry I remove.

**Comment by peabee** [comment]
Is there any way to change the colour of the pa-applet systray icon?

**Comment by 01micko** [comment]
> Is there any way to change the colour of the pa-applet systray icon?

It depends on the gtk icon theme you use.
