### ISSUE TITLE
How to configure the base system?

### ISSUE THREAD

**Issue by kudoakiyama** [puppylinux-woof-CE/woof-CE#2153]
So I love puppy. However, it uses Pale Moon as its default browser which gives me problems vs. just using Firefox. I am fine with the window manager too however I want to use a tiling window manager such as i3 (btw this would be easily fixed if I could remove installed default packages). I checked out the scripts but I can't seem to figure out what packages are being installed to the system. I am a total newbie to this, and can I ask guidance as to what to do?

**Comment by dimkr** [comment]
@kudoakiyama Did you read https://github.com/puppylinux-woof-CE/woof-CE#building-a-puppy-using-the-commandline-scripts?

**Comment by kudoakiyama** [comment]
I kinda understood that instruction, but does that mean that I will configure the system after making the iso? Or before building it?

**Comment by dimkr** [comment]
Ideally, you need to edit DISTRO_PKGS_SPECS, etc' before you run 0setup, 1download, etc'. You can edit the DISTRO_* files after running some steps (e.g. after 1download) but sometimes you'll need to go back and re-run some script - for example, if you add a package to DISTRO_PKGS_SPECS, you'll need to re-run 1download and 2createpackages.

**Comment by kudoakiyama** [comment]
I added
`yes|i3|i3|exe,doc>null`
to DISTRO_PKG_SPECS-debian-bullseye
and currently building it via GitHub. I'll come back if I have more questions. Thank you!

**Comment by dimkr** [comment]
Great! Thank you @kudoakiyama, it's good to see people using the shiny new automated GitHub builds.

I hope this works well a quick and easy way to run woof-CE, and feedback is super valuable 👍🏿

**Comment by dimkr** [comment]
By the way: you might need to change /etc/windowmanger to i3. You can do this in woof-code/packages-templates/i3_FIXUPHACK (`echo i3 > etc/windowmanager`) or via EXTRA_COMMANDS, in woof-distro/x86_64/debian/bullseye64/_00build.conf.

Also, make sure you have i3's dependencies, as listed in https://packages.debian.org/bullseye/i3, and the dependencies of dependencies (i.e. the dependencies of i3-wm, https://packages.debian.org/bullseye/i3-wm).
