### ISSUE TITLE
Allow kit_kernel.sh to use a kernel with a suffix other than DISTRO_FILE_PREFIX

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2168]
This will allow dpup and slacko to use the same kernel, reducing build times.

**Comment by 01micko** [comment]
makes sense for `sublevel=0`

**Comment by 01micko** [comment]
Oh, but there is a snag, slacko64 puts aufs libs in /usr/lib64

**Comment by dimkr** [comment]
Why do we need those libraries? For years, we have Puppies without them and they work just fine.
