### ISSUE TITLE
FindUtils is NOT installed, yet PPM says it is

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2169]
Here is **[FindUtils](https://www.gnu.org/software/findutils/)**.

PPM of FossaPUP64 & Slacko64 says it contained, built-in. Where are its contents?

**Comment by s243a** [comment]
It should be See:
[/woof-distro/x86_64/ubuntu/focal64/adrv/DISTRO_PKGS_SPECS-ubuntu-focal](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/x86_64/ubuntu/focal64/adrv/DISTRO_PKGS_SPECS-ubuntu-focal)
and
[/woof-distro/x86_64/ubuntu/focal64/DISTRO_PKGS_SPECS-ubuntu-focal](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/x86_64/ubuntu/focal64/DISTRO_PKGS_SPECS-ubuntu-focal)

I'll check the ISO though.

**Comment by 01micko** [comment]
It's installed but `locate` and `updatedb` are omitted (filtered out) because of the huge database they create. Fills up a save file quickly.

**Comment by CollaboratorGCM** [comment]
I need the instantaneous find ability. Is there a way to install them via
PPM by "uncrippling" FindUtils? Is there something else that has come along over the years that give
instantaneous? My Google Drive has alway used something similar. And few/many
distros provide mlocate/locate.

And, since FindUtils is "crippled" should it be removed and the ONLY sub-program that PUP needs replace it in system and PPM?

**Comment by s243a** [comment]
> I need the instantaneous find ability. Is there a way to install them via PPM by "uncrippling" FindUtils? Is there something else that has come along over the years that give instantaneous? My Google Drive has alway used something similar. And few/many distros provide mlocate/locate. And, since FindUtils is "crippled" should it be removed and the ONLY sub-program that PUP needs replace it in system and PPM?

You can install it using pkg. The syntax is somthing like this:

`HIDE_BUILTINS=false pkg --get findutils -f` 

https://gitlab.com/sc0ttj/Pkg/-/wikis/home

**Comment by CollaboratorGCM** [comment]
Tried this
1. Menu>Settings>Package Manager (NG) 
2. Updated Repo
3. searched for FindUtils...found it
4. Selected Force Install
5. Got the successful install message
6. Yet NO "locate/mlocate".
![FindUtils](https://user-images.githubusercontent.com/15698050/112265128-582fe580-8c48-11eb-87ff-27a56fdf2297.jpg)
Any other ideas? 

This is a **low priority** as there is still much we are awaiting from Slackware which "may" (with our attention) fix this issue.

If anything else comes to mind along the way, I'll leave this thread's issue open.

**Comment by s243a** [comment]
> Tried this
> 
>     1. Menu>Settings>Package Manager (NG)
> 
>     2. Updated Repo
> 
>     3. searched for FindUtils...found it
> 
>     4. Selected Force Install
> 
>     5. Got the successful install message
> 
>     6. Yet NO "locate/mlocate".
>        ![FindUtils](https://user-images.githubusercontent.com/15698050/112265128-582fe580-8c48-11eb-87ff-27a56fdf2297.jpg)
>        Any other ideas?
> 
> 
> This is a **low priority** as there is still much we are awaiting from Slackware which "may" (with our attention) fix this issue.
> 
> If anything else comes to mind along the way, I'll leave this thread's issue open.

This is the GUI for "pkg" correct? I believe that you have to set HIDE_BUILTINS=false for this to work. If you want to do it via the GUI then perhaps you could export this variable prior to calling the gui.

**Comment by 01micko** [comment]
Pkg, isn't configured properly yet.

It's actually too hard coded and needs to be improved. The repos and distro
need to be entered manually but they should be auto discovered.

**Comment by mrfricks** [comment]
> I need the instantaneous find ability. Is there a way to install them via PPM by "uncrippling" FindUtils? Is there something else that has come along over the years that give instantaneous? My Google Drive has alway used something similar. And few/many distros provide mlocate/locate. And, since FindUtils is "crippled" should it be removed and the ONLY sub-program that PUP needs replace it in system and PPM?

hi @CollaboratorGCM fossapup has fsearch in quickpet on the useful tab that might be what you are after

**Comment by CollaboratorGCM** [comment]
I saw that in the past, but noticed that the help does not take one to the website the Help indicates. So it is not obvious in its proper use.

I will try to barrel thru that again to see if I can get a handle on it's use,and it's db. I assume it is similar to mlocate/locate/updatedb in its GUI use.
Correct?

**Edit:** Upon its installing via QuickPET, I did not see the locate/mlocate commands in terminal.

**Edit2:** **[Found this.](https://www.maketecheasier.com/fsearch-quickly-search-file-linux/)** Seems a good reference with example usage. I will try again to use.

**Edit3:** OK, I see how to use it as a GUI, properly via that site referenced above. It doesn't provide terminal-script as the FindUtils provides, but, for a GUI centric search it does provide instanteous file search results,visually. I will have to find if it provides cron updates or if it refreshes itself (db) somehow.

THANKS!

**Comment by CollaboratorGCM** [comment]
If FindUtils is not fully installed or accessible for installation in PUPs, it should be dropped from the REPOs. 
Further,if **"xargs"** is the only thing that PUPs need, then it should be installed separate with NO reference to FindUtils.

Just an update.

**Comment by s243a** [comment]
> If FindUtils is not fully installed or accessible for installation in PUPs, it should be dropped from the REPOs.
> Further,if **"xargs"** is the only thing that PUPs need, then it should be installed separate with NO reference to FindUtils.
> 
> Just an update.

I mentioned how this package can be re-installed via "pkg". You could also install it in the ppm by deleting the associated metadata from the ppm. 

As a side note, if you set HIDE_BUILTINS=false, then check your blacklists first. For instance libc6 should be blacklisted because you don't want to accidently end up with two version of this library.
