### ISSUE TITLE
Support for missing default applications

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2180]
For example: I want my puplet not to have Abiword or LibreOffice installed, so /usr/local/bin/defaultwordprocessor doesn't do anything. Instead, it should either ask the user to install a word processor, or run PPM.

**Comment by peabee** [comment]
Yes that is exactly what I do for the Light web browser that I supply in the adrv...... I have light-missing in the main sfs symlinked to light which is overwritten by light in the adrv...........

**Comment by dimkr** [comment]
The question, is what to do with applications that are not in the adrv. My adrv has Firefox and a basic set of applications (Sylpheed, Geany, Transmission, etc') but doesn't include, and won't include, Abiword, Gnumeric and Inkscape, among others.

**Comment by 01micko** [comment]
This?

```shell
#!/bin/sh

cd sandbox3

# chroot in to main fs and loop through defaults

for default in rootfs-complete/usr/local/bin/default* ; do
	app=${default##*/}
	app=${app/default/}
	echo -n "$app "
	dexec=`grep '^exec' $default | cut -f 2 -d " "`
	echo -n "$dexec "
	chroot rootfs-complete sh -ec "if ! command -v $dexec >/dev/null 2>&1 ; then
	 echo fixing
	 
	 echo '#!/bin/sh

/usr/lib/gtkdialog/box_yesno \\
--info \\
--image-icon info.svg \\
--yes-label \"Open PPM\" \\
--no-label \"Open Puppy Apps\" \\
--yes-icon package_pet.svg \\
--no-icon puppy_config.svg \\
\"Configure default apps\" \\
\"Configure your default '$app' by either installing one from PPM or openning Puppy Apps
if an appropriate application is on your system.\" \\
\"Click Open PPM to start Puppy Package Manager or Open Puppy Apps to configure.\"
EXITCODE=\$?
echo \$EXITCODE
case \$EXITCODE in
	0)exec ppm;;
	1)exec puppyapps;;
esac' > ${default#*/}
	 chmod 755 ${default#*/}
	else
	 echo ok
	fi"
done

```

![gui](https://user-images.githubusercontent.com/1019119/112696638-21431500-8e7e-11eb-9593-80368727ed2e.png)

Here's what we end up with
```shell
#!/bin/sh

/usr/lib/gtkdialog/box_yesno \
--info \
--image-icon info.svg \
--yes-label "Open PPM" \
--no-label "Open Puppy Apps" \
--yes-icon package_pet.svg \
--no-icon puppy_config.svg \
"Configure default apps" \
"Configure your default audiomixer by either installing one from PPM or openning Puppy Apps
if an appropriate application is on your system." \
"Click Open PPM to start Puppy Package Manager or Open Puppy Apps to configure."
EXITCODE=$?
echo $EXITCODE
case $EXITCODE in
	0)exec ppm;;
	1)exec puppyapps;;
esac

```

**Comment by dimkr** [comment]
@01micko It looks great and there's only one problem to deal with: the loop should look for applications that are missing in both rootfs-complete/usr/local/bin and adrv/usr/local/bin.

**Comment by 01micko** [comment]
Yes, well the `chroot` won't work in `adrv` so a creative work around is needed. Probably _not_ mounting adrv on top of rootfs complete because the adrv defaults should be in the adrv.

**Comment by dimkr** [comment]
I think it can be solved using your solution + checking if adrv/usr/local/bin/default* doesn't exist. If `which` fails in a rootfs-complete chroot, and there's no adrv/usr/local/bin/default*, then this default* should be replaced with a placeholder in rootfs-complete.

**Comment by 01micko** [comment]
`puppyapps` is a good placeholder - and it can be expanded.
