### ISSUE TITLE
puppy package manager

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#2186]
Now that there's talk of improving the speed of the PPM @01micko and before work on this starts, i would like to suggest we roll back to version 2.1.2 and have some saner defaults. 

PPM version 2.5 issues......
1. It's taken away the ability to install multiple packages at once and only installs 
 .  the last item clicked on. 
2. It  has some graphical corruption, when installing a grey blocky area appears 
    over the PPM. 
3. It's removed the install progress bar
4. It's removed the 'non verbose' option when updating the databases so that you 
    have to click 'enter' multiple times
5. It's removed 'skip package size check when more than 4gb space available'

As for saner defaults (applies to version .2.1.2)...
1. Skip package size check when more than 4gb space available
2. Do not show terminal with PPM actions.  
3. Use 'non verbose' option when updating the databases.

Any speedup for the PPM would be great! particularly uninstalling stuff as that seems to take twice as long as installing.

BTW to compare the PPM versions try fossapup64 or bionicpup64 v Latest slacko or @peabee's latest

**Comment by rizalmart** [comment]
QuickPup 21.03 brings back the PPM 2.1.x you talked about. However classic install mode was dropped due to complexity.
