### ISSUE TITLE
Stable woof-CE branch

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2191]
Imagine a world where woof-CE has a branch ("stable", "release", whatever) that's synced with testing every once in a while (3/6/12 months) and the only changes pushed to it in between are bug fixes cherry-picked from testing.

This will make life easier for Puppy builders, and allow automated, periodic releases of Puppy updates (i.e. Slacko 8.0.1, 8.0.2 ...) with fixes from woof-CE plus security/bug fix updates from Slackware/Debian/Ubuntu.

**Comment by dimkr** [comment]
@puppylinux-woof-CE/members @rizalmart @gyrog @zigbert (who did I miss?)

I can branch from testing now, set up automated periodic releases (slacko 7.0.1, 7.0.2 ...), cherry-pick fixes for severe issues from testing every once in a while (say, once a week or two), and set a deadline (half a year?) where this branch will be synced with testing to start another fixes-only period.

But for that to work, everyone will have to commit to:
- Putting reasonable effort into minimizing changes when fixing a bug, to increase the chance of successful cherry-pick onto a branch that looks like testing from half a year ago
- Fixing one bug in each commit
- Separating bug fixes from other changes - i.e. a PR that adds a feature that depends on a bug fix will consist of two commits, so I can cherry-pick just the bug fix
- Clear commit messages and/or documentation of bugs through GitHub issues (for example, the commit message can contain "#1234" to refer to issue 1234) to explain and document what was fixed in a commit
- Avoiding direct commits to testing and passing all changes in testing through PRs, to make it possible to go over recent changes in testing (= recently merged PRs) without looking at all commits one by one (it's easier to look at the commits grouped by feature/issue, rather than looking at hundreds of commits trying to find that one important bug fix commit)

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/tree/stable

**Comment by peabee** [comment]
@dimkr @01micko 
What is the stable branch for?
Do I now need to decide whether to use the testing or stable branches for a build? How does this "make life easier for Puppy builders"?
How do I decide which branch to use?
And what is the purpose of the Master branch now??
Will all "Official Releases" now use the stable branch?

**Comment by peabee** [comment]
The readme seems to be inconsistent as it infers that the stable branch only applies to Vanilla DPup but then mentions Debian/Slackware/Ubuntu........

> This is the stable branch, branched from testing on October 15th, 2021.
> 
> Its main purpose is to protect automated weekly builds of Vanilla Dpup from regressions and issues introduced in testing. Ideally, the only commits to this branch should be critical fixes cherry-picked from testing.
> 
> Currently supported: Build status
> 
> Slackware
> Ubuntu
> Debian

**Comment by dimkr** [comment]
> What is the stable branch for?

Quote from the README:

```
This is the stable branch, branched from testing on October 15th, 2021.

Its main purpose is to protect automated weekly builds of Vanilla Dpup from regressions and issues introduced in testing. Ideally, the only commits to this branch should be critical fixes cherry-picked from testing.
```

You can use it if don't want any new features introduced after October 15th.

I haven't changed anything else in the README, to make it easier to sync the branch with testing at some point in the future, then freeze it and only cherry-pick fixes for some time.

**Comment by peabee** [comment]
OK - so it does only apply to Vanilla DPup ................

**Comment by dimkr** [comment]
No, you can use it. But I only cherry-pick fixes I find useful and safe for Vanilla Dpup. Sometimes they're dpup-specific fixes, but most are not.
