### ISSUE TITLE
chmviewer - why in rootfs-skeleton with no executable?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2200]
Why does rootfs-skeleton have:
/usr/local/bin/defaultchmviewer
when the .pet for its executable:
pzchmview-1.0d-1.pet
is not in:
https://github.com/puppylinux-woof-CE/woof-CE-noarch/tree/master/pet_packages-noarch
whereas it was/is in:
http://distro.ibiblio.org/puppylinux/pet_packages-noarch/
??
What does it do anyways? Are there any builds with it in? Has anybody missed it?
Should it be deleted from rootfs-skeleton?
Should the .pet be copied from ibiblio to github?
Should the executable from the .pet be added to rootfs-skeleton?
@dimkr new puppyapps checking threw up this anomaly.

**Comment by 01micko** [comment]
It opens [compiled html files](https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help), an MS proprietary format that has been reverse engineered.

I reckon delete the exec in `/usr/local/bin`
