### ISSUE TITLE
WoofCE generated distros used with TVs

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2208]
The prompt discusssion got me thinking of our modern times versus where we were in days of merely terminals.

Today, more and more of the user community and us will have use systems that have a mere power-cord and an HDMI (or USB-C) cable running from the PC system(s). **2 cables ONLY!** Oh, there will be times when we connect USB devices from time to time, but for many this may become less over time.

Today's problem is that this fact may not be taken seriously and thereby going overlooked in system development and setup.

This request is for those developers contributing who have a PC connected to a TV, to test to insure **_that OOTB_**, the audio is carried via the HDMI signaling when the system is booted. This is a productivity request, merely, knowing the cost reduction-diving of TVs today.

**Side note:** since switching to the TV, I no longer need glasses (HA!)

**Comment by dimkr** [comment]
Can we close this issue? It's a request (specifically, one that requires equipment some of us don't have), not an issue.

@01micko

**Comment by 01micko** [comment]
Yes.
