### ISSUE TITLE
loopback.cfg not in .iso for recent builds

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2218]
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/support/mk_iso.sh
Line 162:
cp -f ${PX}/usr/share/boot-dialog/loopback.cfg ${BUILD}/boot/grub/

I have had a report that loopback.cfg is not being copied into the .iso for my recent builds and indeed this is the case.
Why would line 162 of mk_iso.sh not be actioned? 
/usr/share/boot-dialog/loopback.cfg is in rootfs-complete

**Comment by peabee** [comment]
Ah - I don't have:
/rootfs-complete/usr/share/grub2-efi
line 34

where should this be coming from?

**Comment by 01micko** [comment]
noarch .. surprised you didn't see it there.

`grub2_efi-2.02.2018.08-fd64.pet`

It's there so it's  so it's  available for 32 and 64.

**Comment by peabee** [comment]
Thanks.
What I don't understand is why I now need it when I didn't need it previously?
Was it maybe provided in frugalpup and has now been removed? @gyrog ?
Closed - thanks.

**Comment by 01micko** [comment]
You probably did but didn't realise

**Comment by gyrog** [comment]
The grub2 efi code in FrugalPup is '/usr/local/frugalpup/grub2-efi.tar.xz'.

**Comment by peabee** [comment]
@01micko @gyrog 
Having to have both makes the .iso about 10MB bigger...... frugal.pet and grub2_efi.pet
Still wondering what has changed fairly recently??

**Comment by 01micko** [comment]
The whole 'cd-boot' thing needs a rewrite. It _should not_ be a download. Woof is perfectly capable of building it on the fly in a few seconds... that's how it was and IDK why @wdlkmpx couldn't work with that and simply adjust the script :confused: 

Anyway, it's something that needs fixing and is entirely related.

NB: the fatdog grub2 was a part of woof before that. But forward we must move. 

@gyrog - do you have a build script for grub2? BTW, it does need to be updated to 2.0.4

**Comment by 01micko** [comment]
> Having to have both makes the .iso about 10MB bigger.

No, the `grub2_efi` pet is 1207 K xz compressed. Maybe expanded it might be approaching 10 MB. 'cd-boot' probably adds it own bit because the `efi.img` must be included to boot on UEFI systems.

**Comment by gyrog** [comment]
@01micko
I do not have a build sript for 'grub2-efi.tar.xz'.
The files in the 'grub2-efi.tar.xz' in FrugalPup were generated by @jamesbond, I just repackaged them a bit.
He assurered me that it was a signigicantly "patched" version of 2.0.3 that already had the best parts of 2.0.4.
See issue "Custom grub efi package for puppy #1618", 'EFI-shim-1.33-puppy.zip'.
This also includes 'puppy.cer' the public key needed as the MOK.
I assume that @jamesbond has the private key that he signed the stuff with.

The non-uefi grub2 used by FrugalPup is 2.0.4, and was compiled by me, I think I should have a script for it.
But it's pretty much a standard grub2 compile and install.

I'm not aware of anything other than FrugalPup that uses the grub2 included in FrugalPup,
so I don't expect that it's necessary to include it in the .iso outside FrugalPup.
(Although, if it were in woof-ce, it could be removed from FrugalPup, but it's a chicken and egg situation, I don't want to release FrugalPup without it until I can be confident that most Puppies contain it.) 

I think the generation of a uefi .iso depends on older grub2 stuff that was in Puppy before I started FrugalPup, possibly the stuff that's in the .pet.
When I started looking at uefi booting with grub2, Puppy already produced uefi .iso files,
but in my testing, the old grub2 stuff in Puppy did not support "Secure Boot enabled".

**Comment by peabee** [comment]
I'm really confused (not an uncommon occurrence!) as my build configs show me that during the 2nd half of 2020 I deliberately excluded the grub2-efi.pet from my builds - not just one build but several. This leads me to think that some information must have "appeared" to cause me to do this - but I am at a complete loss to remember what that was. Reinstating grub2-efi in the build does inevitably make the .iso bigger (but not so much the puppy.sfs) as the missing efi components are reinstated in the boot directory. I'll close again.

**Comment by 01micko** [comment]
@gyrog 

Maybe, for now, we can put frugalpup's grub2 into woof, or replace the fatdog noarch package.

Frugalpup _can still ship with grub2_ but with 2 changes
- a `pinstall.sh` deleting the frugalpup grub2 files from the frugalpup location if grub2 is detected in `/usr/share/...`
- some conditional scripting changes to accommodate the new location in `/usr/share/...`

**Comment by gyrog** [comment]
@01micko,
Except that FrugalPup is primarily released as a ".sfs" file, rather that a ".pet"
If FrugalPup is installed as a ".sfs" then there is little advantage in leaving the file out.

But yes, as a ".pet", a 'pinstall.sh' fifle could delete the grub2 code in FrugalPup, if it exists in Puppy,
this should result in only 1 copy in the ".iso", yes??

Internally, FrugalPup wlll give preference to using the grub2 file in Puppy, if it exists. 

The file we are talking about is currently '/usr/local/frugalpup/grub2-efi.tar.xz'.
Will this end up as '/usr/share/grub2/grub2-efi.tar.xz'?
or
as '/usr/share/grub2-efi/grub2-efi.tar.xz'?
and forget about the other 2 grub2 files.

Should we do the same with "/usr/local/frugalpup/grub2-mbr.tar.xz'?
And maybe '/usr/local/frugalpup/grub2-iso.tar.xz'?

This is a better solution than releasing FrugalPup without grub2, and a separate grub2 release for Puppies.the don't contain tthe appropriate grub2 files.

Well on to FrugalPup v29.

Just 1 thought, what if anything depends on the current files in '/usr/share/grub2-efi/'?

**Comment by 01micko** [comment]
We create a new branch and deal with the fallout later. `cd-boot` does depend on current grub2 but as stated that needs to change.

**Comment by gyrog** [comment]
We could save some space from 'grub2-efi.tar.xz' by removing the 32bit stuff, and making it available independently, perhaps as an archive that can be extract into '/EFI/boot' or '/EFI/Puppy'.
The 32bit efi code is very rarely used, although I have a uefi Lenovo that will recognise only the 32bit efi.

**Comment by gyrog** [comment]
Sometime ago I made 'grub2_frugalpup-20.pet' for storing the grub2 binaries in '/usr/share/grub2'.
Is this used in woof-ce?

**Comment by wdlkmpx** [comment]
The grub2-efi from fatd?g seems to be the only one that works fine with ISOs ... according to my tests back in 2019

I remember testing ISOs with grub from Debian and it didn't work as expected, otherwise the grub2-efi .pet is not needed, I just found that bootflash extracts this file /usr/local/frugalpup/grub2-efi.tar.xz if it's present, hmmm I don't know if the main installer uses that file, I deleted that script long ago

I figured out that distros that don't need to be installed in order to work as expected don't need ISOs and CDs, only proper boot params and a writable filesystem.
 Maybe a simple grub4dos iso for retro computing and install grub4dos to a harddrive, a live installation CD and nothing else

**Comment by wdlkmpx** [comment]
Looking at the old code, the inclusion of the grub2 efi package triggers the CD uefi code, even though it might not be needed if the cdboot.tar.xz already contains the grub2 files (can't remember), it was just a matter of removing a couple of lines to create a uefi CD unconditionally. To fix this, remove the uefi CD code and keep only a grub4dos iso for retro computing

**Comment by 01micko** [comment]
@gyro's frugalpup grub2 binaries work with or without secure boot. We shifted back to construction of CD entirely in woof mechanism without download. Probably need to build grub2 (or at least as an option) on the fly. The one in frugalpup is a few years old now. Signing the binaries might be optional too.
