### ISSUE TITLE
Indeed, loopback.cfg has disappeared in PB's WoofCE builds

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2219]
#2218 is closed. ... BUT ...
Is this problem widespread? 

This affects both developers and users:

- Developers who have become accustomed to seeing their WoofCE outcomes available for a variety of boot options
- User planning for those who are now using SG2D to boot their ISOs and use as an option to Frugal without Frugal storage needs.

But, we know of those affected.

Lastly, it appears moving from GRUB 2.03 to 2.04 would remove the need for JB's patches assuming 2.03 was patched from 2.03 development fixes. This would be a normal practice, I think.

**Comment by 01micko** [comment]
> #2218 is closed. ... BUT ...
> Is this problem widespread?
> 

No
> This affects both developers and users:
> 
> * Developers who have become accustomed to seeing their WoofCE outcomes available for a variety of boot options
> * User planning for those who are now using SG2D to boot their ISOs and use as an option to Frugal without Frugal storage needs.
> 
> But, we know of those affected.
> 

Really a localised issue of which the dev is aware and the rest of us have on the radar.
> Lastly, it appears moving from GRUB 2.03 to 2.04 would remove the need for JB's patches assuming 2.03 was patched from 2.03 development fixes. This would be a normal practice, I think.

A possible outcome.
