### ISSUE TITLE
Slacko64-8.1 - /usr/lib64/gconv directory is missing

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2230]
Directory /usr/lib64/gconv from package glibc is not being included in the build.

A consequence is that Gnumeric is unable to open .xls files...... iconv errors due to missing CP1252.so file

Will try to find out why it is being deleted......

**Comment by peabee** [comment]
Same problem with the "new" FossaPup64-9.5 ...........

**Comment by dimkr** [comment]
focal64 in woof-CE is half-broken (unless someone does the work of cleaning up Fossapup64 and reproducing it in one, clean woof-CE build), so it's not a good environment to test things. For example, text in the terminal isn't rendered correctly.

~Does this happen in slacko64 8.x?~ nvm, read the title of this issue from the middle

**Comment by peabee** [comment]
Yes - title says it all!
The whole directory is c. 2M compressed - presumably it could be "cut down".....

**Comment by peabee** [comment]
It used to be in "older" builds - e.g. both the "real" FossaPup64-9.5 and Slacko64-7.0 have the gconv folder with about 250 .so files.....
It must be being deleted by 2createpackages but I'm blowed if I can see where! templates-packages for glibc don't seem to be the culprit.....
Flummoxed!

**Comment by peabee** [comment]
gconv is being put into glibc_DEV ............. but why?

**Comment by 01micko** [comment]
Should I remove the suspected code I referenced? @dimkr 

EDIT: doing it

**Comment by 01micko** [comment]
Yeah _*gconv_ but could affect anything starting with 'gc'

**Comment by dimkr** [comment]
> Should I remove the suspected code I referenced? @dimkr
> 
> EDIT: doing it

What problem does this deletion fix? 🤔

**Comment by peabee** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/issues/2230#issue-855980173

**Comment by dimkr** [comment]
> [#2230 (comment)](https://github.com/puppylinux-woof-CE/woof-CE/issues/2230#issue-855980173)

I was referring to the deletion of the gconv directory. What's the purpose of deleting it?

**Comment by peabee** [comment]
It is currently being erroneously moved from the main sfs to the devx
The @01micko change to an @rizalmart PR should (untested) restore the status quo where the gconv directory from glibc is included in the main sfs.
The gconv directory should not be deleted as it is needed for iconv to do character map changes (I think).

**Comment by peabee** [comment]
I have done 2 builds following:
BUILD_FROM_WOOF='testing;5aae9c22b;2021-04-14 05:54:56 +1000'
and the folder gconv is now back in its correction location in the main sfs - thanks @01micko

**Comment by 01micko** [comment]
Anyway, nice catch @peabee and fairly timely too. Bug only existed 22 days. Pays to test!

**Comment by peabee** [comment]
> Pays to test!

I suspect the number of people testing new builds using new versions of Woof-CE is very limited.
I rather think given the huge number of recent Woof-CE changes it may be time for a pause and for a small number of testing releases to be made available for wider testing on the forum.............

**Comment by dimkr** [comment]
Or, alternatively (and I strongly support this idea), we can set up automated releases (say, once a week) of a Puppy with an update tool, as I did with dpup in https://github.com/dimkr/woof-CE/actions/workflows/dpupos-rolling.yml and https://github.com/dimkr/woof-CE/releases. If we have something like this but based on Fossapup64 or Slacko 7.0 and with a bug reporting tool, it will be useful enough for people to use as their Puppy of choice.

**Comment by peabee** [comment]
> we can set up automated releases (say, once a week) of a Puppy

I think this may discourage people from testing as they will be unsure what the state is of the version they're testing and whether their test results have already been superceded by later releases..... maybe every 3 months?

**Comment by dimkr** [comment]
The fundamental problem is that code pushed into testing breaks things (and people change things in testing without testing the changes, or without letting other eyes to look at the changes first, but that's a different problem). If you can't guarantee testing doesn't break after a certain commit, you can't guarantee it doesn't break in the last day of each 3 month period, so infrequent releases aren't guaranteed to be stable.

In my experience as a software engineer, without proper automated testing or even manual QA, sometimes you must choose between  "release early, release often", or "release early, release slowly". Changes don't meet reality and get feedback unless you ship them, so they reach users in their early, crude form, and the only question is when. If I have to choose between the two options, I always prefer frequent unstable releases, to infrequent, equally unstable releases.

And to make users happy, it's always good to have a stable branch (#2191), with automated releases as well, but without any changes other than changes backported from the "unstable" version that fix real problems and are safe to cherry-pick.

**Comment by CollaboratorGCM** [comment]
Understanding both of your points, I think the current dilemma is the
"community" of users have changed over the past 19 months. We have to face
that fact.

I see current efforts, here, as positive and right direction of its movement; hence achievements.

The past testing community has changed. It appears to have become more individualized versus a desire to participate in a group.

Several factors in natural movements have contributed to this community behavior: hardware, mainline OSes, pandemic, housing arrangements, communications, protocols, weather effects, etc.

None of this is abnormal, it just heighten and much more obvious now.

Personally, I am unsure how to best inspire the community to focus on more testing and use of the WoofCE productions. Fabulous work seen in this GIT effort, especially when an oversight is presented!

**Comment by CollaboratorGCM** [comment]
@dimkr will there be any ISOs forthcoming? I had noticed your images on
your DPUP site.

Just wanted to know if WoofCE generates ISOs for your weekly postings.

**Comment by dimkr** [comment]
> @dimkr will there be any ISOs forthcoming?

No. I can set up weekly releases of Puppy ISOs built from latest woof-CE, if we find it useful (I do).

Ignore my automated dpup releases, they built using a fork of woof-CE.
