### ISSUE TITLE
Wayland progress among the distros

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2247]
The is an FYI. 

As time moves us, Wayland is progressing in the Linux community with Fedora, Debian, Ubuntu, Arch just to name a few.

Most, if not all, know that nVidia is on-board joining the other video card manufacturers.

Here is **[a document written for system developers and admin](https://wiki.debian.org/Wayland#Others)** that seems to be rather current. 

Again, this post is FYI

**Comment by dimkr** [comment]
So the issue here is that other distros are ahead of Puppy? What's the action item?

**Comment by CollaboratorGCM** [comment]
"Action items?"  2 come to mind:

1. Maybe the steps to move from XORG to Wayland? (The experiences of other distros, if available)

2. BUT, "beware" of forum community reactions to anything new. Maybe better to announce that the change is progressing, first; allowing the expected noise level to diminish as this progresses. (OR, just cold-turkey the move without announcing the change. The importance here is that it will just work and most will not notice Wayland became the way.)

The prime reason for this kind of move is to progress with the upcoming video-audio-systems progress that the manufacturers will be directing their attention to going into present-day future. So, its not just technology in MACs-Windows, but now in LInux. Notwithstanding the code-base clarity that has occurred.

**Comment by 01micko** [comment]
We are taking necessary steps re #2252 so closing
