### ISSUE TITLE
gtkdialog gtk3 theming

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#2248]
The 'on the fly' theming for gtk3 needs fixing and with [this old commit](https://github.com/puppylinux-woof-CE/gtkdialog/commit/3b43d8e1c4d3043d32780b893f1d0ce32d970a71) that largely went unnoticed it is possible to add an option to the gtkdialog call pointing the app at an appropriate `gtk3_xxx.css` theme file.

**Comment by rizalmart** [comment]
Does all puppy scripts are source compatible with gtk3? If not, what are those scripts?

**Comment by rizalmart** [comment]
Does all puppy scripts are source compatible with gtk3? If not, what are those scripts?

**Comment by 01micko** [comment]
> Does all puppy scripts are source compatible with gtk3? If not, what are those scripts?

Mostly issues is where a theme is set in the script. There may be some other cosmetic issues often solved by correctly packing the widgets.
