### ISSUE TITLE
improve zstd support

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#2251]
`zstd` has been in puppy a while now and support is flakey at best.

Here's what needs doing:

- [x] fix run action for a a simple zstd compressed file : eg `myfile.zstd` 
- [x] fix icon for zstd compressed file (icon themes) - `application/x-zstd`
- [x] fix icon for zstd tarball - `application/x-zstd-compressed-tar`
- [x] fix icon for arch zstd packages and run action - `application/x-archlinux-package-zstd`
- [x] ~update `shared-mime-info` to 2.1~ use upstream where possible

This list may be incomplete. Please add to as necessary.

**Comment by peabee** [comment]
Some work was done in Jan 2020:
https://github.com/puppylinux-woof-CE/woof-CE/pull/1742
https://github.com/puppylinux-woof-CE/woof-CE/pull/1743

ppm, xarchive, pextract and pcompress have been able to handle Arch zstd packages for some time.......

**Comment by CollaboratorGCM** [comment]
FYI. Kernel update coming ==> https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/YYSL4WQ6A337UNAR3AYBWKAROJ42SBOO/

User use Implementation(s) should follow.

**Comment by dimkr** [comment]
> FYI. Kernel update coming ==> https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/YYSL4WQ6A337UNAR3AYBWKAROJ42SBOO/
> 
> User use Implementation(s) should follow.

Compressed kernel modules inside a (compressed) Squashfs image. As far as I know, this can increase size *and* slow down loading, not the other way around.

**Comment by 01micko** [comment]
> > FYI. Kernel update coming ==> https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/YYSL4WQ6A337UNAR3AYBWKAROJ42SBOO/
> > User use Implementation(s) should follow.
> 
> Compressed kernel modules inside a (compressed) Squashfs image. As far as I know, this can increase size _and_ slow down loading, not the other way around.

That's why we ditched them when woof-CE was born. 1 level of compression is enough.

**Comment by 01micko** [comment]
> - [ ] update `shared-mime-info` to 2.1

As far as my fifth item in the check list goes I think we should use upstream `shared-mime-info` where possible.

**Comment by 01micko** [comment]
> Some work was done in Jan 2020:
> #1742
> #1743
> 
> ppm, xarchive, pextract and pcompress have been able to handle Arch zstd packages for some time.......

That is a small portion of what needs to be done. At least now we have supporting mime icons. Arch packages are a drop in the bucket really but we'll get there.

**Comment by peabee** [comment]
> > * [ ]  update `shared-mime-info` to 2.1
> 
> As far as my fifth item in the check list goes I think we should use upstream `shared-mime-info` where possible.

I notice that Slackware 2.1 freedesktop.org.xml is much bigger (like getting on for x10) the 1.10 common32/64 versions..... was something done to reduce the size for puppy?? Is a package template needed? @wdlkmpx @woodenshoe-wi may have clues?

**Comment by peabee** [comment]
I think its because all the language variations have been stripped out...........
e.g.
```
2.1:
  <mime-type type="application/x-atari-2600-rom">
    <comment>Atari 2600 ROM</comment>
    <comment xml:lang="bg">ROM — Atari 2600</comment>
    <comment xml:lang="ca">ROM d'Atari 2600</comment>
    <comment xml:lang="da">Atari 2600-ROM</comment>
    <comment xml:lang="de">Atari 2600 ROM</comment>
    <comment xml:lang="en-GB">Atari 2600 ROM</comment>
    <comment xml:lang="es">ROM de Atari 2600</comment>
    <comment xml:lang="eu">Atari 2600 ROMa</comment>
    <comment xml:lang="fi">Atari 2600 ROM</comment>
    <comment xml:lang="fr">ROM Atari 2600</comment>
    <comment xml:lang="fur">ROM Atari 2600</comment>
    <comment xml:lang="hr">Atari 2600 ROM</comment>
    <comment xml:lang="hu">Atari 2600 ROM</comment>
    <comment xml:lang="id">Atari 2600 ROM</comment>
    <comment xml:lang="it">ROM Atari 2600</comment>
    <comment xml:lang="kk">Atari 2600 ROM</comment>
    <comment xml:lang="ko">아타리 2600 롬</comment>
    <comment xml:lang="pl">Plik ROM konsoli Atari 2600</comment>
    <comment xml:lang="pt">ROM Atari 2600</comment>
    <comment xml:lang="pt-BR">ROM do Atari 2600</comment>
    <comment xml:lang="sl">Atari 2600 ROM</comment>
    <comment xml:lang="sv">Atari 2600-rom</comment>
    <comment xml:lang="tr">Atari 2600 ROM</comment>
    <comment xml:lang="uk">Atari 2600 ROM</comment>
    <comment xml:lang="zh-CN">雅达利 2600 ROM</comment>
    <comment xml:lang="zh-TW">雅達利 2600 ROM</comment>
    <generic-icon name="application-x-executable"/>
    <glob pattern="*.a26"/>
  </mime-type>

1.10:
<mime-type type="application/x-atari-2600-rom">
    <comment>Atari 2600</comment>
    <generic-icon name="application-x-executable"/>
    <glob pattern="*.a26"/>
  </mime-type>

```

**Comment by woodenshoe-wi** [comment]
I think the last version of shared-mime-info that I made pets for was 1.9

I used the scripts from puppylinux-woof-CE/petbuilds generic branch, basic/pkgs/shared-mime-info at version 3130a6e  
puppylinux-woof-CE/petbuilds@3130a6e

**Comment by peabee** [comment]
Looks like line 42 of https://github.com/puppylinux-woof-CE/petbuilds/blob/generic/basic/pkgs/shared-mime-info/shared-mime-info.petbuild ......
`sed -i '/xml:lang/d' freedesktop.org.xml`
is what deletes the language variations
and needs to go into a package template

**Comment by 01micko** [comment]
Sure, we can have a package template to reduce the size by deleting the languages, but maybe it should be added to the `nls` dir before alteration. I'll take a look.

**Comment by 01micko** [comment]
Yes, it works
`shared-mime-info_FIXUPHACK` where the orinal goes to _NLS

```
if [ -e ../shared-mime-info_NLS ]; then
	mkdir -p ../shared-mime-info_NLS/usr/share/mime/packages
	cp -a usr/share/mime/packages/freedesktop.org.xml ../shared-mime-info_NLS/usr/share/mime/packages/
fi
sed -i '/xml:lang/d' usr/share/mime/packages/freedesktop.org.xml

```

**Comment by peabee** [comment]
Should the Slackware install script run?

Processing shared-mime-info
 processing shared-mime-info-2.1-i586-3.txz
 **executing (Slackware) install script**
 executing packages-templates/shared-mime-info_FIXUPHACK

doinst.sh
#!/bin/sh
if [ -x /usr/bin/update-mime-database ]; then
  /usr/bin/update-mime-database /usr/share/mime 1>/dev/null 2>/dev/null
  cat /etc/passwd | while read passwdline ; do
    homedir=$(echo $passwdline | cut -f 6 -d :)
    if [ -d $homedir/.local/share/mime ]; then
      username=$(echo $passwdline | cut -f 1 -d :)
      su $username -c "/usr/bin/update-mime-database $homedir/.local/share/mime 1>/dev/null 2>/dev/null" 2> /dev/null
    fi
  done
  ....... This is just "cleanup" in case something might be missed in /home/*/
  for homemimedir in /home/*/.local/share/mime ; do
    if [ -d $homemimedir ]; then
      username=$(echo $homemimedir | cut -f 3 -d /)
      su $username -c "/usr/bin/update-mime-database $homemimedir 1>/dev/null 2>/dev/null" 2> /dev/null
    fi
  done
fi

**Comment by 01micko** [comment]
Doesn't do any harm.

**Comment by peabee** [comment]
Takes quite a time to run - seems to be doing "multi-user" types of things? - maybe a shared-mime-info_PRE is needed like glibc_PRE to remove it?

**Comment by 01micko** [comment]
I see. This fixes it.

```
DISABLE_POST_INSTALL_SCRIPT='yes' #slackware
if [ -e ../shared-mime-info_NLS ]; then
	mkdir -p ../shared-mime-info_NLS/usr/share/mime/packages
	cp -a usr/share/mime/packages/freedesktop.org.xml ../shared-mime-info_NLS/usr/share/mime/packages/
fi
sed -i '/xml:lang/d' usr/share/mime/packages/freedesktop.org.xml
rm -rf install/ #slackware
```

Committing soon. Then doing a test run with a simple zstd compressed file to see if run action is fixed - if so will close.

**Comment by 01micko** [comment]
finally got .zst files working with pupzip both in s-m-i 2.1 (slackware) and 1.10 (puppy generic)
