### ISSUE TITLE
syslinux in slacko64-8 ?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2264]
@01micko 
Why does slacko64-8 use the syslinux version 4.0.7 from slackware when other builds use the 6.4 .pet in common64?

The line in DISTRO_PKGS_SPECS-slackware64-15.0 suggests a .pet is being used but is configured wrongly for a .pet:
yes|syslinux|syslinux|exe,dev>null,doc,nls| #must use my pet syslinux pkg..
should be:
yes|syslinux||exe,dev,doc,nls| #must use my pet syslinux pkg..
???

**Comment by 01micko** [comment]
That's an old comment "#must use my pet syslinux pkg". Why is it an issue?

I much prefer to use upstream for compatibility. I've had endless problems with 'common'

**Comment by peabee** [comment]
Big difference in version numbers...... 4.0.7 to 6.4
All other recent Woof-CE pups (FossaPup64 and DPupOs64) use the common64 version....
I've been alerted that a component (extlinux) is missing from the UPup32 builds due to the Ubuntu tendency to break things into smaller and smaller pieces - I need to decide what to do and part of the process was to look at what other Pups were doing.....

**Comment by 01micko** [comment]
Ok, and really doesn't matter about upstream in this case as syslinux is all static bins. I'll probably change for slacko.

BTW, there was no version 5 of syslinux as far as I'm aware.
