### ISSUE TITLE
.desktop files are opened with Geany when xdg-utils is installed

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2267]
xdg-open from rootfs-skeleton is replaced with the real deal, which opens .desktop files with Geany instead of running what's in Exec through `rox`.

When I install Chromium in dpup, it pulls this package.

**Comment by dimkr** [comment]
http://forum.puppylinux.com/viewtopic.php?f=146&t=2971

**Comment by 01micko** [comment]
Ok, approving.
