### ISSUE TITLE
Builder example cannot be repeated

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2283]
I saw [**this on the forum**](https://forum.puppylinux.com/viewtopic.php?p=26354#p26354) as a set of steps to build on GIT.

Using those steps, my test results follow: (no matter if logged into GITHUB or not)
![Instructions dont match1](https://user-images.githubusercontent.com/15698050/119570141-b9298600-bd7d-11eb-9558-9db65616bccd.jpg)
![Instructions dont match2](https://user-images.githubusercontent.com/15698050/119570142-b9c21c80-bd7d-11eb-8334-74e8bcf13209.jpg)

**No comment requested: This is an FYI.**

**Comment by dimkr** [comment]
@CollaboratorGCM You're not even logged in ...

(and btw, the difference in GitHub's layout are because of the super small resolution you're using, or because the Chrome window is small)
