### ISSUE TITLE
Duplicate Packages-puppy-noarch-official

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2307]
Why is Packages-puppy-noarch-official now duplicated in both
https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-distro
and now also in
https://github.com/puppylinux-woof-CE/woof-CE-noarch
??
Which is master??

**Comment by peabee** [comment]
I have updated https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-distro
for frugalpup-33.pet
but not 
https://github.com/puppylinux-woof-CE/woof-CE-noarch

**Comment by 01micko** [comment]
There is a script that generates the file. You _should_ run it on every update. Then it can be the main source. Saves duplication of effort.

**Comment by peabee** [comment]
Where is the script?
How do you "run it"?
Which file is "generated"?
Which "it" is the main source??
It's very confusing having 2 versions of the same database.........!!

**Comment by 01micko** [comment]
> Where is the script?

root of the repo

> How do you "run it"?

click it

> Which file is "generated"?

the `Packages-puppy-noarch-official`

> Which "it" is the main source??

The one in woof-ce for now

> It's very confusing having 2 versions of the same database.........!!

No it isn't. Generate it, copy to woof-ce

See https://github.com/puppylinux-woof-CE/woof-CE-noarch/commit/4e88c72f20e5d16061bb8ba7101b965519f0cf0f

EDIT: oh , I see, you don't use git cli, just upload files in github. Is that right?

**Comment by peabee** [comment]
> EDIT: oh , I see, you don't use git cli, just upload files in github. Is that right?

Yes!

**Comment by 01micko** [comment]
Ok, I'll try and figure something out with a CI. So then maybe you can run the script from github.

**Comment by peabee** [comment]
I don't understand the reason for the change - what "problem" were you trying to solve??

The wiki will need to change if there is a new process:
https://github.com/puppylinux-woof-CE/woof-CE/wiki/Adding-or-Updating-noarch-packages

What is the script called? I don't see it in my downloaded copies of woof-ce.....

**Comment by 01micko** [comment]
The database was a mess. Simple.

> What is the script called? I don't see it in my downloaded copies of woof-ce

Click the commit above for info. Otherwise I'll just delete it and carry on doing manual things if you aren't happy with it. By all means, you can take over from me if you want. I really don't have the time anyway.

**Comment by peabee** [comment]
> if you aren't happy with it.

Happiness doesn't really come into it...... just trying to understand why there are now 2 copies of the database and what needs to be done when a .pet is changed in the noarch repo.........

I can see a script called get_specs.sh in the noarch repo which seems to update the database in 
https://github.com/puppylinux-woof-CE/woof-CE-noarch

but not the one in
https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-distro

which is the one that all builds download and use?? (even the latest: https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/x86_64/slackware64/15.0/DISTRO_PET_REPOS and https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/x86_64/debian/bullseye64/DISTRO_PET_REPOS use it)

Is the plan to amend all builds to use https://github.com/puppylinux-woof-CE/woof-CE-noarch/blob/master/Packages-puppy-noarch-official ?? and then delete
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/Packages-puppy-noarch-official ?? (although builds out in the wild will try to download this via PPM update so it can't be deleted and must be kept up-to-date)

I only ever access the noarch repo via the github website - I don't download it or access it via devx/git.

Just trying to understand!

**Comment by 01micko** [comment]
I'll leave it how it is until I can figure out a decent work flow. 

The reason I automated the creation of the script is that there were errors in the old database. Not critical but an error is an error.

Maybe close this issue and raise a new one over at `woof-CE-noarch`?
