### ISSUE TITLE
ASPM is disabled in 5.10.x kernels

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2311]
```
CONFIG_PCIEASPM_DEFAULT=y
# CONFIG_PCIEASPM_POWERSAVE is not set
# CONFIG_PCIEASPM_POWER_SUPERSAVE is not set
# CONFIG_PCIEASPM_PERFORMANCE is not set
```

This could result in reduced battery life.

**Comment by gyrog** [comment]
Are you suggesting that all the commented options be set to "y"?
Have you tried it?
If so, did it make any noticable difference?

**Comment by dimkr** [comment]
> Are you suggesting that all the commented options be set to "y"?

Nope, but I'm suggesting that we see what Ubuntu does and align with that.

> Have you tried it?

Not yet. If this needs to be changed, I'll open a pull request and test it.

**Comment by gyrog** [comment]
@dimkr,
Aren't these changes to a kernel DOTconfig file?
If so, why not compile a kernel using a DOTconfig file containing the proposed changes, and run a Puppy with this kernel, before attempting to make any changes to woof-ce?

**Comment by dimkr** [comment]
> @dimkr,
> Aren't these changes to a kernel DOTconfig file?
> If so, why not compile a kernel using a DOTconfig file containing the proposed changes, and run a Puppy with this kernel, before attempting to make any changes to woof-ce?

I'll do the changes in a fork of woof-CE, build dpup or slacko, and do the testing. (And open a pull request.)

**Comment by dimkr** [comment]
Interesting, the Ubuntu 20.04 5.4.x kernel uses the same configuration.
