### ISSUE TITLE
Just a thought: Microcode loading on Puppy (late loading)

### ISSUE THREAD

**Issue by rizalmart** [puppylinux-woof-CE/woof-CE#2315]
What if we add command to update microcode of a cpu on /sbin/init script? What will be it's implication?
If ever microcode loading is implemented, Is there any way to detect if Puppy runs on physical machine or virtual machine using bash?

**Comment by CollaboratorGCM** [comment]
In S390 world, a bit in the PSW indicates bare-metal vs virtual.

I seem to remember that something similar was available in a X86/X86-64
machine instruction to report the same, but its been decades since I was
involved in that implementation.

**Comment by dimkr** [comment]
Debian loads microcode in the initramfs stage. Is it good enough to do this in rc.sysinit?

**Comment by rizalmart** [comment]
> Debian loads microcode in the initramfs stage. Is it good enough to do this in rc.sysinit?

Not all distro's loads microcode at initramfs stage. Also the update-microcode scripts that I made will simply just exit if early loading of microcode was detected

**Comment by dimkr** [comment]
Can we close this one?
