### ISSUE TITLE
GTK+ 3 pnote eats 60 MB of RAM on x86_64

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2325]
It's on by default, and it's a pretty big waste of RAM.

It's true that dialog and especially its GTK+ 3 variant can be resource hungry, but pnote deserves special attention because it's the only long-running gtkdialog process in a clean Puppy.

#2326 is only a partial solution, because it only reduce pnote's RAM consumption, and only on x86.

**Comment by dimkr** [comment]
@01micko How about disabling pnote by default? (instead of this hack, https://github.com/dpupos/woof-CE/blob/59911efa1ca8f43e47738ac14554a1f6f5c1ed50/woof-distro/x86_64/debian/bullseye64/_00build.conf#L144)

**Comment by 01micko** [comment]
Done in 5e6ccb77b
