### ISSUE TITLE
trouble with wolf-ce errors

### ISSUE THREAD

**Issue by Creatorson** [puppylinux-woof-CE/woof-CE#2345]
I am following this (https://github.com/puppylinux-woof-CE/woof-CE/wiki/Building-a-Puppy-on-GitHub), but the program seems to get stuck when it gets to the built-for architecture (see screenshots).  I am trying to build for AArch64 using "arm", distro FossaPup64, version 9.5 and with kernel 5.10.  Probably user error.  Any suggestions would be appreciated.  Thank you-

![Screenshot from 2021-06-18 20-33-50](https://user-images.githubusercontent.com/4780113/122657632-67350f80-d133-11eb-8b5f-d7a619d0964a.png)
![Screenshot from 2021-06-18 20-36-54](https://user-images.githubusercontent.com/4780113/122657643-7d42d000-d133-11eb-9fc3-e5037bfc4120.png)
![Screenshot from 2021-06-19 18-52-03](https://user-images.githubusercontent.com/4780113/122657668-bf6c1180-d133-11eb-8f02-740757bf41d4.png)
![Screenshot from 2021-06-19 18-53-36](https://user-images.githubusercontent.com/4780113/122657674-cabf3d00-d133-11eb-88cd-b6badb9918ec.png)

**Comment by dimkr** [comment]
Hi @Creatorson, it's a bug. `merge2out` gets stuck when you select a configuration that's not implemented. (It asks you to choose between options 1, 2, and 3, but you select 4 so it asks you again and again.)

There are multiple issues with the configuration you specified.

To build A Puppy similar to Fossapup64:
- "Architecture" should be `x86_64`, see https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-distro/
- "Compatible distro" should be `ubuntu`, see https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-distro/x86_64
- "Compatible distro version" should be `focal64`, see https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-distro/x86_64/ubuntu

Not every combination is implemented - for example, if you look at https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-distro/arm, you'll see that we only support Debian or Raspbian-based ARM builds.

Also, not all woof-CE provided kernels support all architectures - see https://github.com/puppylinux-woof-CE/woof-CE/actions/workflows/kernel-kit.yml and https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/951179534#artifacts. For example, we have 4.19.x for x86 and x86_64, but don't have ARM kernels for boards other than veyron-speedy.

And finally, I think you're looking for a 64-bit ARM build (aka `aarch64`, not `arm`) and woof-CE still doesn't support it.

EDIT: I updated the wiki page
