### ISSUE TITLE
dbus problem with latest woof-ce builds 27-june-2021

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2363]
In both Slacko64-8.2.2 and CagePup64 (details below) problem with dbus:
```
~$ dbus-monitor --session
Failed to open connection to session bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
Welcome to Slacko64 Puppy version 8.2.2, released Jun 2021
BUILD_FROM_WOOF='testing;6649757;2021-06-27 17:35:10 +1000;ALTERNATE_BUILD=15.0;EXTRA_MERGE='

CagePup64
BUILD_FROM_WOOF='testing;a795917;2021-06-26 18:25:56 +0300;ALTERNATE_BUILD=bullseye64;EXTRA_MERGE='

**Comment by peabee** [comment]
@dimkr asked me to try running gvfsd-trash as spot..........
All I can report is that both gvfsd-trash and dbus-monitor --session do not produce error messages if run-as-spot....
```
/usr/libexec$ run-as-spot dbus-monitor --session
signal time=1624848266.982306 sender=org.freedesktop.DBus -> destination=:1.8 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.8"
signal time=1624848266.982351 sender=org.freedesktop.DBus -> destination=:1.8 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.8"
^C

/usr/libexec$ run-as-spot ./gvfsd-trash
^C

/usr/libexec$ dbus-monitor --session
Failed to open connection to session bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

/usr/libexec$ ./gvfsd-trash
Error connecting to D-Bus: The connection is closed (g-io-error-quark, 18)
/usr/libexec$ 

```

**Comment by dimkr** [comment]
I wonder why applications running as root can't connect to spot's session bus. I'll do some `strace` to see what's going on.

I'll try to move these two lines (https://github.com/puppylinux-woof-CE/woof-CE/pull/2349/files#diff-8535880d33810dbedf207a6f3145c8fffea8aa4164bfaf2252eb0a9edffb84edR46) to `run-as-spot`, and see if Blueman and PulseAudio keep working.

**Comment by peabee** [comment]
Hi @dimkr any further ideas on what the problem is and how to solve it? Thanks.

**Comment by dimkr** [comment]
@peabee I'll be able to debug this tomorrow and on Sunday.

**Comment by dimkr** [comment]
@peabee Please try #2368 - I see that Blueman runs in a VM but fails only because it doesn't find a Bluetooth adapter. I'll test on a physical machine later today, and it should work.

**Comment by peabee** [comment]
Report:
Made a ydrv to "patch" slacko64-8.2.2 with amended files .xinitrc & run-as-spot
then also installed LXDE as an adrv
All good - trash was back in PcManFM and gvfsd-trash ran without errors as did dbus-monitor --session & --system
Also checked that chromium64 (which is run-as-spot) worked - it did.
Limited tests of pulseaudio and sound seemed sane as well.
Seems fine to me in my tests..........
Thanks
