### ISSUE TITLE
Make cdboot a local build

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#2391]
- [x] remove need to download
- [x] leverage `frugalpup` grub2 - saving us from using the old grub2 method or any other grub2 binaries
- [x] support 64 bit UEFI by default (32 optional in `_00build.conf`)
- [x] support 'secure boot'; frugalpup's grub2 does this - whereas @wdlkmpx debian grub2 used a debian .cer file to sign grub2 binaries - which perplexed me in the beginning when I first tried out booting Puppy with secure boot 'on' and seeing 'debian' in the keys
- [x] test on real hardware
- [x] don't break `isoboot` (that will be my test on real hardware)
This will depend on frugalpup and if that is not installed falls back to an isolinux/grub4dos boot

**Comment by 01micko** [comment]
All checks passed. :clinking_glasses:

**Comment by 01micko** [comment]
Actually dd'd to a stick to test real hardware with secure boot _on_

**Comment by bigpup1** [comment]
Have you seen this work by shinobar?
https://forum.puppylinux.com/viewtopic.php?f=155&t=3360

**Comment by dimkr** [comment]
We have way too many installers, and most of them are limited (BIOS only, UEFI with or without secure boot, only frugal installation/frugal or full, etc').

Can't we just delete all installers in woof-CE, integrate one installer (Frugalpup, grub2config, etc') in rootfs-packages, include it in all builds by default and make it support all useful installation types if it doesn't already?

**Comment by CollaboratorGCM** [comment]
It appears that @shinobar's work is a post process utility for discovery and setup of an existing PC and all the PUP, Linux and Windows it finds. It is a work-in-progress at the moment, but may have promise in the future as a "post-processor" **each time a user adds/changes their PC** with new OSes.

Right now, the ONLY current solution which addresses booting multiple WoofCEs with NO effort remains to be SG2D. Here, merely download the PUP/DOG ISO file to PC and on reboot it is found and presented along with all other Linux, Windows, PUPs found, to the user. The primary advantage that developers provided is "there are NO post processing steps...Ever. Merely download the WoofCE ISO and boot it directly to get ALL the same features that one gets in a Frugal without ever doing anything to either the system's drives or any post processing for a boot-manager update." Again, one of the 2 greatest benefits to SG2D is that it is **NOT a post processor** requiring the user to do any thought for PC setup for booting new things; merely download PUP ISO file(s) and boot to any selected to PUP desktop directly from the ISO file to get all of what a PUP/DOG offers.

This was a PUP game-changer for any tire-kicker or any experienced developer.

As most of the developers, here, know: Adding the loopback.cfg to the WoofCE process was all that was necessary for this productivity gain.

Further with SG2D, there is **NO developer efforts needed** as the Open source developer is committed supporting his work. With GRUB2-EFI, there is **no developer work needed** as the Open source community supports it.

Thus, with those elements, there is NO developer efforts needed for utility support.

**On ANOTHER Note**
I know of ONLY one other "non post-processing ISO file booter" that is comparable, but, the other struggles with some of the WoofCEs while SG2D handles all of the WoofCEs. The other misses 2 of the features of SG2D.

**Comment by CollaboratorGCM** [comment]
P.S. I hope all understands the differences I am pointing to in the above. 
1. SG2D (and the other) is a NON post processing utility! Environmental setup once; And NO user requirements afterwards.
2. All the others, including Grub2config, FrugalPup, ISObooter, ... **ARE** post processing utilities. Environmental setup & constant user requirements thereafter...

I am hopeful this understanding is clear. I find that many have trouble denoting the difference. Thus the benefit is missed or misunderstood.

Currently, **ALL** the work is presently done, since December 2019, for WoofCE PUPs-DOGs. SG2D is external and no developer work effort is required.

@gyrog update to PUP savefile processing facilitated SG2D for identifying the location of persistence (SAVESPEC).

**Comment by CollaboratorGCM** [comment]
I will create an HTML SG2D USB creator document for PUP inclusion to make it all too simple for user to build a USB for adding any modern WoofCE PUP ISO file(s) allowing user to boot on either a BIOS/UEFI PC with/without Secure boot.

**Comment by 01micko** [comment]
@CollaboratorGCM I have a simple script that builds a USB install for exactly 1 ISO file. More later on this.
