### ISSUE TITLE
Linux 5.12 is EOL

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#2403]
We need a config for 5.13

**Comment by peabee** [comment]
Same as 5.12 but:
CONFIG_PVPANIC=y
was:
CONFIG_PVPANIC=m

**Comment by 01micko** [comment]
need to fix `funcs.sh` in kernel-kit for 5.13 too

> Same as 5.12 but:
> CONFIG_PVPANIC=y
> was:
> CONFIG_PVPANIC=m

That's interesting that `CONFIG_PVPANIC=m` seems not allowed.
