### ISSUE TITLE
jwmconfig3 not found!

### ISSUE THREAD

**Issue by Phoenix-Starlight** [puppylinux-woof-CE/woof-CE#2414]
I cannot build bionic ubuntu puppy at all, as it fails due to the package jwmconfig3 not being found.

**Comment by peabee** [comment]
Presumably BionicPup64 ........... as 32 does not contain jwmconfig3 .......

Any reason why you are trying to build such an old Pup??

Google search quickly shows it is still available on ibiblio
https://distro.ibiblio.org/puppylinux/pet_packages-noarch/jwmconfig3-151025.pet

but hasn't made it to
https://github.com/puppylinux-woof-CE/woof-CE-noarch/tree/master/pet_packages-noarch
which is where noarch pets are now stored.........

@mrfricks it probably needs to be moved on ibiblio from noarch to https://distro.ibiblio.org/puppylinux/pet_packages-bionic64/

**Comment by Phoenix-Starlight** [comment]
Mainly because if its not broken, don't fix it. And I prefer lowest memory footprint whenever possible.

**Comment by dimkr** [comment]
> Mainly because if its not broken, don't fix it. And I prefer lowest memory footprint whenever possible.

@Phoenix-Starlight I fixed bionic64 builds and added it to the rotation of weekly testing builds (in https://github.com/puppylinux-woof-CE/woof-CE/pull/2419).

I booted the first build in a VM and to my surprise, memory usage was way more than other Puppy builds 🤔

**Comment by Phoenix-Starlight** [comment]
huh.
