### ISSUE TITLE
petbuilds busybox fails

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#2418]
when running woofce locally petbuilds fail on busybox.  
this is just a default build for fossapup no changes
```
busybox-1.33.1.tar.bz2: OK
busybox-guess_fstype.patch: OK
Building busybox
mount-FULL: /root/woof-out_x86_64_x86_64_ubuntu_focal64/sandbox3/petbuild-rootfs-complete-busybox: wrong fs type, bad option, bad superblock on petbuild, missing codepage or helper program, or other error.
chroot: can't execute 'sh': No such file or directory
umount-FULL: petbuild-rootfs-complete-busybox: not mounted.
rmdir: failed to remove 'petbuild-rootfs-complete-busybox
```

**Comment by dimkr** [comment]
You're probably using an old kernel ~without support for overlayfs~. What does `dmesg` say?

**Comment by mrfricks** [comment]
hi @dimkr 
dmesg error ...
```
unsupported filesystem, ../petbuild-output/busybox-68f0559094b3c3046bb31fa89c773fc2 (aufs)
```
my kernel config 
```
CONFIG_OVERLAY_FS=m
# CONFIG_OVERLAY_FS_REDIRECT_DIR is not set
# CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW is not set
# CONFIG_OVERLAY_FS_INDEX is not set
# CONFIG_OVERLAY_FS_XINO_AUTO is not set
# CONFIG_OVERLAY_FS_METACOPY is not set
```

**Comment by dimkr** [comment]
aufs is unsupported ... what distro are you running woof-CE on?

**Comment by mrfricks** [comment]
just a regular fossapup.  
would it work on the github produced iso?

**Comment by dimkr** [comment]
@mrfricks Yes, it should, but it also should work on Puppy.

You can grab an ISO at https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/1086152541#artifacts.

**Comment by peabee** [comment]
Why does a pet build system depend on an overlay file system.?........?
Aufs is the puppy standard...?
If there are kernel specific requirements they should be checked?

**Comment by dimkr** [comment]
> Why does a pet build system depend on an overlay file system.?........?

Because it's useful. By using aufs to merge devx+rootfs-complete+a temporary directory, we can build packages in a clean environment without having to copy devx onto rootfs-complete for every build.

> Aufs is the puppy standard...?

We're using Aufs. (And I intend to change that to overlayfs, because that's the standard outside of the Puppy world.)

> If there are kernel specific requirements they should be checked?

`unsupported filesystem ... (aufs)` is a pretty descriptive error, and I see no point in additional error checking here. `chroot` fails, and this fails the build.

**Comment by dimkr** [comment]
I see a pattern here, @peabee: you resist change, and criticize changes you become aware of. I don't know why, but #2191 is exactly what you need.

**Comment by mrfricks** [comment]
thanks this is working now in the github release iso.
so presumably the overlayfs needs to be built as builtin not a module for petbuilds to work?
```
CONFIG_OVERLAY_FS=y
```

also is there some way to select which .pets you want/don't want to build? 
for instance i don't want sylpheed,transmission,gpicview,lxterminal,cage,pa-applet,rxvt-unicode,geany

**Comment by dimkr** [comment]
@mrfricks It's not related to overlayfs, because we don't use it in petbuilds.sh (you can see "aufs" in your `dmesg`). I don't know why this error happened, it's the first time I see this 🤷🏿 

> also is there some way to select which .pets you want/don't want to build?

Soon, #2426
