### ISSUE TITLE
Petbuild of busybox fails for local build of slacko32-8.2.2

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2425]
@01micko @dimkr 

Trying to build slacko32-8.2.2 locally.......
Busybox petbuild fails.........2 different build environments with different failures.....

Using slacko-8.2.2-51.iso + devx_slacko_8.2.2-51.sfs failure is:
```
Using GTK+ 2 for x86 petbuilds
Preparing build environment
Downloading busybox
busybox-1.33.1.tar.bz2: OK
busybox-guess_fstype.patch: OK
Building busybox
chroot: can't execute 'sh': No such file or directory
umount-FULL: petbuild-rootfs-complete-busybox: not mounted.
rmdir: failed to remove 'petbuild-rootfs-complete-busybox': Directory not empty
ERROR: failed to build busybox

```
Using ScPup32-21.04+3-T.iso + devx_ScPup32_21.04+3.sfs gets further but failure is:
```
HOSTCC  scripts/basic/fixdep
In file included from /usr/include/bits/posix1_lim.h:161,
                 from /usr/include/limits.h:195,
                 from /usr/lib/gcc/i586-slackware-linux/10.3.0/include-fixed/limits.h:195,
                 from /usr/lib/gcc/i586-slackware-linux/10.3.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/i586-slackware-linux/10.3.0/include-fixed/limits.h:34,
                 from scripts/basic/fixdep.c:113:
/usr/include/bits/local_lim.h:38:10: fatal error: linux/limits.h: No such file or directory
   38 | #include <linux/limits.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.host:104: scripts/basic/fixdep] Error 1
make[1]: *** [/tmp/busybox-1.33.1/Makefile:357: scripts_basic] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:522: include/autoconf.h] Error 2
ERROR: failed to build busybox
```
there are many limits.h in the system.

**Comment by dimkr** [comment]
@peabee Try to add `set -x` to petbuilds.sh, somewhere before the chroot line, and try to do that chroot manually. If it doesn't work, then something is horribly wrong (`/bin/sh` can't run). Also, I'd look at `file rootfs-complete/bin/sh` and `dmesg`).

**Comment by dimkr** [comment]
@peabee Also make sure you don't have errors during 2createpackages. A faulty bash package can explain why `can't execute 'sh': No such file or directory`,

**Comment by 01micko** [comment]
In scpup I believe it's kernel-headers you miss.

**Comment by peabee** [comment]
I loaded kernel headers for the host kernel.....should  they be for the build kernel??

**Comment by 01micko** [comment]
loaded? Kernel-sources != kernel headers.

**Comment by peabee** [comment]
Also....
I was doing my _usual_ mix of 64 bit kernel with a 32 bit build ...
Maybe this doesn't work with this petbuild system 
I'll try a 32 bit kernel tomorrow

**Comment by peabee** [comment]
Both sources and headers loaded from sfs

**Comment by 01micko** [comment]
I _always_ use upstream headers; I think the rule of thumb is to use the kernel headers that upstream used to build glibc. That's why always install them to the devx. Kernel sources are only useful for compiling out of tree or 3rd party kernel modules, I rarely use them.

Some packages don't build without them (kernel headers) - Abiword is a notable one.

**Comment by dimkr** [comment]
> I loaded kernel headers for the host kernel.....should they be for the build kernel??

Kernel headers for the host kernel are not related. The build is done inside a chroot.

**Comment by dimkr** [comment]
> I was doing my _usual_ mix of 64 bit kernel with a 32 bit build ...

In CI, 32-bit builds are done on x86_64, but 1download, 2createpackages, etc', are all wrapped with linux32. woof-CE thinks it's doing a x86 to x86 build, and not a x86_64 to x86 build as in your case, **unless you use linux32 too**. I don't know if woof-CE works when doing a x86 build on x86_64, without using linux32, but I think it should.

In https://github.com/puppylinux-woof-CE/woof-CE/pull/2428, I'm making CI do x86_64 to x86 cross-builds (without linux32), to simulate your use case. This will ensure woof-CE keeps working in this configuration.

EDIT: confirmed, slacko32 builds just fine here, from x86_64. My best bet is that your /bin/sh (the bash package?) is missing or corrupt.

**Comment by peabee** [comment]
I am doing the build of slack32-8.2.2 on 32-bit systems with 32-bit kernels... I think the fact that the huge kernel was 64-bit was a red herring as 3builddistro had got nowhere near installing it.....
Here is the build log from my last attempt on scpup32 with devx and kernel-headers-5.13.7_smp-x86-1.txz installed:
[030821-false.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/6923650/030821-false.gz)

I'm using the slacko32-8 build pack so unsure how /bin/sh could be missing or corrupt??

**Comment by 01micko** [comment]
Must be a host system issue. I'm building latest on my _early_ dev version of slacko32-8x

```
~$ cat /etc/DISTRO_SPECS 
#One or more words that identify this distribution:
DISTRO_NAME='Slacko Puppy'
#version number of this distribution:
DISTRO_VERSION=8.2
#The distro whose binary packages were used to build this distribution:
DISTRO_BINARY_COMPAT='slackware'
#Prefix for some filenames: exs: slackosave.2fs, slacko-8.0.sfs
DISTRO_FILE_PREFIX='slacko'
#The version of the distro whose binary packages were used to build this distro:
DISTRO_COMPAT_VERSION='15.0'
#the kernel pet package used:
DISTRO_KERNEL_PET='Huge_Kernel'
DISTRO_XORG_AUTO='yes'
DISTRO_DB_SUBNAME='slacko15.0'
WOOF_VERSION=9
DISTRO_TARGETARCH='x86'
NO_MULTIARCH_SYMLINK=1
BUILD_FROM_WOOF='gtk3;459e96518;2021-05-09 20:28:00 +1000'
#Puppy default filenames...
#Note, the 'SFS' files below are what the 'init' script in initrd.gz searches for,
#for the partition, path and actual files loaded, see PUPSFS and ZDRV in /etc/rc.d/PUPSTATE
DISTRO_PUPPYSFS='puppy_slacko_8.2.sfs'
DISTRO_ZDRVSFS='zdrv_slacko_8.2.sfs'
DISTRO_FDRVSFS='fdrv_slacko_8.2.sfs'
DISTRO_ADRVSFS='adrv_slacko_8.2.sfs'
DISTRO_YDRVSFS='ydrv_slacko_8.2.sfs'
DISTRO_PUPPYDATE='May 2021'
```

[3builddistro.log.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/6923796/3builddistro.log.gz)

_real_ gzip file

**Comment by 01micko** [comment]
@peabee `scpup` is a bit of a 'mongrel'. Using slackware-current and slackware-14.2 packages in a mix isn't really the recipe for a stable distro IMHO. As stated, I'm not a fan _at all_ of 'common' packages. See #2427 for one example.  _Something **may**_ be missing from the host, but what?  Did you edit the original specs for slacko-8.2.2? With out _all_ the info we can't really deduce what is happening.

Step one is to **delete bash-5.1.008-i586-1.txz** and redownload and rebuild.

**Comment by dimkr** [comment]
> I'm using the slacko32-8 build pack so unsure how /bin/sh could be missing or corrupt??

petbuilds rely on the /bin/sh inside rootfs-complete (the Puppy you're building) and not the one on the host. It could be corrupt or missing, if the bash package is corrupt or missing.

**Comment by peabee** [comment]
@01micko @dimkr 
Still got major problems..........
Went right back to square 1 - downloaded build-x86-slackware-15.0-53.zip - setup new frugal install from slacko64-8.2.2-53.iso and loaded devx_slacko_8.2.2-53.sfs - downloaded BUILD_FROM_WOOF='testing;cf7ebc6cf;2021-08-03 18:10:04 +0000' - did new merge2out of woof-out_x86_x86_slackware_15.0
Did 0setup 1download and complete 2createpackages - checked that bash was present in packages-slacko

Made no changes whatsoever other than to put set -x into /support/petbuilds.sh at line 98

Did 3builddistro which failed whilst doing petbuild of busybox........build log:
[040821-false.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/6930274/040821-false.gz)

Contents of /sandbox3/petbuild-rootfs-complete-busybox do not look right after build failure:
![screenshot](https://user-images.githubusercontent.com/5926865/128159748-49a31992-855f-4cad-a554-5a46079bfbf0.png)

I notice this in build log - no idea if significant:

> LD       ccache
> /usr/bin/ld: src/util.o: in function `get_home_directory':
> util.c:(.text+0x342): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

**Comment by peabee** [comment]
@dimkr 
What are petbuild-rootfs-complete and petbuild-rootfs-complete-busybox used for?
petbuild-rootfs-complete you can chroot into
but
petbuild-rootfs-complete-busybox you can't.... although petbuilds.sh tries to....

**Comment by peabee** [comment]
I am running on an ext4 partition - is this a problem??

**Comment by dimkr** [comment]
> What are petbuild-rootfs-complete and petbuild-rootfs-complete-busybox used for?

petbuild-rootfs-complete is a copy of rootfs-complete, plus tools like ccache, used to greatly speed up the build.

petbuild-rootfs-complete-busybox is an aufs file system that's used to merge petbuild-rootfs-complete, devx and a directory for the petbuild output.

> I notice this in build log - no idea if significant:

No, it's a normal warning. We build a static busybox executable on the host, so we can use it to build a second busybox inside the chroot. Statically linked executables that use glibc still do dynamic loading of shared objects, hence the warning.

> I am running on an ext4 partition - is this a problem??

No.

**Comment by dimkr** [comment]
> Did 3builddistro which failed whilst doing petbuild of busybox........build log:
> 040821-false.gz

The logs indicate there's no /bin/bash inside the chroot.

Try this:

```
find packages-slacko/bash
```

If the output is empty, then the bash package is corrupt, missing or empty.

**Comment by peabee** [comment]
# find packages-slacko/bash
packages-slacko/bash
packages-slacko/bash/install
packages-slacko/bash/install/doinst.sh
packages-slacko/bash/install/slack-desc
packages-slacko/bash/bin
packages-slacko/bash/bin/sh
packages-slacko/bash/bin/bash
packages-slacko/bash/usr
packages-slacko/bash/usr/bin
packages-slacko/bash/usr/bin/sh
packages-slacko/bash/usr/bin/bash
packages-slacko/bash/usr/lib
packages-slacko/bash/usr/lib/bash
packages-slacko/bash/usr/lib/bash/rm
packages-slacko/bash/usr/lib/bash/sync
packages-slacko/bash/usr/lib/bash/finfo
packages-slacko/bash/usr/lib/bash/csv
packages-slacko/bash/usr/lib/bash/print
packages-slacko/bash/usr/lib/bash/tty
packages-slacko/bash/usr/lib/bash/strftime
packages-slacko/bash/usr/lib/bash/loadables.h
packages-slacko/bash/usr/lib/bash/sleep
packages-slacko/bash/usr/lib/bash/rmdir
packages-slacko/bash/usr/lib/bash/seq
packages-slacko/bash/usr/lib/bash/truefalse
packages-slacko/bash/usr/lib/bash/dirname
packages-slacko/bash/usr/lib/bash/pathchk
packages-slacko/bash/usr/lib/bash/mypid
packages-slacko/bash/usr/lib/bash/mkfifo
packages-slacko/bash/usr/lib/bash/head
packages-slacko/bash/usr/lib/bash/realpath
packages-slacko/bash/usr/lib/bash/id
packages-slacko/bash/usr/lib/bash/mktemp
packages-slacko/bash/usr/lib/bash/push
packages-slacko/bash/usr/lib/bash/basename
packages-slacko/bash/usr/lib/bash/Makefile.inc
packages-slacko/bash/usr/lib/bash/fdflags
packages-slacko/bash/usr/lib/bash/accept
packages-slacko/bash/usr/lib/bash/cut
packages-slacko/bash/usr/lib/bash/unlink
packages-slacko/bash/usr/lib/bash/ln
packages-slacko/bash/usr/lib/bash/logname
packages-slacko/bash/usr/lib/bash/printenv
packages-slacko/bash/usr/lib/bash/whoami
packages-slacko/bash/usr/lib/bash/tee
packages-slacko/bash/usr/lib/bash/uname
packages-slacko/bash/usr/lib/bash/setpgid
packages-slacko/bash/usr/lib/bash/mkdir
packages-slacko/bash/usr/share
#

**Comment by dimkr** [comment]
> packages-slacko/bash/bin/bash

What does `file packages-slacko/bash/bin/bash` say?

**Comment by peabee** [comment]
# file packages-slacko/bash/bin/bash
packages-slacko/bash/bin/bash: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, stripped

**Comment by dimkr** [comment]
What does `file petbuild-cache/bash` say?

**Comment by peabee** [comment]
# file petbuild-cache/bash
petbuild-cache/bash: cannot open `petbuild-cache/bash' (No such file or directory)

**Comment by peabee** [comment]
there's only ccache in petbuild-cache

**Comment by dimkr** [comment]
Do you have any way (and the willingness) to share your entire woof-output-* directory?

**Comment by peabee** [comment]
812.6 MB..........
http://smokey01.com/peebee/downloads/test/woof-out_x86_x86_slackware_15.0.sfs
md5 = 4cab4c4c7175036c635f619ddeca38c1

**Comment by dimkr** [comment]
Stopped 3builddistro after busybox, it worked from a x86_64 host 🤔 

```
++ chroot petbuild-rootfs-complete-busybox bash -ec 'cd /tmp && . ./petbuild && build'
patching file util-linux/guess_fstype.c
  GEN     include/applets.h
  GEN     include/usage.h
  GEN     scripts/Kbuild
  GEN     networking/Kbuild
...
```

```
bash-5.1# file petbuild-output/busybox-*/bin/busybox
petbuild-output/busybox-4c09c0048b3e948dbde3c83e7ce2bd9f/bin/busybox: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 3.2.0, stripped
```

**Comment by peabee** [comment]
@dimkr  Does #2430 fix 32-bit host 32-bit target builds?

**Comment by dimkr** [comment]
@peabee #2430 doesn't fix anything, it only makes the build slightly faster (there's no point in building a fast, native busybox or bash, if it's a x86_64 to x86 build, because we're not cross-compiling really).
