### ISSUE TITLE
Github problem warning emails

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2443]
@01micko @dimkr 
Have you had the warning emails?
What do we plan to do about it??

> You've used 100% of included services for the puppylinux-woof-CE account
> Shared storage usage
> Hello! We wanted to provide you with an update on your usage and spending.
> Storage used
> 1,467MB of 512MB included

**Comment by dimkr** [comment]
@peabee Yes, it's my fault. I did an experiment with automated releases in a separate repo, and deleted it now.

**Comment by peabee** [comment]
Something we need to keep an eye on for future..............

**Comment by Butterfly** [comment]
Hopefully this comes out the way it's intended, grin. Now that you all have said this out loud here, please be super extra careful to make sure that any future warnings are actually coming from Github. Someone might try to bait you all in now that they see you're watching for this. :smile:

**Comment by peabee** [comment]
There are 55 old builds listed in woof-ce actions - should they be deleted??
ditto 41 old kernel kits??
ditto 54 dpupos?? (disabled)
ditto 103 c201?? (disabled)

**Comment by dimkr** [comment]
They're deleted, @peabee. Jobs != artifacts != releases != packages.

(For example, try to download the build artifacts from https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/891348227#artifacts)
