### ISSUE TITLE
Do NOT commit something to repel a draft PR

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#2450]
@peabee 

What is the meaning of 2fa3987 , f590183 and 4fbe12e ?

#2445 is still only a draft let alone merged and you have the audacity to preempt this being merged?  I find it a bit more than cheeky and downright rude.

**If you continue to directly commit stuff without consultation I don't mind removing your commit rights to this repo.**

If you object to my frank attitude, say so, but someone _has_ to draw a line somewhere. :angry:

**Comment by peabee** [comment]
Sorry - as it was just a comment to remind future builders that this might be an option.........
I agree it was slightly premature......

**Comment by 01micko** [comment]
The thing is, 'premature' isn't really an excuse. Please be more mindful in the future. Be aware that everything is logged to the commit log. I learned that the hard way.

**Comment by dimkr** [comment]
@peabee Please revert these changes, they conflict with my draft. If my PR doesn't get merged, these lines don't do anything, and they might mislead users (USR_SYMLINKS=yes doesn't work in testing). Also, the default in my draft is USR_SYMLINKS=no and it's an opt-in feature, so there's no need for these changes.

> If you object to my frank attitude, say so, but someone _has_ to draw a line somewhere. 😠

Without diving into social contract theories - I think projects like this are easier to work on when only one person has direct commit (= pull/merge) rights and all changes happen via pull requests.

**Comment by peabee** [comment]
'Fraid I don't know how to revert............
I can re-edit........

**Comment by dimkr** [comment]
> 'Fraid I don't know how to revert............

`git revert`

Opened #2451.

**Comment by 01micko** [comment]
> Without diving into social contract theories - I think projects like this are easier to work on when only one person has direct commit (= pull/merge) rights and all changes happen via pull requests.

Not altogether practical. Last week I had no 'net while moving. I could have some other catastrophic event impeding my ability to commit.

OTOH, Even I have been issuing PRs lately, except for trivial changes to slacko configs.
