### ISSUE TITLE
kernel-kit 32-bit builds no longer include aufs-util ?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2462]
Is this change deliberate? Are there any consequences?

Checked build 45:
kernel-kit-output-5.4.x-x86.zip
kernel-kit-output-5.10.x-x86.zip

**Comment by 01micko** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/runs/3395636806?check_suite_focus=true#step:4:3321

build failure.

**Comment by peabee** [comment]
Thanks

**Comment by dimkr** [comment]
Should be fixed by #2465.
