### ISSUE TITLE
Bad info on installing Puppy on puppylinux.com

### ISSUE THREAD

**Issue by bigpup1** [puppylinux-woof-CE/woof-CE#2485]
https://puppylinux.com/install.html
Says to follow this dd tutorial to do an install to USB.
The dd tutorial https://www.toolbox.com/tech/how-to/blogs/howto-create-a-bootable-linux-media-using-the-dd-command-030915/
Has some comments about problems trying to use the example dd command to install Puppy versions to a USB. 

Someone that can edit puppylinux.com needs to look into this issue.

**Comment by CollaboratorGCM** [comment]
I think WoofCE builds 'should' include BArryK's EasyDD for all buildings. He supports it, its universal, and it provided use is written well by him as he actively maintains it. So, no WoofCE development resources are needed in its incorporation.

I also understand @BigPUP1's concern for info which can be better understood. Downloading a PUP all people understand. But foolproof steps to prep for booting is essential.

Instructions are one-way, and if they include EasyDD, as a "PUP staple", the user community might reduce headaches seen in the past.

**Comment by bigpup1** [comment]
I agree EasyDD is a very good program.
I use it all the time in Puppy Linux.

But the install info is for someone that does not have a Puppy version to run.
So, the info has to be how to do it in some other operating system.
That is why I posted this in the Puppy forum:
https://forum.puppylinux.com/viewtopic.php?f=156&t=157

**Comment by 01micko** [comment]
https://github.com/puppylinux-woof-CE/puppylinux-woof-CE.github.io/issues

Closing this, post at the link.
