### ISSUE TITLE
xorg-autoconf fails in qemu

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#2486]
xorg-autoconf fails in qemu when using the virtio_gpu driver. 
adding .....
```
probe_qemu(){
	cp -r /etc/X11/xorg.conf.udev /etc/X11/xorg.conf

}
```
&
```
1af4) probe_qemu ;;
```
fixes it for me but @rizalmart needs to check that this fix is ok

**Comment by rizalmart** [comment]
> xorg-autoconf fails in qemu when using the virtio_gpu driver.
> adding .....
> 
> ```
> probe_qemu(){
> 	cp -r /etc/X11/xorg.conf.udev /etc/X11/xorg.conf
> 
> }
> ```
> 
> &
> 
> ```
> 1af4) probe_qemu ;;
> ```
> 
> fixes it for me but @rizalmart needs to check that this fix is ok

@mrfricks thanks for pointing out the vendor code for Red hats' virtio. I will fix the xorg-autoconf since the purpose of xorg-autoconf was generating script

**Comment by rizalmart** [comment]
I made a PR now about this issue. I hope it works when merged
#2506

**Comment by rizalmart** [comment]
@mrfricks 
Could please test this new revision PR #2511 of xorg-autoconf?

**Comment by mrfricks** [comment]
hi @rizalmart 
yes this is working for me now 👍
FYI my device section now looks like this
```
Section "Device"
      Identifier  "Card0"
EndSection
```
thanks!
