### ISSUE TITLE
ydrv breaks 3builddistro

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#2492]
adding packages to YDRV_INC="picpuz" in _00build.conf breaks 3builddistro.
 /sandbox/rootfs-complete ends up like this 
![rootfs](https://user-images.githubusercontent.com/1454550/132367816-6ccc12c0-6f72-426e-ae25-b9d111106430.png)
instead of the usual /usr /bin /etc /sbin blah

ADRV_INC="" is working fine

**Comment by dimkr** [comment]
Doesn't reproduce in dpup, with `YDRV_INC="galculator"` and latest testing. Can you share your DISTRO_*?

**Comment by mrfricks** [comment]
hi dimkr,  
just tried in the latest dpupbullseye-9.0.0-65 and it happens in that as well as fossapup with the latest woofce.
i investigated it a bit further and discovered that it doesn't happen if there's also stuff sent to the adrv :/

doesn't work
```
ADRV_INC=""
YDRV_INC="gnumeric"
FDRV_INC=""
```
works
```
ADRV_INC="abiword"
YDRV_INC="gnumeric"
FDRV_INC=""
```

**Comment by dimkr** [comment]
Thanks! Reproduced with dpup. Investigating.

EDIT: I extracted this part out of 3builddistro:

```
. ./DISTRO_SPECS
. ./DISTRO_PKGS_SPECS-debian-bullseye
. ./_00build.conf

echo "Copying to sandbox3/rootfs-complete..."
EXTRAS_LIST="${ADRV_INC// /|} ${YDRV_INC// /|} ${AFDRV_INC// /|}"
if echo "$EXTRAS_LIST" | grep -qvE "[a-z]";then
        DUMMY=""
else
        DUMMY=XXXX #unless they make a Qld beer proggy 'XXXX' will never match; besides need a trailing field
        EXTRAS_LIST="${EXTRAS_LIST// /|}${DUMMY}"
        EXTRAS_LIST="${EXTRAS_LIST//^|}" #strip leading "|"
        EXTRAS_LIST="${EXTRAS_LIST//||/|}" #replace double "||" with "|"
fi
if [ -n "${DUMMY}" ];then
        PKGLIST="`echo "$PKGS_SPECS_TABLE" | grep '^yes' | sed s/#.*//g | grep -vE "${EXTRAS_LIST}" | cut -f 2 -d '|' | tr '\n' ' '`"
else
        PKGLIST="`echo "$PKGS_SPECS_TABLE" | grep '^yes' | sed s/#.*//g | cut -f 2 -d '|' | tr '\n' ' '`"
fi
PKGLIST="${PKGLIST}"
```

Here's the output, when running with -x, when using ADRV_INC and YDRV_INC, respectively:

[adrv.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/7139341/adrv.txt)
[ydrv.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/7139343/ydrv.txt)

The problem is the space at the beginning, which becomes a `|` (a catch-all expression):

```
$ (echo a; echo b) | grep -vE '|firefox-esr|galculator|libavcodec|libva|XXXX'
$ (echo a; echo b) | grep -vE 'firefox-esr|galculator|libavcodec|libva|XXXX'
a
b
```

This line, which is supposed to remove that leading `|`, doesn't work:

```
        EXTRAS_LIST="${EXTRAS_LIST//^|}" #strip leading "|"
```

```
$ EXTRAS_LIST="|ab|cd"
$ echo "${EXTRAS_LIST//^|}"
|ab|cd
```

I'll fix this tomorrow.

EDIT 2: it's impressive how much time this + the typo FDRV_INC went unnoticed

```
413b332095 (wdlkmpx      2019-08-18 09:49:44 +0800  234) EXTRAS_LIST="${ADRV_INC// /|} ${YDRV_INC// /|} ${AFDRV_INC// /|}"
```

**Comment by dimkr** [comment]
@mrfricks Please try my fix, it's pretty simple and doesn't try to refactor all the ugliness in that part of 3builddistro.

**Comment by mrfricks** [comment]
hi @dimkr ,
i tried your fix and it seemed to work, /sandbox/rootfs-complete was populated normally, however all is not well.

this was my test
```
ADRV_INC="deadbeef"
YDRV_INC="galculator osmo"
```
my ADRV ended up with deadbeef lxtask & mypaint inside.
my YDRV just had galculator & osmo as it's supposed to.
but the main puppy.sfs had all the files above still in it, even though they should of been redirected.

FYI i didn't try this on a pristine woofce .... will hopefully get time tonight to try

**Comment by dimkr** [comment]
> my ADRV ended up with deadbeef lxtask & mypaint inside.

That's because of how petbuilds.sh works (at the moment, this can be changed). If there's something in ADRV_INC, all petbuilds that contain .desktop files get automatically redirected to adrv.

EDIT: done, now the selection of petbuilds that get redirected to adrv is manual

**Comment by mrfricks** [comment]
hi @dimkr ,

the advr & ydrv are now building correctly :)

but you may have missed the other issue i mentioned in my last post.

whatever is redirected to the adrv or ydrv is still being built into the main puppy.sfs!
so deadbeef & vidcutter is in the adrv and also in the puppy.sfs ......duplicated.

**Comment by dimkr** [comment]
@mrfricks Fixed in e241509

**Comment by dimkr** [comment]
Merged the fixes to testing - please verify that the issue is gone, and we'll close it.

**Comment by mrfricks** [comment]
hi @dimkr ,

yes all the above are working for me now thankyou!

there is another problem though with 3builddistro in that it doesn't delete any previous /sandbox3/adrv, ydrv (and i suspect fdrv) before starting the build.  

e.g...   i do a build
```
ADRV_INC="simsu palemoon mpv deadbeef"
```
then change my mind, remove 'palemoon' & 'simsu' and run the build again
```
ADRV_INC="mpv deadbeef"
```
the resulting second adrv.sfs still contains 'palemoon' & 'simsu'

**Comment by dimkr** [comment]
@mrfricks It's an old issue - I always delete the directories manually.

I agree this needs to be fixed, so I opened https://github.com/puppylinux-woof-CE/woof-CE/pull/2502.

**Comment by mrfricks** [comment]
thanks @dimkr 
i'll close this issue now
