### ISSUE TITLE
Tovalds concern for GITHUB

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2493]
**[NTFS Support & Garbage](https://www.theregister.com/2021/09/06/github_merges_useless_garbage_says/)**

**FYI**

**Comment by 01micko** [comment]
@CollaboratorGCM 

We all have news feeds of some degree, or at least access to linux news and developments. It is _quite_ unnecessary to post this and similar as a "woof" issue. It is more suited to a forum discussion.
