### ISSUE TITLE
dpkg-deb needs to handle zstd debs

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2517]
From 21.10 Impish Indri Ubuntu .debs can be zstd compressed....
dpkg-deb needs an update to handle zstd debs

Recent Ubuntu builds should be OK
Slackware has an (old) .pet and this needs to be updated
Debian dpkg-deb also does not support zstd compressed debs

**Comment by 01micko** [comment]
A `.deb` package is simply an `ar` archive. They are pretty easy to extract with standard tools, probably even recent `busybox ar` and whatever compression is used on the payload.

**Comment by 01micko** [comment]
Actually, does `busybox dpkg-deb` work for you?

**Comment by peabee** [comment]
@01micko  Sadly not..........
```
Distro: Slacko Puppy 8.2.2-74

$ dpkg-deb -f binutils-i686-linux-gnu_2.37-7ubuntu1_i386.deb 
dpkg-deb: error: archive 'binutils-i686-linux-gnu_2.37-7ubuntu1_i386.deb' uses unknown compression for member 'control.tar.zst', giving up

$ busybox dpkg-deb -f binutils-i686-linux-gnu_2.37-7ubuntu1_i386.deb 

$ busybox dpkg-deb -f acl_2.2.53-10ubuntu1_i386.deb 
Package: acl
Version: 2.2.53-10ubuntu1
Architecture: i386
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Guillem Jover <guillem@debian.org>
Installed-Size: 188
Depends: libacl1 (= 2.2.53-10ubuntu1), libc6 (>= 2.33)
Section: utils
Priority: optional
Multi-Arch: foreign
Homepage: https://savannah.nongnu.org/projects/acl/
Description: access control list - utilities
 This package contains the getfacl and setfacl utilities needed for
 manipulating access control lists. It also contains the chacl IRIX
 compatible utility.

```

**Comment by 01micko** [comment]
Latest `dpkg` compiles fine under slacko-8x .. but IDK if it will work with a deb with zstd. Can you post a link?

**Comment by peabee** [comment]
http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-i686-linux-gnu_2.37-7ubuntu1_i386.deb

**Comment by 01micko** [comment]
Fails.

However, `busybox ar x ` works.

```
~/Downloads/bin-deb$ busybox ar x binutils-i686-linux-gnu_2.37-7ubuntu1_i386.deb 
~/Downloads/bin-deb$ ls
binutils-i686-linux-gnu_2.37-7ubuntu1_i386.deb  data.tar.zst   x
control.tar.zst                                 debian-binary
```

Somewhat later..

*However*

If I compile from Ubuntu-impish sources (same version) it works!

```
~/Downloads/bin-deb$ dpkg-deb -x binutils-i686-linux-gnu_2.37-7ubuntu1_i386.deb x
~/Downloads/bin-deb$
```

```
~/Downloads/bin-deb$ ldd `which dpkg-deb`
	linux-vdso.so.1 (0x00007ffc92497000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f62c7470000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f62c7390000)                   #### there it is
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f62c7368000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f62c7355000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f62c7176000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f62c7155000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f62c748c000)
```

I'll attach a pet - unzip it. (64 and 32)



[dpkg-deb-64.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/7271036/dpkg-deb-64.zip)

[dpkg-deb-32.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/7270065/dpkg-deb-32.zip)

**Comment by peabee** [comment]
-64.zip only contains empty directory......
-32.zip has a .pet in it.........

**Comment by 01micko** [comment]
Sorry, should be fixed.

Does the 32 work for you?

**Comment by peabee** [comment]
Yes - thanks
@dimkr - the dpkg-deb in vanilladpup-9.0.5 has the same issue...... maybe the Ubuntu update will be back-ported to Debian??

**Comment by dimkr** [comment]
> Yes - thanks @dimkr - the dpkg-deb in vanilladpup-9.0.5 has the same issue...... maybe the Ubuntu update will be back-ported to Debian??

Maybe. I don't know, but I'm against mixing Ubuntu packages with Debian packages, so I won't fix this in dpup unless the fix comes from Debian.
