### ISSUE TITLE
New monitor is not enabled automatically and Cage needs to be restarted

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2521]
Happens on my Thinkpad X220 and an old Panasonic TV plugged in using a HDMI to DisplayPort adapter.

Once Cage is restarted, the display is extended properly.

- [x] Check if https://github.com/Hjdskes/cage/pull/210 fixes this issue

**Comment by 01micko** [comment]
Ok, rebuilt slacko64 from latest and while it is an improvement (in that I am actually posting here) the dual monitors are reversed. ~, and possibly could be fixed with `xrandr`..~ 

```
~$ xrandr
Screen 0: minimum 16 x 16, current 3840 x 1080, maximum 32767 x 32767
XWAYLAND6 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 480mm x 270mm
   1920x1080     59.96*+
XWAYLAND7 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 480mm x 270mm
   1920x1080     59.96*+
```

note that XWAYLAND6 starts at +1920+0

**Comment by dimkr** [comment]
What did you see before, and what do you see now? Are both monitors connected using HDMI?

**Comment by 01micko** [comment]
Before the patch I had no input after `quicksetup` with dual monitors.

Now the left screen is on the right. Sure I could switch monitor positions and it would be quite useful, but certainly not the solution.

Neither is connected via HDMI

Here is my `xrandr`on xorg.

```
~$ xrandr
Screen 0: minimum 320 x 200, current 3840 x 1080, maximum 16384 x 16384
HDMI-0 disconnected primary (normal left inverted right x axis y axis)
DVI-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
VGA-0 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1280x1024     75.02    60.02  
   1440x900      59.89  
   1280x960      60.00  
   1280x800      59.81  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
```

**Comment by dimkr** [comment]
Testing a patch for X.Org-like monitor placement.

Cage uses the "automatic" wlroots layout selection logic:

https://github.com/swaywm/wlroots/blob/3d0848daae40a8a471282431eac8310e5d051d33/types/wlr_output_layout.c#L87

```
/**
 * This must be called whenever the layout changes to reconfigure the auto
 * configured outputs and emit the `changed` event.
 *
 * Auto configured outputs are placed to the right of the north east corner of
 * the rightmost output in the layout in a horizontal line.
 */
```

But all displays are auto-configured in our setup, because we don't use wlr-randr or something, so we reach this block:

```
	if (max_x == INT_MIN) {
		// there are no manually configured outputs
		max_x = 0;
		max_x_y = 0;
	}

	wl_list_for_each(l_output, &layout->outputs, link) {
		if (!l_output->state->auto_configured) {
			continue;
		}
                ...
		l_output->x = max_x;
		l_output->y = max_x_y;
	}
```

**Comment by dimkr** [comment]
#2530 should work. When I connect my Panasonic TV, it becomes the left monitor under Xwayland, but it's the right monitor under X.Org. This patch makes Cage add monitors on the right, instead of using wlroots' "automatic configuration" logic.

**Comment by dimkr** [comment]
@01micko Can I close this one? Is the monitor placement correct now?

**Comment by 01micko** [comment]
> @01micko Can I close this one? Is the monitor placement correct now?

Yes.

**Comment by 01micko** [comment]
![slacko64-cage](https://user-images.githubusercontent.com/1019119/135583043-1432d64e-30f1-4e93-994d-41bf54f63f88.png)

That's pretty much what I'm looking at now :smiley:

**Comment by dimkr** [comment]
Weird ... why is the bottom tray on the wrong screen? 🤔 

Here's my laptop, with the Panasonic TV connected, after the fix for monitor order:

![two](https://user-images.githubusercontent.com/1471149/135599639-7ec5ec83-8aa9-4d4d-9af9-b2043cd5d29f.png)

**Comment by 01micko** [comment]
Like that in X.org too. I've grown to like it that way actually.

**Comment by 01micko** [comment]
BTW, the wallpaper is a custom hack.

**Comment by dimkr** [comment]
I think the 16:9 variant should be the default. 16:9 is common nowadays, and 16:9 will work better for 16:9, 16:10 and multiple monitors, compared to the current 4:3 version.
