### ISSUE TITLE
Cage is missing in Slacko 8.x

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2524]
It will be easier to bring the Cage+Xwayland setup to feature parity with X.Org, if it's available in a popular, "official" Puppy and not just Vanilla Dpup.

Probably less useful in 32-bit builds.

**Comment by 01micko** [comment]
So far on slacko64, things are progressing well. 

I might introduce a PR for slacko64 with cage + deps over this weekend.

**Comment by dimkr** [comment]
This issue is kind of fixed, if everything builds fine.

**Comment by 01micko** [comment]
Yes it's not on by default in woof but it works well so far when enabled.

**Comment by 01micko** [comment]
Released https://forum.puppylinux.com/viewtopic.php?f=40&t=4171
