### ISSUE TITLE
wlr-randr doesn't work under Cage

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2528]
https://github.com/emersion/wlr-randr

```
$ wlr-randr
compositor doesn't support wlr-output-management-unstable-v1
```

This is required to support reordering of monitors.

**Comment by 01micko** [comment]
You get further than me, I get
```
~$ wlr-randr 
failed to connect to display
```

**Comment by dimkr** [comment]
> failed to connect to display

`WAYLAND_DISPLAY=wayland-0 wlr-randr`

**Comment by 01micko** [comment]
Even though #2530 works well, it would still be nice to have some control. Appreciate your efforts on this. :smile_cat:

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/pull/2537 is the beginning of a partial solution, which requires restart of Cage to re-arrange monitors.

In order to make wlr-randr work, Cage has to handle the wlroots wlr-output-management-unstable-v1 requests. Currently, it only initializes the wlroots "manager" for this protocol, without handling the requests. I've looked at the relevant code in Sway and it's not super complex, yet not trivial to adapt for Cage, because Cage has no monitor configuration to compare the new configuration against.

**Comment by dimkr** [comment]
Great progress!

```
$ WAYLAND_DISPLAY=wayland-0 ./wlr-randr  
LVDS-1 "Unknown 0x106C 0x00000000 (LVDS-1)"
  Physical size: 280x160 mm
  Enabled: yes
  Modes:
    1366x768 px, 60.103001 Hz (preferred, current)
  Position: 0,0
  Transform: normal
  Scale: 1.000000
```

Now, let's see if it shows two monitors and can reorder them.

EDIT: one step closer!

```
$ WAYLAND_DISPLAY=wayland-0 ./wlr-randr  
LVDS-1 "Unknown 0x106C 0x00000000 (LVDS-1)"
  Physical size: 280x160 mm
  Enabled: yes
  Modes:
    1366x768 px, 60.103001 Hz (preferred, current)
  Position: 0,0
  Transform: normal
  Scale: 1.000000
HDMI-A-1 "Panasonic Industry Company Panasonic-TV 0x00000101 (HDMI-A-1)"
  Enabled: yes
  Modes:
    1280x720 px, 50.000000 Hz (preferred)
    1920x1080 px, 60.000000 Hz (current)
    1920x1080 px, 59.939999 Hz
    1920x1080 px, 50.000000 Hz
    1920x1080 px, 50.000000 Hz
    1920x1080 px, 24.000000 Hz
    1920x1080 px, 23.976000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.939999 Hz
    1280x720 px, 50.000000 Hz
    720x576 px, 50.000000 Hz
    720x576 px, 50.000000 Hz
    720x576 px, 50.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 60.000000 Hz
    640x480 px, 59.939999 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.000000
```

EDIT 2: ` WAYLAND_DISPLAY=wayland-0 ./wlr-randr  --output HDMI-A-1 --off` and `WAYLAND_DISPLAY=wayland-0 ./wlr-randr  --output HDMI-A-1 --off` work!

EDIT 3: `WAYLAND_DISPLAY=wayland-0 ./wlr-randr  --output HDMI-A-1 --right-of LVDS-1` and `WAYLAND_DISPLAY=wayland-0 ./wlr-randr  --output LVDS-1 --right-of HDMI-A-1` work! (this is a wlr-randr patch, https://github.com/dimkr/wlr-randr/commit/d93c83823976c373ae317638e4531ef788a40014)

EDIT 4: `WAYLAND_DISPLAY=wayland-0 ./wlr-randr  --output HDMI-A-1 --mode 1280x720`, `WAYLAND_DISPLAY=wayland-0 ./wlr-randr  --output HDMI-A-1 --mode 720x576` and `WAYLAND_DISPLAY=wayland-0 ./wlr-randr  --output HDMI-A-1 scale 1.5` seem to work 😀
