### ISSUE TITLE
Cursor moves randomly in Valve games under Cage

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2534]
Seems to affect at least CS 1.6 and CS:GO.

A tiny movement of the cursor to one side makes the cursor go crazy: it moves horizontally with crazy acceleration, but every horizontal movement is also a tiny downwards movement. Therefore, the weapon points at the floor and every cursor movement makes it spin.

Even the spectator view is messed up! This weird cursor behavior transforms the game into a top-down action game you can't win, only spectate 😿 

![cut-small](https://user-images.githubusercontent.com/1471149/135586359-25503990-9603-40ce-9aa8-fae79c130598.gif)

**Comment by johanmalm** [comment]
@dimkr @01micko Any chance of testing this on labwc?
I've installed steam and CS:GO, but I think my laptop is too old to run it :smile:

**Comment by dimkr** [comment]
I'll give it a go.

**Comment by dimkr** [comment]
Good job! At least one of these games is playable with johanmalm/labwc@fffa912, but this issue reproduces with johanmalm/labwc@bd1e6f3. I'll patch Cage with support for pointer constraints, copy-pasted from labwc.

**Comment by dimkr** [comment]
CS:GO still has a problem: now it's possible to point up and down, but the view rotates slowly, even if the cursor doesn't move.
