### ISSUE TITLE
Nothing happens when htop is started using the menu entry

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2542]
The htop menu entry has `Terminal=true`, but our menu generator ignores this, and tries to run htop outside of a terminal emulator.

**Comment by 01micko** [comment]
I suppose this won't affect terminal apps for which I added a work around in the desktop file (have done for years).

Here's my Htop example

```desktop
[Desktop Entry]
Encoding=UTF-8
Name=Htop
Icon=htop.png
Comment=System Process Viewer
Exec=/usr/bin/urxvt -e htop
Terminal=false
Type=Application
Categories=Monitor
GenericName=System Process Viewer
```
