### ISSUE TITLE
GTK+ 3 applications running under Cage don't respect the theme set by ptheme

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2560]
When applications run directly under Cage and use their Wayland backend, they don't use the selected GTK+ theme, icon theme and cursor theme.

However, the steps in https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland don't seem to work. After `gsettings set org.gnome.desktop.interface gtk-theme Gradient-grey`, `cage geany` runs a fullscreen Geany with a theme that looks like a mashup of Adwaita and Gradient-grey.

**Comment by 01micko** [comment]
I just tried switching to several different themes and each one worked ok with the widget factory

![wf](https://user-images.githubusercontent.com/1019119/135772381-f05dccd6-fccc-4fa3-a962-3b0b4dbb5c54.jpg)
.

**Comment by 01micko** [comment]
Oh, hang on, I think I misunderstood. Your not running the desktop but the app directly under cage. I suppose this has implications for gtk3 window managers.

**Comment by dimkr** [comment]
Exit X and `cage gtk3-widget-factory` to reproduce this issue.

**Comment by 01micko** [comment]
Yeah, looks like sh!*

**Comment by 01micko** [comment]
Ok, some progress, at least with gtk theme.
```
 dconf write  /org/gnome/desktop/interface/gtk-theme "'Polished-Blue'"
```

~Tried this for icons but failed without error.~ **wrong**
```sh
# dconf write  /org/gnome/desktop/interface/gtk-icon-theme "'PMaterial'"
```

_This_ (not `gtk-icon-theme` but just `icon-theme`). You have to love the consistency </sarc> :confused: 
```sh
dconf write  /org/gnome/desktop/interface/icon-theme "'PMaterial'"
```

```desktop
[Settings]
gtk-theme-name = Polished-Blue
gtk-toolbar-style = GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size = GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-menu-images = 1
gtk-button-images = 1		
gtk-enable-animations = 0
gtk-icon-theme-name = PMaterial
```

**Comment by dimkr** [comment]
Doesn't work here - the themes are still messed up.

**Comment by 01micko** [comment]
What happens when you 'read' the themes? Here's mine 
```
~$ dconf read /org/gnome/desktop/interface/icon-theme
'PMaterial'
~$ dconf read /org/gnome/desktop/interface/gtk-theme
'Polished-Blue'
```

**Comment by dimkr** [comment]
> What happens when you 'read' the themes? Here's mine

It returns the correct values 🤔

**Comment by 01micko** [comment]
It's a dbus problem.

I can't actually change the theme with the above commands if I'm in the wayland (lawbwc) session. I have to go back to the Xwayland (cage) session because `dconf write  /org/gnome/desktop/interface/gtk-theme "'Stardust_dark_mouse'"` gives the error `error: Error spawning command line “dbus-launch --autolaunch=ec72592b3b019b992a8fa4db6163b6ac --binary-syntax --close-stderr”: Child process exited with code 1`.

So I run ` dbus-launch --autolaunch=ec72592b3b019b992a8fa4db6163b6ac --binary-syntax --close-stderr`
and that fails with `Autolaunch error: X11 initialization failed.`

So it seems that while gtk reads the gsettings it needs some magic beyond my capability to write them in a wayland session with `dconf`.

**Comment by 01micko** [comment]
Ok, this worked:

```
~$ export $(dbus-launch)
~$ dconf write  /org/gnome/desktop/interface/gtk-theme "'Stardust_dark_mouse'"
~$ 
~$ geany
```

https://unix.stackexchange.com/questions/95855/dbus-launch-terminated-abnormally-with-the-following-error-no-protocol-specifie

However, this would have implications for user `spot`, so dbus would need to be restarted for him I'd imagine.


![20211011_14h50m07s_grim](https://user-images.githubusercontent.com/1019119/136734860-b960e608-6aef-4bdc-b760-69ee3618232e.png)

**Comment by dimkr** [comment]
> However, this would have implications for user `spot`, so dbus would need to be restarted for him I'd imagine.

~/.xinitrc runs a second D-Bus instance for spot - but if you don't go through .xinitrc, it isn't there.

Therefore, this *should* work:

```
run-as-spot dbus-launch > /tmp/.spot-session-bus
run-as-spot dconf write  /org/gnome/desktop/interface/gtk-theme "'Stardust_dark_mouse'"
```

Maybe we'll also need `dbus-launch` as root, to have a session bus for root too.

**Comment by 01micko** [comment]
root still picked up the old valuse from `dconf read` but running your command above (which I tried) did change the valuse for `spot` only so maybe we need 2 dbus sessions as you suggest.

**Comment by dimkr** [comment]
I hope this won't break Blueman - I remember it doesn't work as root, because one part of it uses the system bus when running as root, while the other one (the tray icon?) uses the session bus. But the tray icon doesn't matter, because there are no tray icons in Wayland, so the main question is whether or not Blueman works when started from the menu.

**Comment by 01micko** [comment]
Perhaps, when/if we do decide to go stable with pure wayland then that may be the time to drop root as the default user. I can hear the pundits now .. "OH, THAT ISN"T PUPPY!"

But the keyword is _default_.

Years ago I had fido running his own X session and it worked well except for the desktop drive icons, but desktop icons aren't a thing in basic wayland compositors either (yet).

Just a thought .. and to anyone else reading this, _read it properly_!!!

**Comment by dimkr** [comment]
Oh yes, the Puppy fundamentalists. They love this kind of comments :)

**Comment by 01micko** [comment]
dconf should work with cursor theme too.

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/issues/2563#issuecomment-944884775

**Comment by dimkr** [comment]
What a stubborn issue! Neither `gsettings set org.gnome.desktop.interface gtk-theme "${PTHEME_GTK3}"` nor `run-as-spot dconf write  /org/gnome/desktop/interface/gtk-theme "Gradient-grey'"` works on dpup, even after #2588. And it doesn't matter if I `ptheme -p 412` from Cage or X.

**Comment by dimkr** [comment]
I'm having trouble with D-Bus.

D-Bus can't be started via labwc startup commands, because we can't set environment variables there. Application started via the labwc menu inherit the labwc process environment variables.

It's easy to start a session bus for root using `dbus-launch labwc`. However, applications running as spot don't use this session bus. Maybe, the solution is something like this:
1. `run-as-spot dbus-launch --exit-with-x11 > /tmp/.spot-session-bus` and `run-as-spot sh -c "pulseaudio --kill > /dev/null 2>&1; pulseaudio --start --log-target=syslog"` as startup commands
2. `PULSE_SERVER=unix:/tmp/runtime-spot/pulse/native` and `PULSE_COOKIE=/home/spot/.config/pulse/cookie` in the environment file
3. Run labwc using `dbus-launch labwc`.

This solution (I'll try it out tomorrow) is not super different from .xinitrc.

**Comment by dimkr** [comment]
Doesn't reproduce in sid64. Closing.

**Comment by 01micko** [comment]
https://github.com/labwc/labwc-tweaks

https://user-images.githubusercontent.com/1019119/149659093-d71a57cf-6488-4f83-b184-04c0ecca87ee.mp4

**Comment by dimkr** [comment]
> https://github.com/labwc/labwc-tweaks

If this can replace ptheme, we must have it!
