### ISSUE TITLE
build (x86_64, ubuntu, focal64, 5.4.x-x86_64) fails - ListDDF has gone?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2566]
@mrfricks @dimkr 
ListDDF has been removed from:
http://distro.ibiblio.org/puppylinux/Packages-puppy-fossa64-official
so
build (x86_64, ubuntu, focal64, 5.4.x-x86_64)
failed 23 hours ago in 1m 9s
WARNING: ListDDF pkg was not found!

Is ListDDF the same as ListDD ??
Line 545 of
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/x86_64/ubuntu/focal64/DISTRO_PKGS_SPECS-ubuntu-focal
needs to be changed??

**Comment by mrfricks** [comment]
hi @peabee 
listddf was just listdd with the pinstall.sh removed.  i think radky may have fixed the pinstall.sh issue with his new release

**Comment by peabee** [comment]
Fixed by changing ListLDDF to ListLDD
