### ISSUE TITLE
Some vanilla dpup testing

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2571]
Hallow there
Still alive and well:-)
Nice to see a fresh up-to-date not-too-hacky puppy coming out!
Tried briefly 9.0.6 in a couple of old laptops

**Computer1 x86**
Vendor		Hewlett-Packard
Date		07/27/2005 (!)
Processor	Intel(R) Pentium(R) M processor 1.60GHz
Memory		1015MB (147MB used)
VGA compatible controller	Intel Corporation Mobile 915GM/GMS/910GML Express Graphics Controller (rev 04)
Network controller		Intel Corporation PRO/Wireless 2200BG [Calexico2] Network Connection (rev 05)

Failed to start X
had to manually pick framebuffer to get to GUI. 
No i915 module in Xorg.

No WiFi even after adding (the missing) ipw2200 firmware from older puppies
Installing frisbee did not help either
ipw2200 module is loaded but no wireless interface found.
May need newer firmware?

For the x86 version, presumably directed towards ancient hardware, you may need additional firmware and drivers (some newer ones could be removed too).
Is a hassle but if is directed to the average users rather than to hackers or developers, should be considered.

**Computer 2 x86_64**
Vendor		SAMSUNG ELECTRONICS
Date		11/08/2012
Processor	Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Memory		5996MB (387MB used)
VGA compatible controller	Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
VGA compatible controller	[AMD/ATI] [Radeon HD 7500M/7600M Series]
 
Started fine with Wayland, Wireless and sound fine but appeared unstable. 
While playing a youtube video and trying to change sound level from keyboard (initially worked - with some lag) I lost keyboard, touchpad and sound and had to hard power off.

Not sure if I can look any further into these.
Thanks for your efforts
Best

**Comment by dimkr** [comment]
Thanks for the feedback @mavrothal. Can you convert this into separate issues please? I started using milestones to assign issues to releases (https://github.com/puppylinux-woof-CE/woof-CE/milestone/2?closed=1), so I can be more organized and efficient when I dedicate time to the Puppy hobby.
