### ISSUE TITLE
Vanilla Dpup x86 drivers and firmware

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2572]
as suggested in #2571

Tried briefly 9.0.6

**Computer1 x86**
Vendor Hewlett-Packard
Date 07/27/2005 (!)
Processor Intel(R) Pentium(R) M processor 1.60GHz
Memory 1015MB (147MB used)
VGA compatible controller Intel Corporation Mobile 915GM/GMS/910GML Express Graphics Controller (rev 04)
Network controller Intel Corporation PRO/Wireless 2200BG [Calexico2] Network Connection (rev 05)

Failed to start X
had to manually pick framebuffer to get to GUI.
No i915 module in Xorg.

No WiFi even after adding (the missing) ipw2200 firmware from older puppies
Installing frisbee did not help either
ipw2200 module is loaded but no wireless interface found.
May need newer firmware?

For the x86 version, presumably directed towards ancient hardware, you may need additional firmware and Xorg drivers (some newer ones could be removed too).
Is a hassle but if is directed to the average users rather than to hackers or developers, should be considered.

**Comment by mavrothal** [comment]
Updated ipw kernel firmware from a newer kernel and now frisbee works
No connection tool on the build as shipped though.

Tried youtube in this machine. Is hardly watchable.
Addition of the missing intel_drv.so in xorg might help? (doubt it...)

Later.  After adding the intel driver from bullseye, X is picking it automatically. 
So the problem of failing to boot to GUI is when the appropriate xorg module is missing and VESA or modesetting or framebuffer fails. 
Maybe xorgwizard should cycle through these on 1st, 2nd and 3rd attempt?

**Comment by dimkr** [comment]
ipw2200 firmware can be installed via PPM; the best clean way to fix this issue is to get rid of Puppy's fdrv, and build a fdrv out of Debian packages like firmware-ipw2x00.

**Comment by mavrothal** [comment]
PPM requires a network connection!
Networking infra should be available OOTB I think

**Comment by dimkr** [comment]
> PPM requires a network connection! Networking infra should be available OOTB I think

SNS is available - is it good enough?

**Comment by dimkr** [comment]
And the x86_64 build uses ConnMan - right/left click the tray icon and you should be able to do pretty much anything you can do with SNS/Frisbee.

**Comment by mavrothal** [comment]
> > PPM requires a network connection! Networking infra should be available OOTB I think
> 

I was referring to the to the network firmware installed via PPM

> SNS is available - is it good enough?
>

Regarding connection managers in x68, I can not see any included in the build in menus or executables. Is SNS renamed to something else?

**Comment by dimkr** [comment]
> Regarding connection managers in x68, I can not see any included in the build in menus or executables. Is SNS renamed to something else?

No - go to the "Internet connection wizard" thing.

**Comment by mavrothal** [comment]
>No - go to the "Internet connection wizard" thing
> 

First thing I did. No cigar. 
It actually fails altogether with a gtk error 
No SNS after calling it from terminal either.
