### ISSUE TITLE
Vanilla Dpup x86_64 stability issue?

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2573]
as suggested in #2571

Tried briefly 9.0.6

**Computer 2 x86_64**
Vendor SAMSUNG ELECTRONICS
Date 11/08/2012
Processor Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Memory 5996MB (387MB used)
VGA compatible controller Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
VGA compatible controller [AMD/ATI] [Radeon HD 7500M/7600M Series]

Started fine with Wayland, Wireless and sound fine but appeared unstable.
While playing a youtube video and trying to change sound level from keyboard (initially worked - with some lag) I lost keyboard, touchpad and sound and had to hard power off.

Maybe an issues with the 2 video cards?

**Comment by mavrothal** [comment]
Took another look at this. 
 The issue is triggered when "Fn+F6-8" is pressed in this computer (sound control)
It would appear that these keys keep firing forever!
You can see it in both the menu sound widget and the pulse audio GUI.
Might be a pulse issue?
If I restart X the issues go away.
Can not see the keycode transmitted as xev reports nothing while wev just gives me a checkered b&w screen that can not get out of!
Could not see anything in Xerr.log or kernel messages
Verified that Xwayland is running in this machine.

**Comment by dimkr** [comment]
Does this happen with X.Org? You can switch to it via the graphics wizard (https://github.com/puppylinux-woof-CE/woof-CE/wiki/Wayland-Support#opt-out-of-xwayland-and-force-use-of-xorg).

**Comment by mavrothal** [comment]
> Does this happen with X.Org?
>

Yes. Same thing. 
The problem is that after that I lose the keyboard so is hard to see what's happening. 
Did not see any flooding of kernel interrupts but the CPU load is going to 100% in all 4 cores.
