### ISSUE TITLE
Firefox in vanilla Dpup

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2577]
When exiting full screen to windowed mode, FF  window is resizable but not movable in both x68 and x86_64 versions. 
It appears that it does not follow the desktop window manager theme.

**Comment by dimkr** [comment]
When Firefox uses its own client-side window title it can't be moved by dragging the title bar. You can move it if you press Alt, then drag the window, though.

I think it's a JWM bug.

**Comment by dimkr** [comment]
https://github.com/joewing/jwm/issues/540

**Comment by dimkr** [comment]
Workaround in #2913, the JWM bug won't be fixed soon I guess.
