### ISSUE TITLE
PPM gui needs TLC

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2590]
PPM gui needs some work.
When installing a package in auto mode it says "calculating needed size" while it actually downloads and install packages without giving a chance to the user to review.
When updating the databases PPM opens with an empty window and you need to change repo to process the db files. This also takes veeeery long time to do.

I guess the changes instigated since PPM 2.0/2.1 maybe important for puppy building but from a user prospective are pretty poor, I would think. 
Given that Vanilla Dpup is fairly spartan application wise, PPM GUI (and infra) might need to be looked, at as users are likely to resort to it.
PPM-ng GUI unfortunately is not any more user friendly.

**Comment by dimkr** [comment]
IMHO, PPM is horrible, and so is any replacement that keeps using the .pet package format and Puppy's package lists.

The next step after https://github.com/puppylinux-woof-CE/woof-CE/pull/2514 is to get rid of PPM.

**Comment by bigpup1** [comment]
Are you using PPM 2.1.2?
When I use it.
I select a item to install.
It shows in the Packages to install.
Under that is the calculated number of packages (dependencies) downloads needed and the size they will use.
If the size is less than 1MB it does show size as 0.
Nothing gets downloaded or installed until I select do it.

About Pet Packages.
Well, with Puppies file system, looking more and more, like a normal Linux OS, file system.
People not getting bothered, about having a lot of not needed stuff, in a program package.
It is getting to a point, that pet packaging, is not really needed, as it was in the past.

**Comment by mrfricks** [comment]
the newer PPM in woofce is horrible but @mavrothal s older 2.1.2 is actually very nice.
it just needs speeding up slightly and the older classic PPM code removed.
see https://github.com/puppylinux-woof-CE/woof-CE/issues/2186
