### ISSUE TITLE
Kernel 5.10 not configured for wireless keyboards during boot

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2598]
Kernel 5.10 does not have the necessary drivers to be able to use a wireless keyboard during the boot sequence and as a result it is not possible to choose between multiple savefolders.

**Comment by peabee** [comment]
Searching oldforum (because this problem has arisen before) - maybe:

CONFIG_USB_OHCI_HCD_PCI=y
is needed?

**Comment by gyrog** [comment]
The solution developed last time was called "initmodules", which (on the second  and subsequent boots), should load the required modules just before 'init' starts sorting out the "save", so it should be in time to enable the keyboard before it is needed to choose a savefolder.

"initmodules" looks at the modules that were loaded during first boot, and then selects those from a number of directories relating to "usb" and "hid".

Part of the thinking was that it might  not be a brilliant idea to support all possible hardware as builtin.
