### ISSUE TITLE
Making mesa much smaller - from BarryK

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2609]
This looks interesting - should it go into Woof-CE?
https://bkhome.org/news/202111/mesa-package-much-bigger-than-it-needs-to-be.html

> I have created packages-templates/mesa/pinstall.sh, a script in that operates upon the folder 'rootfs-complete'. Reduces the size from 139MB to 26MB.... This is pinstall.sh:

```
#!/bin/sh
#the hardlinks may have gone, recreate them. ref:
# https://bkhome.org/news/202111/mesa-package-much-bigger-than-it-needs-to-be.html
#in easyos reduces /usr/libdri from 139MB to 26MB.

if [ -d usr/lib/dri ];then
 PREFIX="usr/lib/"
else
 if [ -d usr/lib64/dri ];then
  PREFIX="usr/lib64/"
 else
  PREFIX="$(find usr/lib -mindepth 2 -maxdepth 2 -type d -name dri | cut -f 1-3 -d '/' | head -n 1)/"
 fi
fi

if [ -d ${PREFIX}dri ];then
 DRVS0="$(ls -1 ${PREFIX}dri)"
 
 while [ "$DRVS0" ];do
  DRVS1=''
  aDRV="$(echo "$DRVS0" | head -n 1)"
  for aaDRV in ${DRVS0}
  do
   [ "$aaDRV" == "" ] && continue
   [ "$aaDRV" == "$aDRV" ] && continue
   cmp -s ${PREFIX}dri/${aDRV} ${PREFIX}dri/${aaDRV}
   if [ $? -eq 0 ];then
    ln -f ${PREFIX}dri/${aDRV} ${PREFIX}dri/${aaDRV}
   else
    if [ ! "$DRVS1" ];then
     DRVS1="${aaDRV}"
    else
     DRVS1="${DRVS1}
${aaDRV}"
    fi
   fi
  done
  DRVS0="$DRVS1"
 done
 sync
fi

```

**Comment by dimkr** [comment]
In dpup, dri*.so are hard links (some files have the same inode). I *think* this is not needed, because links are preserved during 2createpackages and 3builddistro.

**Comment by peabee** [comment]
LxPupSc - don't think they're hard links in this build...........
![Screenshot](https://user-images.githubusercontent.com/5926865/140650915-37170ce9-774b-4231-abfd-fa6bfa85f00f.png)

**Comment by dimkr** [comment]
@peabee `stat /usr/lib/dri/*.so` - look at the inode, or `ls -l /usr/lib/dri/*.so` - look at the number before `root`
