### ISSUE TITLE
gtkdialog-splash relies on xwininfo

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2612]
It doesn't support Wayland.

**Comment by 01micko** [comment]
`xwininfo` still works with Xwayland. If we go 'pure' wayland then that can be an issue, but 'pure' wayland is probably a year away for puppyland. Closing but re-open if you feel the need.

**Comment by 01micko** [comment]
`xwininfo` is only needed for `-placement` option which we have covered with recent commits to gtkdialog.

Probably the only issue for 'pure' wayland is the condition, which may be an environment variable or the status of a running application.
