### ISSUE TITLE
Applications running as spot always use X11

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2642]
GTK+ applications look for `/tmp/runtime-spot/wayland-0`, fail to find it, then fall back to their X11 backend.

**Comment by 01micko** [comment]
Seems that it's in `/tmp/runtime-root/` which *spot* can't access. This could be a very curly problem. It may be the case that we have to login to the desktop as spot to run internet facing apps as spot with wayland.

**Comment by dimkr** [comment]
@01micko chmod/chown didn't work

**Comment by 01micko** [comment]
> @01micko chmod/chown didn't work

No
