### ISSUE TITLE
CONFIG_BLK_DEV_NVME should be y in 5.10.x and 5.15.x

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2649]

**Comment by 01micko** [comment]
Yep :smiley_cat: 

![20211129_20h16m14s_grim](https://user-images.githubusercontent.com/1019119/143849776-2ab0448a-2e2b-4b7d-970e-d52e442ec9ba.png)

Also, `CONFIG_IKCONFIG is not set`.

Some scripts might use `zcat /proc/config`. Not necessarily in woof, but maybe others.

**Comment by dimkr** [comment]
This issue is yet another proof for the usefulness of a centralized source of properly-configured, updated and stable kernel packages. The risk of introducing an issue or skipping a configuration option when configuring the latest and greatest kernel is super high, and most users should be satisfied with a longterm kernel.
