### ISSUE TITLE
Future problem? jwm-2.4.0

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2652]
Debian Sid / Bookworm is now providing jwm-2.4.0 (from 14-Nov-21) which seems to be incompatible with Puppy themes.....
see:
https://debian.pkgs.org/sid/debian-main-amd64/jwm_2.4.0-1_amd64.deb.html
http://ftp.de.debian.org/debian/pool/main/j/jwm/

**Comment by 01micko** [comment]
Every major bump in version does this in JWM. The XSLT file shipped with JWM has had a history of working well.


Some of the old old themes in `noarch` probably don't even work with 2.3.7. Probably need to weed some out. 

I'll take care of `pTheme` over the Christmas break.

**Comment by 01micko** [comment]
2.4.0 isn't stable anyway, we wait for 2.4.1 so closing.

**Comment by peabee** [comment]
Salix is now serving up 2.4.0 ...........
[jwm-2.4.0-i586-1gv.txz]
(http://ftp.nluug.nl/ftp/pub/os/Linux/distr/salix/i486/15.0/salix/xap/jwm-2.4.0-i586-1gv.txz)                           
03-Jan-2022 23:40  106K

**Comment by 01micko** [comment]
It's vanilla (ie - no patches) 2.4.0 - not stable.

**Comment by peabee** [comment]
> 2.4.0 isn't stable anyway, we wait for 2.4.1 so closing.

https://github.com/joewing/jwm/releases/tag/v2.4.1
