### ISSUE TITLE
yaf-splash warnings under X

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2670]
```
** (yaf-splash:17692): CRITICAL **: 09:45:06.987: gtk_wayland_init_if_needed: assertion 'GDK_IS_WAYLAND_DISPLAY (gdk_display)' failed

** (yaf-splash:17692): CRITICAL **: 09:45:06.987: layer_surface_new: assertion 'gtk_wayland_get_layer_shell_global ()' failed

** (yaf-splash:17692): WARNING **: 09:45:06.987: Falling back to XDG shell instead of Layer Shell (surface should appear but layer features will not work)

** (yaf-splash:17692): CRITICAL **: 09:45:06.987: xdg_toplevel_surface_new: assertion 'gtk_wayland_get_xdg_wm_base_global ()' failed

** (yaf-splash:17692): WARNING **: 09:45:06.987: Shell does not support XDG shell stable. Falling back to default GTK behavior

** (yaf-splash:17692): CRITICAL **: 09:45:06.987: GtkWindow is not a layer surface. Make sure you called gtk_layer_init_for_window ()
```

**Comment by 01micko** [comment]
Haven't seen any of those. I get warnings with `geany` but none with `gtkdialog` apart from the gtk-layer-shell version warning which I send to /dev/null. (oh just realised I don't have the latest gtkdialog with gtk-layer-shell installed on my laptop).

**Comment by 01micko** [comment]
Probably need to raise an issue on gtkdialog repo. IMHO, a `getenv()` call could fix it.

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/gtkdialog/pull/105 should fix this. Tested on X, haven't tested on labwc.

EDIT: tested on Cage with GDK_BACKEND=wayland, this `if` is always true 😕

**Comment by 01micko** [comment]
This shouldn't happen once `gtkdialog` is upgraded to `0.8.4h`. Closing for now.

**Comment by dimkr** [comment]
@01micko Looks like #3143 worked, and this issue is indeed fixed in a future-proof way. No warnings anymore, in jammy64, bookworm64 and sid64. 🥳
