### ISSUE TITLE
kernel-kit produces ambiguous package

### ISSUE THREAD

**Issue by gyrog** [puppylinux-woof-CE/woof-CE#2683]
Is there any way to get the current kernel-kit to produce a kernel package with an accurate name?

I just wasted an hour compiling 5.10.86, execting to get a 5.10.86 kernel package, but all I got is a 5.10.0 package.
How is hiding the accurate name of the kernel inside an improvement?

**Comment by dimkr** [comment]
If you build third-party drivers against 5.10.86, but it's called "5.10.0", they will keep working when you update to 5.10.87.

If you don't want this, set `remove_sublevel=no`.

**Comment by gyrog** [comment]
@dimkr,
Thanks, I'll try again with "remove_sublevel=no".

It's kernel modules I'm concerned about, a different sublevel is a crude indicator of a different kernel compile, so may be different modules.
