### ISSUE TITLE
Parted 3.2 needs to be replaced

### ISSUE THREAD

**Issue by Phoenix-Starlight** [puppylinux-woof-CE/woof-CE#2746]
From what I can tell, whenever a puppy is built, it uses parted from puppy-common64/32 which is version 3.2 which incidentally contains a regression that overwrites the boot sector with psuedo-random code, making it unreadable to Windows. If it isn't actually using this parted version, let me know and close it.

**Comment by 01micko** [comment]
This is unfortunate. Not all pups use the 'common' repos - I avoid them and use upstream (eg: ubuntu, debian, slackware) unless it is something really simple that is not in upstream.

You should contact your distro maintainer, You can tag them here see: https://github.com/orgs/puppylinux-woof-CE/people

**Comment by Phoenix-Starlight** [comment]
The glaring issue for that link... is that they aren't publicly listed! Although the iso/package needing replacement appears to apply to xenial and bionic so far.

**Comment by 01micko** [comment]
> is that they aren't publicly listed!

Not even when logged in? 

I'll attach a screenshot.
![woof-members](https://user-images.githubusercontent.com/1019119/147859469-b971c3d8-bab2-4764-ba00-77c5b26c0b8b.png)

Your maintainer will have to post an update somehow.

Cheers

**Comment by Phoenix-Starlight** [comment]
Yes I am logged in. It's most likely I need to join the club first in order to see.
EDIT: I looked at the forum and the one who maintains it is 666philb. Is that mrfricks?

**Comment by 01micko** [comment]
> Yes I am logged in. It's most likely I need to join the club first in order to see. EDIT: I looked at the forum and the one who maintains it is 666philb. Is that mrfricks?

Yes @mrfricks 

It seems xenial and bionic _do_ use upstream now (they may not have before)

```
~$ find /mnt/home/micko/woof-CE/woof-distro/ -type f -name 'DISTRO_PKGS*'|xargs grep 'yes|parted' | grep -E 'xenial|bionic'
/mnt/home/micko/woof-CE/woof-distro/x86/ubuntu/xenial/DISTRO_PKGS_SPECS-ubuntu-xenial:yes|parted|parted,libparted2,libparted-dev,libparted-fs-resize0|exe,dev,doc,nls|
/mnt/home/micko/woof-CE/woof-distro/x86/ubuntu/upupbb/DISTRO_PKGS_SPECS-ubuntu-bionic:yes|parted|parted,libparted2,libparted-dev,libparted-fs-resize0|exe,dev,doc,nls|
/mnt/home/micko/woof-CE/woof-distro/x86_64/ubuntu/bionic64/DISTRO_PKGS_SPECS-ubuntu-bionic:yes|parted|parted,libparted2,libparted-dev,libparted-fs-resize0|exe,dev,doc,nls|
/mnt/home/micko/woof-CE/woof-distro/x86_64/ubuntu/xenial64/DISTRO_PKGS_SPECS-ubuntu-xenial:yes|parted|parted,libparted2,libparted-dev,libparted-fs-resize0|exe,dev,doc,nls|
```

If a pet package is chosen then the 3rd field is empty: eg -

```
yes|parted||exe,dev,doc,nls
```

Ask @mrfricks to post a `quickpet` update if it's not in your version.

Closing for now.
