### ISSUE TITLE
some apt problems

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2788]
Tried 999 and the apt functions briefly
Default command in synaptic.desktop fails with 
pam_open_session() failed: Module is unknown. 
apparently pkexec is looking for something that is not there.
replacing the desktop exec command from synaptic-pkexec to plain synaptic works fine.
Another little issue that is usually not allowed is that you can have synaptic open and run apt from terminal, ie it allows multiple instances.

Synaptic per se, does not have the usual icons and functions to mark multiple packages for installation or removal, but  works.
Tried installation of xfce4, downloaded the packages and the recommended ones (that also included xorg) and it worked!!!
“Complete Removal”  of the packages though failed with “you have broken packages” and “unable to lock the download directory”. 
Simple “removal” worked.
Trying to install also everything “suggested”, sgml-base failed with “post-installation script subprocess returned error exit status 127”. After that dpkg was pretty much stack with pending unresolved errors as well as and apt/dpkg was defunct.

Granted another desktop is not the simplest thing to install but is a good test for the PM abilities. apt almost pulled it out! 

Looks like though that apt integration with a nice GUI is going to be an uphill battle.

**Comment by dimkr** [comment]
> Looks like though that apt integration with a nice GUI is going to be an uphill battle.

I think so, too.

This is why I think it's a good time for #2787. #2779 must be merged before all issues are resolved, so get as much feedback as possible and stabilize it over time.

> Tried 999 and the apt functions briefly

With devx loaded or without it? This test build misses some fixes that move stuff from devx to the main SFS.

**Comment by dimkr** [comment]
Missing icons are fixed by 17b9abb:

![icons](https://user-images.githubusercontent.com/1471149/150500268-8ba062ed-de3d-41c4-91f5-431c356c5680.png)


f714188 resolves the missing sgml-base error.
