### ISSUE TITLE
dpup kernel/devx sfs missing apt kernel package info

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2794]
as a result packages that depend on kernel/kernel headers fail to install with apt
either kernel kit or better the dpup-apt devx (when kernel sfs is loaded) should fix that.

**Comment by dimkr** [comment]
@mavrothal Can you give an example of a package or two?

**Comment by mavrothal** [comment]
This was a package with parellels tools that had to be compiled for better integration of the VM.
So was checking for kernel src presence through the PM. A fast "aptitude why" check indicates only some proprietary video drivers have this requirement. 
I guess is only important compiling from different sources that might check through the PM for the necessary packages and not directly.
I guess rather obsolete case.
