### ISSUE TITLE
Make PPM optional

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2798]
The next step after #2779 is to make PPM optional, but without removing support for .pet packages (aka "petget").

**Comment by 01micko** [comment]
Have to be careful here as `pkg` depends on some aspects of PPM

**Comment by dimkr** [comment]
pkg is already optional 😉 

I want both pkg and PPM out of dpup.

**Comment by dimkr** [comment]
#3325 is good enough for me.
