### ISSUE TITLE
15-Minute Bug Initiative?

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2802]
Something in the spirit of https://pointieststick.com/2022/01/18/the-15-minute-bug-initiative/.

Examples:
- #2790: is it the last duplicate menu entry?
- #2782: is this the only reason why sometimes, the JWM configuration is broken?
- #2775: is this the only place where DISTRO_NAME can be too long?
- #2762: is there any other application that tries to use the Desktop directory?
- #2754: is there any other place where the user has to close a misleading popup, when nlsx is loaded?
- #2726: is there any other place where the use of ROX-Filer instead of defaultfilemanager is hardcoded?
- #2879: do we have a similar problem in the other tray icons?
- #2876: do we have more artificial delay between power on and the desktop?

**Comment by 01micko** [comment]
> * [Bugfix the alignment of ${DISTRO_NAME} if it is longer than "Puppy Li… #2775](https://github.com/puppylinux-woof-CE/woof-CE/pull/2775): is this the only place where DISTRO_NAME can be too long?

When I issue a PR soon for labwc theming changes it wont be!

![20220126_13h39m13s_grim](https://user-images.githubusercontent.com/1019119/151100170-70a04af6-d043-4f85-b0fe-c36c26eadc12.png)

#2730 #2719
