### ISSUE TITLE
Frugality does not allow partition resizing (?) and other little things

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2803]
Tried 9.1.2 briefly on a PC (BTW the included bootx86.efi does not boot intel MACs - I use rEFInd that is good for both). 
Worked OK. 
One issue is that you can not resize the OS partition from within as it is always mounted. 
Given that also holds the savefile, 2GB is too small.
(Yes you can do it in a different system but does not look good…)
Maybe pfix=ram should move everything in RAM to allow unmount and resize.

Also if this is to be run from a USB stick, ext4 without journal will be better.
Or maybe (if not always in RAM - not sure about that) upper layer should be in RAM and only saved at shoutdown to avoid continuous rw.

BTW having everything in RAM is really important if a(n old 2GB) USB2 stick is used that can slow thinks down a lot.
Also since power management is not quite there, running from a laptop that goes to suspension sometimes results in USB unmounting and hanging the system.
 
Another little annoyance is the behaviour of /mnt/home desktop icon that instead of opening the drive when clicking, brings up pmount unless you (try to) unmount it first clicking the eject arrow. 

A grievance about distribution as IMG is that is making hard to test in a VM (VirtualBox, VMWare, Parallels). At least in early sages you should make testing as easy and safe as possible.
Maybe a script should be included  to the build an ISO out of the IMG. If isolinux and friends is too much additional stuff, they could be downloaded by the script to be included in the ISO image.

More if I mange to get a hold of that PC or the next version boots Macs

**Comment by dimkr** [comment]
> Also if this is to be run from a USB stick, ext4 without journal will be better.

https://github.com/puppylinux-woof-CE/woof-CE/blob/24a04e5db270a35a1a37e2521eb889352a3674b5/woof-code/support/pc_image.sh#L24

> Another little annoyance is the behaviour of /mnt/home desktop icon that instead of opening the drive when clicking, brings up pmount unless you (try to) unmount it first clicking the eject arrow.

#2804
