### ISSUE TITLE
Fail to change screen resolution in wayland

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2809]
Try to change screen resolutions passing the "video" kernel argument either as video=\<resolution@freq\> or specifying active display as  video=eDP-1:\<resolution@freq\> but none worked
Xorg had no problem in the same machine.

**Comment by dimkr** [comment]
Have you tried the graphics wizard by @01micko? It can set the resolution, rotation and scaling.

https://github.com/puppylinux-woof-CE/woof-CE/pull/2686

**Comment by mavrothal** [comment]
Yes, but it offers only one alternative resolution.
Maybe is a wayland limitation. (This is with Intel Crystal Well integrated Graphics controler)

**Comment by 01micko** [comment]
hi @mavrothal 

Can you post the output of `wlr-randr` in a terminal emulator please?

**Comment by mavrothal** [comment]
Hi Mick 
on my next attempt  to build a stick and run it I will. 
Sometime over the WE I hope

**Comment by mavrothal** [comment]
```
eDP-1 "Apple Computer Inc Color LCD 0x00000000 (eDP-1)"
  Physical size: 330x210 mm
  Enabled: yes
  Modes:
    2880x1800 px, 59.990002 Hz (preferred, current)
  Position: 0,0
  Transform: normal
  Scale: 1.000000
 
  
# after adding 1680x1050 in  kernel boot options

eDP-1 "Apple Computer Inc Color LCD 0x00000000 (eDP-1)"
  Physical size: 330x210 mm
  Enabled: yes
  Modes:
    1680x1050 px, 59.992001 Hz (current)
    2880x1800 px, 59.990002 Hz (preferred)
  Position: 0,0
  Transform: normal
  Scale: 1.000000
```

**Comment by dimkr** [comment]
These are the natively supported display modes - you should change the scaling factor instead of using a non-native resolution, if you want everything to be bigger or smaller.

**Comment by 01micko** [comment]
> you should change the scaling factor instead of using a non-native resolution, if you want everything to be bigger or smaller.

I was going to suggest that.

**Comment by mavrothal** [comment]
> you should change the scaling factor

That is the first thing I tried but the screen started blinking between the two scales and I did not go further.
(Thought was probably mac-specific so I did not bother you with that)

BTW if you try scaling with not-native resolution wayland breaks and end up with a black screen.
Not sure if this is also mac - specific. 
You may want to check if scaling is compatible with non native resolutions and prevent that in the app.

**Comment by mavrothal** [comment]
> BTW if you try scaling with not-native resolution wayland breaks and end up with a black screen.

Any idea what this setting (the scaling for non-native resolution)  is written in the /upper/save so I can delete it and get back to the desktop without reinstalling everything?

**Comment by dimkr** [comment]
> > BTW if you try scaling with not-native resolution wayland breaks and end up with a black screen.
> 
> Any idea what this setting (the scaling for non-native resolution) is written in the /upper/save so I can delete it and get back to the desktop without reinstalling everything?

$XDG_CONFIG_HOME/wmonitors.

Or you can just delete /var/local/xwin_enable_xwayland to force use of X.Org.

**Comment by mavrothal** [comment]
> Or you can just delete /var/local/xwin_enable_xwayland to force use of X.Org.

THX but this file is not present in /upper/save and I can not get to a terminal after booting
Looks like that wayland starts and gives a black screen.
Is pfix=nox (or equivalent)  implemented in frugality?

**Comment by dimkr** [comment]
> Is pfix=nox (or equivalent) implemented in frugality?

Nope. It's not in /upper/save because this file comes from the main SFS.

Instead, you can delete the file using `mkdir -p  /upper/save/var/local && mknod /upper/save/var/local/xwin_enable_xwayland c 0 0` (an overlayfs whiteout). See https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt.

**Comment by mavrothal** [comment]
> Instead, you can delete the file

Thank you.
This allows getting to Xorg, but does not solve the problem with wayland I asked.
If you change back to wayland from X you get again the same  black screen.

So evidently, changing scale  while in another than the native resolution, wrote something in /upper/save that is still there and does not allow wayland to function.
So any idea what/where this could, be so can be removed/modified and allow wayland to function again?
Is there any other wayland related configuration files other than /root/.Xwayland and the wlr- /root/.config/ files?

**Comment by mavrothal** [comment]
> Is there any other wayland related configuration files other than /root/.Xwayland and the wlr- /root/.config/ files?

For the history removing /root/.Xwayland, /root/.config/swayidle/ and /root/.config/wmonitors/ fixed the problem with wayland.
_I think_ the problem was a malformed /root/.config/swayidle/config file
