### ISSUE TITLE
Frugality stability/debugging

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2812]
Is there are way to make frugality booting more verbal (other than kernel loglevel).
I find frugality setups to be VERY finicky. 
To be specific at least in 6 different attempts with 2 different USB thumb drives and 2 different laptops, after few reboots and changing/adding things at the root partition, the kernel can not make the switch from EFI partition to the main OS partition. 
It ends up with a blinking cursor on a cleared black screen, instead of the expected “making file system usable”.
I assume is stuck at the rootwait, I can see the flash drive light blinking but nothing is happening.  
It would be nice if some feed back was provided so debugging can move forward.

Using rEFInd instead of the included efiliux does not improve things, btw.
BTW2, If you think that the setup may have any special requirements ie USB 3.1 and above, USB port power uninterrupted or whatever, please state it.
BTW3I was expecting the dpup installer to be a bit more flexible, but actually it replicates the logic of the IMG just using the entire drive! The installer installation on a thumb drive is equally finicky stability-wise. (BTW the installer has major quirks, like bailing out if any of the involved partitions is mounted) 

In general, (I’m sorry but) I think your IMG setup is too unforgifing/unfriendly/limiting and need some solid improvement.
Specifically, it can not be in parallel with other OS versions, it needs both its own boot partition and system partition with hard-coded names(!) and when installed in a USB thumb drive appears VERY unstable boot-wise.
If this is also going to be a portable OS, thumb drive performance should be solid. And given that no ISO is provided for the 9.1.X builds, stability is even more urgent for an “Official Puppy” (as declared in the forum). 

Apologies for the complains but I really have a hard time with it 
All your underlying improvements are wasted by the booting limitations - a historically strong point for puppy. 
You can really try to cope with any problems but if it fails to boot consistency, is just of no use.

So for start please make booting as verbal as possible and implement logging so we may identify and communicate the problems

**Comment by dimkr** [comment]
> To be specific at least in 6 different attempts with 2 different USB thumb drives and 2 different laptops, after few reboots and changing/adding things at the root partition, the kernel can not make the switch from EFI partition to the main OS partition.

Do you have `lspci`, `lsusb` and `dmesg` from both laptops? Doesn't matter if it's from a different kernel or different distro: I want to understand what USB controllers and drivers are present.

If the kernel doesn't see the boot partition, the problem starts even before frugalify.

**Comment by mavrothal** [comment]
This may also need some time.
Just to point out that I never have this issue on first boot after the stick making, either with the original linuxefi or with rEFInd (that I update with the EFI partition before the first boot).
So is in response to something that happens after.

**Comment by mavrothal** [comment]
I had to look at it after all...

Here is how I can consistently break the boot process.

Make the stick, boot, setup and reboot.
Copy from another stick (do not download) the kernel-kit sfs at the root of the OS partition along the other dpup SFSs. (copying directly to the /dev/X or the /initrd/Y makes no difference). 
sync.
Reboot.
It hangs.

What happens is that the partition after copying the files into it, is not cleanly umnounted and the kernel can not boot a “dirty” partition (or has mechanism to fix it in the EFI partition).

What I find strange is that if you fsck the partition and try to boot still fails.
But if you first remove the extra (sfs) file and then fsck the partition then the stick boots fine again!

So it must be something more beyond the not clean unmounting and the inability of the kernel to boot or fix “dirty” partitions.

Should point out that the not cleanly unmounted partition has no issues to mount in a linux system and does not appear to have any damaged files.

PS. Pls consider the other issues too...

**Comment by mavrothal** [comment]
> What I find strange is that if you fsck the partition and try to boot still fails.
> But if you first remove the extra (sfs) file and then fsck the partition then the stick boots fine again!
> 

Well, it turn out that is not any SFS but in my case /initrd/kernel_sources-5.10-kernel-kit.sfs (md5:ba94cd4fe45422cfefbec558d642040e)
Mind you that the sfs does not need be to be installed or simple open after copying. Just be there.

**Comment by dimkr** [comment]
I'm confused - I don't understand how you created a bootable flash drive. Did you use the ready-made images? Did you gunzip the image first? Have you tried 9.0.x as well?

You can't use any zdrv/fdrv with Vanilla Dpup 9.1.x. By default, kernel-kit puts modules in /lib/modules and not /usr/lib/modules, so if you swap the kernel, you end up replacing /lib with an almost empty directory.

But let's put this aside for a moment, to focus on real issues. I want to isolate the issue, not the other way around.

> PS. Pls consider the other issues too...

There are too many in one issue, it's hard to solve anything like this.

**Comment by mavrothal** [comment]
> I'm confused

let's see if I can help. 
Downloaded [9.1.4](https://github.com/vanilla-dpup/releases/releases/download/vanilladpup-x86_64-9.1.5/vanilladpup-9.1.5-ext4-2gb-uefi.img.gz) decompressed and made the sticks with [etcher](https://www.balena.io/etcher/)
Booted fine. Configured the laptop. Rebooted. All well.
In similarly made stick  the EFI partition was modified to use [rEFind](https://www.rodsbooks.com/refind/) for booting. Also booted fine. Configured the laptop. Rebooted. All well again
A third (VFAT) stick had the [5.10 kernel source](https://github.com/vanilla-dpup/releases/releases/download/vanilladpup-x86_64-9.1.5/kernel_sources-5.10-kernel-kit.sfs). 
Copied this SFS from the VFAT stick to the /initrd/ (or the respected /dev/sdXY) next to the other vanilladpup SFSs. Did not mount or install the kernel SFS (but when I did, did not change behaviour).
Shutdown and reboot.
The boot hangs.
Hopefully that is clear enough.

Regarding 9.0.X, I'm not sure if it is the same problem. I sure used the kernel SFS and compiled some drivers in 9.0.25(?), but I cannot remember if it was with the ISO on a VM or the IMG on a stick. 
I _**think**_ it was the IMG setup on another stick.

**Comment by dimkr** [comment]
> A third (VFAT) stick had the [5.10 kernel source](https://github.com/vanilla-dpup/releases/releases/download/vanilladpup-x86_64-9.1.5/kernel_sources-5.10-kernel-kit.sfs).
> Copied this SFS from the VFAT stick to the /initrd/ (or the respected /dev/sdXY) next to the other vanilladpup SFSs. Did not mount or install the kernel SFS (but when I did, did not change behaviour).
> Shutdown and reboot.
> The boot hangs.

This should do the trick:

```
$ unsquashfs kernel_sources-5.10-kernel-kit.sfs
$ rm kernel_sources-5.10-kernel-kit.sfs
$ mv squashfs-root/lib squashfs-root/usr/
$ mksquashfs squashfs-root kernel_sources-5.10-kernel-kit.sfs 
```

9.0.x doesn't need this, because /lib is not a symlink.

**Comment by mavrothal** [comment]
> mv squashfs-root/lib squashfs-root/usr/

Yeah, that's another problem ( #2815 )
But this also means that in frugality every SFS at the root of the partition is automatically mounted regardless of user directive!
Is that a bug or  a feature?

**Comment by dimkr** [comment]
It's neither a bug, nor a feature, and it's 100% unrelated to frugalify.

The directory layout in 9.1.x has changed to be more Debian-like, in the name of better Debian compatibility. It's a design decision that has some consequences: it will break SFSs and packages that put files outside of /usr, in directories that became symlinks.

I'll fix the kernel sources SFS, but I don't see a way to fix everything for everyone. I don't control what SFSs people decide to load, and frugalify can't 'fix' SFSs.

**Comment by mavrothal** [comment]
> It's neither a bug, nor a feature, and it's 100% unrelated to frugalify

Maybe I was clear again. I was referring to the automatic loading of _every SFSs_ that is at the root of the partition, regardless of user directive, ie if the user wants this extra SFS loaded or not (as in the traditional)

**Comment by dimkr** [comment]
> regardless of user directive,

This was a deliberate design decision. Instead of putting a SFS there *and* enabling it, you only have to do the first step: less work for the user, and a simpler implementation of SFS loading.

sfs_load is unsupported with overlayfs anyway, so the only way to load a SFS is at boot time. Therefore, there's no reason to distinguish between SFSs loaded at boot time, and those you can load later, using some enable/disable toggle for each.

It's OK to disagree with this design decision, but I still don't understand how this discussion helps understand what sounds to me like USB-related issues.

**Comment by mavrothal** [comment]
> discussion helps understand what sounds to me like USB-related issues.

Indeed we are drifting but there is no USB related issue I think.
The boot breaks because of a malformed SFS that is automatically loaded.

So the  issues are really the following I think:
1) Frugality provides no feed back during boot, so problems can not be easily identified.
2) Malformed (/traditional) SFSs (and pets?) break the installation and there is no mechanism to check for that.
Issues related to the title, regarding stability and debugging I would think

In general, I think that is good to make dpup more Debian compatible but should not break with the multitude of pets and SFSs out there that puppy users are known to tinker with.

**Comment by mavrothal** [comment]
> $ mv squashfs-root/lib squashfs-root/usr/

for people that may want to try it till properly fixed:
You also need to update the symlinks in lib/modules/<kernel_version>/
