### ISSUE TITLE
DMZ cursor theme misses 'text icon

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#2814]
```
 err: render.c:3664: failed to load xcursor pointer 'text'
```

This is running `foot` terminal; it's native wayland. Just symlinking to the `xterm` cursor fixes it.

This _may_ occur in other native wayland apps.

**Comment by dimkr** [comment]
I'll take a look, after #2716. Let's get rid of X terminals on Wayland first, then polish 😸

**Comment by 01micko** [comment]
Might affect more than terminals, and I think if the link is added a fairly innocuous change.

**Comment by dimkr** [comment]
> Might affect more than terminals, and I think if the link is added a fairly innocuous change.

I agree, should be perfectly safe.
