### ISSUE TITLE
vanilla dpup breaks existing pets

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2815]
The symlinking of /lib /bin /sbin to /usr/* breaks many useful pets as petget fails to follow symlinks.
May want to add code in the dpup petget/PPM version to take care of this.

**Comment by dimkr** [comment]
Better Debian compatibility comes at some cost. The solution is not to install incompatible packages from other distros and intentionally break your system.

Users who want compatibility with old .pet packages should use 9.0.x.
