### ISSUE TITLE
Philosophy - petbuilds - debate

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2827]
Making system builds rely on petbuilds means that a working devx is needed before a build can be undertaken.
When starting a new build, where even the main system may not work at first attempt having to have a working devx in order to do petbuilds in order to build the new system is a tall (impossible) ask.
Therefore it must be possible to do builds with only pre-built components and get that working before using the petbuild system.
For debate............

Note: 3builddistro says:
"WARNING: PETBUILDS is empty, this may be a hard error in the future"
and forces:
PETBUILDS="pmaterial_icons puppy_flat_icons puppy_standard_icons"
which means the build fails if the devx is not yet available and/or working

**Comment by dimkr** [comment]
> Making system builds rely on petbuilds means that a working devx is needed before a build can be undertaken.

This is not true.

First of all, petbuilds are not built in the host operating system, but inside a chroot environment that consists of rootfs-complete and devx, of the Puppy you're building.

Look at this piece of code:

```
if [ -z "$PETBUILDS" ]; then
	echo "WARNING: PETBUILDS is empty, this may be a hard error in the future"
	[ -n "$GITHUB_ACTIONS" ] && exit 1
	PETBUILDS="pmaterial_icons puppy_flat_icons puppy_standard_icons"
fi

if [ "$BUILD_DEVX" = "yes" -o -n "$PETBUILDS" ] ; then
```

If devx is not built (BUILD_DEVX=no), the value of PETBUILDS is ignored (the warning is misleading), and nothing gets built.

Moreover: if the built devx is faulty in any way, it's still OK to build these 3 icon packages, because nothing gets compiled. These 3 petbuilds only extract 3 prebuilt tarballs.

>which means the build fails if the devx is not yet available and/or working

Do you still have the 3builddistro logs?

**Comment by peabee** [comment]
> chroot environment that consists of rootfs-complete and devx, of **the Puppy you're building**

My experience was that until the devx was logically brought to a completed state it was not possible to chroot into the petbuild environment and hence no petbuilds could be completed and the whole build failed.

I had to patch my local version of 3builddistro to overcome this and do an initial system build. Now I have a working devx I no longer need the patch. But others may face the same impasse in the future if they expect petbuilds to be using the host (working) devx and want to petbuild more than just icons (which now don't need devx I believe).

Perhaps we need an option to either use the host devx (for initial pet-building) and then use the target devx later when the target devx has been debugged.

I don't keep 3builddistro logs (does it produce any?)

**Comment by dimkr** [comment]
What petbuilds did you enable, other than icons?

**Comment by peabee** [comment]
Just icons in the particular instance which caused me to raise this issue.
