### ISSUE TITLE
Problem with kernel-kit build of 5.15 kernel

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2828]
Marv has reported problems booting various 64-bit pups with the 5.15 kernel-kit kernel.

He has noted:
"most other recent kernels have an /sbin directory with aufs files, 5.15.0 doesn't"

Is this a known aspect of the 5.15 kernel-kit build??

Other 5.15 / 5.16 kernels boot correctly and have /sbin.

**Comment by dimkr** [comment]
Super easy fix.

```
2022-01-31T00:20:40.3530004Z   INSTALL kernel_headers-5.15.18-kernel-kit-x86_64/usr/include
2022-01-31T00:20:40.3533811Z /bin/sh: 1: rsync: not found
2022-01-31T00:20:40.3539043Z make: *** [Makefile:1297: headers_install] Error 127
2022-01-31T00:20:40.3554839Z find: 'kernel_headers-5.15.18-kernel-kit-x86_64/usr/include': No such file or directory
2022-01-31T00:20:40.3573412Z Building aufs-utils - userspace modules
2022-01-31T00:20:40.3797412Z ver.c:19:10: fatal error: linux/aufs_type.h: No such file or directory
2022-01-31T00:20:40.3798414Z    19 | #include <linux/aufs_type.h>
2022-01-31T00:20:40.3798701Z       |          ^~~~~~~~~~~~~~~~~~~
2022-01-31T00:20:40.3798908Z compilation terminated.
```

**Comment by peabee** [comment]
Marv has tested the "new" 5.15 and still has problems....

He reports the following errors in syslog:
Feb 1 15:00:51 (none) kern.err kernel: [ 3.140575] FAT-fs (sda1): IO charset ascii not found
Feb 1 15:00:51 (none) kern.err kernel: [ 6.148282] FAT-fs (sda1): IO charset ascii not found
Feb 1 15:00:58 (none) kern.err kernel: [ 32.465593] FAT-fs (sda1): IO charset ascii not found

He thinks:
In the kernel config, try setting:
CONFIG_NLS_ASCII=y
**not**:
CONFIG_NLS_ASCII=m

**Comment by peabee** [comment]
Marv reports that the 'new+1' 5.15 now boots as expected in his configuration - thanks.
However he also reports an anomaly:
```
With the 5.15.0 kernel in dmesg I see:

# dmesg | grep -i fail
[ 4.491574] zsmalloc: module verification failed: signature and/or required key missing - tainting kernel
[ 9.435465] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[ 9.435471] cfg80211: failed to load regulatory.db

With the 5.16.2 kernel:

dmesg | grep -i fail
[ 8.556770] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[ 8.556777] cfg80211: failed to load regulatory.db
```

**Comment by dimkr** [comment]
I think the `crda` package is missing - regulatory.db is not part of the kernel package

**Comment by peabee** [comment]
I think Marv was pointing out the
zsmalloc: module verification failed: signature and/or required key missing - tainting kernel
line as being different in 5.15-kernel-kit

**Comment by dimkr** [comment]
We don't use signed kernel modules, so the signature can't be wrong - are you sure this is from the automated 5.15 build?

**Comment by dimkr** [comment]
Surprise, I do see CONFIG_MODULE_SIG=y in 5.10.x and 5.15.x. The most likely explanations for this error are 1) the user mixed vmlinuz+zdrv from different builds and 2) somebody stripped the module, which invalidates its signature.

**Comment by peabee** [comment]
In my 5.16.x

CONFIG_MODULE_SIG is not set

Marv is an experienced user - I'm sure he would use matching vmlinuz & zdrv....

**Comment by dimkr** [comment]
Without `CONFIG_MODULE_SIG_FORCE=y`, `CONFIG_MODULE_SIG=y` is harmless. The kernel will warn when a module isn't signed correctly.

But still, this doesn't explain why the module is not signed, or has the wrong signature. A bad mix of vmlinuz+zdrv is still the only explanation I see, whether you like it or not.
