### ISSUE TITLE
Make root partition identifiable in frugalify

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2829]
Frugalify depends on kernel cml to define root partition as /dev/root  mounted  in /initrd (that then links to /mnt/home).
However, many puppy scripts interrogate /proc/mounts to identify the root partition and thus fail. Most characteristically mount, pmount, drive_all, frontend_rox_funcs, filemnt, and others.

Would be useful if code could be included to make the root partition identifiable in /proc/mounts (also) as /dev/sdXN to avoid rewriting all script to work both in the initrd and the frugalify setting

**Comment by dimkr** [comment]
Fixed by https://github.com/puppylinux-woof-CE/frugalify/commit/1504792b8b37aa0c9fd654adff6e5099c7c51adf.

**Comment by mavrothal** [comment]
Thanks but is not there yet (by bad)
Is nice that now is clear that /dev/sdXN is mounted on /initrd
But the mounting of /dev/sdXN on /mnt/home is not needed (sorry) as puppy scripts expect /mnt/home to be a link.
The problem is that they want this link to be on /initrd/mnt/dev_save and not /initrd as originally in frugalify.

I guess what would be a  fix is to drop the flugalify portion that mounts /dev/sdXN on /mnt/home and then link /initrd to /initrd/mnt/dev_save and then /mnt/home to /initrd/mnt/dev_save, so the `readlink /mnt/home` command will output the expected /initrd/mnt/dev_save

**Comment by dimkr** [comment]
@mavrothal https://github.com/puppylinux-woof-CE/woof-CE/pull/2832
