### ISSUE TITLE
XML error in theme Evil_blue_glow-jwmr

### ISSUE THREAD

**Issue by JWMKit** [puppylinux-woof-CE/woof-CE#2837]
typo in the theme Evil_blue_glow-jwmrc at line 6
`<Width>4</Width`
should be
`<Width>4</Width>`
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-packages/jwm_config/usr/share/jwm/themes/Evil_blue_glow-jwmrc

**Comment by 01micko** [comment]
Thanks for that. Never used it so never noticed.
