### ISSUE TITLE
move package support to /var

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#285]
I do not know the historical reasons that ppm support files are in /root/.packages but placing them in /var/packages makes more sense and will facilitate multi-user support or even fido/spot etc.
The change looks pretty simple (just a sed command) and for pets that still look in /root/.packages a symlink should do.
I guess it can wait till after the first woof-CE puppy release ;)

**Comment by wdlkmpx** [comment]
If /root/.packages points to /var/packages 
And all matches of '/root/.packages' have been replaced with '/var/packages'
I don't see how errors can occur

These are all the files containing /root/.packages


	woof-code/0setup
	woof-code/3builddistro
	woof-code/3builddistro-Z
	woof-code/packages-templates/gnome-mplayer/pinstall.sh
	woof-code/packages-templates/gxine/usr/bin/gxineshell
	woof-code/rootfs-skeleton/etc/profile
	woof-code/rootfs-skeleton/etc/rc.d/rc.update
	woof-code/rootfs-skeleton/usr/bin/dir2pet
	woof-code/rootfs-skeleton/usr/bin/petspec
	woof-code/rootfs-skeleton/usr/bin/pman
	woof-code/rootfs-skeleton/usr/local/petget/check_deps.sh
	woof-code/rootfs-skeleton/usr/local/petget/configure.sh
	woof-code/rootfs-skeleton/usr/local/petget/dependencies.sh
	woof-code/rootfs-skeleton/usr/local/petget/devx_service_pack.sh
	woof-code/rootfs-skeleton/usr/local/petget/downloadpkgs.sh
	woof-code/rootfs-skeleton/usr/local/petget/fetchinfo.sh
	woof-code/rootfs-skeleton/usr/local/petget/filterpkgs.sh
	woof-code/rootfs-skeleton/usr/local/petget/findmissingpkgs.sh
	woof-code/rootfs-skeleton/usr/local/petget/findnames.sh
	woof-code/rootfs-skeleton/usr/local/petget/finduserinstalledpkgs.sh
	woof-code/rootfs-skeleton/usr/local/petget/hacks-postinstall.sh
	woof-code/rootfs-skeleton/usr/local/petget/installed_size_preview.sh
	woof-code/rootfs-skeleton/usr/local/petget/installmodes.sh
	woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh
	woof-code/rootfs-skeleton/usr/local/petget/installpreview.sh
	woof-code/rootfs-skeleton/usr/local/petget/petget
	woof-code/rootfs-skeleton/usr/local/petget/pkg_chooser.sh
	woof-code/rootfs-skeleton/usr/local/petget/README-add-repo.htm
	woof-code/rootfs-skeleton/usr/local/petget/removepreview.sh
	woof-code/rootfs-skeleton/usr/local/petget/service_pack.sh
	woof-code/rootfs-skeleton/usr/local/petget/show_installed_version_diffs.sh
	woof-code/rootfs-skeleton/usr/local/video_upgrade/video_upgrade_wizard
	woof-code/rootfs-skeleton/usr/local/video_upgrade/which_ati_pkg
	woof-code/rootfs-skeleton/usr/local/video_upgrade/which_nvidia_pkg
	woof-code/rootfs-skeleton/usr/sbin/bootmanager
	woof-code/rootfs-skeleton/usr/sbin/indexgen.sh
	woof-code/rootfs-skeleton/usr/sbin/momanager
	woof-code/rootfs-skeleton/usr/sbin/pmodemdiag
	woof-code/rootfs-skeleton/usr/sbin/quicksetup
	woof-code/rootfs-skeleton/usr/sbin/remasterpup2
	woof-code/rootfs-skeleton/usr/sbin/remove_builtin
	woof-code/rootfs-skeleton/usr/sbin/sfsget
	woof-code/support/3compat2pets
	woof-code/support/findpkgs
	woof-code/support/pkgsinlivecd
	woof-code/support/slacko/woof_base_hack
	woof-code/support/slacko/woof_base_hack.old

**Comment by mavrothal** [comment]
As Mick/SRF have commend above, we also have to consider what ever is already out there.
We could go ahead with this and link $HOME/.packages to /var/packages in the beginning. 
We should also make sure that woof-building is not messed up by this change.

**Comment by wdlkmpx** [comment]
I think this needs to happen ASAP, should i break stuff in testing or create a new branch?

**Comment by wdlkmpx** [comment]
Here is a test iso where this change is already implemented: 

www.01micko.com/wdlkmpx/stretch-7.0.0a1-20170607_925b23ee.iso

md5:    2e78be2cdbae9581fe4295a827419661

**Comment by wdlkmpx** [comment]
Has anyone tried the iso i provided? It seems stable enough to go to rationalise, but i renamed and relocated fido, i might have to bring back that ugly dog as another account.  It's getting hard for me push anything to testing as the changes in w affected a lot of files. i spent a lot of time on this and i really don't see the results i planned. i don't really want to branch out, but i don't have time to hunt and fix all the possible bugs i'll introduce, so this leaves with no other options than

**Comment by peabee** [comment]
Downloaded & boots OK....what do you want tested? Installing a .pet by clicking on it and uninstalling it from ppm seemed to work OK.

Things I noticed:
icons missing in both menu and ppm
pcmanfm from menu gives error
no way to switch filemanager in puppyapps
only retrovol in systray
some libs missing - see attached
[checkdeps_system.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/1161688/checkdeps_system.txt)

**Comment by wdlkmpx** [comment]
Yeah, installing, uninstalling packages. I'm aware of all the other issuess..

i don't run pcmanfm through the menu. i change the filemanager manually, it was causing problems in puppyapps because of the hardcoded rox stuff everywhere. 
i have a more complete theme locally... i would use the icons in /usr/share/pixmaps/puppy instead of the old themes.. 
i don't miss any of the tray apps

other than that, i have my own set of scripts and stuff that i can apply to the default build. it would be too cool and a true system rescue distro that i'm keeping  for myself out of pure selfishness..

**Comment by wdlkmpx** [comment]
This is actually something easy to do.

0) rootfs-skeleton: make /root/.packages a symlink to /var/...
1) 3builddistro-Z adds stuff to /var/local/packages or /var/packages/puppy ?
2) rc.sysinit verifies that /root/.packages is always a symlink to the correct directory

Some convoluted logic in rc.sysinit to move/copy files to update stuff if /root/.packages is an actual directory

All the references to /root/.packages in the ppm and other apps will not be changed to /var/.. not until the ppm state is discussed, cause i have some changes i won't be able to finish haha

/root/.pup_event -> /tmp/pup_event_frontend was a success, thanks to some logic in frontend_startup that always ensures /root/.pup_event is a symlink, so this change and many others i made can survive an upgrade, but there are sooo many changes that some of them may not be compatible with upgrades. the multiarch symlink (pull request) will never be

Now:

/root/spot -> /home/spot is quite easy as well.

What's somewhat difficult is (fido) /root -> /home/fido or /home/finn, rox, jwm, fixmenus, etc... have hardcoded /root stuff, but if you use something else it really isn't a problem. I already attempted to do this with some success in some lost changes, but now i can do it better, but it doesn't look appealing anymore

**Comment by 01micko** [comment]
Isn't this done by now?
