### ISSUE TITLE
frontend_change is killed if desktop not provided by ROX-Filer - why? line 58

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2852]
@rizalmart this was your change #2583 

Not entirely sure why this has emerged as an issue.........but in my new build of LxPupSc using Slackware-15.0
line 58 of
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/local/pup_event/frontend_change

kills pup_event 
frontend_change 
if ROX-Filer is not providing the desktop (e.g. for LXDE PCManFM provides the desktop)

Can line 58 be deleted?? Why is it there??

**Comment by 01micko** [comment]
Why do you need it?

As far as I can tell, all the code in there is rox specific.

**Comment by peabee** [comment]
Because I want frontend_change to run to completion when the desktop is LXDE..... so that the auto-launch handlers are run when new devices are detected.

**Comment by 01micko** [comment]
Ok, but I think the whole script needs a rewrite.

I'll approve #2852 but raise another issue.
