### ISSUE TITLE
How about x(print)idle?

### ISSUE THREAD

**Issue by JakeSFR** [puppylinux-woof-CE/woof-CE#286]
'getcurpos' is very handy, little binary, however its use in 'frontend_timeout' to measure time of user's inactivity is IMO wrong, as it relies only on mouse, not keyboard.
I'd like to propose an inclusion of another little and very handy piece - xidle, from:
https://github.com/ericpruitt/lintils
or xprintidle (which source at http://freecode.com/projects/xprintidle seems to be unavailable ATM).
Each of them, compiled & stripped, takes only ~5K (personally I prefer xidle).

Appropriate part in frontend_timeout could be simplified like this then:
```
MINUTECNT=0
[ -f /tmp/pup_event_frontend_timeout_minutecnt ] && MINUTECNT="`cat /tmp/pup_event_frontend_timeout_minutecnt`"

 if [ $POWERTIMEOUT -ne 0 ];then #power-off computer after inactivity.
  MINUTECNT=`expr $MINUTECNT + 4`
  echo -n "$MINUTECNT" > /tmp/pup_event_frontend_timeout_minutecnt
  if [ $MINUTECNT -gt 59 ];then #come in here every minute...
   MINUTECNT=0
   echo -n "$MINUTECNT" > /tmp/pup_event_frontend_timeout_minutecnt
   IDLETIME=`xidle -i`
   #IDLETIME=`expr \`xprintidle\` \/ 1000`
   [ $IDLETIME -ge $POWERTIMEOUT ] && wmpoweroff &
  fi
 fi
```
What do you think?

Greetings!

**Comment by 01micko** [comment]
Feel free to re-open if the need arises.
