### ISSUE TITLE
Kernel config change in Dpup 9.1.10?

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2890]
Running 9.1.10 from a USB2 stick on a macbook (version 11,2) fails both to load zram and recognise the touchpad.
9.1.7 was running happily on the same machine from the same stick.
9.1.10 runs fine on the same machine but on a VM (and yes checked md5s to be correct)
Using the existing /upper or with pfix=ram, same result
Also noticed that it fails to recognise the in /upper when running from the USB
I have noticed some kernel config changes are they after 9.1.9 (so I can check that to make sure that are indeed kernel related)?

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/commits/testing/kernel-kit/configs_x86_64/DOTconfig-5.10.60-x86_64

This is the changelog. Only two harmless changes (=y instead of =m).

**Comment by dimkr** [comment]
If you have something else installed on an internal disk, #2889 can explain what happened.

**Comment by mavrothal** [comment]
9.1.9 runs fine in the same USB setting.
#2889 I do  not think is  relevant as I did a manual installation from the tar file and I boot with rEFind (as I mentioned before your bootx86.efi  can not boot Macs)

Was pfix=nox in rc.sysinit implemented yet, so I can get to console and check what might be wrong?

**Comment by dimkr** [comment]
> Was pfix=nox in rc.sysinit implemented yet, so I can get to console and check what might be wrong?

Modify rc.sysinit. Put your modified version in /upper/save/etc/rc.d/rc.sysinit.

**Comment by mavrothal** [comment]
No cigar.
I have no keyboard either. 
Connecting an external one also fails
Looks like the entire USB subsystem is broken

Though must be something more that the USB_UHCI_HCD. Is hard to explain the zram loading failure by that change

I guess I could use vmlinuz/zdrv/ucode from 9.1.9 and check or there is any kernel hard coding elsewhere?

**Comment by mavrothal** [comment]
> I guess I could use vmlinuz/zdrv/ucode from 9.1.9 and check

It works fine!
zram, USB, the works
So is clearly the kernel.
I was wondering though, as is hard to explain the zram failure, if it is indeed the kernel config or if the kbuild (re)moved/changed something that it should't.  
Or was the kernel  build in a system with both kbuild and kernel-kit loaded that somehow generated a problem?

**Comment by mavrothal** [comment]
The bad news is that 5.10.102 kernel from 9.1.11 still fails in my MacBook Pro
The good news is that I recompiled the kernel with an older config (from v99 that works on this Mac) and still fails.
So it looks like is something in the kernel itself. 
The problem is the v101 and v102 introduced  a LOT of changes to fish out the problem over v99.
Hopefully this problem will surface elsewhere and get fixed upstream
