### ISSUE TITLE
Zoom is broken

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2933]
This happens on dpup with Xwayland:

![zoom](https://user-images.githubusercontent.com/1471149/156165813-57e5701e-6868-4d1f-96da-c88de4f1259e.png)

**Comment by Phoenix-Starlight** [comment]
There's a known way for X.org specifically but unfortunately I have not figured how to get Zoom to catch any URL or protocol with it. The environment variable `` LIBGL_ALWAYS_SOFTWARE=1`` needs to be set for it. Perhaps there's an equivalent variable for Wayland.

**Comment by dimkr** [comment]
Looks like Zoom is now promoting the PWA solution.

**Comment by dimkr** [comment]
In case anyone finds this issue in the future and wants a working solution:  https://forum.puppylinux.com/viewtopic.php?p=63869

(happens with X.Org too)
