### ISSUE TITLE
overlayfs support in initrd.gz

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2962]
overlayfs is the de-facto standard these days, and aufs is increasingly problematic. It takes time for it to catch up with new kernel versions, sometimes it breaks across bugfix kernel version updates, and sometimes, it leads to kernel panics.

I think it's time to support overlayfs, at least, as a non-default alternative to aufs.

**Comment by peabee** [comment]
There is lots of work on the forum to use overlayfs - no need to reinvent the wheel.
AUFS is more flexible than overlayfs - a Puppy using overlayfs would be a different beast and should arguably be renamed.
AUFS is actively supported and deserves support and use as a "better" alternative to overlayfs. If AUFS support ceases, then is the time to move to overlayfs.
I don't understand the push to make Puppy "just another boring Linux distro" - there are many, many such distros and if Puppy's slightly quirky characteristics don't match your world view then maybe you would be happier using one of those other distros.....
What will be the next push I wonder - systemd?? multi-user non-root default?? - heaven forbid!

and we already have in _00build.conf:
```
## UnionFS: aufs or overlay
UNIONFS=aufs
```

**Comment by dimkr** [comment]
> AUFS is more flexible than overlayfs

It has more features, but features are not everything. overlayfs is faster and more stable, at least in some cases, so I wouldn't throw it out the window only because sfs_load needs to be re-implemented.

> I don't understand the push to make Puppy "just another boring Linux distro"

It's a push towards making Puppy less reliant on outdated, buggy or unreliable dependencies - X.Org, GTK + 2, aufs, PPM, you name it.

And I'm merely suggesting *adding* overlayfs support, so you can keep doing your thing.

> and we already have in _00build.conf:

I don't think this line does what you think it does:

```
~/woof-CE$ grep  UNIONFS `find woof-code initrd-progs -type f` 2>/dev/null
woof-code/_00build.conf:UNIONFS=aufs
woof-code/rootfs-skeleton/etc/rc.d/rc.shutdown:[ "$PUNIONFS" = "aufs" ] && sfs_load --cli stop
woof-code/rootfs-skeleton/etc/rc.d/rc.shutdown:# remount PUNIONFS read-only
woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit:[ "$PUNIONFS" = "aufs"  ] && sfs_load --cli start
woof-code/rootfs-skeleton/etc/rc.d/rc.update:if [ "$PUNIONFS" = "aufs" ];then
woof-code/rootfs-skeleton/usr/sbin/sfs_load:if [ "$PUNIONFS" = "overlay" ] ; then
woof-code/rootfs-skeleton/usr/sbin/extrasfsfind:if [ "$PUNIONFS" = "overlay" ] ; then
woof-code/3builddistro:	echo "PUNIONFS='overlay'" >> rootfs-complete/etc/rc.d/PUPSTATE
initrd-progs/0initrd/init:echo "PUNIONFS='aufs'"
```

Please correct me if I'm wrong, but aufs is hardcoded all over the place, and this variable is only used to decide whether or not to run sfs_load.

**Comment by dimkr** [comment]
"Whoa, we're halfway there"

It looks like Puppy, it feels like Puppy, because it is Puppy. But with overlayfs instead of aufs.

![overlay](https://user-images.githubusercontent.com/1471149/157212781-50696ff5-00c3-4a42-aaca-35affa3dba26.png)

**Comment by JamesC1** [comment]
I'm currently running a hack-up with sfs save files, copied into ram (/initrd/mnt/tmpfs), in a perversion of pupmode 13.

I am using the mount option trick 'ro,shwh', to preserve whiteouts from generation to generation of the single sfs savefile.

I have looked at overlayfs, and cannot find the equivalent of shwh.  Am I missing something obvious?

**Comment by dimkr** [comment]
> I have looked at overlayfs, and cannot find the equivalent of shwh. Am I missing something obvious?

Yes, overlay is not very feature-rich, and most special features in aufs are either unavailable, or dangerous to emulate.

In #2963, snapmergepuppy.overlay propagates overlay whiteout from pup_rw files to pup_ro1, if they hide a file from one of the SFSs, and that should minimize the number of whiteout files in the savefile.
