### ISSUE TITLE
Flickering in swaylock after wlopm --on

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#3030]

**Comment by 01micko** [comment]
I was getting flicker with the old `wlr-randr` method but none now :confused:

**Comment by dimkr** [comment]
There's a 1/5 chance of flickering after swayidle runs wlopm. Something like that.

**Comment by 01micko** [comment]
I do notice that on my dual monitor setup that waking with key press only wakes 1 monitor but mouse movement reliably wakes both monitors.
