### ISSUE TITLE
cursor theming is messy

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#3051]
At the moment we need to link a cursor theme from `/usr/share/icons` my theme to `$HOME/.icons/default` but that only does part of the job. Many (all?) puppy cursor themes are installed to `$HOME/.icons` (usually _root_) which makes it messy for apps running as spot to pick up the cursor.

I think (not 100% sure) cursors need to be in $HOME for gtk2 apps. For gtk3 apps `gsettings` should take care of cursor theme.

`pcur` is the cursor manager. Perhaps it should be re-written to detect themes in `/usr/share/icons` and make the links to $HOME, then if needed run gsettings.

BUT, if using a wayland compositor such as `labwc` cursor settings are part of the `environment` file! Yeah, at the moment that's a corner case but I'll deal with it anyway.

**Comment by 01micko** [comment]
@dimkr 

Does `dwl` require `gsettings` to switch cursor theme? (or anything else?)

**Comment by 01micko** [comment]
I have `pcur` working well now:
- detects themes in `/usr/share/themes`
- works with labwc

![pcur](https://user-images.githubusercontent.com/1019119/164998776-6218ec6c-a0fa-41f3-9d2a-94e2f4416935.png)

`pcur` diff:

```diff
--- /initrd/pup_ro2/usr/sbin/pcur	2021-12-04 06:18:20.000000000 +1000
+++ /usr/sbin/pcur	2022-04-25 08:33:36.446983909 +1000
@@ -32,6 +32,9 @@ func_switch (){
 			jwm -restart
 		elif pidof openbox >/dev/null 2>&1 ; then
 			openbox --restart
+		elif pidof labwc >/dev/null 2>&1 ; then
+			. /etc/rc.d/wl_func
+			func_labwc "$1"
 		fi
 	fi
 }
@@ -46,8 +49,8 @@ func_download (){
 	rm $PKG
 	/usr/lib/gtkdialog/box_ok "pCur - $(gettext 'Cursor theme setter')" complete "$(gettext 'New themes are installed. <b>Please restart pCur</b> - Cursor theme setter.')" && exit 0
 }
-export -f func_switch func_download
 
+export -f func_switch func_download
 
 #parameters
 while [ $# != 0 ]; do
@@ -75,6 +78,12 @@ if [ "$THEME" ]; then
 	exit
 fi
 #---
+# link cursor themes in /usr/share/icons to $HOME
+while read -r ITHEME; do
+	ETHEME="${ITHEME/\/cursors/}"
+	XTHEME="${ETHEME##*\/}"
+	[ -e "$HOME/.icons/$XTHEME" ] || ln -sv "$ETHEME" $HOME/.icons
+done <<<$(find /usr/share/icons/ -maxdepth 2 -type d -name 'cursors')
 
 for ONEITEM in `ls -1 $HOME/.icons | grep -Ev 'ROX|^default$'`; do
 	#precaution that 'cursors' subdir exists...

```

**Comment by 01micko** [comment]
This is added to the `/etc/init.d/wl_func`

```
+func_labwc (){
+	gsettings set org.gnome.desktop.interface cursor-theme "$1"
+	[ `id -u` -eq 0 ] && run-as-spot gsettings set org.gnome.desktop.interface cursor-theme "$1"
+	grep -q 'XCURSOR_THEME' $XDG_CONFIG_HOME/labwc/environment && sed -i "s/XCURSOR_THEME.*/XCURSOR_THEME=$1/" $XDG_CONFIG_HOME/labwc/environment || \
+		echo "XCURSOR_THEME=$1" >> $XDG_CONFIG_HOME/labwc/environment
+	/usr/lib/gtkdialog/box_splash -bg orange -close box -timeout 7 -text "$(gettext 'To activate the new theme labwc needs to be restarted - just restart X')"
+}
```

**Comment by dimkr** [comment]
> @dimkr
> 
> Does `dwl` require `gsettings` to switch cursor theme? (or anything else?)

As far as I see, no - #2102 and #2221 are enough. But it can't hurt to add that `gsettings set`.
