### ISSUE TITLE
ntfs boot failure with kernels 5.10 and 5.15

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3058]
Even after #3056 
slacko-8.2.2-174.iso  ([build-x86-slackware-15.0-174])
fails to boot from an ntfs formatted boot partition
5.10 and 5.15 both fail
5.4 is OK

**Comment by dimkr** [comment]
Without the output of `dmesg` after failed mount, it will be very hard to fix this.

**Comment by peabee** [comment]
It drops out to a working terminal and commands can be run..........

**Comment by peabee** [comment]
dmesg can be run but its output needs to be store somewhere....

I think /tmp/bootsysinit.log has more interesting information.....

**Comment by peabee** [comment]
> Without the output of `dmesg` after failed mount, it will be very hard to fix this.
[bootinit.log](https://github.com/puppylinux-woof-CE/woof-CE/files/8580129/bootinit.log)
[dmesg.log](https://github.com/puppylinux-woof-CE/woof-CE/files/8580131/dmesg.log)

**Comment by peabee** [comment]
At console, after boot is aborted:
mount -t ntfs /dev/sda1 /mnt/pdrv

works correctly

**Comment by dimkr** [comment]
I bet it's NLS-related (=m instead of =y), just boot with `pfix=rdsh`, do that `mount` and see what `dmesg` says

**Comment by peabee** [comment]
Same result with pfix=rdsh - bombs out to console where mount works

**Comment by peabee** [comment]
Any other ideas of things to try?

**Comment by dimkr** [comment]
> bombs out to console where mount works

What does dmesg say, when you run it from the initrd shell?

**Comment by peabee** [comment]
debugsave output:
[zz_initrd_tmp.sfs-false.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/8592207/zz_initrd_tmp.sfs-false.gz)
