### ISSUE TITLE
savefile / folder problem with DISTRO_SPECS

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3059]
Reopened with different issue - below

**Comment by peabee** [comment]
slacko-8.2.2-174.iso
the DISTRO_SPECS in the savefile / folder is different to the version in the puppy.sfs leading to an upgrade request every reboot.

**Comment by dimkr** [comment]
> the DISTRO_SPECS in the savefile / folder is different to the version in the puppy.sfs leading to an upgrade request every reboot.

These are development builds, build x+1 can be incompatible with build x. I think it's a good idea to increment the version number in every build, otherwise you have no idea what you're testing things on (version x, version x+1 or a blend of the two).

**Comment by peabee** [comment]
No thats not the problem - the update happens EVERY REBOOT not just when a version changes....
The problem is also that the update is trying to be from 8.2.2-174 to just 8.2.2

**Comment by dimkr** [comment]
> 8.2.2-174 to just 8.2.2

Again, -174 may be incompatible with -173, these are testing builds. Some can be great, some can be alpha-grade. I think it's reasonable.

**Comment by peabee** [comment]
Again - thats not the problem.......

These are REBOOTS of -174 which are exhibiting a desire to update every time

NOT version changes

**Comment by peabee** [comment]
BTW....
build-x86-slackware-14.2-174
also exhibits this problem - and this is not an "experimental" system.....
[bootsysinit.log](https://github.com/puppylinux-woof-CE/woof-CE/files/8574881/bootsysinit.log)

**Comment by dimkr** [comment]
> also exhibits this problem - and this is not an "experimental" system.....

Both are built from a branch called "testing" that changes often and sometimes has breaking changes, let's not forget that.

**Comment by peabee** [comment]
OK it definitely has a breaking change!
