### ISSUE TITLE
ptheme doesn't support labwc

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#3069]
Ptheme needs support for labwc and sfwbar/yambar

Working on it.

**Comment by 01micko** [comment]
Working nicely :smile_cat: 



https://user-images.githubusercontent.com/1019119/166222156-7e14fb21-5bae-455b-9258-5108c2febfbe.mp4

**Comment by dimkr** [comment]
Wow, looks awesome. I really like the consistency between the panel and everything else (thanks to the use of GTK). I'm working on something similar with dwl (patched with floating windows, etc'), but with CSD, so even the window title is themed by GTK+.

**Comment by 01micko** [comment]
On my lappy - `PUPMODE=5`

Still some stuff to do, like `libinput` tapping, scrolling but quite usable. :^)


https://user-images.githubusercontent.com/1019119/166674064-a3c7aaf1-5886-49ab-8373-932380312e31.mp4

`ptheme/pinstall` for cursor still needs attention, but once libinput and that are done this is ready for prime time.
