### ISSUE TITLE
petbuild JWM-2.3.7 crash report

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3073]
https://forum.puppylinux.com/viewtopic.php?p=56878

> by gychang » Fri May 06, 2022 8:40 pm
> move command in JWM crashes. Command in jwmrc-personal allows for a window to be moved without using a mouse. I use "CS-m" keybinding and in fossapup64 works well, but in Jammy it crashes to a blank screen with prompt, tried assigning other keybinding and still crashes.

also reports that http://ftp.de.debian.org/debian/pool/main/j/jwm/jwm_2.3.7-5+deb11u1_i386.deb does not crash

Sounds somewhat like a problem that was reported and fixed on the old-forum:
https://oldforum.puppylinux.com/viewtopic.php?p=1057882

**Comment by peabee** [comment]
@01micko - also crashes in slacko-8.2.2-174

Right click the top edge of a window - select "Move" - crash - dmesg:
[   43.457991] jwm[9755]: segfault at 78 ip 04f631c0 sp bfd57110 error 6 in jwm[4f47000+2e000]
[   43.458002] Code: 83 84 0e 00 00 89 44 24 04 e8 ec e7 00 00 3b 47 34 72 ce 8b 46 04 8b 16 89 83 88 0e 00 00 8b 83 8c 0e 00 00 89 93 84 0e 00 00 <83> 48 78 04 80 bb 94 0e 00 00 00 0f 85 97 00 00 00 80 bb 93 0e 00

**Comment by peabee** [comment]
also crash:

slacko64-8.2.2-147

ScPup32-22.02+0-T

**Comment by 01micko** [comment]
I'd update to 2.4.1 but there is another serious bug! https://github.com/joewing/jwm/issues/563

**Comment by 01micko** [comment]
It's still 2.3.7 until 2.4.1 gets fixed and then we can look at `ptheme`

**Comment by 01micko** [comment]
64 bit binary for testing purposes in this post https://github.com/puppylinux-woof-CE/woof-CE/pull/3075#issuecomment-1120658419

**Comment by 01micko** [comment]
Ok now that the jwm-2.4.1 bug is fixed (https://github.com/joewing/jwm/issues/563#issuecomment-1126534526), as soon as the pt_BR translation is fixed or reverted we can move to the latest release of JWM  - and incidentally, `ptheme` works perfectly with it _as is_.
