### ISSUE TITLE
run-as-spot problem

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3077]
/usr/sbin/run-as-spot: line 48: syntax error: unexpected redirection

**Comment by dimkr** [comment]
What Puppy is that? What do you have in /bin/sh? What busybox version are you using?

EDIT: looks like support for process substitution (the `<()` syntax) was introduced in ash in busybox 1.34

**Comment by peabee** [comment]
Worked fine up until recent changes.........

JammyPup32
symbolic link to bash
:busybox:|pet|Packages-puppy-common32-official|busybox-1.31.0-x86_musl_static-2|busybox|1.31.0-x86_musl_static-2||BuildingBlock|1048||busybox-1.31.0-x86_musl_static-2.pet||No description provided||||

**Comment by dimkr** [comment]
These changes require a newer busybox, and you're using busybox from 2019. Is there any reason not to update?

**Comment by peabee** [comment]
Only that this is the first time that an update has been required by a code change.... and there have been no issues with the busybox used to date....

Presumably this could also affect all Woof-CE builds with yes|busybox in their DISTRO_PKGS_SPECS i.e.

/woof-distro/arm/raspbian/buster/DISTRO_PKGS_SPECS-raspbian-buster
/woof-distro/x86_64/debian/buster64/DISTRO_PKGS_SPECS-debian-buster
/woof-distro/x86_64/slackware64/14.0/DISTRO_PKGS_SPECS-slackware64-14.0
/woof-distro/x86_64/slackware64/14.1/DISTRO_PKGS_SPECS-slackware64-14.1
/woof-distro/x86_64/ubuntu/bionic64/DISTRO_PKGS_SPECS-ubuntu-bionic
/woof-distro/x86_64/ubuntu/focal64/adrv/DISTRO_PKGS_SPECS-ubuntu-focal
/woof-distro/x86_64/ubuntu/trusty64/DISTRO_PKGS_SPECS-ubuntu-trusty
/woof-distro/x86_64/ubuntu/xenial64/DISTRO_PKGS_SPECS-ubuntu-xenial
/woof-distro/x86/debian/buster/DISTRO_PKGS_SPECS-debian-buster
/woof-distro/x86/debian/stretch/DISTRO_PKGS_SPECS-debian-stretch
/woof-distro/x86/slackware/14.0/DISTRO_PKGS_SPECS-slackware-14.0
/woof-distro/x86/slackware/14.1/DISTRO_PKGS_SPECS-slackware-14.1
/woof-distro/x86/ubuntu/trusty/DISTRO_PKGS_SPECS-ubuntu-trusty
/woof-distro/x86/ubuntu/upupbb/DISTRO_PKGS_SPECS-ubuntu-bionic
/woof-distro/x86/ubuntu/xenial/DISTRO_PKGS_SPECS-ubuntu-xenial

will they all be updated?

**Comment by dimkr** [comment]
Most of these are unmaintained and already broken, so I'm not worried about extra breakage.

I'm still not sure what's the best way to fix this, but I see two easy solutions:
1) Getting rid of the 3 year old busybox package, this can be done by replacing the busybox .pet with the petbuild
2) Changing to `#!/bin/bash`, but this will slow down run-as-spot for everyone because now it uses a bigger shell

**Comment by peabee** [comment]
Aside: the broken builds should probably be moved to the "legacy" branch. (bionic64? focal64? are still being built)

2. has my vote (is slowdown significant?) - but is there a 3. - change coding?

**Comment by dimkr** [comment]
> is there a 3. - change coding?

As far as I know, there are two ways to do this cleanly, with `<()` and `<<<`, but both are non-standard.

**Comment by peabee** [comment]
Replacing the busybox .pet with the busybox petbuild is not entirely straightforward as they are not 100% compatible - vercmp is missing in the petbuild ..... see #3080

**Comment by dimkr** [comment]
vercmp comes from a different petbuild, aaa_pup_c.
