### ISSUE TITLE
Unknown / Unwanted Strange artefacts?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3084]
Why?

Why do I see these mounts?:
/dev/sda2 /var/lib/containers ext4 rw,noatime 0 0
/dev/sda2 /home/spot/.local/share/containers ext4 rw,noatime 0 0

Why do I have this folder?:
/root/.config/swayidle

Why does blkid show these entries?:
```
# blkid
/initrd/mnt/dev_save/puptest/puppy_bionicpup64_8.0.sfs: TYPE="squashfs"
/initrd/mnt/dev_save/puptest-isos/bionic64/bionicpup64-8.0-uefi.iso: BLOCK_SIZE="2048" UUID="2019-02-26-11-15-32-26" LABEL="CDROM" TYPE="iso9660" PTUUID="748f56d3" PTTYPE="dos"
/initrd/mnt/dev_save/puptest-isos/isos/slacko-7.0.iso: BLOCK_SIZE="2048" UUID="2021-01-03-18-36-18-68" LABEL="CDROM" TYPE="iso9660" PTUUID="17667664" PTTYPE="dos"
/initrd/mnt/dev_save/puptest-isos/isos/slacko64-7.0.iso: BLOCK_SIZE="2048" UUID="2021-01-03-18-33-12-54" LABEL="CDROM" TYPE="iso9660" PTUUID="54b6269d" PTTYPE="dos"
/initrd/mnt/dev_save/puptest/puppy_slacko64_7.0.sfs: TYPE="squashfs"
/initrd/mnt/dev_save/puptest/puppy_slacko_7.0.sfs: TYPE="squashfs"
/initrd/mnt/dev_save/puptest/puppy_buster_8.0.0.sfs: TYPE="squashfs"
/initrd/mnt/dev_save/puptest/puppy_buster_8.0.sfs: TYPE="squashfs"
/initrd/mnt/dev_save/puptest/puppy_stretch_7.5.sfs: TYPE="squashfs"
/initrd/mnt/dev_save/puptest-isos/dpup/buster/dpupbuster-32bits-jwm-PAE-8.0.0-RC2_27072020.iso: BLOCK_SIZE="2048" UUID="2020-07-27-20-55-52-00" LABEL="CDROM" TYPE="iso9660"
/initrd/mnt/dev_save/puptest/puppy_xenialpup_7.5.sfs: TYPE="squashfs"
/initrd/mnt/dev_save/pupmain/firefox52.sfs: TYPE="squashfs"
/mnt/sdc1/test2/slacko32-8.2/slacko-8.2.2-179.iso: BLOCK_SIZE="2048" UUID="2022-05-09-08-39-14-73" LABEL="CDROM" TYPE="iso9660"
/mnt/sdc1/test2/puppy_slacko_8.2.2-179.sfs: TYPE="squashfs"
```

**Comment by dimkr** [comment]
This is a feature, not a bug - see #3044.

Many tools (for example, https://github.com/89luca89/distrobox) use Podman these days, and it's nearly impossible to use Puppy for development without a working container runtime.

**Comment by peabee** [comment]
"This"???

#3044 says "Make buildah and podman work in **jammy64**" - I'm not in jammy64............

**Comment by peabee** [comment]
The mounts are not unmounted cleanly because they appear in the shutdown messages..........

**Comment by dimkr** [comment]
> The mounts are not unmounted cleanly because they appear in the shutdown messages..........

These "mounts" are bind mounts, and I don't see how not unmounting them can lead to problems.

**Comment by woodenshoe-wi** [comment]
> 
> These "mounts" are bind mounts, and I don't see how not unmounting them can lead to problems.

Is there any risk that they would keep filesystems “busy” and not allow other filesystems to unmount cleanly?

**Comment by dimkr** [comment]
> Is there any risk that they would keep filesystems “busy” and not allow other filesystems to unmount cleanly?

They hold a reference, so the bind mount target is still mounted unless the bind mounts are unmounted too. As long as the code in rc.shutdown umounts *all* mounts that need to be unmounted, it's fine.

**Comment by peabee** [comment]
Why are there all those strange entries shown by blkid?? How do I stop them appearing?

**Comment by peabee** [comment]
I seem to have in my savefolder both:
/run/blkid/blkid.tab
/etc/blkid-cache

/run/blkid/blkid.tab has all the unwanted entries in it and seems to have older timestamps than /etc/blkid-cache

Should one or both be deleted at shutdown??

**Comment by dimkr** [comment]
What are you trying to achieve by deleting these files?

**Comment by peabee** [comment]
I'm not trying to delete files.........
I'm trying to find out why the blkid display contains spurious items - old entries for iso and sfs that have been mounted previously but are no longer mounted.
I suspect that sfs-unload is leaving entries in the blkid output..... but need to do further testing to confirm if this is the case.
