### ISSUE TITLE
gtkdialog petbuild fails on VoidPup32

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3086]
Help please! Presumably something? missing in the devx........

Errors seem to be at lines 55/56:
./configure: line 5321: syntax error near unexpected token 'gtk+-2.0,,'
./configure: line 5321: '  PKG_CHECK_EXISTS(gtk+-2.0,,'

and lines 309-312:
undefined reference to 'yywrap'

[build-140522.log](https://github.com/puppylinux-woof-CE/woof-CE/files/8692777/build-140522.log)

**Comment by peabee** [comment]
Update.... @01micko @dimkr 

Got rid of yywrap error by adding LEX='flex --noyywrap' thus:
./autogen.sh --prefix=/usr --bindir=/usr/sbin  LEX='flex --noyywrap'

Still get the line 5321 error - the code in ./configure is:
```
if test "x$with_gtkapi" = "x3.0"; then :
  enable_gtk3=yes
elif test "x$with_gtkapi" = "xauto"; then :
  PKG_CHECK_EXISTS(gtk+-2.0,,
			PKG_CHECK_EXISTS([gtk+-3.0],
				[enable_gtk3=yes])
			)

fi

```

**Comment by peabee** [comment]
and the devx does have:

/sandbox3/devx/usr/lib/pkgconfig/gtk+-2.0.pc

**Comment by woodenshoe-wi** [comment]
I’m afraid I might have had something to do with this when I modified configure.ac to automatically choose between gtk+-2.0 and gtk+-3.0

puppylinux-woof-CE/gtkdialog@330c185

I’m not an expert writing autoconf macros but it seemed to work right when I tested it.

What I wrote had the `PKG_CHECK_EXISTS(gtk+-2.0,, ` part written `PKG_CHECK_EXISTS([gtk+-2.0],,` the same as the gtk-+3.0 part.

If I want to try to reproduce this problem I guess I have to download VoidPup32.  Any particular version/link?

**Comment by dimkr** [comment]
> If I want to try to reproduce this problem

It will be much easier for everyone, especially @peabee, if the modified woof-CE used to build VoidPup is merged into woof-CE, with CI that protects VoidPup from breakage.

**Comment by peabee** [comment]
@woodenshoe-wi Thank you for your interest and help

The [ ] around gtk+-2.0 seem to have disappeared.......

@dimkr For many reasons it would be REALLY difficult to transfer what works locally on my PC to something that would work remotely on GitHub...........

However the fault occurs if you just do a simple build/compile of gtkdialog on a system with devx installed. I'll upload the latest .iso and devx to the links below.........

Here is the build to use after:
wget -t 3 -T 60 -O gtkdialog-0.8.5.tar.gz https://github.com/puppylinux-woof-CE/gtkdialog/archive/0.8.5.tar.gz

[build.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/8697539/build.txt)

then:
sh ./build.txt

Links:
iso: https://u.pcloud.link/publink/show?code=XZJUDHVZ8GA5RJBHN3HfRYdiPRUWtbTB4l0X
devx: https://u.pcloud.link/publink/show?code=XZHUDHVZaGdIqEutPhY0ShEsN1DBRbn0gYxX

**Comment by dimkr** [comment]
> @dimkr For many reasons it would be REALLY difficult to transfer what works locally on my PC to something that would work remotely on GitHub...........

I don't see why. If woof-CE can run in an Ubuntu container on GitHub Actions today, I already took care of 99% of the work.

And, even if it takes several hours to upstream VoidPup into woof-CE, it's a good investment because you'll be able to build VoidPup in < 15m, without heating your CPU and reducing the lifespan of your disks. It will be less likely to break over time (Void is a rolling distro, after all) and it will be much easier for others to help you.

**Comment by peabee** [comment]
Tried same build with ScPup32 - works fine - contents of configure are very different.... almost as if macros are not being expanded in VoidPup32......
```
if test "x$with_gtkapi" = "x3.0"; then :
  enable_gtk3=yes
elif test "x$with_gtkapi" = "xauto"; then :
  if test -n "$PKG_CONFIG" && \
    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0\""; } >&5
  ($PKG_CONFIG --exists --print-errors "gtk+-2.0") 2>&5
  ac_status=$?
  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
  test $ac_status = 0; }; then
  :
else
  if test -n "$PKG_CONFIG" && \
    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-3.0\""; } >&5
  ($PKG_CONFIG --exists --print-errors "gtk+-3.0") 2>&5
  ac_status=$?
  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
  test $ac_status = 0; }; then
  enable_gtk3=yes
fi

```

**Comment by peabee** [comment]
> I don't see why.
>  you'll be able to build VoidPup in < 15m, 

@dimkr .........
A local build takes <5min...

Some "problem" areas:

Pre-processing before 0setup to create Packages-void32-current
Post-processing after 2createpackages to produce /var/db/xbps/pkgdb-0.38.plist
Patched 2createpackages to recognise .xbps components
A number of amended packages-templates
No remote repository for some items (10) in packages-pet
Pre-built adrv.sfs and fdrv.sfs added to /sandbox3/build by code in _00build.conf EXTRA_COMMANDS=

**Comment by 01micko** [comment]
@peabee are your autotools sane? Are your perl packages sane?

As this isn't a petbuild, or even a woof problem then maybe raise an issue at gtkdialog repo?

**Comment by peabee** [comment]
> @peabee are your autotools sane? Are your perl packages sane?
> 
> As this isn't a petbuild, or even a woof problem then maybe raise an issue at gtkdialog repo?

Whats the best way to determine sane?
config.log doesn't indicate any problems other than those mentioned above.....

running:
perl --help 
and automake --help
in a terminal doesn't give any errors either

**Comment by 01micko** [comment]
What about the `meson` build?

Does your void have `python3` ?

Try:
```
meson --prefix=/usr --bindir=/usr/sbin -Dgtkver=2 build
ninja -C build
```

**Comment by peabee** [comment]
No meson or ninja in the iso or devx for VoidPup32 - but ScPup32 doesn't have them either....

Similar for python3 - neither VoidPup32 or ScPup32 have it.

**Comment by 01micko** [comment]
> No meson or ninja in the iso or devx for VoidPup32 - but ScPup32 doesn't have them either....
> 
> Similar for python3 - neither VoidPup32 or ScPup32 have it.

These don't need to cost you anything in terms of iso size as they can go directly to `devx`

On another point, to see if @woodenshoe-wi 's changes broke something for your setup then try building at this commit (the link is a direct link to the source at that commit, 1 before 330c185, just unzip and proceed as usual)

https://github.com/puppylinux-woof-CE/gtkdialog/archive/fb46001689610a4736be4934542edfe0db539182.zip

**Comment by woodenshoe-wi** [comment]
> On another point, to see if @woodenshoe-wi 's changes broke something for your setup then try building at this commit (the link is a direct link to the source at that commit, 1 before 330c185, just unzip and proceed as usual)

That was a good idea for a test.

I downloaded the voidpup iso and devx and was able to reproduce the problem.  Using the zip file version of gtkdialog I get  
```
./configure: line 5304: syntax error near unexpected token `GTHREAD,’
./configure: line 5304: `PKG_CHECK_MODULES(GTHREAD, $pkg_modules)’
```

It looks like some of the macros aren’t getting expanded properly and it was just a coincidence that the first failure was in my change?

**Comment by dimkr** [comment]
Try `bash configure`. If it works, maybe /bin/sh is not a symlink to bash.

**Comment by 01micko** [comment]
So we can deduce reasonably that there _is_ something wrong in the voidpup build, however the `meson` result would absolutely confirm or discredit that hypothesis :thinking:

**Comment by peabee** [comment]
/bin/sh is a symlink to /bin/bash

With the previous version .zip ....
the configure syntax error has gone

but the undefined reference to 'yywrap' has re-appeared and the LEX='flex --noyywrap' addition to the autogen.sh line seems to be ignored - see lines 237-240 & 246-253

[config.log](https://github.com/puppylinux-woof-CE/woof-CE/files/8706395/config.log)

**Comment by dimkr** [comment]
Try to add `libfl-devel` to the `flex` package.

**Comment by peabee** [comment]
Already there:
yes|flex|flex,libfl-devel|exe>dev,dev,doc,nls

**Comment by 01micko** [comment]
What about `sh -x ./autogen.sh`?

edit: I'd almost bet a house that it's a `perl` module missing.


Quote from @woodenshoe-wi 
> It looks like some of the macros aren’t getting expanded properly and it was just a coincidence that the first failure was in my change?

**Comment by peabee** [comment]
With sh -x ./autogen.sh ............
[build-170522.log](https://github.com/puppylinux-woof-CE/woof-CE/files/8708334/build-170522.log)
[config.log](https://github.com/puppylinux-woof-CE/woof-CE/files/8708336/config.log)

Is this significant @ line 44?
```
+ autoconf
configure.ac:28: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

**Comment by dimkr** [comment]
Do you have `m4` in devx?

**Comment by peabee** [comment]
yes|m4|m4|exe>dev,dev,doc,nls

**Comment by woodenshoe-wi** [comment]
Another clue…

I was able to reproduce the error in Fatdog by compiling automake-1.16.5 and installing it to a directory in /tmp

export PATH to use the automake version in /tmp and then trying to run the gtkdialog autogen.sh script.

At first it didn’t make sense why automake would be involved in making the configure script, but in the automake README it says that the “aclocal” program is included with automake.

**Comment by 01micko** [comment]
@woodenshoe-wi that _is_ interesting. 

I have installed `automake-1.16.5` in a slacko 32 install as a test for a jwm automake bug https://github.com/joewing/jwm/issues/565 (and fixed it - but irrelevant of automake version) so I might be able to reproduce too.

---

#### later

EDIT: Emphatic _nope_. That isn't it. Compiled successfully, so _**not**_ a gtkdialog/automake bug.

NOTE: I also upgraded to `autoconf-2.71-noarch-1.txz` (both autoconf and automake = slackware-current) in that installation, which may affect the outcome.

**Comment by peabee** [comment]
This article seems to relate:
Why 'Possibly Undefined Macro' Means Install pkg-config
https://ae1020.github.io/undefined-macro-pkg-config/

Void pkg-config is installed however it installs /usr/bin/pkg-config.pkg-config which is 602KB whereas the ScPup32 /usr/bin/pkg-config is only 45.7KB.............

**Comment by 01micko** [comment]
Have you asked **rockedge** if he can build gtkdialog against gtk2 in his void thingy?

**Comment by dimkr** [comment]
> Void pkg-config is installed however it installs /usr/bin/pkg-config.pkg-config which is 602KB whereas the ScPup32 /usr/bin/pkg-config is only 45.7KB.............

Maybe it uses pkgconf (as opposed to, pkg-config), like Alpine and some other distros.

**Comment by peabee** [comment]
Have changed to:
yes|pkgconfig|pkgconf,libpkgconf,pkgconf-devel|exe>dev,dev,doc,nls
and symlinked pkg-config to pkgconf

but still get:
```
Running autoconf ...
+ autoconf
configure.ac:28: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

```
and then:
```
./configure: line 5321: syntax error near unexpected token 'gtk+-2.0,,'
./configure: line 5321: '  PKG_CHECK_EXISTS(gtk+-2.0,,'
+ exit 1

```
Will PM Erik
[build.log](https://github.com/puppylinux-woof-CE/woof-CE/files/8717975/build.log)

**Comment by woodenshoe-wi** [comment]
I THINK I FOUND IT!!!

Is there a file named `/usr/share/aclocal/pkg.m4.pkg-config` and no file named `pkg.m4`

I booted VoidPup32, copied `pkg.m4.pkg-config` to `pkg.m4` and the gtkdialog configure script completes successfully.

I don’t know what Void is actually using for `pkg.m4`, but apparently it isn’t part of the pkg-config package.

**Comment by peabee** [comment]
WELL DONE YOU!
Many thanks!
How on earth did you work that out?
Will try it out tomorrow (late here now).
Cheers!

**Comment by peabee** [comment]
Excellent - many thanks everybody especially @woodenshoe-wi .....
A simple symlink fixes.
Cheers!
Peter

**Comment by peabee** [comment]
Oh fiddle-sticks!!!!

The petbuild completes successfully but the gtkdialog-0.8.5 binary segfaults:
[   63.583637] gtkdialog[8114]: segfault at 55f80 ip 0050d090 sp bf8df99c error 4 in gtkdialog[4e2000+2c000]
[   63.583651] Code: ff e9 72 ff ff ff 8d 74 26 00 65 8b 0d 00 00 00 00 f7 d8 8b 15 80 5f 05 00 89 04 11 b8 ff ff ff ff eb a2 66 90 66 90 66 90 90 <a1> 80 5f 05 00 65 8b 15 00 00 00 00 01 d0 c3 90 83 ec 0c 89 5c 24

I've made a .pet ..... (remove false .gz)
[gtkdialog-8382197116dbc7b233fa86c68baf2df8.pet.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/8727521/gtkdialog-8382197116dbc7b233fa86c68baf2df8.pet.gz)

**Comment by peabee** [comment]
FWIW.....
The VoidPup64 gtkdialog petbuilds both builds and runs without segfaulting:
```
# uname -a
Linux puppypc16580 5.15.37 #1 SMP Mon May 9 05:56:47 UTC 2022 x86_64 GNU/Linux
# gtkdialog --version
gtkdialog version 0.8.5 release (C) 2003-2007 Laszlo Pere, 2011-2012 Thunor
Built with support for: GTK+ 2, Glade.
# busybox --help
BusyBox v1.35.0 (2022-05-19 19:00:58 +08) multi-call binary.

```

**Comment by woodenshoe-wi** [comment]
> How on earth did you work that out?

I thought that maybe there had been a syntax change in the newer version of autoconf, and when I searched the autoconf documentation for the PKG_CHECK_EXISTS macro I realized it wasn’t part of autoconf.

I had been able to reproduce the same error messages in Fatdog by installing automake-1.16.5 in a directory in /tmp (which would start with an empty aclocal directory) but 01micko couldn’t.

**Comment by 01micko** [comment]
```
CFLAGS=' -fPIC' LDFLAGS=' -no-pie' ./autogen.sh --prefix=/usr --bindir=/usr/sbin
```

**Comment by woodenshoe-wi** [comment]
@peabee I did notice another issue with VoidPup32 just now.

Trying to run the debugger `gdb`, it complains about missing libpython3.10.so.1.0

**Comment by 01micko** [comment]
> ```
> CFLAGS=' -fPIC' LDFLAGS=' -no-pie' ./autogen.sh --prefix=/usr --bindir=/usr/sbin
> ```

That was a quick compile on vpup32 

More correctly, if using in a petbuild

```
 CFLAGS="$CFLAGS -fPIC" LDFLAGS="$LDFLAGS -no-pie" ./autogen.sh --prefix=/usr --bindir=/usr/sbin
```

(edit: change `'` to `"`)

**Comment by peabee** [comment]
deleted

**Comment by dimkr** [comment]
Try to build with `CFLAGS="-O0 -g"`, then `echo /tmp/core > /proc/sys/kernel/core_pattern`, `ulimit -c unlimited`, and run the script that runs the crashing gtkdialog via the terminal where you ran `ulimit`.

Then, run `gdb /usr/bin/gtkdialog /tmp/core`: `bt` will tell you where and why gtkdialog crashed.

**Comment by 01micko** [comment]
That log @peabee isn't any good, we need one from the `./xlog ./3builddistro` as there was no compilation _at all_, probably no `make clean`.

**Comment by 01micko** [comment]
_It really would help_, if you're going to pursue void pup, to merge into woof-ce your necessary changes.

**Comment by peabee** [comment]
Problem solved - my apologies it was something in my build environment that was causing the pie binaries - by going to a new clean build environment the problem has "gone away".

@01micko I understand your request but there are significant problems involved as documented above: https://github.com/puppylinux-woof-CE/woof-CE/issues/3086#issuecomment-1127459174
which I don't know how to solve!

**Comment by 01micko** [comment]
@peabee just upload your hacks somewhere public (even just zip your clean `woof-out_x86_x86_void` or whatever you have) so at least we can see what is going on, and maybe then we can guide you on how to merge.

**Comment by peabee** [comment]
> just upload your hacks somewhere public

https://u.pcloud.link/publink/show?code=XZ4mrHVZy8x61oW8hM4bvrDiNJ34ou4QWoIy

**Comment by 01micko** [comment]
Thanks. I'll take a look on the week end. Cheers!

**Comment by peabee** [comment]
I guess this fell into the "too difficult and not important enough" category.............

**Comment by 01micko** [comment]
Um, `real life` ..
