### ISSUE TITLE
Missing entries in puppylinux.com

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#3160]
Some new Puppy users think the most up-to-date Puppy is 9.5, because puppylinux.com doesn't mention new stuff like VoidPup and Vanilla Dpup.

**Comment by bigpup1** [comment]
To get it listed as an official Puppy version.
Whoever produces it has to do this:

Q: What is an official Puppy Linux distribution?
A: It must meet two conditions. 1) It must be built using Woof-CE and its build “recipe” should be in woof-distro. 2) It must be endorsed as “official” by the Puppy Master.

**Comment by bigpup1** [comment]
Not everything on the Puppy Linux forum is is a Puppy Linux operating system.
Most do have Puppy like ways of doing stuff, but also have their own ways, that do not follow the official Puppy  procedures.

From puppylinux.com FAQ:

About other Puppy Linux-like distributions
    Q: Is DebianDog considered as Puppy Linux?
    A: No. The maintainer itself has said so. Further more it is not built from Woof-CE. But it seeks to emulate most if not all of Puppy Linux features and behaviours; that if you are familiar with Puppy you would be right at home about it.

    Q: If DebianDog is not Puppy, why do you support them, or even mention them here?
    A: DebianDog is considerd as a member of Puppy Linux family of operating systems.

    Q: Is Quirky Linux considered as Puppy Linux? It is also made by Barry.
    A: No, Barry himself has stated multiple times that Quirky is not Puppy. Just like DebianDog, Quirky is a member of Puppy Linux family.

    Q: Is Fatdog64 considered as Puppy Linux?
    A: No. It was originally forked from Puppy Linux 4.0, but it has since took a different path (of doing the same thing). Like DebianDog and Quirky, however, it is considered as part of Puppy Linux family.

**Comment by dimkr** [comment]
> 1) It must be built using Woof-CE and its build “recipe” should be in woof-distro.

The BionicPup and FossaPup recipes (and those of pretty much all their predecessors) are not included in woof-CE, only something similar. And they were built from modified woof-CE trees, which are not publicly available.

Slacko and Vanilla Dpup are the only examples that truly satisfy requirement (1), as far as I know, and most entries in puppylinux.com violate at least one of the so-called requirements.

**Comment by bigpup1** [comment]
Seems 01micko needs to figure this out.
He is suppose to be the Puppy Master and have control of this stuff.

**Comment by 01micko** [comment]
@bigpup1 I don't need to figure out anything. Anyone can approach me or anyone else who has write access here and can call there pup "official". _Anyone_  can issue a PR at https://github.com/puppylinux-woof-CE/puppylinux-woof-CE.github.io for consideration.

Link this response, quote it whatever. Just don't piss me off by saying what I "suppose" (your words). :angry:

**Comment by dimkr** [comment]
> @bigpup1 I don't need to figure out anything. Anyone can approach me or anyone else who has write access here and can call there pup "official". _Anyone_ can issue a PR at https://github.com/puppylinux-woof-CE/puppylinux-woof-CE.github.io for consideration.

I didn't know it was a repo, will open a PR 😮

**Comment by bigpup1** [comment]
This info for how to submit a Puppy version for listing it on puppylinux.com is now on the Puppy forum.
I posted an announcement about it.
https://forum.puppylinux.com/viewtopic.php?t=6247

Shouldn't this info be provided in the puppylinux.com FAQ.
Maybe here:

> Q: What is an official Puppy Linux distribution?
> A: It must meet two conditions. 1) It must be built using Woof-CE and its build “recipe” should be in [woof-distro](https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-distro). 2) It must be endorsed as “official” by the Puppy Master.

**Comment by peabee** [comment]
@01micko @dimkr 

We seem to have sprouted another category "Unofficial" - what does that mean????

Aren't all builds that are not "official" the same? and listed on downloads.html........ 

only 'offficial' should be on index.html .........??

**Comment by dimkr** [comment]
> Aren't all builds that are not "official" the same? and listed on downloads.html........

Most builds in the "official" category (basically, everything except Slacko) are built with a modified woof-CE that was never published, and the "recipe" to build them isn't part of woof-CE. This is a violation of the rules in the FAQ, and a GPL violation of the worst kind. Some of these violators even ask for donations, and that infuriates me: that's almost the same as selling stolen code written by others.

> We seem to have sprouted another category "Unofficial" - what does that mean????

I don't want to be associated with this kind of behavior and software development malpractice, and I'm willing to accept the consequences of losing potential users because of the "unofficial" designation.

> only 'offficial' should be on index.html .........??

If the FAQ is correct and the answer to this question is positive, then FossaPup64 9.5 and VoidPup shouldn't be there.

---

Anyway, I'm closing this issue, because it's solved now. This discussion belongs in https://github.com/puppylinux-woof-CE/puppylinux-woof-CE.github.io/issues.

**Comment by peabee** [comment]
VoidPup is NOT on index.html for exactly that reason.........

Have you looked at download.html??

**Comment by peabee** [comment]
There is another requirement to be "official":

> All the “official” Puppies since version 2 are hosted at Ibiblio.
