### ISSUE TITLE
timebar doesn't work with some time zones

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#3161]
/usr/lib/gtkdialog/svg_analogclock is definitely buggy:

```
MYGMT="`readlink /etc/localtime | cut -d/ -f6 | sed -e 's,^GMT-,GMTx,' -e 's,^GMT+,GMT-,' -e 's,^GMTx,GMT+,'`"
MYTIME="`echo "$MYGMT" | cut -c4- | sed -e 's,-,x,' -e 's,+,-,' -e 's,x,+,'`" #swap it for calculation
```

Some time zones have less than 6 path elements (for example, /usr/share/zoneinfo/Universal) and some don't start with "GMT". I'm not fixing this (or anything JWM-related that's not critical), at least until somebody complains.

**Comment by 01micko** [comment]
Can be fixed for screen pos too on wayland. And some gtk3 transparency would be nice :rofl: 


![20220620_20h46m20s_grim](https://user-images.githubusercontent.com/1019119/174585808-e7a69dfb-8346-4ceb-8ea7-e15a459db70c.png)

**Comment by dimkr** [comment]
> Can be fixed for screen pos too on wayland. And some gtk3 transparency would be nice

Enough with the sfwbar teasers already, give us a petbuild :p

**Comment by 01micko** [comment]
Ok, try this weekend. Had not enough time to scratch myself recently.

**Comment by dimkr** [comment]
> Ok, try this weekend. Had not enough time to scratch myself recently.

That's OK, not trying to push. This adventure with cutting-edge tech is supposed to be fun :)

I hope to complete #3156 (by removing the hardcoded interface name) and implement Alt-Tab in dwl soon, so the dwl-based desktop is imperfect and incomplete but usable even if sfwbar needs more time.

**Comment by sofijacom** [comment]
You can add the backlight of the number of the day
![0](https://user-images.githubusercontent.com/107557749/174626557-4328f415-f911-44d7-ae72-f8b6c8e4f901.png)

**Comment by 01micko** [comment]
While I'm here #3477 (I'm several weekends late!)

![timebar](https://user-images.githubusercontent.com/1019119/194752223-187a0e55-e791-4adc-b6e0-3c10c87318ef.png)
