### ISSUE TITLE
Missing file-systems in WoofCE PUPs

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#3200]
This is posted for developer consideration: USB technology has been with us for decades and for the last decade there are 2 filesystem formats that bring advantage to USB use and longevity; namely F2FS and ExFAT.

Are we at a point where these should be **built-in** to todays distros from WoofCE?

**FYI**

**Comment by Phoenix-Starlight** [comment]
exFAT can be supported by the kernel 5.7+ and tools exists if its not kernel-space. F2FS is primarily used on mobile devices, and again tools exist if you want to access these. FAT32 is still used on many many USBs because its simple, and works on all systems.

I would think no except for exFAT (for speed instead of having to use FUSE), and that is my opinion.

**Comment by dimkr** [comment]
I don't see a use case for exFAT really. ext4 without journaling is a much better choice, in many ways, and dual-booters can always install a Windows ext4 driver if they really want mount a Puppy partition from Windows.

Regarding F2FS, I don't understand what you mean by "USB technology": are you talking about flash drives, SD cards, SSDs, NVMe SSDs or what? They're not the same, and I'm not a big fan of the idea of making technical decisions based on buzzwords and vague generalizations. F2FS is not a "one size fits all" solution, and I'm not even sure what problem it is that you're trying to solve by switching to F2FS. In addition, F2FS has some limitations compared to ext4, and some boot loaders don't support it equally well.

(And, if we're talking about durability or reliability, PUPMODE 13 has issues like #3187, #3183 and #3115, and they affect any file system. I don't know, and I believe nobody here knows, if F2FS does have a significant real-world advantage over ext4 under PUPMODE 13.)

**Comment by CollaboratorGCM** [comment]
ExFAT comes on some/many/most external USBs, SSDs & SDcards from the manufacturers
and purchased items.
F2FS is SAMSUNGs way for extending the life of external stores and their
extension intends to reduce data loss over time on the units.

I hope you evaluate with users and use of externals in mind. This is one of
those straight-away files-systems that has little impact on system size
with no security impact in its data use on modern devices. Data integrity on these externals is one idea of why manufacturers ship these file systems.

Should users with new externals be perplesed when the PUPs do not open the filesystem to the desktop, as things are today? Or should one/some of these be included, OOTB to facilitate opening and data use?

Just another thought as you evaluate the user and use benefits.

**Comment by CollaboratorGCM** [comment]
Just a thought. If you feel it beneficial it will surface in WoofCE distros.

**Comment by dimkr** [comment]
Thoughts are nice, but someone needs to check if F2FS actually extends the lifespan of SSDs, NVMe SSDs, flash drives, etc', in Puppy's particular use case, under both PUPMODE 12 and 13. All these kinds of devices are different and Puppy is not Android.

**Comment by CollaboratorGCM** [comment]
Are you concerned with "internal' device use as a permanent part of the PC or the external insertion devices (removables) that I 'think' the 2 mentioned files-system were intended for modern use? I am looking at what users see in the WoofCE generations for public use when a new removable is inserted. To eliminate a user need to run about, would we serve them best if it was included along with the shipped ones; this looking forward as manufacturers continue their directions.

There is certainly a case to be made beyond removables.

Again, if it does NOT impact a systems apps, or system operations and dos not bring a capacity issue, one or the others of these could be a productivity element for all users. Today, for example, One can Gparted format a partition as such, but, cannot open it in the file managers.

Thoughts?

**Comment by CollaboratorGCM** [comment]
There are bigger fish to fry, I know. so, taking any more time to consider than already, might not be a good development direction. But, some might think it being present because the removable manufacturing community has changed, with this element in the shipped PUPs being overlooked.

Its minor.

**Comment by Phoenix-Starlight** [comment]
You can only format it with gparted if you have the right tools installed to point out, which is not installed by default on puppy.

**Comment by dimkr** [comment]
> Again, if it does NOT impact a systems apps, or system operations and dos not bring a capacity issue, one or the others of these could be a productivity element for all users.

This needs to be tested, you can't just assume F2FS reduces writes in Puppy's use case, which is very different from the use cases in an Android phone.

> Today, for example, One can Gparted format a partition as such, but, cannot open it in the file managers.

Under which Puppy?

**Comment by CollaboratorGCM** [comment]
@DIMKR, i AM NOT SURE WHAT YOU ARE GETTING AT?

If its F2FS and doesn't provide favorable results, then dont add. 
If its ExFAT, same, then dont add. 
If its the fact that I suggested this for consideration, that is a different issue. 

I could argue  a test case,, but the facts are the PROfessional reviewers have already done so, so my input is not one "I" would consider the best judge.

This was offered for consideration to the WoofCE team to determine if it offers a productivity gain while not impacting the system packaging.The environmentals have changed over the years and I felt it time to ask for consideration.

If there is merit, I am sure the 'team' will add. If the feeling is otherwise, it will not. **Again**, this a consideration of productivity...not to fix something.

No answer to this is requested. If its troublesome, close it. Thanks for listening.

**Comment by Phoenix-Starlight** [comment]
Most flash storages (besides the really cheap one which shouldn't be
expected to last very long under heavy load) have systems in place
that already do what F2FS does. As well at best, it is as good as
ext4, and at worse it does worse than ext4's worst case. F2FS has no
UUID support in GParted, cannot be shrunk at all, and cannot be labeled. (This means no GRUB specific drive
selection via UUID)

EDIT: It appears there is a issue with f2fs in that if you choose to downgrade your kernel you'll be also unable to read F2FS either if you created it with a newer kernel.

**Comment by dimkr** [comment]
> @dimkr, i AM NOT SURE WHAT YOU ARE GETTING AT?

This proposal is based on a Samsung marketing blurb which probably talks about F2FS in Android phones, and not on real-world testing with Puppy. Somebody needs to do this work.

> This was offered for consideration to the WoofCE team
> If there is merit, I am sure the 'team' will add. 

You need to understand that this "team" your talking about doesn't exist, and it takes time to seriously evaluate proposals like this. You're talking about some abstract "manufacturing community", "productivity", etc', but Puppy is made by real people. Puppy doesn't just happen, it's made by people willing to do the work: proposals are nice, but proposals without an "owner" who implements them are nothing but a distraction.

Long time ago, Barry something that's still true: Puppy is a doocracy. If **you** don't put in the work to see if F2FS actually brings real-world improvement to Puppy, then add that F2FS support to woof-CE **yourself**, this won't happen.

**Comment by mavrothal** [comment]
Is not clear to me why the issue is still open?
exFAT and F2FS are supported in the newer puppy kernels, actually as builtins.
If the userspace programs for exfat and f2fs are not included by the puppy builder, the user can easily install for the repo. So there s really no issue accessing and using these devices.
If the issue is for exfat or f2fs to be the default USB formatting option when puppy installs in a USB, given the accessibility of these FSs as mentioned above, everybody can implemented to test any advantages or disadvantages. With the data at hand (s)he can then open a more meaningful issue that a developer might then take on.
