### ISSUE TITLE
dwl fails to start in 3 VMs

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#3271]
I tried upup 22.04.61 in 3 different VMs (VirtualBox, VMware fusion and Parallels Desktop) and dwl failed to start in all of them.
Any hints so I can get take it for a spin (other than QEMU)?
Thx

**Comment by dimkr** [comment]
@mavrothal Try a different virtual GPU. If I remember correctly, Wayland works under VirtualBox only if you select one of the 3 options.

**Comment by mavrothal** [comment]
>  If I remember correctly, Wayland works under VirtualBox only if you select one of the 3 options.

Indeed under the VMSVGA controller with 3D Acceleration enabled I get to the the Wayland Desktop. 
No mouse thought. :(

**Comment by dimkr** [comment]
> Indeed under the VMSVGA controller with 3D Acceleration enabled I get to the the Wayland Desktop.

Yes, it's a known issue in Sway and other wlroots-based compositors. `export WLR_NO_HARDWARE_CURSORS=1` in ~/.dwlrc should work around this issue.

**Comment by mavrothal** [comment]
That did it
THX
