### ISSUE TITLE
sfs_load handling of symlinks is wrong

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3320]
#3027 from @rizalmart introduced checks on symlinks when loading sfs

For VoidPup64:
/lib and /usr/lib are real directories
/lib64 and /usr/lib64 are symlinks

The devx for VoidPup64 only contains real directories /lib & /usr/lib but fails to load (erroneously) due the checks in sfs_load

sfs_load should only fail if the sfs contains real directories which are going to overwrite symlinks

Maybe @dimkr can have a look?

**Comment by dimkr** [comment]
That change in sfs_load is incompatible with VoidPup, that's all I can say. The only solution I see is removing all protections of this kind, because VoidPup is incompatible with both USR_SYMLINKS=yes and USR_SYMLINKS=no.

**Comment by peabee** [comment]
The sfs_load logic appears to be wrong to me.........

At line 52 the checks are initiated if any of a list of symlinks is present in the running system however the symlink that has triggered the check is not remembered.

Then at line 65 the contents of the sfs are checked to see if any of the same list of objects is both a directory and not a symlink inside the sfs.

There is no logical connection between the 2 tests.

In the VoidPup64 devx case the first test is triggered by the presence of the /lib64 symlink whereas the 2nd test  is triggered by the /lib directory inside the devx.

The VoidPup64 devx sfs is correctly configured and can be safely installed but the erroneous sfs_load logic is stopping it being loaded.

**Comment by peabee** [comment]
I propose a change lines 52-83:
```
sym_list=""
for fld2 in bin sbin lib lib64 lib32 libx32
do
  [ -L /$fld2 ] && sym_list="$sym_list $fld2"
done

if [ "$sym_list" != "" ]; then

 if [ "$1" ]; then
 
   SFSFILE="$(basename "$1")"
   MNTFLD="$(echo "${SFSFILE}-module" | sed -e 's#\ #_#g')"
   mkdir -p /mnt/"$MNTFLD"
   DEVLOOP="$(losetup -f)"
   losetup "$DEVLOOP" "$1"
   mount -r -t squashfs -o loop,ro "$DEVLOOP" /mnt/$MNTFLD
  
   FLD_INVALID=""
  
    for fld2 in $sym_list
    do
    if [ -d /mnt/$MNTFLD/$fld2 -a ! -L /mnt/$MNTFLD/$fld2 ]; then
      FLD_INVALID="$fld2"
      break
     fi
    done
    
    umount /mnt/$MNTFLD
    rm -rf /mnt/$MNTFLD
       
    if [ "$FLD_INVALID" != "" ]; then
      /usr/lib/gtkdialog/box_yesno "sfs_load" warning "$(gettext "The directory $FLD_INVALID in this sfs will overwrite the system symlink. This may cause problems. Do you want to continue?")"
      [ $? == 1 ] && exit 1
    fi
 
 fi
 
fi 

```

**Comment by dimkr** [comment]
As far as I see, the problem is `-d /mnt/$MNTFLD/$fld2 -a ! -L /mnt/$MNTFLD/$fld2`. The logic is broken, because the right part (`-a ! -L /mnt/$MNTFLD/$fld2`) of this expression is true when the directory doesn't exist.

For example, if you have a /lib64 symlink but the SFS doesn't contain /lib64, `-d /mnt/$MNTFLD/$fld2` is true (because /lib64 is dereferenced and leads to a directory) and `! -L /mnt/$MNTFLD/$fld2` is also true (because a non-existing file is not a symlink).

How about this super minimal fix?

```
    for fld2 in bin sbin lib lib64 lib32 libx32 usr/bin usr/sbin usr/lib usr/lib64 usr/lib32 usr/libx32
    do
      t1=`stat -c %F /$fld2 2>/dev/null`
      t2=`stat -c %F /mnt/$MNTFLD/$fld2 2>/dev/null`
      if [ -n "$t1" -a -n "$t2" -a "$t1" != "$t2" ]; then
        FLD_INVALID="y"
        break
      fi
    done
```

SFS a is compatible with SFS b if for every directory x, a/x and b/x have the same type, a/x doesn't exist or b/x doesn't exist (assuming non-existnece is the the only reason why `stat` would fail).

**Comment by peabee** [comment]
But its an "and" -a
Will comment further on #3323

**Comment by dimkr** [comment]
> But its an "and" -a

So what? This condition is still broken.

```
/tmp$ mkdir x
/tmp$ rm y
rm: cannot remove 'y': No such file or directory
/tmp$ [ -d x -a ! -L y ] && echo bug
bug
```

**Comment by peabee** [comment]
The test is not on x & y - its only x & x where x has been determined already to be a system symlink
