### ISSUE TITLE
The quicksetup locale combobox is broken under Wayland

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#3322]
![a](https://user-images.githubusercontent.com/1471149/183827134-3c59bd9f-5294-4e4b-82e0-27602e803cdc.png)

When clicked:

![b](https://user-images.githubusercontent.com/1471149/183827142-07a3d983-74ca-44ad-b471-33dfbb5fb86b.png)

**Comment by 01micko** [comment]
It's been working fine for quite a while in `labwc` since they've been chasing `wlroots` git.

**Comment by dimkr** [comment]
> It's been working fine for quite a while in `labwc` since they've been chasing `wlroots` git.

That's great! This issue will need to wait until wlroots 0.16.0 is out and pushed to Debian testing.

I'll see if I can change the dwl petbuild so it links statically against wlroots master and aligns with dwl's wlroots-next branch. The sooner I deal with the breaking changes in 0.16.0, the better.
