### ISSUE TITLE
where is the vanilladpup 10.x discussion

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#3342]
@dimkr  I noticed that dpup-10.x moved to vanilla-dpup/unstable, and there the "issues" button has been removed (or not activated). Is that intentional? should discussion/issues move elsewhere? (where?)

BTW the dkms infrastructure is an 200+ MB sfs (xz compressed) and adding build-essential approaches 300MB. However, they'll occupy ~700MB on your savefile (if you use a FAT stick). So a devx or at least a dkms sfs included in the extra.tar, would be handy.

**Comment by dimkr** [comment]
@mavrothal It's intentional. It's built using the vanilla woof-CE, so issues should be reported and fixed here.
