### ISSUE TITLE
Search in  a folder  with  dollar sign in  folder name

### ISSUE THREAD

**Issue by don570** [puppylinux-woof-CE/woof-CE#3357]
I couldn't use  pfind when  there  was dollar sign in  foldername
i.e.  there is a dollar  sign  in variable  SEARCHPATH

I found satisfactory  work-around for  this special  case...

After line 86  in  func file  of  pfilesearch 
I inserted

		
        #---
		
         # special  case  when  Dollar sign  is  in  foldername 
   		if  echo  "$SEARCHPATH" |  grep -q  \\$ ; then 

        VAR="`cat  $WORKDIR/pfilesearch-execfind `" 
     	echo -n  "${VAR//\"/\'}" > $WORKDIR/pfilesearch-execfind #default find		
        fi

**Comment by zigbert** [comment]
fixed in
https://github.com/puppylinux-woof-CE/woof-CE/commit/53fbc0bf40f7e8a7b1426117234a86913c4a41b6
https://github.com/puppylinux-woof-CE/woof-CE/commit/16a4aef457c939de3849fb4141232563040e035b
