### ISSUE TITLE
slackware-15 too old already for wlroots/wayland

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#3372]
I've been developing labwc/sfwbar for a while now and the current 'stable' labwc/wlroots is way too buggy for a prime time puppy release, #3030 #3322 notably . The latest and greatest base is needed and in the case of slackware that is -current.

I'm typing on it now 
- slacware64-current base
- labwc (recent commit - cetainly not latest, however latest is getting very good)
- sfwbar from about a month ago - it had improved in leaps since then too
- petbuilds for both of the above plus using more slackware base packages and using petbuilds for mpv/celluloid - which uses gtk4! Of course there is some theming issues, not too serious.

Everything pretty much works! Sound crashes on GUI restart - I know the cause. Most videos play, can view images (except mtpaint isn't working) , pMusic works (slackware native ffmpeg). It's actually pleasing that this is the first boot! Haven't saved session yet (usb install).

Hopefully I can offer PRs next wekend.

![20220904_19h39m50s_grim](https://user-images.githubusercontent.com/1019119/188307336-0648b0fb-5747-425b-b006-d173a2aa5e83.png)

**Comment by dimkr** [comment]
Even before labwc support in woof-CE is in perfect shape, a slackware64-current configuration would be nice to have, so we can track future issues like new wlroots versions (same rationale as having weekly builds of sid64) 👍🏿

**Comment by 01micko** [comment]
> Even before labwc support in woof-CE is in perfect shape, a slackware64-current configuration would be nice to have, so we can track future issues like new wlroots versions (same rationale as having weekly builds of sid64) 👍🏿

..and just rebooted and restored this session :smiley_cat: 

Absolutely. `-current` is where the action is and I _should_ setup a `wslacko` repo to track breaking changes. 

Time is my enemy however (like most of us :roll_eyes: )

**Comment by dimkr** [comment]
> Time is my enemy however (like most of us 🙄 )

I can help with that. Maybe copying slackware64/15.0 to slackware64/current and adding it to the weekly rotation is a good first step.

**Comment by 01micko** [comment]
> I can help with that. Maybe copying slackware64/15.0 to slackware64/current and adding it to the weekly rotation is a good first step.

Maybe. Some stuff is quite broken though. For example, 
- claws-mail petbuild completely fails
- lots of legacy stuff in the `PKGS_SPECS_TABLE`
- there is _no_ dependency resolution in `-current` - maybe flatpack support would be a good idea?
The thing I'm running now isn't that broken at all, quite usable - surprised me. However I did run into some dependency hell - such as gstreamer - down the line it depends on NetworkManager! I made package templates to remove bloat but the resulting iso is still huge - ~600MB! ffmpeg depends on samba, and samba actually works.

**Comment by 01micko** [comment]
Progress:
- fixed claws-mail - well not really, just disabled the perl plugin and works
- made 'office' petbuild - goffice, gnumeric, abiword - works!
- had to enable stuff in mtpaint - works now
- need to update the icon sets, firefox exposes it's `app_id` as firefox-default - breaking the icon in wayland

**Comment by 01micko** [comment]
Added
- evince (dep `libhandy`)

Still need to fine tune some of these petbuilds

**Comment by 01micko** [comment]
The `-current` wayland build is now 548MB xz compressed with all of the above. Testing shortly.

**Comment by 01micko** [comment]
_Almost_ in a usable state! :sweat_smile: 


https://user-images.githubusercontent.com/1019119/189509943-dcdadf37-3155-4549-baf8-b827a43bb29d.mp4

**Comment by 01micko** [comment]
The above video and post was made on a 2012 mackbook. Everything pretty much works.

**Comment by dimkr** [comment]
> _Almost_ in a usable state! sweat_smile
> 
>  recording.mp4

Super cool stuff!

**Comment by zigbert** [comment]
You are both incredible! Puppy has always been a conservative choice - not anymore.

Are you running the GTK3 version of pMusic or the one in woofCE?

**Comment by 01micko** [comment]
I've been using the gtk3 version of pmusic in my devel environment. It mostly works fine. Great job! The above developments are pure woof so the gtk2 version is included, and works, but in a _pure_ wayland environment it won't work as all X only applications don't. The curent focus is on wayland _with_ Xwayland - an X server for wayland.

![20220914_21h18m43s_grim](https://user-images.githubusercontent.com/1019119/190140666-c63d2e44-af55-4af8-9793-04129f6ff20d.png)

**Comment by dimkr** [comment]
Xwayland works very well in my bookworm64 development builds with dwl - even "big" applications like GIMP work fine.

**Comment by zigbert** [comment]
That's great to hear.
I'll keep the development of pMusic outside woofCE until I have solved the major issues...  First of all the drag'n'drop inside the playqueue.

**Comment by 01micko** [comment]
@zigbert it seems only the old method works for gtk3 -Im not sure why.

 - https://wikka.puppylinux.com/gtkdialogDocTips9.7

EDIT: old solution in practical use:

https://user-images.githubusercontent.com/1019119/190877561-607fe04f-d091-46c0-a479-7609adbba7e5.mp4

**Comment by zigbert** [comment]
@01micko Yepp, the old solution works... though, not as sophisticated as the GTK2 way.

We might end up with this one.

Thank you for your reminder
