### ISSUE TITLE
New version of grep produces warnings

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3379]
grep-3.8-i586-1.txz from Slackware Current

During build:
```
# chroot rootfs-complete/
grep: warning: stray \ before -
grep: warning: stray \ before -
grep: warning: stray \ before -

```
In running system when either LxTerminal or URXVT start:
![Screenshot1](https://user-images.githubusercontent.com/5926865/188848423-0008e2f8-ed65-4f4a-8ac2-74b5670e432b.png)

![Screenshot2](https://user-images.githubusercontent.com/5926865/188848470-920d5b48-8cd6-4411-9951-8d012ff2eeea.png)

**Comment by dimkr** [comment]
Try this:

```
set -x
. /etc/profile
```

At some point you'll probably see that `grep` command-line.

**Comment by peabee** [comment]
Seems that /etc/profile.d/gtkdialog is the cuprit:
```
if ldd $(which gtkdialog) | grep -iq 'gtk\-3' ; then #gtk3
	GTKDIALOG_BUILD=GTK3
elif ldd $(which gtkdialog) | grep -iq 'gtk\-X11\-2' ; then #gtk2
	GTKDIALOG_BUILD=GTK2
fi

```

```
++ . /etc/profile.d/gtkdialog
+++ grep -iq 'gtk\-3'
++++ which gtkdialog
+++ ldd /usr/sbin/gtkdialog
grep: warning: stray \ before -
+++ grep -iq 'gtk\-X11\-2'
++++ which gtkdialog
+++ ldd /usr/sbin/gtkdialog
grep: warning: stray \ before -
grep: warning: stray \ before -
+++ GTKDIALOG_BUILD=GTK2

```

**Comment by dimkr** [comment]
`grep -Fiq 'gtk-X11-2'`

**Comment by peabee** [comment]
Thanks

**Comment by peabee** [comment]
0setup line 67 also needs fixing 2 occurrences
1download line 19 also needs fixing 2 occurrences

**Comment by peabee** [comment]
A search of woof-code for \\- produces this list:
/woof-code/_00func
/woof-code/0setup
/woof-code/1download
/woof-code/packages-templates/pulseaudio_FIXUPHACK
/woof-code/packages-templates/xorg_base_new/FIXUPHACK
/woof-code/rootfs-packages/backend_modprobe/sbin/pup_event_backend_modprobe
/woof-code/rootfs-packages/change_kernels/usr/sbin/change_kernels
/woof-code/rootfs-packages/check_deps_gui/usr/local/petget/check_deps_gui.sh
/woof-code/rootfs-packages/firewall_ng/usr/sbin/firewall_ng
/woof-code/rootfs-packages/frisbee/etc/init.d/frisbee.sh
/woof-code/rootfs-packages/imageview/usr/sbin/imgview
/woof-code/rootfs-packages/pburn/usr/local/pburn/func
/woof-code/rootfs-packages/pdiag/usr/lib/pdiag/pdiag-network
/woof-code/rootfs-packages/ptheme/usr/sbin/fixPuppyPin
/woof-code/rootfs-packages/pupdial/usr/local/pupdial/pupdial
/woof-code/rootfs-petbuilds/netmon_wce/netmon_wce-3.3/netmon_wce.petbuild
/woof-code/rootfs-skeleton/bin/mount-pup
/woof-code/rootfs-skeleton/etc/profile.d/gtkdialog
/woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit
/woof-code/rootfs-skeleton/lib/keymaps/br-abnt.gz
/woof-code/rootfs-skeleton/usr/bin/dir2pet
/woof-code/rootfs-skeleton/usr/bin/new2dir
/woof-code/rootfs-skeleton/usr/bin/petspec
/woof-code/rootfs-skeleton/usr/bin/pextract
/woof-code/rootfs-skeleton/usr/bin/xterm
/woof-code/rootfs-skeleton/usr/lib/gtkdialog/box_splash
/woof-code/rootfs-skeleton/usr/local/petget/check_deps.sh
/woof-code/rootfs-skeleton/usr/local/petget/configure.sh
/woof-code/rootfs-skeleton/usr/local/petget/dependencies.sh
/woof-code/rootfs-skeleton/usr/local/petget/downloadpkgs.sh
/woof-code/rootfs-skeleton/usr/local/petget/filterpkgs.sh
/woof-code/rootfs-skeleton/usr/local/petget/findmissingpkgs.sh
/woof-code/rootfs-skeleton/usr/local/petget/findnames.sh
/woof-code/rootfs-skeleton/usr/local/petget/installed_size_preview.sh
/woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh
/woof-code/rootfs-skeleton/usr/local/petget/installpreview.sh
/woof-code/rootfs-skeleton/usr/local/petget/petget
/woof-code/rootfs-skeleton/usr/local/petget/pkg_chooser.sh
/woof-code/rootfs-skeleton/usr/local/petget/postfilterpkgs.sh
/woof-code/rootfs-skeleton/usr/local/petget/removepreview.sh
/woof-code/rootfs-skeleton/usr/sbin/bootmanager
/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs
/woof-code/rootfs-skeleton/usr/sbin/filemnt
/woof-code/rootfs-skeleton/usr/sbin/fixPuppyPin
/woof-code/rootfs-skeleton/usr/sbin/latest_microcode.sh
/woof-code/rootfs-skeleton/usr/sbin/pdict
/woof-code/rootfs-skeleton/usr/sbin/pupcamera
/woof-code/rootfs-skeleton/usr/sbin/quicksetup
/woof-code/rootfs-skeleton/usr/sbin/report-video
/woof-code/rootfs-skeleton/usr/sbin/savesession-dvd
/woof-code/rootfs-skeleton/usr/sbin/sfs_load
/woof-code/rootfs-skeleton/usr/sbin/shutdownconfig
/woof-code/rootfs-skeleton/usr/sbin/wmonitors.sh
/woof-code/rootfs-skeleton/usr/share/audio/goodluck.m4a
/woof-code/rootfs-skeleton/usr/share/boot-dialog/slacko.png
/woof-code/support/findpkgs
/woof-code/support/huge_kernel.sh

**Comment by peabee** [comment]
Fixed by #3397

**Comment by peabee** [comment]
Another occurrence:

mount - #3510 & https://forum.puppylinux.com/viewtopic.php?p=69822#p69822

**Comment by peabee** [comment]
#3524 refers
