### ISSUE TITLE
pfilesearch fix written

### ISSUE THREAD

**Issue by don570** [puppylinux-woof-CE/woof-CE#3381]
There is excellent  new  version  of  pfilesearch available.
Written by puppy forum  member Burunduk  
http://forum.puppylinux.com/viewtopic.php?p=65890&sid=1e20dcab5384d8d851be9e38500253fc#p6589
`http://forum.puppylinux.com/download/file.php?id=10758&sid=07247b600e7df36b431e7db2249c6b1d`
 pfilesearch-2.3-maybe-fix
It solves all my  problems.
[func.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/9521967/func.txt)

**Comment by zigbert** [comment]
fixed in
https://github.com/puppylinux-woof-CE/woof-CE/commit/53fbc0bf40f7e8a7b1426117234a86913c4a41b6
https://github.com/puppylinux-woof-CE/woof-CE/commit/16a4aef457c939de3849fb4141232563040e035b
