### ISSUE TITLE
system builds are failing

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3424]
https://github.com/puppylinux-woof-CE/woof-CE/actions

**Comment by dimkr** [comment]
The directory layout of https://github.com/thesofproject/sof-bin has changed again, should be an easy fix in get_sof.sh.

**Comment by peabee** [comment]
Thanks - kernels are now building AOK again.....

Still have build error:
1 error
build (arm, debian, bullseye-veyron-speedy, 5.4.x-veyron-speedy, overlay)
Process completed with exit code 1.
