### ISSUE TITLE
Out of tree modules complain 

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#3490]
On a fresh VDpup10.0.43, installing broadcom-sta-dkms (and all its dependencies) with dpkg,  complains about 'MIXED/Proprietary' license that taints the kernel, and the wifi interface does not come up.
On reboot the interface  does come up but does not appear to work (connections fail with multiple access points)
After a second reboot it appears OK.
Anything changed in kernel config or is the expected behaviour ?
Kernel log is attached
[Kernel.log.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/9764395/Kernel.log.zip)

**Comment by dimkr** [comment]
The problem is a bug in this out-of-tree driver (you even have a trace you can report to this driver's maintainers), it's normal for the kernel to say it's "tainted" when it loads a non-GPL module.

**Comment by dimkr** [comment]
Looks similar to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016426.

**Comment by dimkr** [comment]
A Debian issue, not something I want to fix downstream.
