### ISSUE TITLE
udevd warnings displayed during boot sequence (new behaviour)

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3502]
Behaviour has changed between:
BUILD_FROM_WOOF='testing;31102a7f1;2022-10-05 13:18:17 +0000'
and
BUILD_FROM_WOOF='testing;42f1deedd;2022-10-13 19:34:27 +0300'

These udevd warnings have always been present in dmesg but are now displayed during the boot sequence causing concern to users (but boot completes OK):
```
[   18.171838] udevd[1091]: specified group 'input' unknown
[   18.172385] udevd[1091]: NAME="%k" is ignored, because it breaks kernel supplied names, please remove it from /etc/udev/rules.d/55-cups.rules:5
[   18.177522] udevd[1091]: IMPORT{builtin}: 'net_setup_link' unknown /lib/udev/rules.d/80-net-setup-link.rules:9
[   18.177797] udevd[1091]: unknown key 'DEVTYPE' in /etc/udev/rules.d/88-puppy-autodetect.rules:6
[   18.177852] udevd[1091]: invalid rule '/etc/udev/rules.d/88-puppy-autodetect.rules:6'
[   18.177925] udevd[1091]: unknown key 'DEVTYPE' in /etc/udev/rules.d/88-puppy-autodetect.rules:10
[   18.177997] udevd[1091]: invalid rule '/etc/udev/rules.d/88-puppy-autodetect.rules:10'
[   18.179441] udevd[1092]: starting eudev-3.2.9
[   18.487193] udevd[1092]: specified group 'input' unknown
[   18.487703] udevd[1092]: NAME="%k" is ignored, because it breaks kernel supplied names, please remove it from /etc/udev/rules.d/55-cups.rules:5
[   18.491951] udevd[1092]: IMPORT{builtin}: 'net_setup_link' unknown /lib/udev/rules.d/80-net-setup-link.rules:9

```

**Comment by dimkr** [comment]
What Puppy is that? Some builds use eudev, some use udev, and /etc/groups is different. 

(AFAIK nothing udev-related has changed for a very long time.)

**Comment by peabee** [comment]
This was with both FocalPup32 (first occurrence) and then confirmed this morning with new build of JammyPup32

I don't think it's a udev change - it's a "what is reported during boot" change.....

**Comment by dimkr** [comment]
The only logging-related change in this time period is 42f1dee, it doesn't do anything when `loglevel=` is not specified, and only relates to kernel logging (as opposed to, userspace logging via syslog).

What kernel and what udev are you using?

**Comment by peabee** [comment]
JammyPup32 has:
huge-5.10.142-kernel-kit.tar.bz2
udev_249.11-0ubuntu3_i386.deb dated 080422

**Comment by dimkr** [comment]
This problem will go away if you update the kernel to one built after 5998641, or if #3503 is merged.

EDIT: I looked at eudev's source code, and it tries to log to kmsg rather than syslog, if the latter fails. udev is started early and that can explain why logging goes to the kernel log. Kernels from before 5998641, built with a default loglevel of 7 rather than 3, conflict with 42f1dee.

EDIT 2: yep, I see the kernel in UPupFF+D-20.12+13.iso is built with `CONFIG_CONSOLE_LOGLEVEL_DEFAULT=7`.

**Comment by dimkr** [comment]
(By the way, `[   18.179441] udevd[1092]: starting eudev-3.2.9` indicates you're using an old eudev package from >=2019 and <=2021, not Ubuntu 22.04's one)
