### ISSUE TITLE
commit #e96f3f2 messes up terminfo for Void Linux builds

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3509]
commit #e96f3f2
I'm not sure why yet but this change messes up terminfo for Void Linux builds.....

**Comment by dimkr** [comment]
What do you mean by "mess up"? Void's ncurses should be more compatible with Void's terminfo, rather than the ancient copy in rootfs-skeleton.

**Comment by peabee** [comment]
Causes terminal displays to go non-graphic...
see https://forum.puppylinux.com/viewtopic.php?p=69685#p69685

**Comment by dimkr** [comment]
Does the problem disappear if that commit is reverted?

**Comment by peabee** [comment]
Yes
Commented out that line, did a rebuild and retest - terminal back to graphics mode

**Comment by dimkr** [comment]
What does `ls /usr/lib/terminfo/${TERM:0:1}/$TERM` say?

**Comment by peabee** [comment]
```
# /usr/lib/terminfo/${TERM:0:1}/$TERM
bash: /usr/lib/terminfo/x/xterm: Permission denied

```
![Screenshot](https://user-images.githubusercontent.com/5926865/196494661-c2d72c1e-ce61-49ee-9d18-2f28c123747d.png)

**Comment by dimkr** [comment]
Does this corruption happen inside a terminal window, or in the tty, outside of X?

**Comment by peabee** [comment]
tty outside of x is where there is a problem with graphics - e.g. q & x etc. instead of lines

**Comment by dimkr** [comment]
So you should do that `ls /usr/lib/terminfo/${TERM:0:1}/$TERM` outside of X

**Comment by peabee** [comment]
I did - it was the same result:
```
# /usr/lib/terminfo/${TERM:0:1}/$TERM
bash: /usr/lib/terminfo/x/xterm: **Permission denied**
```

**Comment by dimkr** [comment]
Why is `TERM=xterm` outside of X? That's weird.

**Comment by dimkr** [comment]
I see you have `export TERM=xterm` at the end of /etc/profile, maybe try to remove it? It doesn't make much sense.

**Comment by dimkr** [comment]
Clean boot of VoidPup64-22.02+10.iso - I don't see this problem. What am I doing wrong?

![void](https://user-images.githubusercontent.com/1471149/196612330-5ed64a1c-5f15-4d25-9b34-7bd2b3aaecb8.png)

**Comment by peabee** [comment]
> Clean boot of VoidPup64-22.02+10.iso - I don't see this problem. What am I doing wrong?

From exit menu "Drop out to terminal" then "xorgwizard"

**Comment by dimkr** [comment]
> From exit menu "Drop out to terminal" then "xorgwizard"

Looks fine

**Comment by peabee** [comment]
> I see you have `export TERM=xterm` at the end of /etc/profile, maybe try to remove it? It doesn't make much sense.

Removed it.... now TERM=xterm-256color when in X
and TERM=xterm when outside of X

but still no graphics when outside of X

By comparison, in LxPupSc32 - xterm when in X; linux when outside of X

**Comment by peabee** [comment]
> > From exit menu "Drop out to terminal" then "xorgwizard"
> 
> Looks fine

What is TERM for you inside X and outside X?

**Comment by dimkr** [comment]
> and TERM=xterm when outside of X

Does it work fine with `TERM=linux` outside of X?

**Comment by dimkr** [comment]
> What is TERM for you inside X and outside X?

`xterm` outside of X, haven't checked inside X because I want to isolate the problem first

**Comment by peabee** [comment]
> Does it work fine with `TERM=linux` outside of X?

Yes - graphics are restored

**Comment by dimkr** [comment]
OK, now I see it too, outside of X. Indeed, `TERM=linux` solves the problem. Why did you add `export TERM=xterm` to /etc/profile?

**Comment by peabee** [comment]
> OK, now I see it too, outside of X. Indeed, `TERM=linux` solves the problem. Why did you add `export TERM=xterm` to /etc/profile?

I have been trying to recall and sadly can't fully remember...... it was to fix a setting for TERM that was occurring during the VoidPup development that was causing problems - and this fix with the terminfo in rootfs-skeleton produced a sane and working system.

The effect of commit e96f3f2 which changed the terminfo population obviously meant that the fix no longer fully worked.

I have just done a build with the fix removed and the new terminfo files and all is now sane again.

Many thanks for your help and assistance.

**Comment by peabee** [comment]
comment removed - erroneous

**Comment by dimkr** [comment]
Does the problem go away once you install rxvt-unicode-terminfo?

**Comment by dimkr** [comment]
Also, check if /usr/share/terminfo/x/xterm-256color exists - it should be part of ncurses and unaffected by https://github.com/void-linux/void-packages/commit/86d89ffc0a2493609389fd3e80b334bef06cb122

**Comment by peabee** [comment]
Sorry - my error - was testing a wrongly built version ....
