### ISSUE TITLE
Error message during boot re: pcspkr

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3537]
BUILD_FROM_WOOF='testing;a2df1d377;2022-10-21 07:15:28 +0100'
huge-5.10.149-kernel-kit

/var/log/messages shows:
Oct 22 17:32:04 puppypc7445 kern.info kernel: [   39.905549] input: PC Speaker as /devices/platform/pcspkr/input/input15
Oct 22 17:32:04 puppypc7445 kern.err kernel: [   39.915490] Error: Driver 'pcspkr' is already registered, aborting...

This error message is displayed on the console during the boot sequence which is disconcerting.

**Comment by dimkr** [comment]
It's harmless and normal.

(But maybe we should start building kernels with `CONFIG_INPUT_PCSPKR=n`: many blacklist this driver to prevent their computer from beeping loudly.)

**Comment by peabee** [comment]
> It's harmless and normal.

I'm sure you're correct - but this is the first time that an error message has appeared during the boot sequence (for me) - and this could be worrying for "other users"....... is it due to the recent changes in error reporting levels?

**Comment by dimkr** [comment]
> is it due to the recent changes in error reporting levels?

As far as I understand - no. Some kernels defaulted to logging level 7 and now they default to 3, so they should be less verbose and not the opposite.

I do see this harmless error in /var/log/messages, but not printed to the console. What Puppy is it?

**Comment by peabee** [comment]
The new KineticPup32

**Comment by lakshayrohila** [comment]
I get the same error on Jammy64, along with some other errors, possibly related to my network driver. Here is the image:-
![IMG_20221124_213211](https://user-images.githubusercontent.com/103126231/203827160-0bc2ee5e-465a-4eff-bb48-9ff0c83ec7f4.jpg)

**Comment by lakshayrohila** [comment]
@dimkr, @peabee, the same happens on Jammy64, kernel 5.15.x. Is this a kernel error or some configuration is needed tro be done on the distro side?

**Comment by dimkr** [comment]
It's a kernel error, a harmless one. I wonder what makes this error appear in the console, because nothing relevant (including [this line](https://github.com/puppylinux-woof-CE/woof-CE/blob/c0d78add6b03e1eeb27a1614bfcedc5173e98739/initrd-progs/0initrd/init#L99)) has changed.

**Comment by dimkr** [comment]
In addition, the relevant kernel configuration keys are identical across 5.10.x, 5.15.x and dpup kernels, and yet, the problem doesn't happen on dpup:

```
~$ zcat /proc/config.gz | grep LOGLEVEL
CONFIG_CONSOLE_LOGLEVEL_DEFAULT=3
CONFIG_CONSOLE_LOGLEVEL_QUIET=4
CONFIG_MESSAGE_LOGLEVEL_DEFAULT=4
```

**Comment by dimkr** [comment]
#3855 will fix this.
