### ISSUE TITLE
Changes for aufs GIT release (v6.0)

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3539]
"J. R. Okajima":
> - git repositories for aufs6 will appear in a week or two.

I was going to create new repositores for aufs6 on github, but I
couldn't.  aufs5-linux.git on github is a fork of torvalds/linux.git,
and github doesn't allow me to create a new fork of the repository which
I already made a fork.
Obviously I could make a brand new empty aufs6-linux.git repo, but in
this case I had to push all git-objects in mainline. That is
unrealistic.
So I decided to rename aufs5-linux.git and aufs5-standalone.git on
github to aufs-linux.git and aufs-standalone.git respectively. And they
will have the branches for aufs6 series.

If you have a clone (or a fork) of aufs5 repositories, please rename
them to non-versioned name. I guess .git/config is the place.

**Comment by dimkr** [comment]
"Forks" are a GitHub concept (as opposed to, a git concept), and GitHub shows extra UI in repos marked as forks. For example, the button that synchronizes the default branch with upstream.

It's true that GitHub doesn't allow you to "fork" a repo more than once. But if you clone the repo and create an empty repo, you can push the same repo to the "fork" and the empty repo. If you don't do git operations through GitHub, only using git or other local tools, this is a good solution.

For example, you can create an empty repo named `other-repo`, then
```
git clone https://github.com/sfjro/aufs5-standalone
cd aufs5-standalone
git remote add other-repo https://github.com/sfjro/other-repo
git push other-repo aufs5.10.117                      <-- push only the branches you want in the new "fork"
```

And there you have two identical repos.

**Comment by peabee** [comment]
Made small change to kernel-kit.build.sh but kernel-kit action seems to be broken:
```
Check failure on line 11 in .github/workflows/kernel-kit.yml

GitHub Actions
/ kernel-kit
Invalid workflow file
The workflow is not valid. .github/workflows/kernel-kit.yml (Line: 11, Col: 9): Unrecognized named-value: 'matrix'. Located at position 153 within expression: github.event_name != 'schedule' || (github.repository == 'puppylinux-woof-CE/woof-CE' && github.ref == 'refs/heads/testing' && github.event.schedule == matrix.schedule)
```

**Comment by dimkr** [comment]
I'll fix it it later today.

**Comment by peabee** [comment]
Thanks - I think builds have now completed successfully,
