### ISSUE TITLE
Github releases workflow warning.

### ISSUE THREAD

**Issue by lakshayrohila** [puppylinux-woof-CE/woof-CE#3548]
Running releases through github workflows is causing this warning in upload job:-
![screenshot](https://user-images.githubusercontent.com/103126231/197480258-3ee5629d-ef16-4785-97ed-887176878f48.png)
Seems like release github workflow is using a command that is deprecated.

**Comment by dimkr** [comment]
Duplicate of https://github.com/softprops/action-gh-release/issues/268.

**Comment by lakshayrohila** [comment]
This issue would be resolved when softprops/action-gh-release will update to using environment files. Closing the issue as duplicate.
