### ISSUE TITLE
broadcom-sta-dkms fails in dpup10.0.66

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#3562]
when through the usual drill to download broadcom-sta-dkms and all dependencies in another machine and try to install it in the affected machine as with previous dpup versions. However now it fails with the error
```
/var/lib/dkms/broadcom-sta/6.30.223.271/build/src/wl/sys/wl_cfg80211_hybrid.c:2383:18: error: ‘struct cfg80211_roam_info’ has no member named ‘bssid’
 2383 |                 .bssid = wl->profile->bssid,
      |                  ^~~~~
```
full dkms make.log attached
[make.log.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/9895318/make.log.zip)

**Comment by dimkr** [comment]
It's a Debian bug, not a Puppy bug. The kernels are identical now. Closing.

**Comment by mavrothal** [comment]
In a fresh, ram-only dpup 10.0.102-retro and 10.0.104-xorg builds running in the same VM and hardware, going through
```
apt-get update
apt-get install broadcom-sta-dkms 
```
flies through 102-retro and fails in 104-xorg
The dkms infrastructure is installed and configured in the running 102-retro system and is pre installed and configured in 104-xorg.
Are there any other relevant changes in 102 vs 104 (apart from the preinstalled packages)?

**Comment by dimkr** [comment]
> Are there any other relevant changes in 102 vs 104 (apart from the preinstalled packages)?

https://vanilla-dpup.github.io/

Let's wait for the Debian 12 release. DKMS-based drivers break often when the kernel changes often and checking why is a waste of time.

**Comment by mavrothal** [comment]
> https://vanilla-dpup.github.io/
>
> Let's wait for the Debian 12 release. DKMS-based drivers break often when the kernel changes often and 
> checking why is a waste of time.

The link has no info on the changes between 102 and 104 (the change log links to the forum thread on 9.2.x). 
The kernel is identical in 102 and 104 
The difference in retro and xorg versions regarding out-of-tree modutes is that the one has dkms support  builtin and the other not

So  the issue appears to be the building in of dkms which is a built bug rather than Debian
Of course you can "won't fix till Debian 12" but please do not close.

**Comment by dimkr** [comment]
> The link has no info on the changes between 102 and 104 (the change log links to the forum thread on 9.2.x).

It's just too early for changelogs, these are development builds not ready for general consumption: things break often and there's no guarantee of stability from Debian's side.
