### ISSUE TITLE
dpup10.0.66-dwl desktop is problematic

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#3563]
Tried it in a machine with inter iris pro integrated graphics.
Everything opens full screen in windows without a manubar so you can not close them!
The panel strip on the top is minuscule and hard to see
There is no right click
No application menu
No desktop wallpaper 
No driver icons
No file manager
No...
Gave up fast since is not clear what is the intended behaviour. 
A smartphone GUI for the desktop or there is something amiss?

**Comment by dimkr** [comment]
https://dwm.suckless.org/
https://github.com/djpohly/dwl/blob/main/README.md

It's a tiling window manager. If you don't want to use, don't.

These are the key bindings:

https://github.com/puppylinux-woof-CE/woof-CE/blob/66d15f0ae7987d6a49dc3c4cd3d4d3466b36bfc9/woof-code/rootfs-petbuilds/dwl-kiosk/config.h#L115
