### ISSUE TITLE
dpup10 install issues

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#3591]
Tried to install vanilladpup10.0.74 in a new (virtual) disk
Puppy installer fails to install bdrv, docx, kbuild and nlsx SFSs as well as ucode.cpio
The build does not include a boot loader (grub/grub4dos etc) that the installer suggest to use

The other "installation" issue (but mostly bdrv/apt)  is that dpkg/apt is not aware of the devx sfs installation. 
It offers to install packages that already present in the loaded devx sfs.

And talking about packages, **please** include the dkms infrastructure in the main ISO.
Is only 11MB (compressed) and is not going to make any serious difference in the size of the ISO (I believe the kernel headers are already in the kbuild.sfs).

**Comment by dimkr** [comment]
Fixed by 148ab5b. (It's much, much more than 11 MB, but worth it).

**Comment by mavrothal** [comment]
I guess a lot of packages moved from devx to main sfs but broadcom installed just fine on 75.

Are the other 2 issues the installer skipping SFSs  and the missing bootloader a "wont fix" or should I reopen it?

**Comment by dimkr** [comment]
The installers are broken, you can open an issue for each specific problem if you want. Fixing the installers is not my top priority, though, because most users don't use them as far as I see.
