### ISSUE TITLE
Github Builds fail to get cached kernel-kit output

### ISSUE THREAD

**Issue by lakshayrohila** [puppylinux-woof-CE/woof-CE#3629]
I tried building a puppy after a lot of time today (nearly a fortnight or two). I realized that the build had failed. When I tried to build `jammy64` with kernel `5.15.x` (default one), I got this error:-
![screenshot_2022-11-20_1366x768](https://user-images.githubusercontent.com/103126231/202899284-cf3801a4-cd12-4f3d-834b-69e8cfc59ed8.png)
The same error I got when I tried to build `jammy64` with kernel `5.4.x`:-
![screenshot_2022-11-20_1366x768_000](https://user-images.githubusercontent.com/103126231/202899339-769cf0c6-91fb-446f-8784-e5b5bf9b0e03.png)

Here are the links to the runs:-
1. https://github.com/lakshayrohila/woof-CE/actions/runs/3507713069
2. https://github.com/lakshayrohila/woof-CE/actions/runs/3507701129

**EDIT:** Same happened with `slacko64` with all default options. Seems like a bug.

**Comment by dimkr** [comment]
Manually triggered https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/3507985933 so your builds pass, will fix this later.

**Comment by lakshayrohila** [comment]
> Manually triggered https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/3507985933 so your builds pass, will fix this later.

Thanks, I was able to successfully build `jammy64`. I am not closing this issue as you said there might be something else that needs to be fixed.

I request you to close the issue yourself when you fix it.
