### ISSUE TITLE
arm_gentoo_gap6 package download failures

### ISSUE THREAD

**Issue by q5sys** [puppylinux-woof-CE/woof-CE#365]
From: DOWNLOAD-FAILS-gentoo-gap6

a52dec-0.7.4-r6.tar.bz2
acl-2.2.51.tar.bz2
alsa-lib-1.0.25-r1.tar.bz2
alsa-utils-1.0.25-r1.tar.bz2
appres-1.0.3.tar.bz2
atk-2.2.0.tar.bz2
attr-2.4.46-r1.tar.bz2
autoconf-2.13.tar.bz2
automake-1.11.1.tar.bz2
bash-4.2_p20.tar.bz2
bdftopcf-1.0.3.tar.bz2
bigreqsproto-1.1.1.tar.bz2
binutils-2.21.1-r1.tar.bz2
bison-2.4.3.tar.bz2
bzip2-1.0.6-r3.tar.bz2
cairo-1.10.2-r2.tar.bz2
cmake-2.8.7-r5.tar.bz2
compositeproto-0.4.2.tar.bz2
coreutils-8.14.tar.bz2
cpio-2.11.tar.bz2
cups-1.5.2-r4.tar.bz2
curl-7.24.0.tar.bz2
damageproto-1.2.1.tar.bz2
db-4.7.25_p4.tar.bz2
diffutils-3.0.tar.bz2
docbook-xml-dtd-4.1.2-r6.tar.bz2
dri2proto-2.6.tar.bz2
e2fsprogs-1.42.tar.bz2
e2fsprogs-libs-1.42.tar.bz2
eject-2.1.5-r2.tar.bz2
expat-2.1.0.tar.bz2
faac-1.28-r1.tar.bz2
faad2-2.7-r2.tar.bz2
findutils-4.4.2-r1.tar.bz2
fixesproto-5.0.tar.bz2
flac-1.2.1-r3.tar.bz2
flex-2.5.35_p10.tar.bz2
fontconfig-2.8.0-r1.tar.bz2
fontsproto-2.1.1.tar.bz2
foomatic-filters-4.0.15.tar.bz2
freetype-2.4.9-r1.tar.bz2
gawk-4.0.0.tar.bz2
gcc-4.5.3-r2.tar.bz2
gdbm-1.8.3-r4.tar.bz2
gdk-pixbuf-2.24.1-r1.tar.bz2
gettext-0.18.1.1-r1.tar.bz2
ghostscript-gpl-9.05-r1.tar.bz2
giflib-4.1.6-r2.tar.bz2
git-1.7.3.4-r1.tar.bz2
glib-2.30.3.tar.bz2
glib-networking-2.30.2.tar.bz2
glibc-2.13-r4.tar.bz2
glproto-1.4.14-r1.tar.bz2
gmp-5.0.2_p1.tar.bz2
gnutls-2.12.18.tar.bz2
grep-2.9.tar.bz2
groff-1.21.tar.bz2
gtk+-2.24.10-r1.tar.bz2
gtksourceview-2.10.5-r2.tar.bz2
gzip-1.4.tar.bz2
hicolor-icon-theme-0.12.tar.bz2
hunspell-1.3.2-r3.tar.bz2
iceauth-1.0.5.tar.bz2
inputproto-2.0.2.tar.bz2
intltool-0.50.2.tar.bz2
iptables-1.4.13.tar.bz2
kbproto-1.0.5.tar.bz2
lame-3.99.3.tar.bz2
lcms-1.19.tar.bz2
less-444.tar.bz2
libarchive-3.0.3.tar.bz2
libcdio-0.83.tar.bz2
libcroco-0.6.5.tar.bz2
libdrm-2.4.27.tar.bz2
libdv-1.0.0-r2.tar.bz2
libffi-3.0.10.tar.bz2
libfontenc-1.1.0.tar.bz2
libgcrypt-1.4.6.tar.bz2
libglade-2.6.4.tar.bz2
libgpg-error-1.10.tar.bz2
libice-1.0.7.tar.bz2
libidl-0.8.14.tar.bz2
libjpeg-turbo-1.2.0-r1.tar.bz2
libnotify-0.7.4.tar.bz2
libogg-1.3.0.tar.bz2
libpciaccess-0.12.1.tar.bz2
libpcre-8.12.tar.bz2
libpng-1.5.10.tar.bz2
libproxy-0.4.7.tar.bz2
libpthread-stubs-0.3.tar.bz2
librsvg-2.34.2.tar.bz2
libsm-1.2.0.tar.bz2
libsndfile-1.0.25.tar.bz2
libtasn1-2.12.tar.bz2
libtheora-1.1.1.tar.bz2
libtool-2.4-r1.tar.bz2
libusb-1.0.9_rc3.tar.bz2
libvorbis-1.3.2.tar.bz2
libx11-1.4.4.tar.bz2
libxau-1.0.6.tar.bz2
libxaw-1.0.9.tar.bz2
libxcb-1.7.tar.bz2
libxcomposite-0.4.3-r1.tar.bz2
libxcursor-1.1.12.tar.bz2
libxdamage-1.1.3.tar.bz2
libxdmcp-1.1.0.tar.bz2
libxext-1.3.0.tar.bz2
libxfixes-5.0.tar.bz2
libxfont-1.4.4.tar.bz2
libxft-2.2.0.tar.bz2
libxi-1.4.3-r1.tar.bz2
libxkbfile-1.0.7.tar.bz2
libxml2-2.7.8-r5.tar.bz2
libxmu-1.1.0.tar.bz2
libxpm-3.5.9.tar.bz2
libxrandr-1.3.2.tar.bz2
libxrender-0.9.6.tar.bz2
libxres-1.0.5.tar.bz2
libxscrnsaver-1.2.1.tar.bz2
libxslt-1.1.26-r3.tar.bz2
libxt-1.1.1.tar.bz2
libxtst-1.2.0.tar.bz2
libxv-1.0.6.tar.bz2
libxxf86misc-1.0.3.tar.bz2
libxxf86vm-1.1.1.tar.bz2
linux-headers-3.1.tar.bz2
luit-1.1.0.tar.bz2
m4-1.4.15.tar.bz2
make-3.82-r1.tar.bz2
makedepend-1.0.3.tar.bz2
man-1.6g.tar.bz2
mesa-7.11.2.tar.bz2
mkfontdir-1.0.6.tar.bz2
mkfontscale-1.0.9-r1.tar.bz2
module-init-tools-3.16-r1.tar.bz2
mpc-0.8.2.tar.bz2
mpfr-3.0.1_p4.tar.bz2
ncurses-5.9-r2.tar.bz2
net-tools-1.60_p20110409135728.tar.bz2
nettle-2.4.tar.bz2
nspr-4.9.tar.bz2
nss-3.13.4.tar.bz2
openssh-5.9_p1-r4.tar.bz2
openssl-1.0.0i.tar.bz2
pango-1.29.4.tar.bz2
parted-3.1.tar.bz2
patch-2.6.1.tar.bz2
pciutils-3.1.9-r1.tar.bz2
perl-5.12.4-r1.tar.bz2
pixman-0.24.0.tar.bz2
pkgconfig-0.26.tar.bz2
poppler-0.18.4-r1.tar.bz2
popt-1.16-r1.tar.bz2
procps-3.2.8_p11.tar.bz2
psmisc-22.14.tar.bz2
python-2.7.2-r3.tar.bz2
randrproto-1.3.2.tar.bz2
readline-6.2_p1.tar.bz2
realpath-1.16.tar.bz2
recordproto-1.14.1.tar.bz2
renderproto-0.11.1.tar.bz2
resourceproto-1.2.0.tar.bz2
rsync-3.0.9.tar.bz2
scrnsaverproto-1.2.1.tar.bz2
sed-4.2.1.tar.bz2
sgml-common-0.6.3-r5.tar.bz2
speex-1.2_rc1.tar.bz2
sqlite-3.7.10.tar.bz2
startup-notification-0.12.tar.bz2
sudo-1.8.3_p2.tar.bz2
sysvinit-2.88-r3.tar.bz2
texinfo-4.13.tar.bz2
tiff-4.0.1-r1.tar.bz2
timezone-data-2011n.tar.bz2
udev-171-r5.tar.bz2
unrar-4.1.4-r2.tar.bz2
unzip-6.0-r1.tar.bz2
util-linux-2.20.1-r1.tar.bz2
util-macros-1.17.tar.bz2
videoproto-2.3.1.tar.bz2
wget-1.12-r3.tar.bz2
xauth-1.0.6.tar.bz2
xcalc-1.0.4.1.tar.bz2
xcb-proto-1.6-r2.tar.bz2
xcb-util-0.3.8.tar.bz2
xclipboard-1.1.1.tar.bz2
xclock-1.0.5.tar.bz2
xcmiscproto-1.2.1.tar.bz2
xdpyinfo-1.2.0.tar.bz2
xev-1.1.0.tar.bz2
xextproto-7.2.0.tar.bz2
xf86-input-evdev-2.6.0.tar.bz2
xf86-input-keyboard-1.6.0.tar.bz2
xf86-input-mouse-1.7.1.tar.bz2
xf86-video-fbdev-0.4.2.tar.bz2
xf86-video-omapfb-0.1.1_p3.tar.bz2
xf86-video-v4l-0.2.0.tar.bz2
xf86bigfontproto-1.2.0.tar.bz2
xf86dgaproto-2.1.tar.bz2
xf86driproto-2.1.1.tar.bz2
xf86miscproto-0.9.3.tar.bz2
xf86vidmodeproto-2.3.1.tar.bz2
xgamma-1.0.4.tar.bz2
xhost-1.0.4.tar.bz2
xineramaproto-1.2.1.tar.bz2
xinit-1.3.1-r1.tar.bz2
xkbcomp-1.2.3.tar.bz2
xkeyboard-config-2.4.1-r3.tar.bz2
xload-1.1.0.tar.bz2
xmessage-1.0.3.tar.bz2
xmodmap-1.0.5.tar.bz2
xorg-server-1.11.2-r2.tar.bz2
xprop-1.2.1.tar.bz2
xproto-7.0.22.tar.bz2
xrandr-1.3.5.tar.bz2
xrdb-1.0.9.tar.bz2
xset-1.2.2.tar.bz2
xsm-1.0.2.tar.bz2
xtrans-1.2.6.tar.bz2
xvid-1.3.2.tar.bz2
xvidtune-1.0.2.tar.bz2
xvinfo-1.1.1.tar.bz2
xwininfo-1.1.2.tar.bz2
xz-utils-5.0.3.tar.bz2
zip-3.0.tar.bz2
zlib-1.2.5-r2.tar.bz2

**Comment by 01micko** [comment]
This has been removed anyway
