### ISSUE TITLE
Pale Moon appears under both Network and Internet

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#3673]
This is a bug in the petbuild.

**Comment by lakshayrohila** [comment]
Which one do you want it to be shown under? I'll work on it.

**Comment by dimkr** [comment]
I guess Internet, like it does on FossaPup. Just look at FossaPup's palemoon.desktop and use the same value for Categories.

**Comment by lakshayrohila** [comment]
I'll remove the Network one from there. Actually, I got that desktop file from the palemoon `.tar.xz` archive.

**Comment by dimkr** [comment]
> I got that desktop file from the palemoon `.tar.xz` archive.

This is exactly the problem, you used a .desktop file without the usual Puppy customization of Categories as your reference 😄

**Comment by lakshayrohila** [comment]
> This is exactly the problem, you used a .desktop file without the usual Puppy customization of Categories as your reference smile

:sweat_smile: I tested it and it worked. I modified it keeping Fossapup .desktop file in consideration, but thought that as the categories were working, just let them be as they are. :sweat_smile:
