### ISSUE TITLE
Structure of woof-distro for Slackware builds??

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3677]
@01micko @dimkr 
S15Pup build recipes should probably be uploaded to Woof-CE......
however there is an issue with the structure of woof-distro
The current path for Slacko64-8.2.2 is:
/testing/woof-distro/x86_64/**slackware64/15.0**
however comparing it to Ubuntu it perhaps should be:
/testing/woof-distro/x86_64/**slackware/slacko150**
then S15Pup64 could be:
/testing/woof-distro/x86_64/**slackware/s15pup150**
similarly for 32-bit S15Pup32 should be:
/testing/woof-distro/x86/slackware/s15pup150

The other Slacko's would become: slackonnn where nnn is 140, 141, 142 under x86 and x86_64
Should I restructure? What are the "knock-on" implications??

**Comment by lakshayrohila** [comment]
Why is this needed? I mean, ubuntu names its distros with some animal or some generic name, but slackware does not... I suppose. And if it really does not, then why not let it remain as the version number?

Of course, I think `slackware64` could be renamed to `slackware`, but might not be very well needed.

I just had an idea about this, so am posting. @dimkr and @01micko will furthermore tell if they like the idea or not.

**Comment by dimkr** [comment]
It doesn't really matter, you can put your stuff in `woof-distro/x86_64/slackware64/s15pup` or even `woof-distro/x86_64/slackware64/whatever` and everything will work just fine.

**Comment by peabee** [comment]
closed via #3683
