### ISSUE TITLE
Jammy64: evince: Icons not found with Pmaterial

### ISSUE THREAD

**Issue by lakshayrohila** [puppylinux-woof-CE/woof-CE#3781]
Here are few examples (with Pmaterial icon theme):-
![1](https://user-images.githubusercontent.com/103126231/209669989-b02ac9a5-33f3-4526-aa69-eb6294ceb835.png)
![2](https://user-images.githubusercontent.com/103126231/209670000-86fff526-1b0c-481f-81b0-617f41d0e17f.png)

And their counterparts in breeze icon theme:-
![breeze1](https://user-images.githubusercontent.com/103126231/209670067-2b9054f2-32ca-47fc-bac7-97fe5fe3d338.png)
![breeze2](https://user-images.githubusercontent.com/103126231/209670073-da39afd7-fe55-4cd0-94c3-937fddbec5ad.png)

@dimkr, I also followed your advice to build without Pmaterial icon cache (See https://github.com/puppylinux-woof-CE/woof-CE/compare/testing...lakshayrohila:woof-CE:test/jammy64#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721).

**Comment by dimkr** [comment]
It's a small icon theme, it doesn't have all icons GNOME applications uses.

The only solution I see is:
1. Adding `adwaita-icon-theme` as a separate package so it doesn't go through woof-code/packages-templates/gtk+3_FIXUPHACK
2. Changing the default icon theme to Adwaita

Expect a big increase in size, and some applications will be slower to start.

**Comment by lakshayrohila** [comment]
> It's a small icon theme, it doesn't have all icons GNOME applications uses.
> 
> The only solution I see is:
> 
>     1. Adding `adwaita-icon-theme` as a separate package so it doesn't go through woof-code/packages-templates/gtk+3_FIXUPHACK
> 
>     2. Changing the default icon theme to Adwaita
> 
> 
> Expect a big increase in size, and some applications will be slower to start.

Or we may add icons slowly as we get to know which ones are needed. For now I think it might be the only solution to use adwaita theme.

**Comment by dimkr** [comment]
@01micko is the master when it comes to tiny SVG icons. It shouldn't be hard to add those missing "edit", "menu" and "share" icons.

**Comment by 01micko** [comment]
My thought would be to add them to `hicolor` so they are shared with all Puppy native icon themes.

**Comment by lakshayrohila** [comment]
> My thought would be to add them to `hicolor` so they are shared with all Puppy native icon themes.

Where is hicolor icon theme repo? Should we just open up issue relating to this on their repo?

Or should we open it in evince repo (https://gitlab.gnome.org/GNOME/evince)?

For a reference, I found evince's icons [here](https://gitlab.gnome.org/GNOME/evince/-/tree/main/data/icons/48x48/actions).

**Comment by 01micko** [comment]
@lakshayrohila no, because the `hicolor` repo AFAIK doesn't exist. All icon themes _can_ use it as a fallback and that is where most applications put their application icon and in some cases other icons to override defaults or to complement defaults - `geany` is a good example.

We can create our own `hicolor` repo and add missing icons from our themes or even other puppy specific icons that can be called in any GTK app directly by their name with no extension.

**Comment by lakshayrohila** [comment]
The icons we are looking for are (as breeze-icon-theme has named 'em):-
- `document-edit.svg`
- `application-menu.svg`
- `document-share.svg`

Don't know if it will matter whether we use the same names, or just go for {`edit`,`menu`,`share`}`.svg`?

**EDIT:-** Yes, it will matter. Currently, PMaterial has an icon named `edit.svg`. We just need to symbolically link it to `document-edit.svg` (for 16x16 only, I think; others are bigger).

**Comment by 01micko** [comment]
Did you try it? If so, working?

You can also try copying `edit.svg` to `/usr/share/icons/hicolor/scalable/actions/` , update icon cache and try that - also the other icons, you can use any svg icon, just to see if it works - of course named appropriately. All icons themes miss a 'sharing' type icon (as seen in mobile apps, web pages) so this could be a good one to add to a new 'hicolor' repo, which would probably be easier maintained as part of the main woof-ce instead of it's own repo.

**Comment by dimkr** [comment]
I wonder if these file names are correct. Looks like Adwaita doesn't have icons with these names 🤔

**Comment by lakshayrohila** [comment]
> I wonder if these file names are correct. Looks like Adwaita doesn't have icons with these names thinking

Don't know particularly, but evince does seem to use it (atleast the document-edit.svg one).

> Did you try it? If so, working?

Yes, but only the document-edit.svg one. Also works with hicolor.

**EDIT:** I have tested with all of those names, but have been successful only with the first one (the one which I have opened PRs for).

**Comment by 01micko** [comment]
try `open-menu.svg`

**Comment by lakshayrohila** [comment]
I now tried the symbolic links' names used by breeze. Miraculously, it works! Here are the names:-
- send-to.svg (for share)
- open-menu.svg (for menu)

Breeze seemed to be using them as {send-to,open-menu}-symbolic.svg, and it still worked. The above mentioned files also do work, though I can not find any similar icons in PMaterial, so not opening any PR for those.

**Comment by dimkr** [comment]
Aha, Adwaita has:

/usr/share/icons/Adwaita/scalable/actions/send-to-symbolic.svg
/usr/share/icons/Adwaita/scalable/actions/open-menu-symbolic.svg
/usr/share/icons/Adwaita/scalable/actions/document-edit-symbolic.svg

**Comment by dimkr** [comment]
I'll test #3784. AFAIK the idea behind "symbolic icons" is that they don't get themed and applications that use them don't break against icon themes other than Adwaita.

**Comment by 01micko** [comment]
No, the other is `send-to-symbolic` - just `send-to` should do.

**Comment by lakshayrohila** [comment]
> No, the other is `send-to-symbolic` - just `send-to` should do.

I must say, breeze uses the `*-symbolic` one and still succeeds to display the icons. Should work in my opinion with those file names as well.

**Comment by 01micko** [comment]
Ok, so PMaterial and friends can be patched with `document-edit.svg -> edit.svg` and just add a `send-to` and an `open-menu` to woof is the simplest strategy.

I've been using in many gtk apps for years without the `-symbolic` and haven't had issues yet - it may have changed in GTK4, IDK

**Comment by 01micko** [comment]
Here is a very simple `send-to.svg` icon

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" height="256px" width="256px" viewBox="0 0 192 192">
  <path style="fill:#EDEDED;stroke:#646464;stroke-width:10;" d="m 20,36 152,60 -152,60 24,-60 z"/>
</svg>
```

![send-to](https://user-images.githubusercontent.com/1019119/209781108-91696212-d5fd-4421-b24d-8e828bd1967c.png)


and `open-menu.svg` (notice I keep contrast so works in all themes)

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" height="256px" width="256px" viewBox="0 0 192 192">
  <path style="fill:#EDEDED;stroke:none;" d="m 42,10 108,0 a 12 12 0 0 1 12,12  l 0,148 a 12,12 0 0 1 -12,12 l -108,0 a 12,12 0 0 1 -12,-12 l 0,-148 a 12,12 0 0 1 12,-12 z"/>
  <path style="fill:none;stroke:#646464;stroke-width:10;" d="m 42,48 108,0 m -108,48 108,0 m -108,48 108,0"/>
</svg>
```
![open-menu](https://user-images.githubusercontent.com/1019119/209781147-c18dd59c-e0f8-4b40-9df8-245e92aaa501.png)



These are suitable for `/usr/share/icons/scalable/actions` I put theme there because they work but GTK does have to scale them, but because svg scales so well the penalty should be negligible.

**Comment by dimkr** [comment]
@01micko Maybe drop the background, make the 3 lines thicker and fill them with the same light gray color? We have many gray GTK+ themes 😄

**Comment by 01micko** [comment]
ok.

**Comment by dimkr** [comment]
[#3784](https://github.com/puppylinux-woof-CE/woof-CE/pull/3784#discussion_r1058153755) works too, although Puppy-style SVG icons look like a better solution.

**Comment by 01micko** [comment]
Take 2

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" height="256px" width="256px" viewBox="0 0 192 192">
  <path style="fill:#EDEDED;stroke:#646464;stroke-width:8;" d="m 38,44 116,0 0,16 -116,0 z m 0,44 116,0 0,16 -116,0 z m 0,44 116,0 0,16 -116,0 z"/>
</svg>
```

![open-menu2](https://user-images.githubusercontent.com/1019119/209786738-7dd9b7dd-7d0d-43ab-984a-aac586f2911f.png)

**Comment by lakshayrohila** [comment]
@01micko, does look nice. Waiting for you to open a PR for this (or merge directly).
