### ISSUE TITLE
Jammy64: pavucontrol: icon not found.

### ISSUE THREAD

**Issue by lakshayrohila** [puppylinux-woof-CE/woof-CE#3787]
Completely like #3781, except that with pavucontrol this time. Here are the screenshots:-
![1](https://user-images.githubusercontent.com/103126231/209931711-1c8649f0-7a04-4ae0-b5c2-721b6f4c591c.png)

And with breeze:-
![breeze1](https://user-images.githubusercontent.com/103126231/209931718-e124abd4-e99c-41c2-9587-9e0f6c001a70.png)

The name I found for the icon to be added:-
![sol](https://user-images.githubusercontent.com/103126231/209931721-eaa81d5c-aafc-42e1-8a0b-392e985ac08b.png)

There was an image named `lock.svg` as well, but changing that was of no use.

I don't think PMaterial has same icon.

**Comment by 01micko** [comment]
Ah yes, I have that fixed in a local build, PR shortly.
