### ISSUE TITLE
JammyPup64: issue with dbus, rtkit and pipewire

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#3904]
I have a local Woof-CE build of JammyPup64 which is working very nicely. Thank you!

One issue I can't resolve pertains to dbus, rtkit and pipewire (see xerrs.log below).

If I understand correctly, the rkit calls are failing with "org.freedesktop.DBus.Error.ServiceUnknown" which may indicate the rtkit daemon isn't running and dbus doesn't know how to start it. I know very little about such things, but my initial research suggests this is because pipewire is calling module-rt but this fails and the fallback is to call rtkit which also fails ???

I assume the above issue involves: /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-rtkit.so

---

A second error seems to involve a call to /usr/lib/x86_64-linux-gnu/wireplumber-0.4/libwireplumber-module-logind.so, however I can't find a library by that name.

Audio works fine on my system so the errors may be of little importance, but I thought there might be a simple solution.

Thanks

====> /tmp/xerrs.log <====

X.Org X Server 1.21.1.3
X Protocol Version 11, Revision 0
Current Operating System: Linux puppypc29148 6.1.10-JP #1 SMP PREEMPT_DYNAMIC Wed Feb  8 12:49:59 EST 2023 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz pmedia=usbflash pdrv=F1AD-E670 pfix=fsck,fsckp net.ifnames=0 TZ=EST5EDT,M3.2.0,M11.1.0
xorg-server 2:21.1.3-2ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sat Feb 11 00:09:11 2023
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
non-network local connections being added to access control list
[W][05650.957134] mod.rt       | [     module-rt.c:  224 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][05650.957425] mod.rt       | [     module-rt.c:  526 set_nice()] could not set nice-level to -11: No such file or directory
[W][05650.959156] mod.rt       | [     module-rt.c:  224 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][05650.971900] mod.rt       | [     module-rt.c:  224 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][05650.974151] mod.rt       | [     module-rt.c:  224 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][05650.974202] mod.rt       | [     module-rt.c:  716 impl_acquire_rt()] could not make thread 73008 realtime using RTKit: No such file or directory
M 00:09:14.155082             mod.rt ../src/modules/module-rt.c:224:translate_error: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
M 00:09:14.155457             mod.rt ../src/modules/module-rt.c:526:set_nice: could not set nice-level to -11: No such file or directory
M 00:09:14.156254             mod.rt ../src/modules/module-rt.c:224:translate_error: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][05651.204619] mod.rt       | [     module-rt.c:  224 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][05651.204894] mod.rt       | [     module-rt.c:  526 set_nice()] could not set nice-level to -11: No such file or directory
[W][05651.205509] mod.rt       | [     module-rt.c:  224 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
M 00:09:14.160959             mod.rt ../src/modules/module-rt.c:224:translate_error: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
M 00:09:14.161868             mod.rt ../src/modules/module-rt.c:224:translate_error: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
M 00:09:14.161924             mod.rt ../src/modules/module-rt.c:716:impl_acquire_rt: could not make thread 73069 realtime using RTKit: No such file or directory
[W][05651.222166] mod.rt       | [     module-rt.c:  224 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][05651.222927] mod.rt       | [     module-rt.c:  224 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][05651.222971] mod.rt       | [     module-rt.c:  716 impl_acquire_rt()] could not make thread 73073 realtime using RTKit: No such file or directory
M 00:09:14.193640    m-lua-scripting ../modules/module-lua-scripting/config.c:80:load_components: Failed to open module /usr/lib/x86_64-linux-gnu/wireplumber-0.4/libwireplumber-module-logind: /usr/lib/x86_64-linux-gnu/wireplumber-0.4/libwireplumber-module-logind.so: cannot open shared object file: No such file or directory
536870912
M 00:09:14.620272    m-lua-scripting ../modules/module-lua-scripting/api.c:338:object_activate_done: <WpSiAudioAdapter:0x562ed84e80b0> Object activation aborted: proxy destroyed
M 00:09:14.620426 script/create-item create-item.lua:74:chunk: <WpSiAudioAdapter:0x562ed84e80b0> failed to activate item: Object activation aborted: proxy destroyed
/bin/jwm
acpi daemon stopped.
acpi daemon started.
EXIT="Ready"

**Comment by dimkr** [comment]
AFAIK both errors are harmless.

I've played a bit with rtkit - it's used by PipeWire to reduce latency (by using a realtime scheduling policy) but on systems with a slow CPU it can cause slugishness when one application plays audio. You _can_ install rtkit to silence this error, but this might have some consequences.

The logind module is useless - Puppy doesn't include systemd and doesn't use PAM, so it can't use logind. Even if you silence that error by adding that module, it won't do anything when logind (or elogind, doesn't matter) isn't running and functional.

**Comment by radky2** [comment]
Thanks for the quick response.

Good to know the messages are harmless.

Thanks again for JammyPup64 and for your contributions to Woof-CE.

**Comment by dimkr** [comment]
@radky2 Feel free to submit pull requests with changes!

**Comment by lakshayrohila** [comment]
@radky2, can you also look at https://github.com/puppylinux-woof-CE/woof-CE/issues/3741 and check whether its an issue for you as well?

**Comment by dimkr** [comment]
@lakshayrohila It's unlikely. #3741 doesn't look like a bug to me - maybe some other device was connected to your headset? If this problem still happens, try `dmesg`, `cat /var/log/messages` or `connect 11:11:22:CC:94:F4` inside `bluetoothctl`.

**Comment by lakshayrohila** [comment]
> @lakshayrohila It's unlikely. #3741 doesn't look like a bug to me - maybe some other device was connected to your headset? If this problem still happens, try `dmesg`, `cat /var/log/messages` or `connect 11:11:22:CC:94:F4` inside `bluetoothctl`.

The device was earlier connected to the same device's Fossapup installation. Also, even after the problem in Jammy, the problem didn't occur in Fossa (but didn't resolve in Jammy).

Now, I also have access to different hardware. I'll reconfirm the problem with this device.

Searching about `br-connection-timeout` heads me to https://www.reddit.com/r/archlinux/comments/qnffce/bluetooth_headset_connection_occasionally_fails/ (that error is `br-connection-page-timeout`).

I'll also try looking at and providing you the logs.

**Comment by radky2** [comment]
**@lakshayrohila**

Re: Bluetooth error: br-connection-timeout on jammy64

Unfortunately, I no longer use bluetooth and my old (erratic) bluetooth speaker does not provide an adequate base for testing.

Even so, I'll continue to follow your bug reports and contributions to JammyPup64.

Thanks
