### ISSUE TITLE
pmusic .desktop files have no Exec= line

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3906]
@zigbert ......

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-packages/pmusic_cd/usr/share/applications/pmusic_CD.desktop

needs 'Exec=pmusic_CD' added

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-packages/pmusic_radio/usr/share/applications/pmusic_radio.desktop

needs 'Exec=pmusic_radio' added

???

**Comment by zigbert** [comment]
Thank you
Fixed
