### ISSUE TITLE
pMusic missing icons when not under JWM

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3907]
@zigbert (maybe related to #3568)
pMusic does not display some icons when used under a different window manger (e.g. OpenBox)

Terminal output:
```
# pmusic
grep: /root/.config/gtk-3.0/settings.ini: No such file or directory
/usr/local/pmusic/func: line 474: /root/.config/gtk-3.0/settings.ini: No such file or directory
/usr/local/pmusic/themes/Gtk/gtk-2.0/gtkrc:71: Unable to locate image file in pixmap_path: "blank.svg"
/usr/local/pmusic/themes/Gtk/gtk-2.0/gtkrc:74: Background image options specified without filename
ALBUMART_SEARCH=""
ALBUMART_SEARCH1=""
ALBUMART_SEARCH2=""
ALBUMART_SEARCH3=""
ALBUMART_SEARCH4=""
ALBUMART_SEARCH5=""
ALBUMART_SEARCH_ACTIVATE=""
ALBUMART_SEARCH_NEXT=""
ALBUMART_SEARCH_PREV=""
ARTWORK=""
BUTTON_PLAY=""
BUTTON_SMARTADD_BPM=""
BUTTON_SMARTADD_GENRE=""
BUTTON_SMARTADD_RATING=""
HISTORY_REDO=""
HISTORY_UNDO=""
NOTEBOOK_MAINGUI="0"
PIX_TAB_1=""
PIX_TAB_2=""
PIX_TAB_3=""
PIX_TAB_4=""
PIX_TAB_5=""
PIX_TAB_6=""
PIX_TAB_7=""
PIX_TAB_8=""
PIX_TAB_9=""
PLAYLIST=""
PLAYMODE=""
PLAYQUEUE_TABS=""
PLAYQUEUE_TABS_2=""
PROGRESS="0"
REFRESH_LIST=""
REFRESH_TABS=""
SEARCH=""
SEARCHPATH="/mnt [OR] /root"
SEARCH_ALBUMART="false"
SEARCH_COLLECTIONS="true"
SEARCH_FILES="false"
SEARCH_LYRICS="false"
SEARCH_MUSICBRAINZ="true"
SEARCH_MYMUSIC="true"
SEARCH_PODCAST="true"
SEARCH_RADIO="true"
SEARCH_YOUTUBE="false"
SKIP_INDEX_SCAN="false"
SMARTADD_NR="10"
SMARTADD_RANDOM="false"
SMARTADD_SORT_ORDER="true"
SMARTADD_SOURCE="List below"
SOURCE=""
STATUSBAR=" (0:00)"
SVG_NOWPLAYING=""
TXT_TAB_1="
  My PlayQueue  "
TXT_TAB_2=""
TXT_TAB_3=""
TXT_TAB_4=""
TXT_TAB_5=""
TXT_TAB_6=""
TXT_TAB_7=""
TXT_TAB_8=""
TXT_TAB_9=""
UPDATE_SOURCELIST="false"
VBOX_ADD_OPTIONS=""
VBOX_SEARCH_OPTIONS=""
VBOX_TAB_1=""
VBOX_TAB_2=""
VBOX_TAB_3=""
VBOX_TAB_4=""
VBOX_TAB_5=""
VBOX_TAB_6=""
VBOX_TAB_7=""
VBOX_TAB_8=""
VBOX_TAB_9=""
VIEW_ADD_OPTIONS="false"
VIEW_SEARCH_OP[ "$GTKDIALOG_BUILD" = GTK3 ]TIONS="false"
VOLUME="79"
WINDOW_TITLE=""
YOUTUBE_OUTFILE=""
EXIT="Exit"

```
![Screenshot](https://user-images.githubusercontent.com/5926865/218458364-eb0a8da5-296d-48ba-acca-439305e592a0.png)

**Comment by zigbert** [comment]
Do you have a build available where I can test this?

**Comment by peabee** [comment]
Thanks @zigbert 

https://sourceforge.net/projects/lxpup/files/Other/LxPupSc64/LxPupSc64-23.01%2B0-T.iso/download

shows the problem

**Comment by zigbert** [comment]
Can't get LxPupSc64 to run X. I have both a builtin Radeon and a Nvidia 1650TI, and I need to disable the nouveau driver to reach desktop. Tried to add 'blacklist nouveau' to /etc/modprobe.d/blacklist.conf, but it isn't in the file after a reboot and the nouveau driver is still the active one. Do you know how I can do this?

**Comment by peabee** [comment]
Not entirely sure but what I'd try would be:
Boot with nox to terminal
Run xorgwizard
and choose a specific driver i.e. radeon (maybe)

**Comment by peabee** [comment]
Searching the forum:
https://forum.puppylinux.com/viewtopic.php?p=74368#p74368
Yes, the init script modifies /etc/modprobe.d/blacklist.conf. You need to add nouveau to SKIPLIST in /etc/rc.d/MODULESCONFIG - this can be done using sed at the terminal.

or you could put a modified /etc/rc.d/MODULESCONFIG into a ydrv

**Comment by peabee** [comment]
Here is a ydrv with nouveau in the SKIPLIST - remove -false.gz:
[ydrv_LxPupSc64_23.01.sfs-false.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/10744512/ydrv_LxPupSc64_23.01.sfs-false.gz)

**Comment by zigbert** [comment]
I'm in... Thank you!

Must mention that nouveau was misspelled in the ydrv... I have done that many times myself :)

**Comment by zigbert** [comment]
Comments after first dig
- LxPupSc64 runs gtkdialog with Gtk2
- Gtk2 in LxPupSc64 does not look for icons in the common $HOME/icons or /usr/share/icons
- I solved the icon-issue by copying icons to /usr/share/pixmaps, but this is a messy solution since it doesn't read subfolders.

Is there anything special with the Gtk2-lib in LxPupSc64?

A lot of good stuff in this Puppy... but a few sidenotes:
- Abiword crashes when copying text (Ctrl+C). I have not seen this before.
- Gnumeric is old and troubles with my piecharts.
- Special keys on my laptop (screen brightness, volume, etc) does not work. This works in Dpup 9.
- Redshiftgui won't install properly

**Comment by peabee** [comment]
If you switch to JWM (Setup -> Switch desktop environments) you will see that the icons are displayed correctly, so I think all the software must be OK, it's just the settings/config that is causing problems...... maybe?

**Comment by dimkr** [comment]
Does it use the gtkdialog petbuild (= latest gtkdialog) or some old gtkdialog .pet package?

**Comment by peabee** [comment]
petbuild:

gtkdialog-0.8.5a|gtkdialog|0.8.5a||BuildingBlock|256||gtkdialog-0.8.5a.pet||gtkialog is a small utility for fast and easy GUI building|puppy|||

**Comment by zigbert** [comment]
Jwm - OK
Openbox - NO

Do we have others to test? Note, this is a Gtk2 issue.

**Comment by peabee** [comment]
> Jwm - OK Openbox - NO
> 
> Do we have others to test? Note, this is a Gtk2 issue.

Not conclusive - but S15Pup64 with Xfce ydrv also has missing icons..........

![Screenshot](https://user-images.githubusercontent.com/5926865/219867682-b249d752-a24f-4f38-a826-3359b901791e.png)

**Comment by dimkr** [comment]
```
# pmusic
grep: /root/.config/gtk-3.0/settings.ini: No such file or directory                  <---
```

**Comment by peabee** [comment]
Booted with this ydrv which contains gtk-3.0/settings.ini and the error msg is gone but there are still no icons....
[ydrv_LxPupSc32_23.01.sfs-false.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/10774783/ydrv_LxPupSc32_23.01.sfs-false.gz)

**Comment by zigbert** [comment]
The file /root/.config/gtk-3.0/settings.ini is only in use for Gtk3, so in this case it doesn't matter. pMusic is builing icon-structure ready for both version 2 and 3 of Gtk, independent of which version the OS is using.

But obvious there is something I haven't grasped of how to set up a proper icon-structure for Gtk2 without depending on stock icons. I only tested it in Jwm.

Stock icons would be possible, but that would require unique gui-code for each Gtk-version. That would not be suitable. We still have pMusic 6.0.3 as a backup for pure Gtk2.

As mentioned above, there is a solution by dumping all icons into /usr/share/pixmaps/

**Comment by peabee** [comment]
Weirdly, with the Abiword & Gnumeric petbuilds the problem is inverted......
Icons show in menus when using LXDE but disappear when using JWM:

![Screenshot(1)](https://user-images.githubusercontent.com/5926865/220169819-195606c3-efaa-4dcb-b133-6abaa1c33066.png) .... ![Screenshot(2)](https://user-images.githubusercontent.com/5926865/220169851-b29df5f9-f093-491b-948f-2522d5796a63.png)

**Comment by dimkr** [comment]
Maybe it's because s15pup before 65910f5 used some old .pet package of libxml2 instead of the Slackware one? So many things can go wrong when you mix packages from different distros like that.

And, do you have `gtk-menu-images = 1` in ~/.config/gtk-3.0/settings.ini?

**Comment by peabee** [comment]
Was a new build with all changes from https://github.com/puppylinux-woof-CE/woof-CE/commit/65910f5c0a782c013dfcf23513ba3d6ba05c0d71

Will check.......

**Comment by peabee** [comment]
No - Don't have that file at all in either state (JWM or LXDE)..........
What should be providing it? (Slackware build)

**Comment by dimkr** [comment]
ptheme should create it if the GTK+ theme you use supports GTK+ 3, which is not the case as far as I know.

**Comment by peabee** [comment]
Should it be in rootfs-skeleton as a default similar to:
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/root/.gtkrc-2.0
?

It fixes the Abiword/Gnumeric icon issues but makes no difference to the PMusic icon problem...........

**Comment by peabee** [comment]
@zigbert 
could you provide more details of what needs to be done so that I can try it?

> I solved the icon-issue by copying icons to /usr/share/pixmaps
> there is a solution by dumping all icons into /usr/share/pixmaps/

**Comment by zigbert** [comment]
cp /usr/local/pmusic/themes/Nad5/icons/pMusic/scalable/* /usr/share/pixmaps/

**Comment by peabee** [comment]
copy added to relevant local builds
#3936 raised
