### ISSUE TITLE
firewall_ng and ip6tables: Failed match `state'

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#3937]
While starting firewall_ng in local builds of FossaPup64-9.6 and JammyPup64, I see the following:

```
Loading kernel modules ...
net.ipv4.tcp_syncookies = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.all.secure_redirects = 1
net.ipv4.conf.all.log_martians = 1
Flushing Tables ...
Create and populate custom rule chains ...

ip6tables v1.8.X (legacy): Couldn't load match `state':No such file or directory
```

If I understand correctly, when using iptables with extended packet matching, the use of 'state' is deprecated and now replaced by conntrack.

In my tests of firewall_ng, the match 'state' error does not appear after replacing the six instances of

**-m state --state**

with

**-m conntrack --ctstate**

If this correct?

**Comment by dimkr** [comment]
`zcat /proc/config.gz | grep CONFIG_NETFILTER_XT_MATCH_STATE` should say `CONFIG_NETFILTER_XT_MATCH_STATE=m`. If not, this kernel is misconfigured.

(But yes, `state` is deprecated - transitioning firewall_ng to conntrack is a good idea in general)

You can grab a working kernel from https://github.com/puppylinux-woof-CE/woof-CE/actions/workflows/kernel-kit.yml or https://github.com/puppylinux-woof-CE/woof-CE/actions/workflows/dpup-kernel.yml.

Or, you can grab a complete jammy64 build made in a clean build environment from https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/4189614407.

**Comment by radky2** [comment]
**@dimkr**

Thanks  for the quick response.

Yes, I see the following with my current kernel (updated yesterday) so the config seems OK.

```
# zcat /proc/config.gz | grep CONFIG_NETFILTER_XT_MATCH_STATE
CONFIG_NETFILTER_XT_MATCH_STATE=m
```

Thanks again!
