### ISSUE TITLE
Some USB creation tools can't make a UEFI bootable USB

### ISSUE THREAD

**Issue by okwizard** [puppylinux-woof-CE/woof-CE#3961]
USB installers like Rufus add their own EFI directory, installers that do not, like Unetbootin, cannot create a UEFI USB without the EFI directory in / of the ISO.  Solution is to add the EFI directory to the ISO.  This will improve the success rate for new users wanting to try and/or install Puppy.

**Comment by dimkr** [comment]
Tested with latest UNetbootin, this should be fixed now.

**Comment by okwizard** [comment]
@dimkr 
Thanks dima
wizard
