### ISSUE TITLE
Pulseaudio settings: failed persistence

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#3978]
@dimkr

F96-CE users continue to report failed persistence of pulseaudio settings after rebooting, though in part this may be due to users not following posted guidelines for manually saving audio settings to the pulseaudio configuration file.

In the following forum post, bigpup asks if updating pulseaudio could possibly enable automatic persistence of audio settings.

https://forum.puppylinux.com/viewtopic.php?p=84659#p84659

Your thoughts are  welcome.

Thanks

**Comment by dimkr** [comment]
Updating PulseAudio doesn't sound like a good option to me. I don't think that would help, and updating one (important) Ubuntu 20.04 component to a recent version sounds risky to me. Plus, the world has already moved on to PipeWire (so why invest in PulseAudio?), while the Ubuntu 20.04 base is too old to support PipeWire properly.

**Comment by radky2** [comment]
Your quick response is much appreciated.

Thanks !

**Comment by radky2** [comment]
@dimkr,

F96-CE will soon transition to a final release. Granted, major changes at this time are not possible but I would like to minimize future reports of failed persistence of audio settings after boot/reboot/restartX in the pulseaudio environment.

Users have reported that restoring the underlying ALSA audio settings at startup may be helpful. For example, placing the following code in /root/Startup will restore audio volume to prior levels for some users:

if [ -s /etc/asound.state ]; then
 sleep 5
 alsactl -f /etc/asound.state restore 2>/dev/null
fi

One user suggests this is the only way to achieve audio persistence on his system, but I don't know if resetting the ALSA configuration at startup is fully compatible with the F96 pulseaudio environment. If I understand correctly, the following link suggests some ALSA-dependent apps may access the sound card and subsequently restrict pulseaudio access to the same card.

https://wiki.archlinux.org/title/PulseAudio#ALSA

The above reference also recommends removing module snd_pcm_oss (which is active after booting F96) to prevent applications from using ALSA's OSS emulation and bypassing PulseAudio (thereby preventing other applications from playing sound).

Pulseaudio is a relatively new (and soon to be deprecated) concept in Puppy and a bit confusing to most users (including me). Unfortunately, after a brief test of F96, some users are frustrated by audio issues and simply move on to the next distro.

Likely, I will include 'alsactl -f /etc/asound.state restore' in /root/Startup and let the chips fall where they may.

Your thoughts are welcome.

Thanks
