### ISSUE TITLE
pmount problem with a largish number of partitions

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#4021]
Reported by proebler on the forum:
https://forum.puppylinux.com/viewtopic.php?p=87202#p87202

Seems to arise from:
https://github.com/puppylinux-woof-CE/woof-CE/commit/f19046bee040e3871ccb1518437fc1c2330fad2c

as he reports that the version of pmount before this commit works OK but all builds subsequent to this commit do not handle his partitions (9 named sda1 to sda10 less sda4) correctly e.g. sda6 sda8 sda9

His report:

> Exact sequence (after reboot) to confirm:
> - accessed a text file on sda8 to write the sequence
> - open pMount through 'drives' on desktop, situation is as described/shown in my previous post
> - unmount sda9 which makes it grayed out , NOTE: Geany gives me notice that the text file on sda8 is no longer accessible! trying to save fails (see screen shot).
> - in pMount, 'Show Location' for sda8 confirms that it is not accessible
> - unmount sda8 which makes it grayed out
> - mount sda8 mounts it immediately in new rox filer window, closed the window
> - mount sda9 mounts it immediately in new rox filer window, closed the window
> - 'Show Location' for sda9 opens sda8 in rox filer window i.e. in pMount sda9 has effectively become sda8
> - unmount sda8 which makes it grayed out, sda9 remains highlighted
> - 'Show Location" for sda9 opens sda8 in rox filer window , BUT it is an empty window without any files or directories, closed the window
> - unmount sda9 which makes it grayed out
> - mount sda9 > brings up error note (see screen shot) , but it has mounted and is accessible with 'Show Location'; pMount size field for sda8 has turned dark (from gray)
> - 'Show Location' for sda8 opens sda7 (!) in rox filer window
> - screen shot 'pMount-shows-sda8-as-sda9'
> - unmount sda9, pMount size field for sda8 remains dark, sda8 remains inaccessible from pMount.
> - get desktop to show all partitions so that I can mount sda8 to save the notes and move the screen shots there too
> - refresh pMount , it is correct for sda8 but again sda9 is false.

**Comment by dimkr** [comment]
@peabee I think you're on your own here, pmount is on its way out of my builds.

![image](https://user-images.githubusercontent.com/1471149/236222256-fda55e12-8b8f-43e2-938b-97f83a2b5b1a.png)

![image](https://user-images.githubusercontent.com/1471149/236222083-0b2cad22-c72b-46df-ab67-9b1816a0e165.png)

**Comment by peabee** [comment]
It is #2804 that is causing the problem.....
