### ISSUE TITLE
sfwbar launcher cannot be disabled without choosing apps first

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#4022]
1. Tick "Disable Launcher"
![image](https://user-images.githubusercontent.com/1471149/233935809-e9807d0b-5251-443e-ad7d-3290d99347cd.png)
2. Click OK
![image](https://user-images.githubusercontent.com/1471149/233935907-7cc6c909-776e-444f-89b5-93941d1f5afa.png)

**Comment by 01micko** [comment]
Yes a logic problem, will fix, but on holiday soon so may take a week or so.
