### ISSUE TITLE
sfwbar shrinks when launcher is disabled

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#4023]
1. Select items under  "Choose Puppy apps" (needed because #4022)
![image](https://user-images.githubusercontent.com/1471149/233936810-5bb10363-41b2-40b5-a6da-da588dafb87f.png)
2. Tick "Disable Launcher"
![image](https://user-images.githubusercontent.com/1471149/233936887-638007e4-a1b4-4699-8ced-047458a91485.png)
3. Click "OK"
4. Launcher is small and centered
![image](https://user-images.githubusercontent.com/1471149/233936736-2eef5e42-aa38-49a3-89d2-69ff9d2f27bd.png)

**Comment by 01micko** [comment]
Yeah it's broken; moving to `-GtkWidget-visible: true/false` 

Also will move to that for the battery widget.
