### ISSUE TITLE
Maximized applications cover sfwbar

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#4025]
When the panel is in the bottom layer, it's partially covered by applications:

![image](https://user-images.githubusercontent.com/1471149/233938334-e7bca83d-39d4-4221-9f4c-c46b53523937.png)

If the panel is moved to the top layer, the bottom border of maximized windows is cut.

**Comment by 01micko** [comment]
Might be an issue with the exclusive-zone algorithm. Also can happen with Xwayland apps.

**Comment by dimkr** [comment]
Issue is gone, but now there's a small gap here:

![image](https://user-images.githubusercontent.com/1471149/234245406-2c34b932-eda5-4ff6-9dbb-07101d6a3376.png)
