### ISSUE TITLE
Ubuntu updates repo database not being downloaded

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#4053]
Github builds of JammyPup32 & others
e.g. https://github.com/peabee/releases/actions/runs/5013082936

http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-i386/Packages.xz is not being downloaded even though it exists and can be downloaded directly in a browser.
As a result, for example, libgl1-mesa-dri is at version 20.3.5 when it should be version 22.2.5

Log for 0setup shows I think that the Packages.xz for updates is not being downloaded:

> Spider mode enabled. Check if remote file exists.
> 2023-05-18T10:36:59.4010047Z --2023-05-18 10:36:59--  http://0/
> 2023-05-18T10:36:59.4010675Z Resolving 0 (0)... 0.0.0.0
> 2023-05-18T10:36:59.4011698Z Connecting to 0 (0)|0.0.0.0|:80... failed: Connection refused.
> 2023-05-18T10:36:59.4012144Z Spider mode enabled. Check if remote file exists.
> 2023-05-18T10:36:59.4012937Z --2023-05-18 10:36:59--  http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-i386/Packages.xz
> 2023-05-18T10:36:59.4024105Z Resolving archive.ubuntu.com (archive.ubuntu.com)... 91.189.91.39, 91.189.91.38, 185.125.190.36, ...
> 2023-05-18T10:36:59.4835479Z Connecting to archive.ubuntu.com (archive.ubuntu.com)|91.189.91.39|:80... connected.
> 2023-05-18T10:36:59.5639881Z HTTP request sent, awaiting response... 200 OK
> 2023-05-18T10:36:59.5641081Z Length: 1646812 (1.6M) [application/x-xz]
> 2023-05-18T10:36:59.5641668Z Remote file exists.

**Comment by peabee** [comment]
Same is happening for JammyPup64:
Updates has 22.2.5
https://ubuntu.pkgs.org/22.04/ubuntu-updates-main-amd64/libgl1-mesa-dri_22.2.5-0ubuntu0.1~22.04.1_amd64.deb.html

but 1download log shows that 22.01.1 is being downloaded
https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/4986652383

> 2023-05-19T06:09:27.0373198Z * Downloading libgl1-mesa-dri_22.0.1-1ubuntu2_amd64.deb
> 2023-05-19T06:09:27.0430706Z   - from http://archive.ubuntu.com/ubuntu/pool/main/m/mesa

**Comment by dimkr** [comment]
```
Spider mode enabled. Check if remote file exists.
2023-05-19T06:05:55.2897374Z --2023-05-19 06:05:55--  http://0/
2023-05-19T06:05:55.2898024Z Resolving 0 (0)... 0.0.0.0
2023-05-19T06:05:55.2900179Z Connecting to 0 (0)|0.0.0.0|:80... failed: Connection refused.
```
