### ISSUE TITLE
Dpup bdrv: broken symlinks

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#4086]
In the bdrv of BW64 and Vanilla Dpup there are multiple symlinks in /etc and /usr that are broken in the running Pup.

Are these symlinks necessary, or is it possible to automate removal during the Woof-CE build?

Thanks

---

/etc/alternatives/awk.1.gz
/etc/alternatives/builtins.7.gz
/etc/alternatives/c89.1.gz
/etc/alternatives/c99.1.gz
/etc/alternatives/lzcat.1.gz
/etc/alternatives/lzma.1.gz
/etc/alternatives/mt.1.gz
/etc/alternatives/nawk.1.gz
/etc/alternatives/open.1.gz
/etc/alternatives/pager.1.gz
/etc/alternatives/pinentry.1.gz
/etc/alternatives/regulatory.db
/etc/alternatives/regulatory.db.p7s
/etc/alternatives/rmt
/etc/alternatives/rmt.8.gz
/etc/alternatives/start-here-16.png
/etc/alternatives/start-here-22.png
/etc/alternatives/start-here-24.png
/etc/alternatives/start-here-256.png
/etc/alternatives/start-here-32.png
/etc/alternatives/start-here-48.png
/etc/alternatives/start-here.svg
/etc/alternatives/unclutter.1.gz
/etc/alternatives/unlzma.1.gz
/etc/alternatives/which.1.gz
/etc/alternatives/which.de1.gz
/etc/alternatives/which.es1.gz
/etc/alternatives/which.fr1.gz
/etc/alternatives/which.it1.gz
/etc/alternatives/which.ja1.gz
/etc/alternatives/which.pl1.gz
/etc/alternatives/which.sl1.gz
/etc/dpkg/origins/default

/usr/sbin/rmt

**Comment by dimkr** [comment]
You can break apt if you remove these, and symlinks are tiny. Is it worth it?

**Comment by radky2** [comment]
Thanks for the quick reply !
