### ISSUE TITLE
Peasyport 2.8w in puppy-noarch-official

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#4129]
https://forum.puppylinux.com/viewtopic.php?p=95501#p95501

In the above link, forum member rcrsn51 (author of PeasyPort) has questioned the Woof-CE modifications (without annotations) of PeasyPort 2.8w in Packages-puppy-noarch-official (see below).

Woof-CE commit:
https://github.com/puppylinux-woof-CE/woof-CE/commit/8b3f0ed3a26fe802b9698325b3aff3d532f12603

The original PeasyPort by rcrsn51 is available here:
https://oldforum.puppylinux.com/viewtopic.php?t=79913

Is Peasyport 2.8w appropriate for Packages-puppy-noarch-official ?

**Comment by peabee** [comment]
By "appropriate" are you suggesting it should be removed? Quite a few builds include peasyport and would presumably fail if it were removed:
https://github.com/search?q=repo%3Apuppylinux-woof-CE%2Fwoof-CE+path%3A%2F%5Ewoof-distro%5C%2F%2F+peasyport&type=code

What needs to happen to make it "appropriate"? wdlkmpx committed on Oct 3, 2019 and has not been seen for some considerable time.

**Comment by dimkr** [comment]
> the Woof-CE modifications

What do you mean by that? PeasyPort is not part of woof-CE.

**Comment by radky2** [comment]
I agree that PeasyPort 2.8w is a very useful application and (in my opinion) should remain an option for Puppy builds.

By "Woof-CE modifications" I was referring (perhaps incorrectly) to the fact that peasyport 2.8w is a revision of rcrsn51's original application, and this revision is now an accepted Woof-CE commit which is available in Packages-puppy-noarch-official.


My question was intended only to highlight rcrsn51's concern and forum comments about the distribution of PeasyPort 2.8w which rcrsn51 states "claims to be mine but has a number of anonymous, un-annotated changes" and he further informs Puppy forum members that "I (rcrsn51) would not trust it" and "I (rcrsn51) have reported this issue in other Puppies but was ignored".
