### ISSUE TITLE
sfs_load.overlay: Rox right-click issue

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#4132]
Testing sfs_load.overlay and ROX-Filer context menu in Pupmode 13.

On first r-click of an extra SFS file, after choosing the sfs_load menu option I see three sequential dialog options to load, queue or mount the SFS.

If I respond 'No' to the first two dialogs, and 'Yes' to the mount dialog, thereafter when I r-click the SFS there is only the option to queue (no options to unmount or load dynamically).

Is this expected behavior, or am I using this feature incorrectly ?

**Comment by dimkr** [comment]
sfs_load.overlay can't distinguish between a mounted SFS and a loaded SFS (without a long operation that checks if all symlinks are in place).

Therefore, it only offers you to load a SFS if it's not mounted. Unmount the SFS, then click it again, and it will offer you to load it.

**Comment by radky2** [comment]
Thanks dimkr !
