### ISSUE TITLE
Issue: sfs_load.overlay and PupMode 12 (PR #4131)

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#4133]
Testing sfs_load.overlay and PupMode 12 in BW64

Pentium(R) Dual-Core CPU T4400 @ 2.20GHz, 768 MB savefile, 3 GB RAM

1 - Used ROX right-click menu to select a relatively large (178 MB) libreoffice.sfs in /mnt/home.

2 - Selected the options to load (dynamically) and queue for loading on reboot.

3 - Loading the libreoffice.sfs dynamically required about 3 minutes, but loaded correctly and the sfs system symlinks point to MNT in /initrd/pup_ro3.

4 - Rebooted and files of the libreoffice.sfs are now mounted in /initrd/pup_ro8 but the sfs system symlinks are broken and point to an empty /initrd/pup_ro3.

5 - Again ROX right-click menu, selected unqueue libreoffice.sfs, then rebooted.  After rebooting, /initrd/pup_ro3 and /initrd/pup_ro8 are empty but the broken system sfs symlinks remain unchanged.

# losetup
/dev/loop1: [0021]:11 /initrd/mnt/tmpfs/devx_dpup_10.0.1.sfs
/dev/loop8: [0021]:39 /initrd/mnt/tmpfs/LibreOffice-4.3.2_en-US_xz.sfs
/dev/loop6: [0021]:9 /initrd/mnt/tmpfs/adrv_dpup_10.0.1.sfs
/dev/loop4: [0021]:12 /initrd/mnt/tmpfs/zdrv_dpup_10.0.1.sfs
/dev/loop2: [0021]:14 /initrd/mnt/tmpfs/kbuild-6.1.37.sfs
/dev/loop0: [0021]:3 /initrd/mnt/tmpfs/puppy_dpup_10.0.1.sfs
/dev/loop9: [2050]:13 /initrd/mnt/dev_save/LibreOffice-4.3.2_en-US_xz.sfs
/dev/loop7: [2050]:1310747 /initrd/mnt/dev_save/puppy1/dpupsave-test.3fs
/dev/loop5: [0021]:10 /initrd/mnt/tmpfs/bdrv_dpup_10.0.1.sfs
/dev/loop3: [0021]:13 /initrd/mnt/tmpfs/fdrv_dpup_10.0.1.sfs

**Comment by dimkr** [comment]
> Testing sfs_load.overlay and PupMode 12 in BW64

Did you also apply the rc.shutdown change from that PR?

**Comment by radky2** [comment]
@dimkr

I previously failed to include the updated rc.sysinit and rc. shutdown in my BW64 test bed. I apologize for that mistake.

Starting again, I deleted my prior 768 MB savefile and created a new 1 GB savefile, and then tested the most recent PRs for sfs_load.overlay, rc.sysinit, rc.shutdown, and init in Pupmode 12. I also double-checked to confirm the above updated files are indeed in the savefile after rebooting.

In the ROX right-click menu, when I choose load (dynamically) the libreoffice.sfs loads correctly and the sfs is mounted in /initrd/pup_ro4. However, after choosing queue and then rebooting, subsequent loading of the libreoffice.sfs fails for me as follows:

1 - /initrd/pup_ro4 is present but empty
2 - The libreoffice.sfs is now mounted in /initrd/pup_ro8 and the contents are confirmed identical to the original libreoffice.sfs.
3 - In ROX filer, the directories and subdirectories of the libreoffice.sfs are visible in the running Puppy file system, but no system files are linked (not even broken symlinks) to /initrd/pup_ro4 or /initrd/pup_ro8.
4 - I unqueued the libreoffice.sfs and rebooted, then queued again and rebooted. Same results as above.

--

# losetup
/dev/loop1: [0021]:11 /initrd/mnt/tmpfs/devx_dpup_10.0.1.sfs
/dev/loop8: [0021]:39 /initrd/mnt/tmpfs/LibreOffice-4.3.2_en-US_xz.sfs
/dev/loop6: [0021]:9 /initrd/mnt/tmpfs/adrv_dpup_10.0.1.sfs
/dev/loop4: [0021]:12 /initrd/mnt/tmpfs/zdrv_dpup_10.0.1.sfs
/dev/loop2: [0021]:14 /initrd/mnt/tmpfs/kbuild-6.1.37.sfs
/dev/loop0: [0021]:3 /initrd/mnt/tmpfs/puppy_dpup_10.0.1.sfs
/dev/loop7: [2050]:1310747 /initrd/mnt/dev_save/puppy1/dpupsave-test.3fs
/dev/loop5: [0021]:10 /initrd/mnt/tmpfs/bdrv_dpup_10.0.1.sfs
/dev/loop3: [0021]:13 /initrd/mnt/tmpfs/fdrv_dpup_10.0.1.sfs

--

/etc/rc.d/BOOTCONFIG:

EXTRASFSLIST='LibreOffice-4.3.2_en-US_xz.sfs'
PREVUNIONRECORD='dpupsave-test.3fs puppy_dpup_10.0.1.sfs devx_dpup_10.0.1.sfs kbuild-6.1.37.sfs fdrv_dpup_10.0.1.sfs zdrv_dpup_10.0.1.sfs bdrv_dpup_10.0.1.sfs adrv_dpup_10.0.1.sfs'
LASTUNIONRECORD='dpupsave-test.3fs puppy_dpup_10.0.1.sfs devx_dpup_10.0.1.sfs kbuild-6.1.37.sfs fdrv_dpup_10.0.1.sfs zdrv_dpup_10.0.1.sfs bdrv_dpup_10.0.1.sfs adrv_dpup_10.0.1.sfs LibreOffice-4.3.2_en-US_xz.sfs'

The /var/lib/sfs_load.overlay/ folder is empty.

--

 Likely, I'm doing something incorrectly but will continue testing.

**Comment by dimkr** [comment]
Please try again, this time with 2153bb3 and 69fb2d9 applied.

**Comment by dimkr** [comment]
I reproduced the same scenario (dynamically loaded a SFS, queued it for loading, then simulated power failure using `busybox poweroff -f`), and things work fine with 69fb2d9. The symlinks are cleaned up before loading, the SFS is added as a layer and the application is visible in the menu.

**Comment by radky2** [comment]
@dimkr

1 - Deleted the old BW64 savefile and created a new  1 GB savefile, then rebooted (Pupmode 12)
2 - Applied the most recent PR updates for sfs_load.overlay, rc.sysinit, rc.shutdown and init. This includes all updated PRs up to and including d266d8f.
3 - Rebooted, then ROX-Filer right-click -> mounted libreoffice.sfs dynamically
4 - The libreoffice.sfs is mounted in /initrd/pup_ro3 and all sfs symlinks are created correctly in the running file system. Everything looks good at this point.
5 - ROX-Filer right-click -> queued libreoffice.sfs, then rebooted
6 - After rebooting, /initrd/pup_ro3 is no longer present. The libreoffice.sfs is now mounted in /initrd/pup_ro8.
7 - The libreoffice.sfs has 3 top-level directories (opt, root, usr). In the running file system, I see the following:

In /opt and /root, the libreoffice.sfs directories are visible but are empty, i.e. there are no sfs file symlinks to /initrd/pup_ro8.

In /usr the sfs files were symlinks when the sfs was loaded dynamically but are now actual files identical to the files in the sfs (not symlinks).

Since everything is working OK for you, I assume my problem is a local misconfiguration. I will continue testing later today.

**Comment by dimkr** [comment]
> In /usr the sfs files were symlinks when the sfs was loaded dynamically but are now actual files identical to the files in the sfs (not symlinks).

Symlinks are only used to simulate dynamic loading, **not** for loading at boot time.

**Comment by radky2** [comment]
@dimkr

Apparently something  in my older libreoffice.sfs conflicts with sfs_load.overlay.

After switching to an updated libreoffice.sfs (7.5.2), the /opt, /root and /usr directories in the running file system now populate correctly after queueing and rebooting in Pupmode 12.

Thanks for your patience.

**Comment by dimkr** [comment]
> After switching to an updated libreoffice.sfs (7.5.2), the /opt, /root and /usr directories in the running file system now populate correctly after queueing and rebooting in Pupmode 12.

To make it clear - the handling of SFS queued for loading at boot time hasn't changed.
