### ISSUE TITLE
kernel 6.1.52 regressions

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#4151]
@dimkr

Several reports suggest regressions in the 6.1.52 kernel.

Any impact on the dpup 6.1.52 kernel ?

https://github.com/RadeonOpenCompute/ROCm/issues/2451
https://groups.google.com/g/linux.debian.kernel/c/khMR1un3WaQ
https://lore.kernel.org/lkml/ZQPxuZ2tifa9bQKJ@gcabiddu-mobl1.ger.corp.intel.com/T/

Thanks

**Comment by dimkr** [comment]
Maybe, but even if this update introduces regressions, the Debian kernel maintainers will probably fix them in another update.

**Comment by radky2** [comment]
Thanks for the quick response.
