### ISSUE TITLE
kernel-kit build (5.4.x-x86_64, ubuntu:focal) fail

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#4166]
Strangely, 64-bit failed with errors whereas 32-bit built successfully

kernel-kit #215
build (5.4.x-x86_64, ubuntu:focal)
failed yesterday in 27m 41s

```
  CC [M]  drivers/net/dsa/mv88e6xxx/chip.o
drivers/net/dsa/mv88e6xxx/chip.c: In function 'mv88e6xxx_hardware_reset':
drivers/net/dsa/mv88e6xxx/chip.c:2153:4: error: implicit declaration of function 'mv88e6xxx_g2_eeprom_wait'; did you mean 'mv88e6xxx_g2_pvt_write'? [-Werror=implicit-function-declaration]
 2153 |    mv88e6xxx_g2_eeprom_wait(chip);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~
      |    mv88e6xxx_g2_pvt_write
  CC [M]  drivers/media/pci/ddbridge/ddbridge-ci.o
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:262: drivers/net/dsa/mv88e6xxx/chip.o] Error 1
make[3]: *** [scripts/Makefile.build:497: drivers/net/dsa/mv88e6xxx] Error 2
make[2]: *** [scripts/Makefile.build:497: drivers/net/dsa] Error 2
make[1]: *** [scripts/Makefile.build:497: drivers/net] Error 2
make[1]: *** Waiting for unfinished jobs....

```

**Comment by peabee** [comment]
kernel-kit #216
Annotations
1 error
build (5.4.x-x86_64, ubuntu:focal)
Process completed with exit code 1.

**Comment by peabee** [comment]
ubuntu-focal64 #13
fails consequentially

**Comment by dimkr** [comment]
If nobody is willing to fix 5.4.x and nobody is building a Puppy with this kernel version anymore, maybe it's time to retire 5.4.x and 4.19.x

**Comment by peabee** [comment]
I'd vote for that.......
although it is strange that the 32-bit version is building OK whereas the 64-bit is failing......
the system builds that use 4.19 and 5.4 would have to be switched to later kernels or also consigned to the trash can....
FossaPup64 is still pretty active on the forum - but not via Github builds

**Comment by dimkr** [comment]
The selection of drivers is different (AFAIK) and 32 bit kernels are so much likely to break, because most distros don't build them anymore and few users use them. (Even if the build passes, they get very little testing.)
