### ISSUE TITLE
/opt is being deleted in overlayfs build after extra sfs install

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#4169]
@dimkr ?
BookwormPup32 with a savefolder and an extra sfs with /opt in it loaded - after reboot there is no longer a /opt directory.....
![Screenshot](https://github.com/puppylinux-woof-CE/woof-CE/assets/5926865/11bba859-93a2-4bf3-a568-e89a818713cb)

The savefolder upper directory shows /opt has been replaced by "something else":
![Screenshot2](https://github.com/puppylinux-woof-CE/woof-CE/assets/5926865/d0129f0b-cf99-43a8-8834-f7524aec57b5)

**Comment by peabee** [comment]
Further info: BookwormPup64 with a different sfs (but containing /opt) seems to work correctly.

Will make a small test sfs that can be installed on both systems.........

**Comment by dimkr** [comment]
The "file" in the save is a whiteout. When you unload a SFS, sfs_load.overlay deletes empty leftover directories, and /opt is deleted because it's 1. present in the SFS and 2. empty.

If you load another SFS that contains /opt, install a package that contains /opt or simply create /opt (through a file manager or `mkdir /opt`, doesn't matter), you will see /opt again.

**Comment by peabee** [comment]
The extra sfs is loaded by putting it into the frugal install directory and clicking on it.
The extra sfs is never unloaded.
A possible difference between BW64 and BW32 is that BW64 has items in /opt in the puppy.sfs whereas in BW32 /opt is empty....??

**Comment by peabee** [comment]
Confirmed that putting some dummy content into /opt in the main system sfs for BW32 stops /opt being erased after an extra sfs with /opt content is loaded and queued and rebooted.

**Comment by dimkr** [comment]
> A possible difference between BW64 and BW32 is that BW64 has items in /opt in the puppy.sfs whereas in BW32 /opt is empty....??

Yes, sfs_load.overlay removes every directory present if the SFS during unloading, if it's empty. If /opt was empty before the SFS was loaded **and** the SFS contains /opt, /opt will be deleted when you unload the SFS.

**Comment by peabee** [comment]
Bit confused about mention of SFS unloading as the activity was not unloading - it was loading and queuing an sfs with /opt contents for use after a reboot - which couldn't happen because /opt was "deleted".
Does "unloading" somehow occur as part of queuing and rebooting??
Will try the proposed fix.

**Comment by dimkr** [comment]
The leftover directory cleanup procedure happens only if:
1. You unload a SFS, or
2. You use PUPMODE 12 and reboot while a SFS loaded by sfs_load is still loaded, or
3. You use PUPMODE 12 and power is lost (or disk corruption, or something else) while a SFS loaded by sfs_load is loaded, then boot Puppy again
