### ISSUE TITLE
JammyPup64: python giving errors when devx not loaded

### ISSUE THREAD

**Issue by lakshayrohila** [puppylinux-woof-CE/woof-CE#4182]
![Screenshot_20231112_202452](https://github.com/puppylinux-woof-CE/woof-CE/assets/103126231/a1d9e7ee-7871-46af-8035-2478f4883234)

This is the output of `apt update` on the first run of JammyPup. Although this image shows the output of `apt update` only, but I've tried with multiple `apt` commands such as install and others as well, and all return with the same error.

Then I load devx and this error goes away.

So, my instinct is that this error can be resolved by redirecting the dev contents of python to exe in DISTRO_PKGS_SPECS. I'll try doing that and see if it fixes it.

**Comment by lakshayrohila** [comment]
> So, my instinct is that this error can be resolved by redirecting the dev contents of python to exe in DISTRO_PKGS_SPECS. I'll try doing that and see if it fixes it.

I tried that, but that does not fix the issue. I then ran the command `python` and I got the same problem.

**So, it seems that `apt` is not causing the issue, but is `python`.**

Maybe, this is just a problem related to python's configuration (?), or maybe some library required for python to run is in devx (?) and needs to be redirected to main iso.

**Comment by dimkr** [comment]
Two solutions:

1.

```
yes|python|python-is-python3,python3,libpython3.10|exe,dev,doc,nls||deps:yes
```

Instead of:

```
yes|python|python-is-python3,python3|exe,dev,doc,nls||deps:yes
```

2.

Moving this line to the end of the package list:

```
yes|gdb|gdb,libboost-regex1.74.0|exe>dev,dev,doc,nls||deps:yes
```

gdb depends on libpython3.10 and this library is redirected to devx together with gdb, because gdb comes before python in the package list.
