### ISSUE TITLE
Changes needed for node20 ?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#4226]
What do we need to do?

https://github.com/actions/download-artifact/releases/tag/v4.0.0

> What's Changed
> The release of upload-artifact@v4 and download-artifact@v4 are major changes to the backend architecture of Artifacts. They have numerous performance and behavioral improvements.
> 
> However, this is **a major update that includes breaking changes**. Artifacts created with versions v3 and below are not compatible with the v4 actions. Uploads and downloads must use the same major actions versions. There are also key differences from previous versions that may require updates to your workflows.

Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, dawidd6/action-download-artifact@v2, actions/upload-artifact@v3.

Please update the following actions to use Node.js 20: actions/download-artifact@v3, softprops/action-gh-release@v1.

**Comment by dimkr** [comment]
You should do exactly what the warning tells you to do, change `upload-artifact@v3` to `upload-artifact@v4` and so on. But read the changelog/release notes for each action first, especially the "breaking changes" part, because maybe you'll need to change input parameters too.

**Comment by peabee** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/pull/4227
