### ISSUE TITLE
Deadbeef petbuild - help misplaced

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#4238]
The Deadbeef help files from petbuild reside in /usr/share/doc/deadbeef
they therefore get put into the DOCX .sfs whereas they are needed in the main puppy .sfs

Is there a mechanism to redirect them to the main .sfs??

**Comment by lakshayrohila** [comment]
According to this clause in `support/petbuilds.sh`:

https://github.com/puppylinux-woof-CE/woof-CE/blob/f0755e696904f10c6103af897a493db5760d6337/woof-code/support/petbuilds.sh#L326

All the doc dirs are automatically copied to docx - the behaviour you are seeing. AFAIK, `petbuild` is run before this clause `pinstall.sh` is run after this clause.

So, you can manually redirect / move your docs into some temporary location which will remain in the main sfs, and then move the docs from that temporary location in the location they needed to be.

---

I have doubt about this though, maybe `pinstall.sh` is also run before this clause. Please check.

**Comment by lakshayrohila** [comment]
Note that even after this, your docdir might get removed due to this clause:

https://github.com/puppylinux-woof-CE/woof-CE/blob/f0755e696904f10c6103af897a493db5760d6337/woof-code/3builddistro#L507

So, you will have to add your docdir in the exceptions list the next line provides.

**Comment by peabee** [comment]
I can do a build-specific fix with hack code in :
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/x86/debian/dpupbw32/_00build.conf#L176

What is really needed is for petbuilds to be specified in :
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/x86/debian/dpupbw32/DISTRO_PKGS_SPECS-debian-bookworm#L30

rather than separated out in _00build.conf

and to obey something like:
petb|deadbeef|deadbeef|exe,dev,doc>exe,nls

**Comment by peabee** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/commit/4c8a372cd9bec68d687d2f8018e7121d5563efca

# Deadbeef help fix 140224
cp -f ../../petbuild-output/deadbeef-latest/usr/share/doc/deadbeef usr/share/doc

**Comment by lakshayrohila** [comment]
> and to obey something like:
petb|deadbeef|deadbeef|exe,dev,doc>exe,nls

This is more of a 'building mechanism' type issue (improvement?) then, rather than a single petbuild issue. Maybe, you should change the title to indicate that.

**Comment by lakshayrohila** [comment]
@peabee, I've opened #4252 to signify the real issue. Since `Deadbeef petbuild - help misplaced` issue is already fixed (as described in the earlier comment), I think it is better to close this issue.
