### ISSUE TITLE
Add new mechanism to add petbuilds from `DISTRO_PKGS_SPECS-*`

### ISSUE THREAD

**Issue by lakshayrohila** [puppylinux-woof-CE/woof-CE#4252]
Refer to https://github.com/puppylinux-woof-CE/woof-CE/issues/4238#issuecomment-1943441740 (issue #4238).

@peabee's suggestion for the syntax is something like this:
```
petb|<petbuild_name>|<additional_compat_repo_deps>|exe,doc,dev,nls||<deps:yes>
```

This makes it not just a simple re-implementation of the mechanism for adding petbuilds, but it will also add the functionality to add required dependencies on the same line and allow redirection of petbuild outputs.

**Comment by peabee** [comment]
Simpler solution??
Just move the PETBUILDS= line(s) from _00build.conf to DISTRO_PKGS_SPECS-*

as 3builddistro calls _00build.conf at line 11 and then DISTRO_PKGS_SPECS-* at line 14 then:
a. the petbuilds will still be actioned
b. all configuration info (apart from rootfs-packages.conf) will be in DISTRO_PKGS_SPECS-* which is much better?

I will try this approach.

**Comment by peabee** [comment]
Yep - that works. Will gradually change my builds to this format. Closing.
