### ISSUE TITLE
trixie64 doesn't build because of libfuse2 being renamed for t64

### ISSUE THREAD

**Issue by IdfbAn** [puppylinux-woof-CE/woof-CE#4274]
There might be other packages too, but I'm not sure.
https://github.com/IdfbAn/woof-CE/actions/runs/8766666131/job/24059047439#step:12:827
https://packages.debian.org/trixie/libfuse2t64

**Comment by peabee** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/pull/4275/commits/e1dea0f3d0af2be18d346af9051b8bfa389ff8b9
