### ISSUE TITLE
debdb2pupdb and find_cat depends on system-wide /usr/local/petget/categories.dat

### ISSUE THREAD

**Issue by jamesbond3142** [puppylinux-woof-CE/woof-CE#4290]
`debdb2pupdb` and `find_cat` are the two core programs used in `0setup` to convert foreign package database format to puppy database format. 

It turns out that both `debdb2pupdb` and `find_cat` have an unlisted dependency on system-wide /usr/local/petget/categories.dat (as the file itself says):
```
#130124 format modified to be bash-include compatible.
#130124 loaded at runtime by 'debdb2pupdb.bac' and 'find_cat.bac' in Woof.
```

But system-wide  `/usr/local/petget/categories.dat` only exists in Puppy Linux. It doesn't exist in other distros. Hence, running `debdb2pupdb` and `find_cat` will fail. In other words, running `0setup` will fail, without any clear error message. Instead, it will only say:
```
FATAL: failed find to find $pkgname
```
which is very _misleading_. The cause of this "FATAL" message is because the converted pup package database is _empty_, thanks to debdb2pupdb and find_cat failing silently.

This dependency on `/usr/local/petget/categories.dat` is not necessary, because woof-CE itself carries this file in `./woof-code/rootfs-skeleton/usr/local/petget/categories.dat`. 

My suggestion is to modify merge2out to copy `./woof-code/rootfs-skeleton/usr/local/petget/categories.dat` and put it to 'woof-out' directory, and to modify `find_cat`, `debdb2pupdb` (and possible other package database converter that depends on categories.dat, so far I've only tested `debdb2pupdb`) to use the `./categories.dat` inside `woof-out` instead of reaching out to system-wide `/usr/local/petget/categories.dat`.

If this is done, then `0setup` will run on any reasonable Linux distro. This will be the first step to enable building Puppies on mainstream distros.  I'd be happy to submit a PR but I can't see the source for find_cat and debdb2pupdb.

**Comment by dimkr** [comment]
> I'd be happy to submit a PR but I can't see the source for find_cat and debdb2pupdb.

https://github.com/puppylinux-woof-CE/initrd_progs/blob/21e34016d252e40524a23639ba44c6b72cbde09a/pkg/w_apps_static/w_apps/debdb2pupdb.c
https://github.com/puppylinux-woof-CE/initrd_progs/blob/21e34016d252e40524a23639ba44c6b72cbde09a/pkg/w_apps_static/w_apps/find_cat.c

**Comment by jamesbond3142** [comment]
Thanks. Ah, so you want me to apply the patches there, or build the binaries and apply it here?

**Comment by dimkr** [comment]
I don't want you to do anything, I no longer use those 😸 

I guess it's up to @peabee

**Comment by jamesbond3142** [comment]
LOL all right. I'll open a PR for both source and binary. I can't do the ARM binary though, so I'll let it pass. I don't know anyone who still builds the ARM platform anyway.
