### ISSUE TITLE
Updating pet repos in woof_gui messes up DISTRO_PET_REPOS

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#452]
The problem is in woof_gui_tabs lines 342-348.
Building slacko "Packages-puppy-${xDISTRO_COMPAT_VERSION}-official" becomes "Packages-puppy-14.0-official" instead of the correct "Packages-puppy-slacko14-official", thus Packages-puppy-slacko14-official is missing from PACKAGELISTS_PET_ORDER after the update.

**Comment by mavrothal** [comment]
Where do we stand on this?

**Comment by 01micko** [comment]
Don't know. CatDude is building a 14.0 and had a couple of issues which I think are ironed out. Haven't heard from him for a couple of days so I'll let you know when I hear from him.

**Comment by wdlkmpx** [comment]
This is already fixed. You cannot edit DISTRO_PET_REPOS with the GUI, it will open the file for you to edit it. And with the hacks i added. It looks like a normal .conf file.
