### ISSUE TITLE
New kernel setup brakes booting from VFAT USB drives with non-english 'pkeys'

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#505]
When using the "huge kernel" with no modules in initrd,  booting with a pkeys parameter from a usb drive with a vfat file system will fails since it may need CODEPAGE_{850,852} and ISO8859_2 that are now in zdrv and can not be modprobe'ed.
Need to be built in the kernel and not as modules.
Alternatively we may try to mount zdrv in the initfs early and have everything available, though finding and mounting the zdrv may need codepage when in a vfat usb...

**Comment by mavrothal** [comment]
This is fixed now with the new kernel configs. Isn't it?

**Comment by 01micko** [comment]
Should be..

**Comment by mavrothal** [comment]
The modules are indeed built in the kernel. So should be OK.

**Comment by 01micko** [comment]
Ah, yes, I have a check.. just testing kernel-kit from `fdrv` for sanity...

```
================================     INFO      ================================

The 'huge' kernel builds require a number of drivers built into the kernel
image (vmlinuz in x86/x86_64; zImage, uImage or kernel.img in ARM). Things
that must be builtin are filesystems (ext2/3/4, f2fs, NTFS, FAT and others 
which you may want to support as a boot partition) , AUFS, NLS support, 
keyboard drivers and possibly others.
eg:
CONFIG_AUFS_FS=y
===============================================================================
CONFIG_AUFS_FS=y is ok
CONFIG_NLS_CODEPAGE_850=y is ok
Press ENTER to begin

```
