### ISSUE TITLE
Improve scripts readability & speed

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#512]
I usually edit the code and replace spaces with tabs. That way the code looks beautiful.. 

I can edit most scripts so everyone can understand the code better, but I need approval. I'm just learning how to use git, I might get lost

We should replace sed, cut, etc .. where possible. When it comes to process one line... it's better to use 'case' or '[[ ]]', bash also supports regular expressions ...

**Comment by technosaurus** [comment]
perhaps we need a coding and style guide in the docs?
along with an uncrustify config file?

**Comment by mavrothal** [comment]
can't we use one of the ones in the net?
I think one problem is breaking gtkdialog long text lines.
Any chance to modify gtkdialog code to accept escape characters?
