### ISSUE TITLE
Modify some folders in packages-templates 

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#546]
Though Puppy is different, it should try to look as normal as possible.

- woof-CE/woof-code/packages-templates/ 

coreutils, util-linux, create extremely cutdown packages.

I find MANY tutorials and solutions that use utilities from those packages. Also there is a fatal flaw: there is a 'truncate' utility, that I really find useful, but it's different from the one in Puppy, and both share the same path.

busybox also has a lot of applets, you can create symlinks this way:

sh-4.3# busybox --list | while read applet ; do  if ! which $applet >/dev/null ; then  ln -sfv ../../bin/busybox /usr/bin/$applet ; fi ; done 
`/usr/bin/add-shell' -> `../../bin/busybox'
`/usr/bin/adjtimex' -> `../../bin/busybox'
`/usr/bin/arp' -> `../../bin/busybox'
`/usr/bin/arping' -> `../../bin/busybox'
`/usr/bin/bootchartd' -> `../../bin/busybox'
`/usr/bin/brctl' -> `../../bin/busybox'
`/usr/bin/catv' -> `../../bin/busybox'
`/usr/bin/chpst' -> `../../bin/busybox'
`/usr/bin/conspy' -> `../../bin/busybox'
`/usr/bin/cttyhack' -> `../../bin/busybox'
`/usr/bin/dnsd' -> `../../bin/busybox'
`/usr/bin/envdir' -> `../../bin/busybox'
`/usr/bin/envuidgid' -> `../../bin/busybox'
`/usr/bin/ether-wake' -> `../../bin/busybox'
`/usr/bin/fakeidentd' -> `../../bin/busybox'
`/usr/bin/fatattr' -> `../../bin/busybox'
`/usr/bin/ftpd' -> `../../bin/busybox'
`/usr/bin/hush' -> `../../bin/busybox'
`/usr/bin/ifenslave' -> `../../bin/busybox'
`/usr/bin/inetd' -> `../../bin/busybox'
`/usr/bin/killall5' -> `../../bin/busybox'
`/usr/bin/linuxrc' -> `../../bin/busybox'
`/usr/bin/lpd' -> `../../bin/busybox'
`/usr/bin/makemime' -> `../../bin/busybox'
`/usr/bin/mt' -> `../../bin/busybox'
`/usr/bin/nanddump' -> `../../bin/busybox'
`/usr/bin/nandwrite' -> `../../bin/busybox'
`/usr/bin/nbd-client' -> `../../bin/busybox'
`/usr/bin/nmeter' -> `../../bin/busybox'
`/usr/bin/ntpd' -> `../../bin/busybox'
`/usr/bin/patch' -> `../../bin/busybox'
`/usr/bin/popmaildir' -> `../../bin/busybox'
`/usr/bin/raidautorun' -> `../../bin/busybox'
`/usr/bin/reformime' -> `../../bin/busybox'
`/usr/bin/remove-shell' -> `../../bin/busybox'
`/usr/bin/runsv' -> `../../bin/busybox'
`/usr/bin/runsvdir' -> `../../bin/busybox'
`/usr/bin/rx' -> `../../bin/busybox'
`/usr/bin/sendmail' -> `../../bin/busybox'
`/usr/bin/setuidgid' -> `../../bin/busybox'
`/usr/bin/slattach' -> `../../bin/busybox'
`/usr/bin/smemcap' -> `../../bin/busybox'
`/usr/bin/softlimit' -> `../../bin/busybox'
`/usr/bin/sv' -> `../../bin/busybox'
`/usr/bin/svlogd' -> `../../bin/busybox'
`/usr/bin/tcpsvd' -> `../../bin/busybox'
`/usr/bin/telnetd' -> `../../bin/busybox'
`/usr/bin/tftpd' -> `../../bin/busybox'
`/usr/bin/tunctl' -> `../../bin/busybox'
`/usr/bin/ubiattach' -> `../../bin/busybox'
`/usr/bin/ubidetach' -> `../../bin/busybox'
`/usr/bin/ubimkvol' -> `../../bin/busybox'
`/usr/bin/ubirmvol' -> `../../bin/busybox'
`/usr/bin/ubirsvol' -> `../../bin/busybox'
`/usr/bin/ubiupdatevol' -> `../../bin/busybox'
`/usr/bin/udpsvd' -> `../../bin/busybox'
`/usr/bin/vconfig' -> `../../bin/busybox'
`/usr/bin/watchdog' -> `../../bin/busybox'
`/usr/bin/whois' -> `../../bin/busybox'
`/usr/bin/zcip' -> `../../bin/busybox'

Then check the full packages and determine what to keep and what not.

**Comment by mavrothal** [comment]
Is important in puppy-philosophy to use busybox as much as possible.
When the busybox applet is problematic in some instances puppy is using the <utility_name>_FULL to both rename the official utility and use it within scripts.
What you suggest may be problematic as these busybox applets are the one used in initrd too, so either the full versions should be included in initrd or the build system should be modified to accomodate a different version for initrd and another one for the full OS.

**Comment by jamesbond3142** [comment]
This is how I solve the problem: all applets from busybox are created in /bin and /sbin (as appropriate).
The full utilities (coreutils, util-linux, etc) are installed in /usr/bin and /usr/sbin (unless the FHS demands that they be in /bin and /sbin, in which then we overwrite busybox's version altogether), and the default PATH is set so that /usr/bin and /usr/sbin is preferred over /bin and /sbin. This way, the full utilities are used when available, but the system will fallback to busybox utilities when they are not available. No more messing with *-FULL versions (I still have one of those, for compatibility reasons).

That's the easy part, however.

The difficult part: some (most?) puppy scripts use busybox syntax and will choke if given the full version (e.g. "dc" episode in quirky). If you go the above route, you must scour through all the scripts and make sure that they can work with both versions of the utilities - or if not, then for busybox ones you must use the busybox prefix (e.g. "busybox dc" instead of just "dc") to ensure that they will use, well, the busybox version of the utilities.

cheers!

On Wed, 06 May 2015 20:58:44 -0700
jlst <notifications@github.com> wrote:

> Though Puppy is different, it should try to look as normal as possible.
> 
> - woof-CE/woof-code/packages-templates/ 
> 
> coreutils, util-linux, create extremely cutdown packages.
> 
> I find MANY tutorials and solutions that use utilities from those packages. Also there is a fatal flaw: there is a 'truncate' utility, that I really find useful, but it's different from the one in Puppy, and both share the same path.
> 
> busybox also has a lot of applets, you can create symlinks this way:
> 
> sh-4.3# busybox --list | while read applet ; do  if ! which $applet >/dev/null ; then  ln -sfv ../../bin/busybox /usr/bin/$applet ; fi ; done 
> `/usr/bin/add-shell' -> `../../bin/busybox'
> `/usr/bin/adjtimex' -> `../../bin/busybox'
> `/usr/bin/arp' -> `../../bin/busybox'
> `/usr/bin/arping' -> `../../bin/busybox'
> `/usr/bin/bootchartd' -> `../../bin/busybox'
> `/usr/bin/brctl' -> `../../bin/busybox'
> `/usr/bin/catv' -> `../../bin/busybox'
> `/usr/bin/chpst' -> `../../bin/busybox'
> `/usr/bin/conspy' -> `../../bin/busybox'
> `/usr/bin/cttyhack' -> `../../bin/busybox'
> `/usr/bin/dnsd' -> `../../bin/busybox'
> `/usr/bin/envdir' -> `../../bin/busybox'
> `/usr/bin/envuidgid' -> `../../bin/busybox'
> `/usr/bin/ether-wake' -> `../../bin/busybox'
> `/usr/bin/fakeidentd' -> `../../bin/busybox'
> `/usr/bin/fatattr' -> `../../bin/busybox'
> `/usr/bin/ftpd' -> `../../bin/busybox'
> `/usr/bin/hush' -> `../../bin/busybox'
> `/usr/bin/ifenslave' -> `../../bin/busybox'
> `/usr/bin/inetd' -> `../../bin/busybox'
> `/usr/bin/killall5' -> `../../bin/busybox'
> `/usr/bin/linuxrc' -> `../../bin/busybox'
> `/usr/bin/lpd' -> `../../bin/busybox'
> `/usr/bin/makemime' -> `../../bin/busybox'
> `/usr/bin/mt' -> `../../bin/busybox'
> `/usr/bin/nanddump' -> `../../bin/busybox'
> `/usr/bin/nandwrite' -> `../../bin/busybox'
> `/usr/bin/nbd-client' -> `../../bin/busybox'
> `/usr/bin/nmeter' -> `../../bin/busybox'
> `/usr/bin/ntpd' -> `../../bin/busybox'
> `/usr/bin/patch' -> `../../bin/busybox'
> `/usr/bin/popmaildir' -> `../../bin/busybox'
> `/usr/bin/raidautorun' -> `../../bin/busybox'
> `/usr/bin/reformime' -> `../../bin/busybox'
> `/usr/bin/remove-shell' -> `../../bin/busybox'
> `/usr/bin/runsv' -> `../../bin/busybox'
> `/usr/bin/runsvdir' -> `../../bin/busybox'
> `/usr/bin/rx' -> `../../bin/busybox'
> `/usr/bin/sendmail' -> `../../bin/busybox'
> `/usr/bin/setuidgid' -> `../../bin/busybox'
> `/usr/bin/slattach' -> `../../bin/busybox'
> `/usr/bin/smemcap' -> `../../bin/busybox'
> `/usr/bin/softlimit' -> `../../bin/busybox'
> `/usr/bin/sv' -> `../../bin/busybox'
> `/usr/bin/svlogd' -> `../../bin/busybox'
> `/usr/bin/tcpsvd' -> `../../bin/busybox'
> `/usr/bin/telnetd' -> `../../bin/busybox'
> `/usr/bin/tftpd' -> `../../bin/busybox'
> `/usr/bin/tunctl' -> `../../bin/busybox'
> `/usr/bin/ubiattach' -> `../../bin/busybox'
> `/usr/bin/ubidetach' -> `../../bin/busybox'
> `/usr/bin/ubimkvol' -> `../../bin/busybox'
> `/usr/bin/ubirmvol' -> `../../bin/busybox'
> `/usr/bin/ubirsvol' -> `../../bin/busybox'
> `/usr/bin/ubiupdatevol' -> `../../bin/busybox'
> `/usr/bin/udpsvd' -> `../../bin/busybox'
> `/usr/bin/vconfig' -> `../../bin/busybox'
> `/usr/bin/watchdog' -> `../../bin/busybox'
> `/usr/bin/whois' -> `../../bin/busybox'
> `/usr/bin/zcip' -> `../../bin/busybox'
> 
> 
> Then check the full packages and determine what to keep and what not.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/puppylinux-woof-CE/woof-CE/issues/546


-- 
James B <jamesbond3142@gmail.com>
