### ISSUE TITLE
SVG icons break compatibility with older Window Managers

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#548]
www.youtube.com/watch?v=es1vQl_S55Y

All Window managers look so primitive compared to lxp-icewm that is unbelievable that development was stopped almost a decado ago. I guess it was already complete, but not anymore. That ability to use images for everything makes it look so amazing. When the mouse is over the window buttons, they change color (image), when clicked it also happens the same.

IceWM can look for an icon if the extension is not specified. PNG, JPG, XMP, even GIF I think.

ex 'icon=palemoon' is enough for IceWM to get it right every time.

When I moved my whole setup to tharpup CE, IceWM was unable to display 97% of the icons.

**Comment by mavrothal** [comment]
If you are suggesting to part from svg icons, I would disagree. If you are suggesting to fix IceWM to handle them, please do.

**Comment by 01micko** [comment]
I'm not sure if @bbidulock 's IceWM fork has SVG compatibility, but I wouldn't be surprised if it does.
