### ISSUE TITLE
ca-certificates support in 3builddistro

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#549]
https://packages.debian.org/search?keywords=ca-certificates

Basically check if ca-certificates is present and execute it with chroot. This will make some applications behave better.

chroot $dir	update-ca-certificates
	echo "ca-directory=/etc/ssl/certs" >> $dir/etc/wgetrc

**Comment by 01micko** [comment]
@dimkr has now addressed this with a template in this commit : b936aef93f18dd429bae0a27fd8d1abbe8a4f318 . It is the responsibility of the distro builder to make sure it is included!
