### ISSUE TITLE
Merge restartwm, wmpoweroff, wmreboot & wmexit into one script?

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#551]
- restartwm
- wmpoweroff
- wmreboot
- wmexit

These all share the same code, with a few differences. That can be sorted out with a symlink.

Suppose wmexit is the script, all the others are symlinks to wmexit. 

Looking at how busybox works, I realized that by calling an application through a symlink, the $0 variable stores the symlink path.

So we can do this:

	script=${0##*/}

	case $script in
		wmexit)
			#code and comments here
			;;
		restartwm)
			#code and comments here
			;;
		wmreboot)
			#code and comments here
			;;
		wmpoweroff)
			#code and comments here
			;;		
	esac

**Comment by mavrothal** [comment]
OK... but does it solve any issue?

**Comment by technosaurus** [comment]
Yes it solves the problem of puppy having too many files scattered around in too many places.  Each shell script takes 4kb (or more on some file systems).  Not only that, but putting them in the same script allows them to share code.

This has been done before. See: [bashbox](http://www.murga-linux.com/puppy/viewtopic.php?t=60734)

**Comment by 01micko** [comment]
I agree @technosaurus . Probably a lot of things can go into a functions library.

**Comment by mavrothal** [comment]
Yeh... But someone must properly implement it make sure that scripts that call it work and issue a pull request. :wink:

**Comment by wdlkmpx** [comment]
Actually that's pretty easy
