### ISSUE TITLE
Add essential scripts to woof

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#552]
sh-4.3# syscore -gitdiff /usr/sbin/pdict
	15c15
	< yaf-splash -placement center -bg orange -close never -timeout 60 -fontsize large -text "$(gettext 'Please wait, accessing online Dict server...')" &
	---
	> /usr/lib/gtkdialog/box_splash -placement center -close never -timeout 60 -fontsize large -text "$(gettext 'Please wait, accessing online Dict server...')" &

In woof there are trivial scripts like pdict, file associations that must go into the ROX package.

However, in my experiencie, these 2 scripts are more important that most of the scripts introduced to woof lately:

	sh-4.3# syscore -gitdiff /usr/sbin/sfs_load
	diff: /mnt/sda1/github/WOOFCE/woof-code/rootfs-skeleton/usr/sbin/sfs_load: No such file or directory

	sh-4.3# syscore -gitdiff /usr/sbin/frugalinstaller
	diff: /mnt/sda1/github/WOOFCE/woof-code/rootfs-skeleton/usr/sbin/frugalinstaller: No such file or directory

**Comment by mavrothal** [comment]
There are actually many other important scripts that could be in woof-CE. Almost all the noarch pets for one and rootfs-packages is actually designed for that.
Unfortunately, script developers do not want to put and maintain/develop their scripts/app from there and of course no one wants ti highjack the apps.
