### ISSUE TITLE
Move some firmware to a new firmware-specific SFS

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#558]
In continuation to a long discussion on this commit https://github.com/puppylinux-woof-CE/woof-CE/commit/c066ff433d583e212cfa2b3aa6b7d2c90bc8bab8 , this is to discuss the move of some heavy/additional/not much used firmware to an extra SFS (fdrv.sfs) to be loaded when hardware recognition issues arise.

**Comment by gyrog** [comment]
Disadvantage of having 2 versions of an iso or kernel tgz similar to PAE, is that the chioice of PAE v nonPAE can be predicted before the download. I suspect that most times folk won't know if they need the full firmware version before they download. After a firmware problem is found, then they would want to only download the extra firmware.
So, don't include it, make it separately available for download.

**Comment by mavrothal** [comment]
So what do you propose? 
Keep it the way it is? 
Add more firmware? Less?
I guess the issue is what to do about "unrecognised" hardware. A knowledgable user, will identify the problem and solve it one way or another. The issue is what the "novice" user will do faced with such a problem.

**Comment by gyrog** [comment]
I'm suggesting that the sfs containing the extra firmware is made available for separate download, rather than including it in the iso. Most folk don't need it. Once a firmware problem is found, why download the whole iso again?

**Comment by mavrothal** [comment]
I was actually thinking the default to be the ISO with the firmware sfs included. This should not be the 90MB firmware universe but something that would cover 99.9% So an additional 25-30 MB in the ISO size that would be loaded with a simple boot argument in case of a problem.

**Comment by 01micko** [comment]
Anyway, just did a kernel build with pulling in the firmware and it worked as expected. Still needs fine tuning to get the size down.

The overall size of the kernel package is 46M (xz) .. too big. Needs to be between 35 and 38 to bring it in line with my cut versions. The fdrive was produced successfully. 

I notice from #505 that NLS is broken so I added

```
CONFIG_NLS_CODEPAGE_850=y
CONFIG_NLS_CODEPAGE_852=y
```

to the config. When I eventually make a commit I'll add these to the extra configs.. or evn better, detect if we are doing the 'huge' build and have a large warning that if you want pkeys= to work then those must be enabled.

**Comment by 01micko** [comment]
Wow... 40MB for k-4.0.6. About as good as it gets. Compared with 3.4.94 in slacko-5.9.3 @ 30MB.. however, the on disk size of `lib/modules`has increased from 62M to 78M accounting for a fair slice of that difference - and the old b43-legacy is enabled, so those blobs got included. 

I will do a build of the latest 3.4.108 to compare apples with apples. (It's what I like to use in slacko 32 anyways.). Plus this also ensures I didn't break backwards 3.x-series compatibility in the migration to 4.x-series support in the script.

Bear in mind, that this excludes `all-firmware`. My 'big'  and 'cut' (old) firmware packages included most (if not all) of those blobs.

**Comment by 01micko** [comment]
I did a few test builds and everything works as expected. I built with and without `fdrv*.sfs`. It loads fine with `pfix=fw_drv`. Size could come down a little. I used k3.14.45. Anything older and `aufs` crashes the kernel build as Junjiro has stopped support for older (even LTS) kernels.

So I've committed changes to `kernel-kit` and `3builddistro-Z`.

**Comment by mavrothal** [comment]
:+1: 
Are you planing to build and release any test puppy with these changes?

**Comment by 01micko** [comment]
If you commit PPM2 to fdrv branch I'll think about it :cactus:

**Comment by mavrothal** [comment]
PPM 2 is already in testing and thus in fdrv

**Comment by 01micko** [comment]
Oh, I didn't try PPM. Have to fix the call "choose ziggy or classic" in `3builddistro-Z`. I gather 'classic' is gone?

**Comment by mavrothal** [comment]
Both classic and ziggy are there. But now they are recorded in /var/local/petget/ui_choice. So 3bulddistro just needs to write this there but only if you want "Classic". If /var/local/petget/ui_choice is missing PPM2 defaults to ziggy. 
see https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/local/petget/configure.sh#L174 for relevant cde

**Comment by mavrothal** [comment]
Here is the change (did not commit it in case you are doing it also
```
--- a/woof-code/3builddistro-Z
+++ b/woof-code/3builddistro-Z
@@ -1930,16 +1930,14 @@ fi
 #140619 ui_ziggy choice
 echo
-echo "Do you want the Classic gui or the Ziggy gui for PPM?"
-echo "hit \"z\" [enter] for Ziggy, Enter only for Classic."
-read ZIGGY
-if [ "$ZIGGY" = "z" ];then
-	ZIGSET="UI=\"Ziggy\""
-	CLASET="UI=\"Classic\""
-	sed -i "s%$CLASET%$ZIGSET%" rootfs-complete/usr/local/petget/configure.sh
-	sed -i "s%$CLASET%$ZIGSET%" rootfs-complete/usr/local/petget/pkg_chooser.sh
-	echo "PPM gui set to \"Ziggy\""
-	else echo "Leaving PPM gui set to \"Classic\""
+echo "Do you want the PPM2 or the Classic gui for PPM?"
+echo "hit \"c\" [enter] for Classic, Enter only for PPM2."
+read UICHOICE
+if [ "$UICHOICE" = "c" ];then
+	mkdir -p rootfs-complete/var/local/petget
+	echo "Classic" > rootfs-complete/var/local/petget/ui_choice
+else 
+	echo "Leaving PPM2 gui"
 fi
 echo


```

**Comment by 01micko** [comment]
Thanks. Hadn't got to it yet. Not working on it tonight so feel free to commit.

On another note, I see you want to wind this branch up fairly quickly, re #561, so I'll try and get a testing iso out very soon then we can merge into testing, delete 'fdrv' branch and I can create a new 'xorg' branch to fix that mess.

**Comment by mavrothal** [comment]
OK I committed this https://github.com/puppylinux-woof-CE/woof-CE/commit/d203d8e71921ad62502840629ba6a328dc95d40c
If the ISO comes out and there are no issues (remember to also patch sfs_load), we can merge back `fdrv` to `testing` and then branch `xorg` from there.

**Comment by 01micko** [comment]
Nice :tongue: 

There are more complications but they are a bit off topic here. I may open an issue for discussion.
