### ISSUE TITLE
Retire /usr/local/lib/X11/mini-icons

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#560]
We should work towards removing this directory completely.

All scripts and pets will have to be scanned for any reference to this directory and replaced with an icon from elsewhere. Much of this has already been addressed and a raw woof built puppy doesn't need these, but the problem is pets and getting the community used to the fact that these icons are not to be used.

Perhaps they can go into a pet in noarch for those who still want to use them.

**Comment by mavrothal** [comment]
I can hear a lot a "screaming" over "my favourite pet in not working in this new puppy".
What is the advantage of removing those mini-icons (other that the fact that some are ugly)?

**Comment by q5sys** [comment]
Personally I think this is where people in the community (of which I
volunteer), work to rebuild older packages for newer puppy versions.  I
know some people are still trying to wrestle packages from the 4.0 series
on modern builds, which just seems like a bad idea to me.
If there was some easy way people could request packages be rebuilt for
Slacko, I'd happily set my workstation to compiling whatever people need.

**Comment by 01micko** [comment]
@q5sys try https://github.com/puppylinux-woof-CE/petbuilds

There is an 'automated' way to create a `*.petbuild` file and patches, DOTdesktop files and templates can be included in the folder. I have about 123 so far (will commit today to bring the tally up to 123 anyway).

At the moment there is a possible bug in the `perl` installation (the template in woof) which can be overcome by reinstalling `perl` from upstream. Other than that, all should build on slacko and most do on tahr.

**Comment by zigbert** [comment]
If our leading star is KISS, they should go...

**Comment by 01micko** [comment]
Are we there yet? I'd love to delete that folder!

**Comment by zigbert** [comment]
delete delete delete :-)

**Comment by 01micko** [comment]
Something inside me says 'delete' and just deal with it! :+1: 

However we wait until we merge testing to master.. hopefully this week.

**Comment by mavrothal** [comment]
These are gone. I'm closing. Reopen if needed

**Comment by zigbert** [comment]
These are not gone

**Comment by 01micko** [comment]
well the xpms are now :+1: 

I left the png there and the directory.
