### ISSUE TITLE
New JWM is out but breaks current jwmrc*

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#562]
@joewing has released jwm-2.3.0 ( 04fdf3c2ed0cdae7e995114ebd48bbdf4a0a76ba ) and with it (as BK has reported) it breaks themes. 

Fortunately, Joe has a fix by using an xslt file. It can easily be done in a `chroot` and applied to all *jwmrc* files and it works. However this doesn't add the new features, such as using the clock as a menu ( @zigbert  ). It also fixes a touchscreen bug with cellwriter and other virtual keyboards, hence my eagerness to upgrade.

![screenshot](https://cloud.githubusercontent.com/assets/1019119/8327067/f4bc5414-1aa8-11e5-8306-15ae12a77070.png)

**Comment by zigbert** [comment]
I don't see the problem. Upgrade jwm, and I'll fix pTheme / theme-switcher.
Does there exist a pet for jwm 2.3.0?

**Comment by 01micko** [comment]
> Does there exist a pet for jwm 2.3.0?

Yes.. but I need to upload, however not home right now so will do shortly.

**Comment by 01micko** [comment]
http://distro.ibiblio.org/puppylinux/pet_packages-slacko14.1/jwm-2.3.0-i686.pet

There is also _DOC and _NLS

**Comment by zigbert** [comment]
I really can't get the jwm-2.3.0 pack running in my Slacko 5.7.
I have fixed jwmrc, jwmrc-themes, jwmrc-corners  and jwmrc-tray so 'jwm -p' gives no result. but when rebooting, only a black X-screen (including mouse) shows up. How can I debug JWM. pfix=nox works ok, but no messages...

**Comment by 01micko** [comment]
Oh, that was compiled in 5.9.3, maybe I'll compile in 5.7 :fearful:

**Comment by 01micko** [comment]
http://distro.ibiblio.org/puppylinux/pet_packages-slacko14/jwm-2.3.0_slacko57-i686.pet

That works in my slacko-5.7 on a VM. (there is also DOC and NLS files uploaded)

**Comment by zigbert** [comment]
Great stuff!
I have started the work to update the jwm_config and pTheme package.
Hopefully done by this weekend - at least to convert the old features.

**Comment by 01micko** [comment]
There are minor 2 feature requests I have.

- please add the `<Corner>n</Corner>` tag. While round corners were nice 5 years ago when Patriot first did it, a non-hard coded choice is nice. Joe introduced it some months ago.
- please add the `<?xml version="1.0"?>` tag to the top of all `jwmrc*` config files _only_ so we get syntax highlighting :smile:

**Comment by zigbert** [comment]
<?xml version="1.0"?> corrupts the tray-templates. But added to theme files.
Corner will be added.

**Comment by zigbert** [comment]
Looked at the <corner> tag, and I mean it belongs to the theming, - not the jwm-config (window script). I have updated the 4 themes for Woof with different corner roundness. OsX with max, WinXp with just a little...

**Comment by 01micko** [comment]
Ok, sounds good to me, thanks.

**Comment by zigbert** [comment]
I don't like the new 'include' feature that forces one more click to let user show the menu.
I wonder what cons this extra button has...

![screenshot_2015-06-28_090104](https://cloud.githubusercontent.com/assets/5928708/8395536/b3649f60-1d75-11e5-8939-6e6e66d4d2d8.jpg)

**Comment by 01micko** [comment]
I've never seen that, must be a bug

**Comment by 01micko** [comment]
Oh, maybe you need to define the button mask?

**Comment by zigbert** [comment]
Can't find any documentation of masks for the onroot tag
http://www.joewing.net/projects/jwm/config.shtml#root

**Comment by 01micko** [comment]
Ok, I've done a couple of builds and things is a bit of a mess at the moment - not entirely due to `pdesktop` but I'm guessing it's not quite helping.

There is conflicts with the old stuffs in `3builddistro-Z` which I will take care of in due course.

What command sets up a nice default desktop using `pdesktop`? ATM we only run `fixmenus` and that's partly the cause of the mess.

**Comment by 01micko** [comment]
Ok, what I need is a CLI method to set a theme the does not do any graphical stuff at all, just sets the them by putting in place all the gtk and jwm themes to be used for that global.

Here is how I can do it in woof (but I suppose you need something as well as '-p' as that is taken :spaghetti: )

```
#!/bin/sh
[ -f /tmp/pthemes.lst ] && rm /tmp/pthemes.lst
pt=1
for th in rootfs-complete/usr/share/ptheme/globals/* ; do
	echo "$th"|grep -q -i 'touch' && continue
	echo "$pt:${th##*/}" >> /tmp/pthemes.lst
	pt=$(($pt + 1))
done
while [ 1 ];do
	echo "Please choose a theme by pressing 1 to ${th}, then <Enter> key"
	echo
	cat /tmp/pthemes.lst
	read theme_chosen
	case "$theme_chosen" in
		[1-9]) # hmmm... 9 is enough I think for now
		if grep -q "$theme_chosen" /tmp/pthemes.lst;then
			my_theme="`grep "$theme_chosen" /tmp/pthemes.lst|cut -d':' -f2`"
			[ -z "$my_theme" ] && continue || break
		else
			echo "That number doesn't work, try again"
			continue
		fi
		;;
		*)echo "That number doesn't work, try again" && continue
		;;
	esac
done
echo -e "\"$my_theme\" is a nice choice!"
sleep 2
read
chroot rootfs-complete /usr/sbin/ptheme -p "$my_theme"
[ $? -ne 0 ] && echo "oops, something is wrong, but your build should be ok"
```

If I run that from woof as it is the themes _DO_ get set :smile_cat: ...  _BUT_ my running system goes berserk! All sorts of errors and my console fills up with no end in sight -  excepting `CTRL + C` :bug:  .. so if we can avoid _setting_ the theme (ie: not restarting jwm, rox etc) we will have a good system.

BTW, I will reconsider filtering 'touch' when I actually get touch to work.

**Comment by zigbert** [comment]
It should be fairly simple to run activation commands (jwm -restart, switch2, rox -p and fixwidgets) only if X is running.
What test command? Is this reliable?
grep -F 'xwin' <<< $(ps -eo pid,command)

**Comment by 01micko** [comment]
No, we a building this on a non running system in a `chroot`. switch2 is ok but if _any_ graphical program runs it's drama. Bear in mind, the `chroot` doesn't know any environment variables so $HOME doesn't work. Everything has to be relative paths.

I will show a function that I inserted in  `/usr/sbin/ptheme`, call with '-w' switch.. but it is rough because of all the children it calls call graphical programs. It must be strictly no X so it can be ran from woof, or else we get a standard puppy desktop at boot with no advantage of ptheme.

```
set_theme_only (){
	#icons
	if [ "$PTHEME_ICONS" ] && [ -d /usr/local/lib/X11/themes/"$PTHEME_ICONS" ]; then
		icon_switcher -a "$PTHEME_ICONS"
		SWITCH_THEME=true
		UPDATE_ROX=true
	fi
	#rox pinborad - icon placement
	if [ "$PTHEME_ROX_PIN" ] && [ -f /usr/share/ptheme/rox_pinboard/"$PTHEME_ROX_PIN" ]; then
		TMP_BACKDROP="`grep -F '<backdrop ' root/Choices/ROX-Filer/PuppyPin`"
		TMP_DRIVEICONS="`grep -F '.pup_event' root/Choices/ROX-Filer/PuppyPin`"
		echo -e '<?xml version="1.0"?>\n<pinboard>' > $WORKDIR/tmp_puppypin
		echo "$TMP_BACKDROP" >> $WORKDIR/tmp_puppypin
		cat /usr/share/ptheme/rox_pinboard/"$PTHEME_ROX_PIN" >> $WORKDIR/tmp_puppypin
		echo "$TMP_DRIVEICONS" >> $WORKDIR/tmp_puppypin
		echo '</pinboard>' >> $WORKDIR/tmp_puppypin
		mv $WORKDIR/tmp_puppypin root/Choices/ROX-Filer/PuppyPin
		SWITCH_THEME=true
		UPDATE_ROX=true
	fi
	#avoid cursor
	#wallpaper
	if [ "$PTHEME_WALL" ] && [ -f "/usr/share/backgrounds/$PTHEME_WALL" ]; then
		echo "/usr/share/backgrounds/$PTHEME_WALL" > root/.config/wallpaper/bg_img
		echo 'Stretch' > root/.config/wallpaper/backgroundmode
		#"/usr/local/apps/Wallpaper/set_bg" "/usr/share/backgrounds/$PTHEME_WALL"
		SWITCH_THEME=true
	fi
	#gtk
	if [ "$PTHEME_GTK" ] && [ -d "/usr/share/themes/$PTHEME_GTK" ]; then
		export GTK2_RC_FILES="root/.gtkrc-2.0" #reset gtk-theme
		ptheme_gtk -t "$PTHEME_GTK" &
		SWITCH_THEME=true
	fi
	#jwm
	if [ "$PTHEME_JWM_COLOR" ] && [ -f /usr/share/jwm/themes/"$PTHEME_JWM_COLOR"-jwmrc ]; then
		/usr/local/jwm_config/theme_switcher -a "$PTHEME_JWM_COLOR"
		UPDATE_JWM=true
		SWITCH_THEME=true
	fi
	if [ "$PTHEME_JWM_BUTTON$HOMES" ] && [ -d /usr/share/jwm/themes_window_buttons/"$PTHEME_JWM_BUTTONS" ]; then
		/usr/local/jwm_config/window_buttons -a "$PTHEME_JWM_BUTTONS"
		UPDATE_JWM=true
		SWITCH_THEME=true
	fi
	if [ "$PTHEME_JWM_TRAY" ] && [ -d /usr/share/jwm/tray_templates/"$PTHEME_JWM_TRAY" ]; then
		cp -f /usr/share/jwm/tray_templates/"$PTHEME_JWM_TRAY"/jwmrc-tray* $HOME/.jwm/
		[ -s /usr/share/jwm/tray_templates/"$PTHEME_JWM_TRAY"/install ] && /usr/share/jwm/tray_templates/"$PTHEME_JWM_TRAY"/install
		UPDATE_JWM=true
		SWITCH_THEME=true
	fi
	#menuheight
	echo "MENHEIGHT=24" > root/.jwm/menuheights
	exit
}
```

Still have to do something about the wallpaper too. Hard coding can not be helped in this situation.

Maybe a separate script all together is what's really needed. Don't worry, I'll take care of it.

**Comment by 01micko** [comment]
Sorry, I misunderstood what you were saying, I need a break!

`[ "$DISPLAY" ] && do_gui || do_cli`

That's conventional and since there are no env vars DISPLAY is not set anyway.

**Comment by zigbert** [comment]
I misunderstood my own thoughts :-)
Of course this has nothing to with a running X or not.

BTW, I have uploaded the updated osX and winXP themes to the forum link provided in pTheme.

**Comment by 01micko** [comment]
> I don't like the new 'include' feature that forces one more click to let user show the menu.
I wonder what cons this extra button has...

This bug is fixed in jwm-2.3.1 .. package soon.

It's good now, only get bookmarks on a single right click.

**Comment by 01micko** [comment]
Just something to bear in mind when running in our `chroot`

The shell root is '/' not '/root' or "$HOME" so paths should be relative to '/'

**Comment by 01micko** [comment]
Here is your Puppy Slacko 570 jwm 2.3.1 package  -

http://distro.ibiblio.org/puppylinux/pet_packages-slacko14/jwm-2.3.1-i686_slacko570.pet

There is a pinstall.sh in there that updates old configs (based on Joes xslt file). Seems to work very well, tested in slacko-570 and slacko-560 (there is a gz package for 560 and earlier at the same location). Of course it is optional (Xdialog -yesno) and doesn't touch configs built after June 1, 2015.

**Comment by 01micko** [comment]
Ok... needs this as there is a new tag `<Dynamic>` as exec in includes gave troubles. 

See the manual in the http://distro.ibiblio.org/puppylinux/pet_packages-slacko14/jwm_DOC-2.3.1-i686_slacko570.pet packages as the website is not update.

```
<RootMenu label="1" labeled="false" height="MENHEIGHT" onroot="3">
	<Dynamic label="Bookmarks" icon="about.svg" height="MENHEIGHT">exec:$HOME/.jwm/root_menus/menu1</Dynamic>
</RootMenu>
<RootMenu label="2" labeled="false" height="MENHEIGHT" onroot="2">
	<Dynamic label="Main Menu" icon="about.svg" height="MENHEIGHT">exec:$HOME/.jwm/root_menus/menu2</Dynamic>
</RootMenu>

```

I think the label is needed for now otherwise the 'Dynamic' shows as the label - a bug.

Also, it is not respecting menu height - another bug. Note that I had to move the calls to new lines so that MENHEIGHT would get replaced as the C code only allows for 1 per line.

Here is what it looks like (note the button mask is the 'onroot' so clicking middle button shows the main menu.)

![screenshot1](https://cloud.githubusercontent.com/assets/1019119/8448324/4f284c5e-2009-11e5-9c2e-3970447ba372.png)


![screenshot](https://cloud.githubusercontent.com/assets/1019119/8448309/29c4a7c8-2009-11e5-8c85-bbfe60598145.png)

**Comment by zigbert** [comment]
Looking forward to test ;-)
I am sure I have some fixing when running pdesktop on a fresh system.

**Comment by 01micko** [comment]
Ok .. crappy work-around but I have reported this as a bug to @joewing 

```
#output to stdout - jwm menu
[ -f "$HOME/.jwm/menuheights" ] && . $HOME/.jwm/menuheights || MENHEIGHT=24
TMP="`echo -e "$XML" | sort`"
echo -e '<JWM>
<Menu height="'$MENHEIGHT'">
'"$TMP"'
<Separator/>
<Program icon="bookmark.svg" label="'$(gettext 'Edit Bookmarks')'">exec /usr/local/jwm_config/menu -bookmarks</Program>
</Menu>
</JWM>'

```

Similar works for menu2 as well but in both cases we get this :beetle: 

![screenshot2](https://cloud.githubusercontent.com/assets/1019119/8449388/5fda1496-2014-11e5-97e1-3bf63cdf7729.png)

**Comment by 01micko** [comment]
Ok!! Joe fixed the bug. It will be compiled later as I can't be bothered right now and I am busy tomorrow. 

![bug-fixed](https://cloud.githubusercontent.com/assets/1019119/8455019/de7dfd8c-2044-11e5-9810-d3f8a69636ba.png)

Ha.. the Buntoo theme...

**Comment by 01micko** [comment]
I made a quick tarball of the binary only (in 5.6-slacko, same as 5.7 so will run)

http://01micko.com/packages/jwm-2.3.2-snapshot-150701r1149.tar.gz

Untar, make sure it's executable and overwrite the previous version.

**Comment by zigbert** [comment]
jwm_config is updated to support jwm 2.3.2
Still corner-actions doesn't work - so deactivated at this point

**Comment by mavrothal** [comment]
We need to detect accurately jwm version and adjust scripts accordingly.
It also breaks a lot of themes, so we'll need to know the version and install the appropriate themes.
The problem is that a lot of jwm versions floating around have vgit numbers instead of full version. 
Version 2.3.0 I believe is where the new attributes are implemented but which one is the last "good" vgit version?
BTW that's a bug that affect the UI. So I would say major.

**Comment by mavrothal** [comment]
Do we still need to have this open?
Zig's latest looks good.
