### ISSUE TITLE
merge2out & 0setup breaks templates for 64bit ubuntu builds

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#570]
currently if a 64bit build is chosen merge2out attemps to fix the templates (lines 139-157) moving all lib dirs and contents to lib64 and altering all FIXUPHACKs accordingly.

 however ubuntu has its 64bit libs in /usr/lib/x86_64-linux-gnu so most packages that go through the templates process get broken

**Comment by mavrothal** [comment]
Instead of moving lib64 on a distro/version specific manner wouldn't it be more reasonable to symlink accordingly at the z_hack level?

**Comment by 01micko** [comment]
@mrfricks

Phil

Since it works in 32 bit with the `/usr/lib/i386-linux-gnu`, then how about
we skip that step in `merge2out`?

try @line139

`if [ "${COMPATDISTRO}"  = "slackware" -a "${TARGETARCH}" = "x86_64" ];then`

That should skip processing the templates.

**Comment by 01micko** [comment]
Just so you know, formatting markdown didn't work over email so skip the `backticks` :+1:

**Comment by mrfricks** [comment]
0setup line 71 also needed your fix

**Comment by 01micko** [comment]
@mrfricks  I'll close this one but feel free to reopen if it is still an issue.
