### ISSUE TITLE
Move run_woof to puppylinux-woof-CE

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#571]
[https://github.com/dimkr/run_woof](https://github.com/dimkr/run_woof)

**Comment by mavrothal** [comment]
Go ahead!

**Comment by dimkr** [comment]
I don't have the permissions required to do this :(

**Comment by mavrothal** [comment]
You can not add a new repo? Don't you have the "+" sign in the upper right side of the github page as shown in https://help.github.com/articles/creating-a-new-repository/ ?

**Comment by dimkr** [comment]
I have no permissions to create repositories under the organization. You can fork my repository and place the fork under the organization, that would be easier.

**Comment by mavrothal** [comment]
Done. https://github.com/puppylinux-woof-CE/run_woof
Please verify that you have no permission issues with it.

**Comment by dimkr** [comment]
I don't have push permissions.

**Comment by mavrothal** [comment]
Should be OK now. Pls check.

**Comment by dimkr** [comment]
Works. Thank you!
