### ISSUE TITLE
Are Patches to device rules (subsystem) are viable ? [Patches from woof-CE patch generator]

### ISSUE THREAD

**Issue by keyboard-k** [puppylinux-woof-CE/woof-CE#572]
So far I have found changes in device rules (really minor I suppose, just use of ATTR instead SYSFS )in subsystem related to usb devices. are these a viable patch ? Last I heard SYSFS{} would be removed from udev (I might be wrong here, haven't been much updated in this.) . So it does makes sense to change them.

Changes are found here:

https://github.com/puppylinux-woof-CE/woof-CE/commit/58e98dd0aa9d4bf53c9dc430383c422a65c6204b

EDIT:

regarding udev , SYSFS being depreciated,

check here: https://lists.debian.org/debian-user/2009/12/msg00774.html

**Comment by mavrothal** [comment]
Is probably a very old rule, though I'm not sure if it generates any problems.
The change looks reasonable for current udev and kernels. 
Please issue a pull request.
