### ISSUE TITLE
remember screen brightness

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#576]
in tahrpup i use a simple set of sripts to remember the screen brightness on laptops.

 /usr/sbin/brightness
`#!/bin/sh`
`if find /sys/class/backlight/acpi_video0/brightness`
`then`
``brightness=`cat /sys/class/backlight/acpi_video0/brightness``
`echo $brightness > /root/.config/brightness.conf`
`fi`

this is called from /etc/rc.d/rc.shutdown upon poweroff.
 
upon first boot of puppy the script  /root/Startup/laptopcheck runs once.
`#!/bin/sh`
`if find /sys/class/backlight/acpi_video0/brightness`
`then`
`echo ""  >> /etc/rc.d/rc.local`
``echo 'brightness=`cat /root/.config/brightness.conf`' >> /etc/rc.d/rc.local``
`echo 'echo $brightness > /sys/class/backlight/acpi_video0/brightness' >> /etc/rc.d/rc.local`
`fi`
`rm /root/Startup/laptopcheck`

this works well on the few laptops i've tried it on but isn't too elegant.  i wonder if it can be improved and added to woof.

**Comment by 01micko** [comment]
What about make it a service script to go into /etc/init.d? That way you
don't have to hack shutdown and can have a start case and a stop case. And
it would also be a valid pet to put in the noarch repo.

**Comment by mavrothal** [comment]
Given that a laptop can be operated in very different environmental conditions remembering brightness may not be necessary as a default and even bothering at times (afternoon garden movie watching and then bedroom midnight reading). As a mater of fact Windows, OS X, Fedora and Ubuntu do not appear to have this feature. On the other hand all OSs adjust brightness depending on power source (battery vs AC) and I this this feature should be a default service. Remembering brightness  could be an optional pet or a configurable option in the aforementioned service.

**Comment by 01micko** [comment]
Sure! Put a service script in woof, however set as 0644 (not executable)
and it can be set up in the Services tab in Startup Manager.

**Comment by mavrothal** [comment]
> Sure! Put a service script in woof
Are you talking to me?... :-)

**Comment by 01micko** [comment]
Whoever wants to write the script. :-) But it does make sense.

**Comment by mavrothal** [comment]
Well, I do not have a test machine. Tahr 6.0.3 running on my 10year-old Compq Laptop with i915 loaded, has an empty /sys/class/backlight directory. However the brightness keys work fine and the brightness adjusts depending on the power source!
I think is going through /sys/modules/video/parameters/ or /sys/modules/i915/parameters/ but I'm not sure.

**Comment by mrfricks** [comment]
here's the script so far ....but i think i'll keep it as a .pet as it doesn't work with all laptops and i can't see how it can work without editing /etc/rc.d/rc.shutdown.

`#!/bin/sh`
`if find /sys/class/backlight/acpi_video0/brightness`
`then`
`echo '`
``brightness=`cat /root/.config/brightness.conf``
`echo $brightness > /sys/class/backlight/acpi_video0/brightness' >> /etc/rc.d/rc.local`
`echo '#!/bin/sh`
`if find /sys/class/backlight/acpi_video0/brightness`
`then`
``brightness=`cat /sys/class/backlight/acpi_video0/brightness``
`echo $brightness > /root/.config/brightness.conf`
`fi' > /usr/sbin/brightness`
`chmod a+x /usr/sbin/brightness`
`sed -i '/which rfkill/a /usr/sbin/brightness #save screen brightness state' /etc/rc.d/rc.shutdown`
`rm /etc/rc.d/init.d/remember_screen_brightness`
`fi`

**Comment by 01micko** [comment]
1. You should leave `/etc/rc.d/rc.shutdown` alone!

2. I can't work out what your script is doing

3. There is no need to use `/etc/rc.d/rc.local`

Service scripts are *called* from rc.shutdown with the *stop* arg.

Here is what your script should look like, but since I can't really test it it will need editing.

```shell
#!/bin/sh

# service script for laptop brighness
# goes to /etc/init.d/

case $1 in 

	start)
		if find /sys/class/backlight/acpi_video0/brightness
		then
			if [ -f ${HOME}/.config/brightness.conf ]
				brightness=`cat ${HOME}/.config/brightness.conf`
				echo $brightness > /sys/class/backlight/acpi_video0/brightness
			else
				brightness=`cat /sys/class/backlight/acpi_video0/brightness`
				echo -e $brightness > ${HOME}/.config/brightness.conf # user editable
			fi
		fi
	;;
	
	stop)
		if find /sys/class/backlight/acpi_video0/brightness
		then
			brightness=`cat /sys/class/backlight/acpi_video0/brightness`
			echo -n $brightness > ${HOME}/.config/brightness.conf
		fi
	;;
	
	*)
		echo "run $0 with the 'start' or 'stop' argument"
	;;

esac

```

**Comment by 01micko** [comment]
This should be a pet anyway as there is no need to edit shutdown script so I'm closing.
