### ISSUE TITLE
PPM is broken in testing

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#577]
It fails to install packages until something in the configuration is changed. Disabling and re-enabling console output makes it work for some reason.

**Comment by mavrothal** [comment]
Can you be more specific?
Is this related to http://www.murga-linux.com/puppy/viewtopic.php?p=865422#865422 ?

**Comment by dimkr** [comment]
When a package is selected, it doesn't do anything. Running bash -v -x ppm shows many errors and I have no idea where they come from.  Also, it seems $tPattern is empty.

Yes, it's the Librepup issue.

**Comment by dimkr** [comment]
Here's the interesting part of PPM's stdout:

```sed: can't read /tmp/forced_install: No such file or directory
grep: window: No such file or directory
grep: manager: No such file or directory
grep: for: No such file or directory
grep: X11|trisquel|belenos||: No such file or directory
grep: /tmp/overall_dependencies: No such file or directory
```

**Comment by mavrothal** [comment]
These errors are benign I believe. PPM works fine with liber pup.
The problem appeas to be the urxvt version in LibrePup. 
Replacing it with the one from TahrPup brings things to normal. 
I guess is the way the "rxvt -e" is handled that makes the difference.

**Comment by dimkr** [comment]
I'm not sure - I installed the rxvt-unicode package of Trisquel (same as the one from Ubuntu 14.04) and the problem persists.

**Comment by mavrothal** [comment]
I actually just did that too and the problem is gone!
Is the rxvt-unicode_9.19.1 (updated the repo first)

**Comment by dimkr** [comment]
Here's the fix: http://librepup.info/pet_packages-librepup/urxvt-9.21.pet
