### ISSUE TITLE
ARM Chromebooks support

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#587]
Recent ARM chromebooks (those with RK3288 - Asus C201, Haier Chromebook 11 and Hisense Chromebook 11) are supported by Arch Linux ARM and Libreboot. They're cheap, light and quad core: a perfect match for Puppy (especially Librepup). It's a Cortex-A17 chip, compatible with hard-float ARMv7 binaries.

I started work on a RK3288 port of Librepup, which uses Devuan Jessie packages.

**Comment by 01micko** [comment]
Nice!

**Comment by mavrothal** [comment]
The major issue with ARM is that almost each machine needs its own kernel and most of the time some firmware binary blobs. Pure "libre" may be a problem with most (if not all) of them.

**Comment by dimkr** [comment]
I already built most of the base PET packages and a working kernel:
![img_20151009_234127](https://cloud.githubusercontent.com/assets/1471149/10405176/e4d74406-6edf-11e5-8a36-17557df25711.jpg)

Now I'm going to deblob it, add X and the noarch PETs, one by one :)

**Comment by dimkr** [comment]
X works! Time to build JWM and all GTK+ stuff

![Screeny](http://www.dimakrasner.com/c201//IMG_20151016_010111.jpg)
![Screeny 2](http://www.dimakrasner.com/c201//IMG_20151016_010116.jpg)

**Comment by dimkr** [comment]
#605

**Comment by dimkr** [comment]
Duplicate of #1847
