### ISSUE TITLE
Change gettext INSTALL_MODE and REMOVE_MODE  variables in PPM.

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#591]
pkg_chooser.sh passes the gettext $INSTALL_MODE and $REMOVE_MODE variables to installmodes.sh and removemodes.sh. However, if the translation of the variables in the 3 different scripts is not identical to the spacing, punctuation and capitalisation, PPM will fail.
Would be better if the gtkdialog  INSTALL_MODE and REMOVE_MODE variables are interpreted within pkg_chooser.sh and non-translatable variables are passed to installmodes.sh and removemodes.sh scripts to facilitate translation.
Alternatively, some big fat comment should be placed in the script to alert translators of the fact that translation of the variables should be identical across the 3 scripts.

**Comment by mavrothal** [comment]
Currently, option 2 is implemented in b5df298

**Comment by mavrothal** [comment]
After L18L's suggestion put the scripts under the same text domain to "enforce" a common translation. see d1c59c0b

**Comment by dimkr** [comment]
@mavrothal, let me know if you want me to spin fresh Librepup images for testing.

**Comment by mavrothal** [comment]
In spite the very annoying behaviour of some, this is nothing major that needs rushing out.
PPM works in english fine both with and without this change. 
Several translation have been done successfully already with the previous version (xanad actually brought this issue to my attention during such a translation) so there is not any real issue if the translator is a bit careful. And I'm sure after all this commotion will be.
Now, if you need just one more change to justify a new spin, this one sure qualifies ;)
