### ISSUE TITLE
Stupid font path

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#592]
WOW! Forever the stupid path of `/usr/share/fonts/default/*` has worked. 

I did a slacko64 build this afternoon and X would crash as soon as it launched. (Note that Slackware did a rebuild of Xorg earlier this year to fix some vulnerability in 14.1). It took me about 10 rebuilds, searching for missing deps to realise that that was futile. Then it dawned on me. While I'm sitting at the prompt I thought "F*ck it. I'll rel link TTF and Type1 up a directory" .. so now my font path is a more sane `/usr/share/fonts`. Ha :smile: .. X started, no problems!

For now I'll put those links into woof. If I move the dirs it will surely break stuff; links *should* be harmless.

@dimkr - I was ready to blame you at first but I did enough tests to know it wasn't the trivial changes to fonts that you made. :sleeping:

**Comment by dimkr** [comment]
Umm ... will that work? Ubuntu uses /usr/share/fonts/truetype, etc'.

**Comment by 01micko** [comment]
Well it will need testing, but we have had the stupid path without a problem up until now. It shouldn't conflict anyway.

**Comment by 01micko** [comment]
@mrfricks has `/usr/share/fonst/default/truetype/DroidSansMono.ttf` :smile: in tahr 64.

**Comment by 01micko** [comment]
Ok, your fon't path as set by Xorg is the same in Trisquel.
```
[    13.773] (**) FontPath set to:
	/usr/share/X11/fonts/misc/,
	/usr/share/X11/fonts/Type1/,
	/usr/share/X11/fonts/TTF/
```

BTW, it was JWM initiating the crash (couldn't load a font), but then if I tried to avoid a WM altogether and invoke xinit (some prog) it would crash with Pango font errors. Naturally I thought since PV did a rebuild on Xorg I thought it was a dep issue.

IDK if Patrick did something to change things but maybe it wasn't him. I seem to recall some (well a few) CVE's about fonts stuff earlier this year. I couldn't be bothered searching for a link right now.

**Comment by dimkr** [comment]
Fontconfig searches for fonts under /usr/share/fonts by default, so should be OK. By the way: I think we should remove all Type1 fonts. They're incredibly ugly and it seems Puppy used them as fallback for missing TTF fonts for years - Geany uses a weird Type1 font because there's no monospace TTF font (I fixed that when I upgraded DejaVu), but maybe we should remove all of them to ensure applications don't use them.

**Comment by 01micko** [comment]
But that will break things like xmessage, and other lower level xlib apps. Do you really want to do that? While to the casual user they may have no use but to the keen learner they are an invaluable tool.

**Comment by dimkr** [comment]
Don't these applications use the old X bitmap fonts from /usr/share/X11/fonts/misc, "fixed" and friends? I think they won't break if we delete the Type1 fonts. xvidtune still works after I delete /usr/share/fonts/default/Type1.

**Comment by 01micko** [comment]
Ok, I stand corrected. Remove it if you like.

**Comment by dimkr** [comment]
Ummmmm ... I looked at Barry's /etc/fonts/fonts.conf and it loads fonts from /usr/share/fonts too, not from /usr/share/fonts/default. There's no need to keep that symlink - we can rename /usr/share/fonts/TTF to /usr/share/fonts/truetype (to comply with Debian and derivatives) and get rid of the symlink.

**Comment by 01micko** [comment]
Well that would be the best solution, however, until all the apps (scripts) that are looking in the old path catch up I say we leave it until after we merge testing to master.

**Comment by 01micko** [comment]
@dimkr 

Fist side effect is that xcalc crahes X. I think we just remove xcalc and see how it goes. There is a .desktop in the xorh_base template.
