### ISSUE TITLE
new 3builddistro-Z not working

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#594]
i'm getting 2 problems with the new 3builddistro-Z using tahrpup gtkdialog version 0.8.4
first this gtkdialog error 
```
Now building sandbox3/rootfs-complete, with the complete filesystem...

** (gtkdialog:26160): ERROR **: gtkdialog: Error in line 15, near token '</frame>': syntax error

/mnt/sda2/woof-out_x86_x86_ubuntu_trusty/3builddistro-Z: line 337: 26160 Trace/breakpoint trap   gtkdialog -p GUIC -c > $CHOICE
Continuing... please wait
```
so i never get the new popup about rootfs-packages.

a then at the very end of the build it fails with
`mksquashfs: invalid option`

**Comment by dimkr** [comment]
See my comments in https://github.com/puppylinux-woof-CE/woof-CE/commit/2e213a2ab1fab28f49cb753f98b68520da7cfd6a

**Comment by mavrothal** [comment]
I believe this a gtkdialog error introduced in 29993d5
The sfs failure is a "collateral"

**Comment by mavrothal** [comment]
Actually looking at the gtkdialog code looks OK but will fail if rootfs-packages is missing or is empty.
A test that rootfs-packages is present and populated is needed or make dialog coding more tolerant

**Comment by 01micko** [comment]
just something like 
```
[ "$(ls rootfs-packages)" ]
```
should return false

**Comment by 01micko** [comment]
Or .. if $CBOXES is empty then skip just the gtkdialog part. Why is it empty though?

**Comment by mrfricks** [comment]
the build completes fine if rootfs-packages isn't empty......  so user error on my part, as there's no need to delete the contents anymore.

thanks

**Comment by mrfricks** [comment]
spoke too soon ... final build still fails.

**Comment by 01micko** [comment]
No issues here. just built slacko-6.0.5.0 (32 bit). All works well. @mrfricks - please see the forum for a neat JWM fix for old configs.

**Comment by 01micko** [comment]
@mrfricks .. does this work for you yet? If not, where does it fail? Error message?

**Comment by mrfricks** [comment]
yes it is working.

not sure what was going on before.
thanks
