### ISSUE TITLE
Drop ARMv6 support?

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#597]
Maintaining backward compatibility with Raspberry Pi 1 means binaries like debdb2pupdb (which must be heavily optimized, as fast as possible) are slower than they should on ARMv7, because they're ARMv6 optimized.

Also, building such binaries requires Raspberry Pi's old cross-toolchain.

Therefore, I want to rebuild at least some binaries under support/, with Cortex A9, hard-float optimizations. These binaries should work on any modern ARMv7 system, including Raspberry Pi 2.

@mavrothal @01micko - objections?

**Comment by 01micko** [comment]
No objection. But in future we can add arch=armv6.

Hmmm.. perhaps a better approach is add a new arch, say armv7?

**Comment by dimkr** [comment]
Yeah, you're right. I think I'll add an "armv7" architecture.

**Comment by 01micko** [comment]
Perhaps the current 'arm' arch should be renamed to 'armv6' too, to get past some of the lazy filtering. Just see how you go before we do that. You may not get conflicts.
