### ISSUE TITLE
A backup script so builder changes don't get nuked.

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#599]
The essential things to backup are : 
 - kernel-kit (if there is a built kernel in there)
 - DISTRO_SPECS
 - DISTRO_PKGS_SPECS-*-* 

Others useful to distro maintainers may include the Packages-puppy* files.

**Comment by mavrothal** [comment]
Can you be a bit less abstract? ;)

**Comment by 01micko** [comment]
This -

```
#!/bin/sh

TODAY=`date +%y%m%d-%H:%M`

# kernel
KFILE=`find kernel-kit/dist -type d -name packages`
[ "$KFILE" ] && echo "Backing up kernel-kit" && mv kernel-kit kernel-kit-${TODAY}
[ $? -ne 0 ] && echo "failed to backup kernel-kit"

# files
for i in Packages-puppy* DISTRO_SPECS DISTRO_PKGS_SPECS* ;do
	echo "backing up $i"
	cp -af $i ${i}-${TODAY}
	[ $? -ne 0 ] && echo "failed to backup $i"
done

echo "Files are backed up with the current date and time appended : $TODAY"
```

Named as 0backup - with a message in the first few lines of merge2out?

**Comment by mavrothal** [comment]
I do not mind the script but I still do not understand. If we are working on a git repo what is the point of a backup?
Are you warring about files changed in the woof-out and then deleted by another merge2out?

**Comment by 01micko** [comment]
It is simply a tool. That's all. I always make backups when updating in case I make a change. 

Really, the important one is kernel-kit. Why would you want to nuke it if you just built a kernel and realise that woof-ce has been updated while your kernel is building and you want to use the latest :smile: ?
