### ISSUE TITLE
gtkdialog/box_*, pupmessage do not internationalise

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#601]
It would appear that strings passed with /usr/lib/gtkdialog/box_* fail to internationalise.
This is also true for pupmessage (that is not even internationalised itself!).
See relevant discussion [here] (http://www.murga-linux.com/puppy/viewtopic.php?p=867192#867192) and for the few next posts.

**Comment by 01micko** [comment]
Maybe ziggy can fix the *box thing but pupmessage *needs* to die a sudden death. pupdialog should die too, but it would be a fair amount of work; as far as I know only used for shutdown. Is it used elsewhere?

**Comment by mavrothal** [comment]
Too many scripts use pupdialog and pupmessage. 
A fast search for pupdialog shows that
```
/usr/local/petget/installpreview.sh uses it
/usr/local/apps/Trash/AppRun uses it
/usr/local/apps/Trash/template/temp-AppRun uses it
/usr/bin/pupdialog uses it
/usr/bin/pupmessage uses it
/usr/sbin/momanager uses it
/usr/sbin/shutdownconfig uses it
/usr/sbin/filemnt uses it
/usr/sbin/quicksetup uses it
/usr/sbin/bootmanager uses it
/usr/sbin/edit-initramfs uses it
/usr/sbin/floppy-format.sh uses it
/usr/sbin/hostname-set uses it
/usr/sbin/lang2initrd uses it
/usr/sbin/mousecheck uses it
/usr/sbin/pdiag uses it
/usr/sbin/root2user uses it
```
for pupmessage is even worse:
```
/usr/local/bin/drive_all uses it
/usr/local/petget/service_pack.sh uses it
/usr/local/petget/petget uses it
/usr/local/petget/installpkg.sh uses it
/usr/local/petget/findnames.sh uses it
/usr/local/petget/removepreview.sh uses it
/usr/local/petget/devx_service_pack.sh uses it
/usr/local/simple_network_setup/sns uses it
/usr/local/video_upgrade/video_upgrade_wizard uses it
/usr/bin/pupmessage uses it
/usr/sbin/shutdownconfig uses it
/usr/sbin/xorgwizard uses it
/usr/sbin/remasterpup2 uses it
/usr/sbin/sfsget uses it
/usr/sbin/filemnt uses it
/usr/sbin/pmount uses it
/usr/sbin/puppyinstaller uses it
/usr/sbin/bcrypt_gui uses it
/usr/sbin/bootflash uses it
/usr/sbin/bootmanager uses it
/usr/sbin/burniso2cd uses it
/usr/sbin/cdburner-wizard uses it
/usr/sbin/loginmanager uses it
/usr/sbin/resizepfile.sh uses it
/usr/sbin/savesession-dvd uses it
/usr/sbin/user2root uses it
/usr/sbin/xdelta_gui uses it
```

**Comment by 01micko** [comment]
```
# ./pupmessage 
Partial replacement for xmessage.
Can use only -bg -fg -timeout -title -center (default)
ex: pupmessage -bg '' -title 'Title of popup' 'Body text here'
Note: use 'pupkill ' to kill a pupmessage window.# ./pupmessage 
Partial replacement for xmessage.
Can use only -bg -fg -timeout -title -center (default)
ex: pupmessage -bg '' -title 'Title of popup' 'Body text here'
Note: use 'pupkill ' to kill a pupmessage window.
```

Here I fail to see the point of its creation? Wht's wrong with gxmessage? All calls to pupmessage could use (and maybe did before) xmessage (gxmessage).

**Comment by 01micko** [comment]
Wow. In the example in the *help* it doesn't even work! It has to die!

**Comment by mavrothal** [comment]
Go ahead!
I'm not sure of the value of all these "message display scripts" but I have the sense that will be a nightmare for translations if indeed the strings that are called with, need to be in their own (pupmmesage,pupdialog, libstartdust) TEXTDOMAIN instead of the one of the calling script.

**Comment by mavrothal** [comment]
BTW, I think that zigbert, is not watching activity in woof-CE anymore (is not in the watch list - too many mails I guess), so If anyone has any ideas...

**Comment by zigbert** [comment]
I am here - just too busy at the moment. This could be a nice WOC (winter of code) for me if you don't rush ... but first jwm_config and ptheme...

**Comment by mavrothal** [comment]
Recent changes in PPM and the new (10/10/2015) momanager version solves the internationalization/translation issues.
The future use of pupmessage and pupdialog remains but this can be new issue.

**Comment by zigbert** [comment]
Are there any thought of how to update ie. pupmessage. What arguments to use gxmessage, Xdialog or lib/gtkdialog?
