### ISSUE TITLE
Retire /usr/X11R7 dir and symlinks.

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#602]
There is nothing there except for xmessage, which can be moved to /usr/local/bin instead (IIRC xorg_base template takes care of that).

**Comment by dimkr** [comment]
In Librepup xmessage is a symlink to gxmessage, so maybe it should be moved to its template, under /usr/bin.

**Comment by mavrothal** [comment]
Yeah. Even [BK retired it] (http://bkhome.org/news/?viewDetailed=00260) ;)

**Comment by 01micko** [comment]
```
# find . -name X11R7
./woof-code/rootfs-skeleton/usr/X11R7
./woof-code/packages-templates/xorg_base_baby/usr/X11R7
./woof-code/packages-templates/dotpuphandler/usr/X11R7
./woof-code/packages-templates/xorg73_base_t2/usr/X11R7
./woof-code/packages-templates/xorg_base_t2/usr/X11R7
./woof-code/packages-templates/libgl/usr/X11R7
./woof-code/packages-templates/xorg_base_t2quirky6/usr/X11R7
./woof-code/packages-templates/mesa_base/usr/X11R7
./woof-code/packages-templates/libpciaccess/usr/X11R7
```

Damn! We up for removing legacy builds too?

**Comment by mavrothal** [comment]
what about ```ln -s . /usr/X11R7``` when legacy pups are built.
Though I think 2.x-4.x puppies where produced with *unleash*. Is only wary/racy 5.x that will need this. So maybe add the above soft link in rootfs-skeleton by merge2out when wary/racy is selected

**Comment by 01micko** [comment]
I'm just testing something. In the xorg_base FIXUPHACK I moved xmessage to usr/local/bin and in the pinstall.sh I have `rm -rf usr/X11*`.

If that works ok, then I think that will do.

**Comment by 01micko** [comment]
Looks ok :+1: 
![3builddistro 2](https://cloud.githubusercontent.com/assets/1019119/10425632/6be5fe40-711c-11e5-871f-54f3cd488f30.png)
