### ISSUE TITLE
rootfs-skeleton packages are not reported in the woof-installed-packages

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#608]
Moving pets from common/noarch repos to rootfs-packages we have to modify findwoofinstalledpkgs to detect them and record them so PPM will not offer to re-install them. 
Also have them in the builtin files so sudo-removal can work.

**Comment by 01micko** [comment]
Yes, so really each one needs a pet.specs file. That will solve the version info too.

**Comment by 01micko** [comment]
Ok, I'll work on a solution.

Here is my idea.

1. Add the pet.specs as described above

2. Move the call to `findwoofinstalledpkgs` below the GUI selector for `rootfs-packages`.

3. Keep a record of what's installed in /tmp or something then run a modified `findwoofinstalledpkgs` which picks them up.

4. Later down, when the 'pet package' for builtin files gets built we refer to our record in /tmp and switch into `rootfs-packages` to grab the relevant files.

5. Done, then clean up.

**Comment by 01micko** [comment]
@zigbert 

I need to know what versions your packages are at.

Temporarily (for the sake of the exercise) I will put them both at 0.5. This can be easily changed later on.

**Comment by 01micko** [comment]
Haha! Got it working.

here is an example of the file in /root/.packages/builtin_files

```
/usr
/usr/sbin
 change_kernels
/usr/share
/usr/share/doc
/usr/share/doc/nls
/usr/share/doc/nls/change_kernels
 change_kernels.pot
```
..and the woof-installed-packages file

```
caps-0.4.5-i686_slk600|caps|0.4.5-i686_slk600||BuildingBlock|40||caps-0.4.5-i686_slk600.pet|+alsa-lib,+alsaequal|CAPS is a collection of LADSPA audio plugins||||
cddetect-2.2-i686_slk600|cddetect|2.2-i686_slk600||BuildingBlock|36||cddetect-2.2-i686_slk600.pet||utility for CD detection|slackware|14.1||
cdparanoia-III_10.2|cdparanoia|III_10.2|1|BuildingBlock|350K|slackware/ap|cdparanoia-III_10.2-i486-1.txz||digital audio extraction tool|slackware|14.1||
cdrtools-3.01a17|cdrtools|3.01a17|1|BuildingBlock|4060K|slackware/ap|cdrtools-3.01a17-i486-1.txz|+acl,+attr,+libcap,+zlib|CD R ISO and related tools|slackware|14.1||
change_kernels-0.3|change_kernels|0.3||BuildingBlock|52K||change_kernels-0.3.pet|+gtkdialog|a gtkdialog gui script to change huge kernels||||
chmlib-0.40|chmlib|0.40|2|BuildingBlock|180K|slackware/l|chmlib-0.40-i486-2.txz||library for accessing CHM files|slackware|14.1||
coreutils-8.21|coreutils|8.21|1|BuildingBlock|13340K|slackware/a|coreutils-8.21-i486-1.txz|+acl,+attr,+libcap|core GNU utilities|slackware|14.1||
cpio-2.11|cpio|2.11|2|Utility;package|820K|slackware/a|cpio-2.11-i486-2.txz||backup and archiving utility|slackware|14.1||
cups-1.5.4|cups|1.5.4|4_slack14.1|System;print|10540K|patches/packages|cups-1.5.4-i486-4_slack14.1.txz||Common UNIX Printing System|slackware|14.1||
```

Just some tidying up to do.

**Comment by mavrothal** [comment]
That is nice.
So you *manually* add a specs file in each or called the relevant segment from dir2pet? ;)
Is probably better to leave it for latter, but instead we could just visit roofs-skeleton early on (at the end of 2download), make pets and add them in the pet folder, and then go with business as usual. We'll just need to add a version file at the root of each package folder and mod dir2pet to read it.
Down the road will facilitate move to petbuilds of everything and a fully package-based building (woof-ng). Pets would also allow easy updates to older systems (though you can always make a pet latter)

**Comment by 01micko** [comment]
>So you manually add a specs file in each or called the relevant segment from dir2pet? ;)

I made pets then copied in the pet.specs

> probably better to leave it for latter, but instead we could just visit roofs-skeleton early on (at the end of 2download), make pets and add them in the pet folder, and then go with business as usual. We'll just need to add a version file at the root of each package folder and mod dir2pet to read it.

That kind of defeats the purpose. May as well have them as pets in the beginning. The way I have done it is good enough I think. Maybe just a record in /root/.packages of what rootfs-packages are installed. Perhaps `rootfs-installed-packages`. That would tidy everything up without further ado.

**Comment by mavrothal** [comment]
Maybe you are right.
In my mind the only real reason to have rootfs-packages is to maintain them properly instead of hunting the forum.
How they'll get integrated into the builds  it depends on who is writing the code ;)

**Comment by 01micko** [comment]
If you are happy with this I'd say it's solved.

**Comment by mavrothal** [comment]
Sure.
