### ISSUE TITLE
monospace fonts

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#611]
The recent removal of the old type 1 fonts ( e8571f4 ) generates UI issues in apps that use it by default (geany or IPinfo for example). Could they be aliased (maybe in profile) to a TTF or TrueType monospace font so not every app that uses it needs to be re-written or at best reconfigured?
If not possible we may want to consider re-instating them.

**Comment by dimkr** [comment]
The addition of DejaVu Mono should fix those issues - works fine in Librepup. You can check how your Puppy behaves by adding this font manually - the effect appears immediately.

**Comment by 01micko** [comment]
@mavrothal can you be more specific?

Geany and ipinfo work fine here. The only problem I had was with xcalc, and made a template to delete the .desktop if its not part of the xorg packages (optional). I have galculator anyway.

**Comment by mavrothal** [comment]
In Slacko you use Nimbus mono and is OK. Tahr and Libre use Droid Sans mono and is a mess.
Adding Nimbus mono or DejaVu mono as Igu said is OK in Libre but not in Tahr64. 
Radky was also complaining about this and sys-info (see pic from Tahr64 with DejaVu mono installed).
<img width="644" alt="fonts" src="https://cloud.githubusercontent.com/assets/1014999/10710057/f0dd2e9e-7a4e-11e5-83e3-505d9b928dfd.png">

**Comment by mavrothal** [comment]
It would appear that the problem is the fonts.cong used in TahrPup. I have no idea where is coming from (is not in woof and does not appear to come from Ubuntu) but if you replace it with one from Lible or Slacko 6060, and provide another TTF/TrueType mono font, everything is fine.
Bottom line: Avoid Droid Sans Mono font and do not use whatever Phill used as fonts.conf

**Comment by dimkr** [comment]
@mrfricks - you should add fontconfig-config to tahrpup, to make fonts smooth as in Ubuntu.

**Comment by mavrothal** [comment]
Turns out the problem is that the new monospace fonts were not in the preffered list.
Added these in the fonts-puppy in 3e84dbb but if you use a compat-distro derived fonts.conf you may need to add any extra fonts as in the case of Droid Sance Mono. 
Everything works fine olso only with Droid if it is present in the reffered list.
