### ISSUE TITLE
kernel-kit : incorrect kernel version directory in source sfs

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#614]
@dimkr - there is a bug with the kernel-sources sfs where the directory at /lib/modules is miss-named to `${kernel_major_version}$custom_suffix`. It should be `${kernel_version}$custom_suffix` if we didn't patch SUBLEVEL.

Just digressing a little, have you reached a decision whether `SUBLEVEL =` is the correct entry or should it be `SUBLEVEL = 0`? If the latter is the case, maybe you should reset the kernel version when Makefile gets patched.

**Comment by dimkr** [comment]
SUBLEVEL = 0 is the right thing to do. There's no reason not to do this version patching if everything works fine - you get extra compatibility.

Try now - if setting to 0 doesn't work, I'll do a thorough investigation.

**Comment by 01micko** [comment]
Ok, I'll do some hacking in build.sh and produce a kernel. I'll set SUBLEVEL = 0 then reset the kernel_version=3.14.0 at that point, then patch where the sfs gets built with what I have above.

**Comment by dimkr** [comment]
Just merge be436ae from testing to fdrv, should be easier.

**Comment by 01micko** [comment]
wow.. it's a bit more broken than I thought. I'll have to recompile all my recent kernels.

What happens is that dangling (wrong) symlinks are in the kernel package and since kernel source goes to a lower AUFS layer they take priority. The dangling links were supposed to get deleted. Adding a new variable name `kernel_srcsfs_version` and making kernel version equal that fixes it. In the case of sublevel=yes the `kernel_srcsfs_version=${kernel_major_version}.0`. Should be fine once I commit. Tested sane, no dangly symlinks and /lib/modules/`uname -r`/{source,build} both point to /usr/src/linux.

**Comment by 01micko** [comment]
I thinks it's all good now.

**Comment by mavrothal** [comment]
I guess I'm too late in the part but I noticed the complain in be436ae so... 
It is some time that I did not build a kernel but as far as I remember kernel also accepts ```EXTRAVERSION``` in its Makefile. So you can  have major minor and sub as is, and add any other naming/numbering with extraversion. You may just need to ```sed -rie 's/echo "\+"/#echo "\+"/' scripts/setlocalversion``` that (used to be/still is ?) present in some sources.

**Comment by 01micko** [comment]
It's been there from the very start, even in the old 2 series kernel-kit

**Comment by mavrothal** [comment]
So why not use this to name the kernel libre/puppy/something and leave subversion as is?
