### ISSUE TITLE
Printing support should be optional

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#619]
I want to remove CUPS and everything related to printing from Librepup. It's a nightmare to debug CUPS, it's huge and I'm pretty sure only a fraction of users actually uses it.

@zigbert - should I add a [ -n "`which cupsd`" ] check to all printing-related wizards with some friendly error message?

**Comment by zigbert** [comment]
You have closed this? Does it mean you have fixed it?
Else, I think the easiest way would be to deactivate the print-button in wizardwizard if cupsd is missing

**Comment by dimkr** [comment]
01micko and mavrothal convinced me not to remove CUPS :confused:

**Comment by 01micko** [comment]
Hmmm.... IMHO all full puppies should include CUPS.

That said, we should be able to build minimal pups in woof which would probably not include CUPS, a browser, abiword etc. This needs a new issue. I'll do it soon.
