### ISSUE TITLE
findpkgs adds IDLE to Python

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#622]
```
yes|python|python,python2.7-minimal,python2.7,libpython2.7,libpython2.7-stdlib,libpython2.7-minimal|exe,doc,nls| #121022 moved from devx to main f.s. /usr/include/python2.7 must also go into main f.s. so take out ,dev. see also libpython2.7 needed by gdb in devx. 130404 added libs.
```

For some reason, this Python package also includes IDLE, although this package was not specified.

**Comment by 01micko** [comment]
does adding `-IDLE` (or whatever the actual generic name is) on the end of the deps sting avoid grabbing it?

**Comment by dimkr** [comment]
I don't know, but that's a workaround. I haven't specified idle, why does this package get added?
