### ISSUE TITLE
Support a minimal install

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#623]
@dimkr closed the issue #619 about removing CUPS but we really should support a minimal install. Even without X, but that is probably only ~~possible~~ practical after we boot Xorgwizard (#583).

CUPS, browser, defaultwordprocessor, defaultmediaplayer, defaultspreadsheet etc should be made optional.

Apart from wizard detection of such, the PuppyPin (usually part of rox-filer package) would need to be edited on the fly if the default set out is used.

**Comment by wdlkmpx** [comment]
I have edited and added some /usr/local/bin/default* files

This is how my defaultwordprocessor looks like:

	#!/bin/sh

	if which wps &>/dev/null ; then # kingsoft office
		exec wps "$@"
	fi

	if which abiword &>/dev/null ; then
		exec abiword "$@"
	fi

	yad --title="Error" --image="dialog-error" --button="OK":0 \
	--text="There's no program to handle this file, install Kingsoft Office" \
	--center --on-top --fixed --sticky --borders="4" && exit 1

Basically it just notifies the user there is no defaultwordprocessor

This is my 'defaultrun'


	#!/bin/sh
	#arch compat

	[ ! "$DISPLAY" ] && exit

	# generic
	if which gmrun &>/dev/null ; then
		exec gmrun
	fi

	# lxde
	if pidof lxpanel &>/dev/null ; then
		exec lxpanelctl run
	fi
	if pidof lxpanelx &>/dev/null ; then
		exec lxpanelxctl run
	fi

	# xfce
	if which xfce4-appfinder &>/dev/null ; then
		exec xfce4-appfinder
	fi

	# kde
	if which krunner &>/dev/null ; then
		exec krunner
	fi

	# gtkdialog - prun 
	if which prun &>/dev/null ; then
		exec prun
	fi

	# yad 
	if which yad &>/dev/null ; then
		exe=$(yad --center --title "Run" --entry --window-icon=/usr/share/pixmaps/run48.png)
		[ "$exe" ] && exec $exe
	fi

	# extra
	if which lxterminal &>/dev/null ; then
		exec lxterminal
	fi

	if which xterm &>/dev/null ; then
		exec xterm 
	fi

	### END ###

This is a generic way to run whatever program is installed

.jwmrc
<Key mask="4" key="r">exec:defaultrun</Key>

So when I press Win+R, it will pop up something

**Comment by gyrog** [comment]
Sorry about commenting on an "old" issue.
But couldn't this be implemented with an adrv?
If all the "optional" apps and all their supporting fles are in an adrv then,
with an adrv you get a normal puppy,
without an adrv you get a minimal puppy.
There could also be alternate adrv's with different application collections.

**Comment by peabee** [comment]
It probably needs some changes to the format of DISTRO_PKGS_SPECS-* to 
indicate which items should go into the adrv

+ changes to 3builddistro-Z to package those items as an adrv and 
include the adrv in the iso.....

I'm doing an embryo version of this in LxPupSc with the browser in an 
adrv - but manual intervention during 3builddistro-Z is needed....

**Comment by dimkr** [comment]
I think this one is fixed, sort of. Most broken root-skeleton applications and menu entries are deleted by 3builddistro now, there's a minimal pinboard layout, and it's easy to build a minimal Puppy by removing all applications from DISTRO_PKGS_SPECS and letting petbuild build just the core set of applications (optionally, put them in adrv).
