### ISSUE TITLE
remove jwm *-colors files

### ISSUE THREAD

**Issue by zigbert** [puppylinux-woof-CE/woof-CE#624]
$HOME/.jwm/jwm_colors is a ancient mechanism that never came to use. Only absvolume read its swallowed background color from this theme file. We don't use absvolume anymore, we don't require jwm anymore, we don't need it anymore. A global search lead me to:
- $HOME/.xinitrc
- /usr/sbin/remasterpup2
- /usr/local/jwm_config/theme-switcher
I have removed code related to jwm *-colors in these files

Now, a jwm-theme is only 1 file if you use jwm_config. The original setup requires 4 files.

Please remove colors files in the Stardust themes:
https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-code/rootfs-packages/jwm_config/usr/share/jwm/themes

and the default file:
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-packages/jwm_config/root/.jwm/jwm_colors

**Comment by mavrothal** [comment]
You can delete a file through the github web UI ;)

**Comment by zigbert** [comment]
Didn't know, thank you :)

**Comment by zigbert** [comment]
Didn't know, thank you :)
