### ISSUE TITLE
Put unsupported distros out to 'pasture'

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#625]
Arch, mageia, scientific (and other more or less 'discontinued support') distros maybe should go in a 'pasture' directory.

I don't want to delete them, because maybe someone will come along with a keen interest and fix them.

**Comment by ASRIedu** [comment]
I agree with you.

**Comment by mavrothal** [comment]
After merging to master ;)

**Comment by 01micko** [comment]
Agreed.

**Comment by 01micko** [comment]
Ok, since we agree, I'll close this.
