### ISSUE TITLE
jwm_config: themes needs some reasonable sane defaults

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#626]
In woof, if I include old themes for JWM then we end up with a small mess. 

Perhaps some reasonable defaults (with a choice in the pinstall.sh maybe? Which could include the corresponding gtk-theme) could be set then we can avoid the GUI to choose jwm theme, gtk theme, icons if we are using jwm_config.

**Comment by mavrothal** [comment]
What is the mess? 
Some old themes work fine. Others do not work at all but they also do not show as choices in jwm_cofig/pTheme.
If we know which ones work we could just blacklist (remove from SPECS) the rest.

**Comment by 01micko** [comment]
The mess is at the woof stage.

Old themes aren't really compatible with jwm_config so we need a better way to make the selection of theme and wallpaper in woof. Doing it by chroot isn't pretty!

**Comment by 01micko** [comment]
Ok, I'm working on the pinstall in jwm_config and ptheme to add the jwmrc-theme choice from jwm_config and likewise gtk theme choice from ptheme. This will keep things somewhat consistent with ptheme. While we are there I'm adding wallpaper choice, as the new walls from my mkwallpaper (if it exists) have just been created. Then, if default.$ext wallpaper exists we avoid BK's old theme chooser gui.

ATM it's only CLI but gui dropdown lists can be added later.

**Comment by mavrothal** [comment]
What about if a builder decides to not include jwm_config/pTheme? Will the chooser gui still be available?
BTW, should we add this issue in the ["late 2015 release"] (https://github.com/puppylinux-woof-CE/woof-CE/milestones/15R.%20Late%202015%20releases )milestone? ;-)

**Comment by 01micko** [comment]
Yes!

**Comment by 01micko** [comment]
Anyway, I'm gonna try a different approach. I'll suggest to @zigbert perhaps a `ptheme -woof` cli option that doesn't run all the restarts of JWM, rox-filer etc but just sets the appropriate files. My experiment worked but I don't like it.

**Comment by 01micko** [comment]
Well I back-flipped again and went with the pinstall.sh approach.

@zigbert -  here is my proposal for 'poor man's ptheme' usable from the woof building environment: (can be made a GUI later)

```shell
# pinstall for ptheme
############################################################################
echo

for dtop in switch2 GTK-Chtheme icon_switcher; do
    [ -f "usr/share/applications/${dtop}.desktop" ] || continue
    if grep -q "^NoDisplay" usr/share/applications/${dtop}.desktop; then
        sed -i 's%NoDisplay=.*%NoDisplay=true%' usr/share/applications/${dtop}.desktop
    else
        echo 'NoDisplay=true' >> usr/share/applications/${dtop}.desktop
    fi
done

# poor man's pTheme!
# choose a JWM theme
############################################################################
echo
[ -f /tmp/jwm_theme_choose ] && rm /tmp/jwm_theme_choose
echo "You can choose from the following JWM themes"
echo
num=1
for i in `ls usr/share/jwm/themes|grep -v 'colors$'`;do
	echo "$num $i"
	echo "$num $i" >> /tmp/jwm_theme_choose
	num=$(($num + 1))
done
echo
echo "Type the number of the theme you want"

xnum=1
theme=""
while [ $xnum -lt 4 ];do
	read jwm_num
	echo "$jwm_num" | grep -qv '[0-9]' && echo "A number is needed" && continue
	if grep -q ${jwm_num} /tmp/jwm_theme_choose;then
		theme=`grep -w "${jwm_num}" /tmp/jwm_theme_choose|cut -d ' ' -f2`
		echo "You chose ${theme}. Excellent choice."
		break
	else
		if [ $xnum -lt 3 ];then
			echo "Sorry, that didn't work, try another number"
		else
			echo "Last chance..."
		fi
		xnum=$(($xnum + 1))
	fi
done
if [ -z "$theme" ];then
	theme=Stardust_bright-jwmrc
	echo "OK, you didn't choose, defaulting to $theme"
fi
echo "Setting $theme to default"
cp -af usr/share/jwm/themes/${theme} root/.jwm/jwmrc-theme
sleep 1 # reading time

# choose a gtkrc theme
############################################################################
echo
[ -f /tmp/gtk_theme_choose ] && rm /tmp/gtk_theme_choose
echo "You can choose from the following GTK themes"
echo
anum=1
for i in `ls -1 usr/share/themes`;do
	echo "$anum $i"
	echo "$anum $i" >> /tmp/gtk_theme_choose
	anum=$(($anum + 1))
done
echo
echo "Type the number of the theme you want"

ynum=1
my_theme=""
while [ $ynum -lt 4 ];do
	read gtk_num
	echo "$gtk_num" | grep -qv '[0-9]' && echo "A number is needed" && continue
	if grep -q ${gtk_num} /tmp/gtk_theme_choose;then
		my_theme=`grep -w "${gtk_num}" /tmp/gtk_theme_choose|cut -d ' ' -f2`
		echo "You chose ${my_theme}. Excellent choice."
		break
	else
		if [ $ynum -lt 3 ];then
			echo "Sorry, that didn't work, try another number"
		else
			echo "Last chance..."
		fi
		ynum=$(($ynum + 1))
	fi
done
if [ -z "$my_theme" ];then
	my_theme=Stardust_bright_mouse
	echo "OK, you didn't choose, defaulting to $my_theme"
fi
echo "Setting $my_theme to default"

cat > root/.gtkrc-2.0 << _EOF
# -- THEME AUTO-WRITTEN BY gtk-theme-switch2 DO NOT EDIT
include "/usr/share/themes/$my_theme/gtk-2.0/gtkrc"

style "user-font"
{
  font_name=""
}
widget_class "*" style "user-font"

include "/root/.gtkrc-2.0.mine"

# -- THEME AUTO-WRITTEN BY gtk-theme-switch2 DO NOT EDIT
gtk-theme-name = "$my_theme"
_EOF

sleep 1 # reading time

# we'll do wallpaper while we're here
############################################################################
echo
[ -f /tmp/wall_choose ] && rm /tmp/wall_choose
echo "You can choose from the following wallpapers"
rox usr/share/backgrounds
echo
bnum=1
for i in `ls -1 usr/share/backgrounds|sed 's| |_|'`;do
	echo "$bnum $i"
	echo "$bnum $i" >> /tmp/wall_choose
	bnum=$(($bnum + 1))
done
echo
echo "Type the number of the wallpaper you want"

znum=1
my_wall=""
while [ $znum -lt 4 ];do
	read wall_num
	echo "$wall_num" | grep -qv '[0-9]' && echo "A number is needed" && continue
	if grep -q ${wall_num} /tmp/wall_choose;then
		my_wall=`grep -w "${wall_num}" /tmp/wall_choose|cut -d ' ' -f2`
		echo "You chose ${my_wall}. Excellent choice."
		break
	else
		if [ $znum -lt 3 ];then
			echo "Sorry, that didn't work, try another number"
		else
			echo "Last chance..."
		fi
		znum=$(($znum + 1))
	fi
done
if [ -z "$my_wall" ];then
	my_wall="Stardust bright.svg"
	echo "OK, you didn't choose, defaulting to $my_wall"
else 
	if echo "$my_wall"|grep -q '_' ;then
		my_wall="`echo "$my_wall"|sed 's|_| |'`"
	fi	
fi
echo "Setting $my_wall to default"
ext="${my_wall##*.}"
mv -f usr/share/backgrounds/"$my_wall" usr/share/backgrounds/default.${ext}

sleep 1 # reading time

# and rox pinboard - remember the wallpaper
############################################################################
echo
[ -f /tmp/ptheme_roxpins ] && rm /tmp/ptheme_roxpins
pnum=1
for pin in `ls usr/share/ptheme/rox_pinboard|sed 's| |_|'`;do
	echo "$pnum $pin"
	echo "$pnum $pin" >> /tmp/ptheme_roxpins
	pnum=$(($pnum + 1))
done
echo
echo "Type the number for the rox pinboard that you want to choose."

onum=1
my_pin=""
while [ $onum -lt 4 ];do
	read pin_num
	echo "$pin_num" | grep -qv '[0-9]' && echo "A number is needed" && continue
	if grep -q ${pin_num} /tmp/ptheme_roxpins;then
		my_pin=`grep -w "${pin_num}" /tmp/ptheme_roxpins|cut -d ' ' -f2`
		echo "You chose ${my_pin}. Excellent choice."
		break
	else
		if [ $onum -lt 3 ];then
			echo "Sorry, that didn't work, try another number"
		else
			echo "Last chance..."
		fi
		onum=$(($onum + 1))
	fi
done
if [ -z "$my_pin" ];then
	my_pin="Puppy Standard"
	echo "OK, you didn't choose, defaulting to $my_pin"
else 
	if echo "$my_pin"|grep -q '_' ;then
		my_pin="`echo "$my_pin"|sed 's|_| |'`"
	fi
fi
echo "Setting $my_pin to default pinboard"
BACKDROP="  <backdrop style=\"Stretched\">/usr/share/backgrounds/default.${ext}</backdrop>"
echo -e '<?xml version="1.0"?>\n<pinboard>' > /tmp/newpin
echo "$BACKDROP" >> /tmp/newpin
cat usr/share/ptheme/rox_pinboard/"$my_pin" >> /tmp/newpin
echo '</pinboard>' >> /tmp/newpin
cp -a /tmp/newpin root/Choices/ROX-Filer/PuppyPin

sleep 1 # reading time

# might as well do icons too..
############################################################################
echo
[ -f /tmp/ptheme_icons ] && rm /tmp/ptheme_icons
inum=1
for icn in `ls usr/local/lib/X11/themes`;do
	echo "$inum $icn"
	echo "$inum $icn" >> /tmp/ptheme_icons
	inum=$(($inum + 1))
done
echo
echo "Type the number for the icon theme that you want to choose."

enum=1
my_icon=""
while [ $enum -lt 4 ];do
	read icon_num
	echo "$icon_num" | grep -qv '[0-9]' && echo "A number is needed" && continue
	if grep -q ${icon_num} /tmp/ptheme_icons;then
		my_icon=`grep -w "${icon_num}" /tmp/ptheme_icons|cut -d ' ' -f2`
		echo "You chose ${my_icon}. Excellent choice."
		break
	else
		if [ $enum -lt 3 ];then
			echo "Sorry, that didn't work, try another number"
		else
			echo "Last chance..."
		fi
		enum=$(($enum + 1))
	fi
done
if [ -z "$my_icon" ];then
	my_icon="StandardSvg"
	echo "OK, you didn't choose, defaulting to $my_icon"
fi
echo "Setting $my_icon to default icon theme"
echo -n "$my_icon" > etc/desktop_icon_theme
export my_icon

sleep 1 # reading time

echo
# end poor man's pTheme!
```

Of course this doesn't cover everything but will pick up user installed pet packaged 'pthemes'. I am thinking whether to add window icon button support; shouldn't be too difficult. Also works (probably better) if NO extra JWM themes are installed.

Of course a few minor changes are needed in 3builddistro{-Z} to support this.

**Comment by mavrothal** [comment]
The entire rootfs-packages must move way down in the process. Now is even before the package installation I think

**Comment by zigbert** [comment]
If ptheme is installed, I don't understand why not just choose a global theme. One click, and you get a thoughtful desktop. Design is important, and we can here challenge the kennel outside Woof to design a brilliant Puppy desktop. I see that restarting jwm/rox/gtk is wrong, but this is very easy to change ie. by a -woof parameter.

**Comment by mavrothal** [comment]
This is during build time where the builder must decide how (s)he would like the pupplet to look like.
How could you do that "one click" at built time? Does jwm_config/ptheme take cli arguments?

**Comment by zigbert** [comment]
Yes, pTheme takes cli arguments:
ptheme -p "theme"
But this also restarts jwm, rox and gtk, so if this is the way we choose, we need a new parameter to not update these. Something like:
ptheme -w -t "theme"
This is easy for me to implement if you wish.

**Comment by zigbert** [comment]
As a notice:
I have been looking at the corner actions which now are deactivated in _root_jwmrc.
I have made it work, but jwm has done some changes that harms its beauty.
borders can not be set in jwm 2.3.2. They are always 1 pixel, and that means; when we place a tray (what a corner action is) in a corner it won't give any action when you drag the mouse in the absolute corner - because you hit the border. Corner actions requires either no border or a negative offset - and jwm says it does. X/Y can be a negative integer according to the documentation on the homepage. I could not get this to work, but even if I got it working this could of course not autohide the tray. Simply because you wouldn't reach the negative position to show the tray. So if the offset worked, active corner-actions could be a visible dot (2px) in the corner.

I will fix what I can, and upload, but I think we skip this until we get a decent solution.
I can rebuild pdesktop to hide buttons for corners and applets.

**Comment by 01micko** [comment]
> The entire rootfs-packages must move way down in the process. Now is even before the package installation I think

@mavrothal Why? It's ok where it is. If it is further down then none of the pinstall would get included.

> ptheme -w -t "theme"
This is easy for me to implement if you wish.

@zigbert Of course this is the best solution, so yes please.

**Comment by mavrothal** [comment]
>@mavrothal Why? It's ok where it is. If it is further down then none of the pinstall would get included.

If I understand correctly you wanted to define "looks" from installed theme pets. But the pets are not yet moved into sandbox3/rootfs-complete  when rootfs-packages gets in. So running a pinstall script at this pint will have nothing to install theme-wise other than what it is in rootfs-packages.
AAMOF moving rootfs-packages down is safer as could not be clobbered by any pets

**Comment by 01micko** [comment]
>If I understand correctly you wanted to define "looks" from installed theme pets. But the pets are not yet moved into sandbox3/rootfs-complete when rootfs-packages gets in. So running a pinstall script at this pint will have nothing to install theme-wise other than what it is in rootfs-packages.


This is not a problem. pinstalls are concatenated to the main pinstall.sh that gets run after everything is installed.

>AAMOF moving rootfs-packages down is safer as could not be clobbered by any pets

No. There is no clobbering because we test for that. If there is clobbering then it is a bug that will be fixed. It is best that the choices GUI pops early so we can find out what gets included in the system. I can't see a possible way to run it later, without a lot of work a arounds and overwriting stuff which soon becomes messy.

To my way of thinking now, all we need to do is set the theme from @zigbert 's upcoming cli fix for ptheme (run in chroot). The best place for this is just after the pinstall.sh is run.

BTW, I tested my poor man's ptheme and it worked perfectly. The changes to 3builddistro(-Z) will be the same (or maybe a better test is needed) when `ptheme -w $theme` is run. I tested each scenario, even inputting garbage. Of course it is a futile exercise in some ways, but in the context of the theme setting we are getting somewhere toward solving my original issue.

I tested for usr/share/backgrounds/default.$ext wallpaper, but a bool value could be set instead as to whether ptheme exists or not and then BK's old gui can run if ptheme is skipped (ie: jwmconfig3 is present).

**Comment by zigbert** [comment]
Ok, I spent 4 hours trying to make a woof mode of pTheme, but tough case. it depends on too many external tools - I began to see a mess, and returned to Mick's Poor mans ptheme. I made your code more like pTheme - handling one global theme instead of the one-by-one approach which seems more logical if pTheme is not installed.

Feel free to do whatever you want...
```
# pinstall for ptheme
############################################################################
echo

for dtop in switch2 GTK-Chtheme icon_switcher; do
    [ -f "usr/share/applications/${dtop}.desktop" ] || continue
    if grep -q "^NoDisplay" usr/share/applications/${dtop}.desktop; then
        sed -i 's%NoDisplay=.*%NoDisplay=true%' usr/share/applications/${dtop}.desktop
    else
        echo 'NoDisplay=true' >> usr/share/applications/${dtop}.desktop
    fi
done

# poor man's pTheme!
# choose a global theme
############################################################################
echo
[ -f /tmp/ptheme_choose ] && rm /tmp/ptheme_choose
echo "You can choose from the following global themes"
echo
num=1
for i in `ls usr/share/ptheme/globals`;do
    echo "$num $i"
    echo "$num $i" >> /tmp/ptheme_choose
    num=$(($num + 1))
done
echo
echo "Type the number of the theme you want"

xnum=1
theme=""
while [ $xnum -lt 4 ];do
    read ptheme_num
    echo "$ptheme_num" | grep -qv '[0-9]' && echo "A number is needed" && continue
    if grep -q ${ptheme_num} /tmp/ptheme_choose;then
        theme=`grep -w "${ptheme_num}" /tmp/ptheme_choose|cut -d ' ' -f2`
        echo "You chose ${theme}. Excellent choice."
        break
    else
        if [ $xnum -lt 3 ];then
            echo "Sorry, that didn't work, try another number"
        else
            echo "Last chance..."
        fi
        xnum=$(($xnum + 1))
    fi
done
if [ -z "$theme" ];then
    theme=Stardust_bright_mouse
    echo "OK, you didn't choose, defaulting to $theme"
fi
echo "Setting $theme to default"

. usr/share/ptheme/globals/${theme}



##### JWM
cp -af usr/share/jwm/themes/${PTHEME_JWM_COLOR} root/.jwm/jwmrc-theme
echo "jwm colors: ${PTHEME_JWM_COLOR}"

cp -f usr/share/jwm/tray_templates/"$PTHEME_JWM_TRAY"/jwmrc-tray* root/.jwm/
echo "jwm tray: ${PTHEME_JWM_COLOR}"

case $PTHEME_JWM_SIZE in
small) rm root/.jwm/menuheights;;
normal) echo "MENHEIGHT=24" > root/.jwm/menuheights;;
large) echo "MENHEIGHT=32" > root/.jwm/menuheights;;
huge) echo "MENHEIGHT=40" > root/.jwm/menuheights;;
esac
echo "jwm size: ${PTHEME_JWM_SIZE}"

mkdir $HOME/.jwm/window_buttons
Dir=usr/share/jwm/themes_window_buttons/${PTHEME_JWM_BUTTONS}
for icon in $Dir/*; do
	ifile=$(basename $icon)
	ext=${ifile##*.}
	newicon=`echo $ifile|sed "s%${ext}$%png%"`
	#JWM does a crappy svg convert, so we help out if rsvg-convert is installed
	if [ "`which rsvg-convert`" ]; then
		rsvg-convert -w 48 -h 48 -o root/.jwm/window_buttons/${newicon} ${icon}
	else
		ln -sf ${icon} root/.jwm/window_buttons/${newicon}
	fi
done
echo "jwm buttons: ${PTHEME_JWM_BUTTONS}"
sleep 1 # reading time



##### GTK
cat > root/.gtkrc-2.0 << _EOF
# -- THEME AUTO-WRITTEN BY gtk-theme-switch2 DO NOT EDIT
include "/usr/share/themes/${PTHEME_GTK}/gtk-2.0/gtkrc"

style "user-font"
{
  font_name=""
}
widget_class "*" style "user-font"

include "/root/.gtkrc-2.0.mine"

# -- THEME AUTO-WRITTEN BY gtk-theme-switch2 DO NOT EDIT
gtk-theme-name = "${PTHEME_GTK}"
_EOF
echo "gtk: ${PTHEME_GTK}"
sleep 1 # reading time



##### WALLPAPER
ext="${my_wall##*.}"
mv -f usr/share/backgrounds/"${PTHEME_WALL}" usr/share/backgrounds/default.${ext}
echo "wallpaper: ${PTHEME_WALL}"
sleep 1 # reading time



##### ROX
BACKDROP="  <backdrop style=\"Stretched\">/usr/share/backgrounds/default.${ext}</backdrop>"
echo -e '<?xml version="1.0"?>\n<pinboard>' > /tmp/newpin
echo "$BACKDROP" >> /tmp/newpin
cat usr/share/ptheme/rox_pinboard/"${PTHEME_ROX_PIN}" >> /tmp/newpin
echo '</pinboard>' >> /tmp/newpin
cp -a /tmp/newpin root/Choices/ROX-Filer/PuppyPin
echo "rox: ${PTHEME_ROX_PIN}"
sleep 1 # reading time



##### ICONS
echo -n "${PTHEME_ICONS}" > etc/desktop_icon_theme
export ${PTHEME_ICONS}
echo "icons: ${PTHEME_ICONS}"
sleep 1 # reading time



##### CURSOR
[ ! "`grep 'ORIGINAL THEME' <<< "$PTHEME_MOUSE"`" ] && ln -snf root/.icons/$PTHEME_MOUSE root/.icons/default
echo "cursor: ${PTHEME_MOUSE}"
sleep 1 # reading time



##### GTKDIALOG
cp -f "usr/share/ptheme/gtkdialog/$PTHEME_GTKDIALOG" root/.config/ptheme/gtkdialog_active
echo "gtkdialog: ${PTHEME_GTKDIALOG}"
sleep 1 # reading time



echo "done"

**Comment by zigbert** [comment]
I have been editing the previous script the last hour. I am not thinking clear atm. Early hours, and the sun is soon rising. Time to find the pillow :)

**Comment by 01micko** [comment]
I'm sorry ziggy (I should have explained better) but you _can_ use the tools available in the newly built woof system, such as switch2 and others. We can do it in a chroot. What that is a way to run CLI programs inside an independent system. GUI is a no go zone but anything CLI is usable. One problem.. there ore no environmental variables to rely on so $HOME and friends do not work. So maybe the pinstall is better because we can use it at a relative level, such as `root/.jwm`and `usr/share` etc.

**Comment by mavrothal** [comment]
May be a bit late but what about we modify ../support/choose_themes instead and also move lines 1421-1616 of 3bulddistro-Z there?
BTW I still think moving rootfs-packages handling is a good idea. Better prevent a bug than fix it, and install scripts do run with the order loaded (surprisingly I noticed some themes do have pinstall scripts!).

**Comment by 01micko** [comment]
Um you won't prevent any bugs. I am _strongly_ against the idea. It's working fine now.

**Comment by 01micko** [comment]
PS> I already moved the findwoofinstalledpkgs down.. moving it down further wont work.

**Comment by 01micko** [comment]
Maybe the best way, is to get the pinstalls from the rootfs-packages and cat them to a temp file then tack them onto the end of the main pinstall. Is that a reasonable compromise?

**Comment by 01micko** [comment]
>May be a bit late but what about we modify ../support/choose_themes instead and also move lines 1421-1616 of 3bulddistro-Z there?

maybe not that far, still have to create the icons with the square with pngoverlay. I think an if /else from 1421 -1513

**Comment by mavrothal** [comment]
What ever works. Really. There is nothing to "compromise" on. 
I thought that since we have a script for theaming would make sense to use it instead of packing things in to 3builddistro or pinstall scripts. It is a distinct function after building tootfs-complete and relates exclusively with appearance. 
Should be easier/cleaner to maintain and even have provisions according to themes present and  tools to be used, without messing up with the build script per se.
Maybe after merging ;)

**Comment by 01micko** [comment]
>Maybe after merging ;)

:+1: Just for now I'm happy to go with pinstall. Works. I'll probably use my idea of saving to a temp file then tacking on the end of the main pinstall. Haven't tested ziggy's yet but looks ok at a quick glance. After merge we will definitely be more creative!

**Comment by 01micko** [comment]
@zigbert - it almost works perfectly (your pinstall.sh) - couple of bugs with spaces in names that are easy solved but we miss `root/.icons` in the ptheme package! 

I know sleep is valuable so I'll download the latest from the forum and copy the missing cursor icons in to my woof tree. If it all works I'll commit the missing cursor icons.

**Comment by 01micko** [comment]
No.. for now what I'll do is add a test if the cursor themes are there and if not avoid that part of the code.

```shell
if [ -d root/.icons/ ];then
	[ ! "`grep 'ORIGINAL THEME' <<< "$PTHEME_MOUSE"`" ] && ln -snf root/.icons/$PTHEME_MOUSE root/.icons/default
	echo "cursor: ${PTHEME_MOUSE}"
	sleep 1 # reading time
fi
```

**Comment by 01micko** [comment]
Aha! Cursor themes are in the theme pets! So my test is correct :grin:

**Comment by 01micko** [comment]
Stock boot (new iso) - looks good :smile: 

![screenshot](https://cloud.githubusercontent.com/assets/1019119/10905455/0ce2339a-8266-11e5-91c7-ad456df5b76d.png)

Stock boot (brand new iso) with ptheme_winXP in the specs (and unpacked of course). Looks good except for the JWM theme is wrong. More comments below...

![xp](https://cloud.githubusercontent.com/assets/1019119/10905476/3743caa4-8266-11e5-863c-4f0a7ff3362c.png)

Here is the error from `3builddistro-Z`

```shell
You chose winXP. Excellent choice.
Setting winXP to default
cp: cannot stat 'usr/share/jwm/themes/PuppyXPv3': No such file or directory
jwm colors: PuppyXPv3
jwm tray: winXP
jwm size: normal
jwm buttons: XPish
gtk: XPLuna
wallpaper: xp.jpg
rox: Minimal
icons: StandardSvg
cursor: aero
cp: cannot create regular file 'root/.config/ptheme/gtkdialog_active': No such file or directory
gtkdialog: winXP
done
```

Not far off!

NB: XP theme was grapped from here <-- http://murga-linux.com/puppy/viewtopic.php?p=794784#794784

**Comment by zigbert** [comment]
... and the gtkdialog theme is not set by theme.
´´´
[ ! -d root/.config/ptheme/ ] && root/.config/ptheme

**Comment by zigbert** [comment]
I have re-uploaded the winXP theme to
http://murga-linux.com/puppy/viewtopic.php?p=794784#794784
The file was not healty

**Comment by 01micko** [comment]
@zigbert - just one thing with the themes, the Category should be 'Desktop' not 'BuildingBlock' so that PPM can find them :wink: - new screenshots soon.

**Comment by 01micko** [comment]
Oh.. I see what is going on... When I chose 'Stardust Dark' it works because that is the default in jwm_config anyway!

This line is at fault in the pinstall.sh
```
cp -af usr/share/jwm/themes/"${PTHEME_JWM_COLOR}" root/.jwm/jwmrc-theme
```

Perhaps should be

```
cp -af usr/share/jwm/themes/"${PTHEME_JWM_COLOR}-jwmrc" root/.jwm/jwmrc-theme
cp -af usr/share/jwm/themes/"${PTHEME_JWM_COLOR}-colors" root/.jwm/jwm_colors
```

**Comment by 01micko** [comment]
And of course root/.config/ptheme/ might not exist so we may have to make it

```shell
##### GTKDIALOG
[ -d root/.config/ptheme/ ] || mkdir -p root/.config/ptheme/
```

**Comment by 01micko** [comment]
Yes! That's better:

```shell
You can choose from the following global themes

1 Bright Mouse
2 Bright Touch
3 Buntoo
4 Dark Mouse
5 Dark Touch
6 winXP

Type the number of the theme you want
6
You chose winXP. Excellent choice.
Setting winXP to default
jwm colors: PuppyXPv3
jwm tray: winXP
jwm size: normal
jwm buttons: XPish
gtk: XPLuna
wallpaper: xp.jpg
rox: Minimal
icons: StandardSvg
cursor: aero
gtkdialog: winXP
done
```

**Comment by 01micko** [comment]
I'm going to make those commits mentioned in #586 and then we can close this one. I'm pretty happy with the outcome. Thanks @zigbert and @mavrothal

**Comment by 01micko** [comment]
:+1:

**Comment by 01micko** [comment]
@mavrothal 

maybe something like this can be called from rc.update if version is < 6.0. It is similar to the pinstall above and needs to be run before X starts.

```shell
#!/bin/sh
 
grep -q 'jwm' /etc/windowmanager || exit

# if we have basic PoP (plain old puppy) theme we use it, else use 'stardust bright'
# but we leave the user's chosen wall paper.. they will moan enough about icons!

ls /usr/share/ptheme/globals|grep - q 'pop' && THEME='pop' || THEME='Bright Mouse'

if [ -f /usr/share/ptheme/globals/"${THEME}" ];then
	. /usr/share/ptheme/globals/"${theme}"
else
	exit
fi

CUR_BACDROP_LINE="`grep 'backdrop' $HOME/Choices/ROX-Filer/PuppyPin`"
# ah.. but if using a wall on the main sfs it will be gone.. maybe
CUR_WALL="`echo "$CUR_BACDROP_LINE"|tr '/' '\n'|tr '<' '\n'|egrep -i 'png$|svg$|jpg$|jpeg$|gif$|tiff$|background$'`"
# so we drop them off at default wall for install
if ls /usr/share/backgrounds|grep -q "$CUR_WALL";then
	BACKDROP_LINE="$CUR_BACDROP_LINE"
else
	DEF="`ls /usr/share/backgrounds|egrep '^default.png|^default.svg|^default.jpg'|head -n1`"
	BACKDROP_LINE="`echo $CUR_BACDROP_LINE|sed "s%$CUR_WALL%$DEF%"`"
fi

##### JWM
cp -af /usr/share/jwm/themes/"${PTHEME_JWM_COLOR}-jwmrc" $HOME/.jwm/jwmrc-theme
cp -af /usr/share/jwm/themes/"${PTHEME_JWM_COLOR}-colors" $HOME/.jwm/jwm_colors
cp -f /usr/share/jwm/tray_templates/"$PTHEME_JWM_TRAY"/jwmrc-tray* $HOME/.jwm/
case $PTHEME_JWM_SIZE in
	small) rm root/.jwm/menuheights;;
	normal) echo "MENHEIGHT=24" > $HOME/.jwm/menuheights;;
	large) echo "MENHEIGHT=32" > $HOME/.jwm/menuheights;;
	huge) echo "MENHEIGHT=40" > $HOME/.jwm/menuheights;;
esac
mkdir $HOME/.jwm/window_buttons
Dir=/usr/share/jwm/themes_window_buttons/${PTHEME_JWM_BUTTONS}
for icon in $Dir/*; do
    ifile=$(basename $icon)
    ext=${ifile##*.}
    newicon=`echo $ifile|sed "s%${ext}$%png%"`
    #JWM does a crappy svg convert, so we help out if rsvg-convert is installed
    if [ "`which rsvg-convert`" ]; then
        rsvg-convert -w 48 -h 48 -o $HOME/.jwm/window_buttons/${newicon} ${icon}
    else
        ln -sf ${icon} $HOME/.jwm/window_buttons/${newicon}
    fi
done

##### GTK
cat > /root/.gtkrc-2.0 << _EOF
# -- THEME AUTO-WRITTEN BY gtk-theme-switch2 DO NOT EDIT
include "/usr/share/themes/${PTHEME_GTK}/gtk-2.0/gtkrc"

style "user-font"
{
  font_name=""
}
widget_class "*" style "user-font"

include "/root/.gtkrc-2.0.mine"

# -- THEME AUTO-WRITTEN BY gtk-theme-switch2 DO NOT EDIT
gtk-theme-name = "${PTHEME_GTK}"
_EOF

##### ROX
BACKDROP="$BACDROP_LINE"
echo -e '<?xml version="1.0"?>\n<pinboard>' > /tmp/newpin
echo "$BACKDROP" >> /tmp/newpin
while read line;do
	echo "$line" | grep -q 'pup_event' && echo "$line" >> /tmp/newpin || continue
done < $HOME/Choices/ROX-Filer/PuppyPin
cat /usr/share/ptheme/rox_pinboard/"${PTHEME_ROX_PIN}" >> /tmp/newpin
echo '</pinboard>' >> /tmp/newpin
cp -af /tmp/newpin $HOME/Choices/ROX-Filer/PuppyPin

##### CURSOR
if [ -d "$HOME/.icons/" ];then
	[ ! "`grep 'ORIGINAL THEME' <<< "$PTHEME_MOUSE"`" ] && ln -snf $HOME/.icons/$PTHEME_MOUSE $HOME/.icons/default
fi

##### GTKDIALOG
[ -d "$HOME/.config/ptheme/" ] || mkdir -p $HOME/.config/ptheme/
cp -f "/usr/share/ptheme/gtkdialog/$PTHEME_GTKDIALOG" $HOME/.config/ptheme/gtkdialog_active

##### ICONS
icon_switcher_cli -a "${PTHEME_ICONS}"

# end
```

The 'plain old puppy' (pop) theme is up at ibiblio and will be in final. It is what it says; the triangular icon field and no extra trays.

**Comment by mavrothal** [comment]
6+ versions (Tahr) may need it in the future.
You may want to add an early check for the presence of pTheme files and exit instead.
This script should be part jwm_config/pTheme and its call from rc.update should be sed'ed in by the install script in (or around) the conditional update of ```_root_.jwmrc``` (lines 253-6)
Or maybe just stick the call in there regardless of pTheme presence, as long as the script is with the pTheme package

**Comment by 01micko** [comment]
Ok

```
[ -d /usr/share/ptheme ] && exit # should be ok
```

Can be first line.

>This script should be part jwm_config/pTheme and its call from rc.update should be sed'ed in by the install script in (or around) the conditional update of _root_.jwmrc (lines 253-6)
Or maybe just stick the call in there regardless of pTheme presence, as long as the script is with the pTheme package

Whack it in. I'll commit the script to ptheme, just test existence of the script ; it's called by `update_ptheme_fix`.

**Comment by mavrothal** [comment]
There 9721ff4

**Comment by 01micko** [comment]
> There 9721ff4

:+1: 
Hopefully tomorrow I'll upload some deltas. Really my biggest freaking problem is this vast country's lack of bandwidth!!!

It will get there eventually.

**Comment by mavrothal** [comment]
> [ -d /usr/share/ptheme ] && exit # should be ok
But this is always going to be there if we include pTheme.
We should detect this in the OLDFILESMNTPT  savefile/folder/partition

**Comment by 01micko** [comment]
That line was wrong anyway, see 1807ba2 . I'll think more clearly tomorrow... maybe :grinning:

**Comment by mavrothal** [comment]
something like
```
. /etc/rc.d/PUPSTATE
case $PUPMODE in
 5|6|12) OLDSAVEFILE="pup_rw" ;;
 7|13|77) OLDSAVEFILE="pup_ro1" ;;
esac
[ -d /initrd/"$OLDSAVEFILE/usr/share/ptheme ] && exit
```
(hm what about full installs? do we "update" full installs when booting from CD ?)

**Comment by 01micko** [comment]
Full installs overwrite so it is less of a problem.

**Comment by mavrothal** [comment]
The above should not do. If updating from a 6+ slacko will still run.
We need to detect pTheme trace  in $HOME where is certainly going to leave its mark if used.

**Comment by mavrothal** [comment]
The $HOME/.jwm/tmp/pdesktop_xml file is generated the first time you open desktop settings applet and $HOME/.jwm/tmp/tray_xml the first time you open the tray configuration applet. 
The $HOME/.ptheme folder is generated the first time you use pTheme applet
We can bail if any of the 3 is present in the old seavfile/folder.
Is still possible to run jwm_config/pThemes and none of the above to be present (if a 6+ slacko build and nothing is changed), but then updating will not do any harm either.
Maybe Zigbert has a better indicator that jwm_config/pTheme was ever used in a system.

**Comment by 01micko** [comment]
Actually, $HOME/.jwm/tmp isn't there until you use ptheme, so testing for that dir and $HOME/.ptheme dir should be enough. 

Done in 7fcec5d
