### ISSUE TITLE
Integration of Retrovol-0.14.3.2-X

### ISSUE THREAD

**Issue by ASRIedu** [puppylinux-woof-CE/woof-CE#627]
Hello,
Integration of Retrovol-0.14.3.2-X  http://www.murga-linux.com/puppy/viewtopic.php?t=100081
![retrovol-0 14 3 2-x_fr](https://cloud.githubusercontent.com/assets/8407688/10868357/c6fd3b2a-808c-11e5-827e-301723640ed3.jpg)
What do you think ? Good or bad idea ?

**Comment by mavrothal** [comment]
We would rather not have binary packages in woof-CE as they will need to compile at build time making things complicated. [Petbuilds] (https://github.com/puppylinux-woof-CE/petbuilds)would be a better home for this.
