### ISSUE TITLE
Slacko 6.3 is missing sudo

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#635]
Slacko is missing sudo. 
As a result fido is completely broken. Was not any good before but without sudo it simply fails totaly

**Comment by 01micko** [comment]
On purpose. Fido is broken anyway. When its fixed I'll have sudo.

**Comment by mavrothal** [comment]
But fido is already there available as a save option and almost works.
If we break it totally it should be removed from the save options too.
