### ISSUE TITLE
SFS_load fails to unload SFSs in slacko64

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#636]
Sfs_load does not unload SFSs in slacko64. Is OK in skacko(32).
Slacko64 has sfs_load 2.3.6 
Installing 2.3.7 from PPM gets things back to normal

**Comment by 01micko** [comment]
These aren't woof issues! Please report them on the forum as they are specific to slacko.

**Comment by 01micko** [comment]
As an aside, I rebuilt with sfs_load-2.3.7 and re-uploaded. Put a timestamp on the forum for the unfortunate few who grabbed it in 3 separate posts.
