### ISSUE TITLE
sandbox

### ISSUE THREAD

**Issue by jamesbond3142** [puppylinux-woof-CE/woof-CE#638]
Somebody is asking me whether he can run [Fatdog Sandbox] (http://distro.ibiblio.org/fatdog/web/faqs/sandbox.html) in Tahrpup, so I did an initial testing port (which is easy, only 3 lines needs to change). 

The port seems to work okay. Some features can't be implemented ("unshare" in both of Slacko and Tahrpup is too old, and the "xwin" emulation is very Fatdog-specific that I won't even bother to port it to Puppy), but the basic thing works. 

Are you guys interested in having this in Woof-CE? Sandbox heavily depends on aufs so it won't work on systems using different layered filesystems.

**Comment by mavrothal** [comment]
> Are you guys interested in having this in Woof-CE? Sandbox heavily depends on aufs so it won't work on systems using different layered filesystems.

Yes. 
Regarding a different layered filesystem, see #607 :wink: 

And since I have you here ( :tongue:  ), now that Ubuntu 16.04 LTS has nightlies, I build a wily-pup using your woof-next-james tree to see if the Ubuntu move to systemd affects puppy building/function. 
The good news is that it builds and boots to Desktop! The bad news is that it need some (considerable) work to get there. Do you consider revisiting?

**Comment by jamesbond3142** [comment]
> Yes. 
Regarding a different layered filesystem, see #607 :wink: 

Ah, ok. It's fine then!

> And since I have you here ( :tongue:  ), now that Ubuntu 16.04 LTS has nightlies, I build a wily-pup using your woof-next-james tree to see if the Ubuntu move to systemd affects puppy building/function. 
The good news is that it builds and boots to Desktop! The bad news is that it need some (considerable) work to get there. Do you consider revisiting?

It's interesting. I haven't tested that myself; I know the recent Ubuntu and Debian come with systemd so there will be more packages that I have to exclude from the package-list so that they don't accidentally pull systemd-init (although I suppose pulling libsystemd may be unavoidable). I'm glad to you make it to work! :+1: 

If you have a patch I don't mind pushing it into it, though I suppose it's going to be super hard-work to merge many other Woof-CE enhancements that have happened in the last year or so since woof-next diverged from the testing branch. On top of that, I have another 66 commits on my other branch that builds Fatdog instead of Puppy from woof-next - many of the changes are Fatdog related but there are a few that are genuine build-system fixes; and these changes really need to be ported back in to the Puppy branch of woof-next if development is to re-activated. And there are a few Debian-based suggestions from saintless that also needs to be considered and probably goes in as well.

I don't mind revisiting, but as earlier said, I won't be able to do it alone. Just too many things to do :)

**Comment by jamesbond3142** [comment]
Where do you want me to put the script? rootfs-skeleton or rootfs-packages? If rootfs-packages, I can create the directory etc but I don't know which files needs to be edited to pull that in during the build.

**Comment by mavrothal** [comment]
rootfs-packages. Notice that is addition to the relevant files, it also needs a pet.specs file at the root of the folder. Assuming has no binaries the pet.specs line should be added in woof-distro/Packages-puppy-noarch-official. 
Then the puppy builder should add it in woof-distro/$ARCH/$BINCOMP/$VERSION/DISTRO_PKGS_SPECS-$BINCOMP-$VERSION

Regarding "xenial by woof-next", I'm afraid I do not have the time to go through the needed steps either :cry: (building is spoiling fast... :smile: )

**Comment by mavrothal** [comment]
Had another try with "xenial by woof-next" and turns out that you need almost all systemd for it to work. libsystemd only does get you out of console. Looks like X needs (something from)  systemd :-1:

**Comment by 01micko** [comment]
>rootfs-packages. Notice that is addition to the relevant files, it also needs a pet.specs file at the root of the folder. Assuming has no binaries the pet.specs line should be added in woof-distro/Packages-puppy-noarch-official.
Then the puppy builder should add it in woof-distro/$ARCH/$BINCOMP/$VERSION/DISTRO_PKGS_SPECS-$BINCOMP-$VERSION

No need for any of that. Just put the folder with pet.specs in rootfs-packages. The script picks up the dir and automatically provides a checkbox

**Comment by mavrothal** [comment]
> No need for any of that. Just put the folder with pet.specs in rootfs-packages. The script picks up the dir and automatically provides a checkbox

Right. But don;t we need that entry somewhere for builtin packages, PPM or something like it?

**Comment by 01micko** [comment]
It all goes into ~/.packages/builtin_files/ and entries made in ~/.packages/woof-installed/packages . We did that from the start re #608 
I think that's enough.

Also, if it is found in DISTRO_PKGS_SPECS-*-* with 'yes|' then the checkbox is made insensitive.

**Comment by jamesbond3142** [comment]
Thanks for the info. I'll get a pull request for this soon.

**Comment by jamesbond3142** [comment]
Sorry guys, I accidentally pushed directly to testing branch instead of issuing a pull request. Please help to check my commit - happy to revert if it's not good.

**Comment by mavrothal** [comment]
I *think* the pet.specs file should only have one line otherwise the woof-installed-packages list will have blank lines and how knows what happens next :tongue:

**Comment by jamesbond3142** [comment]
Thanks mavrothal. It happens thanks to copy and paste from other pet.specs :tongue:
I've fixed and pushed it again, hopefully that's all.

**Comment by jamesbond3142** [comment]
Just tested the sandbox in Mick's latest "xorg" branch iso. Looks good, so I'm closing this issue.
