### ISSUE TITLE
I'd like to add some of my scripts

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#648]
I have some scripts that might or might not be useful

burniso (burniso2cd replacement, cdrtools/cdrecord specific)
createsfs (gui for mksquashfs)
checkdeps (for files, directories and system)
filesize
firefox-download (download & install latest firefox release or alpha)
ipinfox (gui for ipinfo.io)
lxterm (xterm for lxterminal)
xtract, xcreate, xopen [xtract and xcreate are in the same level as file-roller]
undebs
mplay (adaptative video player launcher)

drive_all with refactored optical part (I tested that with various drives during a few days)

Some power tools
cdmaster (600+ lines)
hdmaster (900+ lines)

There are others, also some of them may require other of my scripts and icons/files.

Unfortunately when it comes to dialogs, I only used yad, but yad is small (150k). 
When it comes to icons, I guess we can replace some strings like --image=dialog-error with something available..

I have other scripts, specially for compiling, (5+/-)

**Comment by mavrothal** [comment]
One at a time :smile_cat: 
Provide some patches and please describe the use case and advantages over existing (if any) solutions.
If they replace existing scripts (filesize, drive_all) please try to test that they behave as expected in all pupmodes and boot setups. 
Other tools could either be provided as pets or go to rootfs-packages.
Is always a good idea new programs to initially distributes as pets in the forum to get some diverse testing. If successful and problem free  can then go to rootfs-packages or the ibiblio pet repo.
