### ISSUE TITLE
xorg.conf-auto-pc: 	HorizSync 35-81 / VertRefresh  59-76

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#650]
These 2 options should be commented out, they get in the way when booting Puppy in old hardware. I have tested 4 motherboards (2003-2005) and 5 very old graphic cards: they all boot to desktop if those options are commented out, otherwise I have to run xorgwizard or edit the generated /etc/X11/xorg.conf directly

**Comment by 01micko** [comment]
See #583 . We are deprecating xorgwizard-automatic
