### ISSUE TITLE
How can gtkdialog find icons in /usr/share/pixmaps/puppy

### ISSUE THREAD

**Issue by zigbert** [puppylinux-woof-CE/woof-CE#651]
The gtkdialog tree widget doesn't support full path for icons. It searches instead some destinations for the icon's name (ie /usr/share/icons/). I have solved this by symlinking icons in /usr/share/pixmaps/puppy/ to /usr/share/icons/. Could we solve this in any way to avoid 'doubling' the icon collection.

Example:
```
ln -s /usr/share/pixmaps/puppy/clock.svg /usr/share/icons
echo 'clock|show puppy svg in gtkdialog tree' > /tmp/tree

echo '<tree>
  <label>"head"</label>
  <input file icon-column="0">/tmp/tree</input>
</tree>' | gtkdialog -s
```

**Comment by zigbert** [comment]
Wonder where the icon-paths are defined
- path is not specified in gtkdialog sourcecode
- does not help to set pixmap_path in gtk-theme

**Comment by technosaurus** [comment]
does it work if you run `gtk-update-icon-cache -f /usr/share/pixmaps/puppy/`
?

**Comment by zigbert** [comment]
It doesn't work for me.
Test script:
```
#!/bin/bash

#set pixmap_path in gtk theme
echo 'pixmap_path "/usr/share/pixmaps/puppy/"' > /tmp/gtkrc
export GTK2_RC_FILES=~/.gtkrc-2.0:/tmp/gtkrc

#set current path
cd /usr/share/pixmaps/puppy/

#set icon-cache
gtk-update-icon-cache -f /usr/share/pixmaps/puppy/

#link one of the icons to verify result of above commands
ln -s /usr/share/pixmaps/puppy/audio.svg /usr/share/icons

echo -e 'phone|text 1\naudio|text 2' > /tmp/tree

echo '<tree>
  <label>"head"</label>
  <input file icon-column="0">/tmp/tree</input>
</tree>' | gtkdialog -s
```

**Comment by 01micko** [comment]
The only way is to make it a 'proper' icon theme and set it in the gtkrc-2.0 file. That involves 'compiling' the theme with standard names and sizes.

**Comment by 01micko** [comment]
Does the [puppy_icon_theme](https://github.com/puppylinux-woof-CE/puppy_icon_theme) address this?

**Comment by zigbert** [comment]
No, It does not.
Gtkdialog is still bound to the active gtk-theme.
The point here is to extend the active theme with 'required' icons.

This is obviously not a woof issue - so I close
