### ISSUE TITLE
PTheme fails to scale JWM title bar

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#655]
When changing to  a 'touch' theme the bar at the top of the windows isn't scaled. Now that I have touch [working](http://murga-linux.com/puppy/viewtopic.php?t=101827) I tried it out on my Acer IconiaTab W500 (the one I use with [FatDog64](http://murga-linux.com/puppy/viewtopic.php?t=98523) ((tag @jamesbond3142 :+1: ))). Apart from the title bar it looks and feels really good, apart from the obvious shortcomings, such as no virtual keyboard!

You can see a video [here](https://youtu.be/-jPiCQqxiFs) that more or less shows the issue. Don't worry about that the theme isn't maintained after X restart on first boot.

I think that the scale of the title bar can be calculated from the MENHEIGHT var easily enough. About 85 to 90 % should do it. It will make it so much easier to close/maximise/minimise windows with this setting.

TIA.

**Comment by 01micko** [comment]
As an aside to this, can global font size be increased when a 'touch' theme is activated? Or should that be fixed in the default JWM theme? (GTK seems OK).

**Comment by zigbert** [comment]
I think you should rename this thread to discuss pTheme improvements in general
I will visit pTheme after finished my round on the tray script... some days probably

So...
- Support height of window titlebar in pTheme. Maybe we can rename the 'Menu size' module to something more general - like 'Desktop sizes'. Could include size of menus, titlebars and global fonts. I don't think we should increase the global font for touchscreen. Fonts are for reading, and my eyes works as usual even if I use a touchscreen. But it might be a nice choice for those who are nearsighted. 
- Support theming of the drive icons.
- Show current theme-modules. Maybe not by default, but it would be great to have the ability.
- All 'official' themes should contain one mouse-theme and one touch-theme, so we can switch quickly at first-boot or even have a tray-button for switching.
- Virtual keyboard should be offered in every main tray.

**Comment by zigbert** [comment]
Changing global font size requires restart of X, so this is a bit out of the scope for pTheme.

**Comment by zigbert** [comment]
The window titlebar-height is set in jwmrc-personal, and since this one is included (in jwmrc) after jwmrc-theme, it will override the values set in the theme.

The question is if we should remove titlebar-height from jwmrc-personal, and let theming handle this, or we should let the theme override personal settings, or we should include an option to override theme in the window configuration gui, or ...

Personally, I feel that setting the titlebar-height is very unimportant for most users... BUT, for touchscreen support it will become important, and if we offer good themes, I think this will be the best solution for the users. I suggest we remove the option in the jwm_config gui and from jwmrc-personal, and include this in the themes as well as the corner-radius.

**Comment by q5sys** [comment]
>Personally, I feel that setting the titlebar-height is very unimportant for most users...

I'd agree that for most users it is, however keep in mind that being able to set title bar size is very important to older netbook users that sometimes have resolutions of 1024x600, like my one Acer.  I dont know how many users we have with units like those, but if we do remove the ability to change title bar height within some menu, we should at least have some documentation somewhere for users so they can learn how to manually go in and edit the theme themselves.

**Comment by mavrothal** [comment]
Puppy demographics suggest a majority of far-sighted users(...) Adjusting the size of various UI elements collectively and individually is important  I believe to remain user configurable. The theme should set those through the existing infra. ie include a themeconfig.sh to take care of them. Set to defaults if no themeconfig.sh is present.

**Comment by zigbert** [comment]
The window titlebar issue should be ok now.

**Comment by 01micko** [comment]
Just one thing, we seem to be missing some `jwmrc*hybrid` file. I can't see where it gets created. I like the addition of the drives with the dynamic menu. Works well.

**Comment by 01micko** [comment]
All works great on a brand new build, though I did not test setting either stardust theme as default (from woof - that is a future test in a couple of days).

I did test my new versions of buntoo and xf themes, but I think if they are to be in rootfs-packages, then they should be installed before ptheme, only so that the pinstall.sh gets priority (to set the wallpapers if there is a custom version for the distro).

Before I commit anything, here is a pet for perusal : [extras_ptheme-0.2.pet](https://01micko.com/extras_ptheme-0.2.pet)

The gtk themes need a little work but are getting close. I was thinking to use the hybrid approach for the xf theme but in reality, the default xfce desktop in slackware and ubuntu does have that little bottom tray stealing real estate! I think I'll just leave it for authenticity! :tongue:

**Comment by zigbert** [comment]
Nice themes.
Great to see that both have touch-themes.

The scrollbars in Buntoo-touch is equal to bars in Buntoo.
Am I blind? - I could not find the tray-button for virtual keyboard in the touch-themes  ;-)

Regarding the hybrid, I think it will fit well in the xf theme for 3 reasons.
- It will look the same
- It will give larger workspace
- It will 'allow' larger tray-icons in touch mode

**Comment by zigbert** [comment]
I see, the Minimal_Labelled is NOT equal. Sorry.

**Comment by 01micko** [comment]
Having actually _used_ my tablet with fatdog and now slacko (the latest _xvkbd_ is in the slacko repos as of yesterday - plus a helper program _x-keyboard_, but it is buggy), I know it's not very intuitive to raise and lower a keyboard with a button. 

There are 2 solutions to this. 
- There is a small program called 'easystroke' which you can train to recognise gestures. This is certainly the most professional solution, but it does not address select/copy/paste of text.
- I have a home grown solution (written in C using xlib and extensions) that recognises when the _xterm_ cursor (aka 'I' beam - the text cursor) is on screen and when button1 is pressed pops the keyboard. A down swipe in a non-text area closes the keyboard. Selecting text is possible and once selected a 'copy' button is popped. If pressed that text is copied to the clipboard and a 'paste' button is popped. You the have a bit of time (25 seconds) to raise the app you want to paste the selected text and place the cursor where you want said text pasted. Then hit that 'paste' button and text is pasted. For the most part it works but it certainly is not perfect. I probably have to rewrite it using gdk/gtk as I think that just detecting a cursor is too sensitive. I really need to detect a text area, be it terminal emulator, text editor, word processor, entry box (app or browser) etc.

**Comment by zigbert** [comment]
It would be wonderful with an auto-popup keyboard, but a button is an OK plan B.

Your work make me consider buying a pad/tablet ;-) I guess it has to run a intel CPU...

I think pTheme is getting complete. We control most aspects of the graphical moduls. Of course it would be great to include global fonts as well, but restarting x is just too much...

**Comment by 01micko** [comment]
If you consider a tablet, I can recommend the Iconia W500 or 501. They are from around 2011 but still is powerful enough to run 64 bit OS. (It's what I'm testing ATM) but with only 2 GB RAM probably 32 bit OS is a better match. 

For sure they would be cheap enough on ebay or some other auction/sale site. I was lucky enough to have mine donated to me for development, so this is why I take a keen interest :smile: , but it is _fun_ too! It boots off an SD card too so no USB hanging off the side.

**Comment by 01micko** [comment]
@zigbert 

Here is a reasonable fix for the `x-keyboard` PET package, which I'll fix soon.

```shell
#!/bin/sh

read ROOTDIMS MAXX MAXY << EOF
`xwininfo -root | grep ' \-geometry ' | cut -f 1 -d '+' | tr 'x' ' '`
EOF

if which cellwriter 2>/dev/null ;then
	cellwriter --keyboard-only  --dock-window=1 &
else
	if [ $MAXX -gt $MAXY ];then
		GEO=$((3*($MAXX/4)))x$((3*$MAXY/10))+$((($MAXX/2)-(3*$MAXX/8)))+$(($MAXY-($MAXY/5)-64))
		xvkbd -geometry $GEO -always-on-top &
	else 
		GEO=${MAXX}x$(($MAXY/4))+0+$(($MAXY-($MAXY/5)-64))
		xvkbd -geometry $GEO -always-on-top -no-keypad &
	fi
fi
```

**Comment by zigbert** [comment]
Is this /usr/local/bin/defaultkeyboard?
Maybe I should add defaultkeaboard to a function-button in the jwm_config tray app?
Tray-templates supports an install-script, so including a tray-button if x-keyboard exists is possible.
I have used xvkbd earlier. (You remember DuDE...) Looks nasty (default setting), couldn't get norwegian keys, but else - works as expected.

Checked out Iconia W510, and I can get a pre-owned (32GB) in Norway for 190 AUD.
Why do you recommend it? Is it price, features or X-686 that is the best reason?
