### ISSUE TITLE
0setup find_cat segfaulting

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#659]
in both tahrpup64-6.0.4 & slacko64-6.3.0 when building a .deb based puppy 0setup segfaults on various repos, in ubuntu pups it's the universe repo 
```
Processing Packages-ubuntu-precise-universe into a standard format...
 please wait...
Segmentation fault
```
/var/log/messages shows
```
Dec  7 12:32:00 puppypc26147 user.info kernel: find_cat[28423]: segfault at 6c726570 ip 00000000004029dd sp 00007ffdb34f3d18 error 4 in find_cat[400000+5000]
Dec  7 12:33:17 puppypc26147 user.info kernel: debdb2pupdb[2405]: segfault at 0 ip 0000000000400266 sp 00007fff16d34270 error 6 in debdb2pupdb[400000+e000]
```
tahrpup64-6.0.3.9 built in october can run the same 0setup without problems.

any idea what difference in the newer builds might be causing this?

**Comment by dimkr** [comment]
Yeah, I'll take a look when I get home. Don't you worry, my friend.

**Comment by mavrothal** [comment]
> when building a .deb based puppy 0setup segfaults on various repos

There is no difference in find_cat and debdb2pupdb between 6.0.3.9 and 6.0.4
I also tried a db update in tahr64 6.0.4 through PPM and had no segfaults.
Is it only when building a puppy in your system or in dbupdates through PPM too?

**Comment by dimkr** [comment]
@mrfricks - copy support/debdb2pupdb to /usr/local/petget/. Does the problem persist?

**Comment by wdlkmpx** [comment]
How fast is find_cat? I think a script can be as fast

**Comment by mavrothal** [comment]
I was actually wrong it **does** segfaults on the ubuntu universe repo.
This is a huge file with 763000 lines. 
It fails at the lxshortcut package at line 505359.
Find_cat and debdb2pupdb in tahr64 are the same as in woof-CE as suggested by md5sum

**Comment by dimkr** [comment]
Alright, I'll be home in 3 hours or so. I'll try to run 0setup, should be easy to spot and fix.

> How fast is find_cat? I think a script can be as fast

Barry's implementation was written in BaCon and it took more than 10 minutes to do the exact same thing as my C implementation, which does this in seconds. A shell script ought to be much, much slower than that.

**Comment by dimkr** [comment]
I was unable to reproduce this issue - I'm cross-building from x86 for x86_64, with testing HEAD. Make sure you're using HEAD too.

**Comment by mrfricks** [comment]
@dimkr copying debdb2pupdb to /usr/local/petget didn't work.  copying debdb2pupdb from 6.0.3.9 also didn't work (it is working in 6.0.3.9).
although debdb2pupdb is where the segfault is, the problem may be elsewhere as with the same woof folder tahrpup 6.0.3.9 works fine.

the problem is with tahrpup64-6.0.4 & slacko64-6.3.0

**Comment by dimkr** [comment]
Still unable to reproduce it, on tahrpup64 6.0.3.9. Check your free RAM while doing the repo update, there's a good chance you're out of memory.

**Comment by mrfricks** [comment]
i've got 8gb so i don't think ram is the issue.
the issue isn't present in tahrpup64-6.0.3.9and i've actually pulled the 6.0.4 iso.
to test try slacko64-6.3.0 as the problem was occuring there as well

**Comment by dimkr** [comment]
Downloading. I'll compare the binaries to those from HEAD, that's the only thing that could have changed.

**Comment by mrfricks** [comment]
tried a few different combos and as far as i can tell it's /usr/local/petget/find_cat.  if it's the one from tahrpup64-6.0.3.9 all is fine. but the one from slacko64-6.3.0 & tahrpup64-6.0.4 is problematic.
the find_cat in the support folder doesn't seem to matter

**Comment by dimkr** [comment]
No, the difference is the Ubuntu version. Precise has veeeeery long package names that cause overflow. Gimme a couple of minutes, I'll commit a fixed binary.

**Comment by 01micko** [comment]
You need 64 built?

**Comment by dimkr** [comment]
Just a sec, uploading ;)

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/raw/testing/woof-arch/x86_64/build/support/find_cat

**Comment by mrfricks** [comment]
yes that is working :)

but i'm still confused as to why if the binary hasn't changed, there was a problem in these newer builds

**Comment by 01micko** [comment]
@mrfricks the binary changed a bit over a month ago - see d44a842dab31f2c666d72ca0ae41a18b86c8f463

**Comment by dimkr** [comment]
> but i'm still confused as to why if the binary hasn't changed, there was a problem in these newer builds

Maybe only Precise triggers the bug, although I took a look at package names and it seems Trusty has those long names too :confused:

**Comment by 01micko** [comment]
I just built 32 bit find_cat, you want me to push? If no answer in 10 mins I'll push :wink:

**Comment by dimkr** [comment]
I updated both binaries ;)

**Comment by 01micko** [comment]
Thanks

**Comment by mrfricks** [comment]
@dimkr precise, trusty and also debian wheezy had the problem. slacko was ok ...that's as far as i went.

**Comment by mrfricks** [comment]
and thankyou :)
