### ISSUE TITLE
Misc Issues that probably need addressing

### ISSUE THREAD

**Issue by starhawk64** [puppylinux-woof-CE/woof-CE#667]
starhawk from the Murga Puppy Forum here :) Bringing up some issues I've experienced... consider each of these offerings as a note in the Suggestion Box.

(1) savefiles corrupt spontaneously, due to (I suspect) improper unmount at shutdown. fsck at bootup slows this process down but does not solve it completely.

(2) many applications in Puppy have poorly written English in them -- the grub4dos wizard comes to mind here ("Press OK to install. Press Cancel if you do not want to." ;) ).

(3) there is no command-line package installer... and when I showed a Linux Guru friend of mine the part of petget that validates dotPET packages, he very nearly lost both lunch and sanity. I'd asked him to explain to me what it was doing where. He gave up completely midway through. IIRC it was MD5sum-ing two MD5sums and comparing them, about where he stopped... and there was at least one case where a command was routed to a binary that was POSIX-noncompliant -- I want to say that it had the name of a POSIX binary/command but was a Puppy-specific implementation.

(4) we should probably have an archaic-machines branch specifically for dusty old relics brought in by folks who simply don't know any better. No offense to ttuuxxx and goingnuts -- but ClassicPup and pUPnGO are simply not practical offerings for these machines (5x86-class CPUs, max. 256mb RAM). There should be a Pup for these machines... we kind of are the only game in town for them. (DSL is not a serious offering any more, given how outdated its everything is, and Knoppix AFAIK is dead and gone.)

**Comment by mavrothal** [comment]
Welcome.
File corruption may be because of a faulty drive rather than improper shutdown. Fsck can not do miracles in this case though ext4 fs may help a bit.
Regarding english, please you or others, edit as needed.  It does not even need any coding knowledge. Just keep in mind that many apps (like grub4dos) come from pets and are not in woof-CE. Offer your help to the pet maintainer in these cases.
Tell your friend to send some patches over for petget :wink: 
Archaic branch may be a good idea, however I do not think that any Pentium III, 256MB machine can handle a modern browser with any tolerable responsiveness. So I'm not sure that anything "better" than puppy2 can run on this kind of machines (that is the reason I stopped making puppies for the [XO-1](http://laptop.org/en/laptop/hardware/specs.shtml) :crying_cat_face: )

**Comment by wdlkmpx** [comment]
You mean truncate, don't you? I think it's not being used anymore, it was used in /usr/bin/pet2tgz

This is what I do to run current pups, which are way too heavy:
1) recompress sfs with gz compression
2) remove/disable all startup apps and some services

**Comment by starhawk64** [comment]
I can tell you for a fact that none of the drives were bad, on which I've experienced corruption of the savefile... there is something in software going on here.

I will be doing a lot of copyediting of Puppy as part of a project of mine, if things go well, and will probably push updates in as far as that's concerned, when it happens.

My friend now refuses to touch Puppy because he knows how it's coded and he's a programmer and he thinks he's better.

As for low-resource machines... we need *something* -- I can tell you that a P2 300MHz system with 128MB RAM is *barely* tolerable with a lighter browser such as SlimBoat... doubling the RAM there may help, and I've got the system (I'll be getting the RAM for Christmas) so I'll be able to test ;) P1's will not be 'Net-able but will still be useful for light word processing and maybe browserless email -- which is all some folks need ;)

@wdlkmpx -- truncate is it and it is still in use... is there a reason it could not be replaced with POSIX truncate, or renamed, say, pmtruncate (for Poor Man's truncate ;) )...?

**Comment by wdlkmpx** [comment]
It's there in /usr/bin, but it's not used anymore. I just checked the whole woof-ce tree. I think that package should not included in any woof ce based puppy:
	no|truncate||exe

**Comment by mavrothal** [comment]
The following little change will log the shutdown process into /mnt/home. It does put some additional stress in the system but if there is anything wrong we may be able to find it.
```
--- a/etc/rc.d/rc.shutdown
+++ b/etc/rc.d/rc.shutdown
@@ -86,7 +86,7 @@
 export OUTPUT_CHARSET=UTF-8
 
 clear
-exec 1> /dev/null 2>&1
+set -x; exec 1> /mnt/home/shutdown.log 2>&1
 
 which rfkill &>/dev/null && rfkill unblock all #110919 jemimah has this in fluppy. if don't do this, may be locked at next boot.
 
```

**Comment by wdlkmpx** [comment]
Well regarding petget, I think I can do something, but I'm not sure, a PET file is basically a corrupted tar file. I've been testing pacman from Arch Linux. Puppy is still the only linux distro I use and am still a GNU/Linux newbie, but I guess I can do something..

I'm writing some functions to work with .pet files:
http://pastebin.com/1vk3fenZ

**Comment by 01micko** [comment]
Old issue? Still valid? Closing. Re-open as necessary @starhawk64
