### ISSUE TITLE
petget problems

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#668]
today i've been trying to get the final tahrpup64 iso but it has problems. .pets which install fine in tahrpup64-6.0.3.9 fail to install in the new iso. it's not all .pets! as far as i can tell it's the ones created with the newer dir2pet.

so here's a new iso built with the latest woof (ignore the size, abiword.dev crept into this secondary build) http://distro.ibiblio.org/puppylinux/puppy-tahr/iso/testing/tahr64-6.0.4.iso
and here's one of the .pets that won't install http://distro.ibiblio.org/puppylinux/pet_packages-tahr64/dunst-1.0.0-x86_64.pet

solutions welcome :)

**Comment by mavrothal** [comment]
What is the error with the pet?
Is it OK if you generate it with the "g" (gzip compression) option?

**Comment by wdlkmpx** [comment]
I'm using latest woof ce in a 32bit puppy and that package installs fine hehe. I'm downloading slowly.

It would be a good idea to add error messages to petget, now it works silently for the most part, many errors can occur and there is no way to tell.

I recently edited /usr/bin/pet2tgz, if you're having problems with dir2pet xz files, then it must be pet2tgz

The output of 'file -b file.pet' must be one of these:
xz compressed data
gzip compressed data, from Unix ...

**Comment by mrfricks** [comment]
nothing in xerrs.log

![capture16686](https://cloud.githubusercontent.com/assets/1454550/11724478/3e6d46e6-9faf-11e5-8ecf-7ee4d3f7a3f0.png)
![capture17154](https://cloud.githubusercontent.com/assets/1454550/11724480/3fcf50e2-9faf-11e5-83bf-11a79ff07bd7.png)

**Comment by mavrothal** [comment]
That is on your latest tahr64. :-?
![dunst](https://cloud.githubusercontent.com/assets/1014999/11724815/074a3d5c-9f7f-11e5-9c82-d9ff3a0bbef2.jpg)

**Comment by mrfricks** [comment]
it's on the iso built today, with todays woof on the first post (note that it's still called 6.0.4 at the mo)

**Comment by mavrothal** [comment]
I got it. Is a bug introduced in 5c3e69a that looks like was more than cosmetic...
Fixed in a00da91

**Comment by mrfricks** [comment]
thanks

**Comment by wdlkmpx** [comment]
Indeed, but that change makes it easy to add bzip2 support. The only issue is 'file -b's output, it can vary...
