### ISSUE TITLE
Support for multiple desktops: /etc/desktop

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#673]
This file would tell /root/.xinitrc to load the correct desktop

You see, there are puppy derivatives that replace rox/jwm (I replace rox but not jwm) using an edited /root/.xinitrc

I have a vision where Puppy becomes 1

**Comment by wdlkmpx** [comment]
This edited lxpup's .xinitrc file and made it work in a "normal" woof ce puppy
http://pastebin.com/h1bJQ6hf

	echo -n 'lxde' > /etc/desktop

This is basically what I'm thinking of.

**Comment by 01micko** [comment]
IMHO, `xinitrc` should be system wide as I have done in the `xorg` branch.
Of course this can be a symlink or the 'users' xinitrc can be made to take precedence.
Just some food for thought. :smile:

**Comment by jamesbond3142** [comment]
> IMHO, `xinitrc` should be system wide as I have done in the `xorg` branch.
Of course this can be a symlink or the 'users' xinitrc can be made to take precedence.
Just some food for thought. :smile: 

:+1:

**Comment by wdlkmpx** [comment]
The biggest problem in puppy is the .desktop files, you just can't use a proper DE without fixing all the desktop files, well at least a DE that is not hacked to like puppy. My experience was just to recreate all the desktop files to use other file manager at least..

I guess the PPM and all that stuff is still somewhat usable, as long as the whole process don't touch the desktop files.

I guess no other distro has this incovenience. I remember i had to manually add a desktop file specially crafted for puppy when i compiled/installed a package... and this is not how things work.

Looking at some scripts (pkginstall.sh, 2createpackages) I see that puppy finds and edits desktop files (code that now is outdated).

I don't know what barry is doing right now with his quirky project, but i guess once the project was forked it was the perfect time to undo many things to start working in this lonely lane with something that other people develop (lightweight DEs), using what most other people use... to avoid working in developing/fixing the puppy DE and focus on other things...
