### ISSUE TITLE
debdb2pupdb segfaulting part 2

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#692]
been playing around with ubuntu xenial builds and debdb2pupdb is segfaulting ... works for the regular repos but segfaults on the update repos 

https://www.dropbox.com/s/5vuzpujh2u5v7t3/woof-distro.tar.gz?dl=0

**Comment by dimkr** [comment]
Great, I'll investigate this tomorrow on the way to work :mask:
