### ISSUE TITLE
Tahrpup: Always forgets the DNS which I have set ?

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [puppylinux-woof-CE/woof-CE#703]
Whenever I set my DNS from `/etc/resolv.conf` it always changes back to it's old DNS after sometime. I don't know what is causing this so for the time being I have wrote a bit of [hacky script](https://github.com/Mr-Kumar-Abhishek/set-my-dns) which somehow does my job when X is running. I am using Tahrpup on my old Laptop and getting the Internet through tethering from my android phone. My question is what is causing this ? Any help is appreciated. Or please point out where to get help regarding this.

Script:
```bash
#!/bin/bash
write_to_file(){
	local file="/etc/resolv.conf"
	
	while true; do 
		DNS_SERVER1="nameserver 208.67.222.222" #new dns
		DNS_SERVER2="nameserver 208.67.220.220" #new dns 
		if [ ! -f "$file" ]; then
			touch "$file"
		else
			if  grep "192.168.43.1" $file
			 then
				rm "$file"
				touch "$file"

				echo "$DNS_SERVER1" > "$file";
				echo "$DNS_SERVER2" >> "$file";
			fi
		fi
		sleep 1
	done
}

write_to_file
```

**Comment by mavrothal** [comment]
Tis is not the place for this question. Try the puppy forum instead.
BTW all the connection tools overwrite resolv.conf based on server/hotspot info.

**Comment by Mr-Kumar-Abhishek** [comment]
I see , thanks for the information, however I am not receiving any confirmation email after registering with [puppy linux forums](http://murga-linux.com/puppy/). I have mailed the site admin about this. If it is not much of a problem could you tell me if `sns` overwrites *after* the connection has been made ?

**Comment by 01micko** [comment]
It's not any of the connection tools that cause this. It's rather dhcpcd
daemon interaction with the dhcp server. All the tools rely on dhcpcd.

**Comment by Mr-Kumar-Abhishek** [comment]
Thanks a lot for help @01micko :sweat_smile: I could probably do something now by hooking scripts with dhcpcd events.
