### ISSUE TITLE
Ask to set default app

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#721]
I have a small addition to PPM that taking advantage of puppyapps will ask the user to set as default a newly installed application if it falls in one of the /usr/local/bin/default<category>.
But I'm not sure if it is going to be useful or just annoying or if it even worths to make it user configurable through yet another PPM configuration option.
What do you think?

The code (in case I misplace it :blush: ) is this

```
# Add ~ L838 of /usr/local/petget/instalpkg.sh
HASDESKTOP=$(grep -s '.desktop' /root/.packages/${DLPKG_NAME}.files)
if [ "$HASDESKTOP" -a "$(which puppyapps)" ]; then
    for APPL in $(grep '.desktop' /root/.packages/${DLPKG_NAME}.files)
    do
        DESKNAME=$(echo $(basename $APPL) | sed 's/\.desktop//')
        if [ "$(grep -s "$DESKNAME" /usr/sbin/puppyapps | grep APPLIST)" ]; then
            for LINE in $(grep -B 1 ${DESKNAME} /usr/sbin/puppyapps | grep -B 1 \
             APPLIST | grep -vE 'APPLIST|--' | cut -f 1 -d ')' | tr -d '\t')
            do 
                CATEGORY=$(echo "${LINE}") 
                . /usr/lib/gtkdialog/box_yesno "$(gettext 'Puppyapps')" "$(eval echo $(gettext 'Do you want to  set ${DESKNAME} as the default ${CATEGORY} application?'))"
                [ "$EXIT" = "yes" ] && puppyapps -c $CATEGORY $DESKNAME
            done
        fi
    done
fi
```

**Comment by wdlkmpx** [comment]
PPM can query puppyapps for this. The number of hardcoded apps in APPSLIST is minimun to keep the script fast enough, and most  of them are my choices hehe..

something like:
$(puppyapps -cat <app>)
return value <category> or null, 0 or 1

if [ "category" ] ; then
ask the user, then
puppyapps -c category <>
fi

A file called /var/lib/puppyapps/categories.db (a text file obviously) can be created for this purpose with many other relevant apps
audioeditor|one|two|three|for|five| ... n
mediaplayer|one|two|three|for|five| ... n

something like that comes to mind

**Comment by wdlkmpx** [comment]
On second thought only the best or most advanced apps are worthy of a special treatment, I think another variable can be created inside puppyapps to contain only that kind of apps, something like:

BESTAPPS="audioeditor ...
browser ..."

Then PPM can query puppyapps, and puppyapps will return the category it belongs to (if it's a BESTAPP)... then PPM can offer the user set that app as default

**Comment by mavrothal** [comment]
I do not know who is to determine BESTAPPS. Needs vary from person to person.
If a user installs an additional to the existing apps it is conceivable that (s)he may want to use it as a default. That's what the  current proposal (#721) does, but I still think is an overkill. 
One can always run one of the available "setdefaults" apps and do it if needed.

**Comment by wdlkmpx** [comment]
It certainly looks like an overkill. But I think it would be a good idea to introduce a least one question about puppyapps in the build scripts.

I've already written code and have a small mime_defaults.db that contains all the data I could gather from woof-ce and the rox_filer pkg. It generates defaults.list mailcap, desktop files, and files for $HOME/Choices/MIME-types, all at the same time
