### ISSUE TITLE
rc.update needs some cleanup?

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#730]
I see this piece of code is actually not in use:

	echo -n " desk-icons" >/dev/console
	if [ -f /etc/desktop_icon_theme ];then #110119
	 DEFAULT_DESK_ICONS="`cat /etc/desktop_icon_theme`" #Woof creates this.
	else #precaution
	 DEFAULT_DESK_ICONS="`ls -1 /usr/local/lib/X11/themes | tail -n 1`"
	fi
	#110826 not needed, now done in 3builddistro...
	#/usr/sbin/icon_switcher_cli $DEFAULT_DESK_ICONS
	#[ -f /usr/share/doc/woof-tree-official.svg ] && [ ! -f /usr/share/doc/woof-tree-official.png ] && rsvg-convert -w 648 -a -o /usr/share/doc/woof-tree-official.png /usr/share/doc/woof-tree-official.svg #100425

DEFAULT_DESK_ICONS=...
#/usr/sbin/icon_switcher_cli $DEFAULT_DESK_ICONS

And this some lines below

	#w002 generate desktop icons (previously done in unleashed)...
	echo -n " desk-icons" >/dev/console
	if [ -f /etc/desktop_icon_theme ];then #110119
	 DEFAULT_DESK_ICONS="`cat /etc/desktop_icon_theme`" #Woof creates this.
	else #precaution
	 DEFAULT_DESK_ICONS="`ls -1 /usr/local/lib/X11/themes | tail -n 1`"
	fi
	#110826 not needed, now done in 3builddistro...
	#/usr/sbin/icon_switcher_cli $DEFAULT_DESK_ICONS

There is also a huge commented out section.

If you remove these code blocks, more than 100 lines will be gone..

**Comment by mavrothal** [comment]
Go for it.
