### ISSUE TITLE
Add icon theme to ptheme

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#759]
It would be nice if we could tack on the icon theme to the gtkrc file. I have a couple of nice 'pthemes' but are  bit bloated because of the icon theme so I intend to offer them as sfs packages.

Here is a one liner to find all the icon themes at the standard location:

```shell
find /usr/share/icons -type f -maxdepth 2 -name 'index.theme'|sed -e 's/^/"/' -e 's/$/"/'| xargs grep 'Name='|cut -d '=' -f2
```

The above finds themes with spaces in the name (pipe through `sed`).
Below is my output - but we should filter out the fallbacks ("hicolor" and "locolor").

```
Breeze Dark
Breeze
Hicolor
Oxygen
Vibrantly-Simple
```

It's then just a matter of tacking that onto the gtkrc file:

```shell
echo  -e "gtk-icon-theme-name = \"$my_chosen_theme\"" >> ~/.gtkrc-2.0
```

The logic is the only catch. It must be written only after `switch2` has done its thing.

**Comment by zigbert** [comment]
If you like, I can initiate adding of gtk-icons-themes to pTheme, but please tell me where I can download a theme to work/test with.

Are you suggesting that we build our own theme based on the themes in /usr/share/pixmaps/puppy? I guess it will give an improved look in the touch-themes where icons are scale up.
Does there exist a list telling what icons a theme should contain. I can make the missing icons...

**Comment by 01micko** [comment]
Just search "icon-theme" in ppm. Any one will do. Probably gnome is the most comprehensive.

>Are you suggesting that we build our own theme based on the themes in /usr/share/pixmaps/puppy? 

I think @technosaurus first suggested something like that. All the standard gtk icons are necessary but I don't know how to build the database (I think the icon.theme file gives a clue). Naming is the important thing and there will be a lot of symlinks. But that can be all scripted and sizes down to 16x16 can all be adjusted by script with the 'viewport'.

I'm sure there are tutorials around.

**Comment by zigbert** [comment]
It shouldn't be hard to add gtk-icons-theme support to pTheme, but I have not been able to set a new theme...
- Installed GNOME theme from official Slackware repo using PPM
- Edited ~/.gtkrc-2.0
- Restarted X.
No go. Still Hicolor icons...

![gnome_icon_theme](https://cloud.githubusercontent.com/assets/5928708/14081824/df7972be-f50c-11e5-8a2f-b4a2432806c2.png)

**Comment by 01micko** [comment]
You're right! Gnome wasn't a good suggestion (I didn't try it). I did however just try Faenza and it _does_ work. It is rather bloated (includes several themes) but there are much lighter themes around. I might hunt some and package them.

**Comment by 01micko** [comment]
>Does there exist a list telling what icons a theme should contain. I can make the missing icons...

Yes: [Standard from freedesktop.org](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html)

Yes it is old, but the spec for gtk-2.0 hasn't changed much I believe. Many icons can be simply symlinks that can be generated at "compile time". Don't be too concerned with naming either. I will make a script from that list with the appropriate names/categories. I already have a lot of mime type icons so don't start there!!! (I'll post them soon).

What I would suggest is leave them in /usr/share/pixmaps/puppy and the theme can be built as part of the woof process.

**Comment by zigbert** [comment]
Got Faenza working.
pTheme is now ok with gtk-icons-theme, but I still has some work with ptheme_gtk. The set icon-theme in ptheme has to be parsed to ptheme_gtk...

**Comment by zigbert** [comment]
A quick review of the iconlist at freedesktop.org shows that there are a few icons missing in /usr/share/pixmaps/puppy/ :-D

Making a complete icon-set for gtk will take some time...
What is the benefits of such a major task?
- as mentioned, I guess smoother icons in touch-mode when button. etc gets bigger.
- will we be able to remove the Hicolor icon theme? Rox counted content of /usr/share/icons/hicolor/ to 15Mb. Is this a potential iso-shrink?
- unified look of icons - ok - but I don't think that alone is enough to motivate me for such a task

**Comment by 01micko** [comment]
>unified look of icons - ok - but I don't think that alone is enough to motivate me for such a task

Yes a big task! I tend to agree that your time is better spent elsewhere.

Thanks for updating ptheme.

**Comment by 01micko** [comment]
> Yes a big task! I tend to agree that your time is better spent elsewhere.

Perhaps mine too.. ( @zigbert  ) .. however..

![icons](https://cloud.githubusercontent.com/assets/1019119/14581016/70326e34-0424-11e6-847a-732d5447d71e.png)

Recognise these?

A simple script builds _the lot_

_More to come!_

**Comment by zigbert** [comment]
Nice.
What is the grand plan?
Don't hesitate to ask me to make requested svgs.
If the benefit of a svg icon-theme is clear, we should set it as a long term goal.

I see many programs (as geany) put icons inside /usr/share/icons/Hicolor/. Do these rely on Hicolor directories structure. I have put pmusic-icons inside Hicolor as well. Maybe /usr/share/pixmaps is a better place...

Your Rox-screeny shows vector icons with correct size (22x22px?). When using a svg-icon directly in gtkdialog like <input file>/usr/share/pixmaps/puppy/add.svg</input>, it shows up with its defined 100x100 px. Do the Rox-code fix this scaling issue, or have you defined the size elsewhere?

**Comment by 01micko** [comment]
> Nice

Thanks.

> What is the grand plan?

See issue #671 

PVM gets its icons from the icon theme. Now we can match that for a better aesthetic. I haven't tried yet but my little "gtksplash" proggy (written in C) is a great test bed. 

```
 gtksplash -s "hello disk" -c green -f "Sans 48" -i gtk-harddisk
```

![harddisk](https://cloud.githubusercontent.com/assets/1019119/14585418/ee88bfe8-04b7-11e6-81b9-82314890c3cd.png)

Most work but some don't; a bit perplexing why but never mind for now. Maybe @technosaurus will know.

I have started a git repo: https://github.com/puppylinux-woof-CE/puppy_icon_theme

Download the tarball and build it your self :smile: .. it's very easy. Just put the resulting directory into `/usr/share/icons/`.

The icons are all scaled with a `viewbox` so are the correct size. 

> I see many programs (as geany) put icons inside /usr/share/icons/Hicolor/. Do these rely on Hicolor directories structure. I have put pmusic-icons inside Hicolor as well. Maybe /usr/share/pixmaps is a better place...

Hicolor and Locolor are _fallback_ themes. usually an GTK app builder will place her/his icons in there and usually `Inherits=Hicolor` is specified in the `icon.theme` file as the fallback. probably `/usr/share/pixmaps` is better for just one icon.

**Comment by 01micko** [comment]
Pup Volume Monitor icons work :tongue: 

Just a small issue with a broken 'mounted' icon but I'm sure if I scour the source code I can find it and add it.

![pvm](https://cloud.githubusercontent.com/assets/1019119/14585722/2fb35c80-04c2-11e6-92f1-934bdb3c6e25.png)

**Comment by 01micko** [comment]
Getting close now...

![pvm2](https://cloud.githubusercontent.com/assets/1019119/14586170/4e329d04-04d3-11e6-88a8-4683afa71a3e.png)

**Comment by zigbert** [comment]
2 questions:
- Do you plan to keep 2 set of the icons. One in /usr/share/pixmaps/puppy, and one in /usr/share/icons/ ?
- Which of these destinations should I point my svg-code.

**Comment by 01micko** [comment]
Well, if the "Puppy Standard" theme is set in .gtk2rc then all widgets get the icons anyway - geany even gets one as its default icon! (edit.svg)

Some icons are not used so some will have to stay in /usr/share/pixmaps/puppy

I'm not sure if this new 'icon-theme' is mature enough for a daily use as yet - soon though.  Still lots of mimetypes missing and as said some don't work at all (about.svg is a notable one).

I'm also thinking to make the icon-theme entirely optional which means if it is included then there will be redundancy - but they are so small it barely bloats the ISO image. In this case /usr/share/pixmaps/puppy should be maintained as and where it is.
