### ISSUE TITLE
Packages-puppy-noarch-official at ibliblio

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#761]
Further changes are needed to Packages-puppy-noarch-official
Packages-puppy-noarch-official at ibilblio needs to be updated consistent with woof-ce version

[https://github.com/puppylinux-woof-CE/woof-CE/commit/981141f7cd04248bf2895767a34766c644d47375](url)

**Comment by 01micko** [comment]
@peabee put in a pull request and I'll upload the missing packages.

**Comment by 01micko** [comment]
Pup-Kview and Packages-puppy-noarch-official are both now updated at Ibiblio
