### ISSUE TITLE
loginmanager calls the missing mini-question.xpm

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#764]
See [here](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/sbin/loginmanager#L137) and L139

**Comment by 01micko** [comment]
Do I have to fix everything? :tongue:

**Comment by 01micko** [comment]
What is 'L139' ?

**Comment by 01micko** [comment]
>What is 'L139' ?

lol

**Comment by mavrothal** [comment]
> Do I have to fix everything? :tongue:

You should actually scout the forum, see what code change suggestions might be hidden there, decipher them, incorporate them into woo-**CE** if appropriate  and make sure to acknowledge the "author". But I'm a nice person... :imp:  :laughing:
