### ISSUE TITLE
Add building woof-CE commit number into built puppy 

### ISSUE THREAD

**Issue by scsijon** [puppylinux-woof-CE/woof-CE#766]
I can't find if there appears somewhere in a puppy build the last woof-CE Commit date or some point of referance back to the last woof-CE commit used in building the puppy?

Can it be added somewhere please. I'm sure there must be a simple point somewhere for it to go and found.

Reason is, while i'm ill, i've been looking at and trying a rebuild of some of my old basic puppys but with the latest available packages. But what built and ran then, isn't doing so now. I'd like to go back in my archives and build with the old matching woof-CE sets, but with 'quite a few' commit sets in the directory I do need to work out which is the one that worked and go from there and I can't find somewhere to start as a referance point.

**Comment by jamesbond3142** [comment]
This is a good idea. We can get the git commit by doing ```git rev-list HEAD -n 1``` and if the result is not empty, put the result to either BUILD_ID in /etc/os-release, or somewhere else convenient.

**Comment by ninaholic** [comment]
Hi,

In the bottom of /etc/DISTRO_SPECS you can find:
BUILD_FROM_WOOF='testing;9dea777;2016-03-31 20:08:11 +1000'

So it is built March 31st, 2016 using the testing branch.

Also plugging the "9dea777" into the url can show you the last commit:
https://github.com/puppylinux-woof-CE/woof-CE/commit/9dea777

Hope that helps. :)

**Comment by scsijon** [comment]
thanks you ninaholic, 

so the information is there, in which case i'll close this issue

My currently running one (racy551 VERY modified) has as a similar line: 
DISTRO_IDSTRING='w130302222831ZZZZ5.5XXXXXXXXXXXX'
so I expect that means it's pre woof-CE and in a similar format.

It's not one of the ones i've been trying to 'duplicate' so i'll start up the relvant development box (I have 2 now, one for 32bit and another for 64bit), run one of the good as well as the failing builds and see if that's also the differance, if so it also means the problems I am coming up with may start with the changeover from barry's woof to woof-CE, GOODEE

OK i'll start from there and start with my first woof-CE and the earlier packageset and see what happens. 

sorry for the bother

**Comment by scsijon** [comment]
closed
