### ISSUE TITLE
gtk-server in Puppy?

### ISSUE THREAD

**Issue by jamesbond3142** [puppylinux-woof-CE/woof-CE#767]
Are you keen to put gtk-server into Woof-CE? Fatdog uses gtk-server mainly but still has gtkdialog so it can happily run Puppy scripts. If gtk-server is in Woof-CE then Puppy would be able to use Fatdog scripts too.Compressed size (xz) including all the docs are only 154K.

**Comment by mavrothal** [comment]
Zigbet is trying to develop a unique gtkdialog-based puppy-look which is shaping up in Slcko. Tahr/Xenial on the other hand use a mix of new and old style dialogs. If we add to that gtk-server based fatdog looks  we'll get a nice "Frankenstein" look (aaah, the Apple influence 😄 👅 ). 
Then again Linux is all about choices and options, so I see nothing wrong with a gtk-server pet, or a petbuild or even a rootfs-packages entry.

**Comment by jamesbond3142** [comment]
Ahh, the idea is just to enable cross-script compatibility between FD and Puppy. I definitely not suggesting that everyone abandons gtkdialog and switch to gtk-server; or to even code new native Puppy script on gtk-server. 

Anyway, perhaps this isn't a good idea - putting it in petbuild is probably better, anyone who needs it can get it through PPM.

I'm closing this - I'll just add gtk-server to petbuilds to whomever needs it.

**Comment by wdlkmpx** [comment]
The same thing happens when I try to run my yad scripts in puppy, yad
is either too old or not there... i guess it's just a matter of
talking personally to the people involved in building puppies to 1st
upload the pets and then convince them to add that pet to the distro
specs.. i find that procedure too much to handle, but it can be donde
i guess, i'm not sure, haven't tried it.

**Comment by peabee** [comment]
yad is already in:


http://distro.ibiblio.org/puppylinux/pet_packages-common/ 

On
25/04/2016 16:46, wdlkmpx wrote: 

> The same thing happens when I try
to run my yad scripts in puppy, yad
> is either too old or not there...
i guess it's just a matter of
> talking personally to the people
involved in building puppies to 1st
> upload the pets and then convince
them to add that pet to the distro
> specs.. i find that procedure too
much to handle, but it can be donde
> i guess, i'm not sure, haven't
tried it. 
> 
> --
> You are receiving this because you are subscribed
to this thread.
> Reply to this email directly or view it on GitHub
[1]

-- 
PB.............
 

Links:
------
[1]
https://github.com/puppylinux-woof-CE/woof-CE/issues/767#issuecomment-214407558
