### ISSUE TITLE
debdb2pupdb segfaulting part 3

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#771]
hi dimkr

the 32bit debdb2pupdb segfaults on the xenial repos ! however the 64bit one works fine which allowed me to do a xenial build.

i've temporarily stuck in quirkys debdb2pupdb into the build just so users can update the PPM.

here's the woof-distro files if you need them https://dl.dropboxusercontent.com/u/19554672/xenial.tar.xz

cheers

**Comment by 01micko** [comment]
Any chance you can pinpoint the line which causes the segfault? (just look at the end result - it should tell you). When you find that try and see what is different about that line, say non-ascii chars for example.

See Barry's comments about [removing UTF-8 chars.](http://barryk.org/news/?viewDetailed=00338)

**Comment by 01micko** [comment]
Ping @dimkr

**Comment by dimkr** [comment]
Very busy these days and my x86 laptop is sick, I'll take a look at this problem next week probably.

**Comment by dimkr** [comment]
Found 10 spare minutes for this - does not happen with the 32-bit debdb2pupdb. Trying again.

**Comment by wdlkmpx** [comment]
I see in 0setup that it always uses /usr/local/petget/debdb2pupdb .. what if it's outdated?

**Comment by 01micko** [comment]
> I see in 0setup that it always uses /usr/local/petget/debdb2pupdb .. what if it's outdated?

Doesn't matter. Outdated == s l o w - that's all. Produces same end result.

**Comment by 01micko** [comment]
This is fixed right? Closing.
