### ISSUE TITLE
Replace guess_fstype with a wrapper script?

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#777]
That runs blkid

This code uses busybox exclusively and behaves exactly like guess_fstype, not to mention that it does recognize the filesystem of /dev/loopX devices that guess_fstype does not

	#!/bin/busybox ash

	bb=busybox

	if [ "$1" = "" ] ; then
		echo "Usage: guess_fstype device"
		exit
	fi
	if [ ! -b "$1" ] ; then
		echo unknown
		exit 1
	else
		res=$($bb blkid "$1" | $bb sed -e 's|.*TYPE="||' -e 's|".*||')
		if [ "$res" = "" ] ; then
			echo unknown
			exit 1
		else
			echo "$res"
		fi
	fi

**Comment by wdlkmpx** [comment]
The steps are as follows:

1) create a script called guess_fstype
2) remove guess_fstype from all the DISTRO_PKGS_SPECS

A static blkid and busybox can be compiled for i486, x86_64, arm4-6 in the initrd_progs repo, which means that all puppies can integrate them even in the main SFS to accomplish a standard behavior among all derivatives and all versions.

**Comment by 01micko** [comment]
Maybe.. but @jamesbond3142 does have a guess_fstype patch for busybox which should be added to initrd_progs and petbuilds.

**Comment by wdlkmpx** [comment]
I'd like to see the patch

**Comment by 01micko** [comment]
See http://www.lightofdawn.org/blog/?viewDetailed=00020

**Comment by wdlkmpx** [comment]
It looks like busybox already has all those file systems

http://s32.postimg.org/4iph0e05h/capture30163.png

one of them or at least a previously unknown fs was added after 1.24
because it appeared as a new option, but i'm not sure.

I just wrote a patch to add -u/--update to busybox cp for the initrd
so I can disable compiling the coreutils version. It works quite well,
as expected, i think i'll submit that patch one of these days for
approval, i'll also add --remove-destination

**Comment by jamesbond3142** [comment]
I have a newer one here: http://distro.ibiblio.org/fatdog/source/700/patches/busybox-1.22-20130821-guess_fstype-applet.patch.

This one no longer includes f2fs detector which is already included in newer busybox.
It applied to 1.23.1, don't know how well it would apply to latest git or 1.24.

cheers!

**Comment by wdlkmpx** [comment]
Thanks jamesbond, your patch still applies cleanly, will be added in
the next commit

**Comment by 01micko** [comment]
Ok, closing this since it seems solved.
