### ISSUE TITLE
Simplify the build system

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#788]
I just noticed that in the forum there is a discussion about the init script that is actually 2. There is also 2  rc.sysinit (I have my own hybrid rc.sysinit ( http://pastebin.com/jLCGKFtk ) )

Everyone notices that sooner or later.

I think it's time to take a stand and just adopt one of the two and cleanup the code to use that specific implementation... regarding retro users... I am one, but I use the latest version of woof.

I think those using puppy4, wary... will not update to a woofce puppy. I also think that something below a P4-based cpu (intel netburst arch) is a piece for a museum as it's way too slow. Recent (or not-so-old) kernels actually run fine in an old cpus... I know that for sure.

I also think there's no need to add more variants, with slacko and the debian-based puppies is more than enough... perhaps a different experimental puppy would be something refreshing, something based on Sabotage Linux for example.

I think it's time just delete some files and adjust code, at least that's my style... I spend a lot of time writing code, but then i realize there is better way to do it... i just delete the old code without regrets  and replace it with the new code, but that's my style..

**Comment by wdlkmpx** [comment]
In woof-code there are some files safe to delete... the bacon files, the old init, the old 3builddistro,  any remaining bacon files should be written in C or a fast shell script (you know a shell script can be quite fast), some random files that doesn't appear to be useful anymore and so on... 

Also the code in rc.services... what does it do? It's quite unclear to me, if you remove the first and bloated code block and put a "sleep 6" or 7 instead.. the results are the same.

I also noticed that any app executed by that script must *terminate* or daemonize before the next service is run, if it happens to run a script or app that does not do one of the above... then strange things happen.. (that's why is very unsafe to have the standard "services" provided by some packages from the distros puppy uses, you have to check it first).

**Comment by wdlkmpx** [comment]
Perhaps the repo commit history also needs an intrusive cleanup operation? there is a huge 'find'  binary in the x86_64 static progs.. it that gets deleted (busybox can now handle the code), there will be a huge file in the history haha. Yes everything once placed in the repo stays forever in the history, even a 2.2GB movie

http://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository

**Comment by 01micko** [comment]
Go for it in new `rationalise` branch. See #789 

Be careful deleting the BaCon stuff. We should leave that until replacements are built and tested.

**Comment by wdlkmpx** [comment]
Ok, we'll further discuss in that issue. My first commit will actually be biggest change for some time

**Comment by 01micko** [comment]
Don't forget to pull in `testing` as i want to push a few minor changes, actually about to open an issue.
