### ISSUE TITLE
ptheme add 'puppy_icon_theme' at woof build stage

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#790]
Today I committed to the `noarch` repo the puppy_icon_theme re b1e748a

I'd like to add a block to add `PTHEME_ICONS_GTK` (a var in the globals) to the `rootfs-packages/ptheme/pinstall.sh`.

I suppose this is simple enough to append to `~/.gtkrc-2.0` but should we make 'puppy_icon_theme' (actual name is "Puppy Standard") default if `PTHEME_ICONS_GTK` is undefined?

@zigbert any thoughts?

**Comment by zigbert** [comment]
Yes,  this should be as simple as:
echo "gtk-icon-theme-name = \"$PTHEME_ICONS_GTK\"" >> $HOME/.gtkrc-2.0

Should puppy_icon_theme be default... ?

If we are talking about the value of PTHEME_ICONS_GTK, pTheme itself don't want it - as it stay idle if no value is defined. This is a speed issue. As long as $HOME/.gtkrc-2.0 contains the gtk-icon-theme-name definition, I see no reason for more.

But, if we are talking about using 'Puppy standard' icon-set over Hicolor in pinstall.sh, I think YES.That might require to set PTHEME_ICONS_GTK="Puppy Standard" if not defined in global theme.

**Comment by 01micko** [comment]
This what I have now in `/rootfs-packages/ptheme/pinstall.sh`

```shell
# icon theme
[ -n "$PTHEME_ICONS_GTK" ] && \
USE_ICON_THEME="`find usr/share/icons -type d -name "$PTHEME_ICONS_GTK" -maxdepth 1`"
[ -z "$USE_ICON_THEME" ] && USE_ICON_THEME="Puppy Standard" # default if exists
if [ -d "usr/share/icons/$USE_ICON_THEME" ];then
	# first global
	echo -e "gtk-icon-theme-name = \"$USE_ICON_THEME\"" >> root/.gtkrc-2.0
	# then ROX
	ROX_THEME_FILE="usr/local/apps/ROX-Filer/ROX/index.theme" # this could change in future
	cat > $ROX_THEME_FILE << _ROX
Name=$USE_ICON_THEME
Comment=custom icon theme
Directories=MIME
Example=inode:directory

[MIME]
Size=48
Context=MimeTypes
Type=Threshold	
_ROX
	echo "icon theme: $USE_ICON_THEME"
fi
```
Just testing the ROX part now. This uses "Puppy Standard" (if it exists) by default. I do have another theme to test that does NOT use "Puppy Standard' - it is rather bloated though so will be offered at some point as an SFS.

**Comment by 01micko** [comment]
Note: the above code sets "Puppy Standard" as default only if it exists. I have been testing it since April now and it has exceeded my expectations.

PTHEME_ICONS_GTK need not be set. But I see no reason _not_ to use the "Puppy Standard" if it exists. All my tests point to SVG being much lighter and possibly faster than any other format with recent GTK+-2.0. If we ever have to move to GTK+-3.0 (I hope not but even Firefox has gone there now) then we are very well placed as the standard for theming there relies on CSS.

**Comment by 01micko** [comment]
The above code fails.

Testing this now...

```shell
	ROX_THEME_FILE="root/.config/rox.sourceforge.net/ROX-Filer/Options" # this could change in future
	sed -i "s%ROX%$USE_ICON_THEME%" $ROX_THEME_FILE
	echo "icon theme: $USE_ICON_THEME"
```

Should work. (This is for mimetypes).

**Comment by 01micko** [comment]
All working OK. I'll commit this to testing soon.

**Comment by 01micko** [comment]
Here is a build screeny (in qemu) - all working well. Take note of the icons in the Rox toolbar and the mime icons.

![pristine_boot](https://cloud.githubusercontent.com/assets/1019119/15805184/86700108-2b65-11e6-8b10-a64423f17b5b.jpg)

**Comment by zigbert** [comment]
Absolutely cool stuff :-D

**Comment by peabee** [comment]
see
https://github.com/puppylinux-woof-CE/woof-CE/issues/1091
