### ISSUE TITLE
PupCamera digital camera access should not be provided by rootfs-skeleton

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#809]
PupCamera digital camera access should be a .pet rather than provided in rootfs-skeleton (it is very rox specific and needs updating for latest xserver_xorg)

**Comment by 01micko** [comment]
Hopefully it works in thunar|pcmanfm|spacefm now. I tested in an older lxpup-sc (from last month) and rg66's Xslacko-4.0. Seems ok to me.

**Comment by 01micko** [comment]
BTW, @zigbert rox switches are restored if we determine rox is the FM.

**Comment by zigbert** [comment]
:+1:
