### ISSUE TITLE
root/.packages/builtin_files only contains the packages from rootfs-packages

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#814]
BUILD_FROM_WOOF='testing;b83db13;2016-06-15 17:37:12 +1000'

root/.packages/builtin_files only contains the packages from rootfs-packages - see list below

root/.packages/woof-installed-packages has the full list of packages

ls builtin_files/
change_kernels  get_java    pclock       pmirror    ptheme         sandbox
firewall_ng     jwm_config  pfilesearch  pmusic     ptheme_buntoo  wallpaper
frisbee         mscw        pfind        pprocess   ptiming
getflash        pburn       pgprs        pschedule  pupx

**Comment by wdlkmpx** [comment]
That is in testing, strange. I'm also building in rationalise and the "builtin_files" dir has 422 files, slacko. Haven't produced a puppy yet as I made some mistakes in 2createpackages which made main sfs grow by 50MB xz compressed (already fixed).

A huge list should be there

I also don't like the way the filelists are produced, with convoluted post-processing, I guess this is to save bytes, the result also needs a convoluted post-processing to check the files.

**Comment by peabee** [comment]
I think this was caused by moving the packages-*** directory out of the woof-out_*** directory and linking it back. Everything except built_in files worked. Closing the issue.
