### ISSUE TITLE
Firmware in zdrv

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#821]
kernel-kit builds 33 items of firmware into the zdrv as shown below

Where does this firmware come from? Is it all necessary to be included in zdrv? Can any of it be moved to an fdrv?

> ls -R    
> .:
> 3com      bnx2x     emi62        mts_edge.fw  sun           whiteheat.fw
> acenic    cis       ess          mts_gsm.fw   tehuti        whiteheat_loader.fw
> adaptec   cxgb3     kaweth       ositech      ti_3410.fw    yamaha
> advansys  e100      keyspan_pda  qlogic       ti_5052.fw
> av7110    edgeport  korg         r128         tigon
> bnx2      emi26     mts_cdma.fw  radeon       ttusb-budget
> 
> ./3com:
> typhoon.bin
> 
> ./acenic:
> tg1.bin  tg2.bin
> 
> ./adaptec:
> starfire_rx.bin  starfire_tx.bin
> 
> ./advansys:
> 3550.bin  38C0800.bin  38C1600.bin  mcode.bin
> 
> ./av7110:
> bootcode.bin
> 
> ./bnx2:
> bnx2-mips-06-6.2.1.fw   bnx2-rv2p-06-6.0.15.fw  bnx2-rv2p-09ax-6.0.17.fw
> bnx2-mips-09-6.2.1a.fw  bnx2-rv2p-09-6.0.17.fw
> 
> ./bnx2x:
> bnx2x-e1-6.2.9.0.fw  bnx2x-e1h-6.2.9.0.fw  bnx2x-e2-6.2.9.0.fw
> 
> ./cis:
> 3CCFEM556.cis  DP83903.cis    PCMLM28.cis    SW_555_SER.cis
> 3CXEM556.cis   LA-PCM.cis     PE-200.cis     SW_7xx_SER.cis
> COMpad2.cis    MT5634ZLX.cis  PE520.cis      SW_8xx_SER.cis
> COMpad4.cis    NE2K.cis       RS-COM-2P.cis  tamarack.cis
> 
> ./cxgb3:
> ael2005_opt_edc.bin  ael2020_twx_edc.bin  t3c_psram-1.1.0.bin
> ael2005_twx_edc.bin  t3b_psram-1.1.0.bin
> 
> ./e100:
> d101m_ucode.bin  d101s_ucode.bin  d102e_ucode.bin
> 
> ./edgeport:
> boot2.fw  boot.fw  down2.fw  down3.bin  down.fw
> 
> ./emi26:
> bitstream.fw  cpia2  firmware.fw  loader.fw
> 
> ./emi26/cpia2:
> stv0672_vp4.bin
> 
> ./emi62:
> bitstream.fw  loader.fw  midi.fw  spdif.fw
> 
> ./ess:
> maestro3_assp_kernel.fw  maestro3_assp_minisrc.fw
> 
> ./kaweth:
> new_code.bin  new_code_fix.bin  trigger_code.bin  trigger_code_fix.bin
> 
> ./keyspan_pda:
> keyspan_pda.fw  xircom_pgs.fw
> 
> ./korg:
> k1212.dsp
> 
> ./ositech:
> Xilinx7OD.bin
> 
> ./qlogic:
> 1040.bin  12160.bin  1280.bin
> 
> ./r128:
> r128_cce.bin
> 
> ./radeon:
> R100_cp.bin  R600_pfp.bin   RV610_pfp.bin  RV635_pfp.bin  RV730_pfp.bin
> R200_cp.bin  RS600_cp.bin   RV620_me.bin   RV670_me.bin   RV770_me.bin
> R300_cp.bin  RS690_cp.bin   RV620_pfp.bin  RV670_pfp.bin  RV770_pfp.bin
> R420_cp.bin  RS780_me.bin   RV630_me.bin   RV710_me.bin
> R520_cp.bin  RS780_pfp.bin  RV630_pfp.bin  RV710_pfp.bin
> R600_me.bin  RV610_me.bin   RV635_me.bin   RV730_me.bin
> 
> ./sun:
> cassini.bin
> 
> ./tehuti:
> bdx.bin
> 
> ./tigon:
> tg3.bin  tg3_tso5.bin  tg3_tso.bin
> 
> ./ttusb-budget:
> dspbootcode.bin
> 
> ./yamaha:
> ds1_ctrl.fw  ds1_dsp.fw  ds1e_ctrl.fw
> #

**Comment by ninaholic** [comment]
I have the option to add firmware or not with kernel-kit.
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/kernel-kit/build.sh#L522

The one you posted is matches the 9.7MB option one here I think:
http://distro.ibiblio.org/puppylinux/firmware/

It sounds like stemsee removed the option in his fork to simplify things?

**Comment by wdlkmpx** [comment]
Actually that's something easy to do, peebee try my kernel-kit-zzzzz.. tarball posted on the forum.. if it's working correctly, then I might add the changes you want. I won't touch the woofce kernel-kit, because I've already edited it.

**Comment by gyrog** [comment]
When are we going to stop pretending that firmwsare is poroduced by compiling the kernel?
Remove firmware from the kernel process, and have a separate firmware update mechanism.
Then remove all firmware from the zdrv, and have either limited or all firmware in fdrv.
If puppy producers want to, they can easily merge the fdrv and zdrv in their iso.

**Comment by wdlkmpx** [comment]
There is also firmware in the kernel skeleton. It should no be there.. 15MB

The firmware is not produced when compiling a kernel (as far as I can tell some firmware do), but following the logic in kernel-kit, it's needed to trim it down applying some rules (this is totally incomplete and unreliable). I'd suggest to forget about it and just ship a fdrv.sfs with all firmware (past, present and future). Stop worrying about the iso size.

Is the main SFS file the only one that is copied to ram? Then there should be no problem.

The logic in the initrd should be this: if (RAM > (mainSFS_size * 3)) then it's ok to load it into ram.


I also think the default iso should come with most modules already in ZDRV... this makes puppy really generic and for all tastes.

**Comment by wdlkmpx** [comment]
I forgot to add, when rox filer is there, no matter how complete and friendly puppy becomes.. most people will still disregard puppy as soon as they discover they can't copy and paste files using keyboard shortcuts.. (don't know why they used to say puppy is for windows refugees...).

**Comment by gyrog** [comment]
There is code in init  to only copy stuff to ram if the ram is big enough, but the algorithm could easily be revisited.
I am thinking of an extension to "pfix=nocopy", so that it is possible to specify which sfs's should never be copied to ram.
Of course all this gets thrown out the window if booting "pfix=ram".

**Comment by peabee** [comment]
How do I tell kernel-kit that I want no firmware in zdrv? There seems to be no such option in build.conf....
I notice that the kernel_sources .sfs has firmware in it - from "somewhere"....is it just getting passed down from the previous kernel_sources to the next?? Can I break the cycle by removing the firmware manually?
I will do a manual experiment to remove all firmware from the zdrv and put it into the fdrv instead....

**Comment by 01micko** [comment]
> There is also firmware in the kernel skeleton. It should no be there.. 15MB

I can't discuss why that is there. Drop me an email. You can either use the address on my site or 01micko AT gmail

**Comment by peabee** [comment]
The firmware comes from the vanilla linux kernel tarball....the readme in the directory says:

> This directory is only here to contain firmware images extracted from old
> device drivers which predate the common use of request_firmware().

so perhaps kernel-kit should remove this directory during the clean process??

**Comment by peabee** [comment]
The experiment to move all firmware out of zdrv and put it into fdrv (rationalise branch build) worked fine as @gyrog said it would....

**Comment by ninaholic** [comment]
Thanks peebee. I did not realize the linux kernel tarball itself came shipped with firmware inside, as I always selected one of the bottom 3 options (instead of the "I'll copy in my own.") one.

**Comment by peabee** [comment]
Hi Nina

Please note the extract from the readme - the firmware in the kernel 
tarball is not general purpose - it's there for old drivers.....

**Comment by peabee** [comment]
kernel-kit has been amended to ask for firmware option - thanks @wdlkmpx 
fdrv is now fully supported - thanks @gyrog 
closing this issue

**Comment by wdlkmpx** [comment]
I haven't tested that stuff since... months ago, so if you have any
comments, ideas, issues to report, just explain yourself...

There is an option the use the firmware tarballs from ibiblio and from
the official git repo.. i think it's working

There is an option to choose firmware according to built modules
extracting the files from the local git dir... that isn't working as
expected, it needs many rules.

There is an option to create the firmware sfs with the files specified
in firmware.lst... that should include radeon firmware.. haven't
looked at it yet.

I think this is something that can also done in 3builddistro.

**Comment by peabee** [comment]
I use option 3 - but don't add any extra firmware into the zdrv
I supply extra firmware in the fdrv in the iso - the fdrv can be replaced by a bigger or smaller version as the user requires/needs....most people seem reasonably happy with the 15.5MB version I ship.
I don't know if the other options work.
