### ISSUE TITLE
Overwriting /lib/$ARCHDIR breaks puppy

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#822]
[3builddistro](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/3builddistro-Z#L495) generates symlinks for /lib/$ARCHDIR /usr/lib/$ARCHDIR /usr/bin/$ARCHDIR that link to upstream directory. When a package with such a folder is installed, will overwrite the link and break the built.
Test case install libnih1 in Xenialpup64. Will overwrite the  /lib/x86_64-linux-gnu symlink and the build will break till you remove the /initrd/pup_rw/lib/x86_64-linux-gnu folder.
As a matter of fact as soon as you overwrite or delete the symlink, puppy will break.
PPM could be modified to force pet packages or slackware packages to respect symlinks (use the -h option in tar) but dpkg-deb or dpkg, do not provide such an option.

It might be better to have  /lib/$ARCHDIR as a directory and link its content to /lib/<filename>

**Comment by mavrothal** [comment]
Here is a workaround patch to extract in /tmp and copy each file and link avoiding overwriting the $ARCHDIR symlink.

```
--- a/usr/local/petget/installpkg.sh
+++ b/usr/local/petget/installpkg.sh
@@ -261,7 +261,24 @@
   [ $? -ne 0 ] && exit 1
   echo "$PFILES" > /root/.packages/${DLPKG_NAME}.files
   install_path_check
-  dpkg-deb -x $DLPKG_BASE ${DIRECTSAVEPATH}/
+  # Workaround for overwriting x86_64-linux-gnu symlink
+  # Should also be done for i386-linux-gnu too
+  mkdir -p /tmp/$DLPKG_BASE
+  rm -rf /tmp/$DLPKG_BASE/*
+  dpkg-deb -x $DLPKG_BASE /tmp/$DLPKG_BASE/
+  for f in $(find /tmp/$DLPKG_BASE \( -type f -o -type l \))
+  do
+	xf=$(echo $f | cut  -f 4-30 -d "/")
+	if [ "$(echo $xf | grep x86_64\-linux\-gnu)" = "" ]; then
+		mkdir -p /$(dirname $xf)
+		cp -a $f /$(dirname $xf)/
+	else
+		xpath=$(echo $xf | sed 's/x86_64\-linux\-gnu\///')
+		mkdir -p $(dirname $xpath)
+		cp -a $f /$(dirname $xpath)/
+	fi
+  done
+  rm -rf /tmp/$DLPKG_BASE
   [ $? -ne 0 ] && clean_and_die
   [ -d /DEBIAN ] && rm -rf /DEBIAN #130112 precaution.
   dpkg-deb -e $DLPKG_BASE /DEBIAN #130112 extracts deb control files to dir /DEBIAN. may have a post-install script, see below.
```
A better solution should be found or improve this one (at least include all the $ARCHDIR options)
Sorry no time for more.

**Comment by mavrothal** [comment]
Just a bit more generic version of the workaround patch
```
--- a/usr/local/petget/installpkg.sh
+++ b/usr/local/petget/installpkg.sh
@@ -261,7 +261,24 @@
   [ $? -ne 0 ] && exit 1
   echo "$PFILES" > /root/.packages/${DLPKG_NAME}.files
   install_path_check
-  dpkg-deb -x $DLPKG_BASE ${DIRECTSAVEPATH}/
+  # Workaround for overwriting $DISTRO_ARCHDIR symlink. ie /lib/x86_64-linux-gnu 
+  # Should be done for others that may be also present. ie i386-linux-gnu 
+  if [ "$DISTRO_ARCHDIR" = "" ]; then
+	dpkg-deb -x $DLPKG_BASE ${DIRECTSAVEPATH}/
+  elif [ "$DISTRO_ARCHDIR" != ""  -a "$(echo "$PFILES" | grep "$DISTRO_ARCHDIR")" = "" ]; then
+	dpkg-deb -x $DLPKG_BASE ${DIRECTSAVEPATH}/
+  elif [ "$DISTRO_ARCHDIR" != "" -a "$(echo "$PFILES" | grep "$DISTRO_ARCHDIR")" != "" ]; then
+	mkdir -p /tmp/$DLPKG_BASE
+	rm -rf /tmp/$DLPKG_BASE/*
+	dpkg-deb -x $DLPKG_BASE /tmp/$DLPKG_BASE/
+	for f in $(find /tmp/$DLPKG_BASE \( -type f -o -type l \))
+	do
+		xpath=$(echo $f |  cut  -f 4-30 -d "/" | sed "s/$DISTRO_ARCHDIR\///")
+		mkdir -p $(dirname $xpath)
+		cp -a $f /$(dirname $xpath)/
+	done
+	rm -rf /tmp/$DLPKG_BASE
+  fi
   [ $? -ne 0 ] && clean_and_die
   [ -d /DEBIAN ] && rm -rf /DEBIAN #130112 precaution.
   dpkg-deb -e $DLPKG_BASE /DEBIAN #130112 extracts deb control files to dir /DEBIAN. may have a post-install script, see below.
```

**Comment by wdlkmpx** [comment]
Looks good. In 2createpackages there is also a way to do this but with
hardcoded path:

if [ -d sandbox2/lib/$ARCHDIR ];then
if [ -d sandbox2/usr/lib/$ARCHDIR ];then
if [ -d sandbox2/usr/bin/$ARCHDIR ];then

/bin and /usr/include missing..

**Comment by mavrothal** [comment]
Committed in  10b8aea. Though someone fix spacing as browser editing does not respect tab and space strokes...

**Comment by mrfricks** [comment]
thanks for the fix though i haven't tested it yet.

however i think that it's one of xenialpup64's packages that's the problem.

early builds of tahrpup64 used to exhibit this same behavior of the symlink not being respected and being overwritten by a folder (this included the one in /usr/lib).
the release build of tahrpup64 does respect the /lib/x86_64-linux-gnu symlink!

this issue only became fixed when i updated  various packages to ones compiled by barry k' and 01micko, i don't know which package was/is the problem though  

.... any ideas?

**Comment by wdlkmpx** [comment]
There are a number of packages with the same problem, it happened a
lot in precise, that's one of the reasons i didn't use petget. i have
2 scripts that deal with deb packages in a simple way, install2root
and undebs.. basically extract the file to a temp folder and run this
function:

	function FixMultiArch() {
		local dir2fix="$@"
		. /etc/DISTRO_SPECS #$DISTRO_ARCHDIR
		if [ "$DISTRO_ARCHDIR" ] ; then
			for BASEDIR in bin lib usr/bin usr/lib usr/include ; do
				if [ -e ${dir2fix}/${BASEDIR}/${DISTRO_ARCHDIR} ] ; then
					cp -a --remove-destination
${dir2fix}/${BASEDIR}/${DISTRO_ARCHDIR}/* ${dir2fix}/${BASEDIR}/
2>/dev/null
					rm -rf ${dir2fix}/${BASEDIR}/${DISTRO_ARCHDIR}
				fi
			done
		fi
	}

That code is also in 2createpackages in rationalise:
https://github.com/puppylinux-woof-CE/woof-CE/commit/2e7a99058844a16125e62044bf4d47e85685fb0c

**Comment by 01micko** [comment]
Perhaps we should kill the symlink. That will break all legacy packages I suppose but that is easier to fix than bending and possibly breaking upstream packages and the target distro itself.

**Comment by rogerlga** [comment]
The workaround in 10b8aea inserts a new bug when running on PUPMODE != 2, leading to an incomplete installation of the .deb package. That's because the patch is not taking $DIRECTSAVEPATH into consideration, which results in the files being copied to tmpfs. Later, on the "flush unionfs cache" part of the code, all the files just installed get removed with execution of line `[ -e "/initrd/pup_rw${ONESPEC}" ] && rm -f "/initrd/pup_rw${ONESPEC}"`.

In my xenialpup64 frugal install, I solved the issue by changing some lines of the workaround patch, as below:

> mkdir -p ${DIRECTSAVEPATH}/$(dirname $xpath)
cp -a $f ${DIRECTSAVEPATH}/$(dirname $xpath)/

Hope it helps!
