### ISSUE TITLE
Add at "trusty-lite-pae-backport" and Problem with compile

### ISSUE THREAD

**Issue by Illutorium** [puppylinux-woof-CE/woof-CE#826]
Source for Issue: murga-linux.com/puppy/viewtopic.php?t=107514
About at Fail Compile and Ask to add "trusty-lite-pae-backport"

**Comment by wdlkmpx** [comment]
Uhmm what do you mean exactly?

**Comment by wdlkmpx** [comment]
I see you're providing config files or "build recipes". It's not clear what you're trying to say, but i guess you're using the master branch now. Well, soon the testing branch will be merged to master and the rationalise branch will be merged to testing. Although i'm not sure why keep master branch if it's so outdated.

You have to read the CHANGELOG and the README files.
