### ISSUE TITLE
 kernel kit build.conf defaults

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#842]
in the kernel kits build.conf the 'remove kernel sublevel' default is set to 'sublevel=yes'.  this causes problems when trying to compile graphic drivers as they expect a proper version number for the kernel.

i think the default should be set to 'no' and also the option renamed to 'remove_sublevel' as on first read 'sublevel=yes' makes you think that you'll actually get a sublevel .

**Comment by ninaholic** [comment]
Another thing that confused me is the menu says

1. make menuconfig
2. make gconfig
3. make xconfig
4. make oldconfig
s. skip

I thought the last one said 5, and when I pressed 5 it did "make menuconfig" - lol.
