### ISSUE TITLE
petspecs getting prefered over Packages-puppy-*-official

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#843]
i was wondering why when building xenial 'uget' gets missed. ugets petspecs are

```
uget-1.4.8.5-1-pup4|uget|1.4.8.5-1-pup4||Internet|196K||uget-1.4.8.5-1-pup4.pet|+gtk+,+curl,+openssl|Uget download manager|puppy|4||
```

it seems because it says |puppy|4|| at the end, it gets ignored. changing it to |||| works.

this isn't much of a problem for xenial but it completely breaks the tahrpup64 build as it has lot of packages from april in its repo. 

i think Packages-puppy-*-official should be respected whatever petspecs it contains

**Comment by wdlkmpx** [comment]
there are rules in findpkgs, i haven't changed them, but i'll look into this

changing the rules can also cause side effects and basically the repos must be in the correct order.

**Comment by wdlkmpx** [comment]
puppy4 packages must be avoided, and basically a "team" should be working to update some "common" packages and keep  all distro pkgs specs up to date

**Comment by mrfricks** [comment]
uget was just as example ... my main concern is that the change has broken tahrpup64 and possibly tahrpup32 builds which used to build nearly perfectly (as long as you chose the right background :) )  i think it'll also confuse new comers to woofCE

i can bodge it my end by just changing the end of all lines in Packages-puppy-tahr64-official to ||||  not ideal but works.... but i still think Packages-puppy-*-official should be respected whatever its contents as it used to be.

**Comment by wdlkmpx** [comment]
hmm i'll perform some tests, i'll try to fix today..

**Comment by wdlkmpx** [comment]
i see dead peopl

**Comment by wdlkmpx** [comment]
xenial 32.

i see something's wrong with the uget pkg

in 1download, the script downloaded uget like 5-10 times. suspicious i thought.

md5sums dont match:
a673683513bc31e187eeefb30d6afbbe
79ce1f16662e242c2ca1110a8427bbb9

pet2tgz fails... i had to go back in time to a previous revision...
and it still fails. the package might be "damaged".

now with a tahrpup 32/64... this will take some time.

**Comment by wdlkmpx** [comment]
tahrpup 64

well, apparently all packages were downloaded. so far i see no issues. maybe the problems begin in 2createpackages?

i removed some unused and old entries from the distro pkgs specs file. it's good to know a that a tahrpup comes with lxtask and lxrandr.... lxterminal is missing (60kb), these apps are lightweight and generic, also gmrun is worth looking at, useful tiny generic apps

**Comment by wdlkmpx** [comment]
this is what i do to download the repo

git clone repo-url

to update (inside the woofce dir): git pull

then i type ./merge2out

(choose arch, distro and version)

and i have a new woof environment ready to work with the latest changes.

**Comment by 01micko** [comment]
I think this is fixed. Correct me if wrong and re-open as necessary.
