### ISSUE TITLE
cron and pschedule issues

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#860]
pschedule and cron are in a bit of a mess.....

in rootfs-skeleton crontabs is in /var/spool/cron

pschedule uses /var/local/cron and ignores /var/spool/cron

rootfs-skeleton should be changed to be consistent with pschedule? or vice-versa

in rootfs-packages/pschedule/usr/local/pschedule/pschedule at lines 50-64 a shellscript cron-check is created in root/.config/autostart

root/.config/autostart is only meant to contain .desktop files and the readme says any other files are ignored....so cron-check never runs and the crond daemon is never started

cron-check should be created somewhere else - either in ~/Startup or /etc/init.d ?? and needs to be a properly formed shellscript (with #!/bin/sh )?

crond should be a system service appearing in Menu->System->Boot Manager->Services ??

**Comment by wdlkmpx** [comment]
Yes, /var/spool/cron is the location, and yes cron-check or crond must be a "service"... i'll fix this..

**Comment by wdlkmpx** [comment]
hahaha i clicked the wrong button

i addressed this issue, but i have doubts. before i push the changes, i have questions.. how do people use this? is it meant to work only when X is running?, etc..

**Comment by wdlkmpx** [comment]
ok, test the modified pSchedule.. i think there is room for another checkbox "Only when X is running"

**Comment by wdlkmpx** [comment]
from what i can tell by reading the script.. pschedule is not meant to be THE cron gui, but a simple gui to run cron when X starts.. i guess that's why is using /var/local

should i move the crond service to /usr/local/pschedule and use /usr/local/cron ?

**Comment by wdlkmpx** [comment]
It's working as a service and i just fixed a bug, let me know if you want to restrict pschedule to  /usr/local/pschedule and /var/local/cron (this is a symlink to /var/spool/cron..)

**Comment by peabee** [comment]
Hi
This arose from trying to get snap2 to do an incremental backup each evening at 9pm.
The investigation started because the backup wasn't happening....
My opinion is that a single crond service is all that's required and that pschedule and cron used directly should use the same crontabs.
I'll do a rebuild using the latested updates and then close this issue (assuming success). I'll probably then reverse the changes I made to snap2.

**Comment by peabee** [comment]
Test build shows all now AOK - thanks.
