### ISSUE TITLE
files missing from kernels built with the kernel kit

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#870]
not sure when things changed but the zdrv.sfs built for tahrpup had some extra files in /lib/modules/$kernel version
```           
modules.builtin.bin  modules.order
modules.alias      modules.dep          modules.softdep
modules.alias.bin  modules.dep.bin      modules.symbols
modules.builtin    modules.devname      modules.symbols.bin
```
these are missing from the zdvr.sfs built with the latest kernel kit.. 
some but not all get created when you boot, but modules.builtin & modules.order are missing and cause modprobe errors
```
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.4.19/modules.builtin.bin'
```

**Comment by wdlkmpx** [comment]
modules.dep.bin is generated by depmod

http://man7.org/linux/man-pages/man5/modules.dep.5.html

i'm not sure if those files were generated by kernel-kit. the way to
know is by compiling a kernel with the kernel kit in the legacy branch

git checkout legacy

**Comment by mrfricks** [comment]
those files are in previous zdrv.sfs which were built with legacy
depmod seems to need modules.builtin & modules.order 
```
depmod
depmod: WARNING: could not open /lib/modules/4.4.19/modules.order: No such file or directory
depmod: WARNING: could not open /lib/modules/4.4.19/modules.builtin: No such file or directory
```

**Comment by mrfricks** [comment]
just tried the new slacko64 7.0.0 alpha and that has the same issue

**Comment by wdlkmpx** [comment]
yesss.. you're right. it was my fault.

i tried to compile a tiny kernel, but there was error. but i think commit https://github.com/puppylinux-woof-CE/woof-CE/commit/a5444f24763dea414ce69a57d7fc3e4e269b3b65 fixes this issue

**Comment by wdlkmpx** [comment]
although the files can be found in /etc/modules ... with a couple lines in rc.sysinit it can restore those files to their proper location if they're missing.

**Comment by wdlkmpx** [comment]
In /etc/modules there is also DOTconfig-$kernel_version and the same file in /boot/config-$kernel_version

I've seen docs saying /boot/config-$kernel_version is the right path

http://stackoverflow.com/questions/14587251/understanding-boot-config-file

**Comment by ninaholic** [comment]
Thanks @mrfricks and @wdlkmpx. I saw modprobe evdev fatal on first boot also, will try to rebuild 3.14.77 again. :relieved:

**Comment by 01micko** [comment]
@ninaholic  you shouldn't need to because the bug was in rc.sysinit. The kernel should be fine.

**Comment by gyrog** [comment]
Sorry for not commenting earlier, but init uses modules.order, so pelase fix in zdrv not in rc.sysinit.

**Comment by mrfricks** [comment]
wdlkmpx i built kernel 4.7.2 and it;s now fixed. modprobe & depmod working

thanks
