### ISSUE TITLE
woof-output-sqzd-4.101-uefi

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#872]
Where is that dir coming from? When I run merge2out it always reappears.

Doesn't affect anything but surely doesn't look great. :stuck_out_tongue:

**Comment by wdlkmpx** [comment]
i've never seen that dir after running merge2out.. steps to reproduce?

**Comment by 01micko** [comment]
only occurs with slacko64 on x86_64 host using 14.2

x86 host with x86 target is fine
