### ISSUE TITLE
Question: /lib treated differently in adrv vs. sfs

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#881]
Question: why if I have an sfs with an udated library in /lib does that library get replaced if I install the sfs as an adrv but does **not** get replaced if I use sfs-load to install the sfs?? I would expect the 2 mechanisms to behave consistently.....

**Comment by 01micko** [comment]
> I would expect the 2 mechanisms to behave consistently.....

Why?

**a, f, y and z** drives are _system_ sfs files that can be incorporated in an iso image and get loaded _before_ a save file. _Any other sfs_ (which can include an a, y etc drive) which is loaded by *sfs_load* is treated more like a package in that it can be _installed_ or _uninstalled_  just like any other package.

Sure, you can change an [afyz]_*_drv.sfs but of course that requires a reboot and can't be done 'on the fly'.

You can't load something above something that is already on the stack.

Hope this clarifies.

**Comment by ninaholic** [comment]
@peabee : This post by gyro explains the layering a bit more too:
http://www.murga-linux.com/puppy/viewtopic.php?p=906486#906486
