### ISSUE TITLE
Using xorg evdev

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#882]
Today i pushed some changes with some code and ideas from 01micko in the xorg branch.

The new xorg.conf.udev is basically for this, /usr/local/xorg_input is the flag file to force this behavior (it has to be manually created).

The current code works but there are a couple of issues:
- xorg evdev does not work with the current /etc/X11/xkb  (at least in slacko 700a),
i tested a xkb dir from ubuntu yaketty and it works
- now that the kbd is working, the up key opens the "defaultscreenshot"
i've been reading about this, but i couldn't fix the issue following the suggested solutions,  however the issue is fixed by removing this line from  /root/.jwm/jwmrc-personal

	[Key keycode="111"]exec:defaultscreenshot[/Key]

ps: xkbconfigmanager may work with the new approach, editing /etc/X11/xorg.conf.d/90-keyboard-layout.conf but it needs to be placed in rootfs-skeleton.. it don't see it there.

**Comment by wdlkmpx** [comment]
the new xorg template uses the AutoAddDevices option and input configs, placing the evdev keyboard layout stuff in the same template makes sense, and basically there would be nothing else to change 

i have ideas but i think i have to write them down or something. i think it's a good idea for micko to post a test iso here next week maybe. @mrfricks might also want to track this issue or something

**Comment by 01micko** [comment]
Since I pushed the complementary changes to this I'm going to close.
