### ISSUE TITLE
1choosepackages and woof_gui

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#885]
does anybody use these scripts?

my intention is to delete them

**Comment by 01micko** [comment]
I think it is for the GUI. We should probably leave it as the GUI is a good idea but certainly will need some work.

**Comment by wdlkmpx** [comment]
Today i built a slacko using the woof-next branch and its superioriy
in concept and design is over 9000, i like it. Although mouse and
keyboard did not work, it reached the desktop and that was enough to
make it worthwhile.. it was a truly fast build.

I fixed a couple bugs in the current build system, it can be improved
and simplified a bit more with the creation of a build.conf and
finally implementing the ideas that were discussed here - basically
for the slackware compat as i have no interest in any of the other
compat distros... and a gui is not needed, specially one that is not
finished. It's good for users, but not for builders and developers.
that only encourages illiteracy.. specially in a very complex build
system like woofce, where everyone who builds must understand how it
works.

I also want to bring the woof-next stuff to the current branch, for
testing purposes, but i'm not sure i if can do that. Not trying to
replace anything.

So... i request permission to delete any files related to woof_gui...
