### ISSUE TITLE
The DEVDIR.tar.gz (dev.tar.gz) files

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#888]
These tar files contain device nodes, i've seen puppies (slacko 6.x?) working without these files.

I guess they were quite used in the past.. anybody know if kernels 3.2+ can always work fine without these files?

**Comment by dimkr** [comment]
If a devtmpfs is mounted at /dev, yep.

**Comment by wdlkmpx** [comment]
I see..  'It provides a fully functional /dev directory, where usually udev runs on top, managing permissions and adding meaningful symlinks.' I've seen devtmpfs present in the config tools of 2.x kernels as well.

devtmpfs is enforced. it's the only way... so i'll delete those files.

**Comment by wdlkmpx** [comment]
haha i have to close this  manually
