### ISSUE TITLE
Kernel kit adding strange files since 25-sep-16

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#889]
Kernel kit seems to be putting libau files at the topmost directory since c. 25-sep-16....doesn't seem correct??

![4 7 4](https://cloud.githubusercontent.com/assets/5926865/19417036/a4882c0a-9399-11e6-80a9-286830639cba.png)

![4 7 5](https://cloud.githubusercontent.com/assets/5926865/19417038/aaafed34-9399-11e6-8e59-a654c2ccf5b1.png)

**Comment by ninaholic** [comment]
Hi peabee,

Can someone post how to make a 4.7 kernel with the woof-ce kernel-kit? I only see dotconfig for 3.2, 3.14, and 4.1 branch, and using "no config" option and writing 4.8 downloaded it, then failed shortly after.

**Comment by wdlkmpx** [comment]
those files should be /usr/lib .. it is unknown why they are there. here is a workaround (i haven't tested it)... https://github.com/puppylinux-woof-CE/woof-CE/commit/cb66e0fc17333111c173519ea15b559ca99f9e46 . let me know if it works..

ninaholic just rename one of the files. ex: DOTconfig-4.4.17-i686-pae > DOTconfig-4.8.1-i686-pae   ..... DOTconfig-4.1.10-slacko64 > DOTconfig-4.8.1-slacko64

then configure the kernel accordingly. this last step is usually time consuming. Replace DOTconfig-4.8.1-slacko64 with the contents from the newly configured kernel. store the new config for when you need it again

**Comment by wdlkmpx** [comment]
I forgot to add ' \' .. https://github.com/puppylinux-woof-CE/woof-CE/commit/57fa13cc769a11c2108d810f6decb2042c211776

**Comment by peabee** [comment]
Thanks - will test on next kernel build - 4.8.2 - the kernels seemed to work fine with these libau files in the wrong location - just looked untidy ......go figure!

**Comment by wdlkmpx** [comment]
by the way, nh, you can find peebee's config file in
/boot/config-X.XX.XX, you can use that one to build, /boot is the
standard location where kernel config and System.map are stored, or so
i read

**Comment by peabee** [comment]
Kernel 4.8.2 built correctly....
