### ISSUE TITLE
3builddistro

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#892]
Well, this script asks too many questions... i don't think this script is meant to be used quite often, but every once in a while

i'm moving some stuff to _0build.conf to produce a more automated build process.. i'm building and it creeps me out. this might or might not be pushed (i'm not using the gui). 

there is also the rootfs-packages issue. i think the pkgs specs should select these pkgs. if there is conflict specially the rox/jwm stuff, the packages should be renamed to <pkgname>_ce

the uefi stuff is in rootfs-packages? shouldn't it be in woof-code/boot?

to make things simpler.. so what do you think?

**Comment by wdlkmpx** [comment]
well, now checking woof_gui.. it needs an update. some things are gone. i'll edit this my way

**Comment by wdlkmpx** [comment]
well i think i made 3builddistro more straightforward. it could be better, but without communication i

**Comment by peabee** [comment]
3builddistro-Z is **MUCH** better - thanks - config file means unattended builds are now almost possible (still have to wait for the wallpaper question before being able to go away for a coffee...) and the broken symlink phase is now considerably quicker - as is the built-in pet creation etc. Excellent job!
