### ISSUE TITLE
rox defaults

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#893]
Working through pain

When working with rox it has come to my attention that once you get used to it, you may not want to use other fm's. you get used to it and in the end reality hits you in the face, when you see basically nobody else around wants to touch such thing.

There is a thread about this in the forums. Issues:
1) keyboard shortcuts... everybody everywhere use ctrl+x to 'cut' a file (and then paste it somewhere else), not to delete it
2) assuming adults use puppy: hidden files hide the fun.
3) you're using linux, it's essential that you always see file permissions

there are many other issues, but where could be the correct place to put the rox config, including file associations and everything rox perhaps..

another unrelated issue is the rox switches everywhere... do you want to keep it that way or fix it?

**Comment by wdlkmpx** [comment]
I remember reading a log file where micko said the next slacko will have thunar or something. although i think it relies heavily on xfce. the only DE that has many generic apps, and works fine without a complete DE, with basically bits and pieces enough to be extremely fast and at the same time DE standards compliant, is the apps from lxde

**Comment by zigbert** [comment]
Our workflow is indeed personal. - I have never noticed it doesn't work with ctrl-c... :)
The only thing I miss is; unlike gtk-open/save dialog, Rox doesn't scroll to files beginning with 'T' when I press 'T'.
I am getting used to open files in the proper app, instead of using Rox as the launcher.

**Comment by wdlkmpx** [comment]
Well, the rox flaws are a deal-breaker for me. You might notice the insane amount of files i edit, all of this is easy having a file manager that:

1) jumps and selects a specific file/folder as you type
2) ability to copy and paste with the keyboard

The process of browsing files becomes quite easy, and with a file manager with tabs, volume icons and 2 panes, i just switch tab, copy and paste, browse, everything in a single window... and everything with the keyboard. I have an old keyboard with korean chars along the english ones, made in 1999. it's quite resistent compared to modern keyboards, it's like steel. Then i sit down 2 meters away from the monitor, and start browsing the woofce tree looking for something to edit.

When i'm in rox mode i become considerably dumb and tend to use a terminal window a lot. At least 1) and 2) should be implemented in rox, maybe by copying code from other file managers..

I think the rox-filer from jun7 might need some fixing for older systems, i fixed all the issues i found, but the icon view looks weird, the list view is OK.
