### ISSUE TITLE
Slacko - integrate *patches into *official

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#894]
This should have been done a long time ago.

Packages-slackware*-official should be updated with Packages-slackware*-patches so that the patches database can be deleted and everyone gets the latest package from PPM.

To implement this I will have to change the patches repo from `ftp://ftp.osuosl.org/pub/slackware/slackware64-14.2/patches/PACKAGES.TXT` to `http://salix.enialis.net/x86_64/slackware-14.2/patches/PACKAGES.TXT` so that dependency info is present.

This simple script does the substitution (almost pure shell - the stat -c %s stuff can be eliminated because we will do it in the right order!)

``` shell
#!/bin/bash

[ -z "$1" ] && exit
[ -z "$2" ] && exit
set -e
TMP=x$$

_fix() {
    cp $2 ${2}.orig # backup
    local f=0 # flag
    while read -r aline;do
        xline=${aline%%|*}
        while read -r bline;do
            while IFS='|' read -r a b c;do
                [ "${xline%-*}" == "$b" ] && f=1 && echo $bline >> $TMP && break
            done <<<${bline}
        done <$1
        [ $f -eq 1 ] || echo $aline >> $TMP
        f=0 # reset flag
    done <$2
    cat $TMP > $2
    rm $TMP
    #rm ${2}.orig
    #rm $1
}

a=`stat -c %s $1`
b=`stat -c %s $2`

if [ $a -lt $b ];then
    _fix $1 $2
else
    _fix $2 $1
fi
echo 'done!'
```

It takes 5 seconds on my Athlon X2, 4GB RAM. I can't speed it up any more but maybe someone could .. 

This will also eliminate the "Updates Manager" I have in slacko but could be replaced with an 'updates list' to inform the user that updates are available and install them with PPM; much simpler.

**Comment by wdlkmpx** [comment]
It takes 2:30 minutes in a very slow processor, but it doesn't matter as it's too old. i'll commit something in an hour or so, as i'll write something faster and change the repo url

**Comment by wdlkmpx** [comment]
i edited 0setup to implement this, according to what i think i understood. it integrates patches into official and clears the patches db file. no errors occur afterwards

**Comment by peabee** [comment]
Is this going to affect my LxPupSc builds?? 
I currently have:
salix.enialis.net|http://salix.enialis.net/i486/slackware-14.2/PACKAGES.TXT|Packages-slackware-14.2-official

and a patch to 3builddistro-z to ensure that only Packages-slackware-14.2-official is available in ppm....

**Comment by 01micko** [comment]
@peebee I would think no, but there is more to come and your patch should be obsolete.
