### ISSUE TITLE
How about using of these avatars for the github project (organization)

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#895]
From this thread
http://murga-linux.com/puppy/viewtopic.php?t=48880

![alienpup](https://cloud.githubusercontent.com/assets/10052849/19754954/9cd012f2-9bd7-11e6-9d14-7251e29359b4.png)
![cannibalpup](https://cloud.githubusercontent.com/assets/10052849/19754955/9cdb2dae-9bd7-11e6-8eb5-3ba71235725b.png)
![zombiepup](https://cloud.githubusercontent.com/assets/10052849/19754956/9d1595f2-9bd7-11e6-8471-28f1ed7f0899.png)

**Comment by 01micko** [comment]
Ok lol.. we should _all_ use them. :smile:

**Comment by wdlkmpx** [comment]
The new log is cool hehe
