### ISSUE TITLE
Puppy Remaster Script: Add UEFI CD boot support

### ISSUE THREAD

**Issue by rizalmartin** [puppylinux-woof-CE/woof-CE#898]
If the source CD has UEFI boot support then then output of puppy remaster script has UEFI boot support. too. See remasterpup script in X-Slacko Slim.

**Comment by wdlkmpx** [comment]
good idea, i'll take a look at the slacko slim iso, but it would be nice if you posted a direct link to the iso here. I'll see if i can port it to the current remasterpup2... because.. it has diverged a bit).. 30-50 lines deleted probably

**Comment by rizalmartin** [comment]
X-slacko slim download link: https://drive.google.com/open?id=0B2FRkttfZuG0RmwwUzZxa0RJaVE

It has very few modifications on its remasterpup script. Aside from remaster UEFI CD support its more small screen friendly

**Comment by wdlkmpx** [comment]
hmm  well i think commit https://github.com/puppylinux-woof-CE/woof-CE/commit/05de6ba22c42446973bb8fc088707d4b82a4376d fixes this, will take a look at the x-slacko iso to see the 'small screen friendly' stuff. soon..
