### ISSUE TITLE
ptheme and jwm 2.3.6

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#901]
i've used the woofce jwm stuff to build a puppy. but it doesn't look right

i've had defaulted dark touch, but it has orange which kills the purity and the true sense of a dark theme. i wonder what theme is the one used in slacko (with blue). so i changed it to 'bright mouse'.

now, it's not possible to change theme, i get this error: 'The window manager reports that something is wrong with your latest settings, and will roll back' ...

this can be fixed by commenting out that code in /usr/local/jwm_config/jwm_restart.

Now, the tray looks weird: http://www.01micko.com/wdlkmpx/capture13044.png

/root/.jwm/jwmrc-tray2

to fix this, in 'Tray autohide=....' i removed layout="horizontal" and halign="center", restarted jwm and now looks fine.

but if i change theme it looks bad again

**Comment by wdlkmpx** [comment]
in the screenshot provided there are no drive icons.. i was missing binary apps since i mindlessly replaced rootfs-skeleton to build this puppy. but i see the (fake) fd0 somehow is causing a long delay. drives appear after 20-30 seconds. this should happen under any circumstance. using a tahrpup kernel and busybox 1.21.. will update it to 1.25.1. i think for a wooce approach, some cleanup is recommended for all distro_pkgs_sepcs. i identified deprecated apps and can create a list for a sed command. maybe a the new busybox petbuild i'll create should be enforced and compiled for all woofce puppies.. the one compiled in precise can bed used for all i686 compat distros. and so on

**Comment by zigbert** [comment]
I think jwm_config should be renamed to jwm_config-2.3.2 to tell which jwm release it is built for. Next is to select which recent jwm we should support and make another jwm_config-2.x.x for this specific jwm.

Jwm is a great project, but the rc files is not backwards compatible, which gives issues with the configuration frontends.

@01micko @mavrothal 
I want a discussion of what to be the next jwm. I will then make a new jwm_config package.

**Comment by wdlkmpx** [comment]
it would probably have been better to let the jwm stuff as it was and let it fade into obscurity. i always use jwm but with a fixed minimal theme that i guess works fine in any recent jwm version. there is too much work to do with all this rox/jwm stuff that is just too much for 1 or 2 people.. i've been testing an hybrid  between some lxde apps + jwm + puppy volume monitor for about a year, been using in a 2003  machine with a celeron 2002 processor, so it's basically as fast as rox+jwm but with native support for .desktop files/icon themes and all the standard stuff i mentioned in the issues i open 2015.. if anybody is interesed..  https://s33.postimg.org/5it4g6htb/capture29126.jpg

**Comment by wdlkmpx** [comment]
as i also edited jwcomfig, my best advice is that you simplify it, make it less configurable, but safe for future versions, taking into account the fixes in the 1st comment.

the 1st ignores jwm warnings.. it works
the 2nd removes a couple settings that somehow are affecting the tray..

i usually also delete many lines i write. in fact i deleted my scripts i wrote because there were better solutions, this is my point of view and of course what i do with my own work...

**Comment by mavrothal** [comment]
> I want a discussion of what to be the next jwm. I will then make a new jwm_config package.

I’m not sure what is the question.
Which version of JWM  should puppy use? If yes here is a couple of cents.
Is not necessary to have the latest and greatest, unless there is a security issue or a killer feature.
Looking through the [change log] (http://joewing.net/projects/jwm/snapshots/ChangeLog) nothing jumps out.
Looking at the [upgrade log] (https://github.com/joewing/jwm/blob/master/README.upgrading ) however it appears that we just need a 2.3.0- 2.3.1 version for the config since newer versions revert the 2.3.2 changes.
So I would think that if we do not have a 2.3.0-1 version theme/config, stick with 2.3.2-5 versions till 2.4.x.
But I'm not building any puppies so I would think Mick, Phil (and the next JWM-based puppy-builder) are better qualified  to make suggestions on JMW versions

**Comment by wdlkmpx** [comment]
i think phil is out of the question. he's (or he was) building with a different jwmconfig, which i'd like to edit to put the same stuff: fix keybindings for the xorg evdev stuff and add some more. also change apps to defaultapps.. i really think duplication of efforts does not help, specially in a project that has one or 2 devs and then has none until the next one suddenly appears out of nowhere to do just whatever he thinks is right. nothing is planned. we're really not enough to do everything, or even qualified to do it the right way.

then that leads us to 3builddistro that poses another complication. i'll open a new issue "The future of WoofCE", to explain my point of view after spending months editing/simplifying/adding scripts and finally trying to resurrect some puppies..

**Comment by zigbert** [comment]
Hmmm...
I step up assigning for the task to upgrade jwm_config... the answer is pointing to another jwm configuration tool with the argumentation of avoiding duplication... Ok, I do something else.

**Comment by wdlkmpx** [comment]
I see there is a really tiny puppy gtk icon theme in another repo, when it's xz compressed. It must be a requirement just like the puppy fonts.

As part of the rationalising process. woofce must switch to gtk icon themes.. and integrate /usr/share/pixmaps/puppy into the puppy standard theme... and maybe change it to the default icon theme or 'hicolor', and make ROX use it (all the other file managers use the standard icon theme).

This is something that must be done by ALL woofce pups, it's not for a specific variant, because this requires changes in /usr/lib/gtkdialog/* 

I already opened and closed an issue about this, but the more i think in woofce and how to improve it, the more i get frustrated and revert to my old thinking about "standards"..

**Comment by wdlkmpx** [comment]
what i was thinking was... many apps usually show an X instead of the proper image.  when i install a complete icon theme all the missing images are displayed. Specially true for snes9x-gtk where i had to combine two or more icon themes to make some other icons appear.. like the joypad. This means that all possibilities about icons are already in the gtk theme specification or something like that. We just have to learn about it and make a complete or semi-complete standard tiny puppy gtk theme, if it's not done already..

**Comment by 01micko** [comment]
'Puppy Standard' attempts to be a full blown icon theme. Sure, there are some application and mime-types missing but it is a work in progress. Slacko uses it as the default theme for gtk and rox. All you have to do is work out the mime-type and make (or link an existing) icon. Similar for application icons (urxvt is one I need to work on). I'm attempting to make it gtk3 and QT compliant as well. 
![demo](https://cloud.githubusercontent.com/assets/1019119/20444994/12b6d29a-ae1f-11e6-8099-78a193f3d060.png)

**Comment by wdlkmpx** [comment]
Yes, i built a puppy including puppy_icon_theme, and everything looks better from the start. the changes i've been making at woof level also apply cleanly with the new apps i included. it's looking good.

**Comment by wdlkmpx** [comment]
by the way, i see some people don't like the wbar style for a second tray or a second tray at all.  Maybe the default option for this should be "Hidden when not in use". 

it would also be probably be a good idea to make it optional and i can confirm this command wipes it:
echo > /root/.jwm/jwmrc-tray1 

but i guess it's overriden when adjusting settings in ptheme or by changing theme, i'm not sure, have to test first.. but it's well designed though. the gui to design the trays is really pro. probably it needs more themes for people to appreciate it or something..

**Comment by mavrothal** [comment]
Happy to "see" you Mick. 
After my e-mail to your 01micko.com address bounced back I was wondering... 😟
