### ISSUE TITLE
DISTRO_PKGS_SPECS-* cleanup?

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#904]
- remove some deprecated/very outdated apps
- replace some apps with scripts and then remove them..
and so on.

to make the dbs look cleaner and smaller..

for example, this can be a replacement for minixcal, exactly the same behavior and gui

	#!/bin/sh
	
	osmobutton='--no-buttons'
	[ "`which osmo`" != "" ] && osmobutton='--button="Launch Osmo Calendar:0"'

	eval yad --undecorated --mouse --calendar --skip-taskbar $osmobutton

	[ $? -eq 0 ] && exec osmo --calendar

This can a replacement for gFontsel

	#!/bin/sh
	yad --font --title "gFontsel" --button="Close:0"

and so on. i know i can do this alone (for all the DISTRO_PKGS_SPECS* files), but this definitely is a ... operation. i know most compat distros are abandoned, easy task there. but that's not case with slacko (@01micko) and ubuntu (@mrfricks) ....

**Comment by wdlkmpx** [comment]
there is also a guess_fstype script that i wrote months ago:
https://github.com/puppylinux-woof-CE/woof-CE/commit/f568aa7a4bae2bfc2a48478e3d86aad0908315e4

there's also a busybox version that may need a tweak maybe. to be added.

also a waitmax script that uses busybox timeout and a busybox waitmax version as well, directly in the code.

busybox can be used to add puppy apps as well, the size will grow by 1-2k in most cases.

an interesting bash script to compare versions:
http://stackoverflow.com/questions/4023830/how-compare-two-strings-in-dot-separated-version-format-in-bash

**Comment by wdlkmpx** [comment]
busybox has also matured a lot in the last 2-3 years, that's why i think it should be used to replace some puppy apps that might have the same functionality, i tried to replicate elpsci, but there was something that was not right. i know they rejected many patches to improve it and add functionality, but that's what always happens everywhere, at least one of my patches was accepted hehe https://git.busybox.net/busybox/commit/?id=877dedb8251be47b3614a371434081ae9b7b358b

the same stuff happened with the lxde apps. i recently compiled all the apps i use and they have improved a  lot and still are tiny and simple... about 800kb gzipped including pcmanfm, lxtask, gpicview, lxterminal, lxrandr, lxinput, gmrun, pup-volume-monitor.. all of this working flawlessly for the first time in precise with my woofce build.

talking about lost stuff, i still have my custom drive_all that adds about 100 lines to the optical stuff that i want to include, but it uses yad, like 10-15 dialogs and there are a few png images, one liners. it looks cool the way it is, maybe replace the png images with svg ones but i'm not sure how to proceed..

**Comment by zigbert** [comment]
:-)
You have many interesting thoughts, and are doing a h*ll of a job here. I am excited to see the fulfilled rationalized branch in action. I do not agree on every step you take, but that is much less important. Thank you for you effort!

**Comment by wdlkmpx** [comment]
You will see it in a few days when i upload a test iso. Basically using all the changes i made to present a puppy with my customizations, of course keeping the woofce stuff.

Basically everything has been dealt with, but the puppy desktop environment is still rudimentary, but quite flexible at this point. puppyapps has code that can be used with my dbs to create a proper puppy DE stuff for rox and pcmanfm, but it has to be tested throughly. it creates mime associations for the defaultapps and more, about 300 i think. i'll add my puppyapps dbs soon

So far the only problem is still the hardcoded rox stuff everywhere.

rox is the 'defaultfilemanager', it has to be a symlink to it, and the real rox has to be renamed to roxfiler.. defaultfilemanager must default to 'roxfiler' or something like that.

at least that's what i think... this is to facilitate switching file managers and "desktops" with ease and without breaking anything..

**Comment by ninaholic** [comment]
I agree zigbert! Is there an ETA for when rationalize will be finalized and/or merged with testing, or will it always be an ongoing WIP? I think gyro still is working on the new initrd?
