### ISSUE TITLE
Build fails: woof-CE/initrd-progs/build.sh bad URL

### ISSUE THREAD

**Issue by gremplar** [puppylinux-woof-CE/woof-CE#912]
Hi, when attempting to build a new Puppy, the URL referenced in build.sh points to a non-existent file:

 PREBUILT_BINARIES="http://01micko.com/wdlkmpx/puppy/initrd_progs-20160725-static.tar.xz"

The file referenced in the last commit to build.sh ("initrd_progs-20160630-static.tar.xz") is still there... did the file get moved?  Is there another URL that should be used?

**Comment by wdlkmpx** [comment]
oops i don't have that file anymore.

the latest file is PREBUILT_BINARIES="http://01micko.com/wdlkmpx/woof-CE/initrd_progs-20161109-static.tar.xz"

which is a bit different .. rationalise branch (679 commits ahead)

**Comment by peabee** [comment]
I had a copy.....uploaded to:
[http://smokey01.com/peebee/downloads/woofce-rationalise/initrd_progs-20160725-static.tar.xz](http://smokey01.com/peebee/downloads/woofce-rationalise/initrd_progs-20160725-static.tar.xz)

**Comment by wdlkmpx** [comment]
thanks peebee.. the file has been restored.
