### ISSUE TITLE
problem with ibiblio not synching with mirrors

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#923]
To be noted - not our problem but affects Puppy....
Reported:

-------- Forwarded Message --------
Subject: 	Re: nluug not synching with ibiblio?
Date: 	Sat, 17 Dec 2016 11:45:58 +0100
From: 	ftpmirror-beheer@nluug.nl
Reply-To: 	ftpmirror-beheer@nluug.nl
To: 	PeeBee

Quoting PeeBee:
Hi PeeBee,

Ibiblio has problems.
rsync ibiblio.org::
rsync: failed to connect to ibiblio.org (2610:28:3090:3000:0:bad:cafe:23): Connection refused (111)
rsync: failed to connect to ibiblio.org (152.19.134.40): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

That's why we are behind.

Grtz.
Mike
> Hi Mike
>
> Just noticed that some recent updates (from 15-dec) on ibiblio > haven't appeared on nluug??
>
> Grateful if you could check and fix.
>
> Many thanks
> Peter (peebee)
> on behalf of the Puppy Linux Community
>
> e.g.
>
> distro.ibiblio.org/puppylinux/test/tahrpup/tahr64-6.0.5.3-uefi.iso
>
> distro.ibiblio.org/puppylinux/pet_packages-noarch/getflash-1.6c_161215.pet

**Comment by peabee** [comment]
Seems to be now updating again....

**Comment by peabee** [comment]
Updates to ibiblio on not appearing on any mirrors since 22-Dec.
I have filed a Question with Ibiblio Answers to try to get fixed....

**Comment by peabee** [comment]
ibiblio have replied.....I have sent reply to nluug.nl ..... BUT how do we contact the other mirror OPs??

A new answer to the question ibiblio not synching with mirrors was posted by cmpalmer on ibiblio Answers:

    Try switching from ibiblio.org to distro.ibiblio.org for that target.
    $ rsync distro.ibiblio.org::

    Welcome to the distro.ibiblio.org public rsync server.

    You may download any of our distributions by using the appropriate module name. For example:

    rsync -av distro.ibiblio.org::ubuntu/ /local/path/

    If you are mirroring part or all of our distributions, please consider subscribing to our mirror announcement list: http://lists.ibiblio.org/mailman/listinfo/ibiblio-mirrors

    If you have problems or questions, please visit http://www.ibiblio.org/help/

    Thanks!

    blackarch blackarch cdlinux cdlinux epidemic epidemic fatdog fatdog fedora-enchilada Fedora the whole enchilada fedora-epel Extra Packages for Enterprise Linux fedora-linux-development Fedora Linux Core Development fedora-linux-releases Fedora Linux Core fedora-linux-updates Fedora Linux Updates hanthana hanthana mageia mageia manjaro manjaro openmandriva openmandriva pclinuxos pclinuxos puppylinux puppylinux puppyrus puppyrus quirky quirky smeserver smeserver tinycorelinux tinycorelinux tinyme tinyme unity unity

**Comment by peabee** [comment]
Just in - fingers crossed.....
```
Answer by cmpalmer · 28 minutes ago
So it turns out there were two problems. One is that some indeterminate time in the past we switched to needing to use distro.ibiblio.org instead of ibiblio.org, and the second is that one of the backend rsync hosts was pulling the wrong puppet classes for its role. It was trying to be a fedora-only mirror server, but was in the load balancer as a distros host. I believe that both problems are now fixed. I hope folks will let me know if there are other problems (or if I'm wrong).
```

**Comment by peabee** [comment]
Closed

**Comment by peabee** [comment]
All the ibiblio mirrors have not synched since 5-feb-2017......

email received from cmpalmer:
 Hi peebee,

A new comment on a ibiblio not synching with mirrors was posted by cmpalmer on ibiblio Answers:

    TCP  mirrors.ibiblio.org:rsync wlc
      -> 172.27.205.17:rsync          Masq    1      0          0
      -> 172.27.205.18:rsync          Masq    1      0          0

    The view from our load balancer for this service shows the backend hosts up (and the backend hosts look fine), but zero clients. I think something is wrong on the load balancer and will be forcing a manual failover shortly.

**Comment by peabee** [comment]
This email received from ibiblio - not sure how to respond - have forwarded it to @01micko for his attention.....

Hi @peebee, It looks like Barry Kauler decommissioned Puppy Linux on Jan 3:

http://barryk.org/bkauler/

Barry push-mirrors to ibiblio, so if the Puppy Community is taking over, I'm happy to point ibiblio's mirror to a central rsync server? (or if a member of the Puppy team would like an ibiblio account to continue push-mirroring to us, we'll be happy to create one).

Thank you!

Donald

**Comment by peabee** [comment]
Hi peebee,

A new answer to the question ibiblio not synching with mirrors was posted by DonSizemore on ibiblio Answers:

    ugh, puppet ate rsyncd.conf again. there was a foreman upgrade yesterday, but a backout probably reverted this fix. i'm a mere volunteer these days so i'll let @cmpalmer sort it, and probably send him chocolates.

    i do see that we're your primary site so we'll hop on that. any word on an account you'd like to use for uploading to us (or any host you'd like us to rsync from)?

    thank you,

    donald

**Comment by mavrothal** [comment]
Reopen as needed

**Comment by peabee** [comment]
There are still problems....
If you look at the mirrors linked on http://puppylinux.com/download.html
and look at the dates in directory test/xenialpup/
you will see that whilst nluug is in synch
 UoC, AARNET and Internode mirrors are way behind.....

**Comment by mavrothal** [comment]
Maybe, but how is this a woof issue. 
Both ibiblio and the mirror servers are beyond our control.

**Comment by peabee** [comment]
DonSizemore at ibiblio reports he has fixed - see
https://answers.ibiblio.org/questions/1910/ibiblio-not-synching-with-mirrors.html

**Comment by peabee** [comment]
All mirrors on website are now in synch.....
