### ISSUE TITLE
Record changes to Packages-puppy-noarch-official on ibiblio

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#925]
This issue should be used to record changes made to Packages-puppy-noarch-official on ibiblio.

**Comment by peabee** [comment]
22-dec-2016: getflash-1.6.1.pet uploaded; http://distro.ibiblio.org/puppylinux/Packages-puppy-noarch-official updated

**Comment by peabee** [comment]
27-dec-2016: PupControl-3.1.1.pet uploaded; http://distro.ibiblio.org/puppylinux/Packages-puppy-noarch-official updated

**Comment by wdlkmpx** [comment]
there is also baconrecorder by don5707... i saw that one in tahr or xenial. 

i'm creating a few firmware pet packages (taken from the 'kernel-skeleton' dir).. i guess the forum members also have suggestions.. @rserwin1 , etc.

maybe you should create a forum topic.. something like... ibiblio: Community Projects to update or upload

Then write a short message to invite the puppy devs and users to post updated noarch packages or something, so you don't to have hunt down packages. and ask flash to make that topic sticky. they will see you have ibiblio access, but it's not like they'll try to steal that access from you ...

**Comment by peabee** [comment]
30-dec-2016: PupMenu-5.1.1.pet uploaded; http://distro.ibiblio.org/puppylinux/Packages-puppy-noarch-official updated

**Comment by mrfricks** [comment]
fixed 'media-skip-forward.svg' in puppy_standard_icons (it was pointing backwards)

**Comment by peabee** [comment]
3-feb-2017: Pup-SysInfo-2.6.6.pet uploaded; http://distro.ibiblio.org/puppylinux/Packages-puppy-noarch-official updated

**Comment by peabee** [comment]
5-feb-2017: getflash-1.7.pet uploaded; http://distro.ibiblio.org/puppylinux/Packages-puppy-noarch-official updated

**Comment by rserwin1** [comment]
Note that I had to re-upload the package after download #3, to fix a 
minor bug.  Assuming you took one of the first 3 downloads, please 
consider downloading it again and replacing the version now at ibiblio.

PB wrote:

**Comment by peabee** [comment]
28-mar-2017: peasywifi-4.2.pet uploaded; http://distro.ibiblio.org/puppylinux/Packages-puppy-noarch-official updated

**Comment by mrfricks** [comment]
updated puppy_standard_icons (kept same name)

ListDD removed 'restart xserver' message from pinstall (kept same name)

**Comment by 01micko** [comment]
Ok, I created `puppy_icon_theme` (with @zigbert and @technosaurus ) and there is the git repo and a petbuild to support it but what is exactly the difference between it and `puppy_standard_icons`?

I am rather curious ...

**Comment by mrfricks** [comment]
hi 01micko,

i made that. pet of your icons when you first posted about them on the puppy blog last year.
initially they were in the xenialpup repo , but i moved them to noarch so others could use them.

i did alter 3 icons....found a round .svg for isos and added some colour to .debs & rpms to make them easily distinguishable.

i think your icons should be in rootfs-packages

**Comment by 01micko** [comment]
Thanks @mrfricks 
On my test install I have already made different coloured icons for `.deb` and `.rpm` -  to be committed soon. Not sure the the 'round' icon is suitable for the mimetype of an `.iso` image but I'm open to ideas, bearing in mind that the 'round' icon may suit the 'device' better than the 'mime'.

**Comment by mrfricks** [comment]
yes i know the iso icon i put in doesn't really match the icon set, but i think a round icon makes identification much easier/quicker.

the cd icon in /usr/share/pixmaps/puppy might have been more fitting.

**Comment by 01micko** [comment]
> yes i know the iso icon i put in doesn't really match the icon set, but i think a round icon makes identification much easier/quicker.

Horses for courses.

Ok, but there is a conflict. Even though the original project is licenced "CC0" those icons shouldn't really be installed in "Puppy Standard". Your package conflicts with the original (which is also in noarch). Call it "Puppy Sandard 1" or whatever you like. Or rename the package to `puppy_icon_theme-(whatever version)_patched` and provide a patch via a petbuild or whatever, at least somewhere. You may think I'm being pedantic. Well I probably am, but not to be mean, but just to differentiate. :tongue: 

As an alternative, icons can be overwritten with a different theme, but depending on the parent theme. :wink: . The different theme may only include as few icons as necessary.

**Comment by mrfricks** [comment]
ok no probs.... I'll keep the .pet in noarch pristine.

**Comment by 01micko** [comment]
Don't get me wrong. If you want to alter it, do so. But also change the name of the icon theme as not to cause conflict. I'll build and upload the latest `puppy_icon_theme` soon.

Perhaps if you want changes a pull request against https://github.com/puppylinux-woof-CE/puppy_icon_theme would be the best place to start :-)

**Comment by 01micko** [comment]
Just uploaded `puppy_icon_theme-0.8-noarch_all.pet` to ibiblio and updated Packages-puppy-noarch-official`. @mrfricks you talked me into it... I changed the mime icon for an iso image :stuck_out_tongue: 

The source is uploaded to github too. Anyone can build it by cloning the repo or downloading the 0.8 tar/zip file. Petbuild will be updated soon.

Note that I added a pinstall.sh to update the icon cache because it isn't good practice to ship cache. This only works in a running system, not woof. I think we need to add code to rc.update to detect other themes than hicolor :smiley: 

Here are some representations of some of the new icons (can't upload svg to github so are png)


![application-kernel](https://cloud.githubusercontent.com/assets/1019119/24583944/e36be400-179e-11e7-9eb0-ecf87b56a2f2.png) 
![application-x-cd-image](https://cloud.githubusercontent.com/assets/1019119/24583948/ec553422-179e-11e7-9420-a6d58fc54f00.png) 
![application-x-deb](https://cloud.githubusercontent.com/assets/1019119/24583952/f3f72ee2-179e-11e7-85c5-28f5e850b78a.png) 
![application-x-rpm](https://cloud.githubusercontent.com/assets/1019119/24583955/f9896b68-179e-11e7-92dd-9b1923251ee3.png)

Note: the penguin is a completely new one for the mime of the kernel. 

For it to show up the `/usr/share/mime/packages/puppy.xml` needs editing:

Add these lines:

```
  <mime-type type="application/kernel">
    <comment>linux kernel</comment>
    <glob pattern="vmlinuz*"/>
  </mime-type>
  
  <mime-type type="application/kernel">
    <comment>linux kernel</comment>
    <glob pattern="bzImage*"/>
  </mime-type>
  

```
I did it just under the `<mime-type type="application/pet">` block
 then you need to run: `update-mime-database /usr/share/mime`

Here's how it looks:
![build](https://cloud.githubusercontent.com/assets/1019119/24583978/efa31350-179f-11e7-8c9b-552fa6d9ba62.png)

Enjoy!

**Comment by peabee** [comment]
peasydisc-3.9.pet

**Comment by 01micko** [comment]
```
f2fs-usb-installer-0.24-noarch|f2fs-usb-installer|0.24-noarch||Setup|280K||f2fs-usb-installer-0.24-noarch.pet|+f2fs-tools|F2FS Installer - Flash Drives||||
updates_notice-0.1|updates_notice|0.1||Setup|32K||updates_notice-0.1.pet||Update notices - Slackware bugfixes|slackware|||
```

The first is the bugfixed version via @gyrog and the second is a replacement for the slacko updates manager now that `patches` repo gets merged into the main repo. 

Why noarch? Because the latter is used by 32 and 64 slackoes (and if there were a slacko-arm that too). The f2fs installer is completely distro independent; so long as the kernel is enabled and f2fs-tools is installed.

**Comment by 01micko** [comment]
```
puppy_flat_theme-0.3-noarch_all|puppy_flat_theme|0.3-noarch_all||BuildingBlock|7312||puppy_flat_theme-0.3-noarch_all.pet||A light weight flat GTK icon theme||||
puppy_flat_theme_DEV-0.3-noarch_all|puppy_flat_theme_DEV|0.3-noarch_all||BuildingBlock|20||puppy_flat_theme_DEV-0.3-noarch_all.pet|+puppy_flat_theme|puppy_flat_theme development||||
```

New flatter icon theme ... see https://github.com/puppylinux-woof-CE/puppy_flat_theme

It can be used the same as "Puppy Standard" as ROX and/or GTK theme.

**Comment by 01micko** [comment]
puppy_flat_theme-0.4-noarch_all
puppy_flat_theme_DEV-0.4-noarch_all

just a version bump/bugfix

**Comment by 01micko** [comment]
add: `SaveFolderBackup-1.2|SaveFolderBackup|1.2||Utility|44K||SaveFolderBackup-1.2.pet|+lzop|Save folder backup and restore||||`
by rcrsn51
update: `sfs_manager-0.14|sfs_manager|0.14||Setup|60K||sfs_manager-0.14.pet||download and install sfs files||||`

**Comment by 01micko** [comment]
updated: `puppy_flat_theme`
added: `get_browser`

`get_browser` package is a gtkdialog gui to download and install (as pet or sfs) either Chrome, Vivaldi or Opera latest versions. The backend is entirely based on @ruario 's scripts for `latest-chrome.sh`,`latest-opera.sh` and `install-vivaldi.sh` so thank him, not me. (well me for the bugs :tongue: )

**Comment by 01micko** [comment]
```
#upgraded
get_browser-0.4|get_browser|0.4||Setup|100K||get_browser-0.4.pet|+libarchive|Download Chrome, Vivaldi or Opera||||
#added
firmware_acx-170511|firmware_acx|170511||BuildingBlock|432||firmware_acx-170511.pet||firmware||||
firmware_atmel-170511|firmware_atmel|170511||BuildingBlock|836||firmware_atmel-170511.pet||firmware||||
firmware_dvd_usb-170511|firmware_dvd_usb|170511||BuildingBlock|256||firmware_dvd_usb-170511.pet||firmware||||
firmware_hso-170511|firmware_hso|170511||BuildingBlock|32||firmware_hso-170511.pet||firmware||||
firmware_ipw-170511|firmware_ipw|170511||BuildingBlock|1208||firmware_ipw-170511.pet||firmware||||
firmware_ipwireless-170511|firmware_ipwireless|170511||BuildingBlock|32||firmware_ipwireless-170511.pet||firmware||||
firmware_nouveau-170511|firmware_nouveau|170511||BuildingBlock|508K||firmware_nouveau-170511.pet||firmware||||
firmware_nozomi-170511|firmware_nozomi|170511||BuildingBlock|32||firmware_nozomi-170511.pet||firmware||||
firmware_prism54-170511|firmware_prism54|170511||BuildingBlock|456||firmware_prism54-170511.pet||firmware||||
firmware_usbserial-170511|firmware_usbserial|170511||BuildingBlock|32||firmware_usbserial-170511.pet||firmware||||
firmware_zd1201-170511|firmware_zd1201|170511||BuildingBlock|164K||firmware_zd1201-170511.pet||firmware||||
```

**Comment by 01micko** [comment]
added:
`inxi-2.3.8` (exe, dev, doc)

**Comment by peabee** [comment]
frisbee-1.4.4 (for availability by PPM download on old systems only)

**Comment by peabee** [comment]
pupmd5sum-1.3-1.pet - adds sha-256 and sha-512

**Comment by 01micko** [comment]
sfs_manager-0.17.pet (slacko)

**Comment by peabee** [comment]
pupmd5sum-1.4.pet

**Comment by 01micko** [comment]
add `mtpaint_hanbook-3.40-noarch.pet`

NB: `mtpaint` for slackoes is reuploaded with a minor patch to suggest 'look in Package manager' for mtpaint_handbook. (version number *is not* changed - @peabee )

**Comment by peabee** [comment]
Pup-SysInfo-2.7.pet

**Comment by 01micko** [comment]
haha.. @peabee was thinking to do it shortly... Pup-Kview needs doing too.

**Comment by peabee** [comment]
Pup-Kview-1.3.5.pet  ;-)

**Comment by 01micko** [comment]
update
`get_browser-0.5.pet`

This has been updated to work in xenial64 without the devx. So far tested chrome and vivaldi, but no reason opera wont work. Also has a warning to install GTK+3 for chrome.

add
`mtpaint_help-3.40-noarch.pet`

As opposed to the mtpaint_handbook pet (full local document) this one is just a stub linking to the online version.

**Comment by peabee** [comment]
peasyport-2.2.pet

**Comment by peabee** [comment]
getflash-1.7-1.pet

YASSM-3.0.pet

**Comment by peabee** [comment]
peasywifi-4.3

**Comment by peabee** [comment]
peasyport-2.3

**Comment by peabee** [comment]
Pup-SysInfo-2.7.2

**Comment by peabee** [comment]
YASSM-4.1

**Comment by peabee** [comment]
PupMenu-6.0

**Comment by peabee** [comment]
pfind-6.3 - in woof-ce and ibiblio repository so scope for 2 versions to be dissimilar....

**Comment by peabee** [comment]
pupmd5sum-1.5

**Comment by peabee** [comment]
Pup-SysInfo-2.7.3

**Comment by peabee** [comment]
wcpufreq-0.8.2
same patch for kernel 4.13 as Pup-SysInfo-2.7.3

**Comment by peabee** [comment]
PupClockset-2.6
and
PupMenu-6.1

**Comment by peabee** [comment]
pupmd5sum-1.6.pet

**Comment by peabee** [comment]
JWMDesk-2.4.1.pet

ListDD-2.1.pet

**Comment by peabee** [comment]
PupControl-3.2.1.pet

**Comment by peabee** [comment]
JWMDesk-2.4.2.pet

**Comment by ninaholic** [comment]
some updated peasy apps:
[peasyapps-Oct20_2017.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/1403379/peasyapps-Oct20_2017.zip)

pet.spec entries
```
peasydiff-1.4|peasydiff|1.4||Setup|44K||peasydiff-1.4.pet||compare two files/folders||||
peasydisc-4.1|peasydisc|4.1||Multimedia|80K||peasydisc-4.1.pet||PeasyDisc||||
peasyglue-2.0|peasyglue|2.0||Graphic|68K||peasyglue-2.0.pet||Image joiner||||
peasypdf-4.2|peasypdf|4.2||Document|56K||peasypdf-4.2.pet||Manipulate PDF documents||||
peasyscale-2.0|peasyscale|2.0||Graphic|68K||peasyscale-2.0.pet||graphic resizer|slackware|14.0||
peasyscan-2.12|peasyscan|2.12||Graphic|172K||peasyscan-2.12.pet||PeasyScan simple image scanner|slackware|14.0||
peasywifi-4.5|peasywifi|4.5||Network|136K||peasywifi-4.5.pet||Reliable WiFi connection manager|slackware|14.0||
```
updated noarch and slacko14 files are in zip so that it picks that latest. all pets working on test

**Comment by peabee** [comment]
Updated peasy apps as above in noarch
(no peasy apps in slacko14)

**Comment by peabee** [comment]
pmusic_PLUGIN_tray both 32-bit and 64-bit copied out of Slacko-14, rebuilt with different names and then added to Packages-puppy-common-official so that they can be used in non-Slacko builds....
pmusic_PLUGIN32_tray-0.5|pmusic_PLUGIN32_tray|0.5||BuildingBlock|32K||pmusic_PLUGIN32_tray-0.5.pet||Tray plugin for pmusic - 32bit||||
pmusic_PLUGIN64_tray-0.6|pmusic_PLUGIN64_tray|0.6||BuildingBlock|36K||pmusic_PLUGIN64_tray-0.6.pet||Tray plugin for pmusic - 64bit||||

**Comment by peabee** [comment]
get_libreoffice-0.41.pet

**Comment by peabee** [comment]
uextract-3.32.pet (probably by 666philb...)

**Comment by peabee** [comment]
ffconvert-1.4.3.pet

fixes a nasty bug found by @radky where files and directories could be unintentionally deleted after running ffconvert

**Comment by peabee** [comment]
pclock-0.8.2.pet

**Comment by zigbert** [comment]
pClock is found in woof-packages

**Comment by peabee** [comment]
shared-mime-info.....
noarch has a version dated April-2012
slacko14.2, slacko6414.2, xenial, tahr and tahr64 all have later versions
xenial64 for some reason does not have a later version but is probably using the tahr64 version? I cannot determine what dpup is using.
The noarch version is confusing the build process and is being selected erroneously.
I propose to delete the entry for noarch versions from Packages-puppy-noarch-official

**Comment by ninaholic** [comment]
@peabee: In dpup and 14.0, when noarch entry is removed, shared-mime-info just falls back to even older puppy-common version, and it still grabbed newer 1.2 correctly for me in Slacko 6.9.9.9 with the older noarch list, so I don't think this is good solution and perhaps a bigger issue in your slacko-current order of repositories (if that's where you noticed the problem) that could be fixed there somehow specifically instead?

**Comment by wdlkmpx** [comment]
dpup is now using the compat distro shared-mime-info (1.8) (but i see 1.3 in pkgconfig)

however you can upload this to the common repo and replace the entry in the pkg db:
[shared-mime-info-1.9-i686_wary5.pet_fake.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/1767442/shared-mime-info-1.9-i686_wary5.pet_fake.gz)
[shared-mime-info_DEV-1.9-i686_wary5.pet_fake.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/1767443/shared-mime-info_DEV-1.9-i686_wary5.pet_fake.gz)

shared-mime-info-1.9-i686_wary5|shared-mime-info|1.9-i686_wary5||BuildingBlock|396K||shared-mime-info-1.9-i686_wary5.pet||no description provided|puppy|wary5||
shared-mime-info_DEV-1.9-i686_wary5|shared-mime-info_DEV|1.9-i686_wary5||BuildingBlock|20K||shared-mime-info_DEV-1.9-i686_wary5.pet||no description provided|puppy|wary5||

it was a huge pain to compile it, not editing the petbuilds stuff to support wary... but using it without my jwm key bindings, xorg mousekeys and pcmanfm is just painful and miserable experience in puppy. Pain & misery.

**Comment by wdlkmpx** [comment]
Hmm although that pet pkg is meant for recent woofce builds. It might cause trouble in other woof build systems, as update-mime-datase is not executed in (very) old releases.

All the Puppy-packages dbs should be only in the git repo and the ibiblio repos should only store .pet pkgs.. peebee is carrying a burden that mavrothal should be carrying.. the task to manage the common and noarch pet repos.

And a new thread in the forum is needed so people can inform about new releases of noarch packages and even provide the pkgs themselves.. that way rootfs-packages can now finally cease to exist...

**Comment by peabee** [comment]
Sorry everybody - completely losing the plot here....
- why is something called wary5 going into "common"??
- why do some builds have compat-distro specific .pets and some rely on noarch??
- why not do what 01micko has done and rely on the package from the compat-distro? there is after all a package-template for shared-mime-info.....??
- there is a binary in shared-mime-info - /usr/bin/update-mime-database - so it can't go into noarch??
Confused here!!

**Comment by wdlkmpx** [comment]
Because there is an order specified in DISTRO_PET_REPOS, slacko 6.9
has a shared-mime-info pet package that is picked first. Other pups
don't have specific a pet  package one of the fallbacks is selected
from common or noarch, tahrpup and xenialpup also list wary5 as a
fallback. It should be removed the from the fallback list.

shared-mime-info can be split into 2 packages actually

freedesktop mimedb - noarch
update-mime-datase - arch dependent.

However i can provide another fixed pet pkg with all the mimedb stuff
generated including puppy.xml stuff. So that there is no breakage in
any anyway anywhere. Ignoring the fact the should only worry about
woofce and nothing else.

A way to put an end to the shared-mime-info chaos is by adding the
latest zfreedeskop.org.xml and zpuppy.xml. That way 3builddistro
overrides both making a consistent base across all the supported
pups... there is the pmime script that can generate loads of file
associations for rox and other filemanagers.

The only way to bring some order into this is by following what i said
earlier, it describes how to do it in a very concise way

**Comment by wdlkmpx** [comment]
I wrote a long message from gmail with too many typos but i don't the message to edit here.

But it can be done, everything can be done, the problem is the changes in the pkgs specs can be reverted anytime, but i'll do it anyway

**Comment by peabee** [comment]
The package-template for shared-mime-info does not work for slackware - the generated image is different to the slacko .pet contents in a number of ways.....in particular /usr/bin/update-mime-database in not transferred neither is the contents of /usr/share/mime....

I think the package-template should be fixed and all builds should use the shared-mime-info from their compat-distro and there should be no .pets.....

**Comment by wdlkmpx** [comment]
All the pups now use the compat distro shared-mime-info. Which in all
cases is a newer version the pet pkgs. It's amazing how slackware
keeps updating the whole 14.x series..

You've got to be kidding, you must be still using the deleted
shared-mime-info pkg template... DELETED shared-mime-info package.

I just tested, this is ok.. it's enough for 3builddistro or a very
recent rc.update.. update-mime-database is always triggered if
mime.cache is missing.

shared-mime-info
├── usr
│   ├── bin
│   │   └── update-mime-database
│   └── share
│       └── mime
│           └── packages
│               └── freedesktop.org.xml
└── var
    └── log
        └── setup
            └── setup.07.update-mime-database

shared-mime-info_DEV/
└── usr
    └── lib
        └── pkgconfig
            └── shared-mime-info.pc

**Comment by peabee** [comment]
I've now caught up with what you've done - major changes like this need to be highlighted in some way!
I'm presuming that with these changes all shared-mime-info .pets can be removed from the ibiblio repos....??

**Comment by wdlkmpx** [comment]
Micko once said that nothing should be removed. so i think the answer is no.

When you want to fix something, you upload a pet pkg and then edit the
corresponding puppy-packages db to reference only that pet pkg. Or
maybe that's what you're trying to say..

I think all these packages should only be used to provide
update-mime-database... 3builddistro could override the
freedesktop.org.xml and puppy.xml files, that's easy to do, but the
mimetype stuff keeps evolving, and pmime can handle the file
associations with its db. But then maintaining something is the key..

**Comment by wdlkmpx** [comment]
peebee i fixed the PACKAGELISTS_PET_ORDER  in the upups
https://github.com/puppylinux-woof-CE/woof-CE/commit/cd75ed7f64a04cd4f5759400defd813dad66f4fd

wary5 should not a fallback, not even precise. everything should start
with tahrpup. but this requires some work and testing. i guess no one
can do that now..

i hope you don't think artful will stay there after bionic is released..

**Comment by wdlkmpx** [comment]
> I've now caught up with what you've done - major changes like this need to be highlighted in some way!

I always add major changes, i should be writing like a madman about all those changes, but the truth is i don't have enough time to even apply the code changes i want, even though i already made them in my mind. And i don't want to spread some badly written english

The fact that i have to keep adding disrupting changes all the time speaks a lot about how bad everything was, it's still bad, but it's s.l.o.w.l.y getting to a point that it can be relatively reasonable. But i have to keep deleting many files.

Those who have their own build configs might have trouble identifying what's wrong when their build fails or something is missing. But the only way to improve things is by applying global changes that affect everything. And it feels more like a masochist adventure rather than a fun experience, probably it has to with something my brother said, trying to prove him wrong. prove him that puppy can be somewhat "normal". But doing this is something i only wish to my worst enemy..

So you might want pick a woofce distro compat version, and store your lxpup pkg specs in the git repo and use it to produce your official derivative in the standard woof process... because if you don't.. it will happen in dpup anyway although a bit differently

**Comment by peabee** [comment]
BUILD_FROM_WOOF='testing;cbb38a7e;2018-03-11 20:41:49 +0800'
:shared-mime-info:|compat|Packages-ubuntu-bionic-main|shared-mime-info_1.9-2|shared-mime-info_1.9-2_i386.deb
Some old .isos and more recent Dpup isos have wrong type - model/stl.x-binary giving wrong icon and no open action.
Can be cured by installing shared-mime-info-0.70-6.pet from ibiblio/noarch
but not clear why this fixes!
See discussion:
http://murga-linux.com/puppy/viewtopic.php?p=985211#985211

**Comment by wdlkmpx** [comment]
I'm using shared-mime-info 1.9.. and i don't see any issues in
pcmanfm. I downloaded a wary5.5 iso again just to test this. I can
mount and unmount isos by clicking on them. Good.

I open a rox window just in case and i see all the .iso files with a
question mark.. the same issue pb is experimenting in bionic pup.

What does this mean? I don't know but i certainly can't stand this.
I'm going nuts and will boot a tiny linux in a floppy.

Some time ago, I deleted all the rox stuff i had, including scripts
dealing with rox stuff, except one, one that is already in woofce.

Seriously, rox is crap. It's torturing many innocent souls in the name
of BK's insane legacy.

**Comment by woodenshoe-wi** [comment]
I think the problem is shared-mime-info-1.9
http://murga-linux.com/puppy/viewtopic.php?p=985213&sid=c137e7b5b301f0c3a306b0babae494ea#985213

Installing the old pet reverts the mime databases back to an old working state.

**Comment by woodenshoe-wi** [comment]
Try these,

https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/0pets_out/x86/common32/shared-mime-info-1.2-i686_common32.pet

https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/0pets_out/x86_64/common64/shared-mime-info-1.2-x86_64_common64.pet

**Comment by woodenshoe-wi** [comment]
I think I found the magic definition that was causing the problem and patched it in the petbuild.

Try these,

https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/0pets_out/x86/common32/shared-mime-info-1.9-i686_common32.pet

https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/0pets_out/x86_64/common64/shared-mime-info-1.9-x86_64_common64.pet

**Comment by peabee** [comment]
Confirmed - fixes when loaded onto ubbpup....
What happens now? Do we go back to using this .pet instead of the compat-distros shared-mime-info
or in addition to....
or is this .pet going to become part of woof-ce???
I'm not clear on the strategy / implementation :-(

**Comment by woodenshoe-wi** [comment]
They should be replacements for the compat-distros shared-mime-info, I compiled them against the libs from slacko 14.0 so hopefully they will work in any pup as long as it is the right 32bit/64bit pet.

I was thinking that there could be new common32 and common64 repos at ibiblio for pets compiled this way.  I think more things can be compiled against older libs than compiled statically.

**Comment by wdlkmpx** [comment]
Those new repos can be in a github repo as a part of
https://github.com/puppylinux-woof-CE/  that way there can't be delays
or barriers when updating stuff, i'll see what i can do. And peebee
should have commit access... access should be based on activity and
skills, both are equally important.. but activity is more important.

**Comment by woodenshoe-wi** [comment]
That I disagree with.

The reason I put the files on gitlab instead of GitHub is that the large file support at GitHub isn't worth using.  There is a bandwidth quota at GitHub.

Without using large file support (LFS) the pets will collect in the git history and the repo will grow too large.

**Comment by wdlkmpx** [comment]
A git repo can be restarted by removing the .git directory and adding
the 1st commit again. That means only those who can cope with that can
update it. I don't use gitlab so i'm not sure what to do.

Another option is: patch freedesktop.xml through the package-template

I just created a forum
http://wmsgs.freeforums.net/

**Comment by woodenshoe-wi** [comment]
I'm using gitlab as an alternative to Dropbox for sharing files, but I don't see it as a replacement for ibiblio.  Also remember that ibiblio is mirrored by several other sites.

**Comment by wdlkmpx** [comment]
This is the syntax a pet repo must follow:

<site>/puppylinux/pet_packages-<petrepo>

The db file:
Packages-puppy-<petrepo>-official

<petrepo>: common32, common64, commonx86 (static 32bit)

It can be hosted on github, gitlab, ibiblio, etc. But it must be
easily updatable

**Comment by peabee** [comment]
Hi both - this issue has got a bit off-track.......probably my fault......maybe it would be better to use https://github.com/puppylinux-woof-CE/woof-CE/issues/1133 ??

**Comment by ninaholic** [comment]
Hi,

There is a "usb-modeswitch-data-20170806-noarch_noarch.pet" that is 130 bytes and seems to be empty uploaded yesterday (woof-CE pulls this one). Is this right?

http://distro.ibiblio.org/puppylinux/pet_packages-noarch/usb-modeswitch-data-20170806-noarch_noarch.pet

**Comment by ninaholic** [comment]
![screenshot](https://user-images.githubusercontent.com/5408521/38061106-d83e9fb2-32bb-11e8-9d7d-3335be5a2cce.png)

**Comment by ninaholic** [comment]
![screenshot 1](https://user-images.githubusercontent.com/5408521/38062022-dc56a690-32bf-11e8-8ea2-a34445d2f077.png)

**Comment by woodenshoe-wi** [comment]
@peabee did you clone my repo instead of downloading though the web interface?

If you want to clone my gitlab repo you have to have git-lfs installed.

**Comment by woodenshoe-wi** [comment]
This is a git-lfs pointer file.  You get them when you clone a git-lfs repo (which my gitlab repo is) without having git-lfs installed.  The pets in commom32 and common64 are probably pointer files too, because they look too small to be the real pets.

If you want to clone my gitlab repo instead of using the web interface see
https://help.github.com/articles/installing-git-large-file-storage/#platform-linux

**Comment by wdlkmpx** [comment]
petbuilds-out.tar.xz  (3.5MB - 3.453 MB)
http://s000.tinyupload.com/index.php?file_id=24776416383939497025

**Comment by peabee** [comment]
I downloaded from the web interface......

**Comment by peabee** [comment]
ibiblio updated from the above link

**Comment by peabee** [comment]
This issue can now be closed as all the package db's have been transferred to github for new woof-ce builds.

**Comment by peabee** [comment]
acpid-busibox-4.pet reuploaded same name with missing " added to last line - delete any existing old version to force a download

**Comment by peabee** [comment]
Shinobar's new grub4dos-0.4.4.v1.9.4
http://murga-linux.com/puppy/viewtopic.php?p=1004943#1004943
should be uploaded???
