### ISSUE TITLE
findpkgs and _DEV pets

### ISSUE THREAD

**Issue by woodenshoe-wi** [puppylinux-woof-CE/woof-CE#933]
I'm working on getting a build based on Raspbian stretch working and wanted to reuse the gtkdialog and jwmxdgmenu pets I compiled in jessie.

I figured out how to add support for FALLBACKS_COMPAT_VERSIONS to the DISTRO_PET_REPOS file for stretch, and findpkgs would find the jwmxdgmenu pet fine.

The problem was with gtkdialog, findpkgs would only find the gtkdialog_DEV pet.

I tracked the problem down to the part of findpkgs that finds the _DEV only pets.  Because the gtkdialog_DEV pet has a blank DISTRO_BINARY_COMPAT and DISTRO_COMPAT_VERSION, `|||` it was being found before the main gtkdialog pet, `|raspbian|jessie|` and findpkgs would stop searching.

Commit ab0324b fixes it for me, but I think this could affect any build that use pets not compiled in the exact same distro.

I don't know if this needs testing by other builders, so I'm raising this as an issue.  If you want me to issue a pull request I can do that too, but this seemed like a significant change to an important part of woof-CE and I don't want to break anything.

**Comment by wdlkmpx** [comment]
gtkdialog-0.8.4-armv6l_1|gtkdialog|0.8.4-armv6l_1||BuildingBlock|256||gtkdialog-0.8.4-armv6l_1.pet|+gtk+2|gtkialog is a small utility for fast and easy GUI building|raspbian|jessie||
gtkdialog_DEV-0.8.4-armv6l_1|gtkdialog_DEV|0.8.4-armv6l_1||BuildingBlock|20||gtkdialog_DEV-0.8.4-armv6l_1.pet|+gtkdialog|gtkdialog development||||

The best way to deal with this is by fixing the pkg itself:

armv6l_1||BuildingBlock|20||gtkdialog_DEV-0.8.4-armv6l_1.pet|+gtkdialog|gtkdialog development|raspbian|jessie||

It looks like there is a bug in dir2pet or something... it creates a faulty pet.specs for the _DEV pkg.. 

gtkdialog-0.8.4-armv6l_1|gtkdialog|0.8.4-armv6l_1||BuildingBlock|260||gtkdialog-0.8.4-armv6l_1.pet||No description provided|debian|stretch||
gtkdialog_DEV-0.8.4-armv6l_1|gtkdialog_DEV|0.8.4-armv6l_1||BuildingBlock|20||gtkdialog_DEV-0.8.4-armv6l_1.pet||No description provided||||

**Comment by wdlkmpx** [comment]
now dir2pet creates proper pet.specs for _DEV pkgs
gtkdialog_DEV-0.8.4-armv6l_1|gtkdialog_DEV|0.8.4-armv6l_1||BuildingBlock|20||gtkdialog_DEV-0.8.4-armv6l_1.pet||No description provided|debian|stretch||

Someone has to take look at dir2pet's history to know when thIs line was commented out
[ "`echo "${BASEPKG}" | grep '_DEV'`" != "" ] && ARCHINDEPENDENT='no' #100303

I wonder if this has something to do with #843

the damage is already done. but i believe we have to fix pkgs, of course this is something tedious..

_DEV pkgs shouldn't be found first.

**Comment by woodenshoe-wi** [comment]
The idea with ab0324b was that if the _DEV pkg was found first but the full pkg also existed findpkgs would ignore the _DEV pkg and keep looking.

This would not need any pets to be fixed, and since the part of findpkgs that looks for _DEV only pets was marked with the following comment,  
`#in wary, i have many pkgs that are _DEV only, need to find these, a hack fix to find most...`  
I thought I had found a bug in findpkgs.

I had first made this into a patch so if it wouldn't be appropriate to fix findpkgs in woof-CE it would not be a problem for my builds, but I thought this problem might be affecting other builds.

As for #843 I think findpkgs first looks through all the pet pkg lists in order for an exact match `|raspbian|stretch|`, then starts all over looking though the pet pkg lists for a distro independent pet `|||`, then starts all over again looking for a pet compiled in any version of the compat distro `|raspbian|` and if it still can't find a pet it starts over again looking for any pet `|`.

If you want to use a pet from a specific pkg list I think you have to put it on the end of the line in DISTRO_PKGS_SPECS  
`yes|gtkdialog||exe,dev,doc>dev,nls|pet:jessie`

**Comment by wdlkmpx** [comment]
Ok, open a pull request..

**Comment by woodenshoe-wi** [comment]
Should I close this issue or leave it open for a while so other builders would know a change has been made and can complain if something broke?

**Comment by wdlkmpx** [comment]
Leave open for a while for people to read this important issue. By the
way micko, you should make him a team member

**Comment by woodenshoe-wi** [comment]
Just remember this is my winter time project.  When spring comes I will be too busy to do much work until late fall.

**Comment by woodenshoe-wi** [comment]
@mavrothal 
Does this still needs to be open?

**Comment by woodenshoe-wi** [comment]
Ok, I'll try a different approach.

I opened this issue approximately a year ago, and in the spirit of the 2018 clean up, I'm closing it now.

If someone thinks it shouldn't be closed they can reopen it.
