### ISSUE TITLE
merge2out error

### ISSUE THREAD

**Issue by whetherever** [puppylinux-woof-CE/woof-CE#937]
Receiving the following error while running merge2out in testing branch.

>    Undoing VCS-friendly stuff...
>   ./merge2out: 226: ./merge2out: Syntax error: redirection unexpected

This may be helpful, I'm not sure.
Choices:
Host architecture:     x86_64
Target architecture:   x86
Compatible-distro:     ubuntu
Compat-distro version: xenial

**Comment by wdlkmpx** [comment]
http://stackoverflow.com/questions/2462317/bash-syntax-error-redirection-unexpected

what happens if you change !/bin/sh to #!/bin/bash ?

--

question:
what distro are you using and what version?

**Comment by whetherever** [comment]
That solved it!

 Xubuntu 16.04, for the record.

**Comment by wdlkmpx** [comment]
I have bad news... you'll find many troubles, in fact I think you won't be able to build a puppy.

But you can help fixing this. In puppy we use bashisms in many scripts, specially to speedup processing.. pretty much like a small and limited python/perl.

Besides that, we all build puppies with a Puppy and a Puppy has special stuff. Soo... take a breath and start reporting more issues..

**Comment by whetherever** [comment]
Yes, as I examined the output, I had permissions issues and, of course, no spot user.  I'll switch to a puplet and go from there :)  Thank you for your assistance and direction.

**Comment by wdlkmpx** [comment]
If you get to build the iso, you might want to share it here.. there are people eager to test xenialpup, specially after the latest changes in the pkgs specs...

If you have problems building the iso, share your experience and complaints here.. so we can try to help you.

We're in automatic mode, kind of.

**Comment by whetherever** [comment]
Hi,
I'm working with woof-CE on XenialPup as we speak.  I was wondering if you might explain the PKGS_SPECS_TABLE fields "exe,dev,doc,nls."  In the file there is DISTRO_PKGS_SPECS there is a reference to Barry's blog (http://bkhome.org/blog/?viewDetailed=02414), but I can't seem to access it, even through Google's cache.

**Comment by wdlkmpx** [comment]
yes, i'll write a little doc as i edited scripts. this is something.
meanwhile this should be enough:

|exe,dev,doc,nls|

split PKG into PKG, PKG_DEV, PKG_DOC, PKG_NLS

**Comment by whetherever** [comment]
Thank you!  But, uh, I have no intuition as to what "NLS" designates.  Can you clarify that one?

**Comment by wdlkmpx** [comment]
Haha i was editing what i was writing and ended up activating the Send button.

continuing:
the split pkgs are in packages-xenial/
2createpackages sends processed stuff to that directory

if you specify only |exe|
then the PKG will not be split into _DEV, _DOC, _NLS components

However 3builddistro will delete any doc and nls stuff it finds. Only PKG and PKG_DEV are used to create puppy.sfs and the devx.sfs

i'll write more later.. in a doc..

**Comment by wdlkmpx** [comment]
NLS = Native Language Support... /usr/share/locale , etc

by the way, there's an irc channel i registered on rizon. puppy has its official channel #puppylinux @ freenode .. someone said it's under a tyranny and created #puppyos @ freenode .. but freenode shows your ip, that's why i think it's unsafe.

the secret channel for woofce is: #wce @ irc.rizon.net . You might want to enter with xchat or hexchat or use Rizon's webchat. https://www.rizon.net/chat (Channels: #wce)

**Comment by whetherever** [comment]
The new documentation is very helpful!  Thank you very much!  Also, I have the flu as well, and I admire you for working through it.  I could not get myself out of bed yesterday :)
