### ISSUE TITLE
Pet loading leaving detritus in /root?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#938]
I'm getting a .tar.xz file left in /root after loading a .pet by clicking on it....
Not sure when this started to happen I'm afraid....

**Comment by peabee** [comment]
It happens when the .pet is xz compressed....
![screenshot](https://cloud.githubusercontent.com/assets/5926865/21743774/20f3b28e-d501-11e6-9c98-98201b250057.png)

**Comment by wdlkmpx** [comment]
i think https://github.com/puppylinux-woof-CE/woof-CE/commit/3db60fb3b6d77c45743193fddcc8d6bc4fea55c6 fixes this issue.
