### ISSUE TITLE
findpkgs-dep-helper.c

### ISSUE THREAD

**Issue by woodenshoe-wi** [puppylinux-woof-CE/woof-CE#943]
I have been working on a compiled helper program for findpkgs "Processing dependencies...".
e72fb0f

This is only the source code, but it will build with the rest of the w_apps.

I am not an experienced c programmer, and I think my coding style is strongly influenced by my past projects programming PIC micro controllers in assembly and the bash script `for - in` loops I was copying from findpkgs, so I hope it is understandable.

On my laptop it speeds up ./1download from 10 minutes when it doesn't have to download anything to 4 minutes.

Once it is compiled and placed in woof-out.../support along with findpkgs you have to set the environment variable `USE_FINDPKGS_DEP_HELPER=yes` to enable it.  If it works well for everyone this could later be changed to be enabled by default and use `USE_FINDPKGS_DEP_HELPER=no` to disable it.

When I was testing it I found that it would find 10 more fnd_ok_deps entries than the original script, but I couldn't find anything wrong with my code.  I eventually figured out that in the original script if `DEPNAME` matched one of the aliases in `PKG_NAME_ALIASES` then `aliasPTNS` would be blank instead of having the alias in it and that entry would be skipped.  After I commented out the alias handling in the original script my program gave identical results as long as PKG_NAME_ALIASES was not used.

**Comment by wdlkmpx** [comment]
Well, findpkgs is used basically in all the build scripts. it's triggered everytime you edit the pkgs specs or something changes in the status/ dir.

I never took a close at the pkg dependency check in findpkgs, so i always avoid it hehe. This can certainly be of help. 

Just open a pull request. i'll compile static binaries after i merge it

**Comment by woodenshoe-wi** [comment]
If this works ok, I can try to make a compiled helper program for the findpkgs search function also.

I started with the dependency checking function because it looked simpler and took longer to finish than the two searches.

I figured the rationalize branch was for testing new things and I tested it the best I could so I was hoping others would be willing to test it too.

**Comment by wdlkmpx** [comment]
I'll test it with dpup stretch., i'll add the binaries tomorrow as i'm going to sleep right now

Well findpkgs is a complex script, i think only one pass would be enough, but haven't read it thoroughly...

**Comment by wdlkmpx** [comment]
I get this error:

Error processing file: /tmp/findpkgs_tmp/pet_log1 line: 180 

line 180:
xdg_puppy||xdg_puppy.pet|||Packages-puppy-tahr-official|

It's an unsual entry... no version..

**Comment by wdlkmpx** [comment]
Making pkg version optional i see a huge speedup. It would take long minutes, but now it takes like 2 seconds. I sped up the original a script a bit, but only the search_func trying to produce the same output. i'm not sure about the dep stuff, but if this works as expected then it surely is a great improvement.

**Comment by woodenshoe-wi** [comment]
Good point, it should only be a problem if a pkg requests a specific version of a dependency that has no version information.  Packages that don't have versions should be supported.

Issued pull request #946

**Comment by wdlkmpx** [comment]
It might be a good idea to create a compiled binary for the search function.. for debian/ubuntu puppies. I have my reservations regarding the design, i think it can be simplified, but it needs collaboration and some talk, in other words it's not going to happen. but if you're willing to do it, then it's good...

I think the deb-helper is really fast, so it doesn't really need to output the pkg names, i see more delay in printing those strings.

By the way, how accurate are the words for this vid?  https://www.youtube.com/watch?v=uBlFxymx0j0
words: http://pastebin.com/B7iMA51w

**Comment by woodenshoe-wi** [comment]
A little off topic I guess, but I think line 7 should read  
`I call your name out in the raging wind`

And I think line 15 should read. 
`A prisoner to my own dreams`

I think line 24 should read  
`I'll chase my dreams, i will not give up`  
That is a capital "i" with two lowercase "L"s, the contracted form of "I will"

I think line 34 should read  
`The thoughts of you lift me beyond the clouds`

Just as a matter of grammar, in English "I" and "I'm" always start with a capital letter.

Back on topic, when I was working on the dep-helper program I wanted it to have identical output compared to the original script.

If it is okay to base it on the current script I can see what I can do, but if there are plans to change the script in the near future it would be easier to wait until after the changes to the script are finished.

For debugging purposes I want to keep any compiled helper programs and the original script in sync.

**Comment by woodenshoe-wi** [comment]
I did some speed tests with and without printing the dependency names and I could only get more than a fraction of a second difference by running it on my pi1.  The output is buffered and doesn't seem to slow the program down much at all.

If you don't want it cluttering up the console, just comment out the printf statement at line 453, but don't expect it to run much faster.



--- on laptop ---

time ./findpkgs-dep-helper_old compat_log1 pet_log1
...
real	0m3.597s
user	0m3.233s
sys	0m0.013s

time ./findpkgs-dep-helper_new compat_log1 pet_log1 
real	0m3.229s
user	0m3.197s
sys	0m0.010s


--- on pi3 ---

time ./findpkgs-dep-helper_old compat_log1 pet_log1
...
real	0m9.646s
user	0m9.500s
sys	0m0.030s

time ./findpkgs-dep-helper_new compat_log1 pet_log1
real	0m9.347s
user	0m9.290s
sys	0m0.020s


--- on pi1 ---

time ./findpkgs-dep-helper_old compat_log1 pet_log1
...
real	0m20.209s
user	0m17.370s
sys	0m0.060s

time ./findpkgs-dep-helper_new compat_log1 pet_log1
real	0m17.623s
user	0m17.230s
sys	0m0.050s

**Comment by wdlkmpx** [comment]
Thanks.

Yes, it's okay to base it on the current script... I won't change anything, unless there is something to fix

**Comment by wdlkmpx** [comment]
I always get the same missing deps in both passes.. what do you think of the second pass? what does it exactly do? is it possible to get rid of it without 'side effects'?

**Comment by woodenshoe-wi** [comment]
It turned into quite a project, but I think I finished the findpkgs search helper program.  #954 

I also added a --verbose flag to the dep helper so you can choose if you want it to print output without having to make changes to the source code and recompile.

If it is still too slow, if you are not processing the dependencies anyway, maybe you could skip the first search because it is what generates the input files for the dependency processing.  The second search is what generates the findpkgs-FINAL_PKGS file.

I don't think skipping the first search would cause any new side effects that skipping the dependency processing isn't causing already.

**Comment by wdlkmpx** [comment]
Yeah it's faster. It works fine for debian stretch, this will certainly make me update stuff.

You might want to test this in tahrpup (don't download anything), slacko (any version) [./0setup and ./support/findpkgs], and see the diffs. If it's ok... you might want to compile the static apps yourself:

In a 64bit puppy: load the devx.sfs, go to the initrd-progs directory and type
./build.sh w  
(will download toolchains from landley.net)

The result is w_apps_static-xxxxxxxx.tar.xz
extract that file and copy findpkgs-dep-helper and findpkgs-search-helper to

woof-arch/arm/build/support
woof-arch/x86/build/support
woof-arch/x86_64/build/support

and then open a pull request.. (I would do this myself but...)

**Comment by woodenshoe-wi** [comment]
I already had tested them the way you described, and I am glad I did because I did find a typo in my code where I was mixing up the DOC and NLS pets.

I was able to fix all the problems I found except some pets compiled in april have an extra '|' character on the end of the db entries which shows up in the diffs but shouldn't cause any trouble.

I did find two entries that were different,
in slackware64 14.2 the original script gives

:grub4dos:|pet|Packages-puppy-slacko6414.1-official|grub4dos-0.4.4.v1.9|grub4dos|0.4.4.v1.9||System|464K||grub4dos-0.4.4.v1.9.pet||Grub4Dos bootloader config||14.0||

but the new compiled programs give

:grub4dos:|pet|Packages-puppy-noarch-official|grub4dos-0.4.4.v1.9.2-2|grub4dos|0.4.4.v1.9.2-2||Setup|464K||grub4dos-0.4.4.v1.9.2-2.pet||Grub4Dos bootloader config|slackware64|14.1||

I figured out that the original script was mistaking it's entry for a 'no arch' pet because the compiled in distro name is blank, but because my programs go by fields instead of grepping for '|||' they got it right.

The other difference was in my raspbian build, the original script would include both  

:xarchive:|pet|Packages-puppy-armv6-official|xarchive-0.2.8.6.i18n-armv6|xarchive|0.2.8.6.i18n-armv6||Setup|212K||xarchive-0.2.8.6.i18n-armv6.pet|+gtk+|XArchive archiver, internationalised by rodin.s|puppy|||  

and

:xarchive:|pet|Packages-puppy-armv6-official|xarchive_DOC-0.2.8-6-i18n-armv6|xarchive_DOC|0.2.8-6-i18n-armv6||Setup|76K||xarchive_DOC-0.2.8-6-i18n-armv6.pet||archive manager||||

but my programs leave out the DOC pet.  If you look at the version of the DOC pet it has two '-' where the main pet has '.'

The original script uses regular expressions so a '.' matches any character but my program uses strcmp() for checking that the version matches.

**Comment by woodenshoe-wi** [comment]
@mavrothal 
Does this still needs to be open?

**Comment by woodenshoe-wi** [comment]
Ok, I'll try a different approach.

I opened this issue approximately a year ago, and in the spirit of the 2018 clean up, I'm closing it now.

If someone thinks it shouldn't be closed they can reopen it.
