### ISSUE TITLE
Help request....keyboard problem in Slackware Current

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#945]
Slackware Current has just changed to using libinput and xf86-input-libinput - see below
A test build of LxPupSc with these new components is working quite well apart from the up-arrow and print-screen buttons on my keyboard....
The up-arrow button activates print-screen instead of going up
The print-screen button doesn't do anything anymore

I vaguely remember seeing something about this before, but am unable to find the discussion and google has not come to my help either. Presumably its something to do with xorg.conf etc.

Can anybody give me any clues what to change and where? Thanks PeeBee

`x/libinput-1.5.4-i586-1.txz:  Added.
x/libwacom-0.22-i586-1.txz:  Added.
  This is needed for libinput.
x/xf86-input-libinput-0.23.0-i586-1.txz:  Added.
  This is the new generic X.Org input driver which replaces evdev for most
  purposes.  It does not (for now) replace xf86-input-synaptics or
  xf86-input-vmmouse.  If this driver package is missing then X will fall
  back to using xf86-input-evdev as before.
x/xorg-server-1.19.1-i586-2.txz:  Rebuilt.
  Rename 90-keyboard-layout.conf to 90-keyboard-layout-evdev.conf.`

**Comment by wdlkmpx** [comment]
Upload the iso or interim delta... www.datafilehost.com is a good option

For example: 

An anonymous user provided me this slacko iso pointing out an error in the drive icon labels: wrong filesystem (ext2) for ext3 partitions.

https://www.datafilehost.com/d/f5907521 (slacko 2017-01-17) 

Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/4c48ec84d6eb7199f6f8881ee2548d78f352dcb3  fixes this...

**Comment by peabee** [comment]
Many thanks....
http://smokey01.com/peebee/downloads/test/LxPupSc-17.01.26.iso
md5= f4dc11ba4ee7055df49c13c14742bfc0

**Comment by wdlkmpx** [comment]
The problem was in some openbox keybindings, the same problem i had with jwm. 

I updated the files in /root/.config/openbox. it's picking rc.xml .. i updated both xml files with the same keybindings that can be found in /root/.jwm/jwmrc-personal . it's way more awesome with all those key bindings..

https://www.datafilehost.com/d/147e2db0

**Comment by wdlkmpx** [comment]
By the way, the fixed openbox files are here https://www.datafilehost.com/d/147e2db0 just in case you think i fixed those files in woof... they're not in woof.

**Comment by peabee** [comment]
Very many thanks - tested as a ydrv "patch" and all looks good.
I thought I recalled that you had encountered a similar problem previously - I should have found the cause myself but you could do it so much faster.....
