### ISSUE TITLE
patch init to provide accurate detection of savefiles

### ISSUE THREAD

**Issue by gyrog** [puppylinux-woof-CE/woof-CE#952]
Which is the currently recommended puppy for testing the latest initrd.gz in the testing branch?
I don't have any installed puppy using the latest initrd.gz from the testing branch.
While the code is tested, it's not tested using the latest.
I could push it to rationalise, perhaps?

The curent code in init for detecting savefiles, can easily produce false positives, e.g. "tahrsave.sfs".
The patched code should elimate, hopefully, all chance of false positives.
The patch is supposed to support the new savefile/savefolder backup facility.

**Comment by wdlkmpx** [comment]
The latest version of lxPupSc is usually up-to-date. 

SE uploaded a new build yesterday (using slackware 14.1)
https://my.pcloud.com/publink/show?code=XZqxvKZDessIkyS4mBseOmKyjCb448qby8V

In any case you can always use any fairly recent iso, extract initrd.gz replace the init script with the one from testing, edit accordingly, test and push changes.

**Comment by gyrog** [comment]
@wdlkmpx,
Thanks, I'll use the initrd.gz from the lxPupSc iso you mentioned, if I need to.
But I might see what I can do with your "http://01micko.com/wdlkmpx/woof-CE/initrd_progs-20170114-static.tar.xz" first.
Try something new.

**Comment by wdlkmpx** [comment]
Thinking about all the changes I made...

The base name is requirement ${DISTRO_FILE_PREFIX} (this is the standard)

A valid savefolder is basically any folder.
A valid savefile is any file containing *.3fs* *.2fs* *.4fs* (Pupsave Backup)

The good thing about the new init, is that it continues after encountering a fake or invalid savefile (in PUPMODE 5). And with all the recent debug messages I added, people will know what exactly is happening after an error (there are 60 seconds to read before init continues)...

I figured out you will find a partial or full fix by now..
