### ISSUE TITLE
init script - decode_spec() code, rework

### ISSUE THREAD

**Issue by gyrog** [puppylinux-woof-CE/woof-CE#958]
I'm working on a "How to" document which will result in a patched README file, and reworked code in the decode_spec function that obviously implements what's in the documentation.
I have attached my first draft of this document.
[file_spec_boot_params.txt](https://github.com/puppylinux-woof-CE/woof-CE/files/754445/file_spec_boot_params.txt)
I have one unresolved issue:
What should the spec mean "psave=:lxpupsc/", i.e. specifying a path without a leading "/"?
It can mean the same as "psave=:/lxpupsc/", so the missing "/" is prepended.
Or, it can mean it's a sunbirectory of psubdir, so $PSUBDIR is prepended.

Any thoughts?

I'm currently leaning towards prepending a "/", since this is consistent with what happens to the "psubdir=" parameter.

**Comment by wdlkmpx** [comment]
Hmm psave=:lxpupsc/ should probably mean a mistake.. i think only full paths should be accepted, but it's up to you.

Just make sure to add many examples to clarify any doubts.. if people don't understand the param description, they will definitely understand the examples. Also, examples of bad syntax, so every possible case is covered..

**Comment by gyrog** [comment]
@wdlkmpx,
Thanks for the imput.
I'm going to go with inserting the missing "/" for now.
It's a single line of code that could easily be replaced later, if deemed desirable.
