### ISSUE TITLE
PPM anomaly

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#959]
From @Billtoo
LxPupSc-17.02.1
BUILD_FROM_WOOF='testing;f4e45ee;2017-01-31 19:45:44 +0800'
Entry in Packages-slackware-14.2-official =
> kpat-4.14.3|kpat|4.14.3|2|Fun|3460K|slackware/kde|kpat-4.14.3-i586-2.txz|+acl,+attica,+attr,+bzip2,+dbus,+eudev,+expat,+flac,+fontconfig,+freetype,+gamin,+gcc,+gcc-g++,+glib2,+harfbuzz,+json-c,+kdelibs,+libICE,+libSM,+libX11,+libXau,+libXcursor,+libXdmcp,+libXext,+libXfixes,+libXft,+libXi,+libXpm,+libXrender,+libXtst,+libasyncns,+libcap,+libdbusmenu-qt,+libffi,+libkdegames,+libogg,+libpng,+libsndfile,+libvorbis,+libxcb,+libxml2,+phonon,+pulseaudio,+qca,+qt,+soprano,+strigi,+util-linux,+xz,+zlib|patience card game for KDE|slackware|current||

Pristine frugal install without savefolder - PPM identifies 32 dependencies for kpat as shown below**....
Reboot, creating savefolder - PPM now identifies only 31 dependecies for kpat - libtool is no longer identified as a dependancy. Packages-slackware-14.2-official has not changed (md5sum check)

** 32 dependencies:
attica-0.4.2
clucene-2.3.3.4
fftw-3.3.4
gst-plugins-base-1.6.4
gstreamer-1.6.4
ilmbase-2.2.0
jemalloc-3.6.0
json-c-0.12
judy-1.0.5
kdelibs-4.14.21
libaio-0.3.109
libasyncns-0.8
libiodbc-3.52.10
libkdegames-4.14.3
libtool-2.4.6                **** this is missing after savefolder creation
mariadb-10.0.29
mhash-0.9.9.9
openexr-2.2.0
phonon-4.8.3
polkit-qt-1-0.103.0
pulseaudio-9.0
qca-2.1.1
qt-4.8.7
raptor2-2.0.15
rasqal-0.9.30
redland-1.0.16
sbc-1.3
soprano-2.9.4
speexdsp-1.2rc3
strigi-0.7.8
utempter-1.1.6

**Comment by mavrothal** [comment]
The problem is the [INSTALLED_PATTERNS_GEN](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/local/petget/pkg_chooser.sh#L265) variable.
It mistakenly identifies  that devx is loaded when puppy is installed and includes packages from devx. Thus libtool that is in devx is (inappropriately) excluded.
