### ISSUE TITLE
Version update fails without functions4puppy4

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#973]
The removal of functions4puppy4 in 392bf5c5 results in a output freeze (the process proceeds) during version update. What appears to fail is /bin/mount with mount-FULL returning "unknown error".
A temp work around is implemented in  63859a4 but a proper fix is needed.

**Comment by mavrothal** [comment]
Bit more info. 
initrd/Init appears ok 
(I only get the complain 
 ```
cp -a -n /lib/consolefonts/LatArCyrHeb-16.psfu.gz /lib/consolefonts/LatGrkCyr-8x16.psfu.gz /lib/consolefonts/lat1-12.psfu.gz /lib/consolefonts/lat2-12.psfu.gz /lib/consolefonts/ter-u16n.psf.gz /pup_new/lib/consolefonts/
cp: unrecognized option: n
```  
but this is independent of the freeze)
Then rc.sysinit fails to mount dev or anything else.
```
echo -n Making the filesystem usable...
 mount -t devtmpfs devtmpfs /dev
 [ ! -e /dev/loop ]
 mkdir -p /dev/loop
 ls /dev/loop[0-9]*
 read i
 sed s|/dev/loop||
ls: cannot access '/dev/loop[0-9]*': No such file or directory
 mount -t proc none /proc
/bin/mount: line 23: /etc/rc.d/functions4puppy4: No such file or directory
 STATUS=1
```
and over at /bin/mount we have
```
'[' '!' ']'
 exec busybox mount
mount: no /proc/mounts
 '[' '!' ']'
 exec busybox mount
mount: no /proc/mounts
 '[' '!' /dev/sdb1 ']'
 MYPID=4807
 . /usr/local/pup_event/frontend_funcs
```
Why all these do not happen when a *blank* /etc/rc.d/functions4puppy4 file is present, is a mystery...
I have a hunch that may be related with the initrd/init $PCLEAN call, but not sure how.

**Comment by wdlkmpx** [comment]
You should remove the -n (unknown cp param) then.

I don't how see how the functions4puppy4 error can occur

**Comment by mavrothal** [comment]
Well.... I found it.
In updates the /bin/mount (and unmount) used is the one present in the save folder/file.
This is still calling functions4puppy4, hence the crash.
I guess we need to add a condition in the initrd/init $PCLEAN to remove those too if they have functions4puppy4. Or just clean them no matter what.
You may want to clean other scripts that call functions4puppy4 and may be present in the savefile

**Comment by mavrothal** [comment]
...Or just leave the dummy functions4puppy4 file in.

**Comment by mavrothal** [comment]
And here is a list of old version of woof files that are not "cleaned'  and have a call to functions4puppy4
```
woof-code/rootfs-skeleton/bin/mount
woof-code/rootfs-skeleton/bin/umount
woof-code/rootfs-skeleton/usr/local/pup_event/frontend_change
woof-code/rootfs-skeleton/usr/local/pup_event/frontend_funcs
woof-code/rootfs-skeleton/usr/local/pup_event/frontend_startup
woof-code/rootfs-skeleton/usr/local/pup_event/frontend_timeout
woof-code/rootfs-skeleton/usr/sbin/pmount
woof-code/rootfs-skeleton/usr/sbin/pupscan
```
Hopefully there are no "common" pets that also call functions4puppy4 and may need updating (could not find anything else in Xenial pup)

**Comment by mavrothal** [comment]
121e2073 should fix this
