### ISSUE TITLE
functions4puppy

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#983]
i've noticed that /etc/rc.d/functions4puppy starts with #!/bin/sh but isn't executable.
is it meant to be executable?

**Comment by ninaholic** [comment]
I notice _00func is the same too. They both seem to be called as added library or resource and not as standalone scripts, but they both contain "functions". Do the functions still work if the #!/bin/sh line is trimmed? :scissors: :haircut_man: :haircut_woman:

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/etc/rc.d/rc.shutdown#L42
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/3builddistro-Z#L15

**Comment by 01micko** [comment]
> Do the functions still work if the #!/bin/sh line is trimmed? ✂️ 💇‍♂️ 💇

Yes. I believe it is only there for syntax highlighting in geany.

**Comment by ninaholic** [comment]
Thanks @01micko ! Now it all makes sense :)
