### ISSUE TITLE
BUILD_FROM_WOOF= not overwritten on merge2out

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#988]
Line:
BUILD_FROM_WOOF=
should be overwritten in /etc/DISTRO_SPECS
every time merge2out is run
currently the line is not updated if it exists and systems are produced with incorrect status info

**Comment by wdlkmpx** [comment]
I can't reproduce the issue..

1.
BUILD_FROM_WOOF='testing;c4c170dd;2017-04-03 14:53:11 +0800'

2.
BUILD_FROM_WOOF='testing;de7daba3;2017-04-05 14:53:03 +0100'

**Comment by peabee** [comment]
The situation arises if the DISTRO_SPECS in woof-CE/woof-distro is updated prior to merge2out  with a version from woof-out_ which already has a BUILD_FROM_WOOF= line in it.

i.e. the DISTRO_SPECS in woof-out_ is different to the DISTRO_SPECS in woof-CE/woof-distro by the addition of the BUILD_FROM_WOOF= line.

To test, try adding a modified BUILD_FROM_WOOF= line to the DISTRO_SPECS in woof-CE/woof-distro and then do merge2out - the modified BUILD_FROM_WOOF= line will not be overwritten....

**Comment by peabee** [comment]
Closed after further testing - sorry!
