### ISSUE TITLE
merge2out should delete noarch

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#997]
`Packages-puppy-noarch-official` is no longer part of woof. It's downloaded in `0setup`. Should be deleted by `merge2out` to save getting the silly red message all the time after updating your tree and running `./0setup`.

**Comment by wdlkmpx** [comment]
The main pkg dbs for slackware 14.0 x86_64 (local & online) are quite different from each other. the one at ibiblio is unusable, so i added a new variable for fix-puppy-dbs to ignore all local-only dbs:

PKGS_DOCS_PET_REPOS_LOCAL_ONLY="Packages-puppy-${DISTRO_DB_SUBNAME}-official"

Maybe 0setup should delete ```Packages-puppy-noarch-official``` before calling fix-puppy-dbs..
