### ISSUE TITLE
Should 'Puppy Standard' icons be in rootfs-packages?

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#998]
In #925 @mrfricks suggested maybe adding puppy_icon_theme (a.k.a. "Puppy Standard")  to `rootfs-packages`.

I don't mind either way but I would like some feedback on this idea.

I'm also sitting on another theme more or less based on "Puppy Standard" but is unique in its own right.

Sneak peek...

![icns](https://cloud.githubusercontent.com/assets/1019119/25067126/84615898-227d-11e7-8a5a-f4ca1d422651.png)

**Comment by zigbert** [comment]
rootfs-packages sounds reasonable to me... What I would like to see, is the Puppy Standard theme as the fallback theme instead of Hicolor. Removing Hicolor would be a space-saver since it contains raster graphics.

If I got it right, Hicolor is bundled with the gtk package, but I guess a pinstall.sh in the Puppy Standard pack could solve this... It would of course require Puppy Standard to be installed after libgtk, and that might be an issue if placed in rootfs-packages?
```
# du -s /usr/share/icons/hicolor/
15216	/usr/share/icons/hicolor/
# du -s /usr/share/icons/Puppy\ Standard/
1552	/usr/share/icons/Puppy Standard/
```

**Comment by 01micko** [comment]
@zigbert 

> If I got it right, Hicolor is bundled with the gtk package

No, not exactly. In fact it isn't even a theme at all.

This is Pat Volkerding's (Slackware maintainer) comments in the doinst.sh (slack equivalent of pinstall.sh)

```shell
# Since the use of icon caching is optional, and has to be kept in sync
# somehow (like a "registry" through a cron job, or whatever, I tend to
# think the user should be the one to choose if they really want to set
# this up or not:
 
# Using an absolute path (/usr/bin/gtk-update-icon-cache) will make
# this script function only on a running system.  Otherwise an end-of-
# install script will take care of this job.

# Don't make a global cache in /usr/share/icons.  Not only is it huge,
# but it causes problems if it isn't constantly updated.
# |>@&^^ registries...  ;-)
#
# /usr/share/icons isn't really a "theme" anyway and shouldn't have a
# icon-theme.cache file there.
#
# If there already is a global cache, rm it:
rm -f usr/share/icons/icon-theme.cache

# Update hicolor theme cache:
if [ -d usr/share/icons/hicolor ]; then
  if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then # ONLY run this if there's already a cache!!!
    if [ -x /usr/bin/gtk-update-icon-cache ]; then
      chroot . /usr/bin/gtk-update-icon-cache -f -t usr/share/icons/hicolor 1> /dev/null 2> /dev/null
    fi
  fi
fi
```

The actual theme is a bunch of empty directories; look at this.. (in my woof tree I unpacked it)
```
# pwd
/mnt/sda6/00_new-woof/local-repositories/x86_64/packages-tgz_txz-14.2/usr/share/icons
# find . -type f
./hicolor/index.theme
# find . -type d | wc -l
368

```

The bloat comes from genie, firefox and friends storing there icons in there by default, which by the way is recommended practice by [freedesktop](https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout]), so we invite problems by getting rid of it, however, if the icons for genie, firefox etc are added to "Puppy Standard" and new "[Puppy Flat](https://github.com/puppylinux-woof-CE/puppy_flat_theme)" then we can limit the bloat somewhat.

> *In order to have a place for third party applications to install their icons there should always exist a theme called "hicolor" [1]. The data for the hicolor theme is available for download at: http://www.freedesktop.org/software/icon-theme/. Implementations are required to look in the "hicolor" theme if an icon was not found in the current theme.*

**Comment by 01micko** [comment]
After some consideration, I've decided to keep these as pets in `noarch` as it is probably easier to upgrade, rebuild (petbuild) and upload.
